import { MindTopicDetail, MindLanguageCode } from '../types';

/**
 * Mentalab Mind — Cognitive Biases Track
 * Topic: Belief Perseverance: Clinging to Discredited Beliefs
 * Category: Cognitive Biases (cognitive_biases)
 * 
 * Academic Grounding:
 * - Ross, L., Lepper, M. R., & Hubbard, M. (1975): Perseverance in self-perception and social perception. Journal of Personality and Social Psychology.
 * - Anderson, C. A., Lepper, M. R., & Ross, L. (1980): Perseverance of social theories: The role of explanation in the persistence of discredited information.
 * - Nyhan, B., & Reifler, J. (2010): When corrections fail: The backfire effect. Political Behavior.
 */

export const TOPIC_BELIEF_PERSEVERANCE_EN: MindTopicDetail = {
  id: 'belief_perseverance',
  categoryId: 'cognitive_biases',
  slug: 'belief-perseverance',
  difficulty: 'intermediate',
  estimatedReadingMinutes: 5,
  scientificConsensusTier: 'established',
  sortWeight: 21,
  viewCount: 6940,
  shareCount: 510,
  bookmarkCount: 1140,
  title: 'Belief Perseverance: Clinging to Discredited Beliefs',
  subtitle: 'The psychological refusal to abandon an initial belief even after the evidence supporting it has been completely debunked.',
  shortDescription: 'A cognitive bias where a person continues to maintain a belief despite being presented with undeniable, conclusive evidence that refutes the initial basis for that belief.',
  oneLineExplanation: 'Finding out the headline was fake news, but continuing to believe the rumor anyway.',

  summary30s: 'Discovered in 1975 by Lee Ross, Mark Lepper, and Michael Hubbard at Stanford University, Belief Perseverance explains why myths die so hard. Once our brain constructs causal explanations to support an idea, those explanations take on a life of their own. Even when the original source is definitively proven fraudulent, the secondary causal web remains intact.',

  coreConcept: 'Belief Perseverance demonstrates that human beliefs are not stored as isolated data points, but as interconnected causal networks. When you adopt a claim (e.g. "Candidate X is corrupt"), your brain immediately searches memory for corroborating stories and plausible explanations. If someone proves the initial claim was a total fabrication, the supporting stories you generated still feel intuitively true.',
  summary60s: 'In Ross and Lepper\'s seminal Stanford study, participants read suicide notes and guessed which ones were genuine. Experimenters provided fake feedback: some were told they had an extraordinary 95% accuracy rate, while others were told they scored poorly. Afterward, the experimenters completely debriefed the participants, showing them that the feedback was generated by random coin flips and had zero relation to their real ability. Despite knowing the feedback was 100% fake, participants who received high scores still rated their intuitive ability as exceptionally high. The belief survived the destruction of its evidence.',

  quickTakeaways: [
    'Self-Sustaining Causal Webs: The explanations we invent to justify a belief survive the death of the original evidence',
    'The Debunking Paradox: Merely proving a rumor false rarely changes minds; people cling to the emotional narrative',
    'The Counter-Explanation Antidote: To dismantle an entrenched belief, you must actively generate explanations for the OPPOSITE premise',
    'Identity Entanglement: Beliefs tied to personal identity, religion, or political tribe are nearly impervious to raw facts',
  ],

  whyItHappens: 'Cognitive conservation and narrative generation. The brain creates causal explanations to make sense of information; tearing down that internal structure creates painful cognitive dissonance.',
  evolutionaryMechanism: 'Constantly oscillating beliefs with every new rumor created tribal instability. Consistent worldview alignment was far more valuable for group cohesion than hyper-agile factual updates.',

  howItWorks: 'Three phases: (1) Exposure: An individual hears a claim; (2) Causal Elaboration: The brain invents reasons why it makes sense; (3) Discredit Immunity: When the claim is refuted, the elaborated reasons maintain the conviction.',
  whereYouEncounterIt: 'Debunked conspiracy theories, medical misinformation (discredited vaccine-autism claims), brand loyalty, and political smear campaigns.',

  visualExplanation: {
    type: 'contrast_matrix',
    visualConceptType: 'comparison_matrix',
    headline: 'Evidence Discreditation vs. Belief Survival',
    description: 'Why destroying the foundation does not collapse the psychological house.',
    analogySideA: {
      label: 'Logical Deduction Model',
      detail: 'If Premise A is proven false, Conclusion B is instantly and automatically discarded.',
    },
    analogySideB: {
      label: 'Belief Perseverance Reality',
      detail: 'Even after Premise A is proven fraudulent, Conclusion B remains supported by secondary rationalizations.',
    },
  },

  researchSummary: 'Anderson, Lepper, & Ross (1980) had participants write explanations for why risk-preferring individuals make better firefighters. Even after being told that the case studies were fictional fabrications created for the experiment, participants continued to strongly insist that risk-taking is essential for firefighting.',
  limitationsAndControversies: 'The "Backfire Effect" Nuance: While early studies suggested corrections could make people double down on false beliefs, recent large-scale political science replications (Wood & Porter, 2019) show that factual corrections DO generally reduce factual inaccuracy, though emotional attitudes linger.',
  commonMisconceptions: 'Common myth: "Showing people fact-check links will immediately change their minds." Reality: Direct fact-checks often trigger defensive emotional pushback unless paired with an alternative, coherent causal narrative.',

  howToRecognize: [
    'Hearing that a sensational WhatsApp forward was completely fake, but thinking: "Well, even if that specific story is false, the general point is still true"',
    'Continuing to distrust a colleague even after proof arrives that an allegation against them was a malicious lie',
    'Refusing to sell a collapsed stock because you still believe the startup\'s original marketing promises from 3 years ago',
    'Feeling angry when authoritative evidence disproves a rumor you enjoyed sharing with friends',
  ],

  scenarios: [
    {
      id: 'scen_bel_01',
      scenarioType: 'indian_context',
      title: 'The WhatsApp Land Grab Rumor in Bhopal',
      vignette: 'Sunil receives a viral WhatsApp forward in Bhopal warning that a nearby community park is being sold to a private real estate builder by corrupt municipal officials. Sunil becomes furious, attends a protest rally, and posts angry Facebook updates. Two days later, the municipal commissioner holds a live press conference with land deeds, proving that the park is legally protected and that the rumor was created by a blacklisted contractor. Sunil reads the official clarification, but mutters to his neighbor: "Well, maybe they didn\'t sell it this week, but government officials are all corrupt anyway. They definitely tried to sell it behind closed doors."',
      breakdownAnalysis: 'Sunil exhibited textbook Belief Perseverance. The complete factual destruction of the original claim did not alter his belief. His brain had already generated a broader causal narrative of government corruption, which easily survived the discreditation of the specific spark.',
      recommendedAction: 'Apply Counter-Explanation: Actively force yourself to brainstorm: "What are 3 legitimate, non-malicious reasons why this rumor was spread?" Generating explanations for the opposite premise neutralizes perseverance.',
    },
  ],

  examples: [
    {
      id: 'ex_bel_01',
      domain: 'health',
      displayOrder: 1,
      title: 'The Wakefield Autism Retraction',
      description: 'In 1998, Andrew Wakefield published a fraudulent paper linking vaccines to autism. The paper was fully retracted by The Lancet and Wakefield lost his medical license. Yet decades later, millions still cling to the myth because the causal narrative was emotionally sticky.',
      takeaway: 'Discrediting data does not erase the emotional narrative that accompanied it.',
    },
  ],

  practiceQuestions: [
    {
      id: 'pq_bel_01',
      scenarioContext: 'An internal company audit accuses a department manager of embezzling ₹10,00,000 based on an accounting spreadsheet. The entire office hears about it. Three days later, forensic auditors discover that the discrepancy was an automated double-entry software bug, and the manager is completely exonerated with an official apology from the CEO.',
      question: 'Which employee reaction demonstrates Belief Perseverance?',
      prompt: 'Which employee reaction demonstrates Belief Perseverance?',
      scenarioText: 'An internal company audit accuses a department manager of embezzling ₹10,00,000 based on an accounting spreadsheet. The entire office hears about it. Three days later, forensic auditors discover that the discrepancy was an automated double-entry software bug, and the manager is completely exonerated with an official apology from the CEO.',
      options: [
        {
          id: 'opt_a',
          label: 'A',
          text: '"Where there is smoke, there must be fire. Even if the spreadsheet had a bug, I still don\'t trust him with our budget."',
          explanation: 'Accurate: clinging to suspicion and inventing vague rationalizations after the factual basis has been 100% debunked is the classic hallmark of belief perseverance.',
          isCorrect: true,
        },
        {
          id: 'opt_b',
          label: 'B',
          text: '"The forensic audit clearly disproved the allegation, so I completely restore my trust in the manager."',
          explanation: 'This represents rational, evidence-based Bayesian updating.',
          isCorrect: false,
        },
        {
          id: 'opt_c',
          label: 'C',
          text: '"We should upgrade our accounting software to prevent automated double-entry bugs."',
          explanation: 'This is operational problem-solving, not a cognitive distortion.',
          isCorrect: false,
        },
      ],
      correctAnswerId: 'opt_a',
      cognitiveTakeaway: 'When evidence collapses, emotional suspicion frequently invents new ad-hoc justifications to survive.',
      difficulty: 'easy',
    },
  ],

  howToRespond: 'Construct an alternative coherent causal narrative and practice counter-explanation.',
  psychologicalDefenses: [
    {
      title: 'Counter-Explanation Exercise',
      instruction: 'Whenever evidence discredits your belief, spend 2 minutes deliberately writing down reasons why the OPPOSITE conclusion is true and healthy.',
    },
    {
      title: 'Replace, Don\'t Just Erase',
      instruction: 'You cannot simply delete a false belief; you must replace it with a more accurate, equally coherent alternative explanation of what actually occurred.',
    },
  ],

  reflectionPrompt: 'Has someone ever proven to you with undeniable facts that a rumor was false, yet you still felt an intuitive lingering suspicion?',
  references: [
    {
      id: 'ref_bel_01',
      title: 'Perseverance in self-perception and social perception',
      citation: 'Ross, L., Lepper, M. R., & Hubbard, M. (1975). Journal of Personality and Social Psychology, 32(5), 880–892.',
      authors: 'Lee Ross, Mark R. Lepper, Michael Hubbard',
      publicationYear: 1975,
      journalOrPublisher: 'Journal of Personality and Social Psychology',
      sourceType: 'peer_reviewed_journal',
      evidenceStrength: 'peer_reviewed_experimental',
      doiOrUrl: 'https://doi.org/10.1037/0022-3514.32.5.880',
      relevance: 'The foundational experimental study establishing that debriefed participants maintain beliefs created by fake feedback.',
      displayOrder: 1,
    },
  ],
  tags: ['Cognitive Biases', 'Belief Perseverance', 'Misinformation', 'Critical Thinking'],
  relatedTopics: [
    { topicId: 'confirmation_bias', slug: 'confirmation-bias', title: 'Confirmation Bias', relationshipType: 'amplified_by' },
    { topicId: 'bias_blind_spot', slug: 'bias-blind-spot', title: 'Bias Blind Spot', relationshipType: 'amplified_by' },
  ],
  seoTitle: 'Belief Perseverance: Why Fake News & Myths Never Die | Mentalab Mind',
  seoDescription: 'Why humans cling to false beliefs even after the evidence is completely debunked. Learn the science of counter-explanation and narrative replacement.',
  canonicalUrl: '/mind/cognitive-biases/belief-perseverance',
  ogImageUrl: '/images/mind/belief-perseverance.png',
  publishedAt: '2026-09-27T00:00:00Z',
  deepExplanation: 'Belief perseverance is the cognitive maintenance of hypotheses after disconfirmation of evidentiary premises via causal elaboration.',
};

export const TOPIC_BELIEF_PERSEVERANCE_HINGLISH: MindTopicDetail = {
  ...TOPIC_BELIEF_PERSEVERANCE_EN,
  title: 'Belief Perseverance: Saboot Jhootha Saabit Hone Par Bhi Yakeen Na Chhodna',
  subtitle: 'Pata chal gaya ki khabar fake news thi, fir bhi dimaag usi jhooth ko sach maanta rehta hai.',
  shortDescription: 'Ek aisi cognitive bias jisme kisi claim ka base poori tarah jhootha saabit hone ke baad bhi insaan us purane vishwas ko chhodne ko tayyar nahi hota.',
  oneLineExplanation: 'Pata chal gaya ki rumor fake tha, par dimaag bolta hai: "Kuch toh gadbad zaroor hogi."',

  summary30s: '1975 me Stanford University ke Lee Ross aur Mark Lepper ne Belief Perseverance discover kiya tha. Jab hum kisi afwah par yakeen kar lete hain, toh humara dimaag uske piche hazaron dimaagi kahaniyan jod leta hai. Baad me jab saabit ho jata hai ki wo khabar 100% fake thi, tab bhi wo jodhi hui dimaagi kahaniyan zinda rehti hain aur vishwas khatam nahi hota.',
  coreConcept: 'Dimaag me vishwas akela nahi rehta, wo ek jaal ki tarah jud jata hai. Agar aap sunte hain ki "Sharma ji beimaan hain", toh dimaag unke purane behavior ko negative lens se dekhne lagta hai. Agar saabit ho jaye ki wo baat jhoothi thi, tab bhi unke prati shak dimaag me bacha rehta hai.',
  summary60s: 'WhatsApp forwards me yeh sabse zyada hota hai. Ek fake video aati hai jisme kisi brand me chemical hone ka daawa hota hai. Agle din lab testing aur court clarification aa jata hai ki video scripted aur fake thi. Par log dukaan par jaakar kehte hain: "Chhodo yaar, video fake thi par dhuwan utha hai toh aag toh hogi hi." Jhooth mar jata hai, par darr aur shak zinda rehta hai.',

  quickTakeaways: [
    'Self-Sustaining Causal Web: Suboot mar jata hai par uske peeche bani dimaagi kahani zinda rehti hai',
    'Fact-Check Ka Limitation: Sirf link bhejne se logon ka vishwas nahi badalta; naya narrative chahiye hota hai',
    'Counter-Explanation Antidote: Purane jhooth ko todne ke liye khud se ulte sach ke 3 reasons likhein',
    'Ego Defense: Apni galti manna mushkil hota hai, isliye dimaag jhooth ko hi defend karta rehta hai',
  ],

  whyItHappens: 'Cognitive conservation. Ek baar bane hue dimaagi dhang ko todna aur accept karna ki "main bewakoof ban gaya tha" bohot painful hota hai.',
  evolutionaryMechanism: 'Roz-roz apne qabile ke vishwas ko badalna dangerous tha; consistency qabile me unity maintain rakhti thi.',

  howItWorks: 'Teen steps: (1) Exposure: Jhoothi khabar suni; (2) Elaboration: Dimaag ne reasons banaye; (3) Immunity: Suboot jhootha nikla par reasons zinda reh gaye.',

  visualExplanation: {
    type: 'contrast_matrix',
    visualConceptType: 'comparison_matrix',
    headline: 'Logic vs Belief Perseverance',
    description: 'Kyu neev hilne par bhi dimaagi makaan nahi girta.',
    analogySideA: {
      label: 'Pure Logic (Scientific)',
      detail: 'Agar buniyad jhoothi saabit hui, toh conclusion turant zero ho jata hai.',
    },
    analogySideB: {
      label: 'Belief Perseverance (Dimaag)',
      detail: 'Buniyad khatam hone ke baad bhi dimaag hawa me naye khambe khade kar leta hai.',
    },
  },

  examples: [
    {
      id: 'ex_bel_01',
      domain: 'health',
      displayOrder: 1,
      title: 'Wakefield Autism Myth',
      description: '1998 me vaccine-autism paper fraud saabit hua aur doctor ka license cancel ho gaya. 25 saal baad bhi lakho log is jhooth par yakeen karte hain.',
      takeaway: 'Emotional darr factual clarification se bohot zyada taqatwar hota hai.',
    },
  ],

  scenarios: [
    {
      id: 'scen_bel_01',
      scenarioType: 'indian_context',
      title: 'Bhopal Me Park Bikne Ki WhatsApp Afwah',
      vignette: 'Bhopal me Sunil ko WhatsApp forward mila ki municipal officers colony ka public park ek builder ko bech rahe hain. Sunil gusse me protest me gaya aur Facebook par post daale. Do din baad Municipal Commissioner ne press conference karke legal documents dikhaye ki park fully protected hai aur afwah ek corrupt contractor ne failayi thi. Sunil ne clarification padha par padosi se bola: "Is hafte nahi becha hoga, par saare babu chor hain, parde ke peeche setting zaroor chal rahi thi."',
      breakdownAnalysis: 'Sunil Belief Perseverance ka shikaar tha. Fact-check aane ke baad bhi uske dimaag ne "corruption" ki kahani ko bachaye rakhne ke liye naya bahana bana liya.',
      recommendedAction: 'Counter-Explanation karein: Khud se poochein: "Aise kaunse 3 genuine reasons hain jisse pata chalta hai ki yeh afwah galat thi?" Naye sach par focus karein.',
    },
  ],

  practiceQuestions: [
    {
      id: 'pq_bel_01',
      scenarioContext: 'Company me ek manager par ₹10,00,000 chori ka aarop lagta hai. 3 din baad forensic audit me pata chalta hai ki software me double-entry bug tha aur manager 100% innocent hai.',
      question: 'Kaunsa reaction Belief Perseverance ka saboot hai?',
      prompt: 'Kaunsa reaction Belief Perseverance ka saboot hai?',
      scenarioText: 'Company me ek manager par ₹10,00,000 chori ka aarop lagta hai. 3 din baad forensic audit me pata chalta hai ki software me double-entry bug tha aur manager 100% innocent hai.',
      options: [
        {
          id: 'opt_a',
          label: 'A',
          text: '"Dhuwan utha hai toh aag toh hogi hi. Bug chahe software me ho, par mujhe is manager par ab bharosa nahi hai."',
          explanation: 'Sahi: Suboot galat saabit hone ke baad bhi bina wajah shak banaye rakhna hi belief perseverance hai.',
          isCorrect: true,
        },
        {
          id: 'opt_b',
          label: 'B',
          text: '"Forensic report ne saabit kar diya hai isliye main manager par poora bharosa karta hoon"',
          explanation: 'Yeh evidence-based rational thinking hai.',
          isCorrect: false,
        },
        {
          id: 'opt_c',
          label: 'C',
          text: '"Software bug theek karne ke liye IT team ko bolna chahiye"',
          explanation: 'Yeh technical solution hai.',
          isCorrect: false,
        },
      ],
      correctAnswerId: 'opt_a',
      cognitiveTakeaway: 'Afwah galat saabit hone ke baad bhi dimaag emotional shak ko zinda rakhne ke liye naye bahane bana leta hai.',
      difficulty: 'easy',
    },
  ],

  howToRespond: 'Ulte sach ke reasons likhein aur purani kahani ko naye scientific sach se replace karein.',
  psychologicalDefenses: [
    {
      title: 'Counter-Explanation Technique',
      instruction: 'Jab koi baat galat saabit ho jaye, toh 2 minute baith kar likhein ki sach ke kya fayde hain aur wo kyu sahi hai.',
    },
    {
      title: 'Replace the Void',
      instruction: 'Galat khabar ko sirf delete mat kijiye; uski jagah actual sach ka poora narrative samjhein.',
    },
  ],

  reflectionPrompt: 'Kya aapke sath kabhi hua hai ki kisi ke bare me koi galat baat pata chali thi, aur clarification aane ke baad bhi aapka shak nahi gaya?',
  seoTitle: 'Belief Perseverance Kya Hai? Fake News Kyu Nahi Marti | Mentalab Mind',
  seoDescription: 'Janiye kyu saboot jhootha nikalne par bhi log purani afwahon par yakeen karte rehte hain. Seekhein belief update karne ke tareeqe.',
  canonicalUrl: '/mind/cognitive-biases/belief-perseverance',
};

export const TOPIC_BELIEF_PERSEVERANCE_HI: MindTopicDetail = {
  ...TOPIC_BELIEF_PERSEVERANCE_EN,
  title: 'Belief Perseverance (विश्वास हठधर्मिता)',
  subtitle: 'प्रमाणों के पूरी तरह खंडित हो जाने के बाद भी अपने मूल विश्वास पर अड़े रहना।',
  shortDescription: 'एक संज्ञानात्मक पूर्वाग्रह जहाँ व्यक्ति किसी दावे का आधार झूठा सिद्ध होने के बावजूद उस पूर्व धारणा या विश्वास को त्यागने से इनकार कर देता है।',
  oneLineExplanation: 'आधार का अंत हो जाने पर भी धारणा का जीवित रहना।',
  summary30s: '1975 में ली रॉस और मार्क लेपर द्वारा खोजा गया विश्वास हठधर्मिता (Belief Perseverance) यह दर्शाता है कि एक बार जब मस्तिष्क किसी विचार के समर्थन में कारण गढ़ लेता है, तो मूल प्रमाण झूठा साबित होने पर भी वे गढ़े हुए कारण जीवित रहते हैं।',
};

export const TOPIC_BELIEF_PERSEVERANCE: Record<MindLanguageCode, MindTopicDetail> = {
  en: TOPIC_BELIEF_PERSEVERANCE_EN,
  hinglish: TOPIC_BELIEF_PERSEVERANCE_HINGLISH,
  hi: TOPIC_BELIEF_PERSEVERANCE_HI,
  gu: TOPIC_BELIEF_PERSEVERANCE_EN,
  mr: TOPIC_BELIEF_PERSEVERANCE_EN,
  te: TOPIC_BELIEF_PERSEVERANCE_EN,
  ta: TOPIC_BELIEF_PERSEVERANCE_EN,
  kn: TOPIC_BELIEF_PERSEVERANCE_EN,
  ml: TOPIC_BELIEF_PERSEVERANCE_EN,
  bn: TOPIC_BELIEF_PERSEVERANCE_EN,
  pa: TOPIC_BELIEF_PERSEVERANCE_EN,
  ur: TOPIC_BELIEF_PERSEVERANCE_EN,
  or: TOPIC_BELIEF_PERSEVERANCE_EN,
  as: TOPIC_BELIEF_PERSEVERANCE_EN,
};
