import { MindTopicDetail, MindLanguageCode } from '../types';

export const TOPIC_PHANTOM_VIBRATION_SYNDROME_EN: MindTopicDetail = {
  id: 'phantom_vibration_syndrome',
  categoryId: 'social_media_tech',
  slug: 'phantom-vibration-syndrome',
  difficulty: 'beginner',
  estimatedReadingMinutes: 5,
  scientificConsensusTier: 'established',
  sortWeight: 6,
  viewCount: 3520,
  shareCount: 270,
  bookmarkCount: 570,
  title: "Phantom Vibration Syndrome: Tactile Hypervigilance",
  subtitle: "Why you constantly feel your phone vibrating in your pocket even when nobody called.",
  shortDescription: "A sensory hallucination where an individual perceives that their cell phone is vibrating or ringing when it is not, caused by anticipatory sensory gating in the cerebral cortex.",
  oneLineExplanation: "Your brain treating every slight muscle twitch as an urgent incoming digital notification.",

  summary30s: "Studied extensively by Dr. Michelle Drouin and neuroscientists, Phantom Vibration Syndrome affects up to 89% of smartphone users. The brain anticipates notifications so intensely that it misinterprets clothes rubbing against the leg or muscle spasms as phone vibration signals.",
  coreConcept: "Signal Detection Theory explains phantom vibrations. The brain constantly monitors ambiguous sensory signals. Because missing an important text or notification carries perceived social cost, the brain sets its sensitivity threshold extremely low: it prefers a \"false alarm\" (checking an unvibrated phone) over a \"miss\" (ignoring a real call).",
  summary60s: "This phenomenon proves that modern smartphones have literally become integrated into the human brain's biological body schema (the neurological map of one's physical body). When the phone is in your pocket, your somatosensory cortex treats it like an extended limb, remaining in a state of chronic low-grade sensory hypervigilance.",
  quickTakeaways: ["Phantom vibrations are sensory false alarms generated by an anxious brain","Up to 90% of college students and knowledge workers experience this regularly","The brain treats the smartphone as a literal neurological extension of the body","Carrying the phone in a bag or taking weekly screen detoxes resets the sensory threshold"],

  whyItHappens: "Signal detection calibration: our social reward circuitry values incoming connection so highly that the brain biases sensory interpretation toward false positives.",
  evolutionaryMechanism: "Hunters in the wild needed to mistake rustling grass for a predator (false alarm) rather than ignore a tiger (fatal miss).",

  howItWorks: "Anticipation of messages -> Somatosensory cortex increases tactile gain -> Thigh muscle twitches or trousers rustle -> Brain categorizes sensation as vibration -> Reach for pocket -> Screen is blank.",
  visualExplanation: {
    type: 'contrast_matrix',
    visualConceptType: 'comparison_matrix',
    headline: "Signal Detection Theory: The Low Threshold Trap",
    description: "How the brain trades sensory accuracy for avoiding social misses.",
    analogySideA: {
      label: "Sensory Reality",
      detail: "Pocket fabric rubs against thigh hair follicle (0.05 Newtons of friction, zero phone activity).",
    },
    analogySideB: {
      label: "Brain's Perceptual Output",
      detail: "\"ALERT! Important notification incoming! Check your phone right now!\" (False Positive).",
    },
  },

  researchSummary: "Drouin et al. (2012, Computers in Human Behavior) and Rothberg et al. (2010) found that 89% of respondents experienced phantom vibrations, with frequency directly correlating to emotional dependency on text messaging.",
  references: [
    {
      id: 'ref_phantom_vibration_syndrome_01',
      title: "Phantom Vibrations Among Undergraduates: Prevalence and Characteristics",
      citation: "Drouin, M., et al. (2012). Computers in Human Behavior, 28(4), 1490–1496.",
      authors: "Drouin, M., Kaiser, D. H., & Miller, D. A.",
      publicationYear: 2012,
      sourceType: 'peer_reviewed_journal',
      evidenceStrength: 'empirical_study',
      doiOrUrl: "https://doi.org/10.1016/j.chb.2012.03.013",
      relevance: 'Foundational empirical grounding.',
      displayOrder: 1,
    },
  ],

  scenarios: [
    {
      id: 'scen_phantom_vibration_syndrome_01',
      scenarioType: 'indian_context',
      displayOrder: 1,
      isFeatured: true,
      title: "The Mumbai Local Train False Alarm",
      narrativeContext: "Sameer was commuting on a crowded Mumbai local train to Churchgate. Every 4 minutes, he reached down to tap his front pocket, convinced his phone was buzzing with urgent client emails. When he finally took it out, it was at 0% battery and had been dead for an hour.",
      biasInAction: "Sameer experienced acute tactile hypervigilance: train vibrations and muscle tension were misclassified by his cortex as digital notifications.",
      optimalResponse: "Break the tactile attachment: carry the phone in a backpack compartment and turn off vibration mode for non-essential notifications.",
      reflectionPrompt: "How many times today did you reach for your pocket only to find no new messages or alerts waiting for you?",
    },
  ],

  examples: [
    {
      id: 'ex_phantom_vibration_syndrome_01',
      domain: 'workplace',
      displayOrder: 1,
      title: "The Mumbai Local Train False Alarm",
      description: "Sameer was commuting on a crowded Mumbai local train to Churchgate. Every 4 minutes, he reached down to tap his front pocket, convinced his phone was ...",
      takeaway: "Phantom vibrations are sensory false alarms generated by an anxious brain",
    },
  ],

  howToRecognize: "Reaching for your thigh or pocket feeling an unmistakable buzzing sensation, only to pull out a screen that has had no alerts for hours.",
  whereYouEncounterIt: "Commutes, exam halls, high-pressure office environments, and waiting rooms.",
  commonMisconceptions: "Myth: \"Phantom vibrations mean you have brain damage or schizophrenia.\" Fact: It is a benign neurological false alarm caused by learned cognitive conditioning.",
  limitationsAndControversies: "Rarely, true nerve damage (meralgia paresthetica) can cause tingling in the thigh; the distinction is that phantom vibrations match the exact haptic rhythm of your phone.",

  howToRespond: "Relocate the device: stop carrying your phone in the exact same front pocket. Moving it to a jacket pocket or bag breaks the sensory association.",
  psychologicalDefenses: [{"title":"The Pocket Relocation Drill","instruction":"Keep your phone in your desk drawer or backpack rather than your trouser pocket to desensitize your leg nerves."},{"title":"Haptic Notification Audit","instruction":"Turn off vibration for WhatsApp groups, social media, and email; keep haptic buzzes exclusively for direct phone calls."}],

  practiceQuestions: [
    {
      id: 'pq_phantom_vibration_syndrome_01',
      difficulty: 'beginner',
      questionFormat: 'scenario_analysis',
      displayOrder: 1,
      prompt: "You feel a distinct vibration in your right pocket, reach in, and realize your phone is actually on the kitchen table. What neural mechanism explains this?",
      scenarioText: "You swear on your life you felt the exact 2-buzz pattern of a WhatsApp notification.",
      explanation: "Phantom vibration is a sensory false positive where clothing friction or muscle fasciculations are mapped onto learned digital notification patterns.",
      antidoteAdvice: "Recognize the hypervigilance and recalibrate by leaving the phone away from your body for several hours.",
      options: [
        {
          id: 'opt_a',
          isCorrect: false,
          displayOrder: 1,
          optionText: "You are experiencing early-onset neurological motor neuron degeneration.",
          text: "You are experiencing early-onset neurological motor neuron degeneration.",
          feedbackText: "Incorrect. It is a completely normal cognitive false positive.",
        },
        {
          id: 'opt_b',
          isCorrect: true,
          displayOrder: 2,
          optionText: "Your brain’s signal detection threshold is set so low that it misinterprets ordinary clothes friction as a notification.",
          text: "Your brain’s signal detection threshold is set so low that it misinterprets ordinary clothes friction as a notification.",
          feedbackText: "Correct! This is classical Signal Detection Theory in digital psychology.",
        },
        {
          id: 'opt_c',
          isCorrect: false,
          displayOrder: 3,
          optionText: "Someone hacked your phone and is sending ghost signals.",
          text: "Someone hacked your phone and is sending ghost signals.",
          feedbackText: "Incorrect. This is a paranoid misconception.",
        }
      ],
    },
  ],

  reflectionPrompt: "Can you spend an entire Sunday carrying your phone exclusively in a backpack rather than your pocket?",
  tags: ['Mentalab Mind', 'social_media_tech'],
  relatedTopics: [],
  seoTitle: `${"Phantom Vibration Syndrome: Tactile Hypervigilance"} | Mentalab Mind`,
  seoDescription: "A sensory hallucination where an individual perceives that their cell phone is vibrating or ringing when it is not, caused by anticipatory sensory gating in the cerebral cortex.",
  canonicalUrl: '/mind/social-media-tech/phantom-vibration-syndrome',
  ogImageUrl: '/images/mind/phantom-vibration-syndrome.png',
  publishedAt: '2026-09-10T00:00:00Z',
  deepExplanation: "This phenomenon proves that modern smartphones have literally become integrated into the human brain's biological body schema (the neurological map of one's physical body). When the phone is in your pocket, your somatosensory cortex treats it like an extended limb, remaining in a state of chronic low-grade sensory hypervigilance.",
};

export const TOPIC_PHANTOM_VIBRATION_SYNDROME_HINGLISH: MindTopicDetail = {
  ...TOPIC_PHANTOM_VIBRATION_SYNDROME_EN,
  title: "Phantom Vibration Syndrome: Jeb Me Naqli Vibration Ka Ehsaas",
  subtitle: "Kyu lagta hai ki phone vibrate hua, par jeb se nikaalo to koi notification nahi hota.",
  shortDescription: "Sensory hallucination: Jab kapdo ki ragad ya muscle twitch ko dimaag phone ka vibration samajh leta hai.",
  oneLineExplanation: "Dimaag ka phone ke notifications ke liye itna bechain hona ki hawa se bhi phone bajta lagta hai.",
  summary30s: "Research ke mutabiq 89% smartphone users ko lagta hai ki unka phone vibrate hua, jabki phone par koi call nahi aayi hoti. Hamara dimaag notifications ke dopamine ke liye itna alert rehta hai ki pant ki ragad ko bhi call samajh leta hai.",
  coreConcept: "Ise kehte hain Signal Detection Theory. Dimaag kehta hai: \"Agar call aayi aur maine miss kar di to nuksan hoga, isliye shak hone par bhi phone check kar lo.\" Dimaag phone ko apne sharir ka ek hissa maan leta hai.",
  summary60s: "Agar aap roz phone ko right pocket me rakhte hain, to wahan ki nerves hyper-sensitive ho jati hain. Train ki vibration ya pair ki muscle twitch ko dimaag message samajhta hai. Is aadat ko todne ke liye phone ko jeb se nikaal kar bag me rakhna shuru karein.",
  quickTakeaways: ["Phantom vibration koi bimari nahi, balki mobile addiction ka brain signal hai","Dimaag notification miss karne ke darr se jhoothe alerts generate karta hai","Phone ko pant ki pocket ke bajaye bag ya table par rakhne se yeh 3 din me theek ho jata hai","Faltu WhatsApp groups aur apps ka vibration hamesha OFF rakhein"],
  howItWorks: "Notification ka intezar -> Dimaag nerves ko extra alert karta hai -> Pant thodi si hili -> Dimaag ne signal diya \"Vibration hua!\" -> Jeb me haath daala -> Screen blank thi.",
  howToRespond: "Phone ki jagah badlein: Phone ko jeans ki pocket me rakhna band karein, bag ya table par rakhein. Aur faltu apps ke vibration notifications band kar dein.",
  practiceQuestions: [
    {
      ...TOPIC_PHANTOM_VIBRATION_SYNDROME_EN.practiceQuestions[0],
      prompt: "Aapko laga jeb me phone 2 baar vibrate hua, nikaal kar dekha to phone switch off tha. Dimaag me kya hua?",
      explanation: "Dimaag ne kapdo ki aam movement ko notification samajh liya kyuki wo extra alert mode me tha.",
      options: [
        {
          id: 'opt_a',
          isCorrect: false,
          displayOrder: 1,
          optionText: "Aapka dimaag kharab ho raha hai aur doctor ke paas jana padega.",
          text: "Aapka dimaag kharab ho raha hai aur doctor ke paas jana padega.",
          feedbackText: "Galat. Yeh 90% smartphone users ke sath hota hai.",
        },
        {
          id: 'opt_b',
          isCorrect: true,
          displayOrder: 2,
          optionText: "Dimaag ki sensory nerves ne kapde ki ragad ko galti se vibration interpret kar liya.",
          text: "Dimaag ki sensory nerves ne kapde ki ragad ko galti se vibration interpret kar liya.",
          feedbackText: "Sahi! Ise Phantom Vibration kehte hain.",
        },
        {
          id: 'opt_c',
          isCorrect: false,
          displayOrder: 3,
          optionText: "Phone switch off hone ke baad bhi tarangein chhod raha tha.",
          text: "Phone switch off hone ke baad bhi tarangein chhod raha tha.",
          feedbackText: "Galat. Yeh physical sensation brain ki hai, phone ki nahi.",
        }
      ],
    },
  ],
  seoTitle: `${"Phantom Vibration Syndrome: Jeb Me Naqli Vibration Ka Ehsaas"} | Mentalab Mind`,
  seoDescription: "Sensory hallucination: Jab kapdo ki ragad ya muscle twitch ko dimaag phone ka vibration samajh leta hai.",
};

function createLocalizedRecord(
  lang: MindLanguageCode,
  title: string,
  summary: string,
  takeaways: string[]
): MindTopicDetail {
  return {
    ...TOPIC_PHANTOM_VIBRATION_SYNDROME_EN,
    title,
    subtitle: summary.slice(0, 80) + '...',
    oneLineExplanation: summary.slice(0, 60),
    summary30s: summary,
    coreConcept: summary,
    quickTakeaways: takeaways,
    seoTitle: `${title} | Mentalab Mind`,
    seoDescription: `${summary.slice(0, 150)}...`,
  };
}

export const TOPIC_PHANTOM_VIBRATION_SYNDROME: Record<MindLanguageCode, MindTopicDetail> = {
  en: TOPIC_PHANTOM_VIBRATION_SYNDROME_EN,
  hinglish: TOPIC_PHANTOM_VIBRATION_SYNDROME_HINGLISH,
  hi: createLocalizedRecord('hi', "आभासी कंपन सिंड्रोम (Phantom Vibration)", "फोन में कोई कॉल या मैसेज न होने पर भी जेब में कंपन महसूस होने का संवेदी मनोवैज्ञानिक भ्रम।", ["मस्तिष्क कपड़ों के घर्षण को नोटिफिकेशन समझ लेता है","यह अत्यधिक डिजिटल निर्भरता का संकेत है","फोन को जेब के बजाय बैग में रखना इसका समाधान है"]),
  gu: createLocalizedRecord('gu', "ફેન્ટમ વાઇબ્રેશન સિન્ડ્રોમ (આભાસી કંપન)", "ફોન વાગ્યો ન હોવા છતાં ખિસ્સામાં વાઇબ્રેશનનો ખોટો આભાસ થવાની મનોવૈજ્ઞાનિક સ્થિતિ.", ["ખોટા આભાસથી સાવધાન રહો","ફોનને ખિસ્સામાં ન રાખો","ડિજિટલ નિર્ભરતા ઘટાડો"]),
  mr: createLocalizedRecord('mr', "फॅन्टम व्हायब्रेशन सिंड्रोम (भासमान कंपन)", "फोनवर कोणताही मेसेज नसतानाही खिशात व्हायब्रेशन झाल्याचा भास होण्याची मेंदूची सवय.", ["हा मेंदूचा एक भास आहे","अति-डिजिटल वापराचे लक्षण","फोन खिशात ठेवणे टाळा"]),
  te: createLocalizedRecord('te', "ఫాంటమ్ వైబ్రేషన్ సిండ్రోమ్ (భ్రమతో కూడిన ప్రకంపనలు)", "ఫోన్ మోగకపోయినా జేబులో వైబ్రేషన్ వచ్చినట్లు అనిపించే సహజ మానసిక భ్రమ.", ["ఇది ఒక నాడీ సంబంధిత భ్రమ","డిజిటల్ వ్యసనాన్ని తగ్గించండి","ఫోన్‌ను బ్యాగ్‌లో ఉంచండి"]),
  ta: createLocalizedRecord('ta', "போலி அதிர்வு நோய்க்குறி (Phantom Vibration)", "தொலைபேசி அதிராத போதும் பாக்கெட்டில் அதிர்வு ஏற்படுவது போல் தோன்றும் உளவியல் மாயை.", ["இது ஒரு தவறான உணர்வு","செல்போன் பயன்பாட்டை குறையுங்கள்","போனை பையில் வையுங்கள்"]),
  kn: createLocalizedRecord('kn', "ಫ್ಯಾಂಟಮ್ ವೈಬ್ರೇಶನ್ ಸಿಂಡ್ರೋಮ್", "ಫೋನ್ ರಿಂಗ್ ಆಗದಿದ್ದರೂ ಜೇಬಿನಲ್ಲಿ ಕಂಪನವಾದಂತೆ ಭಾಸವಾಗುವ ಸಾಮಾನ್ಯ ಮಾನಸಿಕ ಭ್ರಮೆ.", ["ಇದು ನರಗಳ ಅತಿಯಾದ ಜಾಗರೂಕತೆ","ಮೊಬೈಲ್ ಗೀಳನ್ನು ಕಡಿಮೆ ಮಾಡಿ","ಫೋನನ್ನು ಬ್ಯಾಗ್‌ನಲ್ಲಿಡಿ"]),
  ml: createLocalizedRecord('ml', "ഫാന്റം വൈബ്രേഷൻ സിൻഡ്രോം", "ഫോൺ വൈബ്രേറ്റ് ചെയ്യാതിരുന്നിട്ടും പോക്കറ്റിൽ അങ്ങനെ തോന്നുന്ന മാനസിക വിഭ്രാന്തി.", ["ഇതൊരു സാധാരണ ഇന്ദ്രിയ ഭ്രമമാണ്","ഫോൺ ഉപയോഗം പരിമിതപ്പെടുത്തുക","ഫോൺ ബാഗിൽ സൂക്ഷിക്കുക"]),
  bn: createLocalizedRecord('bn', "ফ্যান্টম ভাইব্রেশন সিন্ড্রোম (অলীক কম্পন)", "ফোনে কোনো নোটিফিকেশন না আসা সত্ত্বেও পকেটে ভাইব্রেশন অনুভব করার মনস্তাত্ত্বিক ভ্রান্তি।", ["এটি একটি সংবেদনশীল বিভ্রম","ডিজিটাল নির্ভরতা কমান","ফোন পকেটে না রেখে ব্যাগে রাখুন"]),
  pa: createLocalizedRecord('pa', "ਫੈਂਟਮ ਵਾਈਬ੍ਰੇਸ਼ਨ ਸਿੰਡਰੋਮ (ਕੰਬਣੀ ਦਾ ਭੁਲੇਖਾ)", "ਫ਼ੋਨ ਨਾ ਵੱਜਣ ਦੇ ਬਾਵਜੂਦ ਜੇਬ ਵਿੱਚ ਵਾਈਬ੍ਰੇਸ਼ਨ ਮਹਿਸੂਸ ਹੋਣ ਦਾ ਮਨੋਵਿਗਿਆਨਕ ਭੁਲੇਖਾ।", ["ਇਹ ਦਿਮਾਗ ਦਾ ਇੱਕ ਭਰਮ ਹੈ","ਮੋਬਾਈਲ ਦੀ ਵਰਤੋਂ ਘਟਾਓ","ਫ਼ੋਨ ਬੈਗ ਵਿੱਚ ਰੱਖੋ"]),
  ur: createLocalizedRecord('ur', "فینٹم وائبریشن سنڈروم (خام خیالی لرزش)", "موبائل پر کوئی کال یا میسج نہ ہونے کے باوجود جیب میں وائبریشن محسوس ہونے کا نفسیاتی وہم۔", ["یہ حسیات کا ایک مغالطہ ہے","موبائل پر انحصار کم کریں","فون کو بیگ میں رکھیں"]),
  or: createLocalizedRecord('or', "ଫାଣ୍ଟମ୍ ଭାଇବ୍ରେସନ୍ ସିଣ୍ଡ୍ରୋମ୍ (କାଳ୍ପନିକ କମ୍ପନ)", "ଫୋନ୍ ନବାଜିଲେ ମଧ୍ୟ ପକେଟ୍‌ରେ ଭାଇବ୍ରେସନ୍ ହେଉଥିବାର ମାନସିକ ଭ୍ରମ।", ["ଏହା ମସ୍ତିଷ୍କର ଏକ ଭ୍ରମ","ମୋବାଇଲ୍ ବ୍ୟବହାର ସୀମିତ କରନ୍ତୁ","ଫୋନ୍‌କୁ ବ୍ୟାଗ୍‌ରେ ରଖନ୍ତୁ"]),
  as: createLocalizedRecord('as', "ফেণ্টম ভাইব্ৰেচন চিনড্ৰম (কাল্পনিক কম্পন)", "ফোনটো নবজাকৈয়ে পকেটত ভাইব্ৰেচন হোৱা যেন অনুভৱ হোৱাৰ মানসিক বিভ্ৰান্তি।", ["ই এটা ইন্দ্ৰিয়গত ভ্ৰম","ডিজিটেল আসক্তি হ্ৰাস কৰক","ফোনটো জেপত নাৰাখি বেগত থওক"]),
};
