import { ComprehensiveTopicDef } from '../topicGeneratorHelper';

export const CONSUMER_TOPICS: ComprehensiveTopicDef[] = [
  {
    fileName: 'penniesADayFraming.ts',
    varName: 'pennies_a_day_framing',
    id: 'pennies_a_day_framing',
    categoryId: 'consumer_advertising',
    slug: 'pennies-a-day-framing',
    difficulty: 'beginner',
    readTime: 5,
    sortWeight: 5,
    titleEn: 'Pennies-a-Day Framing: The Illusion of Trivial Expense',
    subtitleEn: 'John Gourville’s pricing research on why re-framing a lump sum into small daily amounts bypasses mental accounting brakes.',
    shortDescEn: 'A cognitive pricing strategy that presents an aggregate recurring expense as a trivial daily cost (e.g. "Only ₹15 a day—less than a cup of chai!"), bypassing consumer spending friction.',
    oneLineEn: 'Making a ₹15,000 annual commitment feel like pocket change by breaking it into daily coins.',
    summary30sEn: 'First analyzed scientifically by Harvard Business School professor John Gourville in 1998, Pennies-a-Day (PAD) framing shifts a consumer’s mental accounting category. Instead of comparing a ₹3,650 gym fee to major household bills, comparing it to "₹10 a day" categorizes it alongside trivial petty cash that requires zero deliberation.',
    coreConceptEn: 'Mental accounting dictates that consumers maintain cognitive budgets for different categories: large expenses undergo high scrutiny, while petty cash expenses below a cognitive threshold are spent frictionlessly. Temporal reframing reclassifies an aggregate luxury purchase into an everyday routine expense, neutralizing buyer hesitation.',
    summary60sEn: 'Subscription businesses (streaming, software, gym memberships, term insurance) rely heavily on PAD. While consumers evaluate the daily unit cost as negligible, payments compound into significant annual drains. When stacked across 10 different subscriptions, "just ₹20 a day" quietly extracts tens of thousands of rupees each year.',
    takeawaysEn: [
      'PAD framing tricks the brain by comparing lump-sum commitments to trivial petty cash',
      'Small daily expenses bypass the brain’s "pain of paying" insula response',
      'Marketers intentionally frame costs daily while billing annually or monthly on auto-debit',
      'The antidote is annualizing all micro-subscriptions before approving purchase'
    ],
    whyItHappensEn: 'Working memory evaluates numbers relative to reference anchors; ₹10 anchors to loose change rather than annual capital allocation.',
    evolutionaryEn: 'Ancestral humans managed resources on a day-to-day horizon; evolutionary biology has no innate mechanism for calculating compounded recurring liabilities.',
    howItWorksEn: 'Annual price encountered (₹12,000) -> Brain feels pain of paying -> Marketer presents "Just ₹33/day" -> Brain shifts anchor to a cup of chai -> Rational scrutiny disengages -> Subscription approved.',
    visualHeadlineEn: 'Annual Capital Outlay vs. The "Chai" Reframing Trap',
    visualDescEn: 'How temporal granularity shifts mental accounting evaluation.',
    sideALabelEn: 'Aggregate Real Outlay',
    sideADetailEn: '₹14,400 deducted every year; requires budgeting, trade-offs, and financial discipline.',
    sideBLabelEn: 'Pennies-a-Day Illusion',
    sideBDetailEn: '"Just ₹39 a day! Less than your evening snack!" -> Perceived as essentially free.',
    researchSummaryEn: 'Gourville (1998, Journal of Consumer Research) proved that framing a $350 annual charitable donation or subscription as "under a dollar a day" increased compliance rates by over 100%.',
    refAuthor: 'Gourville, J. T.',
    refYear: 1998,
    refTitle: 'Pennies-a-Day: The Effect of Temporal Reframing on Transaction Evaluation',
    refCitation: 'Gourville, J. T. (1998). Journal of Consumer Research, 24(4), 395–408.',
    refDoi: 'https://doi.org/10.1086/209517',
    scenarioTitleEn: 'The ₹29/Day Gym Trap in Whitefield',
    scenarioContextEn: 'Arjun signed up for an upscale fitness club in Whitefield, Bengaluru, because the billboard advertised "World-Class Fitness for just ₹29 a day!" He forgot about the fine print requiring an upfront 2-year non-refundable commitment of ₹21,170 on auto-debit. He attended for 3 weeks and never went again.',
    scenarioBiasEn: 'Arjun evaluated the purchase against his daily pocket change mental budget rather than his annual discretionary savings.',
    scenarioOptimalEn: 'Always multiply the daily quote by 365: "This gym membership will cost me ₹10,585 this year. Will I realistically attend 100 times to make each visit worth ₹105?"',
    scenarioReflectionEn: 'How many software apps, OTT platforms, or memberships are currently deducting auto-debit fees that you justified with "it’s only a few rupees a day"?',
    howToRecognizeEn: 'Marketing copy that uses phrases like: "For less than a cup of coffee", "Just ₹9/day", or "Costs pennies per hour."',
    whereEn: 'OTT streaming plans, insurance premiums, charity fundraisers, gym memberships, and consumer software.',
    misconceptionsEn: 'Myth: "If it’s only ₹15 a day, it really doesn’t matter to my finances." Fact: Ten small ₹15/day subscriptions compound to ₹54,750 per year—equivalent to an international holiday or emergency fund.',
    limitationsEn: 'If a service is genuinely utilized every single day and produces measurable productivity or health returns, the daily cost calculation reflects accurate utility.',
    howToRespondEn: 'The Multiplication Rule: Whenever a salesperson or advertisement pitches a daily or weekly price, immediately multiply it by 365 (or 52) and state the annual figure aloud.',
    defensesEn: [
      { title: 'The Annualization Habit', instruction: 'Force yourself to write down the full 1-year and 3-year total cash outflow before authorizing any subscription.' },
      { title: 'The Subscription Quarantine', instruction: 'Never use credit card auto-debit for new micro-subscriptions; use single-payment virtual cards to prevent silent renewal.' }
    ],
    pqPromptEn: 'An educational app advertises: "Unlock your child’s genius for just ₹19 a day!" As an economically rational decision maker, how should you evaluate this offer?',
    pqScenarioEn: 'The checkout page asks you to enter credit card details for a mandatory 12-month auto-billing plan.',
    pqExplanationEn: 'Evaluating recurring expenses through daily anchors bypasses cognitive cost scrutiny. The true metric is the aggregate annual cost (₹6,935) measured against expected usage.',
    pqAntidoteEn: 'Annualize the cost and evaluate whether the child will realistically use the platform consistently for 12 months.',
    pqOptionsEn: [
      { id: 'opt_a', text: 'Buy it immediately because ₹19 is less than a packet of chips and therefore negligible.', isCorrect: false, feedback: 'Incorrect. This falls directly into the mental accounting trap.' },
      { id: 'opt_b', text: 'Calculate the total annual cost (₹6,935) and evaluate it against your family’s annual education budget and realistic weekly usage.', isCorrect: true, feedback: 'Correct! Multiplying by 365 restores fiscal clarity.' },
      { id: 'opt_c', text: 'Ask if they have a ₹5 a day option.', isCorrect: false, feedback: 'Incorrect. This remains trapped in daily micro-framing.' }
    ],
    reflectionPromptEn: 'If you reviewed all your bank statements today, what is the combined annual total of all recurring micro-subscriptions you currently pay for?',
    titleHinglish: 'Pennies-a-Day Framing: "Chai Ke Daam Me" Ka Asli Sach',
    subtitleHinglish: 'Kyu "Roz ka sirf ₹15" sun kar hum saal ke ₹5,000 bina soche barbaad kar dete hain.',
    shortDescHinglish: 'John Gourville ki pricing research: Badi subscription ko roz ke chillar me tod kar bechna taaki dimaag ko mehenga na lage.',
    oneLineHinglish: 'Badi payment ko pocket change ke bahane dimaag ke logic se chupana.',
    summary30sHinglish: 'Harvard ke professor John Gourville ne 1998 me study kiya ki jab companies kehti hain "Ek chai se bhi sasta, sirf ₹10 roz!", to log asani se trap me fas jate hain. Dimaag sochta hai "arre ₹10 to chillar hai", par saal ke end me bank account se ₹3,650 chupchap kat jate hain.',
    coreConceptHinglish: 'Ise kehte hain Mental Accounting. Hamare dimaag me alag-alag batuye hote hain: Badi shopping ke liye hum 10 baar sochte hain, par pocket change bina soche uda dete hain. Sales wale saal ke kharche ko pocket change category me daal dete hain.',
    summary60sHinglish: 'Gym, OTT apps aur insurance wale is trick ke master hain. Agar wo bolein "₹12,000 do", to aap mana kar doge. Isliye wo bolte hain "Roz ka sirf ₹33". Jab aapke paas aisi 5 subscriptions hoti hain, to saal ka ₹60,000 bina pata chale gayab ho jata hai.',
    howItWorksHinglish: 'Company ne saal ka kharcha chupaya -> "Sirf ₹20 roz" bola -> Dimaag ne chillar samjha -> Auto-debit chalu hua -> Saal me hazaaro rupaye nikal gaye.',
    howToRespondHinglish: 'Multiply by 365 Rule: Jab bhi koi bole "Roz ka sirf ₹X", turant calculator nikalo aur 365 se multiply karke saal ka kharcha dekho.',
    takeawaysHinglish: [
      '"Chai ke daam me" bolna marketing ka dimaag ghumane wala formula hai',
      'Roz ke chote kharche bank account me aag ki tarah saal ke end me bada nuksan karte hain',
      'Hamesha daily cost ko 365 se multiply karke annual cost judge karein',
      'Auto-debit band karein taaki har renewal par dimaag conscious faisla le sake'
    ],
    pqPromptHinglish: 'Ek app bolti hai: "Sirf ₹15 roz me meditation seekhein!" Checkout par 1 saal ka auto-pay maang rahe hain. Sahi decision kya hoga?',
    pqExplanationHinglish: 'Roz ke ₹15 ko 365 se multiply karke saal ka ₹5,475 banta hai. Dekhein kya aap sach me 1 saal roz use karenge.',
    pqOptionsHinglish: [
      { id: 'opt_a', text: 'Turant card laga dena kyuki ₹15 to bilkul muft jaisa hai.', isCorrect: false, feedback: 'Galat. Yeh mental accounting trap hai.' },
      { id: 'opt_b', text: '15 ko 365 se multiply karke ₹5,475 dekhna aur sochna ki kya itna paisa is app ke liye justified hai.', isCorrect: true, feedback: 'Sahi! Annualize karna hi is framing ka sabse bada tod hai.' },
      { id: 'opt_c', text: 'Company ko phone karke roz ₹15 cash lene ko kehna.', isCorrect: false, feedback: 'Galat. Yeh impractical hai.' }
    ],
    hiTitle: 'दैनिक व्यय की भ्रांति (Pennies-a-Day Framing)',
    hiSummary: 'बड़ी वार्षिक लागत को छोटे दैनिक सिक्कों के रूप में प्रस्तुत करके मानसिक प्रतिरोध को समाप्त करने की विपणन रणनीति।',
    hiTakeaways: ['दैनिक मूल्य की भ्रांति बड़े खर्चों को छुपाती है', 'मस्तिष्क छोटी राशि को अनदेखा कर देता है', 'निर्णय लेने से पहले दैनिक लागत को 365 से गुणा करें'],
    guTitle: 'પેનિસ-એ-ડે ફ્રેમિંગ (રોજના ખર્ચનો આભાસ)', guSummary: 'મોટા વાર્ષિક ખર્ચને રોજના નાના સિક્કાઓમાં રજૂ કરીને ગ્રાહકને લલચાવવાની માર્કેટિંગ યુક્તિ.', guTakeaways: ['રોજના ખર્ચની માયાજાળ સમજો', 'વાર્ષિક કુલ ખર્ચ ગણો', 'વિચારીને સબ્સ્ક્રિપ્શન લો'],
    mrTitle: 'दैनिक खर्चाचा आभास (Pennies-a-Day Framing)', mrSummary: 'मोठ्या खर्चाची विभागणी रोजच्या किरकोळ पैशांमध्ये करून ग्राहकाची दिशाभूल करण्याचे विपणन तंत्र.', mrTakeaways: ['किरकोळ पैशांच्या आमिषाला बळी पडू नका', 'वार्षिक खर्चाची बेरीज करा', 'अनावश्यक खर्च टाळा'],
    teTitle: 'రోజువారీ వ్యయ భ్రమ (Pennies-a-Day Framing)', teSummary: 'భారీ వార్షిక ఖర్చును చిన్న రోజువారీ పైసలుగా చూపి వినియోగదారులను ఆకర్షించే మార్కెటింగ్ వ్యూహం.', teTakeaways: ['రోజువారీ ఖర్చుల భ్రమలో పడవద్దు', 'వార్షిక మొత్తాన్ని లెక్కించండి', 'అప్రమత్తంగా ఉండండి'],
    taTitle: 'தினசரி கட்டண மாயை (Pennies-a-Day Framing)', taSummary: 'பெரிய ஆண்டு கட்டணங்களை சிறிய தினசரி சில்லறையாக காட்டி வாடிக்கையாளர்களை ஏமாற்றும் சந்தைப்படுத்தல் முறை.', taTakeaways: ['தினசரி கட்டண மாயையை நம்பாதீர்கள்', 'ஆண்டு செலவை கணக்கிடுங்கள்', 'தேவையற்ற சந்தாக்களை தவிருங்கள்'],
    knTitle: 'ದೈನಂದಿನ ವೆಚ್ಚದ ಭ್ರಮೆ (Pennies-a-Day Framing)', knSummary: 'ದೊಡ್ಡ ವಾರ್ಷಿಕ ಮೊತ್ತವನ್ನು ಸಣ್ಣ ದಿನನಿತ್ಯದ ಚಿಲ್ಲರೆಯಂತೆ ತೋರಿಸಿ ಗ್ರಾಹಕರನ್ನು ಸೆಳೆಯುವ ತಂತ್ರ.', knTakeaways: ['ದೈನಂದಿನ ವೆಚ್ಚದ ಭ್ರಮೆಗೆ ಒಳಗಾಗಬೇಡಿ', 'ವಾರ್ಷಿಕ ಮೊತ್ತವನ್ನು ಪರಿಶೀಲಿಸಿ', 'ಬುದ್ಧಿವಂತಿಕೆಯಿಂದ ಖರೀದಿಸಿ'],
    mlTitle: 'ദൈനംദിന ചെലവ് മിഥ്യ (Pennies-a-Day Framing)', mlSummary: 'വലിയ വാർഷിക ചെലവുകളെ ചെറിയ ദിവസ ചെലവുകളായി കാണിച്ച് ഉപഭോക്താക്കളെ ആകർഷിക്കുന്ന മാർക്കറ്റിംഗ് തന്ത്രം.', mlTakeaways: ['ദിവസേനയുള്ള ചെറിയ തുകകൾ ശ്രദ്ധിക്കുക', 'വാർഷിക തുക കണക്കാക്കുക', 'ആവശ്യമുള്ളവ മാത്രം തിരഞ്ഞെടുക്കുക'],
    bnTitle: 'দৈনিক খরচের বিভ্রম (Pennies-a-Day Framing)', bnSummary: 'বড় বার্ষিক খরচকে ক্ষুদ্র দৈনিক খুচরো পয়সার আকারে উপস্থাপন করে ক্রেতাকে আকৃষ্ট করার কৌশল।', bnTakeaways: ['দৈনিক খরচের ফাঁদে পা দেবেন না', 'বছরের মোট খরচ হিসাব করুন', 'সচেতন সিদ্ধান্ত নিন'],
    paTitle: 'ਰੋਜ਼ਾਨਾ ਖਰਚੇ ਦਾ ਭੁਲੇਖਾ (Pennies-a-Day Framing)', paSummary: 'ਵੱਡੇ ਸਾਲਾਨਾ ਖਰਚੇ ਨੂੰ ਰੋਜ਼ ਦੇ ਨਿੱਕੇ ਸਿੱਕਿਆਂ ਵਾਂਗ ਦਿਖਾ ਕੇ ਗਾਹਕਾਂ ਨੂੰ ਭਰਮਾਉਣ ਵਾਲੀ ਮਾਰਕੀਟਿੰਗ ਚਾਲ।', paTakeaways: ['ਰੋਜ਼ਾਨਾ ਖਰਚੇ ਦੇ ਭੁਲੇਖੇ ਤੋਂ ਬਚੋ', 'ਸਾਲਾਨਾ ਕੁੱਲ ਖਰਚਾ ਦੇਖੋ', 'ਸੋਚ-ਸਮਝ ਕੇ ਖ਼ਰੀਦੋ'],
    urTitle: 'روزانہ کے خرچ کا مغالطہ (Pennies-a-Day Framing)', urSummary: 'بڑے سالانہ اخراجات کو روزانہ کی چھوٹی رقم کی صورت میں پیش کر کے گاہک کو قائل کرنے کی چال۔', urTakeaways: ['روزانہ کے معمولی خرچ کے جال سے بچیں', 'سالانہ خرچ کا حساب لگائیں', 'غیر ضروری سبسکرپشنز منسوخ کریں'],
    orTitle: 'ଦୈନନ୍ଦିନ ଖର୍ଚ୍ଚର ଭ୍ରମ (Pennies-a-Day Framing)', orSummary: 'ବଡ଼ ବାର୍ଷିକ ଖର୍ଚ୍ଚକୁ ଛୋଟ ଦୈନିକ ଖର୍ଚ୍ଚ ଭାବରେ ଦର୍ଶାଇ ଗ୍ରାହକଙ୍କୁ ଆକର୍ଷିତ କରିବାର ମାର୍କେଟିଂ କୌଶଳ।', orTakeaways: ['ଦୈନିକ ଖର୍ଚ୍ଚର ମାୟାଜାଲ ବୁଝନ୍ତୁ', 'ବାର୍ଷିକ ମୋଟ ଖର୍ଚ୍ଚ ହିସାବ କରନ୍ତୁ', 'ସତର୍କତାର ସହ ନିଷ୍ପତ୍ତି ନିଅନ୍ତୁ'],
    asTitle: 'দৈনিক খৰচৰ বিভ্ৰম (Pennies-a-Day Framing)', asSummary: 'ডাঙৰ বাৰ্ষিক খৰচক দৈনিক ক্ষুদ্ৰ পইচাৰ ৰূপত দেখুৱাই গ্ৰাহকক আকৰ্ষণ কৰাৰ বাণিজ্যিক কৌশল।', asTakeaways: ['দৈনিক খৰচৰ বিভ্ৰমত নপৰিব', 'বাৰ্ষিক খৰচৰ হিচাপ কৰক', 'সচেতন হৈ সিদ্ধান্ত লওক']
  },

  {
    fileName: 'priceQualityHeuristic.ts',
    varName: 'price_quality_heuristic',
    id: 'price_quality_heuristic',
    categoryId: 'consumer_advertising',
    slug: 'price-quality-heuristic',
    difficulty: 'beginner',
    readTime: 5,
    sortWeight: 6,
    titleEn: 'The Price-Quality Heuristic: The Placebo Effect of Pricing',
    subtitleEn: 'Baba Shiv’s Stanford experiment on why expensive painkillers literally work better than discounted ones.',
    shortDescEn: 'A mental shortcut where consumers infer the superior quality, effectiveness, or craftsmanship of a product solely based on its higher monetary price tag.',
    oneLineEn: 'Assuming that if it is expensive, it must be better—and your brain actually making it so.',
    summary30sEn: 'Studied by Rao, Monroe, and experimentally proven by Stanford professor Baba Shiv, the Price-Quality Heuristic is not just a cognitive bias; it triggers genuine biological placebos. In Shiv’s famous study, identical energy drinks and painkillers provided measurably superior cognitive focus and pain relief when participants were told they cost full price versus discounted price.',
    coreConceptEn: 'When consumers face information asymmetry (they cannot personally verify wine chemistry, watch mechanics, or doctor expertise), price becomes the primary proxy for unobservable quality. The higher expectation physically alters sensory experience via dopamine activation in the orbitofrontal cortex: people genuinely taste expensive wine as richer and sweeter.',
    summary60sEn: 'Luxury conglomerates (apparel, skincare, luxury dining) exploit this heuristic ruthlessly. Often, cutting a price reduces sales because consumers suspect the item is defective, while tripling the price dramatically boosts desirability. This is how generic chemical compounds (retinol, hyaluronic acid) are packaged in fancy bottles and sold for 50x markup.',
    takeawaysEn: [
      'Price alters physical sensory perception through prefrontal expectation placebo effects',
      'Identical medications relieve more physical pain when labeled with expensive price tags',
      'Marketers raise prices intentionally to create an aura of exclusivity and efficacy',
      'The antidote is blind testing and inspecting raw active ingredient specifications'
    ],
    whyItHappensEn: 'Information asymmetry and risk aversion: verifying technical quality requires domain expertise; price serves as a convenient heuristic summary of market value.',
    evolutionaryEn: 'In ancestral resource trading, high-cost items (obsidian blades, rare shells) genuinely required more labor and dangerous quarrying.',
    howItWorksEn: 'High price seen -> Prefrontal expectation primed -> Dopamine released in reward anticipation -> Sensory experience altered -> Subjective quality confirmed -> Consumer justifies the premium.',
    visualHeadlineEn: 'Expectation Placebo vs. Chemical Reality',
    visualDescEn: 'How price tags modulate sensory and neurobiological responses.',
    sideALabelEn: 'Identical Energy Drink @ Discount (₹20)',
    sideADetailEn: 'Solved 6.8 word puzzles on average; reported feeling slightly energized.',
    sideBLabelEn: 'Identical Energy Drink @ Full Price (₹100)',
    sideBDetailEn: 'Solved 9.9 word puzzles on average (30% increase!) purely driven by the price expectation placebo.',
    researchSummaryEn: 'Shiv, Carmon & Ariely (2005, Journal of Marketing Research) and Plassmann et al. (2008, PNAS) proved via fMRI that increasing the stated price of wine directly increases blood oxygenation in the medial orbitofrontal cortex during consumption.',
    refAuthor: 'Shiv, B., Carmon, Z., & Ariely, D.',
    refYear: 2005,
    refTitle: 'Placebo Effects of Marketing Actions: Consumers May Get What They Pay For',
    refCitation: 'Shiv, B., et al. (2005). Journal of Marketing Research, 42(4), 383–393.',
    refDoi: 'https://doi.org/10.1509/jmkr.2005.42.4.383',
    scenarioTitleEn: 'The ₹8,000 Ayurvedic Face Serum in South Bombay',
    scenarioContextEn: 'Ananya bought an organic face oil in South Mumbai for ₹8,500, claiming it transformed her skin texture within 3 days. A cosmetic chemist friend analyzed the bottle: the formulation was 98% cold-pressed sesame oil and rose water, identical to a ₹150 bottle from the local chemist.',
    scenarioBiasEn: 'Ananya experienced the price-quality placebo: the exorbitant price triggered psychological commitment, careful application, and expectation confirmation.',
    scenarioOptimalEn: 'Ignore marketing packaging; turn the box around and read the active ingredients (INCI list) and their percentage concentrations.',
    scenarioReflectionEn: 'Have you ever enjoyed a restaurant meal or bottle of wine noticeably more simply after discovering how outrageously expensive the bill was?',
    howToRecognizeEn: 'Assuming a service, consultant, or product is elite solely because their hourly rate or sticker price is exorbitant.',
    whereEn: 'Cosmetics, designer fashion, boutique medical clinics, consulting firms, and fine dining.',
    misconceptionsEn: 'Myth: "Expensive things are always better made." Fact: While basic minimum quality requires investment, beyond a baseline threshold, price reflects brand status markup, not manufacturing cost.',
    limitationsEn: 'In complex engineered precision goods (e.g. Japanese kitchen knives, aircraft engines), higher prices frequently reflect genuinely superior alloys and tolerances.',
    howToRespondEn: 'Conduct Blind Audits: whenever possible, evaluate products without knowing their brand or price tag, and compare generic active ingredients directly.',
    defensesEn: [
      { title: 'The Ingredient Specification Audit', instruction: 'Never buy cosmetics, supplements, or generic electronics without verifying the raw chemical composition and technical specs against budget alternatives.' },
      { title: 'Blind Taste/Trial Protocol', instruction: 'Have a friend pour two different brands into unmarked cups before deciding which one tastes or works better.' }
    ],
    pqPromptEn: 'In a double-blind scientific trial, two groups are given identical placebo sugar pills for a headache. Group A is told the pill costs ₹200; Group B is told it costs ₹5. What are the clinical results?',
    pqScenarioEn: 'Neither pill contains any active pharmaceutical ingredient.',
    pqExplanationEn: 'Due to the price-quality heuristic and expectation placebo effect, Group A experiences statistically significant higher pain relief despite chemical equivalence.',
    pqAntidoteEn: 'Evaluate generic medications by their active pharmaceutical ingredient (API), not their commercial brand price.',
    pqOptionsEn: [
      { id: 'opt_a', text: 'Both groups report the exact same pain relief because sugar pills have zero chemical efficacy.', isCorrect: false, feedback: 'Incorrect. Psychological expectations actively trigger endogenous endorphin release.' },
      { id: 'opt_b', text: 'Group A (₹200 pill) reports significantly greater headache reduction than Group B.', isCorrect: true, feedback: 'Correct! Higher price primes a stronger neurological placebo response.' },
      { id: 'opt_c', text: 'Group B reports better results because they feel relief from saving money.', isCorrect: false, feedback: 'Incorrect. Cheap pricing primes suspicion of poor efficacy.' }
    ],
    reflectionPromptEn: 'What product in your life are you currently overpaying for purely because a cheaper alternative feels "inferior" without any factual proof?',
    titleHinglish: 'Price-Quality Heuristic: Mehenga Hai To Achha Hi Hoga',
    subtitleHinglish: 'Kyu ₹8,000 ka cream aur ₹500 ka dard ka dawai hume saste se zyada asardaar lagta hai.',
    shortDescHinglish: 'Baba Shiv ki Stanford research: Zyada price tag dekh kar dimaag cheez ko sach me behtar feel karwane lagta hai (Placebo Effect).',
    oneLineHinglish: 'Dimaag ka dhokha: Daam dekh kar quality ka andaza lagana.',
    summary30sHinglish: 'Stanford ke professor Baba Shiv ne prove kiya ki jab logo ko ek hi painkiller di gayi—ek ko bola gaya ₹200 ki hai aur doosre ko bola gaya ₹5 ki hai—to ₹200 wali goli ne sir-dard sach me 50% zyada gayab kar diya! Dimaag mehnge daam par believe kar leta hai.',
    coreConceptHinglish: 'Jab hume kisi cheez ka technical knowledge nahi hota (jaise skin care, wine, ya luxury ghadi), to hamara dimaag price ko hi quality ka saboot maan leta hai. Is chakkar me brands wahi sasta tel sundar bottle me daal kar 50 guna munafa kamate hain.',
    summary60sHinglish: 'Companies janti hain ki agar wo price kam karengi to log sochenge "kuch kharaab hoga". Isliye wo jaan-boojh kar daam double kar deti hain taaki logo ko lage ki product premium hai. Dimaag ke fMRI scan me dikhta hai ki mehngi cheez consume karte waqt dimaag sach me zyada pleasure signals generate karta hai.',
    howItWorksHinglish: 'Bada price tag dekha -> Dimaag ne bola "Yeh to world-class hai" -> Dopamine aur expectation badha -> Asli anubhav me sach me maza aaya -> Mehnga bill justify kiya.',
    howToRespondHinglish: 'Ingredients check karein: Bottle ke peeche composition padho. 90% mehnge cosmetics aur generic medicines me wahi sasta formula hota hai jo generic brand me milta hai.',
    takeawaysHinglish: [
      'Mehnga price tag dimaag ke andar placebo effect trigger karta hai',
      'Same dawai zyada asar karti hai agar patient ko lage ki wo bohot mehngi hai',
      'Brands daam badha kar exclusivity aur premium image create karte hain',
      'Packaging par mat jao, peeche chemical ingredients aur technical specs padho'
    ],
    pqPromptHinglish: 'Do identical energy drinks hain. Ek par ₹20 ka tag hai aur doosre par ₹150 ka. Research ke mutabiq log kaisa perform karenge?',
    pqExplanationHinglish: '₹150 wale drink ka price expectation dimaag me placebo effect create karta hai jisse unka focus sach me badhta hai.',
    pqOptionsHinglish: [
      { id: 'opt_a', text: 'Dono ka performance bilkul barabar hoga kyuki drink andar se same hai.', isCorrect: false, feedback: 'Galat. Human brain expectation se perform karta hai.' },
      { id: 'opt_b', text: '₹150 wala drink peene wale puzzles me behtar perform karenge placebo effect ke chalte.', isCorrect: true, feedback: 'Sahi! Baba Shiv ki Stanford study ne yahi prove kiya tha.' },
      { id: 'opt_c', text: '₹20 wala behtar karega kyuki usme guilt kam hota hai.', isCorrect: false, feedback: 'Galat. Sasti cheez par low efficacy ka shak hota hai.' }
    ],
    hiTitle: 'मूल्य-गुणवत्ता स्वयंसिद्ध (Price-Quality Heuristic)',
    hiSummary: 'उच्च मूल्य को सीधे तौर पर श्रेष्ठ गुणवत्ता या प्रभावशीलता का प्रमाण मान लेने की संज्ञानात्मक प्रवृत्ति और उसका प्लेसबो प्रभाव।',
    hiTakeaways: ['मूल्य प्रत्याशा मस्तिष्क में वास्तविक जैविक प्रभाव उत्पन्न करती है', 'महंगी वस्तुएं अधिक प्रभावशीलता का भ्रम पैदा करती हैं', 'मूल्य के बजाय अवयवों (Ingredients) की सत्यता जांचें'],
    guTitle: 'કિંમત-ગુણવત્તા પૂર્વગ્રહ (Price-Quality Heuristic)', guSummary: 'વધુ કિંમત જોઈને ગુણવત્તા શ્રેષ્ઠ જ હશે તેવું માની લેવાની ગ્રાહકની માનસિકતા.', guTakeaways: ['વધુ કિંમત ઉત્કૃષ્ટતાની ગેરંટી નથી', 'પ્લેસિબો અસરથી સાવચેત રહો', 'ઘટકો અને ગુણવત્તા તપાસો'],
    mrTitle: 'किंमत-गुणवत्ता गृहीतक (Price-Quality Heuristic)', mrSummary: 'जास्त किंमत म्हणजे उच्च दर्जा असे गृहीत धरण्याची आणि त्यातून प्लेसिबो अनुभव घेण्याची मानवी प्रवृत्ती.', mrTakeaways: ['किमतीवरून दर्जा ठरवू नका', 'प्लेसिबो इफेक्ट ओळखा', 'घटकांची पडताळणी करा'],
    teTitle: 'ధర-నాణ్యత సహజ జ్ఞానం (Price-Quality Heuristic)', teSummary: 'ఎక్కువ ధర ఉంటే నాణ్యత కూడా అత్యున్నతంగా ఉంటుందని భావించే మానసిక అలవాటు.', teTakeaways: ['ధర నాణ్యతకు కొలమానం కాదు', 'ప్లేసిబో ప్రభావాన్ని గుర్తించండి', 'విషయ సూచికను పరిశీలించండి'],
    taTitle: 'விலை-தரம் சார்ந்த உளவியல் (Price-Quality Heuristic)', taSummary: 'அதிக விலை கொண்ட பொருட்கள் தரமானதாக இருக்கும் என்று தானாகவே நம்பும் மனப்பான்மை.', taTakeaways: ['அதிக விலை தரத்தின் அடையாளம் அல்ல', 'நம்பிக்கை மாயையை உணருங்கள்', 'உண்மையான மூலப்பொருட்களை சோதிக்கவும்'],
    knTitle: 'ಬೆಲೆ-ಗುಣಮಟ್ಟದ ಮಾನಸಿಕ ಪಕ್ಷಪಾತ', knSummary: 'ಹೆಚ್ಚಿನ ಬೆಲೆಯನ್ನು ಕಂಡಾಗ ಅದು ಉತ್ತಮ ಗುಣಮಟ್ಟದ್ದೇ ಎಂದು ನಂಬುವ ಸಾಮಾನ್ಯ ಗ್ರಾಹಕ ಪ್ರವೃತ್ತಿ.', knTakeaways: ['ಬೆಲೆಯೇ ಗುಣಮಟ್ಟದ ಮಾನದಂಡವಲ್ಲ', 'ಪ್ಲೇಸಿಬೊ ಪರಿಣಾಮವನ್ನು ಅರಿಯಿರಿ', 'ಘಟಕಗಳನ್ನು ಪರಿಶೀಲಿಸಿ'],
    mlTitle: 'വില-ഗുണനിലവാര മിഥ്യാധാരണ (Price-Quality Heuristic)', mlSummary: 'കൂടിയ വില ഉയർന്ന ഗുണനിലവാരത്തിന്റെ തെളിവാണെന്ന് സ്വയം വിശ്വസിക്കുന്ന ഉപഭോക്തൃ സ്വഭാവം.', mlTakeaways: ['വില ഗുണനിലവാരത്തിന്റെ മാനദണ്ഡമല്ല', 'പ്ലേസിബോ പ്രഭാവം തിരിച്ചറിയുക', 'ഉള്ളടക്കം പരിശോധിച്ച് വാങ്ങുക'],
    bnTitle: 'মূল্য-গুণমান মানসিক পক্ষপাত (Price-Quality Heuristic)', bnSummary: 'উচ্চ মূল্য দেখে কোনো পণ্যের গুণমান স্বয়ংক্রিয়ভাবে ভালো বলে ধরে নেওয়ার মনস্তাত্ত্বিক ভ্রান্তি।', bnTakeaways: ['অধিক মূল্য মানেই ভালো গুণমান নয়', 'প্লাসিবো প্রভাব সম্পর্কে সচেতন থাকুন', 'উপাদান যাচাই করে কিনুন'],
    paTitle: 'ਕੀਮਤ-ਗੁਣਵੱਤਾ ਦਾ ਭੁਲੇਖਾ (Price-Quality Heuristic)', paSummary: 'ਮਹਿੰਗੀ ਕੀਮਤ ਦੇਖ ਕੇ ਕਿਸੇ ਚੀਜ਼ ਨੂੰ ਆਪਣੇ-ਆਪ ਵਧੀਆ ਮੰਨ ਲੈਣ ਦੀ ਮਾਨਸਿਕ ਆਦਤ।', paTakeaways: ['ਮਹਿੰਗੀ ਚੀਜ਼ ਹਮੇਸ਼ਾ ਚੰਗੀ ਨਹੀਂ ਹੁੰਦੀ', 'ਪਲੇਸੀਬੋ ਪ੍ਰਭਾਵ ਨੂੰ ਸਮਝੋ', 'ਅਸਲ ਗੁਣਾਂ ਦੀ ਜਾਂਚ ਕਰੋ'],
    urTitle: 'قیمت اور معیار کا مغالطہ (Price-Quality Heuristic)', urSummary: 'زیادہ قیمت دیکھ کر کسی چیز کو لازمی طور پر اعلیٰ معیار کا سمجھنے کا نفسیاتی وہم۔', urTakeaways: ['زیادہ قیمت اچھے معیار کی ضامن نہیں', 'پلاسیبو اثر کو سمجھیں', 'اجزاء کی جانچ کر کے خریدیں'],
    orTitle: 'ମୂଲ୍ୟ-ଗୁଣବତ୍ତା ଭ୍ରାନ୍ତି (Price-Quality Heuristic)', orSummary: 'ଅଧିକ ମୂଲ୍ୟ ଦେଖି କୌଣସି ଜିନିଷକୁ ଶ୍ରେଷ୍ଠ ବୋଲି ମାନିନେବାର ମନସ୍ତାତ୍ତ୍ୱିକ ପ୍ରବୃତ୍ତି।', orTakeaways: ['ଅଧିକ ଦାମ୍ ଗୁଣବତ୍ତାର ପ୍ରମାଣ ନୁହେଁ', 'ପ୍ଲେସିବୋ ପ୍ରଭାବ ବୁଝନ୍ତୁ', 'ସାମଗ୍ରୀର ଉପାଦାନ ଦେଖନ୍ତୁ'],
    asTitle: 'মূল্য-গুণগত মানসিক ধাৰণা (Price-Quality Heuristic)', asSummary: 'অধিক মূল্য দেখিলেই বস্তু এটা উন্নত মানৰ বুলি ধৰি লোৱাৰ মানৱীয় মানসিকতা।', asTakeaways: ['বেছি দাম মানেই ভাল গুণ নহয়', 'প্লেচীব’ প্ৰভাৱৰ বিষয়ে জানক', 'উপাদান পৰীক্ষা কৰি লওক']
  },

  {
    fileName: 'zeroPriceEffect.ts',
    varName: 'zero_price_effect',
    id: 'zero_price_effect',
    categoryId: 'consumer_advertising',
    slug: 'zero-price-effect',
    difficulty: 'beginner',
    readTime: 5,
    sortWeight: 7,
    titleEn: 'The Zero Price Effect: The Irrational Magnetism of "Free"',
    subtitleEn: 'Dan Ariely’s MIT truffle experiment on why zero is an emotional hot button, not just another price.',
    shortDescEn: 'A psychological phenomenon where the demand for a good, service, or bundle increases exponentially when its price drops to exactly zero, far beyond standard rational economic models.',
    oneLineEn: 'Zero is not just a price; it is an emotional trigger that disables rational trade-off math.',
    summary30sEn: 'Demonstrated in landmark research by Kristina Shampanier, Nina Mazar, and Dan Ariely at MIT, "Free" is a psychological superpower. When given a choice between a luxury Lindt truffle for 15 cents and an ordinary Hershey’s Kiss for 1 cent, 73% chose the luxury truffle. But when both prices were reduced by just one cent (14 cents vs. Free), 69% switched to the inferior Kiss!',
    coreConceptEn: 'In classical economics, a 1-cent price drop should produce the exact same shift in demand across options. But the difference between ₹1 and ₹0 is psychologically infinite compared to the difference between ₹2 and ₹1. The price of zero eliminates the "pain of paying" and eliminates the perceived risk of making a mistake, creating a flood of positive affect.',
    summary60sEn: 'Retailers leverage the Zero Price Effect through "Buy One Get One Free", "Free Shipping with ₹999", and "Free Gift with Purchase". Consumers routinely spend ₹400 on extra unneeded items just to avoid a ₹50 shipping fee, acting completely counter to their own financial self-interest.',
    takeawaysEn: [
      'Zero is an emotional trigger that eliminates the perceived possibility of loss',
      'A 1-cent drop from 1 to 0 produces a massive non-linear surge in consumer demand',
      'Consumers routinely overspend hundreds of rupees just to qualify for "Free" shipping',
      'Nothing is free; the cost is paid in personal attention, data, time, or surplus buying'
    ],
    whyItHappensEn: 'Loss aversion and affect heuristic: humans hate losing; paying even 1 rupee involves risk and loss, but zero feels risk-free.',
    evolutionaryEn: 'Opportunistic foraging: discovering calories or tools that required zero energetic expenditure provided an uncontested survival dividend.',
    howItWorksEn: 'Option A (Luxury @ ₹10) vs Option B (Standard @ ₹1) -> Both reduced by ₹1 -> Option A @ ₹9 vs Option B @ Free -> Brain perceives zero risk in B -> Disregards superior value in A -> Chooses inferior free item.',
    visualHeadlineEn: 'Rational Economic Step vs. The Zero Price Abyss',
    visualDescEn: 'Ariely’s MIT truffle pricing experiment visualized.',
    sideALabelEn: '15¢ Lindt vs. 1¢ Hershey Kiss',
    sideADetailEn: '73% choose Lindt Truffle (superior luxury taste worth the extra 14 cents).',
    sideBLabelEn: '14¢ Lindt vs. FREE Hershey Kiss',
    sideBDetailEn: '69% switch to FREE Hershey Kiss! Rational trade-off calculation completely collapses.',
    researchSummaryEn: 'Shampanier, Mazar & Ariely (2007, Marketing Science) demonstrated across four experiments that the zero price effect cannot be explained by standard economic transaction costs, proving it is driven by emotional affect.',
    refAuthor: 'Shampanier, K., Mazar, N., & Ariely, D.',
    refYear: 2007,
    refTitle: 'Zero as a Special Price: The True Value of Free Products',
    refCitation: 'Shampanier, K., et al. (2007). Marketing Science, 26(6), 742–757.',
    refDoi: 'https://doi.org/10.1287/mksc.1060.0254',
    scenarioTitleEn: 'The Free Shipping Trap in South Delhi',
    scenarioContextEn: 'Karan was buying a ₹650 book online in South Delhi. At checkout, delivery was ₹60. The banner said: "Add ₹350 more to get FREE Delivery!" Karan spent 35 minutes searching the site and bought a ₹450 water bottle he didn’t need, spending ₹1,100 instead of ₹710.',
    scenarioBiasEn: 'Karan fell victim to the Zero Price Effect: he spent ₹450 in actual cash purely to experience the psychological dopamine of "saving" ₹60 on shipping.',
    scenarioOptimalEn: 'Calculate the net ledger: paying ₹60 shipping saves ₹390 in hard currency compared to adding unneeded junk.',
    scenarioReflectionEn: 'Have you ever waited in a 45-minute queue in the summer heat for a "free" ice cream cone or promotional umbrella worth ₹100?',
    howToRecognizeEn: 'Feeling an overwhelming impulse to take a sample, qualify for a freebie, or grab an item solely because the price tag says "₹0".',
    whereEn: 'E-commerce checkout shipping tiers, buffet dining, free smartphone apps (selling user data), and exhibition freebies.',
    misconceptionsEn: 'Myth: "Taking free stuff has no downside." Fact: Free items clutter physical living space, consume precious time, and often tie you to expensive recurring maintenance or upgrades.',
    limitationsEn: 'When the free item is something you were 100% committed to purchasing anyway, qualifying for free shipping without extra spending is genuine optimization.',
    howToRespondEn: 'The Dollar Substitute Test: Ask yourself: "If this free gift had a price tag of ₹20, would I reach into my wallet and pay cash for it?" If not, reject the freebie.',
    defensesEn: [
      { title: 'The Shipping Fee Discipline', instruction: 'Treat shipping fees as standard transaction overhead; never add extra cart items to avoid a shipping charge under ₹100.' },
      { title: 'The Hidden Cost Audit', instruction: 'Whenever a digital service or app is free, audit the true currency: how is your attention, privacy, or behavioral data being monetized?' }
    ],
    pqPromptEn: 'An online clothing store offers a shirt for ₹1,200 with ₹100 delivery, or a bundle with an ugly pair of socks for ₹1,500 with FREE delivery. How should a rational consumer decide?',
    pqScenarioEn: 'The consumer loves the shirt but will never wear the socks.',
    pqExplanationEn: 'The Zero Price Effect tempts people to pay ₹300 extra just to see the word "FREE" next to shipping. Paying the delivery fee results in a net saving of ₹200.',
    pqAntidoteEn: 'Compare total out-of-pocket costs directly (₹1,300 vs ₹1,500) rather than focusing on shipping.',
    pqOptionsEn: [
      { id: 'opt_a', text: 'Buy the ₹1,500 bundle because paying for shipping is a waste of money.', isCorrect: false, feedback: 'Incorrect. You spend ₹200 more in total cash.' },
      { id: 'opt_b', text: 'Pay ₹1,200 + ₹100 shipping = ₹1,300, saving ₹200 in total out-of-pocket cash.', isCorrect: true, feedback: 'Correct! Total expenditure is what matters, not whether shipping is zero.' },
      { id: 'opt_c', text: 'Email the CEO demanding free clothes.', isCorrect: false, feedback: 'Incorrect. Unrealistic and unproductive.' }
    ],
    reflectionPromptEn: 'What is one useless promotional item currently cluttering your house that you only brought home because it was "free"?',
    titleHinglish: 'The Zero Price Effect: "Muft" Ka Zeher',
    subtitleHinglish: 'Dan Ariely ki research: Kyu "FREE" sunte hi hamara dimaag dimaag lagana band kar deta hai.',
    shortDescHinglish: 'Zero ka psychological trigger: Kaise log ₹50 ki delivery bachane ke liye ₹500 ka faltu samaan khareed lete hain.',
    oneLineHinglish: 'Free koi price nahi hai, yeh ek emotional nasha hai jo calculation ko khatam kar deta hai.',
    summary30sHinglish: 'Dan Ariely ne MIT me experiment kiya: Ek 15 cent ki luxury chocolate thi aur 1 cent ki normal chocolate. 73% logo ne luxury chocolate chuni. Par jab dono ka daam 1 cent kam kiya (14 cent vs FREE), to 69% log sasti chocolate lene bhaage! "Free" shabd logic ko hila deta hai.',
    coreConceptHinglish: 'Zero me koi risk nahi lagta. Jab hum ₹1 bhi dete hain to lagta hai nuksan ho sakta hai, par Free me lagta hai "kya hi jayega". Iska fayda utha kar online sites kehti hain: "₹500 ka aur samaan lo aur ₹60 ki Free delivery pao!" Aur log fas jate hain.',
    summary60sHinglish: 'Zindagi me kuch bhi free nahi hota. Jo app free hai, wahan aapka data aur attention bika raha hai. Aur jo free delivery hai, uske chakkar me aap hazaro rupaye ka kachra ghar le aate hain. Free cheez lene se pehle socho: "Kya main iske liye ₹10 bhi deta?"',
    howItWorksHinglish: 'Cart me ₹600 ka samaan -> Delivery fee ₹50 dikhi -> Banner aaya "Add ₹400 for FREE delivery" -> ₹400 ka bekaar samaan add kiya -> ₹50 bachane ke chakkar me ₹350 extra kharch kiye.',
    howToRespondHinglish: 'Total Cost Rule: Shipping fee ko normal service charge mano. Kabhi bhi delivery fee bachane ke liye aisi cheez mat khareedo jiski zaroorat na ho.',
    takeawaysHinglish: [
      '"Free" sunte hi dimaag ka rational hissa switch off ho jata hai',
      'Delivery fee bachane ke chakkar me log har saal hazaaron rupaye faltu kharch karte hain',
      'Free gifts ghar me kachra aur dimaag me distraction laate hain',
      'Hamesha total bill dekho, "Free" ka sticker mat dekho'
    ],
    pqPromptHinglish: 'Amazon par ₹500 ki t-shirt par ₹50 delivery lag rahi hai. "Free delivery" ke liye ₹300 ka aur samaan lena padega. Kya karna chahiye?',
    pqExplanationHinglish: '₹550 pay karna ₹800 pay karne se ₹250 sasta hai. Shipping fee pay karna financially smart hai.',
    pqOptionsHinglish: [
      { id: 'opt_a', text: '₹300 ki faltu socks add kar lena taaki delivery free ho jaye.', isCorrect: false, feedback: 'Galat. Aapne ₹250 extra kharch kar diye.' },
      { id: 'opt_b', text: '₹50 delivery dekar ₹550 me order khatam karna, kyuki yeh ₹800 se ₹250 sasta hai.', isCorrect: true, feedback: 'Sahi! Total out-of-pocket paisa bachana hi samajhdari hai.' },
      { id: 'opt_c', text: 'Shopping karna hi chhod dena.', isCorrect: false, feedback: 'Galat. Agar zaroorat hai to sasta option choose karein.' }
    ],
    hiTitle: 'शून्य मूल्य प्रभाव (The Zero Price Effect)',
    hiSummary: 'किसी वस्तु का मूल्य शून्य (मुफ़्त) होते ही उसकी मांग में आने वाली अत्यधिक अतार्किक वृद्धि का मनोवैज्ञानिक विश्लेषण।',
    hiTakeaways: ['मुफ़्त शब्द मस्तिष्क में तार्किक मूल्यांकन को समाप्त कर देता है', 'डिलिवरी शुल्क बचाने के चक्कर में अधिक खर्च से बचें', 'कुल व्यय का हिसाब लगाएं, मुफ़्त के प्रलोभन से बचें'],
    guTitle: 'શૂન્ય કિંમત અસર (મફતનું આકર્ષણ)', guSummary: 'કોઈપણ વસ્તુ મફત મળતી હોય ત્યારે તાર્કિક ગણતરી ભૂલી જવાની ગ્રાહકની માનસિકતા.', guTakeaways: ['મફત પાછળનો છૂપો ખર્ચ સમજો', 'ડિલિવરી ચાર્જ બચાવવા વધારાનો ખર્ચ ન કરો', 'કુલ ખર્ચ પર ધ્યાન આપો'],
    mrTitle: 'शून्य किंमत प्रभाव (मोफतची भुरळ)', mrSummary: 'वस्तू मोफत मिळताच तार्किक विचार बाजूला सारून ती मिळवण्याची मानवी मनाची अतार्किक ओढ.', mrTakeaways: ['मोफतच्या मोहात पडू नका', 'डिलिव्हरी शुल्कापेक्षा जास्त खर्च टाळा', 'एकूण खर्चाचा विचार करा'],
    teTitle: 'సున్నా ధర ప్రభావం (ఉచితం అనే ఆకర్షణ)', teSummary: 'ఏదైనా వస్తువు ఉచితంగా లభించినప్పుడు తార్కిక ఆలోచనను కోల్పోయే వినియోగదారుల మానసిక ప్రవర్తన.', teTakeaways: ['ఉచితం వెనుక దాగివున్న ఖర్చును గ్రహించండి', 'డెలివరీ ఛార్జీల కోసం ఎక్కువ కొనవద్దు', 'మొత్తం ఖర్చును లెక్కించండి'],
    taTitle: 'பூஜ்ஜிய விலை விளைவு (இலவசத்தின் ஈர்ப்பு)', taSummary: 'ஒரு பொருள் இலவசம் என்றவுடன் தர்க்கரீதியான கணக்குகளை மறந்து வாங்கும் மனித மனோபாவம்.', taTakeaways: ['இலவசத்தின் மாயையில் விழாதீர்கள்', 'டெலிவரி கட்டணத்தை தவிர்க்க வீண் செலவு செய்யாதீர்கள்', 'மொத்த செலவை பாருங்கள்'],
    knTitle: 'ಶೂನ್ಯ ಬೆಲೆಯ ಪರಿಣಾಮ (ಉಚಿತದ ಆಕರ್ಷಣೆ)', knSummary: 'ಯಾವುದಾದರೂ ವಸ್ತು ಉಚಿತ ಎಂದಾಗ ತಾರ್ಕಿಕ ಲೆಕ್ಕಾಚಾರಗಳನ್ನು ಮರೆತು ಮುಗಿಬೀಳುವ ಮಾನಸಿಕ ಪ್ರವೃತ್ತಿ.', knTakeaways: ['ಉಚಿತದ ಹಿಂದಿನ ತಂತ್ರವನ್ನು ತಿಳಿಯಿರಿ', 'ಡೆಲಿವರಿ ಶುಲ್ಕ ಉಳಿಸಲು ಹೆಚ್ಚು ಖರ್ಚು ಮಾಡಬೇಡಿ', 'ಒಟ್ಟು ವೆಚ್ಚವನ್ನು ಗಮನಿಸಿ'],
    mlTitle: 'പൂജ്യം വില പ്രഭാവം (സൗജന്യത്തിന്റെ ആകർഷണം)', mlSummary: 'സൗജന്യമായി ലഭിക്കുമ്പോൾ യുക്തിസഹമായ കണക്കുകൂട്ടലുകൾ ഉപേക്ഷിച്ച് സാധനങ്ങൾ വാങ്ങുന്ന രീതി.', mlTakeaways: ['സൗജന്യങ്ങളുടെ ചതിക്കുഴികൾ തിരിച്ചറിയുക', 'ഡെലിവറി ചാർജ് ഒഴിവാക്കാൻ കൂടുതൽ വാങ്ങരുത്', 'മൊത്തം ചെലവ് കണക്കാക്കുക'],
    bnTitle: 'শূন্য মূল্য প্রভাব (বিনামূল্যের অন্ধ মোহ)', bnSummary: 'কোনো পণ্য বিনামূল্যে পেলেই অযৌক্তিক চাহিদার ব্যাপক বৃদ্ধি ঘটার মনস্তাত্ত্বিক সত্যতা।', bnTakeaways: ['বিনামূল্যের প্রলোভন থেকে দূরে থাকুন', 'ডেলিভারি চার্জ বাঁচাতে অতিরিক্ত খরচ করবেন না', 'মোট খরচের হিসাব রাখুন'],
    paTitle: 'ਜ਼ੀਰੋ ਕੀਮਤ ਦਾ ਪ੍ਰਭਾਵ (ਮੁਫ਼ਤ ਦਾ ਲਾਲਚ)', paSummary: 'ਕੋਈ ਚੀਜ਼ ਮੁਫ਼ਤ ਮਿਲਣ ਤੇ ਤਰਕਸ਼ੀਲ ਸੋਚ ਨੂੰ ਛੱਡ ਕੇ ਉਸਦੇ ਪਿੱਛੇ ਭੱਜਣ ਦੀ ਮਾਨਸਿਕ ਆਦਤ।', paTakeaways: ['ਮੁਫ਼ਤ ਦੇ ਲਾਲਚ ਤੋਂ ਬਚੋ', 'ਡਿਲੀਵਰੀ ਫੀਸ ਬਚਾਉਣ ਲਈ ਵਾਧੂ ਖਰਚ ਨਾ ਕਰੋ', 'ਕੁੱਲ ਬਿੱਲ ਵੱਲ ਧਿਆਨ ਦਿਓ'],
    urTitle: 'صفر قیمت کا اثر (مفت کا لالچ)', urSummary: 'کسی چیز کے مفت ملنے پر عقلی سوچ اور حساب کتاب کو بالائے طاق رکھنے کا نفسیاتی رجحان۔', urTakeaways: ['مفت کے دھوکے سے بچیں', 'ڈیلیوری چارجز بچانے کے لیے زیادہ خرچ نہ کریں', 'کل لاگت کا حساب لگائیں'],
    orTitle: 'ଶୂନ୍ୟ ମୂଲ୍ୟ ପ୍ରଭାବ (ମାଗଣାର ମୋହ)', orSummary: 'କୌଣସି ଜିନିଷ ମାଗଣାରେ ମିଳିଲେ ଯୁକ୍ତିଯୁକ୍ତ ଚିନ୍ତାଧାରା ଭୁଲିଯିବାର ମାନସିକ ଦୁର୍ବଳତା।', orTakeaways: ['ମାଗଣାର ମାୟାଜାଲ ବୁଝନ୍ତୁ', 'ଡେଲିଭରୀ ଫି ବଞ୍ଚାଇବାକୁ ଅଧିକ ଖର୍ଚ୍ଚ କରନ୍ତୁ ନାହିଁ', 'ମୋଟ ଖର୍ଚ୍ଚ ଉପରେ ନଜର ରଖନ୍ତୁ'],
    asTitle: 'শূন্য মূল্যৰ প্ৰভাৱ (বিনামূলীয়াৰ অন্ধ মোহ)', asSummary: 'কোনো বস্তু বিনামূলীয়াকৈ পালে যুক্তি-তৰ্ক পাহৰি তাৰ প্ৰতি আকৃষ্ট হোৱাৰ মানৱীয় মানসিকতা।', asTakeaways: ['বিনামূলীয়াৰ প্ৰলোভনৰ পৰা আঁতৰি থাকক', 'ডেলিভাৰী মাচুল বচাবলৈ অতিৰিক্ত খৰচ নকৰিব', 'মুঠ খৰচৰ হিচাপ ৰাখক']
  },

  {
    fileName: 'veblenSnobEffect.ts',
    varName: 'veblen_snob_effect',
    id: 'veblen_snob_effect',
    categoryId: 'consumer_advertising',
    slug: 'veblen-and-snob-effect',
    difficulty: 'intermediate',
    readTime: 6,
    sortWeight: 8,
    titleEn: 'The Veblen & Snob Effect: Conspicuous Consumption and Social Signaling',
    subtitleEn: 'Thorstein Veblen and Harvey Leibenstein on why people buy luxury goods specifically because they are expensive and exclusive.',
    shortDescEn: 'Economic anomalies where demand for a luxury good increases as its price rises (Veblen Good) and decreases as more people own it (Snob Effect), driven by evolutionary status signaling.',
    oneLineEn: 'Buying things not for their utility, but to broadcast that you have the wealth to waste.',
    summary30sEn: 'Coined by economist Thorstein Veblen in 1899 and formalized by Harvey Leibenstein in 1950, Veblen and Snob effects defy the law of demand. People do not buy a Rolex, a Hermès Birkin bag, or an iPhone Pro for their technical functionality; they buy them precisely because the high price acts as an unforgeable biological signal of wealth, prestige, and high social rank.',
    coreConceptEn: 'Amotz Zahavi’s evolutionary "Handicap Principle" explains why conspicuous consumption works: an honest signal must be costly to be credible. Just as a peacock’s heavy, colorful tail handicaps its survival to prove genetic fitness to peahens, wasting capital on overpriced luxury goods proves to the tribe that one has surplus resources to burn.',
    summary60sEn: 'The "Snob Effect" dictates that once a luxury brand becomes too accessible to the middle class (losing exclusivity), true elites abandon it for obscure, harder-to-acquire alternatives. Luxury conglomerates intentionally burn unsold stock, enforce artificial waitlists, and raise prices annually to preserve this snob prestige barrier.',
    takeawaysEn: [
      'Veblen goods violate the law of demand: demand rises as the price increases',
      'The Snob Effect causes demand to crash if an item becomes widely accessible to the masses',
      'Conspicuous luxury consumption is evolutionary status signaling (Handicap Principle)',
      'True financial security is quiet wealth; loud luxury is often debt-financed status anxiety'
    ],
    whyItHappensEn: 'Costly signaling theory: displaying surplus resources without immediate survival utility serves as an honest indicator of social and sexual fitness.',
    evolutionaryEn: 'In ancestral groups, individuals with surplus resources attracted superior mating opportunities and political protection.',
    howItWorksEn: 'Brand raises price from ₹2 Lakh to ₹5 Lakh -> Middle-class buyers priced out -> Perceived status signal increases -> Ultra-wealthy desire item more -> Sales volume and margins expand.',
    visualHeadlineEn: 'Standard Economic Good vs. Veblen Status Good',
    visualDescEn: 'Comparing traditional downward sloping demand against the upward sloping Veblen curve.',
    sideALabelEn: 'Standard Good (Price Elasticity)',
    sideADetailEn: 'Price rises -> Demand drops. (e.g., cooking oil, laptops, train tickets). Utility-driven.',
    sideBLabelEn: 'Veblen Good (Status Elasticity)',
    sideBDetailEn: 'Price rises -> Demand surges! (e.g., Rolex Daytona, Birkin Bags). Signaling-driven.',
    researchSummaryEn: 'Leibenstein (1950, Quarterly Journal of Economics) and Bagwell & Bernheim (1996, American Economic Review) mathematically modeled the signaling equilibria of conspicuous consumption and snob preferences.',
    refAuthor: 'Veblen, T. & Leibenstein, H.',
    refYear: 1899,
    refTitle: 'The Theory of the Leisure Class / Bandwagon, Snob, and Veblen Effects',
    refCitation: 'Leibenstein, H. (1950). Quarterly Journal of Economics, 64(2), 183–207.',
    refDoi: 'https://doi.org/10.2307/1882692',
    scenarioTitleEn: 'The ₹1.5 Lakh Phone EMI in Delhi NCR',
    scenarioContextEn: 'Kunal earns ₹45,000 per month as a junior designer in Noida. When the latest flagship phone launched at ₹1,60,000, he took out an 18-month predatory high-interest EMI to buy it, putting the phone face-up on every restaurant table he visited so others would see the distinctive three-camera lens.',
    scenarioBiasEn: 'Kunal engaged in compensatory conspicuous consumption: he sacrificed his nutritional and investment savings to purchase a Veblen status signal that would mask his financial insecurity.',
    scenarioOptimalEn: 'Remember that displaying luxury items signals consumption, not wealth. Shift identity toward building invisible, income-producing assets (equity, real estate, emergency funds).',
    scenarioReflectionEn: 'Have you ever bought an expensive branded item primarily so that coworkers, relatives, or peers would perceive you as successful?',
    howToRecognizeEn: 'Feeling a desire for an item multiply after finding out how expensive it is, or losing interest in a brand the moment everyone in your neighborhood starts wearing it.',
    whereEn: 'Luxury watches, designer sneakers, exclusive private clubs, VIP airport lounges, and flagship smartphones.',
    misconceptionsEn: 'Myth: "People buy luxury because the materials are 10x better." Fact: Manufacturing costs of luxury goods are typically 5% to 10% of the retail price; 90% is pure status rent.',
    limitationsEn: 'When high prices correlate with genuine artisanal longevity (e.g. hand-stitched Goodyear-welted leather boots that last 25 years), the purchase is driven by durability utility, not Veblen signaling.',
    howToRespondEn: 'The "Invisible Wealth" Rule: Never spend money on visible consumer badges to impress people you don\'t respect; channel capital into assets that generate dividends rather than depreciation.',
    defensesEn: [
      { title: 'The Status Inversion Drill', instruction: 'Recognize that the ultra-wealthy often dress in unbranded, simple clothes ("stealth wealth"), while loud logos are marketed to the insecure middle class.' },
      { title: 'The 30-Day Luxury Waiting Period', instruction: 'Force a mandatory 30-day delay on all luxury purchases over ₹10,000 to allow the dopamine signaling impulse to dissipate.' }
    ],
    pqPromptEn: 'A luxury handbag brand raises its prices by 30% without changing the leather or manufacturing quality. In response, their waiting list doubles from 6 months to 12 months. What economic phenomenon explains this?',
    pqScenarioEn: 'The price increase made the item completely unaffordable to upper-middle-class consumers.',
    pqExplanationEn: 'This is the Veblen Good dynamic: the higher price amplifies the item’s scarcity and social signaling value, increasing demand among status-seeking elites.',
    pqAntidoteEn: 'Decouple personal self-worth from expensive consumer signaling.',
    pqOptionsEn: [
      { id: 'opt_a', text: 'The brand discovered a magical new leather tanning process.', isCorrect: false, feedback: 'Incorrect. The product specifications remained unchanged.' },
      { id: 'opt_b', text: 'The price hike transformed the handbag into a stronger Veblen signal of exclusivity, boosting elite desire.', isCorrect: true, feedback: 'Correct! Higher price increases status utility and triggers the Veblen effect.' },
      { id: 'opt_c', text: 'Inflation made consumers richer overnight.', isCorrect: false, feedback: 'Incorrect. Inflation reduces real purchasing power.' }
    ],
    reflectionPromptEn: 'If nobody in the world could ever see your clothes, watch, or car, what would you choose to buy based purely on personal comfort?',
    titleHinglish: 'Veblen & Snob Effect: Ameeri Ka Dikhaawa Aur Status Ka Khel',
    subtitleHinglish: 'Kyu log ₹1.5 lakh ka phone aur ₹5 lakh ki ghadi utility ke liye nahi, balki aukat dikhane ke liye khareedte hain.',
    shortDescHinglish: 'Thorstein Veblen aur Leibenstein ki research: Cheez jitni mehngi hoti hai log utna zyada khareedte hain taaki samaj me status ban sake.',
    oneLineHinglish: 'Cheez kaam ke liye nahi, balki yeh dikhane ke liye khareedna ki mere paas barbaad karne ke liye paisa hai.',
    summary30sHinglish: '1899 me Thorstein Veblen ne dekha ki aam cheezon me daam badhta hai to demand kam hoti hai, par Luxury cheezon (Veblen goods) me daam badhane par demand aur badh jati hai! Rolex ya iPhone log time dekhne ya call karne ke liye nahi, balki status dikhane ke liye khareedte hain.',
    coreConceptHinglish: 'Biology me mor (peacock) ke bhaari aur chamakdaar pankh shikaari se bachne me rukawat bante hain, par mor unhe dikhata hai taaki morani ko lage ki wo kitna powerful hai (Handicap Principle). Insaan bhi EMI par mehngi gaadi aur kapde lekar yahi dikhaawa karte hain.',
    summary60sHinglish: 'Doosra hota hai "Snob Effect": Jaise hi koi brand aam logo ke haath me aane lagta hai, ameer log use pehanna chhod dete hain aur koi naya anokha brand dhoondte hain. Asli ameer log simple kapde pehante hain ("Stealth Wealth"), jabki EMI par jeene wale loud logos wale kapde pehante hain.',
    howItWorksHinglish: 'Brand ne daam 50% badhaya -> Aam log bahar huye -> Exclusivity badhi -> Status seekers ne aur shauk se khareeda -> Brand ka profit aasmaan chhu gaya.',
    howToRespondHinglish: 'Stealth Wealth mindset apnayein: Un logo ko impress karne ke liye paisa mat udao jinhe aap pasand bhi nahi karte. Paisa show-off me nahi, investments me lagao.',
    takeawaysHinglish: [
      'Veblen goods me daam badhne se demand badhti hai kyuki status badhta hai',
      'Snob effect ke mutabiq ameer log aam logo wali cheez chhod dete hain',
      'Loud logos aksar financial insecurity ko chupane ke liye use kiye jate hain',
      'Asli daulat wo hai jo dikhayi nahi deti (bank balance, equity, mental peace)'
    ],
    pqPromptHinglish: 'Ek designer brand ne bina quality badle apne bag ka daam ₹1 lakh se ₹2 lakh kar diya. Uski sale double ho gayi. Kyu?',
    pqExplanationHinglish: 'Daam badhne se bag ek behtar Veblen status symbol ban gaya jisse ameer logo me uski demand badh gayi.',
    pqOptionsHinglish: [
      { id: 'opt_a', text: 'Bag ke andar sone ke taar lage huye the.', isCorrect: false, feedback: 'Galat. Quality wahi thi.' },
      { id: 'opt_b', text: 'Veblen effect ki wajah se daam badhne par status signaling badh gayi aur demand badh gayi.', isCorrect: true, feedback: 'Sahi! Yahi Veblen good ka standard definition hai.' },
      { id: 'opt_c', text: 'Customer andhe the aur unhe daam nahi dikha.', isCorrect: false, feedback: 'Galat. Customer ne specifically daam dekh kar hi khareeda.' }
    ],
    hiTitle: 'वेबलेन और स्नॉब प्रभाव (Veblen & Snob Effect)',
    hiSummary: 'सामाजिक प्रतिष्ठा, दिखावे और विशिष्टता के प्रदर्शन हेतु मूल्य वृद्धि के साथ विलासिता वस्तुओं की मांग में होने वाली वृद्धि का अध्ययन।',
    hiTakeaways: ['वेबलेन वस्तुएं आर्थिक मांग के सामान्य नियमों का उल्लंघन करती हैं', 'उच्च मूल्य सामाजिक स्थिति और संपन्नता का संकेत देता है', 'दिखावे के उपभोग के बजाय स्थायी संपत्ति निर्माण पर ध्यान दें'],
    guTitle: 'વેબલેન અને સ્નોબ અસર (દિખાવાનો પ્રભાવ)', guSummary: 'સમાજમાં મોભો અને ધનવાન હોવાનું દર્શાવવા માટે મોંઘી વસ્તુઓ ખરીદવાની ગ્રાહકની વૃત્તિ.', guTakeaways: ['દિખાવાથી દૂર રહો', 'બ્રાન્ડ મોહ છોડી ઉપયોગિતા જુઓ', 'વાસ્તવિક સંપત્તિ બનાવો'],
    mrTitle: 'वेबलेन आणि स्नॉब प्रभाव (दिखाऊपणाचे अर्थशास्त्र)', mrSummary: 'समाजात प्रतिष्ठा आणि श्रीमंती दाखवण्यासाठी जाणीवपूर्वक अति-महागड्या वस्तूंची मागणी वाढण्याचे मानसशास्त्र.', mrTakeaways: ['दिखाऊपणाच्या मोहात पडू नका', 'किंमत नव्हे उपयोगिता तपासा', 'अदृश्य संपत्ती निर्माण करा'],
    teTitle: 'వెబ్లెన్ మరియు స్నాబ్ ప్రభావం (దర్పం ప్రదర్శన)', teSummary: 'సమాజంలో హోదా మరియు దర్పం చూపించడానికి అధిక ధర కలిగిన లగ్జరీ వస్తువులను కొనుగోలు చేసే ధోరణి.', teTakeaways: ['దర్ప ప్రదర్శనకు దూరంగా ఉండండి', 'ఉపయోగాన్ని బట్టి కొనండి', 'నిజమైన సంపదను సృష్టించండి'],
    taTitle: 'வெப்லென் மற்றும் ஸ்னாப் விளைவு (ஆடம்பர தற்பெருமை)', taSummary: 'சமூகத்தில் அந்தஸ்தையும் செல்வத்தையும் காட்டிக்கொள்ள அதிக விலை கொண்ட பொருட்களை வாங்கும் உளவியல்.', taTakeaways: ['ஆடம்பர மாயையில் சிக்காதீர்கள்', 'பயன்பாட்டுக்கு முன்னுரிமை கொடுங்கள்', 'உண்மையான சொத்துக்களை உருவாக்குங்கள்'],
    knTitle: 'ವೆಬ್ಲೆನ್ ಮತ್ತು ಸ್ನಾಬ್ ಪರಿಣಾಮ (ಪ್ರತಿಷ್ಠೆಯ ಪ್ರದರ್ಶನ)', knSummary: 'ಸಮಾಜದಲ್ಲಿ ಅಂತಸ್ತು ಮತ್ತು ಸಿರಿವಂತಿಕೆಯನ್ನು ತೋರ್ಪಡಿಸಿಕೊಳ್ಳಲು ದುಬಾರಿ ವಸ್ತುಗಳನ್ನು ಖರೀದಿಸುವ ಮಾನಸಿಕತೆ.', knTakeaways: ['ಆಡಂಬರಕ್ಕೆ ಬಲಿಯಾಗಬೇಡಿ', 'ಉಪಯುಕ್ತತೆಗೆ ಆದ್ಯತೆ ನೀಡಿ', 'ನಿಜವಾದ ಆಸ್ತಿ ಬೆಳೆಸಿಕೊಳ್ಳಿ'],
    mlTitle: 'വെബ്ലെൻ ആന്റ് സ്നോബ് പ്രഭാവം (ആഡംബര പ്രദർശനം)', mlSummary: 'സമൂഹത്തിൽ പദവിയും പ്രൗഢിയും കാണിക്കാൻ വേണ്ടി മാത്രം ഉയർന്ന വിലയുള്ള വസ്തുക്കൾ വാങ്ങിക്കൂട്ടുന്ന രീതി.', mlTakeaways: ['ആഡംബര ഭ്രമം ഉപേക്ഷിക്കുക', 'ഉപയോഗത്തിന് പ്രാധാന്യം നൽകുക', 'യഥാർത്ഥ സമ്പത്ത് കെട്ടിപ്പടുക്കുക'],
    bnTitle: 'ভেবলেন ও স্নব প্রভাব (দেখনদারি আভিজাত্য)', bnSummary: 'সমাজে মর্যাদা ও প্রাচুর্য প্রদর্শনের জন্য উচ্চমূল্যের বিলাসবহুল পণ্যের চাহিদা বৃদ্ধির মনস্তাত্ত্বিক অর্থনীতি।', bnTakeaways: ['দেখনদারির ফাঁদ এড়িয়ে চলুন', 'কার্যকারিতা দেখে কিনুন', 'বাস্তব সম্পদ গঠনে মন দিন'],
    paTitle: 'ਵੈਬਲਨ ਅਤੇ ਸਨੌਬ ਪ੍ਰਭਾਵ (ਦਿਖਾਵੇ ਦੀ ਖਪਤ)', paSummary: 'ਸਮਾਜ ਵਿੱਚ ਆਪਣੀ ਹੈਸੀਅਤ ਅਤੇ ਅਮੀਰੀ ਦਿਖਾਉਣ ਲਈ ਜਾਣਬੁੱਝ ਕੇ ਮਹਿੰਗੀਆਂ ਚੀਜ਼ਾਂ ਖ਼ਰੀਦਣ ਦੀ ਮਾਨਸਿਕ ਆਦਤ।', paTakeaways: ['ਦਿਖਾਵੇ ਦੀ ਖ਼ਰੀਦਦਾਰੀ ਤੋਂ ਬਚੋ', 'ਚੀਜ਼ ਦੀ ਲੋੜ ਸਮਝੋ', 'ਅਸਲ ਪੂੰਜੀ ਇਕੱਠੀ ਕਰੋ'],
    urTitle: 'ویبلین اور اسنوب اثر (نمود و نمائش کا اثر)', urSummary: 'معاشرے میں اپنی امارت اور اونچے رتبے کی نمائش کے لیے مہنگی ترین اشیاء کی خریداری کا نفسیاتی رجحان۔', urTakeaways: ['دکھاوے کے جال سے بچیں', 'افادیت کو ترجیح دیں', 'حقیقی مالی استحکام پیدا کریں'],
    orTitle: 'ଭେବଲେନ୍ ଓ ସ୍ନୋବ୍ ପ୍ରଭାବ (ଦେଖାଣିଆ ମନୋବୃତ୍ତି)', orSummary: 'ସମାଜରେ ପ୍ରତିଷ୍ଠା ଓ ଆଭିଜାତ୍ୟ ପ୍ରଦର୍ଶନ କରିବା ପାଇଁ ଅତ୍ୟଧିକ ମୂଲ୍ୟବାନ ସାମଗ୍ରୀ କ୍ରୟ କରିବାର ମାନସିକତା।', orTakeaways: ['ଦେଖାଣିଆ ଖର୍ଚ୍ଚରୁ ଦୂରେଇ ରୁହନ୍ତୁ', 'ଆବଶ୍ୟକତାକୁ ପ୍ରାଥମିକତା ଦିଅନ୍ତୁ', 'ପ୍ରକୃତ ସମ୍ପତ୍ତି ଗଠନ କରନ୍ତୁ'],
    asTitle: 'ভেবলেন আৰু স্ন’ব প্ৰভাৱ (প্ৰদৰ্শনকামিতাৰ অৰ্থনীতি)', asSummary: 'সমাজত মৰ্যাদা আৰু ঐশ্বৰ্য প্ৰদৰ্শনৰ বাবে অত্যধিক মূল্যৰ বিলাসী সামগ্ৰী ক্ৰয় কৰাৰ মানসিক প্ৰৱণতা।', asTakeaways: ['প্ৰদৰ্শনকামিতা পৰিহাৰ কৰক', 'ব্যৱহাৰযোগ্যতা চাই কিনক', 'বাস্তৱ সম্পদ গঢ়ি তোলক']
  },

  {
    fileName: 'goalGradientEffect.ts',
    varName: 'goal_gradient_effect',
    id: 'goal_gradient_effect',
    categoryId: 'consumer_advertising',
    slug: 'goal-gradient-effect',
    difficulty: 'beginner',
    readTime: 5,
    sortWeight: 9,
    titleEn: 'The Goal-Gradient Effect: The Artificial Finish Line Rush',
    subtitleEn: 'Clark Hull’s behavioral discovery on why people accelerate effort and spending as they approach a reward.',
    shortDescEn: 'The psychological tendency for humans and animals to increase their effort, frequency of action, and motivation as they perceive themselves getting closer to a desired goal or reward.',
    oneLineEn: 'The closer you feel to the finish line, the faster you run and the more you spend.',
    summary30sEn: 'First discovered in 1932 by psychologist Clark Hull with rats in a maze and proven in consumer marketing by Ran Kivetz, Oleg Urminsky, and Yuhuang Zheng in 2006, the Goal-Gradient Effect explains loyalty programs. Customers accelerate coffee purchases as they approach a free 10th cup stamp.',
    coreConceptEn: 'Motivation is not linear; it is an accelerating exponential curve governed by perceived distance to completion. Furthermore, Kivetz proved the power of "Endowed Progress": customers given a 12-stamp loyalty card with 2 pre-stamped bonus circles completed the card twice as fast as customers given a blank 10-stamp card, even though both required purchasing 10 coffees!',
    summary60sEn: 'Consumer platforms exploit this through progress bars (LinkedIn profile completion at 85%), tier status qualification (only 1,200 points to Gold status!), and delivery trackers. By granting illusionary head starts and displaying proximity to rewards, companies trigger urgency and repeat purchases.',
    takeawaysEn: [
      'Effort and spending accelerate dramatically as the finish line approaches',
      'Endowed progress (giving an artificial head start) doubles completion rates',
      'A 12-stamp card with 2 free stamps outperforms a blank 10-stamp card',
      'The antidote is auditing whether you actually want the reward or are just addicted to completing the bar'
    ],
    whyItHappensEn: 'Dopamine reward prediction: dopamine ramps up continuously as spatial or temporal distance to an anticipated reward contracts.',
    evolutionaryEn: 'Predators stalking prey sprint with maximum energy during the final meters when success probability is highest.',
    howItWorksEn: 'Start at Step 1 (Low motivation) -> Reach Step 8 (Dopamine spikes) -> Urge to cross line peaks -> Extra purchases made hastily -> Reward claimed -> Post-achievement motivation crash.',
    visualHeadlineEn: 'Blank 10-Stamp Card vs. 12-Stamp Card with 2 Free Stamps',
    visualDescEn: 'Kivetz’s famous Columbia University loyalty card field experiment.',
    sideALabelEn: 'Blank 10-Stamp Card (0% Complete)',
    sideADetailEn: 'Took 15.6 days to complete; 19% completion rate. Perceived as starting from zero.',
    sideBLabelEn: '12-Stamp Card with 2 Pre-stamps (16% Complete)',
    sideBDetailEn: 'Took only 8.6 days to complete! 34% completion rate! Same 10 coffees, but perceived as an active race.',
    researchSummaryEn: 'Kivetz, Urminsky & Zheng (2006, Journal of Marketing Research) and Hull (1932, Psychological Review) demonstrated that proximity to rewards significantly accelerates purchase velocity and decreases inter-purchase intervals.',
    refAuthor: 'Kivetz, R., Urminsky, O., & Zheng, Y.',
    refYear: 2006,
    refTitle: 'The Goal-Gradient Hypothesis Resurrected: Purchase Acceleration, Illusionary Progress, and Customer Retention',
    refCitation: 'Kivetz, R., et al. (2006). Journal of Marketing Research, 43(1), 39–58.',
    refDoi: 'https://doi.org/10.1509/jmkr.43.1.39',
    scenarioTitleEn: 'The Airline Tier Rush in Mumbai',
    scenarioContextEn: 'Vikram realized on December 20 that he was only 800 tier points away from maintaining his Airline Gold status. He booked a totally unnecessary round-trip weekend flight from Mumbai to Goa for ₹14,000, sat in the airport lounge, and flew back on the same plane just to cross the threshold.',
    scenarioBiasEn: 'Vikram fell into the Goal-Gradient trap: the close proximity of the status finish line triggered an irrational urgency that blinded him to the financial absurdity of the flight.',
    scenarioOptimalEn: 'Calculate the cold cash value of the reward: Gold tier perks (free bags and lounge access) were worth ₹3,000, yet he spent ₹14,000 to acquire them.',
    scenarioReflectionEn: 'Have you ever bought an extra coffee, pizza, or flight purely to fill the last remaining stamp or badge on a loyalty app?',
    howToRecognizeEn: 'Feeling an accelerating impatience and spending urge when you notice a progress meter sitting between 80% and 95% complete.',
    whereEn: 'Coffee loyalty cards, frequent flyer tiers, gaming battle passes, fitness streak apps, and profile setup bars.',
    misconceptionsEn: 'Myth: "Loyalty cards give me free value." Fact: Loyalty programs are engineered behavioral accelerants designed to increase your purchase frequency and total lifetime spend by 20% to 40%.',
    limitationsEn: 'When applied to personal health habits (e.g., closing your Apple Watch fitness rings), the goal-gradient effect can be harnessed as a positive motivational engine.',
    howToRespondEn: 'The Reward Valuation Test: Before making a purchase to complete a streak or tier, calculate: "How much would I pay for this final perk in cash right now?" If less than the required spend, abandon the goal.',
    defensesEn: [
      { title: 'The Tier Rationality Audit', instruction: 'Never spend money to maintain an airline or hotel tier unless the guaranteed future savings exceed the qualification expense.' },
      { title: 'The Artificial Head Start Immunity', instruction: 'When an app gives you "Bonus points just for signing up!", recognize it as an endowed progress hook to drag you into their goal gradient.' }
    ],
    pqPromptEn: 'A coffee shop runs two loyalty promotions. Card A requires 8 stamps (starts blank). Card B requires 10 stamps (comes with 2 stamps already stamped for free). Which card will customers complete faster and why?',
    pqScenarioEn: 'Both cards require purchasing exactly 8 coffees to earn the free drink.',
    pqExplanationEn: 'Card B leverages Endowed Progress and the Goal-Gradient Effect: starting at 20% progress makes customers feel they are already on the home stretch, accelerating purchase frequency.',
    pqAntidoteEn: 'Focus on the absolute number of transactions required, not the illusionary percentage of completion.',
    pqOptionsEn: [
      { id: 'opt_a', text: 'Card A, because 8 total boxes looks less intimidating than 10 boxes.', isCorrect: false, feedback: 'Incorrect. Starting from absolute zero triggers procrastination.' },
      { id: 'opt_b', text: 'Card B, because endowed progress makes consumers perceive themselves as closer to the goal, accelerating purchases.', isCorrect: true, feedback: 'Correct! This was proven empirically by Kivetz and colleagues.' },
      { id: 'opt_c', text: 'Both cards will be completed at the exact same speed because the math is identical.', isCorrect: false, feedback: 'Incorrect. Human behavior is influenced by framing, not just pure math.' }
    ],
    reflectionPromptEn: 'Which loyalty app on your phone is currently nudging you to spend money just to "maintain" a streak or status level?',
    titleHinglish: 'Goal-Gradient Effect: Aakhri Kadam Ki Bhaagdoud',
    subtitleHinglish: 'Kyu manjil ke paas aate hi hamara kharcha aur bechaini dono double ho jate hain.',
    shortDescHinglish: 'Clark Hull aur Kivetz ki research: Progress bar 80% dekh kar log faltu shopping karke target poora karne daudte hain.',
    oneLineHinglish: 'Manjil jitni paas dikhti hai, dimaag utni tezi se bina soche daudta hai.',
    summary30sHinglish: '1932 me Clark Hull ne dekha ki choohe cheese ke paas aate hi tezi se bhaagne lagte hain. Columbia University ke Kivetz ne prove kiya ki yahi insaano ke sath hota hai: Coffee shop me 10 cup par 1 free cup ka card ho, to 8th aur 9th cup log roz-roz peene lagte hain taaki reward mil jaye.',
    coreConceptHinglish: 'Ise kehte hain "Endowed Progress". Agar aapko 10 stamps ka khali card mile to aap sust rahoge. Par agar 12 stamps ka card mile jisme 2 pehle se stamped ho, to aap do guna tezi se coffee khareedoge! Halanki dono me 10 coffee hi khareedni thi, par 2 pre-stamps ne dimaag ko race me daal diya.',
    summary60sHinglish: 'Airlines ke status points aur Zomato Gold is trick se chalte hain. Saal ke end me log Gold tier bachane ke liye ₹15,000 ki faltu flight book kar lete hain, jabki Gold tier ke fayde sirf ₹3,000 ke hote hain! Progress bar ka nasha insaan se bewakoofi karwata hai.',
    howItWorksHinglish: 'Card mila (2 stamps free) -> Dimaag ne socha "20% to ho gaya" -> Tezi se shopping ki -> 90% par aakar bechaini hui -> Faltu kharcha karke target poora kiya.',
    howToRespondHinglish: 'Math over Progress Bar: Poocho ki reward ki asli keemat kya hai? Agar ₹500 ke free reward ke liye ₹2,000 ka extra kharcha karna pad raha hai, to card faad kar phek do.',
    takeawaysHinglish: [
      'Progress bar 80% hote hi dimaag rationality kho kar andha daudne lagta hai',
      'Companies 2 free stamps dekar aapko jhootha head start deti hain (Endowed Progress)',
      'Tier status ya streaks bachane ke liye faltu shopping karna sabse bada financial loss hai',
      'Free reward ke value ko required kharche ke sath compare karein'
    ],
    pqPromptHinglish: 'Ek coffee shop Card A deti hai (8 stamps khali) aur Card B (10 stamps jisme 2 pehle se free stamped hain). Dono me 8 coffee khareedni hain. Log kaunsa card jaldi poora karenge?',
    pqExplanationHinglish: 'Card B me 2 free stamps hone ki wajah se endowed progress feel hoti hai, jisse log jaldi-jaldi khareedte hain.',
    pqOptionsHinglish: [
      { id: 'opt_a', text: 'Card A, kyuki 8 boxes kam lagte hain.', isCorrect: false, feedback: 'Galat. Zero se start karna boring lagta hai.' },
      { id: 'opt_b', text: 'Card B, kyuki 2 free stamps se lagta hai ki hum race me aage hain (Endowed Progress).', isCorrect: true, feedback: 'Sahi! Kivetz ki research ne yahi prove kiya tha.' },
      { id: 'opt_c', text: 'Dono me barabar time lagega kyuki dono me 8 coffee hi leni hain.', isCorrect: false, feedback: 'Galat. Psychology math se alag behave karti hai.' }
    ],
    hiTitle: 'लक्ष्य-प्रवणता प्रभाव (Goal-Gradient Effect)',
    hiSummary: 'लक्ष्य या पुरस्कार के निकट पहुंचते ही प्रयास, गति और व्यय में होने वाली अप्रत्याशित तीव्र वृद्धि का मनोवैज्ञानिक विश्लेषण।',
    hiTakeaways: ['समाप्ति रेखा के निकट आते ही व्यय और प्रयास तीव्र हो जाते हैं', 'कृत्रिम शुरुआत (Endowed Progress) निष्ठा कार्यक्रमों की सफलता बढ़ाती है', 'पुरस्कार के वास्तविक मूल्य की तुलना आवश्यक खर्च से करें'],
    guTitle: 'ધ્યેય-પ્રવણતા અસર (Goal-Gradient Effect)', guSummary: 'લક્ષ્ય નજીક દેખાતા જ ઉત્સાહ અને ખર્ચમાં ઝડપી વધારો થવાની ગ્રાહકની માનસિકતા.', guTakeaways: ['લક્ષ્ય નજીક હોય ત્યારે સંયમ રાખો', 'લોયલ્ટી કાર્ડ્સના ચક્કરમાં ન પડો', 'વાસ્તવિક લાભની ગણતરી કરો'],
    mrTitle: 'ध्येय-प्रवणता प्रभाव (Goal-Gradient Effect)', mrSummary: 'ध्येय किंवा बक्षीस जवळ आल्याचे दिसताच प्रयत्न आणि खर्चाचा वेग वाढण्याचे मानसशास्त्र.', mrTakeaways: ['शेवटच्या टप्प्यात घाईगडबड टाळा', 'लॉयल्टी प्रोग्राम्सचे गणित समजून घ्या', 'बक्षिसाचे वास्तविक मूल्य तपासा'],
    teTitle: 'లక్ష్య ప్రవణత ప్రభావం (Goal-Gradient Effect)', teSummary: 'లక్ష్యం లేదా బహుమతి సమీపిస్తున్న కొద్దీ శ్రమ మరియు ఖర్చు వేగవంతమయ్యే మానసిక ప్రవర్తన.', teTakeaways: ['ముగింపు రేఖ వద్ద సంయమనం పాటించండి', 'లాయల్టీ కార్డుల ఉచ్చులో పడవద్దు', 'నిజమైన ప్రయోజనాన్ని లెక్కించండి'],
    taTitle: 'இலக்கு சாய்வு விளைவு (Goal-Gradient Effect)', taSummary: 'இலக்கு அல்லது வெகுமதி நெருங்கும் போது முயற்சியும் செலவும் அதிவேகமாக அதிகரிக்கும் உளவியல்.', taTakeaways: ['இலக்கு நெருங்கும் போது நிதானம் தேவை', 'விசுவாச அட்டைகளின் தந்திரத்தை உணருங்கள்', 'உண்மையான மதிப்பை கணக்கிடுங்கள்'],
    knTitle: 'ಗುರಿ-ಪ್ರವಣತೆಯ ಪರಿಣಾಮ (Goal-Gradient Effect)', knSummary: 'ಗುರಿ ಅಥವಾ ಬಹುಮಾನ ಸಮೀಪಿಸಿದಂತೆ ಪ್ರಯತ್ನ ಮತ್ತು ಖರ್ಚಿನ ವೇಗ ಹೆಚ್ಚಾಗುವ ಮಾನಸಿಕ ಪ್ರವೃತ್ತಿ.', knTakeaways: ['ಅಂತಿಮ ಹಂತದಲ್ಲಿ ಸಂಯಮವಿರಲಿ', 'ಲಾಯಲ್ಟಿ ಕಾರ್ಡ್‌ಗಳ ತಂತ್ರ ತಿಳಿಯಿರಿ', 'ನಿಜವಾದ ಲಾಭವನ್ನು ಲೆಕ್ಕಹಾಕಿ'],
    mlTitle: 'ലക്ഷ്യ-പ്രവണതാ പ്രഭാവം (Goal-Gradient Effect)', mlSummary: 'ലക്ഷ്യം അടുത്തെത്തുമ്പോൾ പരിശ്രമവും ചെലവും വേഗത്തിലാക്കുന്ന ഉപഭോക്തൃ മാനസികാവസ്ഥ.', mlTakeaways: ['അവസാന ഘട്ടത്തിൽ വിവേകം കൈവിടരുത്', 'ലോയൽറ്റി ഓഫറുകളിൽ ജാഗ്രത പാലിക്കുക', 'യഥാർത്ഥ മൂല്യം പരിശോധിക്കുക'],
    bnTitle: 'লক্ষ্য-প্রবণতা প্রভাব (Goal-Gradient Effect)', bnSummary: 'লক্ষ্য বা পুরস্কারের কাছাকাছি পৌঁছানোর সাথে সাথে প্রচেষ্টা ও ব্যয়ের গতি নাটকীয়ভাবে বৃদ্ধির মনস্তাত্ত্বিক সত্যতা।', bnTakeaways: ['শেষ মুহূর্তে অযথা খরচ এড়িয়ে চলুন', 'লয়ালটি কার্ডের কৌশল বুঝুন', 'পুরস্কারের আসল মূল্য বিচার করুন'],
    paTitle: 'ਟੀਚਾ-ਪ੍ਰਵਣਤਾ ਪ੍ਰਭਾਵ (Goal-Gradient Effect)', paSummary: 'ਇਨਾਮ ਜਾਂ ਟੀਚੇ ਦੇ ਨੇੜੇ ਪਹੁੰਚਦੇ ਹੀ ਖਰਚੇ ਅਤੇ ਜਲਦਬਾਜ਼ੀ ਦੀ ਰਫ਼ਤਾਰ ਤੇਜ਼ ਹੋਣ ਦੀ ਮਾਨਸਿਕ ਆਦਤ।', paTakeaways: ['ਆਖ਼ਰੀ ਪਲਾਂ ਵਿੱਚ ਸੰਜਮ ਰੱਖੋ', 'ਲੌਇਲਟੀ ਕਾਰਡਾਂ ਦੀ ਚਾਲ ਸਮਝੋ', 'ਇਨਾਮ ਦੇ ਅਸਲ ਮੁੱਲ ਦਾ ਹਿਸਾਬ ਲਗਾਓ'],
    urTitle: 'ہدف کی کشش کا اثر (Goal-Gradient Effect)', urSummary: 'کسی انعام یا ہدف کے قریب پہنچتے ہی کوشش اور خریداری کی رفتار غیر معمولی طور پر تیز ہونے کا رجحان۔', urTakeaways: ['آخری لمحات میں ہوش مندی برقرار رکھیں', 'وفاداری کارڈز کے جال سے بچیں', 'انعام کی اصل قیمت کا اندازہ لگائیں'],
    orTitle: 'ଲକ୍ଷ୍ୟ-ପ୍ରବଣତା ପ୍ରଭାବ (Goal-Gradient Effect)', orSummary: 'ଲକ୍ଷ୍ୟ ବା ପୁରସ୍କାର ନିକଟତର ହେଲେ ଉଦ୍ୟମ ଓ ଖର୍ଚ୍ଚର ଗତି ଦ୍ରୁତ ହେବାର ମନସ୍ତାତ୍ତ୍ୱିକ ପ୍ରବୃତ୍ତି।', orTakeaways: ['ଶେଷ ମୁହୂର୍ତ୍ତରେ ସତର୍କ ରୁହନ୍ତୁ', 'ଲୟାଲ୍ଟି କାର୍ଡର ରହସ୍ୟ ବୁଝନ୍ତୁ', 'ପ୍ରକୃତ ଲାଭର ହିସାବ କରନ୍ତୁ'],
    asTitle: 'লক্ষ্য-প্ৰৱণতাৰ প্ৰভাৱ (Goal-Gradient Effect)', asSummary: 'লক্ষ্য বা পুৰস্কাৰ ওচৰ চাপিলেই প্ৰচেষ্টা আৰু খৰচৰ গতি অস্বাভাৱিকভাৱে বৃদ্ধি পোৱাৰ মানসিকতা।', asTakeaways: ['অন্তিম মুহূৰ্তত সংযম ৰাখক', 'লয়ালিটি কাৰ্ডৰ কৌশল বুজক', 'পুৰস্কাৰৰ প্ৰকৃত মূল্য নিৰ্ণয় কৰক']
  },

  {
    fileName: 'scarcityCountdownTriggers.ts',
    varName: 'scarcity_countdown_triggers',
    id: 'scarcity_countdown_triggers',
    categoryId: 'consumer_advertising',
    slug: 'scarcity-and-countdown-triggers',
    difficulty: 'beginner',
    readTime: 5,
    sortWeight: 10,
    titleEn: 'Scarcity & Countdown Triggers: Artificial Urgency & Loss Aversion',
    subtitleEn: 'Robert Cialdini’s influence weapon on why "Only 2 rooms left!" and ticking timers suspend critical thinking.',
    shortDescEn: 'A ubiquitous behavioral marketing tactic that fabricates artificial limits on time or quantity (e.g. countdown clocks, low stock banners) to induce panic and force impulsive purchases.',
    oneLineEn: 'Making you buy right now by triggering the evolutionary panic of missing out.',
    summary30sEn: 'Documented in Dr. Robert Cialdini’s seminal work *Influence*, the Scarcity Principle states that opportunities seem vastly more valuable to us when their availability is limited. Modern e-commerce platforms weaponize this with dynamic countdown clocks ("Sale ends in 04:12!"), fabricated stock counters ("Only 1 seat left at this price!"), and concurrent viewer alerts ("42 people are looking at this right now!").',
    coreConceptEn: 'Scarcity activates psychological reactance (Jack Brehm): when our freedom to obtain a resource is threatened by impending expiration, our desire to preserve that freedom skyrockets. Combined with Kahneman and Tversky’s Loss Aversion (losses hurt 2.5x more than equivalent gains feel good), the fear of *losing the deal* overrides the rational evaluation of whether you even need the product.',
    summary60sEn: 'Regulatory investigations (like the UK Competition and Markets Authority and India’s Central Consumer Protection Authority) have repeatedly revealed that many countdown clocks are deceptive "dark patterns" engineered to reset automatically upon page refresh. The stock counters are often hardcoded random number generators designed solely to induce physiological panic in the consumer.',
    takeawaysEn: [
      'Scarcity manipulates loss aversion: the brain panics at the thought of losing an option',
      'Countdown timers and stock counters are frequently fabricated algorithmic dark patterns',
      'Urgency forces System 1 intuitive impulse buying, short-circuiting System 2 analysis',
      'The antidote is closing the browser tab for 1 hour; real emergencies don’t happen on flash sales'
    ],
    whyItHappensEn: 'Ancestral survival: resources like fresh meat or ripe fruit spoiled rapidly; immediate seizure was vital for caloric survival.',
    evolutionaryEn: 'Hominids who hesitated when encountering scarce seasonal berries or water holes lost them to competitors and perished.',
    howItWorksEn: 'Item browsed -> Flashing red timer seen ("Ends in 10 mins!") -> Amygdala feels resource threat -> Cortisol and adrenaline rise -> Prefrontal cost analysis bypassed -> Checkout completed -> Immediate buyer regret.',
    visualHeadlineEn: 'Fabricated Panic (Dark Pattern) vs. Cold Rational Audit',
    visualDescEn: 'How artificial urgency manipulates the consumer purchase funnel.',
    sideALabelEn: 'Artificially Triggered Panic',
    sideADetailEn: '"Hurry! 17 people have this hotel in their cart! Only 1 left!" -> Blood pressure rises; buys in 45 seconds without checking reviews.',
    sideBLabelEn: 'Rational Inspection Antidote',
    sideBDetailEn: 'Refreshes page in incognito window -> Notice timer resets to 15:00 -> Closes tab -> Realizes hotel was overpriced anyway.',
    researchSummaryEn: 'Cialdini (1984, Influence) and Worchel, Lee & Adewole (1975, JPSP) demonstrated that identical cookies tasted significantly better and were rated as higher value when taken from a jar containing only 2 cookies versus a jar of 10.',
    refAuthor: 'Cialdini, R. B.',
    refYear: 1984,
    refTitle: 'Influence: The Psychology of Persuasion',
    refCitation: 'Cialdini, R. B. (1984). William Morrow & Company.',
    refDoi: 'https://doi.org/10.1080/08959285.2017.1350692',
    scenarioTitleEn: 'The Midnight Flash Sale in Bengaluru',
    scenarioContextEn: 'Sneha was browsing airfares from Bengaluru to Jaipur for a holiday 4 months away. The travel portal showed a pulsing red banner: "Only 2 seats left at ₹4,200! 8 other travelers viewing now!" Panicking, Sneha entered her card details in 90 seconds, accidentally booking the wrong return date and paying a ₹3,000 non-refundable change fee.',
    scenarioBiasEn: 'Sneha was blinded by artificial scarcity: the ticking countdown induced an acute fight-or-flight panic that short-circuited her prefrontal attention to flight dates.',
    scenarioOptimalEn: 'Recognize the dark pattern. Take a slow breath, open an incognito window, verify that seats are actually abundant, and double-check all booking details with zero hurry.',
    scenarioReflectionEn: 'How many times have you rushed to buy an item because of a ticking countdown clock, only to find the exact same "deal" still available days later?',
    howToRecognizeEn: 'Ticking digital clocks, flashing red text ("Almost gone!"), banners showing real-time visitor counts, and "limited-edition" flash sales.',
    whereEn: 'Hotel booking portals, airline reservation engines, e-commerce flash sales, and online course landing pages.',
    misconceptionsEn: 'Myth: "The website is legally required to tell the truth about stock levels." Fact: E-commerce platforms regularly deploy deceptive dark patterns that simulate scarcity with client-side JavaScript.',
    limitationsEn: 'Genuine physical scarcity exists (e.g. concert tickets in a 5,000-seat stadium, seasonal mango harvests); the distinction is whether the limit is physically real or algorithmically generated.',
    howToRespondEn: 'The Incognito Refresh Test: Open the product page in an incognito/private browser window. If the countdown timer resets back to its starting time or the "Only 2 left" count remains static, the urgency is completely fabricated.',
    defensesEn: [
      { title: 'The Incognito Dark-Pattern Check', instruction: 'Whenever you see a countdown timer or "Only X items left", refresh the URL in an incognito tab to expose fake timers.' },
      { title: 'The 2-Hour Walk-Away Rule', instruction: 'Never buy anything triggered by a flash sale timer on the spot; close the browser for 2 hours. If it is truly meant for you, you will buy it rationally later.' }
    ],
    pqPromptEn: 'A hotel booking site shows: "Only 1 room remaining at this price! 14 people are viewing this property right now!" and a 10-minute timer counts down. What is the scientifically smartest first step?',
    pqScenarioEn: 'Your heart rate increases and you feel an urgent urge to click "Book Now" immediately.',
    pqExplanationEn: 'This combination of scarcity, social proof, and countdown timers is designed to induce physiological panic and bypass rational decision-making. Opening the page in an incognito window checks for client-side fake scarcity.',
    pqAntidoteEn: 'Pause, recognize the emotional panic, test the timer in an incognito window, and read customer reviews calmly.',
    pqOptionsEn: [
      { id: 'opt_a', text: 'Enter your credit card immediately before the other 14 people take the room.', isCorrect: false, feedback: 'Incorrect. This surrenders completely to the artificial urgency dark pattern.' },
      { id: 'opt_b', text: 'Take a deep breath, open the URL in an incognito tab to see if the timer and stock change, and review the cancellation terms calmly.', isCorrect: true, feedback: 'Correct! This disarms the manipulation and protects your consumer agency.' },
      { id: 'opt_c', text: 'Call 14 of your friends to tell them not to book the room.', isCorrect: false, feedback: 'Incorrect. The 14 people are often fabricated metrics.' }
    ],
    reflectionPromptEn: 'What is the most expensive purchase you made in a rush that you would have avoided if you had waited just 24 hours?',
    titleHinglish: 'Scarcity & Countdown Triggers: "Sirf 2 Bache Hain" Ka Darr',
    subtitleHinglish: 'Robert Cialdini ki research: Kyu ticking timer aur "Only 1 left" dekh kar dimaag paagal ho jata hai.',
    shortDescHinglish: 'Artificial urgency aur FOMO: Websites kaise jhoothe timers aur limited stock dikha kar aapse turant payment karwati hain.',
    oneLineHinglish: 'Aapko sochne ka waqt na mile, isliye ghadi ki sui tez chala di jati hai.',
    summary30sHinglish: 'Dr. Robert Cialdini ne apni kitaab *Influence* me bataya ki jab koi cheez durlabh (scarce) hoti hai, to dimaag use 10 guna zyada keemti samajhne lagta hai. Websites is darr ka fayda uthati hain: "Sale 5 minute me khatam!", "Sirf 1 seat bachi hai!", aur "20 log abhi dekh rahe hain!"',
    coreConceptHinglish: 'Ise kehte hain Loss Aversion. Insaan ko kuch paane ki khushi se 2.5 guna zyada chot kisi cheez ko khone par lagti hai. Jab timer chalta hai, to dimaag ko lagta hai "deal chali jayegi". Is ghabrahat me log galat date ki ticket book kar lete hain ya bekaar samaan khareed lete hain.',
    summary60sHinglish: 'Government ki investigations me pata chala hai ki 90% websites par yeh countdown timers jhoothe hote hain (Dark Patterns). Page refresh karo to timer wapas 15 minute par chala jata hai! Yeh sab sirf customer ke dimaag me emergency create karne ke liye code kiya gaya hota hai.',
    howItWorksHinglish: 'Product dekha -> Red color me timer dikha ("Only 3 left!") -> Dimaag me panic hua -> Bina reviews padhe jaldi se card swipe kiya -> Baad me pata chala cheez bekaar thi.',
    howToRespondHinglish: 'Incognito Test: Page ko Incognito (Private) window me kholo. Agar timer wapas reset ho gaya, to samajh jao website jhooth bol rahi hai. Tab shanti se 2 ghante baad socho.',
    takeawaysHinglish: [
      'Ticking timers dimaag ke logical hisse ko switch off karne ke liye banaye jate hain',
      '"Only 2 left" aksar computer code ka jhooth hota hai (Dark Pattern)',
      'Flash sale ke darr me aakar kabhi 2 minute me decision mat lo',
      'Incognito mode me check karo, timer reset hote hi sach samne aa jayega'
    ],
    pqPromptHinglish: 'Flight book karte waqt screen par laal rang me likha aata hai: "Sirf 1 seat bachi hai! 10 log dekh rahe hain!" Kya karein?',
    pqExplanationHinglish: 'Ghabrane ke bajaye page ko private window me khol kar check karein aur date/time dhyan se verify karein.',
    pqOptionsHinglish: [
      { id: 'opt_a', text: 'Aankh band karke turant card details daal dena taaki koi aur na le le.', isCorrect: false, feedback: 'Galat. Isse galat date book hone ka khatra hota hai.' },
      { id: 'opt_b', text: 'Ek gehri saans lena, Incognito window me check karna aur dates dhyan se verify karke book karna.', isCorrect: true, feedback: 'Sahi! Yeh dark patterns ko neutralise karta hai.' },
      { id: 'opt_c', text: 'Airline ko tweet karke daantna.', isCorrect: false, feedback: 'Galat. Unproductive hai.' }
    ],
    hiTitle: 'कृत्रिम अभाव और उलटी गिनती (Scarcity & Countdown Triggers)',
    hiSummary: 'वेबसाइटों द्वारा कृत्रिम समय सीमा और कम स्टॉक दिखाकर उपभोक्ताओं में घबराहट उत्पन्न करने और त्वरित खरीदारी कराने की रणनीति।',
    hiTakeaways: ['अभाव का भय मस्तिष्क के तार्किक विश्लेषण को रोक देता है', 'उलटी गिनती वाले टाइमर अक्सर भ्रामक (Dark Patterns) होते हैं', 'निर्णय लेने से पहले इनकॉग्निटो मोड में टाइमर की सत्यता जांचें'],
    guTitle: 'કૃત્રિમ અછત અને કાઉન્ટડાઉન (Scarcity Triggers)', guSummary: 'વેબસાઇટ્સ પર ટિકિંગ ટાઈમર અને ખોટો સ્ટોક બતાવીને ગ્રાહકોને ઉતાવળે ખરીદી કરાવવાની યુક્તિ.', guTakeaways: ['ખોટી ઉતાવળથી બચો', 'કાઉન્ટડાઉન ટાઈમરની સત્યતા તપાસો', 'શાંતિથી નિર્ણય લો'],
    mrTitle: 'कृत्रिम टंचाई आणि काउंटडाऊन (Scarcity Triggers)', mrSummary: 'वेबसाइट्सवर खोटे टायमर आणि मर्यादित साठा दाखवून ग्राहकांमध्ये भीती निर्माण करण्याचे विपणन तंत्र.', mrTakeaways: ['कृत्रिम टंचाईच्या जाळ्यात अडकू नका', 'खोट्या काउंटडाऊनपासून सावध रहा', 'घाईगडबडीत खरेदी टाळा'],
    teTitle: 'కృత్రిమ కొరత మరియు కౌంట్‌డౌన్ ట్రిగ్గర్లు', teSummary: 'వెబ్‌సైట్లలో తప్పుడు టైమర్లు మరియు పరిమిత స్టాక్ చూపిస్తూ వినియోగదారులను భయపెట్టి కొనిపించే వ్యూహం.', teTakeaways: ['కృత్రిమ అత్యవసరంలో పడవద్దు', 'కౌంట్‌డౌన్ టైమర్లను తనిఖీ చేయండి', 'ప్రశాంతంగా నిర్ణయం తీసుకోండి'],
    taTitle: 'செயற்கை தட்டுப்பாடு மற்றும் கவுண்டவுன் (Scarcity Triggers)', taSummary: 'இணையதளங்களில் போலி டைமர்கள் மற்றும் குறைந்த இருப்பு காட்டி அவசர அவசரமாக வாங்க வைக்கும் உளவியல் தந்திரம்.', taTakeaways: ['செயற்கை அவசரத்தை நம்பாதீர்கள்', 'டைமர்களின் உண்மைத்தன்மையை சோதிக்கவும்', 'அமைதியாக முடிவெடுங்கள்'],
    knTitle: 'ಕೃತಕ ಕೊರತೆ ಮತ್ತು ಕೌಂಟ್‌ಡೌನ್ ತಂತ್ರಗಳು', knSummary: 'ವೆಬ್‌ಸೈಟ್‌ಗಳಲ್ಲಿ ಸುಳ್ಳು ಟೈಮರ್‌ಗಳು ಮತ್ತು ಸೀಮಿತ ಸ್ಟಾಕ್ ತೋರಿಸಿ ಗ್ರಾಹಕರನ್ನು ಆತುರದ ಖರೀದಿಗೆ ಪ್ರಚೋದಿಸುವ ತಂತ್ರ.', knTakeaways: ['ಕೃತಕ ತುರ್ತುಸ್ಥಿತಿಗೆ ಒಳಗಾಗಬೇಡಿ', 'ಟೈಮರ್‌ಗಳ ಸತ್ಯಾಸತ್ಯತೆ ಪರೀಕ್ಷಿಸಿ', 'ಶಾಂತಚಿತ್ತದಿಂದ ಖರೀದಿಸಿ'],
    mlTitle: 'കൃത്രിമ ദൗർലഭ്യവും കൗണ്ട്ഡൗണും (Scarcity Triggers)', mlSummary: 'വെബ്‌സൈറ്റുകളിൽ വ്യാജ ടൈമറുകളും പരിമിത സ്റ്റോക്കും കാണിച്ച് ഉപഭോക്താക്കളെ തിടുക്കത്തിൽ വാങ്ങിപ്പിക്കുന്ന രീതി.', mlTakeaways: ['കൃത്രിമ തിടുക്കത്തിൽ വീഴരുത്', 'കൗണ്ട്ഡൗൺ ടൈമറുകൾ പരിശോധിക്കുക', 'സമാധാനത്തോടെ തീരുമാനമെടുക്കുക'],
    bnTitle: 'কৃত্রিম সংকট এবং কাউন্টডাউন ফাঁদ (Scarcity Triggers)', bnSummary: 'ওয়েবসাইটে ভুয়া টাইমার এবং সীমিত স্টকের ভীতি দেখিয়ে দ্রুত কেনাকাটা করতে বাধ্য করার চাতুরী।', bnTakeaways: ['কৃত্রিম তাড়াহুড়োয় পা দেবেন না', 'কাউন্টডাউন টাইমারের সত্যতা যাচাই করুন', 'ধৈর্য ধরে সিদ্ধান্ত নিন'],
    paTitle: 'ਨਕਲੀ ਥੁੜ ਅਤੇ ਕਾਊਂਟਡਾਊਨ (Scarcity Triggers)', paSummary: 'ਵੈੱਬਸਾਈਟਾਂ ਤੇ ਝੂਠੇ ਟਾਈਮਰ ਅਤੇ ਘੱਟ ਸਟਾਕ ਦਿਖਾ ਕੇ ਗਾਹਕਾਂ ਵਿੱਚ ਘਬਰਾਹਟ ਪੈਦਾ ਕਰਕੇ ਖ਼ਰੀਦਦਾਰੀ ਕਰਵਾਉਣ ਦੀ ਚਾਲ।', paTakeaways: ['ਨਕਲੀ ਕਾਹਲ ਤੋਂ ਬਚੋ', 'ਟਾਈਮਰਾਂ ਦੀ ਅਸਲੀਅਤ ਪਰਖੋ', 'ਸ਼ਾਂਤੀ ਨਾਲ ਫੈਸਲਾ ਲਓ'],
    urTitle: 'مصنوعی قلت اور الٹی گنتی کے حربے (Scarcity Triggers)', urSummary: 'ویب سائٹس پر جھوٹے ٹائمرز اور محدود اسٹاک دکھا کر صارفین کو گھبراہٹ میں خریداری پر مجبور کرنے کا طریقہ۔', urTakeaways: ['مصنوعی جلدی کے جال میں نہ آئیں', 'ٹائمر کی حقیقت چیک کریں', 'سکون سے فیصلہ کریں'],
    orTitle: 'କୃତ୍ରିମ ଅଭାବ ଓ କାଉଣ୍ଟଡାଉନ୍ ଚକ୍ରାନ୍ତ (Scarcity Triggers)', orSummary: 'ୱେବସାଇଟ୍‌ରେ ନକଲି ଟାଇମର୍ ଓ ସୀମିତ ଷ୍ଟକ୍ ଦେଖାଇ ଗ୍ରାହକଙ୍କୁ ତରବରିଆ ଭାବେ କିଣିବାକୁ ବାଧ୍ୟ କରିବାର କୌଶଳ।', orTakeaways: ['କୃତ୍ରିମ ବ୍ୟସ୍ତତାରୁ ଦୂରେଇ ରୁହନ୍ତୁ', 'ଟାଇମରର ସତ୍ୟତା ଯାଞ୍ଚ କରନ୍ତୁ', 'ଧୈର୍ଯ୍ୟର ସହ ନିଷ୍ପତ୍ତି ନିଅନ୍ତୁ'],
    asTitle: 'কৃত্ৰিম নাটনি আৰু কাউণ্টডাউনৰ জাল (Scarcity Triggers)', asSummary: 'ৱেবছাইটত ভুৱা টাইমাৰ আৰু সীমিত ষ্টক দেখুৱাই গ্ৰাহকক খৰখেদাকৈ ক্ৰয় কৰিবলৈ বাধ্য কৰোৱাৰ কৌশল।', asTakeaways: ['কৃত্ৰিম খৰখেদাত নপৰিব', 'টাইমাৰৰ সত্যতা পৰীক্ষা কৰক', 'ধৈৰ্যৰে সিদ্ধান্ত লওক']
  }
];

