import { ComprehensiveTopicDef } from '../topicGeneratorHelper';

export const CRITICAL_TOPICS: ComprehensiveTopicDef[] = [
  {
    fileName: 'secondOrderThinking.ts',
    varName: 'second_order_thinking',
    id: 'second_order_thinking',
    categoryId: 'critical_thinking',
    slug: 'second-order-thinking',
    difficulty: 'intermediate',
    readTime: 6,
    sortWeight: 5,
    titleEn: 'Second-Order Thinking: And Then What?',
    subtitleEn: 'Howard Marks and Garrett Hardin on anticipating downstream consequences that blind immediate thinkers.',
    shortDescEn: 'A mental model that looks past the immediate, obvious effects of an action to predict the subsequent second, third, and fourth-order systemic consequences over time.',
    oneLineEn: 'First-order thinkers look for immediate gratification; second-order thinkers ask: "And then what?"',
    summary30sEn: 'Popularized by legendary investor Howard Marks and ecologist Garrett Hardin, Second-Order Thinking separates amateur problem solvers from strategic masters. First-order thinking is simple, fast, and seductive: "I am hungry, so I will eat a box of doughnuts." Second-order thinking asks: "And then what happens 2 hours later to my blood sugar, mood, and fat storage?"',
    coreConceptEn: 'Complex adaptive systems always push back. Every intervention produces ripples of unintended consequences. In first-order thinking, solving a problem creates an immediate apparent win; in second-order reality, the feedback loops, human counter-reactions, and equilibrium shifts often make the ultimate outcome far worse than the original problem.',
    summary60sEn: 'Historical examples abound: the British government in colonial Delhi offered a bounty for dead cobras to eradicate snakes (First Order). Citizens began breeding cobras in secret to collect cash (Second Order). When the bounty was canceled, breeders released thousands of cobras into Delhi streets, multiplying the snake population (Third Order). This is the famous Cobra Effect.',
    takeawaysEn: [
      'First-order thinking solves for the immediate moment; second-order thinking solves for systemic stability',
      'The Cobra Effect: well-intentioned short-term policies frequently exacerbate the core problem',
      'Always ask the golden question: "And then what?" across 10 minutes, 10 months, and 10 years',
      'Discount immediate dopamine in exchange for long-term compounding systemic advantages'
    ],
    whyItHappensEn: 'Hyperbolic discounting and cognitive ease: the human brain evolved to prioritize immediate caloric and safety rewards over distant probabilistic outcomes.',
    evolutionaryEn: 'In ancestral foraging environments, food spoiled within hours and life expectancy was short; long-term second-order calculations offered low evolutionary return.',
    howItWorksEn: 'Problem encountered -> First-order solution applied -> Immediate relief felt -> System reacts to new incentive -> Unintended downstream consequence strikes -> Situation worsens.',
    visualHeadlineEn: 'First-Order Shortcut vs. Second-Order Loop',
    visualDescEn: 'Garrett Hardin’s systemic consequence cascade.',
    sideALabelEn: 'First-Order Thinking (Fast & Blind)',
    sideADetailEn: '"Rent is too expensive in Mumbai! Let\'s cap rent at ₹15,000!" -> Immediate tenant cheers; zero long-term analysis.',
    sideBLabelEn: 'Second-Order Thinking (Systemic)',
    sideBDetailEn: '"Landlords stop maintaining buildings -> Developers stop building new housing -> Extreme housing shortage & black market emerge!"',
    researchSummaryEn: 'Hardin (1968, Science) and Marks (2011, The Most Important Thing) detailed the mathematical and systemic failures that occur when dynamic human reactions are ignored in policy and capital allocation.',
    refAuthor: 'Marks, H. & Hardin, G.',
    refYear: 2011,
    refTitle: 'The Most Important Thing: Uncommon Sense for the Thoughtful Investor',
    refCitation: 'Marks, H. (2011). Columbia University Press.',
    refDoi: 'https://doi.org/10.7312/mark15360',
    scenarioTitleEn: 'The Bengaluru Traffic Flyover Paradox',
    scenarioContextEn: 'To solve traffic jams at a major Silk Board junction in Bengaluru, authorities spent ₹400 Crores building a 4-lane elevated flyover. Within 18 months, induced demand caused 80,000 additional cars to enter the corridor, making gridlock worse than before the flyover was constructed.',
    scenarioBiasEn: 'City planners used first-order thinking (more asphalt = less traffic), completely ignoring the second-order reality of induced traffic demand.',
    scenarioOptimalEn: 'Run a 3-step systemic projection: "If we build this, who changes their commute? Does it incentivize car ownership or public transit usage over a 5-year horizon?"',
    scenarioReflectionEn: 'What is a quick-fix solution you applied to your schedule, health, or finances that ended up creating three bigger problems later?',
    howToRecognizeEn: 'Celebrating a quick victory without asking how other people or systems will adapt to your new rule or decision.',
    whereEn: 'Public policy design, corporate incentive structures, parenting discipline, software architecture, and personal investing.',
    misconceptionsEn: 'Myth: "Second-order thinking causes analysis paralysis." Fact: It takes only 90 seconds to ask "And then what?" three consecutive times before executing an irreversible decision.',
    limitationsEn: 'In genuine life-threatening emergencies (e.g. a house fire or cardiac arrest), first-order immediate action is mandatory; second-order analysis must wait.',
    howToRespondEn: 'The 10/10/10 Rule: Before finalizing any major decision, ask: How will I feel about this in 10 minutes? In 10 months? In 10 years?',
    defensesEn: [
      { title: 'The "And Then What?" Cadence', instruction: 'Whenever proposing a solution, force yourself to write three sequential answers to "And then what happens next?"' },
      { title: 'Perverse Incentive Simulation', instruction: 'Assume people will exploit your new policy or rule in the most selfish way possible; how will they game it?' }
    ],
    pqPromptEn: 'A manager notices team members are skipping unit tests to meet deadlines. She introduces a new policy: "Developers will receive a ₹5,000 cash bonus for every 100 bug-free unit tests committed." What is the predicted second-order consequence?',
    pqScenarioEn: 'The manager expects test coverage to improve and software quality to skyrocket.',
    pqExplanationEn: 'First-order thinking expects more tests. Second-order thinking predicts engineers will game the incentive by writing hundreds of trivial, meaningless tests (e.g. testing `1 == 1`) to maximize cash bonuses, degrading real quality.',
    pqAntidoteEn: 'Incentivize holistic outcomes (e.g. production uptime and customer satisfaction) rather than easily manipulated activity metrics.',
    pqOptionsEn: [
      { id: 'opt_a', text: 'Software defects will drop to zero and the company will save millions.', isCorrect: false, feedback: 'Incorrect. This is naive first-order wishful thinking.' },
      { id: 'opt_b', text: 'Engineers will write hundreds of superficial, trivial tests to collect cash bonuses without improving actual code safety.', isCorrect: true, feedback: 'Correct! Campbell’s Law and second-order thinking predict incentive gaming.' },
      { id: 'opt_c', text: 'All engineers will immediately resign in anger.', isCorrect: false, feedback: 'Incorrect. They will happily accept the free money.' }
    ],
    reflectionPromptEn: 'What shortcut are you currently taking in your daily work that is quietly creating massive technical or emotional debt for your future self?',
    titleHinglish: 'Second-Order Thinking: "Uske Baad Kya?" Sochna Seekhein',
    subtitleHinglish: 'Howard Marks ki strategy: Aam log sirf turant ka fayda dekhte hain, par genius log agle 3 kadam aage sochte hain.',
    shortDescHinglish: 'First vs Second-Order Thinking: Short-term solution kaise long-term me bada sir-dard ban jata hai (The Cobra Effect).',
    oneLineHinglish: 'Pehle kadam par sab khush hote hain, par teesre kadam par asli toofan aata hai.',
    summary30sHinglish: 'Wall Street ke legendary investor Howard Marks ne kaha ki aam log First-Order Thinking karte hain: "Mujhe bhookh lagi hai, main chocolate kha leta hu." Second-Order thinker poochta hai: "Iske baad kya? 2 ghante baad sugar crash hoga, neend aayegi aur weight badhega!"',
    coreConceptHinglish: 'Angrezon ke zamane me Delhi me saanp bohot the. Sarkar ne ailan kiya: "Jo mara hua cobra layega use inaam milega" (First Order). Logo ne ghar me cobra paalna shuru kar diya taaki inaam le sakein (Second Order)! Sarkar ne scheme band ki to logo ne saare saanp sadak par chhod diye (Third Order)! Saanp pehle se double ho gaye. Ise kehte hain Cobra Effect.',
    summary60sHinglish: 'Life me har quick-fix ka ek reaction hota hai. Agar aap thakawat door karne ke liye roz 5 cup coffee peete ho (First order: energy badhi), to raat ko neend nahi aayegi, agle din double thakawat hogi aur cortisol badhega (Second order). Genius log hamesha poochte hain: "And then what?"',
    howItWorksHinglish: 'Problem aayi -> Quick shortcut lagaya -> 5 minute ka relief mila -> System ne ulta react kiya -> 6 mahine baad pehle se badi museebat ban gayi.',
    howToRespondHinglish: '10/10/10 Rule: Koi bhi bada faisla lene se pehle socho: 10 minute baad kaisa lagega? 10 mahine baad kya asar hoga? Aur 10 saal baad iska kya anjaam hoga?',
    takeawaysHinglish: [
      'First-order thinking aam hoti hai, second-order thinking hi strategic master banati hai',
      'Cobra Effect: Bina soche banaye gaye rules problem ko 10 guna bada kar dete hain',
      'Hamesha ek golden question poocho: "Uske baad kya hoga?"',
      'Short-term sukoon ke peeche mat bhago, long-term stability dekho'
    ],
    pqPromptHinglish: 'Company ne rule banaya: "Jo developer jitne zyada unit tests likhega, use ₹5,000 bonus milega." Second-order thinking ke mutabiq kya hoga?',
    pqExplanationHinglish: 'Developers bonus ke chakkar me faltu aur bekaar tests likhne lagenge jisse code ki quality improve nahi hogi balki time waste hoga.',
    pqOptionsHinglish: [
      { id: 'opt_a', text: 'Software ke saare bugs hamesha ke liye khatam ho jayenge.', isCorrect: false, feedback: 'Galat. Yeh naive first-order soch hai.' },
      { id: 'opt_b', text: 'Engineers bonus lene ke liye bekaar aur easy tests ki bheed laga denge (Incentive gaming).', isCorrect: true, feedback: 'Sahi! Yahi second-order consequence ka textbook example hai.' },
      { id: 'opt_c', text: 'Company ke saare computers crash ho jayenge.', isCorrect: false, feedback: 'Galat.' }
    ],
    hiTitle: 'द्वितीय-क्रम चिंतन (Second-Order Thinking)',
    hiSummary: 'किसी निर्णय के केवल तात्कालिक परिणामों को देखने के बजाय उसके दीर्घकालिक, अप्रत्यक्ष और प्रणालीगत प्रभावों का विश्लेषण करने का मॉडल।',
    hiTakeaways: ['तात्कालिक लाभ अक्सर दीर्घकालिक संकटों को जन्म देते हैं', 'कोबरा प्रभाव (Cobra Effect) से सीखें और प्रोत्साहन संरचनाओं को समझें', 'हमेशा स्वर्णिम प्रश्न पूछें: "और फिर उसके बाद क्या?"'],
    guTitle: 'સેકન્ડ-ઓર્ડર થિંકિંગ (દૂરંદેશી વિચારસરણી)', guSummary: 'માત્ર તાત્કાલિક ફાયદો જોવાને બદલે ભવિષ્યના દૂરગામી પરિણામો વિચારવાની કળા.', guTakeaways: ['તાત્કાલિક ફાયદાની લાલચ છોડો', 'કોબ્રા ઇફેક્ટ સમજો', 'હંમેશા પૂછો: "આના પછી શું થશે?"'],
    mrTitle: 'द्वितीय-स्तरीय विचार (Second-Order Thinking)', mrSummary: 'फक्त तात्काळ फायद्याचा विचार न करता भविष्यातील दूरगामी परिणामांचा अंदाज घेण्याची विचारसरणी.', mrTakeaways: ['तात्पुरत्या फायद्याला भुलू नका', 'कोब्रा इफेक्ट लक्षात ठेवा', '"यानंतर काय?" हा प्रश्न विचारा'],
    teTitle: 'రెండవ-స్థాయి ఆలోచన (Second-Order Thinking)', teSummary: 'కేవలం తక్షణ ప్రయోజనాలను మాత్రమే కాకుండా దీర్ఘకాలిక పర్యవసానాలను అంచనా వేసే విధానం.', teTakeaways: ['తక్షణ లాభాల కోసం వెంపర్లాడవద్దు', 'కోబ్రా ఎఫెక్ట్ గ్రహించండి', '"ఆ తర్వాత ఏమిటి?" అని ప్రశ్నించండి'],
    taTitle: 'இரண்டாம் நிலை சிந்தனை (Second-Order Thinking)', taSummary: 'உடனடி நன்மைகளை மட்டும் பார்க்காமல் எதிர்கால பின்விளைவுகளை கணிக்கும் ஆழமான சிந்தனை முறை.', taTakeaways: ['உடனடி லாபத்தை மட்டும் பார்க்காதீர்கள்', 'கோப்ரா விளைவை புரிந்து கொள்ளுங்கள்', '"அதன் பிறகு என்ன?" என்று கேளுங்கள்'],
    knTitle: 'ದ್ವಿತೀಯ-ಹಂತದ ಚಿಂತನೆ (Second-Order Thinking)', knSummary: 'ಕೇವಲ ತಕ್ಷಣದ ಲಾಭವನ್ನು ನೋಡದೆ ಭವಿಷ್ಯದ ದೀರ್ಘಕಾಲಿಕ ಪರಿಣಾಮಗಳನ್ನು ಊಹಿಸುವ ವಿವೇಚನಾಶೀಲ ಕಲೆ.', knTakeaways: ['ತಕ್ಷಣದ ಆಕರ್ಷಣೆಗೆ ಒಳಗಾಗಬೇಡಿ', 'ಕೋಬ್ರಾ ಎಫೆಕ್ಟ್ ಅರಿಯಿರಿ', '"ಆಮೇಲೆ ಏನಾಗುತ್ತದೆ?" ಎಂದು ಪ್ರಶ್ನಿಸಿ'],
    mlTitle: 'രണ്ടാം ഘട്ട ചിന്ത (Second-Order Thinking)', mlSummary: 'ഉടനടിയുള്ള ഗുണങ്ങൾക്കപ്പുറം ഭാവിലുണ്ടാകുന്ന ദൂരവ്യാപകമായ പ്രത്യാഘാതങ്ങൾ മുൻകൂട്ടി കാണുന്ന രീതി.', mlTakeaways: ['ക്ഷണിക ലാഭം മാത്രം നോക്കരുത്', 'കോബ്ര ഇഫക്റ്റ് മനസ്സിലാക്കുക', '"അതിനുശേഷം എന്ത്?" എന്ന് ചോദിക്കുക'],
    bnTitle: 'দ্বিতীয়-ক্রম চিন্তা (Second-Order Thinking)', bnSummary: 'কেবল তাৎক্ষণিক ফলাফলের ওপর নির্ভর না করে দীর্ঘমেয়াদী সামগ্রিক প্রতিক্রিয়া বিশ্লেষণের মানসিক মডেল।', bnTakeaways: ['তাৎক্ষণিক লাভের ফাঁদ এড়িয়ে চলুন', 'কোবরা ইফেক্ট সম্পর্কে সচেতন থাকুন', 'সবসময় জিজ্ঞেস করুন: "তারপর কী?"'],
    paTitle: 'ਦੂਜੇ-ਦਰਜੇ ਦੀ ਸੋਚ (Second-Order Thinking)', paSummary: 'ਸਿਰਫ਼ ਤੁਰੰਤ ਦੇ ਫ਼ਾਇਦੇ ਦੀ ਬਜਾਏ ਭਵਿੱਖ ਵਿੱਚ ਨਿਕਲਣ ਵਾਲੇ ਅਸਲ ਨਤੀਜਿਆਂ ਦਾ ਅੰਦਾਜ਼ਾ ਲਾਉਣ ਦੀ ਵਿਧੀ।', paTakeaways: ['ਤੁਰੰਤ ਦੇ ਫ਼ਾਇਦੇ ਪਿੱਛੇ ਨਾ ਭੱਜੋ', 'ਕੋਬਰਾ ਇਫੈਕਟ ਤੋਂ ਸਿੱਖੋ', 'ਹਮੇਸ਼ਾ ਪੁੱਛੋ: "ਇਸ ਤੋਂ ਬਾਅਦ ਕੀ?"'],
    urTitle: 'دوسرے درجے کی سوچ (Second-Order Thinking)', urSummary: 'محض فوری نتائج دیکھنے کے بجائے طویل المدتی اور دور رس اثرات کا جائزہ لینے کا ذہنی ماڈل۔', urTakeaways: ['فوری فائدے کے فریب سے بچیں', 'کوبرا اثر سے سبق لیں', 'ہمیشہ پوچھیں: "اس کے بعد کیا ہوگا؟"'],
    orTitle: 'ଦ୍ୱିତୀୟ-ସ୍ତରୀୟ ଚିନ୍ତାଧାରା (Second-Order Thinking)', orSummary: 'କେବଳ ତତକ୍ଷଣାତ୍ ଲାଭ ନଦେଖି ଭବିଷ୍ୟତର ଦୂରଗାମୀ ପ୍ରଭାବ ଆକଳନ କରିବାର ମାନସିକ କଳା।', orTakeaways: ['ତତକ୍ଷଣାତ୍ ଫାଇଦା ପଛରେ ଗୋଡ଼ାନ୍ତୁ ନାହିଁ', 'କୋବ୍ରା ପ୍ରଭାବ ବୁଝନ୍ତୁ', '"ଏହା ପରେ କ\'ଣ?" ପ୍ରଶ୍ନ ପଚାରନ୍ତୁ'],
    asTitle: 'দ্বিতীয়-স্তৰীয় চিন্তা (Second-Order Thinking)', asSummary: 'কেৱল তাৎক্ষণিক ফলাফলৰ ওপৰত নিৰ্ভৰ নকৰি ভৱিষ্যতৰ সুদূৰপ্ৰসাৰী প্ৰভাৱ বিশ্লেষণ কৰাৰ মানসিক কৌশল।', asTakeaways: ['তাৎক্ষণিক লাভৰ মোহ ত্যাগ কৰক', 'কোব্ৰা ইফেক্টৰ বিষয়ে জানক', 'সদায় সোধক: "তাৰ পিছত কি?"']
  },

  {
    fileName: 'inversionTechnique.ts',
    varName: 'inversion_technique',
    id: 'inversion_technique',
    categoryId: 'critical_thinking',
    slug: 'the-inversion-technique',
    difficulty: 'intermediate',
    readTime: 5,
    sortWeight: 6,
    titleEn: 'The Inversion Technique: Invert, Always Invert',
    subtitleEn: 'Carl Jacobi and Charlie Munger on why avoiding stupidity is vastly easier than seeking brilliance.',
    shortDescEn: 'A powerful problem-solving framework where complex challenges are approached backwards by focusing on what you want to avoid rather than what you want to achieve.',
    oneLineEn: 'Tell me where I’m going to die so I simply never go there.',
    summary30sEn: 'Coined by 19th-century German mathematician Carl Gustav Jacob Jacobi ("Man muss immer umkehren" — Invert, always invert) and immortalized by Berkshire Hathaway’s Charlie Munger, inversion flips problems upside down. Instead of asking: "How do I make my startup succeed?", ask: "What actions would guarantee my startup fails completely?" Then systematically avoid them.',
    coreConceptEn: 'Human beings are poorly equipped to predict brilliant breakthroughs, but exceptionally adept at recognizing catastrophic failure modes. Trying to be consistently brilliant produces high error rates, hubris, and fragile bets. In contrast, systematically eliminating unforced errors (laziness, debt, arrogance, toxic culture) guarantees robust, compounding survival.',
    summary60sEn: 'Inversion forms the foundation of modern risk engineering: pre-mortems (imagining the project has died before launching), cybersecurity threat modeling (thinking like a malicious hacker), and personal health (eliminating smoking and junk sleep rather than hunting for exotic superfoods).',
    takeawaysEn: [
      '"Invert, always invert": Turn problems upside down to expose hidden blind spots',
      'Avoiding stupidity consistently is vastly more profitable than trying to be brilliant',
      'Pre-mortems anticipate catastrophic failure before a single dollar is spent',
      'Success is often the simple byproduct of ruthlessly eliminating unforced errors'
    ],
    whyItHappensEn: 'Asymmetry of downside: single catastrophic errors destroy decades of accumulated success; avoiding ruin preserves the option to compound.',
    evolutionaryEn: 'Ancestral survival favored hominids who prioritized not dying (avoiding cliffs, predators, and toxins) over those seeking marginal glory.',
    howItWorksEn: 'Goal stated ("Build a great marriage") -> Invert goal ("How do I guarantee a divorce?") -> List toxic behaviors (nagging, contempt, dishonesty) -> Ruthlessly eliminate those behaviors -> Healthy relationship emerges naturally.',
    visualHeadlineEn: 'Forward Ambition vs. Inversion Risk Elimination',
    visualDescEn: 'Charlie Munger’s mental model of inverted engineering.',
    sideALabelEn: 'Forward Thinking (Fragile)',
    sideADetailEn: '"How do I become a billionaire in 3 years?" -> High risk, excessive leverage, blindness to downside, frequent bankruptcy.',
    sideBLabelEn: 'Inversion Thinking (Antifragile)',
    sideBDetailEn: '"What guarantees financial ruin?" (Excess debt, gambling, zero emergency fund). Eliminates ruin -> Wealth compounds steadily.',
    researchSummaryEn: 'Munger (1995, Harvard University Address) and Klein (2007, Harvard Business Review) established the scientific efficacy of pre-mortems and inversion in reducing catastrophic operational errors by over 30%.',
    refAuthor: 'Munger, C. T. & Klein, G.',
    refYear: 1995,
    refTitle: 'The Psychology of Human Misjudgment / Performing a Project Premortem',
    refCitation: 'Klein, G. (2007). Harvard Business Review, 85(9), 18–19.',
    refDoi: 'https://doi.org/10.1225/R0709B',
    scenarioTitleEn: 'The Startup Pre-Mortem in Koramangala',
    scenarioContextEn: 'An ed-tech founding team in Koramangala, Bengaluru, gathered before launching their new mobile app. Instead of celebrating, the CEO said: "Imagine it is 12 months from now, our startup is completely bankrupt, and we are shutting down. What specifically killed us?"',
    scenarioBiasEn: 'Standard forward-planning teams suffer from collective optimism bias, ignoring fatal flaws until it is too late.',
    scenarioOptimalEn: 'By inverting, the team listed: 1) high customer acquisition cost, 2) slow Android load times, 3) lack of teacher retention. They re-engineered their app around these three vulnerabilities before launch.',
    scenarioReflectionEn: 'If you wanted to guarantee that your physical health collapses over the next 5 years, what daily habits would you adopt? How many of those are you doing right now?',
    howToRecognizeEn: 'Struggling with a complex, ambiguous problem where forward solutions feel overwhelming or paralyzing.',
    whereEn: 'Strategic corporate planning, personal financial independence, marital therapy, and aerospace safety engineering.',
    misconceptionsEn: 'Myth: "Inversion is pessimistic and negative thinking." Fact: Inversion is pragmatic realism; by securing the downside, it frees your mind to pursue upside with total confidence.',
    limitationsEn: 'Inversion eliminates bad paths, but creative breakthroughs (e.g. composing a symphony, inventing the iPhone) still require positive forward imagination.',
    howToRespondEn: 'The Premortem Drill: Before starting any major initiative, convene your team and write the fictional autopsy of how the project ended in total disaster.',
    defensesEn: [
      { title: 'The Anti-Goal Checklist', instruction: 'Alongside your yearly goals, maintain an "Anti-Goal" list: specific things you refuse to do, clients you refuse to work with, and habits you refuse to tolerate.' },
      { title: 'The Inverted Budget', instruction: 'Instead of trying to find the highest-risk stock to get rich quick, eliminate high-interest loans, unnecessary subscriptions, and speculative bets.' }
    ],
    pqPromptEn: 'A high school principal wants to dramatically improve student academic performance. Using the Inversion Technique, what question should the principal ask first?',
    pqScenarioEn: 'The administration has limited budget and needs immediate, high-impact improvements.',
    pqExplanationEn: 'Inversion focuses on identifying and eliminating the primary drivers of student failure and distraction before introducing complex new programs.',
    pqAntidoteEn: 'Invert the objective: ask what forces guarantee student failure and eliminate them systematically.',
    pqOptionsEn: [
      { id: 'opt_a', text: '"What expensive smartboards and virtual reality headsets can we buy for the classrooms?"', isCorrect: false, feedback: 'Incorrect. This is ungrounded forward spending.' },
      { id: 'opt_b', text: '"What factors currently guarantee that students fail, lose sleep, and get distracted—and how do we eliminate them?"', isCorrect: true, feedback: 'Correct! Inversion attacks failure modes directly to create success.' },
      { id: 'opt_c', text: '"How can we make exams 50% easier so everyone gets an A grade?"', isCorrect: false, feedback: 'Incorrect. Lowering standards destroys educational value.' }
    ],
    reflectionPromptEn: 'What is one obvious bad habit you indulge in weekly that, if completely eliminated, would immediately improve your quality of life?',
    titleHinglish: 'The Inversion Technique: Ulta Sochne Ka Kamaal',
    subtitleHinglish: 'Charlie Munger ka formula: Genius banne ki koshish mat karo, bas bewakoofiyaan karna band kar do.',
    shortDescHinglish: 'Carl Jacobi & Charlie Munger: "Invert, always invert" — Safalta paane ke bajaye barbadi ke raasto ko pehchan kar unhe block karna.',
    oneLineHinglish: 'Mujhe bas itna bata do ki meri maut kahan hogi, taaki main wahan kabhi na jau.',
    summary30sHinglish: 'Warren Buffett ke partner Charlie Munger ne kaha ki log hamesha sochte hain "Ameer kaise banein?". Par asli sawal yeh hona chahiye: "Garib aur barbad kaise bante hain?" Agar aap karz, juwa, aalas aur ghamand se bach jao, to ameer banna automatic ho jata hai!',
    coreConceptHinglish: 'Ise kehte hain Inversion Technique ("Ulta Sochna"). Jacobi ne kaha tha: "Hamesha ulta socho". Seedha sochna mushkil hota hai, par galti dhoondna asaan hota hai. Agar aapko ek acchi shaadi chahiye, to socho "Ek shaadi kaise barbad hoti hai?" (Dhokha, disrespect, jhooth). In cheezon ko zindgi se nikaal phek do, rishta khud behtar ho jayega.',
    summary60sHinglish: 'Startups me is technique ko "Pre-Mortem" kehte hain. Project launch karne se pehle team baithti hai aur sochti hai: "Maan lo 1 saal baad hamari company band ho gayi. Hum kyu barbad huye?" Sab log kamzoriyan likhte hain aur launch se pehle hi unhe theek kar lete hain.',
    howItWorksHinglish: 'Goal banaya -> Goal ko ulta kiya ("Barbad kaise hona hai?") -> Barbadi ke 5 raaste likhe -> Un 5 raasto ko block kiya -> Safalta guaranteed ho gayi.',
    howToRespondHinglish: 'Pre-Mortem lagao: Koi bhi naya kaam shuru karne se pehle socho: "Agar yeh plan sabse bada disaster bana, to uski wajah kya hogi?" Un galtiyo ko abhi theek karo.',
    takeawaysHinglish: [
      'Galtiyon se bachna hero banne se zyada faydemand hota hai',
      '"Invert, always invert": Problem ko ulta karke dekho, solution saaf dikhega',
      'Pre-mortem se disaster hone se pehle hi kamzoriyan pakad me aa jati hain',
      'Anti-Goals banao: Yeh tay karo ki zindgi me kya KABHI nahi karna hai'
    ],
    pqPromptHinglish: 'Agar ek student ko exam me top karna hai, to Inversion Technique ke mutabiq use pehle kya sochna chahiye?',
    pqExplanationHinglish: 'Inversion kehta hai ki pehle yeh dekho ki exam me fail hone ke kya guaranteed tareeqe hain (Phone addiction, procrastination, last night cramming) aur unhe band karo.',
    pqOptionsHinglish: [
      { id: 'opt_a', text: 'Yeh sochna ki topper ban kar interview me kya bolunga.', isCorrect: false, feedback: 'Galat. Yeh day-dreaming hai.' },
      { id: 'opt_b', text: 'Yeh sochna ki ek student fail kaise hota hai (Phone addiction, notes na padhna) aur un aadtoko pehle khatam karna.', isCorrect: true, feedback: 'Sahi! Inversion failure modes ko eliminate karke success ensure karta hai.' },
      { id: 'opt_c', text: 'Exam se ek raat pehle 10 Red Bull peena.', isCorrect: false, feedback: 'Galat. Yeh guaranteed disaster hai.' }
    ],
    hiTitle: 'उलटाव तकनीक (The Inversion Technique)',
    hiSummary: 'सफलता के सीधे मार्ग खोजने के बजाय विफलता और बर्बादी के कारणों को पहचानकर उन्हें योजनाबद्ध रूप से समाप्त करने का मानसिक मॉडल।',
    hiTakeaways: ['"उलटा सोचें, हमेशा उलटा सोचें": समस्याओं को उलटकर नए समाधान खोजें', 'मूर्खतापूर्ण गलतियों से बचना अत्यधिक बुद्धिमानी दिखाने से अधिक लाभकारी है', 'परियोजना शुरू करने से पहले प्री-मॉर्टम (Pre-Mortem) विश्लेषण करें'],
    guTitle: 'ઇન્વર્ઝન ટેકનિક (ઊંધું વિચારવાની કળા)', guSummary: 'સફળતા શોધવા કરતાં નિષ્ફળતાના કારણો જાણી તેને દૂર કરવાની ચાર્લી મંગરની અદભુત પદ્ધતિ.', guTakeaways: ['હંમેશા ઊંધું વિચારો', 'ભૂલો ટાળવી એ જ સાચી બુદ્ધિ છે', 'પ્રી-મોર્ટમ વિશ્લેષણ કરો'],
    mrTitle: 'उलटे विचार तंत्र (Inversion Technique)', mrSummary: 'यश मिळवण्यापेक्षा अपयशाची कारणे शोधून ती नष्ट करण्यावर भर देणारी चार्ली मंगर यांची विचारसरणी.', mrTakeaways: ['नेहमी उलटा विचार करा', 'चुका टाळणे म्हणजेच यश मिळवणे', 'प्री-मॉर्टेम तंत्राचा वापर करा'],
    teTitle: 'విలోమ పద్ధతి (Inversion Technique)', teSummary: 'విజయాన్ని వెతకడం కంటే వైఫల్యానికి దారితీసే కారణాలను గుర్తించి వాటిని నివారించే మానసిక నమూనా.', teTakeaways: ['ఎల్లప్పుడూ విలోమంగా ఆలోచించండి', 'మూర్ఖత్వాలను నివారించడమే అసలైన విజయం', 'ప్రీ-మార్టమ్ విశ్లేషణ చేయండి'],
    taTitle: 'தலைகீழ் சிந்தனை நுட்பம் (Inversion Technique)', taSummary: 'வெற்றியைத் தேடுவதை விட தோல்விக்கான காரணங்களை அடையாளம் கண்டு அவற்றை அகற்றும் சக்திவாய்ந்த சிந்தனை முறை.', taTakeaways: ['எப்போதும் தலைகீழாக சிந்தியுங்கள்', 'முட்டாள்தனங்களை தவிர்ப்பதே வெற்றி', 'ப்ரீ-மார்ட்டம் முறையை பின்பற்றுங்கள்'],
    knTitle: 'ವಿಲೋಮ ಚಿಂತನಾ ತಂತ್ರ (Inversion Technique)', knSummary: 'ಗೆಲುವನ್ನು ಹುಡುಕುವ ಬದಲು ಸೋಲಿಗೆ ಕಾರಣವಾಗುವ ಅಂಶಗಳನ್ನು ಗುರುತಿಸಿ ಅವುಗಳನ್ನು ತಪ್ಪಿಸುವ ಮಾನಸಿಕ ಮಾದರಿ.', knTakeaways: ['ಯಾವಾಗಲೂ ವಿಲೋಮವಾಗಿ ಯೋಚಿಸಿ', 'ತಪ್ಪುಗಳನ್ನು ತಪ್ಪಿಸುವುದೇ ಜಾಣ್ಮೆ', 'ಪ್ರೀ-ಮಾರ್ಟಮ್ ವಿಶ್ಲೇಷಣೆ ನಡೆಸಿ'],
    mlTitle: 'വിപരീത ചിന്താ രീതി (Inversion Technique)', mlSummary: 'വിജയം തേടുന്നതിനേക്കാൾ പരാജയത്തിന്റെ കാരണങ്ങൾ കണ്ടെത്തി അവ ഒഴിവാക്കാൻ പഠിപ്പിക്കുന്ന ചിന്താരീതി.', mlTakeaways: ['എപ്പോഴും വിപരീതമായി ചിന്തിക്കുക', 'വിഡ്ഢിത്തങ്ങൾ ഒഴിവാക്കുക', 'പ്രീ-മോർട്ടം വിശകലനം നടത്തുക'],
    bnTitle: 'বিপরীতায়ন কৌশল (Inversion Technique)', bnSummary: 'সরাসরি সাফল্যের পেছনে না ছুটে ব্যর্থতার সম্ভাব্য কারণগুলি চিহ্নিত করে তা নির্মূল করার মনস্তাত্ত্বিক পদ্ধতি।', bnTakeaways: ['সবসময় উল্টো করে ভাবুন', 'বোকামি এড়িয়ে চলাই আসল বুদ্ধিমত্তা', 'কাজের আগে প্রি-মর্টেম অ্যানালাইসিস করুন'],
    paTitle: 'ਉਲਟ ਸੋਚਣ ਦੀ ਤਕਨੀਕ (Inversion Technique)', paSummary: 'ਕਾਮਯਾਬੀ ਲੱਭਣ ਨਾਲੋਂ ਨਾਕਾਮੀ ਦੇ ਕਾਰਨਾਂ ਨੂੰ ਪਛਾਣ ਕੇ ਉਨ੍ਹਾਂ ਨੂੰ ਖ਼ਤਮ ਕਰਨ ਦਾ ਮਾਨਸਿਕ ਫਾਰਮੂਲਾ।', paTakeaways: ['ਹਮੇਸ਼ਾ ਉਲਟਾ ਸੋਚੋ', 'ਗ਼ਲਤੀਆਂ ਤੋਂ ਬਚਣਾ ਹੀ ਸਭ ਤੋਂ ਵੱਡੀ ਸਿਆਣਪ ਹੈ', 'ਪ੍ਰੀ-ਮਾਰਟਮ ਵਿਧੀ ਅਪਣਾਓ'],
    urTitle: 'الٹ سوچ کی تکنیک (Inversion Technique)', urSummary: 'کامیابی کے راستے تلاش کرنے کے بجائے ناکامی کی وجوہات کو پہچان کر ان کا خاتمہ کرنے کا طریقہ۔', urTakeaways: ['ہمیشہ الٹا سوچیں', 'بیوقوفیوں سے بچنا ہی اصل کامیابی ہے', 'کام سے پہلے پری مارٹم تجزیہ کریں'],
    orTitle: 'ବିପରୀତ ଚିନ୍ତନ କୌଶଳ (Inversion Technique)', orSummary: 'ସଫଳତା ଖୋଜିବା ଅପେକ୍ଷା ବିଫଳତାର କାରଣଗୁଡ଼ିକୁ ଚିହ୍ନଟ କରି ସେଗୁଡ଼ିକୁ ଦୂର କରିବାର ମାନସିକ ପଦ୍ଧତି।', orTakeaways: ['ସର୍ବଦା ଓଲଟା ଚିନ୍ତା କରନ୍ତୁ', 'ମୂର୍ଖାମୀରୁ ବଞ୍ଚିବା ହିଁ ବୁଦ୍ଧିମତା', 'ପ୍ରି-ମର୍ଟମ୍ ବିଶ୍ଳେଷଣ କରନ୍ତୁ'],
    asTitle: 'বিপৰীত চিন্তাৰ কৌশল (Inversion Technique)', asSummary: 'সফলতাৰ সন্ধান কৰাৰ বিপৰীতে ব্যৰ্থতাৰ কাৰণসমূহ চিনাক্ত কৰি সেইবোৰ নিৰ্মূল কৰাৰ মানসিক আৰ্হি।', asTakeaways: ['সদায় ওলোটাকৈ ভাবক', 'মূৰ্খামি পৰিহাৰ কৰাটোৱেই প্ৰকৃত বুদ্ধিমত্তা', 'কামৰ পূৰ্বে প্ৰি-মৰ্টেম বিশ্লেষণ কৰক']
  },

  {
    fileName: 'hanlonsRazor.ts',
    varName: 'hanlons_razor',
    id: 'hanlons_razor',
    categoryId: 'critical_thinking',
    slug: 'hanlons-razor',
    difficulty: 'beginner',
    readTime: 5,
    sortWeight: 7,
    titleEn: 'Hanlon’s Razor: Never Attribute to Malice What Stupidity Explains',
    subtitleEn: 'Robert J. Hanlon on cutting through paranoia, grievance, and fabricated conspiracies in human conflict.',
    shortDescEn: 'A philosophical razor suggesting that when someone does something that causes harm or inconvenience, it is far more likely due to negligence, ignorance, or incompetence than deliberate malevolence.',
    oneLineEn: 'Stop inventing evil conspiracies when plain exhaustion, rushing, or clumsiness is the real culprit.',
    summary30sEn: 'Coined by Robert J. Hanlon in 1980 (and echoed by Goethe and Napoleon Bonaparte), Hanlon’s Razor is an indispensable cognitive tool for mental peace and interpersonal sanity. When an email goes unanswered, a driver cuts you off, or a coworker drops a project file, your brain instinctively invents an intentional personal attack. Hanlon’s razor slices away paranoia.',
    coreConceptEn: 'The human brain is an hyperactive agency-detection device. When we experience pain or frustration, we instinctively hallucinate an intentional villain behind the misfortune. In reality, human beings are chronically tired, distracted, overwhelmed, and misinformed. True deliberate malice is statistically rare; simple incompetence, cognitive overload, and careless oversight account for 95% of social friction.',
    summary60sEn: 'Applying Hanlon’s Razor defuses rage in corporate workplaces, romantic relationships, and customer service disputes. Instead of retaliating against an imagined enemy (which sparks an escalating vendetta), you approach the situation with curiosity, empathy, and constructive clarification, saving immense emotional energy.',
    takeawaysEn: [
      'Assume incompetence, distraction, or fatigue before assuming deliberate malice',
      'The brain is biologically wired to over-detect intentional threats (Hostile Attribution Bias)',
      'Escalating retaliation against innocent blunders creates real enemies out of thin air',
      'Asking curious clarifying questions resolves issues faster than accusatory confrontations'
    ],
    whyItHappensEn: 'Hostile Attribution Bias: evolutionary threat detection biased early humans to assume rustling leaves were a predator rather than the wind.',
    evolutionaryEn: 'Assuming hostility kept ancestors alive in warring tribal skirmishes; in modern cooperative society, it ruins partnerships and creates chronic paranoia.',
    howItWorksEn: 'Frustrating event occurs -> Amygdala triggers anger -> Default assumption: "They did this deliberately to hurt me!" -> Apply Hanlon\'s Razor -> Realize: "They were probably just overwhelmed or forgot" -> Calm communication initiated.',
    visualHeadlineEn: 'Paranoid Attribution vs. Hanlon’s Reality Filter',
    visualDescEn: 'Robert Hanlon’s interpersonal explanatory filter.',
    sideALabelEn: 'Paranoid Mindset (Default)',
    sideADetailEn: '"My boss didn’t reply to my WhatsApp message for 8 hours because she hates me and plans to fire me!" -> Panic and passive aggression.',
    sideBLabelEn: 'Hanlon’s Razor (Rational)',
    sideBDetailEn: '"My boss had 14 meetings, a crying toddler at home, and accidentally swiped the notification away." -> Zero emotional distress.',
    researchSummaryEn: 'Crick & Dodge (1994, Psychological Bulletin) documented the mechanics of Hostile Attribution Bias and how cognitive reframing via heuristic razors eliminates retaliatory aggression.',
    refAuthor: 'Hanlon, R. J. & Crick, N. R.',
    refYear: 1980,
    refTitle: 'Murphy’s Law Book Two: More Reasons Why Things Go Wrong!',
    refCitation: 'Hanlon, R. J. (1980). Arthur Bloch (Ed.), Price Stern Sloan.',
    refDoi: 'https://doi.org/10.1037/0033-2909.115.1.74',
    scenarioTitleEn: 'The Delayed WhatsApp Blue Tick Drama in Delhi',
    scenarioContextEn: 'Neha sent her project proposal to her teammate Rahul at 10 AM in Gurugram. By 4 PM, she saw two blue ticks on WhatsApp but no reply. Her mind spiraled: "He is stealing my idea! He thinks I am incompetent!" She drafted a scathing email to their VP. Before clicking send, she walked to his desk and saw Rahul frantically troubleshooting a crashed client server with sweat on his forehead.',
    scenarioBiasEn: 'Neha fell into the Hostile Attribution trap, constructing a villainous conspiracy around a simple case of priority overload.',
    scenarioOptimalEn: 'Apply Hanlon\'s Razor: send a polite, neutral follow-up: "Hey Rahul, hope you\'re having a good day! Whenever you get a breathing moment, let me know your thoughts on the proposal."',
    scenarioReflectionEn: 'When someone doesn’t reply to your text or forgets a promise, is your first instinct to feel hurt and angry, or to wonder what crisis they are managing?',
    howToRecognizeEn: 'Feeling a sudden surge of righteous indignation and believing someone is orchestrating a subtle campaign against you.',
    whereEn: 'Remote work communication (Slack/Email), marital misunderstandings, highway driving, and customer support disputes.',
    misconceptionsEn: 'Myth: "Hanlon’s Razor means being a naive doormat who lets malicious people walk over them." Fact: Hanlon’s Razor applies to first-time blunders; repeated, documented patterns of harmful behavior should be dealt with strictly.',
    limitationsEn: 'When dealing with geopolitical state espionage, corporate corporate fraud, or toxic narcissists, deliberate malice must be actively evaluated.',
    howToRespondEn: 'The 24-Hour Benevolence Pause: When feeling offended by someone\'s action, wait 24 hours and force yourself to find three benign explanations (busy, tired, sick) before reacting.',
    defensesEn: [
      { title: 'The Generous Interpretation Reflex', instruction: 'Force yourself to state the most charitable possible motive for the other person’s blunder out loud.' },
      { title: 'The Direct Clarification Query', instruction: 'Replace accusations with questions: "Hey, I noticed X happened; was that intentional or did something slip through the cracks?"' }
    ],
    pqPromptEn: 'A driver cuts abruptly into your lane on the Mumbai-Pune Expressway without using an indicator, forcing you to tap your brakes. According to Hanlon’s Razor, what is the most statistically probable explanation?',
    pqScenarioEn: 'Your immediate emotional reaction is to honk furiously and assume the driver is an aggressive sociopath.',
    pqExplanationEn: 'Statistically, drivers make lane errors because they are distracted, missed an exit, or have a crying child in the backseat, not because they targeted you personally.',
    pqAntidoteEn: 'Remind yourself: "Never attribute to malice what is easily explained by human distraction or poor driving skill."',
    pqOptionsEn: [
      { id: 'opt_a', text: 'The driver specifically targeted you to ruin your day and assert dominance.', isCorrect: false, feedback: 'Incorrect. Egocentric hostile attribution.' },
      { id: 'opt_b', text: 'The driver was distracted, inexperienced, or panicked about an upcoming highway exit.', isCorrect: true, feedback: 'Correct! Hanlon’s Razor recognizes incompetence and distraction over malice.' },
      { id: 'opt_c', text: 'The driver is an undercover agent in a high-speed chase.', isCorrect: false, feedback: 'Incorrect. Hollywood fantasy.' }
    ],
    reflectionPromptEn: 'Who in your life are you currently assuming has malicious intentions toward you, and what innocent blunder might actually explain their behavior?',
    titleHinglish: 'Hanlon’s Razor: Har Baat Par Dushmani Mat Dhoondo',
    subtitleHinglish: 'Robert Hanlon ka rule: Jis cheez ki wajah aam galti, thakawat ya aalas ho sakti hai, use saazish mat samjho.',
    shortDescHinglish: 'Hostile Attribution Bias: Kisi ne reply nahi kiya to dushman mat maano; ho sakta hai wo busy ho ya bhool gaya ho.',
    oneLineHinglish: 'Har galti ke peeche villain nahi hota, aksar log bas thake huye aur distracted hote hain.',
    summary30sHinglish: '1980 me Robert Hanlon ne ek golden rule diya: "Kabhi bhi us baat ke peeche buri neeyat mat maano jise aam bewakoofi ya laparwahi se explain kiya ja sake." Agar kisi ne aapka message dekh kar reply nahi kiya, ya traffic me aage gaadi daal di, to wo aapse dushmani nahi nikaal raha, bas thaka hua ya distracted hai.',
    coreConceptHinglish: 'Insaan ka dimaag hamesha saazish dhoondhta hai. Office me boss ne thoda rude baat ki to hum sochte hain "Yeh mujhe nikaalne ki planning kar raha hai". Par reality yeh hoti hai ki boss ki biwi bimaar thi ya client ne use daanta tha. Asli buri neeyat 5% hoti hai, 95% mamle me log bas confused aur overworked hote hain.',
    summary60sHinglish: 'Hanlon\'s Razor apnaane se dimaag ka 90% gussa aur stress gayab ho jata hai. WhatsApp par blue tick aane ke baad overthink karna band karo. Ladai karne ke bajaye kindly poocho: "Sab theek hai na bhai?" Dushmani create karne se bacho.',
    howItWorksHinglish: 'Kisi ne galti ki -> Gussa aaya ("Usne jaanboojh kar kiya!") -> Hanlon\'s Razor lagaya -> "Nahi, wo busy hoga ya bhool gaya" -> Shanti se baat ki -> Rishta bach gaya.',
    howToRespondHinglish: '24-Hour Rule: Jab kisi ki baat se bura lage, to turant ladne mat lago. 24 ghante ruko aur socho: "Kya wo thaka hua tha? Kya use koi tension thi?"',
    takeawaysHinglish: [
      'Har buri cheez ke peeche saazish dhoondhna band karo',
      'Log aksar bure nahi hote, bas careless, thake huye aur confuse hote hain',
      'Galti ko dushmani samajh kar ladna naye dushman paida karta hai',
      'Shanti se clarify karo: "Bhai kya hua, sab theek hai na?"'
    ],
    pqPromptHinglish: 'Colleague ne 6 ghante tak important email ka reply nahi kiya. Hanlon\'s Razor ke hisaab se sabse likely wajah kya hai?',
    pqExplanationHinglish: 'Hanlon\'s razor kehta hai ki wo dushmani nikaalne ke bajaye meetings me fasa hoga ya reply karna bhool gaya hoga.',
    pqOptionsHinglish: [
      { id: 'opt_a', text: 'Wo aapke khilaf office politics kar raha hai aur career barbad karna chahta hai.', isCorrect: false, feedback: 'Galat. Yeh unnecessary paranoia hai.' },
      { id: 'opt_b', text: 'Wo kisi urgent meeting me busy hoga ya uska dhyan bhatak gaya hoga.', isCorrect: true, feedback: 'Sahi! Yahi Hanlon’s Razor ka practical application hai.' },
      { id: 'opt_c', text: 'Uska laptop hack ho gaya hai.', isCorrect: false, feedback: 'Galat.' }
    ],
    hiTitle: 'हैनलॉन का उस्तरा (Hanlon’s Razor)',
    hiSummary: 'किसी भी कार्य के पीछे दुर्भावना या षड्यंत्र मानने से बचने का सिद्धांत, जिसे मानवीय भूल, अज्ञानता या थकावट द्वारा आसानी से समझाया जा सके।',
    hiTakeaways: ['दुर्भावना मानने से पहले मानवीय भूल, व्याकुलता या लापरवाही की संभावना देखें', 'शत्रुतापूर्ण आरोपण पूर्वाग्रह (Hostile Attribution Bias) से बचें', 'क्रोधित होने के बजाय विनम्रतापूर्वक स्पष्टीकरण मांगें'],
    guTitle: 'હેનલોનનું રેઝર (Hanlon’s Razor)', guSummary: 'કોઈની ભૂલ પાછળ દ્વેષભાવ શોધવાને બદલે અજ્ઞાનતા કે થાકને કારણ ગણવાનો બુદ્ધિગમ્ય સિદ્ધાંત.', guTakeaways: ['દરેક વાતમાં ષડયંત્ર ન શોધો', 'લોકો ઘણીવાર માત્ર થાકેલા હોય છે', 'શાંતિથી સ્પષ્ટતા માંગો'],
    mrTitle: 'हॅनलॉन्स रेझर (Hanlon’s Razor)', mrSummary: 'एखाद्या कृतीमागे वाईट हेतू शोधण्यापेक्षा मानवी निष्काळजीपणा किंवा अज्ञानाला कारण मानण्याची विचारसरणी.', mrTakeaways: ['षड्यंत्राचा संशय घेणे टाळा', 'माणसे अनेकदा व्यस्त किंवा थकलेली असतात', 'शांततेने चर्चा करा'],
    teTitle: 'హాన్లాన్స్ రేజర్ (Hanlon’s Razor)', teSummary: 'ఎవరి చర్యల వెనుకా కుట్ర లేదా దురుద్దేశం ఆపాదించకుండా, పొరపాటు లేదా అలసటగా భావించే విధానం.', teTakeaways: ['దురుద్దేశాన్ని ఊహించవద్దు', 'అజాగ్రత్త లేదా ఒత్తిడి కారణం కావచ్చు', 'శాంతియుతంగా వివరణ కోరండి'],
    taTitle: 'ஹான்லானின் ரேஸர் (Hanlon’s Razor)', taSummary: 'ஒருவரின் தவறை வேண்டுமென்றே செய்த சதியாக பார்க்காமல், கவனக்குறைவு அல்லது அறியாமையாக பார்க்கும் அறிவார்ந்த அணுகுமுறை.', taTakeaways: ['சதித்திட்டங்களை கற்பனை செய்யாதீர்கள்', 'மக்களின் சோர்வை புரிந்து கொள்ளுங்கள்', 'அமைதியாக விளக்கம் கேளுங்கள்'],
    knTitle: 'ಹ್ಯಾನ್ಲಾನ್‌ನ ರೇಜರ್ (Hanlon’s Razor)', knSummary: 'ಯಾರಾದರೂ ತಪ್ಪು ಮಾಡಿದಾಗ ಅದರಲ್ಲಿ ದುರುದ್ದೇಶ ಹುಡುಕುವ ಬದಲು ಅಜ್ಞಾನ ಅಥವಾ ಆಯಾಸ ಕಾರಣವೆಂದು ತಿಳಿಯುವ ತತ್ವ.', knTakeaways: ['ದುರುದ್ದೇಶವನ್ನು ಊಹಿಸಬೇಡಿ', 'ಜನರು ಸುಸ್ತಾಗಿರಬಹುದು ಅಥವಾ ಮರೆತಿರಬಹುದು', 'ಶಾಂತವಾಗಿ ಸ್ಪಷ್ಟೀಕರಣ ಕೇಳಿ'],
    mlTitle: 'ഹാൻലൺസ് റേസർ (Hanlon’s Razor)', mlSummary: 'മറ്റുള്ളവരുടെ തെറ്റുകൾക്ക് പിന്നിൽ ദുരുദ്ദേശ്യം കാണാതെ, അശ്രദ്ധയോ അറിവില്ലായ്മയോ ആയി കാണുന്ന രീതി.', mlTakeaways: ['ദുരുദ്ദേശ്യം ആരോപിക്കരുത്', 'മനുഷ്യസഹജമായ തെറ്റുകൾ മനസ്സിലാക്കുക', 'സമാധാനപരമായി കാര്യം തിരക്കുക'],
    bnTitle: 'হ্যানলনের রেজর (Hanlon’s Razor)', bnSummary: 'কারো কোনো ভুল বা ক্ষতিকারক আচরণের পেছনে শত্রুতা না খুঁজে মানুষের অজ্ঞতা বা অসচেতনতাকে কারণ হিসেবে দেখার মানসিক নিয়ম।', bnTakeaways: ['সবকিছুতে শত্রুতা বা ষড়যন্ত্র খুঁজবেন না', 'মানুষ প্রায়শই কেবল ক্লান্ত বা বিভ্রান্ত থাকে', 'রাগ করার আগে শান্তভাবে জেনে নিন'],
    paTitle: 'ਹੈਨਲਨ ਦਾ ਰੇਜ਼ਰ (Hanlon’s Razor)', paSummary: 'ਕਿਸੇ ਦੀ ਗ਼ਲਤੀ ਪਿੱਛੇ ਦੁਸ਼ਮਣੀ ਜਾਂ ਸਾਜ਼ਿਸ਼ ਲੱਭਣ ਦੀ ਬਜਾਏ ਉਸਨੂੰ ਆਮ ਭੁੱਲ ਜਾਂ ਲਾਪਰਵਾਹੀ ਸਮਝਣ ਦਾ ਸਿਧਾਂਤ।', paTakeaways: ['ਹਰ ਗੱਲ ਪਿੱਛੇ ਸਾਜ਼ਿਸ਼ ਨਾ ਦੇਖੋ', 'ਲੋਕ ਅਕਸਰ ਸਿਰਫ਼ ਥੱਕੇ ਜਾਂ ਪਰੇਸ਼ਾਨ ਹੁੰਦੇ ਹਨ', 'ਸ਼ਾਂਤੀ ਨਾਲ ਗੱਲਬਾਤ ਕਰੋ'],
    urTitle: 'ہینلون کا استرا (Hanlon’s Razor)', urSummary: 'کسی کے عمل کے پیچھے بدنیتی تلاش کرنے کے بجائے اسے محض غفلت، نادانی یا تھکن سمجھنے کا اصول۔', urTakeaways: ['ہر بات کے پیچھے سازش نہ تلاش کریں', 'لوگ اکثر محض غافل یا تھکے ہوتے ہیں', 'غصے کے بجائے پرسکون انداز میں معلوم کریں'],
    orTitle: 'ହାନଲନଙ୍କ ରେଜର (Hanlon’s Razor)', orSummary: 'କାହାର ଭୁଲ୍ ପଛରେ ଶତ୍ରୁତା ବା ଷଡ଼ଯନ୍ତ୍ର ନଖୋଜି ତାହାକୁ ଅଜ୍ଞତା ବା କ୍ଳାନ୍ତି ବୋଲି ବୁଝିବାର ବୈଜ୍ଞାନିକ ନିୟମ।', orTakeaways: ['ଷଡ଼ଯନ୍ତ୍ର ସନ୍ଦେହ କରନ୍ତୁ ନାହିଁ', 'ଲୋକେ ପ୍ରାୟତଃ ବ୍ୟସ୍ତ ବା ଅସାବଧାନ ଥାଆନ୍ତି', 'ଶାନ୍ତିପୂର୍ଣ୍ଣ ଭାବେ ବୁଝନ୍ତୁ'],
    asTitle: 'হেনলনৰ ৰেজৰ (Hanlon’s Razor)', asSummary: 'কাৰোবাৰ ভুলৰ আঁৰত শত্ৰুতা বা কু-অভিপ্ৰায় নিবিচাৰি মানুহৰ অজ্ঞতা বা ভাগৰক কাৰণ বুলি ধৰি লোৱাৰ যুক্তিপূৰ্ণ নীতি।', asTakeaways: ['সকলোতে ষড়যন্ত্ৰ নেদেখিব', 'মানুহ প্ৰায়েই কেৱল ব্যস্ত বা পাহৰণিৰ চিকাৰ হয়', 'শান্তভাৱে স্পষ্টীকৰণ বিচাৰক']
  },

  {
    fileName: 'mapTerritoryFallacy.ts',
    varName: 'map_territory_fallacy',
    id: 'map_territory_fallacy',
    categoryId: 'critical_thinking',
    slug: 'the-map-is-not-the-territory',
    difficulty: 'advanced',
    readTime: 6,
    sortWeight: 8,
    titleEn: 'The Map Is Not the Territory: Abstract Models vs. Raw Reality',
    subtitleEn: 'Alfred Korzybski on why confusing our simplified mental diagrams with complex physical reality leads to catastrophic blunders.',
    shortDescEn: 'A foundational epistemological mental model stating that human perceptions, abstractions, and financial models are mere simplified representations of reality, not reality itself.',
    oneLineEn: 'You cannot walk on the blueprint of a house, and the menu is not the meal.',
    summary30sEn: 'Coined in 1931 by Polish-American philosopher Alfred Korzybski, "The map is not the territory" is the cornerstone of intellectual humility. Every theory, spreadsheet, medical chart, or political ideology is an abstraction that discards 99% of reality’s chaotic nuance to fit into human working memory. Catastrophe strikes when we fall in love with the map and ignore the jagged ground beneath our feet.',
    coreConceptEn: 'Maps are necessary reductions; a 1:1 scale map containing every pebble, gust of wind, and blade of grass would be useless. But every reduction introduces blind spots. In the 2008 financial crash, Wall Street quant models mathematically proved that subprime mortgage default risks were diversified; the model was pristine, but the real-world housing market collapsed anyway.',
    summary60sEn: 'Software engineers, corporate strategists, and government policymakers chronically mistake dashboard metrics for customer happiness. A KPI is just a map; user frustration is the territory. Whenever your metric says everything is green but users are furious, throw away the metric: the territory always wins.',
    takeawaysEn: [
      'Every model, dashboard, and mental framework is an imperfect simplification',
      'Confusing the menu with the meal causes catastrophic strategic blindness',
      'When your spreadsheet contradicts messy physical reality, the spreadsheet is wrong',
      'Continuously update your mental maps by touching ground-truth physical reality'
    ],
    whyItHappensEn: 'Cognitive compression: the brain must aggressively compress sensory data into low-dimensional semantic symbols to prevent metabolic energy collapse.',
    evolutionaryEn: 'Hominids survived by using coarse symbolic categories ("predator", "edible"); survival rewarded rapid heuristic maps over infinite sensory precision.',
    howItWorksEn: 'Complex reality exists -> Model constructed -> Model simplifies reality -> People optimize for the model -> Reality shifts dynamically -> Model diverges -> Catastrophic crash.',
    visualHeadlineEn: 'Pristine Spreadsheet Model vs. Jagged Ground Reality',
    visualDescEn: 'Alfred Korzybski’s abstraction abstraction hierarchy.',
    sideALabelEn: 'The Map (Abstraction)',
    sideADetailEn: 'A financial model showing 0.001% risk of bank failure based on 5-year historical averages.',
    sideBLabelEn: 'The Territory (Reality)',
    sideBDetailEn: 'A sudden panic triggers a digital bank run over Twitter/X in 4 hours, draining $42 Billion (Silicon Valley Bank, 2023).',
    researchSummaryEn: 'Korzybski (1933, Science and Sanity) and Box (1976, Journal of the American Statistical Association: "All models are wrong, but some are useful") demonstrated the fundamental limits of formal abstraction.',
    refAuthor: 'Korzybski, A. & Box, G. E. P.',
    refYear: 1933,
    refTitle: 'Science and Sanity: An Introduction to Non-Aristotelian Systems / Science and Statistics',
    refCitation: 'Box, G. E. P. (1976). J. of the American Statistical Association, 71(356), 791–799.',
    refDoi: 'https://doi.org/10.1080/01621459.1976.10480949',
    scenarioTitleEn: 'The GPS River Plunge in Kerala',
    scenarioContextEn: 'During heavy monsoon rains in Kerala, three tourists blindly followed Google Maps directions at midnight. The navigation map showed a continuous blue line, completely unaware that a bridge had washed away hours earlier. The driver accelerated into a raging river, narrowly escaping drowning.',
    scenarioBiasEn: 'The driver trusted the digital map over their physical eyes and local weather alerts, committing the classic Map-Territory fallacy.',
    scenarioOptimalEn: 'Always treat models as advisory hints: verify current ground truth with physical observation before taking irreversible actions.',
    scenarioReflectionEn: 'What dashboard metric or performance review score do you optimize for at work that doesn’t actually reflect the real quality of your contribution?',
    howToRecognizeEn: 'Arguing that reality "must be wrong" because your theory, policy document, or financial spreadsheet predicted otherwise.',
    whereEn: 'Macroeconomic policy, algorithmic trading, corporate OKRs/KPIs, military combat operations, and AI prompt engineering.',
    misconceptionsEn: 'Myth: "Because maps are imperfect, we should discard all models and rely purely on gut instinct." Fact: Models are indispensable tools for navigation; we must simply remember their boundary conditions and margins of error.',
    limitationsEn: 'In purely closed mathematical systems (like Euclidean geometry or chess), the rules and axioms ARE the complete territory; the fallacy applies to physical and human systems.',
    howToRespondEn: 'The Ground-Truth Audit: Step out of the boardroom or terminal and spend 4 hours observing actual customers using your product in the real world.',
    defensesEn: [
      { title: 'The Boundary Condition Check', instruction: 'Explicitly state the exact assumptions under which your business model or plan will completely break down.' },
      { title: 'Gemba Walk (Go and See)', instruction: 'Adopt the Toyota lean manufacturing rule: never make a production decision from an office; walk the physical assembly line floor.' }
    ],
    pqPromptEn: 'A hospital administrator is delighted because the computer dashboard shows that average patient wait times in the emergency room dropped from 45 minutes to 8 minutes. However, patient mortality rose by 15%. What explains this discrepancy?',
    pqScenarioEn: 'The hospital had instituted a policy penalizing doctors if patient check-in wait times exceeded 10 minutes on the computer.',
    pqExplanationEn: 'The staff optimized for the map (logging patients into rooms in the software within 8 minutes) while the territory (actual medical care delivery) degraded dangerously.',
    pqAntidoteEn: 'Remember: "The metric is not the care; never sacrifice the territory to make the map look pretty."',
    pqOptionsEn: [
      { id: 'opt_a', text: 'The computer software had a virus that poisoned the medication dispensers.', isCorrect: false, feedback: 'Incorrect. Science fiction explanation.' },
      { id: 'opt_b', text: 'Goodhart’s Law and Map-Territory Fallacy: staff gamed the computer metric by moving patients into unstaffed rooms without providing real medical care.', isCorrect: true, feedback: 'Correct! The dashboard map diverged completely from clinical reality.' },
      { id: 'opt_c', text: 'Patient mortality naturally spikes whenever wait times drop.', isCorrect: false, feedback: 'Incorrect. Causation is reversed by metric gaming.' }
    ],
    reflectionPromptEn: 'Where in your personal life are you mistaking a symbolic label (like your job title, bank balance, or BMI) for your actual wellbeing and identity?',
    titleHinglish: 'The Map Is Not The Territory: Chart Aur Asliyat Ka Farq',
    subtitleHinglish: 'Alfred Korzybski ka model: Spreadsheet, dashboard aur rules sirf tasveer hain, zameen ki asliyat nahi.',
    shortDescHinglish: 'Epistemological Humility: Restaurant ka menu dekhne se pet nahi bharta; theory aur ground reality me zameen-aasmaan ka farq hota hai.',
    oneLineHinglish: 'Aap ghar ke naqshe (blueprint) par chal nahi sakte, aur menu card ko chaba kar bhookh nahi mit sakti.',
    summary30sHinglish: '1931 me philosopher Alfred Korzybski ne ek amar baat kahi: "Map kabhi bhi zameen (territory) nahi hota." Har spreadsheet, theory aur corporate rulebook sirf ek choti si tasveer hoti hai. Asli duniya bohot complex, ulti-pulti aur unpredictable hoti hai. Jab log Excel sheet ko hi sach maan lete hain, to bohot bade nuksan hote hain.',
    coreConceptHinglish: '2008 ke US Financial Crisis me Wall Street ke bade-bade math models keh rahe the ki "Zero risk hai". Models paper par perfect the, par asli zameen par poora banking system doob gaya. Isi tarah corporate offices me baithe log dashboards par green indicators dekh kar khush hote rehte hain, jabki zameen par customer gaaliyan de raha hota hai.',
    summary60sHinglish: 'Kerala me baarish ke time kuch tourists ne Google Maps par blind trust kiya. Map par seedhi road dikh rahi thi, par aage pul toot chuka tha aur gaadi seedhi nadi me gir gayi! Yeh Map-Territory fallacy ka sabse bada example hai: Hamesha apni aankho par aur ground reality par bharosa karo, sirf screen ke naqshe par nahi.',
    howItWorksHinglish: 'Idea aaya -> Paper par model banaya -> Model simple laga -> Model par blind trust kiya -> Asli duniya badal gayi -> Model crash ho gaya.',
    howToRespondHinglish: 'Gemba Walk karo: Sirf laptop screen mat dekho. Zameen par jao, dukan par baitho, actual customer se baat karo aur reality check lo.',
    takeawaysHinglish: [
      'Koi bhi model ya spreadsheet poori reality ko capture nahi kar sakti',
      'Menu aur khane me farq samjho; metrics real satisfaction nahi hote',
      'Jab computer data aur ground reality me ladai ho, to hamesha ground reality jeetti hai',
      'Apne cabin se bahar niklo aur zameen par jakar sach dekho'
    ],
    pqPromptHinglish: 'Hospital ke software me dikh raha hai ki patient wait time 40 minute se ghat kar 5 minute ho gaya, par patients ki death rate badh gayi. Aisa kyu hua?',
    pqExplanationHinglish: 'Staff ne software ka number theek karne ke liye patients ko bina dekhe bed par daal diya. Map (Software metric) accha ho gaya, par Territory (Asli treatment) kharab ho gaya.',
    pqOptionsHinglish: [
      { id: 'opt_a', text: 'Software me technical error aa gaya tha.', isCorrect: false, feedback: 'Galat. Problem human behavior ki thi.' },
      { id: 'opt_b', text: 'Staff ne computer metric (Map) ko sundar banane ke liye treatment (Territory) ko nazarandaz kar diya.', isCorrect: true, feedback: 'Sahi! Yahi Map-Territory fallacy aur Goodhart’s law hai.' },
      { id: 'opt_c', text: 'Patients ko jaldi theek hone ki aadat nahi thi.', isCorrect: false, feedback: 'Galat.' }
    ],
    hiTitle: 'मानचित्र भूभाग नहीं है (The Map Is Not The Territory)',
    hiSummary: 'सैद्धांतिक मॉडल, आंकड़ों और रूपरेखाओं को वास्तविक दुनिया की जटिल और अप्रत्याशित वास्तविकता समझने की भूल से बचने का सिद्धांत।',
    hiTakeaways: ['कोई भी मॉडल या स्प्रेडशीट वास्तविकता का केवल एक सरलीकृत रूप है', 'मेनू को भोजन समझने की भूल कभी न करें; जमीनी हकीकत हमेशा जीतती है', 'केवल कंप्यूटर स्क्रीन देखने के बजाय वास्तविक उपयोगकर्ताओं और परिस्थितियों का प्रत्यक्ष निरीक्षण करें'],
    guTitle: 'નકશો એ જમીન નથી (The Map Is Not The Territory)', guSummary: 'કાગળ પરના મોડલ્સ અને વાસ્તવિક જમીની હકીકત વચ્ચેનો ભેગ પારખવાનો બુદ્ધિગમ્ય સિદ્ધાંત.', guTakeaways: ['ડેશબોર્ડ પર આંધળો વિશ્વાસ ન કરો', 'મેનુ એ ભોજન નથી', 'જમીની હકીકત રૂબરૂ તપાસો'],
    mrTitle: 'नकाशा म्हणजे प्रत्यक्ष जमीन नव्हे (The Map Is Not The Territory)', mrSummary: 'कागदावरील मॉडेल्स आणि प्रत्यक्ष जमिनीवरील वास्तव यातील फरक ओळखण्याचे तत्त्वज्ञान.', mrTakeaways: ['फक्त संगणकावरील आकडेवारीवर अवलंबून राहू नका', 'मेन्यू म्हणजे जेवण नव्हे', 'प्रत्यक्ष जमिनीवर जाऊन सत्य तपासा'],
    teTitle: 'మ్యాప్ అసలైన భూభాగం కాదు (The Map Is Not The Territory)', teSummary: 'కాగితంపై లేదా కంప్యూటర్‌లోని నమూనాలు వాస్తవ ప్రపంచాన్ని పూర్తిగా ప్రతిబింబించలేవని గుర్తించే సిద్ధాంతం.', teTakeaways: ['కంప్యూటర్ డాష్‌బోర్డులను గుడ్డిగా నమ్మవద్దు', 'మెనూ అంటే భోజనం కాదు', 'క్షేత్రస్థాయి వాస్తవాలను పరిశీలించండి'],
    taTitle: 'வரைபடம் நிலப்பரப்பு அல்ல (The Map Is Not The Territory)', taSummary: 'காகிதத்தில் உள்ள வரைபடங்களும் கணினி மாதிரிகளும் நிஜ உலகத்தின் முழுமையான உண்மை அல்ல என்பதை உணர்த்தும் கோட்பாடு.', taTakeaways: ['கணினி எண்களை கண்மூடித்தனமாக நம்பாதீர்கள்', 'மெனு என்பது உணவு அல்ல', 'கள யதார்த்தத்தை நேரில் பாருங்கள்'],
    knTitle: 'ನಕ್ಷೆಯು ಭೂಭಾಗವಲ್ಲ (The Map Is Not The Territory)', knSummary: 'ಕಾಗದದ ಮೇಲಿನ ಮಾದರಿಗಳು ಮತ್ತು ನೈಜ ಜಗತ್ತಿನ ಕಠಿಣ ವಾಸ್ತವದ ನಡುವಿನ ವ್ಯತ್ಯಾಸವನ್ನು ಗುರುತಿಸುವ ಮಾನಸಿಕ ಮಾದರಿ.', knTakeaways: ['ಕಂಪ್ಯೂಟರ್ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್‌ಗಳನ್ನು ಕುರುಡಾಗಿ ನಂಬಬೇಡಿ', 'ಮೆನು ಎಂದರೆ ಊಟವಲ್ಲ', 'ಕ್ಷೇತ್ರ ಮಟ್ಟದ ಸತ್ಯಾಸತ್ಯತೆ ಪರೀಕ್ಷಿಸಿ'],
    mlTitle: 'ഭൂപടം യഥാർത്ഥ ഭൂമിയല്ല (The Map Is Not The Territory)', mlSummary: 'സിദ്ധാന്തങ്ങളും കമ്പ്യൂട്ടർ മോഡലുകളും യഥാർത്ഥ ലോകത്തിലെ യാഥാർത്ഥ്യത്തിന് പകരമാകില്ലെന്ന് ഓർമ്മിപ്പിക്കുന്ന തത്വം.', mlTakeaways: ['കമ്പ്യൂട്ടർ ഡാറ്റയെ അന്ധമായി വിശ്വസിക്കരുത്', 'മെനു ഭക്ഷണത്തിന് പകരമാകില്ല', 'യാഥാർത്ഥ്യം നേരിട്ട് കണ്ട് ബോധ്യപ്പെടുക'],
    bnTitle: 'মানচিত্র কখনো ভূখণ্ড নয় (The Map Is Not The Territory)', bnSummary: 'কাগজের মডেল বা স্প্রেডশিটের সরলীকৃত রূপকে বাস্তবের জটিল রূপ ভেবে ভুল না করার জ্ঞানতাত্ত্বিক নীতি।', bnTakeaways: ['কম্পিউটার ড্যাশবোর্ডে অন্ধ বিশ্বাস করবেন না', 'মেনু কখনো খাবার নয়', 'মাঠপর্যায়ের বাস্তবতাকে সর্বোচ্চ গুরুত্ব দিন'],
    paTitle: 'ਨਕਸ਼ਾ ਅਸਲ ਜ਼ਮੀਨ ਨਹੀਂ ਹੁੰਦਾ (The Map Is Not The Territory)', paSummary: 'ਕਾਗਜ਼ਾਂ ਜਾਂ ਸਕਰੀਨਾਂ ਉੱਤੇ ਬਣੇ ਮਾਡਲਾਂ ਨੂੰ ਜ਼ਮੀਨੀ ਹਕੀਕਤ ਸਮਝਣ ਦੀ ਗ਼ਲਤੀ ਤੋਂ ਬਚਣ ਦਾ ਸਿਧਾਂਤ।', paTakeaways: ['ਕੰਪਿਊਟਰ ਅੰਕੜਿਆਂ ਤੇ ਅੰਨ੍ਹਾ ਭਰੋਸਾ ਨਾ ਕਰੋ', 'ਮੈਨੂ ਅਸਲ ਖਾਣਾ ਨਹੀਂ ਹੁੰਦਾ', 'ਜ਼ਮੀਨੀ ਹਕੀਕਤ ਖ਼ੁਦ ਜਾ ਕੇ ਪਰਖੋ'],
    urTitle: 'نقشہ اصل زمین نہیں ہوتا (The Map Is Not The Territory)', urSummary: 'کاغذ پر بنے ماڈلز یا کمپیوٹر ڈیٹا کو زمینی حقیقت سمجھنے کی فکری غلطی سے بچنے کا اصول۔', urTakeaways: ['کمپیوٹر ڈیش بورڈ پر اندھا بھروسہ نہ کریں', 'مینو اصل کھانا نہیں ہوتا', 'زمینی حقائق کا خود مشاہدہ کریں'],
    orTitle: 'ମାନଚିତ୍ର ପ୍ରକୃତ ଭୂଭାଗ ନୁହେଁ (The Map Is Not The Territory)', orSummary: 'କାଗଜର ମଡେଲ ବା ଡାଟାକୁ ପ୍ରକୃତ ଜଟିଳ ବାସ୍ତବତା ଭାବି ଭୁଲ୍ ନକରିବାର ବୈଜ୍ଞାନିକ ସତର୍କତା।', orTakeaways: ['କମ୍ପ୍ୟୁଟର ଡ୍ୟାସବୋର୍ଡ଼ ଉପରେ ଅନ୍ଧବିଶ୍ୱାସ କରନ୍ତୁ ନାହିଁ', 'ମେନୁ କେବେ ଖାଦ୍ୟ ନୁହେଁ', 'କ୍ଷେତ୍ରସ୍ତରୀୟ ବାସ୍ତବତା ପରଖନ୍ତୁ'],
    asTitle: 'মানচিত্ৰ প্ৰকৃত ভূমিখণ্ড নহয় (The Map Is Not The Territory)', asSummary: 'কাগজৰ আৰ্হি বা কম্পিউটাৰৰ তথ্যক বাস্তৱ পৃথিৱীৰ জটিল সত্য বুলি ভুল নকৰাৰ জ্ঞানমূলক নীতি।', asTakeaways: ['কম্পিউটাৰৰ তথ্যত অন্ধবিশ্বাস নকৰিব', 'মেনু কেতিয়াও প্ৰকৃত খাদ্য নহয়', 'ক্ষেত্ৰভিত্তিক বাস্তৱতাক অগ্ৰাধিকাৰ দিয়ক']
  },

  {
    fileName: 'chestertonsFence.ts',
    varName: 'chestertons_fence',
    id: 'chestertons_fence',
    categoryId: 'critical_thinking',
    slug: 'chestertons-fence',
    difficulty: 'intermediate',
    readTime: 5,
    sortWeight: 9,
    titleEn: 'Chesterton’s Fence: Why Reforms Destroy Working Systems',
    subtitleEn: 'G.K. Chesterton’s principle on why you must never tear down a fence until you know why it was put up.',
    shortDescEn: 'A decision-making principle stating that reforms, deletions, or policy removals should not be executed until the underlying reason for the existing state of affairs is fully understood.',
    oneLineEn: 'Do not remove a barrier until you know what dangerous beast it was built to keep out.',
    summary30sEn: 'Articulated in 1929 by British writer G.K. Chesterton in *The Thing*, this mental model targets arrogant reformers and ambitious junior leaders. Chesterton envisioned a fence erected across a country road. A modern reformer says: "I see no use for this fence; let us tear it down!" A wise thinker replies: "If you do not see its use, I certainly will not let you tear it down. Go find out why it was built, and only then may you remove it."',
    coreConceptEn: 'Complex institutions, traditions, biological adaptations, and software architectures rarely evolve by random accident. They exist because they solved a painful, forgotten historical crisis. When newcomers enter an organization, their immediate instinct is to view existing complexities as archaic stupidity. Tearing down the "useless" fence invariably releases the hidden monster it was built to contain.',
    summary60sEn: 'In software development, this manifests when a new developer deletes an ugly, convoluted 50-line `if/else` block, thinking "this is sloppy legacy code". Within 2 hours of deployment, production crashes because that messy block was handling an obscure bug in a legacy bank payment gateway. Respect systemic evolution before refactoring.',
    takeawaysEn: [
      'Never remove a rule, habit, or code block until you discover why it was created',
      'Things that appear useless to a newcomer often solve an invisible historical problem',
      'Reforms carried out in ignorance invariably resurrect the ancient crisis',
      'Humility in the face of existing complex systems is the hallmark of great leadership'
    ],
    whyItHappensEn: 'Presentism and naive interventionism: the tendency to assume past actors were less intelligent than ourselves because we lack their historical context.',
    evolutionaryEn: 'Cultural taboos (e.g. food preparation rituals, marriage kinship rules) preserved tribal survival across generations without explicit scientific theories.',
    howItWorksEn: 'Newcomer observes legacy barrier -> Concludes it is irrational -> Destroys barrier without investigation -> Latent crisis unleashes -> Catastrophic failure -> Rebuilding at 10x cost.',
    visualHeadlineEn: 'Arrogant Deletion vs. Chesterton’s Historic Audit',
    visualDescEn: 'G.K. Chesterton’s systemic barrier preservation model.',
    sideALabelEn: 'Arrogant Reformer (Naive)',
    sideADetailEn: '"Why does our database have this weird cache invalidation script? It looks redundant; deleting it!" -> Server outages hit 500k users.',
    sideBLabelEn: 'Chesterton’s Thinker (Wise)',
    sideBDetailEn: '"Let\'s read git blame and commit logs from 2021 to understand what specific race condition this script was written to prevent."' ,
    researchSummaryEn: 'Chesterton (1929, The Thing: Why I Am a Catholic) and Taleb (2012, Antifragile: Things That Gain from Disorder - The Lindy Effect) documented how unconsidered removals destroy evolved institutional antifragility.',
    refAuthor: 'Chesterton, G. K. & Taleb, N. N.',
    refYear: 1929,
    refTitle: 'The Thing: Why I Am a Catholic / Antifragile',
    refCitation: 'Chesterton, G. K. (1929). Sheed & Ward.',
    refDoi: 'https://doi.org/10.1002/9781118536858',
    scenarioTitleEn: 'The Deleted Safety Protocol in Pune',
    scenarioContextEn: 'A newly appointed operations manager at an auto-parts manufacturing plant in Pune noticed that workers were required to wait 90 seconds after pressing an emergency shutdown button before opening machine panels. Calling it "a waste of productivity," he abolished the rule. Two weeks later, a technician opened a panel prematurely and suffered severe thermal burns from unvented pressurized steam.',
    scenarioBiasEn: 'The manager saw the fence (the 90-second wait) but failed to investigate the beast it kept out (hydraulic steam depressurization).',
    scenarioOptimalEn: 'Before modifying any SOP or safety regulation, interview veteran staff and examine incident logs to understand the blood that wrote the original rule.',
    scenarioReflectionEn: 'What daily habit or boundary do you feel tempted to drop right now without remembering why you set it up in the first place?',
    howToRecognizeEn: 'Looking at an old company policy, code repository, or cultural tradition and thinking: "These people were so stupid; this serves no purpose."',
    whereEn: 'Software engineering refactoring, corporate restructuring, constitutional law amendments, and personal lifestyle boundary changes.',
    misconceptionsEn: 'Myth: "Chesterton’s Fence is a conservative excuse to never change anything." Fact: Chesterton explicitly allowed removing the fence—ONCE you have proven you understand its exact original purpose and have an alternative defense.',
    limitationsEn: 'When a barrier was built for an environment that objectively no longer exists (e.g. keeping buggy whips in an electric car era), removal is fully justified after validation.',
    howToRespondEn: 'The Archaeological Inquiry: Whenever you want to delete a feature or rule, write a 1-paragraph summary explaining the problem it originally solved before executing the deletion.',
    defensesEn: [
      { title: 'The Git Blame Protocol', instruction: 'Never delete code without running `git blame` and reading the original developer\'s pull request comments.' },
      { title: 'The Veteran Interview', instruction: 'Speak to the longest-tenured employee or architect to understand what disaster triggered the creation of the policy.' }
    ],
    pqPromptEn: 'A new junior software engineer finds a 40-line chunk of convoluted code marked "DO NOT TOUCH". It appears to do nothing in their local environment. What is the correct Chestertonian approach?',
    pqScenarioEn: 'The engineer wants to clean up the codebase to improve readability scores on GitHub.',
    pqExplanationEn: 'Chesterton’s Fence demands discovering why the code was written (checking commit history, tests, and speaking to the author) before deleting it.',
    pqAntidoteEn: 'Investigate the history before touching the fence.',
    pqOptionsEn: [
      { id: 'opt_a', text: 'Delete the code immediately because clean code is the top priority.', isCorrect: false, feedback: 'Incorrect. This creates high-risk production bugs.' },
      { id: 'opt_b', text: 'Investigate commit history, Jira tickets, and consult senior architects to understand what edge case it protects before considering removal.', isCorrect: true, feedback: 'Correct! This embodies Chesterton’s Fence in modern engineering.' },
      { id: 'opt_c', text: 'Rewrite the entire codebase in a new programming language over the weekend.', isCorrect: false, feedback: 'Incorrect. Reckless arrogance.' }
    ],
    reflectionPromptEn: 'What is an annoying rule at your job or in your family that you now realize might be protecting everyone from a hidden disaster?',
    titleHinglish: 'Chesterton’s Fence: Purane Niyamo Ko Todne Ki Jaldbazi Mat Karo',
    subtitleHinglish: 'G.K. Chesterton ka principle: Jab tak yeh na pata chal jaye ki deewar kyu banayi gayi thi, tab tak use girane ka haq kisi ko nahi hai.',
    shortDescHinglish: 'Unintended Consequences of Reform: Naye log purani cheezon ko bekaar samajh kar hata dete hain aur fir bada nuksan uthate hain.',
    oneLineHinglish: 'Pehle yeh pata lagao ki baadh (fence) kyu lagayi gayi thi, fir decide karo ki use todna hai ya nahi.',
    summary30sHinglish: '1929 me writer G.K. Chesterton ne ek misaal di: Do log raste par chal rahe the aur beech me ek lakdi ki fence (baadh) lagi thi. Pehla bola: "Mujhe iska koi use nahi dikh raha, ise tod dete hain!" Doosra bola: "Agar tumhe iska use nahi pata, to main tumhe ise chhoone bhi nahi dunga. Pehle pata karo yeh kyu lagayi gayi thi, fir todne ki baat karna."',
    coreConceptHinglish: 'Office me ya coding me naye log aate hi kehte hain: "Purane log kitne pagal the, yeh faltu rule kyu banaya!" Fir wo us rule ya code ko delete kar dete hain, aur agle hi din production phat jata hai! Kyuki wo "faltu" rule darasal kisi purane bade haadse ya bug se bachne ke liye banaya gaya tha.',
    summary60sHinglish: 'Factory me ek naye manager ne dekha ki machine band karne ke baad 2 minute rukne ka rule tha. Usne kaha "Time waste hai, rule hata do!" Agle hafte ek worker ne machine kholi aur andar ki garam steam se uska hath jal gaya. Purane niyam bekaar nahi hote, unke peeche dardnaak galtiyon ka itihas hota hai.',
    howItWorksHinglish: 'Naya insaan aaya -> Purana rule bekaar laga -> Bina soche delete kiya -> Purani museebat wapas aa gayi -> 10 guna bada nuksan hua.',
    howToRespondHinglish: 'Itihas check karo: Kisi bhi purane rule ya code ko hatane se pehle purane seniors se poochho ya documentation padho: "Yeh rule kyu bana tha?" Jab samajh aa jaye, tabhi change karo.',
    takeawaysHinglish: [
      'Jab tak kisi rule ka purpose na pata chale, use badalne ki koshish mat karo',
      'Purane log bewakoof nahi the; unhone kisi bade haadse ke baad hi wo deewar khadi ki thi',
      'Jaldbazi me reforms karne se purana daanav wapas bahar nikal aata hai',
      'Asli samajhdaari purani cheezon ke peeche ke karan ko samajhne me hai'
    ],
    pqPromptHinglish: 'Ek naye coder ne dekha ki code me ek ajeeb sa 20-line ka block hai. Use lagta hai yeh bekaar hai. Chesterton’s Fence ke hisaab se use kya karna chahiye?',
    pqExplanationHinglish: 'Pehle git commit history aur tickets check karne chahiye taaki pata chale yeh code kis bug ko rokne ke liye likha gaya tha.',
    pqOptionsHinglish: [
      { id: 'opt_a', text: 'Turant delete karke weekend par chutti par chale jana.', isCorrect: false, feedback: 'Galat. Production crash hone ka risk hai.' },
      { id: 'opt_b', text: 'Git history aur seniors se pata karna ki yeh code kis bug ya edge case ko handle karne ke liye banaya gaya tha.', isCorrect: true, feedback: 'Sahi! Yahi Chesterton’s Fence ka practical software application hai.' },
      { id: 'opt_c', text: 'Code ko copy karke social media par mazak udana.', isCorrect: false, feedback: 'Galat.' }
    ],
    hiTitle: 'चेस्टरटन की बाड़ (Chesterton’s Fence)',
    hiSummary: 'किसी भी स्थापित नियम, परंपरा या संरचना को तब तक न हटाने का सिद्धांत, जब तक कि उसके निर्माण के मूल कारण और उद्देश्य को पूरी तरह न समझ लिया जाए।',
    hiTakeaways: ['किसी नियम को हटाने से पहले यह जानें कि उसे क्यों बनाया गया था', 'अनुभवहीन सुधारक अक्सर पुरानी व्यवस्थाओं को मूर्खतापूर्ण मानकर बड़ी तबाही लाते हैं', 'जटिल प्रणालियों के विकासवादी इतिहास का सम्मान करें'],
    guTitle: 'ચેસ્ટરટનની વાડ (Chesterton’s Fence)', guSummary: 'જ્યાં સુધી જૂનો નિયમ કે પરંપરા શા માટે બનાવવામાં આવી હતી તે ન સમજાય, ત્યાં સુધી તેને દૂર ન કરવાનો સિદ્ધાંત.', guTakeaways: ['જૂના નિયમો પાછળનું કારણ શોધો', 'ઉતાવળે ફેરફાર કરવાનું ટાળો', 'સિસ્ટમના ઇતિહાસનો આદર કરો'],
    mrTitle: 'चेस्टरटनचे कुंपण (Chesterton’s Fence)', mrSummary: 'एखादा जुना नियम किंवा कुंपण कशासाठी तयार केले होते हे समजल्याशिवाय ते नष्ट करू नये ही विवेकपूर्ण विचारसरणी.', mrTakeaways: ['नियम हटवण्यापूर्वी त्याचे कारण शोधा', 'सुधारणांच्या घाईत नुकसान टाळा', 'अनुभवातून शिकलेल्या गोष्टींचा आदर करा'],
    teTitle: 'చెస్టర్‌టన్ కంచె (Chesterton’s Fence)', teSummary: 'ఒక నియమం లేదా కంచె ఎందుకు ఏర్పాటు చేయబడిందో తెలుసుకోకుండా దానిని తొలగించకూడదనే వివేకవంతమైన సూత్రం.', teTakeaways: ['నియమాల వెనుక ఉన్న కారణాన్ని తెలుసుకోండి', 'తొందరపడి మార్పులు చేయవద్దు', 'వ్యవస్థ చరిత్రను గౌరవించండి'],
    taTitle: 'செஸ்டர்டனின் வேலி (Chesterton’s Fence)', taSummary: 'ஒரு பழைய விதி அல்லது வேலி எதற்காக அமைக்கப்பட்டது என்பதை புரிந்து கொள்ளாமல் அதை அகற்றக்கூடாது என்ற விவேகமான கொள்கை.', taTakeaways: ['விதிகளின் பின்னணியை அறிந்து கொள்ளுங்கள்', 'அவசர சீர்திருத்தங்களை தவிருங்கள்', 'அனுபவத்தின் உண்மையை மதியுங்கள்'],
    knTitle: 'ಚೆಸ್ಟರ್‌ಟನ್ ಬೇಲಿ (Chesterton’s Fence)', knSummary: 'ಒಂದು ಹಳೆಯ ನಿಯಮ ಅಥವಾ ಬೇಲಿಯನ್ನು ಏಕೆ ನಿರ್ಮಿಸಲಾಯಿತು ಎಂದು ತಿಳಿಯುವವರೆಗೆ ಅದನ್ನು ತೆಗೆದುಹಾಕಬಾರದು ಎಂಬ ವಿವೇಕಯುತ ತತ್ವ.', knTakeaways: ['ನಿಯಮಗಳ ಹಿಂದಿನ ಉದ್ದೇಶ ತಿಳಿಯಿರಿ', 'ಅತಿಯಾದ ಆತುರದಿಂದ ಬದಲಾವಣೆ ಮಾಡಬೇಡಿ', 'ಹಳೆಯ ವ್ಯವಸ್ಥೆಗಳ ಇತಿಹಾಸವನ್ನು ಗೌರವಿಸಿ'],
    mlTitle: 'ചെസ്റ്റർട്ടന്റെ വേലി (Chesterton’s Fence)', mlSummary: 'ഒരു പഴയ നിയമമോ വേലിയോ എന്തിനാണ് ഉണ്ടാക്കിയതെന്ന് മനസ്സിലാക്കാതെ അത് മാറ്റരുതെന്ന വിവേകപൂർണ്ണമായ തത്വം.', mlTakeaways: ['നിയമങ്ങൾക്ക് പിന്നിലെ കാരണം കണ്ടെത്തുക', 'ധൃതിപിടിച്ചുള്ള മാറ്റങ്ങൾ ഒഴിവാക്കുക', 'പഴയ അനുഭവങ്ങളെ ബഹുമാനിക്കുക'],
    bnTitle: 'চেস্টারটনের বেড়া (Chesterton’s Fence)', bnSummary: 'একটি পুরোনো নিয়ম বা প্রতিবন্ধকতা কেন তৈরি করা হয়েছিল তা না জেনে তা ভেঙে ফেলা অনুচিত—এই বিষয়ক সংস্কারমূলক সতর্কতা।', bnTakeaways: ['নিয়ম ভাঙার আগে তার পেছনের কারণ জানুন', 'সংস্কারের অন্ধ আবেগে ভুল করবেন না', 'বিবর্তিত ব্যবস্থার ইতিহাসকে শ্রদ্ধা করুন'],
    paTitle: 'ਚੈਸਟਰਟਨ ਦਾ ਵਾੜਾ (Chesterton’s Fence)', paSummary: 'ਜਦੋਂ ਤੱਕ ਇਹ ਪਤਾ ਨਾ ਲੱਗੇ ਕਿ ਪੁਰਾਣਾ ਨਿਯਮ ਜਾਂ ਵਾੜ ਕਿਉਂ ਲਗਾਈ ਗਈ ਸੀ, ਉਦੋਂ ਤੱਕ ਉਸਨੂੰ ਨਾ ਹਟਾਉਣ ਦਾ ਸਿਆਣਾ ਸਿਧਾਂਤ।', paTakeaways: ['ਨਿਯਮ ਹਟਾਉਣ ਤੋਂ ਪਹਿਲਾਂ ਕਾਰਨ ਲੱਭੋ', 'ਬਦਲਾਅ ਦੀ ਕਾਹਲ ਤੋਂ ਬਚੋ', 'ਪੁਰਾਣੇ ਤਜਰਬੇ ਦਾ ਸਤਿਕਾਰ ਕਰੋ'],
    urTitle: 'چیسٹرٹن کی باڑ (Chesterton’s Fence)', urSummary: 'جب تک یہ معلوم نہ ہو جائے کہ کوئی پرانا قانون یا باڑ کیوں بنائی گئی تھی، تب تک اسے ہٹانا غیر دانشمندانہ ہے۔', urTakeaways: ['اصولوں کے پس منظر کو سمجھیں', 'جلدی میں تبدیلیاں کرنے سے گریز کریں', 'پرانے تجربات اور تاریخ کا احترام کریں'],
    orTitle: 'ଚେଷ୍ଟରଟନଙ୍କ ବାଡ଼ (Chesterton’s Fence)', orSummary: 'କୌଣସି ପୁରୁଣା ନିୟମ ବା ବାଡ଼ କାହିଁକି ତିଆରି ହୋଇଥିଲା ତାହା ନଜାଣି ତାହାକୁ ନଭାଙ୍ଗିବାର ବିଜ୍ଞତାପୂର୍ଣ୍ଣ ନୀତି।', orTakeaways: ['ନିୟମ ପଛର କାରଣ ଖୋଜନ୍ତୁ', 'ବଦଳାଇବାରେ ତରବର ହୁଅନ୍ତୁ ନାହିଁ', 'ପୁରୁଣା ଅନୁଭବକୁ ସମ୍ମାନ ଦିଅନ୍ତୁ'],
    asTitle: 'চেষ্টাৰটনৰ বেৰা (Chesterton’s Fence)', asSummary: 'এটা পুৰণি নিয়ম বা বেৰা কিয় নিৰ্মাণ কৰা হৈছিল সেয়া নজনাকৈ তাক আঁতৰাই পেলোৱা অনুচিত—এই সম্পৰ্কীয় সতৰ্কতামূলক নীতি।', asTakeaways: ['নিয়ম ভঙাৰ পূৰ্বে কাৰণ বিচাৰক', 'সংস্কাৰৰ নামত খৰখেদা নকৰিব', 'পুৰণি অভিজ্ঞতা আৰু ইতিহাসক শ্ৰদ্ধা কৰক']
  }
];

