import { ComprehensiveTopicDef } from '../topicGeneratorHelper';

export const EMOTIONS_TOPICS: ComprehensiveTopicDef[] = [
  {
    fileName: 'amygdalaHijack.ts',
    varName: 'amygdala_hijack',
    id: 'amygdala_hijack',
    categoryId: 'emotions',
    slug: 'amygdala-hijack',
    difficulty: 'intermediate',
    readTime: 5,
    sortWeight: 5,
    titleEn: 'Amygdala Hijack: The Neural Surge That Overrides Reason',
    subtitleEn: 'When the primitive threat center triggers fight-or-flight before the rational prefrontal cortex can process facts.',
    shortDescEn: 'A sudden, overwhelming emotional explosion triggered when the amygdala bypasses the prefrontal cortex, perceiving a social threat as physical danger.',
    oneLineEn: 'The brain reacting with survival aggression before logical thought even begins.',
    summary30sEn: 'Coined by Daniel Goleman based on Joseph LeDoux’s neuroscience research, an amygdala hijack happens when sensory input bypasses the neocortex, flooding your body with adrenaline in milliseconds before your logical mind can intervene.',
    coreConceptEn: 'Sensory signals split at the thalamus: a high road leads to the rational prefrontal cortex, while a low, emergency road goes straight to the amygdala. In high-stress conflicts, the amygdala triggers a neurochemical storm before the rational mind can formulate words.',
    summary60sEn: 'When someone insults or criticizes you, your primitive amygdala cannot distinguish between a physical tiger and a social attack. It triggers cortisol and adrenaline release, hijacking working memory and disabling logical reflection. The biological reaction takes roughly 6 seconds to subside if you do not add fuel through defensive self-talk.',
    takeawaysEn: [
      'The subcortical pathway reacts in milliseconds, far faster than the rational neocortex',
      'Blood flow shifts away from the prefrontal cortex, causing temporary logical blindness',
      'A conscious 6-second pause gives the prefrontal cortex time to regain executive control',
      'Physical markers like heart pounding and shallow breathing precede verbal explosions'
    ],
    whyItHappensEn: 'Evolutionary survival prioritized speed over accuracy: reacting to a false alarm is harmless, but hesitating in front of a predator is fatal.',
    evolutionaryEn: 'Early humans faced lethal predators; immediate neurochemical readiness was essential for clan survival.',
    howItWorksEn: 'Social stimulus perceived as threat -> Thalamus routes signal directly to amygdala -> Adrenaline surge disables working memory -> Prefrontal cortex goes offline -> Regrettable outburst occurs.',
    visualHeadlineEn: 'The Fast Low Road vs. The Deliberate High Road',
    visualDescEn: 'How emergency subcortical wiring bypasses rational cortical processing.',
    sideALabelEn: 'Rational High Road (Prefrontal Cortex)',
    sideADetailEn: 'Takes 250–500ms to analyze context, understand nuance, and choose an assertive response.',
    sideBLabelEn: 'Amygdala Low Road (Survival Hijack)',
    sideBDetailEn: 'Fires in 12–20ms, dumping adrenaline and screaming fight-or-flight before you can think.',
    researchSummaryEn: 'LeDoux (1996, The Emotional Brain) and Goleman (1995) documented the anatomical short-circuit between the sensory thalamus and the amygdala, proving that emotional response can precede cognitive evaluation.',
    refAuthor: 'Goleman, D. & LeDoux, J. E.',
    refYear: 1995,
    refTitle: 'Emotional Intelligence and the Emotional Brain',
    refCitation: 'Goleman, D. (1995). Emotional Intelligence. Bantam Books.',
    refDoi: 'https://doi.org/10.1037/0003-066X.51.10.1069',
    scenarioTitleEn: 'The Startup Pitch Outburst in Gurgaon',
    scenarioContextEn: 'During a crucial funding pitch in Cyber City Gurgaon, an investor casually remarked that Rohan\'s financial model was "childish". Rohan felt a flash of intense heat in his face and immediately snapped, shouting that the investor didn\'t understand modern tech.',
    scenarioBiasEn: 'Rohan experienced an acute amygdala hijack: the investor\'s critique felt like an identity-level threat, disabling his composure.',
    scenarioOptimalEn: 'Take a deliberate 6-second sip of water to allow the prefrontal cortex to come back online, then respond calmly: "Let me walk you through the unit economics that justify that estimate."',
    scenarioReflectionEn: 'When was the last time you felt sudden physical heat or heart pounding during an argument before speaking words you regretted?',
    howToRecognizeEn: 'Sudden surge of bodily heat, clenched jaw, racing heartbeat, and an irresistible urge to interrupt or shout.',
    whereEn: 'High-stakes negotiations, family arguments, performance reviews, and heated online comments.',
    misconceptionsEn: 'Myth: Emotional intelligence means never feeling anger. Reality: High EQ people feel the exact same adrenaline surge, but have trained the ability to insert a pause before reacting.',
    limitationsEn: 'In physical emergencies (fire, physical assault), the amygdala hijack is life-saving and should not be suppressed.',
    howToRespondEn: 'Implement the 6-Second Circuit Breaker: breathe in for 4 seconds, exhale for 4, drink water, and label the emotion internally ("I am feeling threatened right now").',
    defensesEn: [
      { title: 'The 6-Second Biological Buffer', instruction: 'Never speak for the first 6 seconds after hearing triggering criticism; sip water or take a deep belly breath.' },
      { title: 'Name It to Tame It', instruction: 'Silently say: "My amygdala is firing an alarm bell." Linguistic labeling activates the left prefrontal cortex.' }
    ],
    pqPromptEn: 'A colleague loudly questions your integrity in front of the entire department. What is the scientifically optimal immediate reaction?',
    pqScenarioEn: 'Your heart is racing at 130 bpm and you feel a wave of intense anger rushing through your chest.',
    pqExplanationEn: 'During an amygdala hijack, your logical reasoning is biologically impaired. Forcing a physical pause and conscious breath lets the prefrontal cortex regain control.',
    pqAntidoteEn: 'Pause for 6 seconds, acknowledge the surge, and delay verbal response until pulse stabilizes.',
    pqOptionsEn: [
      { id: 'opt_a', text: 'Instantly shout back with equal aggression to maintain status and assert dominance.', isCorrect: false, feedback: 'Incorrect. This fuels the hijack and damages professional credibility.' },
      { id: 'opt_b', text: 'Pause, take a slow 4-second breath, sip water, and respond with a neutral fact-based question.', isCorrect: true, feedback: 'Correct! The pause allows prefrontal cortex re-engagement.' },
      { id: 'opt_c', text: 'Walk out of the room slamming the door to show complete disgust.', isCorrect: false, feedback: 'Incorrect. This is an emotional surrender to the hijack.' }
    ],
    reflectionPromptEn: 'Can you identify the specific physical bodily cue (jaw clench, stomach flutter, throat tight) that signals your amygdala is activating?',
    titleHinglish: 'Amygdala Hijack: Jab Gussa Dimaag Ke Logic Ko Band Kar Deta Hai',
    subtitleHinglish: 'Kyu achanak choti si baat par insaan bina soche samjhe chilla padta hai aur baad me regret karta hai.',
    shortDescHinglish: 'Ek achanak hone wala emotional explosion jisme dimaag ka threat center logic ko bypass kar deta hai.',
    oneLineHinglish: 'Dimaag ka logic chhodkar purani animal survival instinct par chale jana.',
    summary30sHinglish: 'Daniel Goleman ne samjhaya ki dimaag ka emergency alarm (amygdala) prefrontal cortex se pehle trigger hota hai. Choti si criticism par dimaag adrenaline release kar deta hai, jisse logic temporary tor par band ho jata hai.',
    coreConceptHinglish: 'Hamare dimaag me do raste hote hain: lamba rasta jo soch-samajh kar faisla leta hai, aur chota emergency rasta jo direct amygdala se judta hai. Gusse me emergency rasta jeet jata hai.',
    summary60sHinglish: 'Jab koi aapki beizzati karta hai, to dimaag use physical attack samajhta hai. Dil ki dhadkan badh jati hai aur prefrontal cortex offline chala jata hai. Is biological storm ko shant hone me lagbhag 6 second lagte hain.',
    howItWorksHinglish: 'Trigger milte hi amygdala adrenaline pump karta hai -> Bood flow dimaag ke logic part se muscle ki taraf chala jata hai -> Muh se bina soche baatein nikal jati hain -> Baad me guilt hota hai.',
    howToRespondHinglish: '6-Second Rule apnayein: Kuch bhi bolne se pehle 6 second ka pause lein, paani piyein aur lambi saans lein.',
    takeawaysHinglish: [
      'Gusse me logic isliye band hota hai kyuki dimaag survival mode me chala jata hai',
      'React karne se pehle 6 second ka pause biological circuit breaker ka kaam karta hai',
      'Physical signals jaise garam chehra ya tezi se dhadakta dil hijack ki pehli warning hain',
      'Apne emotion ko silently naam dein: "Mujhe gussa aa raha hai" kehne se prefrontal cortex active hota hai'
    ],
    pqPromptHinglish: 'Office meeting me kisi ne aapke kaam par public me galat ilzam lagaya. Sabse scientific reaction kya hoga?',
    pqExplanationHinglish: 'Pehle 6 second me aapka prefrontal cortex offline hota hai. Pause lene se hi aap sensible answer de sakte hain.',
    pqOptionsHinglish: [
      { id: 'opt_a', text: 'Turant uth kar samne wale par chilana taaki log kamzor na samjhein.', isCorrect: false, feedback: 'Galat. Yeh amygdala hijack ka victim banna hai.' },
      { id: 'opt_b', text: '6 second ka pause lein, paani piyein, aur shanti se facts ke sath sawal puchein.', isCorrect: true, feedback: 'Sahi! Yeh logic ko wapas lane ka scientific tareeqa hai.' },
      { id: 'opt_c', text: 'Meeting chhod kar bahar nikal jana aur gusse me resignation likhna.', isCorrect: false, feedback: 'Galat. Yeh impulsivity hai.' }
    ],
    hiTitle: 'अमिग्डाला अपहरण (Amygdala Hijack)',
    hiSummary: 'जब मस्तिष्क का भावुक केंद्र तार्किक प्रीफ्रंटल कॉर्टेक्स को बाईपास करके तात्कालिक क्रोध या भय की प्रतिक्रिया शुरू कर देता है।',
    hiTakeaways: ['भावनाएं तर्क से पहले सक्रिय होती हैं', '६ सेकंड का विराम तर्क को पुनः सक्रिय करता है', 'सहानुभूतिपूर्ण तंत्रिका तंत्र तात्कालिक प्रतिक्रिया देता है'],
    guTitle: 'એમિગ્ડાલા હાઇજેક (આવેગિક પ્રતિક્રિયા)', guSummary: 'જ્યારે તીવ્ર ક્રોધ વિચારશક્તિ પર હાવી થઈને અવિચારી નિર્ણય લેવડાવે છે.', guTakeaways: ['આવેગ પર કાબૂ રાખો', '૬ સેકન્ડનો વિરામ લો', 'શાંતિથી વિચાર કરો'],
    mrTitle: 'अमिग्डाला हायजॅक (आवेगाचा स्फोट)', mrSummary: 'तार्किक विचारांआधी मेंदूच्या भावनिक केंद्राकडून तात्काळ आक्रमक प्रतिक्रिया उमटणे.', mrTakeaways: ['आवेगावर नियंत्रण ठेवा', '६ सेकंदांचा विराम घ्या', 'तर्कशुद्ध विचार करा'],
    teTitle: 'అమిగ్డాలా హైజాక్ (ఆవేశపు స్పందన)', teSummary: 'మెదడులోని భావోద్వేగ కేంద్రం విచక్షణా జ్ఞానాన్ని నిలిపివేసి ఆవేశంతో స్పందించే స్థితి.', teTakeaways: ['ఆవేశాన్ని అదుపులో ఉంచండి', 'క్షణికావేశాన్ని ఆపండి', 'శాంతంగా ఆలోచించండి'],
    taTitle: 'அமிக்டாலா கடத்தல் (உணர்ச்சி வெடிப்பு)', taSummary: 'மூளையின் தர்க்கரீதியான சிந்தனையை முடக்கி உடனடி கோபத்தை உருவாக்கும் நரம்பியல் செயல்முறை.', taTakeaways: ['உணர்ச்சியை கட்டுப்படுத்துங்கள்', 'ஆறு நொடிகள் தாமதிக்கவும்', 'அமைதியாக சிந்தியுங்கள்'],
    knTitle: 'ಅಮಿಗ್ಡಾಲಾ ಹೈಜಾಕ್ (ಭಾವೋದ್ರೇಕದ ಸೆಳೆತ)', knSummary: 'ತರ್ಕಬದ್ಧ ಚಿಂತನೆಗೆ ಮುನ್ನವೇ ಮೆದುಳಿನ ಭಾವನಾತ್ಮಕ ಕೇಂದ್ರವು ತಕ್ಷಣದ ಪ್ರತಿಕ್ರಿಯೆಯನ್ನು ಪ್ರಚೋದಿಸುವ ಸ್ಥಿತಿ.', knTakeaways: ['ಭಾವೋದ್ರೇಕವನ್ನು ನಿಯಂತ್ರಿಸಿ', 'ಶಾಂತರಾಗಿ ನಿರ್ಧರಿಸಿ', 'ತರ್ಕಕ್ಕೆ ಆದ್ಯತೆ ನೀಡಿ'],
    mlTitle: 'അമിഗ്ഡല ഹൈജാക്ക് (വൈകാരിക തരംഗം)', mlSummary: 'യുക്തിസഹമായ ചിന്തയെ മറികടന്ന് മസ്തിഷ്കം പെട്ടെന്നുള്ള വൈകാരിക പ്രതികരണം നൽകുന്ന അവസ്ഥ.', mlTakeaways: ['വികാരങ്ങളെ നിയന്ത്രിക്കുക', 'ആറ് സെക്കൻഡ് നിശബ്ദത പാലിക്കുക', 'ശാന്തമായി പ്രതികരിക്കുക'],
    bnTitle: 'অ্যামিগডালা হাইজ্যাক (আবেগীয় বিস্ফোরণ)', bnSummary: 'মস্তিষ্কের যৌক্তিক অংশ কাজ করার আগেই তাত্ক্ষণিক রাগ বা ভয়ের অপ্রতিরোধ্য বহিঃপ্রকাশ।', bnTakeaways: ['আবেগ নিয়ন্ত্রণ করুন', 'ছয় সেকেন্ডের বিরতি নিন', 'শান্তভাবে সিদ্ধান্ত নিন'],
    paTitle: 'ਐਮਿਗਡਾਲਾ ਹਾਈਜੈਕ (ਗੁੱਸੇ ਦਾ ਉਛਾਲ)', paSummary: 'ਜਦੋਂ ਤਰਕ ਤੋਂ ਪਹਿਲਾਂ ਦਿਮਾਗ ਦਾ ਭਾਵਨਾਤਮਕ ਕੇਂਦਰ ਬੇਕਾਬੂ ਪ੍ਰਤੀਕਿਰਿਆ ਸ਼ੁਰੂ ਕਰ ਦਿੰਦਾ ਹੈ।', paTakeaways: ['ਗੁੱਸੇ ਤੇ ਕਾਬੂ ਰੱਖੋ', 'ਕੁਝ ਪਲ ਰੁਕ ਕੇ ਸੋਚੋ', 'ਸ਼ਾਂਤਮਈ ਹੱਲ ਲੱਭੋ'],
    urTitle: 'امیگڈالا ہائی جیک (جذباتی طوفان)', urSummary: 'جب دماغ کا جذباتی مرکز عقل و شعور کو معطل کر کے فوری اور بے قابو ردعمل پیدا کرتا ہے۔', urTakeaways: ['جذبات پر قابو پائیں', 'چھ سیکنڈ کا وقفہ لیں', 'ہوش مندی سے جواب دیں'],
    orTitle: 'ଆମିଗ୍ଡାଲା ହାଇଜ୍ୟାକ୍ (ଆବେଗପୂର୍ଣ୍ଣ ପ୍ରତିକ୍ରିୟା)', orSummary: 'ତର୍କପୂର୍ଣ୍ଣ ଚିନ୍ତା ପୂର୍ବରୁ ମସ୍ତିଷ୍କର ଭାବପ୍ରବଣ କେନ୍ଦ୍ର ଅପ୍ରତ୍ୟାଶିତ କ୍ରୋଧ ସୃଷ୍ଟି କରିବା।', orTakeaways: ['ଆବେଗ ନିୟନ୍ତ୍ରଣ କରନ୍ତୁ', 'ଧୈର୍ଯ୍ୟ ରଖନ୍ତୁ', 'ଶାନ୍ତ ଭାବରେ ପ୍ରତିକ୍ରିୟା ଦିଅନ୍ତୁ'],
    asTitle: 'এমিগডালা হাইজেক (আৱেগিক আক্ৰমণ)', asSummary: 'যুক্তিগত চিন্তাৰ পূৰ্বেই মগজুৰ আৱেগিক কেন্দ্ৰই নিয়ন্ত্ৰণহীন খং বা ভয় সৃষ্টি কৰে।', asTakeaways: ['খং নিয়ন্ত্ৰণ কৰক', 'কিছু সময় শান্ত থাকক', 'বিচাৰ-বিবেচনাৰে উত্তৰ দিয়ক']
  },

  {
    fileName: 'somaticMarkerHypothesis.ts',
    varName: 'somatic_marker_hypothesis',
    id: 'somatic_marker_hypothesis',
    categoryId: 'emotions',
    slug: 'somatic-marker-hypothesis',
    difficulty: 'advanced',
    readTime: 6,
    sortWeight: 6,
    titleEn: 'The Somatic Marker Hypothesis: How Bodily Signals Guide Reasoning',
    subtitleEn: 'Antonio Damasio’s discovery that rational choices depend fundamentally on subconscious gut sensations.',
    shortDescEn: 'Neurobiological theory showing that bodily sensations associated with past outcomes unconsciously filter choices before conscious logic begins.',
    oneLineEn: 'Your gut and heart acting as subconscious data summaries of all your past experiences.',
    summary30sEn: 'Neuroscientist Antonio Damasio found that patients with damage to the ventromedial prefrontal cortex—who could not feel bodily emotional signals—could calculate probabilities endlessly but were completely paralyzed when making simple everyday choices.',
    coreConceptEn: 'Somatic markers are emotional bioreactions (shifts in heart rate, gut contraction, skin conductance) linked to past experiences. When facing multiple complex choices, somatic markers rapidly mark certain options with an internal "danger" or "reward" tag, pruning the decision tree so rational logic is not overloaded.',
    summary60sEn: 'We often think pure logic is best, but pure abstract logic without bodily feelings leads to decision paralysis. When you negotiate a deal or meet someone, your body reacts milliseconds before your conscious mind articulates reasons. Somatic markers are not mystical instincts; they are compressed neural memories stored across the insular cortex and ventromedial prefrontal cortex.',
    takeawaysEn: [
      'Emotions are not the enemy of reason; they are biological prerequisites for decisive action',
      'Patients without emotional gut markers can analyze options but cannot choose between two pens',
      'Somatic signals rapidly eliminate terrible options before working memory is overwhelmed',
      'Effective decision making pairs bodily intuition with rigorous factual verification'
    ],
    whyItHappensEn: 'Working memory can only hold 4–7 bits of data; without rapid bodily value-tagging, evaluating complex outcomes would crash mental bandwidth.',
    evolutionaryEn: 'Fast assessment of habitat danger or social deceit required immediate visceral alerts rather than mathematical probability calculation.',
    howItWorksEn: 'Scenario encountered -> Brain retrieves past emotional associations -> Autonomic signals alter heart rate and gut tension -> Sensation reported to insula -> Consciousness feels a "gut feeling" -> Logic confirms or refutes.',
    visualHeadlineEn: 'Analytical Paralysis vs. Somatic Pruning',
    visualDescEn: 'How bodily signals make complex decision making cognitively manageable.',
    sideALabelEn: 'Pure Detached Logic (Paralysis)',
    sideADetailEn: 'Endlessly calculating 142 probabilities for a minor choice, trapped in infinite analysis.',
    sideBLabelEn: 'Somatic Pruned Choice (Effective)',
    sideBDetailEn: 'Gut feeling instantly cuts 140 weak options, letting focused logic deeply evaluate the top 2.',
    researchSummaryEn: 'Damasio (1994, Descartes’ Error) and Bechara et al. (1997, Science) used the Iowa Gambling Task to prove normal subjects register skin conductance sweat responses to risky decks long before conscious awareness.',
    refAuthor: 'Damasio, A. R. & Bechara, A.',
    refYear: 1996,
    refTitle: 'The Somatic Marker Hypothesis: A Neural Theory of Decision Making',
    refCitation: 'Damasio, A. R. (1996). Philosophical Transactions of the Royal Society of London. Series B: Biological Sciences, 351(1346), 1413–1420.',
    refDoi: 'https://doi.org/10.1098/rstb.1996.0125',
    scenarioTitleEn: 'The Suspicious Warehouse Lease in Bhiwandi',
    scenarioContextEn: 'Vikram was offered an unusually cheap warehouse rental near Mumbai. On paper, the title was pristine. However, during the walkthrough, Vikram experienced persistent nausea and an unexplained heaviness in his chest, despite the landlord’s smooth charm.',
    scenarioBiasEn: 'Vikram’s somatic markers detected subtle micro-inconsistencies (evasive eye contact, freshly painted water damage) before his conscious mind could document them.',
    scenarioOptimalEn: 'Do not dismiss the bodily discomfort as superstition. Use it as an investigative prompt: hire a structural engineer and conduct a municipal audit, which revealed pending demolition.',
    scenarioReflectionEn: 'Have you ever had a strong physiological gut feeling about a deal or person that proved completely accurate weeks later?',
    howToRecognizeEn: 'Visceral bodily sensations (tight throat, stomach knot, sudden calm) emerging before logical pros-and-cons lists.',
    whereEn: 'High-stakes investments, partnership agreements, ethical dilemmas, and medical diagnoses.',
    misconceptionsEn: 'Myth: "Gut feeling is 100% infallible intuition." Fact: Somatic markers are based on past training; if you are in a brand new domain, your gut can be completely wrong.',
    limitationsEn: 'In novel environments where you lack domain expertise (e.g. quantum physics or crypto trading), somatic markers reflect random anxiety rather than wise intuition.',
    howToRespondEn: 'Treat somatic markers as internal smoke alarms: let them flag concerns, but demand documented evidence before making the final decision.',
    defensesEn: [
      { title: 'The Interoceptive Scan', instruction: 'Before signing or agreeing, pause and scan your stomach and chest for tension or constriction.' },
      { title: 'Intuition-Then-Audit Protocol', instruction: 'Never execute purely on gut alone; treat a gut feeling as a warrant to conduct deeper factual due diligence.' }
    ],
    pqPromptEn: 'A senior investor feels a sharp, unexplained stomach tightness during an otherwise flawless financial presentation. What should they do?',
    pqScenarioEn: 'The spreadsheets look mathematically sound, but an internal visceral unease persists throughout the founder’s speech.',
    pqExplanationEn: 'Somatic markers synthesize micro-cues faster than conscious logic. The investor should use the gut signal to investigate unstated assumptions without making rash decisions.',
    pqAntidoteEn: 'Leverage the bodily alert to ask forensic questions rather than dismissing the feeling or accepting the deal blindly.',
    pqOptionsEn: [
      { id: 'opt_a', text: 'Dismiss the feeling as silly irrational anxiety and wire the funds immediately.', isCorrect: false, feedback: 'Incorrect. Emotional numbness ignores valuable subconscious pattern recognition.' },
      { id: 'opt_b', text: 'Treat the visceral sensation as a prompt to conduct deeper forensic audits into hidden liabilities.', isCorrect: true, feedback: 'Correct! Somatic markers should guide deeper rational investigation.' },
      { id: 'opt_c', text: 'Accuse the founder of fraud instantly based solely on the stomach knot.', isCorrect: false, feedback: 'Incorrect. Bodily signals are alerts, not legal proof.' }
    ],
    reflectionPromptEn: 'In your career, have you made better choices by ignoring bodily signals or by using them to guide your research?',
    titleHinglish: 'Somatic Marker Hypothesis: Gut Feeling Aur Dimaag Ka Rishta',
    subtitleHinglish: 'Kyu hamara pet aur dil kisi faisle se pehle hi signal de dete hain ki kuch gadbad hai.',
    shortDescHinglish: 'Antonio Damasio ki scientific research: sharir ki physical sensations decisions lene me dimaag ki madad karti hain.',
    oneLineHinglish: 'Hamari gut feeling hamare dimaag ka compressed past experience hoti hai.',
    summary30sHinglish: 'Neuroscientist Antonio Damasio ne dikhaya ki jinke dimaag ka emotional center damage ho jata hai, wo pure logical hone ke bawajood chote chote decisions me ghanto atak jate hain. Gut feeling options ko filter karne ke liye zaroori hai.',
    coreConceptHinglish: 'Somatic markers purane tajurbon ke physical signals hote hain (pet me ajeeb lagna, dil ki dhadkan tezi hona). Jab hum naye faisle lete hain, to hamara sharir pehle hi warning de deta hai.',
    summary60sHinglish: 'Hume lagta hai ki best decision sirf thandi logic se hota hai. Lekin bina bodily feelings ke dimaag calculation paralysis me fas jata hai. Gut feeling koi jaadu nahi hai, balki past experience ka subconscious data backup hai.',
    howItWorksHinglish: 'Situation aati hai -> Dimaag purane tajurbe match karta hai -> Sharir me physical sensation bhejta hai -> Hume lagta hai "kuch galat hai" -> Hum logic se cross-check karte hain.',
    howToRespondHinglish: 'Gut feeling ko smoke alarm samjhein: jab pet me ajeeb lage, to deal cancel mat karo, balki paperwork aur background check double karo.',
    takeawaysHinglish: [
      'Gut feeling magic nahi, balki past data ka subconscious summary hai',
      'Bina emotion ke insaan super-smart nahi, balki faisla lene me bekaar ho jata hai',
      'Sharir ke physical signals ko ignore mat karo, unhe deeper investigation ka signal mano',
      'Domain me agar experience naya hai to gut feeling galat bhi ho sakti hai'
    ],
    pqPromptHinglish: 'Ek naye business partner ke sath contract sign karte waqt aapke pet me ajeeb si ghabrahat ho rahi hai, jabki paper theek lag rahe hain. Kya karein?',
    pqExplanationHinglish: 'Sharir ka signal alert karta hai ki shayad subconscious mind ne kuch notice kiya hai. Use investigate karne ka mauka samjhein.',
    pqOptionsHinglish: [
      { id: 'opt_a', text: 'Ghabrahat ko ignore karein aur bina dekhe sign kar dein.', isCorrect: false, feedback: 'Galat. Subconscious warning ko ignore mat karein.' },
      { id: 'opt_b', text: 'Is signal ko warning maan kar lawyer aur references se double verification karein.', isCorrect: true, feedback: 'Sahi! Gut feeling ko facts se verify karna hi best decision banata hai.' },
      { id: 'opt_c', text: 'Bina kisi proof ke partner par fraud ka case kar dein.', isCorrect: false, feedback: 'Galat. Gut feeling alert hai, court ka faisla nahi.' }
    ],
    hiTitle: 'शारीरिक संकेत परिकल्पना (Somatic Marker)',
    hiSummary: 'शारीरिक अनुभूतियां और अंतर्ज्ञान कैसे जटिल निर्णयों को सरल और सटीक बनाने में मस्तिष्क का मार्गदर्शन करते हैं।',
    hiTakeaways: ['शारीरिक संवेदनाएं अतीत के अनुभवों का संक्षिप्त रूप हैं', 'भावनाओं के बिना निर्णय लेना असंभव हो जाता है', 'आंतरिक अनुभूतियों को तार्किक जांच से जोड़ें'],
    guTitle: 'સોમેટિક માર્કર પૂર્વધારણા', guSummary: 'શરીરના સંકેતો અને આંતરિક લાગણીઓ નિર્ણય લેવાની ક્ષમતાને માર્ગદર્શન આપે છે.', guTakeaways: ['શરીરના સંકેતો સમજો', 'સત્યની તપાસ કરો', 'સંતુલિત નિર્ણય લો'],
    mrTitle: 'सोमॅटिक मार्कर सिद्धांत', mrSummary: 'शारीरिक संवेदना आणि अंतःप्रेरणा कशा प्रकारे जटिल निर्णयांमध्ये मेंदूला मदत करतात.', mrTakeaways: ['शारीरिक संकेत ओळखा', 'तथ्ये पडताळून पहा', 'योग्य निर्णय घ्या'],
    teTitle: 'సోమాటిక్ మార్కర్ సిద్ధాంతం', teSummary: 'శరీర సంకేతాలు మరియు సహజ అంతర్దృష్టి సరైన నిర్ణయాలు తీసుకోవడంలో ఎలా సహాయపడతాయి.', teTakeaways: ['అంతర్దృష్టిని విశ్లేషించండి', 'ఆధారాలు సరిచూడండి', 'స్పష్టమైన నిర్ణయం తీసుకోండి'],
    taTitle: 'உடல் உணர்வு கோட்பாடு (Somatic Marker)', taSummary: 'உடலின் உள்ளுணர்வு சமிக்ஞைகள் எவ்வாறு பகுத்தறிவு முடிவுகளை வழிநடத்துகின்றன.', taTakeaways: ['உடல் சமிக்ஞைகளை கவனியுங்கள்', 'உண்மைகளை ஆராயுங்கள்', 'சரியான முடிவெடுங்கள்'],
    knTitle: 'ಸೊಮ್ಯಾಟಿಕ್ ಮಾರ್ಕರ್ ಸಿದ್ಧಾಂತ', knSummary: 'ದೇಹದ ಆಂತರಿಕ ಸಂವೇದನೆಗಳು ನಿರ್ಧಾರ ಕೈಗೊಳ್ಳುವಲ್ಲಿ ಮೆದುಳಿಗೆ ಹೇಗೆ ಮಾರ್ಗದರ್ಶನ ನೀಡುತ್ತವೆ.', knTakeaways: ['ಆಂತರಿಕ ಸಂವೇದನೆಗಳನ್ನು ಗಮನಿಸಿ', 'ದಾಖಲೆಗಳನ್ನು ಪರಿಶೀಲಿಸಿ', 'ಬುದ್ಧಿವಂತ ನಿರ್ಧಾರ ತೆಗೆದುಕೊಳ್ಳಿ'],
    mlTitle: 'സൊമാറ്റിക് മാർക്കർ സിദ്ധാന്തം', mlSummary: 'ശരീരത്തിൻ്റെ ആന്തരിക പ്രതികരണങ്ങൾ ശരിയായ തീരുമാനങ്ങളിലേക്ക് നയിക്കുന്നു.', mlTakeaways: ['ഉള്ളുണർവുകൾ തിരിച്ചറിയുക', 'വസ്തുതകൾ പരിശോധിക്കുക', 'യുക്തിയോടെ തീരുമാനിക്കുക'],
    bnTitle: 'সোমাটিক মার্কার হাইপোথিসিস', bnSummary: 'শারীরিক অনুভূতি এবং অবচেতন সংকেত কীভাবে সঠিক সিদ্ধান্ত নিতে সাহায্য করে।', bnTakeaways: ['শারীরিক অনুভূতি বুঝুন', 'তথ্য যাচাই করুন', 'সঠিক সিদ্ধান্ত নিন'],
    paTitle: 'ਸੋਮੈਟਿਕ ਮਾਰਕਰ ਸਿਧਾਂਤ', paSummary: 'ਸਰੀਰਕ ਸੰਕੇਤ ਅਤੇ ਅੰਦਰੂਨੀ ਆਵਾਜ਼ ਫੈਸਲਾ ਲੈਣ ਵਿੱਚ ਦਿਮਾਗ ਨੂੰ ਕਿਵੇਂ ਰਾਹ ਦਿਖਾਉਂਦੇ ਹਨ।', paTakeaways: ['ਅੰਦਰੂਨੀ ਆਵਾਜ਼ ਸੁਣੋ', 'ਤੱਥਾਂ ਦੀ ਜਾਂਚ ਕਰੋ', 'ਸਹੀ ਫੈਸਲਾ ਲਓ'],
    urTitle: 'سوماتی نشاناتی مفروضہ (Somatic Marker)', urSummary: 'جسمانی کیفیات اور دل کی دھڑکن کس طرح عقلی فیصلوں کی رہنمائی کرتی ہے۔', urTakeaways: ['جسمانی اشاروں کو سمجھیں', 'حقائق کی تصدیق کریں', 'متوازن فیصلہ کریں'],
    orTitle: 'ସୋମାଟିକ୍ ମାର୍କର୍ ଅନୁମାନ', orSummary: 'ଶରୀରର ଆଭ୍ୟନ୍ତରୀଣ ସଙ୍କେତ କିପରି ନିଷ୍ପତ୍ତି ନେବାରେ ସାହାଯ୍ୟ କରେ।', orTakeaways: ['ଅନ୍ତର୍ନିହିତ ସଙ୍କେତ ବୁଝନ୍ତୁ', 'ତଥ୍ୟ ପ୍ରମାଣ ଦେଖନ୍ତୁ', 'ଠିକ୍ ନିଷ୍ପତ୍ତି ନିଅନ୍ତୁ'],
    asTitle: 'সোমেটিক মাৰ্কাৰ অনুমান', asSummary: 'শাৰীৰিক সংবেদনাই জটিল সিদ্ধান্ত গ্ৰহণত কেনেকৈ মগজুক বাট দেখুৱায়।', asTakeaways: ['শাৰীৰিক সংকেত বুজি লওক', 'তথ্য পৰীক্ষা কৰক', 'সচেতন সিদ্ধান্ত লওক']
  },

  {
    fileName: 'hedonicTreadmill.ts',
    varName: 'hedonic_treadmill',
    id: 'hedonic_treadmill',
    categoryId: 'emotions',
    slug: 'hedonic-treadmill',
    difficulty: 'beginner',
    readTime: 5,
    sortWeight: 7,
    titleEn: 'The Hedonic Treadmill: The Rapid Adaptation to Life Upgrades',
    subtitleEn: 'Why luxury, promotions, and wealth spikes quickly become the new baseline of normal.',
    shortDescEn: 'The observed psychological tendency of humans to quickly return to a relatively stable level of happiness despite major positive or negative life events.',
    oneLineEn: 'Running endlessly on the treadmill of desire, always ending up where you started.',
    summary30sEn: 'First identified by Brickman and Campbell in 1971, the hedonic treadmill describes how humans rapidly habituate to material windfalls, salary hikes, and luxuries. Within months, what once felt extraordinary becomes the invisible default, leaving baseline happiness unchanged.',
    coreConceptEn: 'Neural sensory adaptation applies directly to emotional rewards: neurons fire vigorously in response to novel positive stimuli, but reduce their firing rates as the stimulus persists. As expectations rise in tandem with accomplishments, happiness resets to the individual’s genetic and cognitive set point.',
    summary60sEn: 'In a famous 1978 study comparing lottery winners and paraplegic accident survivors, Brickman found that after one year, both groups returned remarkably close to their pre-event happiness baselines. While life circumstances account for roughly 10% of subjective well-being, the treadmill tricks us into believing that the next milestone will permanently fix our dissatisfaction.',
    takeawaysEn: [
      'Material upgrades produce temporary dopamine spikes followed by permanent sensory adaptation',
      'The "arrival fallacy" creates the false belief that hitting a future goal guarantees lasting joy',
      'Experiences, deep social bonds, and autonomy resist hedonic adaptation far longer than possessions',
      'Intentional gratitude and voluntary discomfort reset hedonic tolerance levels'
    ],
    whyItHappensEn: 'Evolutionary survival required constant striving; animals that stayed permanently satisfied after finding one fruit tree lacked motivation to seek future sustenance.',
    evolutionaryEn: 'A perpetually satisfied human would not prepare for winter or defend against competitors.',
    howItWorksEn: 'Major goal achieved -> Massive dopamine high -> Sensory habituation occurs -> Expectations recalibrate upwards -> New state feels ordinary -> Urge for next achievement begins.',
    visualHeadlineEn: 'The Hedonic Adaptation Reset Cycle',
    visualDescEn: 'How luxury upgrades become the invisible baseline over 90 days.',
    sideALabelEn: 'Perceived Future State',
    sideADetailEn: '"Once I buy this luxury apartment and car, I will never feel stressed or unhappy again."',
    sideBLabelEn: 'Actual Neurological Reality',
    sideBDetailEn: 'Day 1: Ecstatic joy; Day 30: Pleasant satisfaction; Day 90: It is just where you sleep, stress returns.',
    researchSummaryEn: 'Brickman, Coates & Janoff-Bulman (1978) in JPSP tracked lottery winners and control groups, finding that lottery winners took no more pleasure in mundane everyday events than ordinary citizens.',
    refAuthor: 'Brickman, P. & Campbell, D. T.',
    refYear: 1971,
    refTitle: 'Hedonic Relativism and Planning the Good Society',
    refCitation: 'Brickman, P., & Campbell, D. T. (1971). Adaptation-level theory: A symposium, 287–305.',
    refDoi: 'https://doi.org/10.1037/h0037340',
    scenarioTitleEn: 'The Bengaluru Tech Promotion Reset',
    scenarioContextEn: 'Neha worked 70 hours a week for two years in Bengaluru to reach Senior Engineering Director, assuming a ₹60 LPA salary would erase all anxiety. Within three months of buying a luxury German sedan, the excitement evaporated and she was consumed by envy for peers making ₹1 Crore.',
    scenarioBiasEn: 'Neha fell victim to the hedonic treadmill: her material baseline adapted instantly, resetting her dopamine threshold without changing her internal relationship to work.',
    scenarioOptimalEn: 'Anchor satisfaction in intrinsic craft and meaningful connections, using intermittent digital sabbaths and voluntary frugality to preserve emotional appreciation.',
    scenarioReflectionEn: 'Think of something you desperately wanted three years ago that you now own. How often do you actively feel intense joy about it today?',
    howToRecognizeEn: 'The persistent thought: "I will finally be happy once X happens," followed by hollow indifference weeks after achieving X.',
    whereEn: 'Luxury consumer goods, salary increments, tech device upgrades, and social status competition.',
    misconceptionsEn: 'Myth: "The hedonic treadmill means you should never pursue goals." Fact: Goals provide purpose and direction; the trap is assuming they will permanently solve your internal state.',
    limitationsEn: 'Chronic severe stressors (chronic pain, severe poverty, toxic abuse) do not adapt fully and permanently lower baseline well-being.',
    howToRespondEn: 'Practice Voluntary Hedonic Resetting: take periodic cold showers, fast, camping trips, or gratitude journaling to recalibrate the brain’s dopamine sensitivity.',
    defensesEn: [
      { title: 'The 30-Day Delay Rule', instruction: 'Wait 30 days before buying any non-essential luxury item to allow the initial hedonic craving spike to cool.' },
      { title: 'Negative Visualization (Stoic Practice)', instruction: 'Spend 2 minutes imagining life without your current health, home, or loved ones to re-sensitize appreciation.' }
    ],
    pqPromptEn: 'A professional receives a 40% salary hike and buys their dream sports car. According to hedonic adaptation research, what will their emotional state be 9 months later?',
    pqScenarioEn: 'They initially feel ecstatic and show the car to everyone in their social circle.',
    pqExplanationEn: 'Hedonic adaptation ensures that neurological habituation returns subjective well-being close to the baseline level within months.',
    pqAntidoteEn: 'Anticipate adaptation and invest in growth and relationships rather than endless material upgrades.',
    pqOptionsEn: [
      { id: 'opt_a', text: 'They will maintain a permanently elevated 40% higher level of daily happiness.', isCorrect: false, feedback: 'Incorrect. Sensory adaptation prevents permanent joy spikes from material goods.' },
      { id: 'opt_b', text: 'Their daily happiness will return close to baseline as the car becomes the new normal.', isCorrect: true, feedback: 'Correct! The hedonic treadmill resets the baseline of satisfaction.' },
      { id: 'opt_c', text: 'They will plunge into clinical depression solely due to having the car.', isCorrect: false, feedback: 'Incorrect. Baseline returns to normal, not pathological depression.' }
    ],
    reflectionPromptEn: 'What daily habit or relationship in your life provides enduring satisfaction that never seems to fade with time?',
    titleHinglish: 'The Hedonic Treadmill: Har Khushi Ka Normal Ban Jana',
    subtitleHinglish: 'Kyu nayi gaadi, salary hike aur promotions ka maza kuch hi mahino me gayab ho jata hai.',
    shortDescHinglish: 'Dimaag ka psychological habituation mechanism jo har nayi luxury ko normal default bana deta hai.',
    oneLineHinglish: 'Khushi ki treadmill par daudte rehna par hamesha wahi khade rehna.',
    summary30sHinglish: 'Brickman aur Campbell ne prove kiya ki insaan kitni bhi badi lottery jeet le ya luxury khareed le, 6 mahine me dimaag use aam baat maan leta hai aur khushi wapas purane level par aa jati hai.',
    coreConceptHinglish: 'Hamare neurons nayi cheezon par dopamine chhodte hain, lekin jab wahi cheez roz rehti hai to dimaag adapt kar leta hai. Expectations badh jati hain aur hum wapas nayi cheez ki talaash me lag jate hain.',
    summary60sHinglish: 'Aapne jo phone ya bike 3 saal pehle mar-mar ke khareedi thi, aaj wo bas ek aam cheez lagti hai. Ise kehte hain Hedonic Treadmill. Agar hum is mechanism ko nahi samjhenge to hum hamesha consumerism ke jaal me phase rahenge.',
    howItWorksHinglish: 'Naya goal achieve hua -> Dopamine spike mila -> Kuch dino me adaptation ho gayi -> Nayi luxury normal lagne lagi -> Agle goal ke peeche bhaagna shuru.',
    howToRespondHinglish: 'Negative visualization karein: Sochein agar yeh suvidhayein na hoti to kaisa hota. Aur voluntary fasting ya simplicity se dopamine baseline reset karein.',
    takeawaysHinglish: [
      'Nayi cheezon ki khushi temporary hoti hai, dimaag use jaldi hi normal bana deta hai',
      '"Bas yeh mil jaye to sab theek ho jayega" dimaag ka sabse bada dhokha hai (Arrival Fallacy)',
      'Cheezon ke bajaye anubhav aur rishte lamba sukoon dete hain',
      'Kabhi kabhi simplicity aur gratitude se baseline reset karna zaroori hai'
    ],
    pqPromptHinglish: 'Ek dost ko badi company me 50% hike mila. 6 mahine baad uski mental state research ke mutabiq kaisi hogi?',
    pqExplanationHinglish: 'Hedonic adaptation ke chalte nayi salary jaldi hi standard kharche aur baseline me badal jati hai.',
    pqOptionsHinglish: [
      { id: 'opt_a', text: 'Wo hamesha ke liye 50% zyada khush rahega aur kabhi tension nahi lega.', isCorrect: false, feedback: 'Galat. Dimaag jaldi adapt kar leta hai.' },
      { id: 'opt_b', text: 'Uski khushi wapas purane level par aa jayegi aur naye kharche normal lagne lagenge.', isCorrect: true, feedback: 'Sahi! Hedonic treadmill baseline ko reset kar deti hai.' },
      { id: 'opt_c', text: 'Wo turant salary wapas karne ki koshish karega.', isCorrect: false, feedback: 'Galat. Yeh unrealistic hai.' }
    ],
    hiTitle: 'सुखवादी ट्रेडमिल (Hedonic Treadmill)',
    hiSummary: 'जीवन में बड़ी उपलब्धियों और भौतिक सुख-सुविधाओं के बाद भी मानव मस्तिष्क का अपनी सामान्य स्थिति में वापस लौट आना।',
    hiTakeaways: ['भौतिक सुखों का प्रभाव अल्पकालिक होता है', 'मस्तिष्क नई परिस्थितियों को शीघ्र सामान्य मान लेता है', 'संतुष्टि आंतरिक दृष्टिकोण से आती है'],
    guTitle: 'હેડોનિક ટ્રેડમિલ (સુખનું અનુકૂલન)', guSummary: 'જીવનમાં ગમે તેટલી પ્રગતિ થાય તો પણ સુખનું સ્તર થોડા સમયમાં સામાન્ય થઈ જાય છે.', guTakeaways: ['ભૌતિક સુખ ક્ષણિક છે', 'મન નવી સ્થિતિ સ્વીકારી લે છે', 'આંતરિક શાંતિ કેળવો'],
    mrTitle: 'सुखवादी ट्रेडमिल (Hedonic Treadmill)', mrSummary: 'भौतिक प्रगती आणि सुखसोयींनंतरही मानवी आनंदाची पातळी पुन्हा पूर्ववत होण्याची मानसिक प्रवृत्ती.', mrTakeaways: ['भौतिक सुखाचे आकर्षण तात्पुरते असते', 'मेंदू नव्या सुखांना सरावतो', 'समाधान आंतरिक असते'],
    teTitle: 'హెడోనిక్ ట్రెడ్‌మిల్ (సుఖానికి అలవాటుపడటం)', teSummary: 'ఎంత పెద్ద విజయం సాధించినా కొంత కాలానికి ఆనందం సాధారణ స్థాయికి చేరే సహజ మానసిక లక్షణం.', teTakeaways: ['భౌతిక ఆనందం తాత్కాలికం', 'మనస్సు కొత్త స్థితిని స్వీకరిస్తుంది', 'శాశ్వత తృప్తి అంతర్గతం'],
    taTitle: 'இன்ப நடைவண்டி கோட்பாடு (Hedonic Treadmill)', taSummary: 'எவ்வளவு பெரிய மகிழ்ச்சியான நிகழ்வு நடந்தாலும் மனித மனம் மீண்டும் இயல்பு நிலைக்குத் திரும்பும் உளவியல்.', taTakeaways: ['பொருளாதார மகிழ்ச்சி தற்காலிகமானது', 'மனம் புதிய நிலைக்கு பழகிவிடும்', 'உள் அமைதியே நிலையானது'],
    knTitle: 'ಹೆಡೋನಿಕ್ ಟ್ರೆಡ್‌ಮಿಲ್ (ಸುಖದ ಹೊಂದಾಣಿಕೆ)', knSummary: 'ಎಷ್ಟೇ ದೊಡ್ಡ ಯಶಸ್ಸು ಸಿಕ್ಕರೂ ಸಂತೋಷದ ಮಟ್ಟವು ಶೀಘ್ರದಲ್ಲೇ ಸಾಮಾನ್ಯ ಸ್ಥಿತಿಗೆ ಮರಳುವ ವಿದ್ಯಮಾನ.', knTakeaways: ['ಭೌತಿಕ ಸಂತೋಷ ಕ್ಷಣಿಕ', 'ಮನಸ್ಸು ಸುಖಕ್ಕೆ ಹೊಂದಿಕೊಳ್ಳುತ್ತದೆ', 'ಆಂತರಿಕ ತೃಪ್ತಿ ಮುಖ್ಯ'],
    mlTitle: 'ഹെഡോണിക് ട്രെഡ്മിൽ (സുഖാനുഭവത്തിന്റെ വേഗത)', mlSummary: 'വലിയ നേട്ടങ്ങൾ കൈവരിച്ചാലും സന്തോഷം വേഗത്തിൽ സാധാരണ നിലയിലേക്ക് മടങ്ങുന്ന സ്വഭാവം.', mlTakeaways: ['ഭൗതിക സുഖം താൽക്കാലികമാണ്', 'മനസ്സ് പുതിയ സാഹചര്യങ്ങളുമായി പൊരുത്തപ്പെടുന്നു', 'ശാശ്വത സമാധാനം ഉള്ളിലാണ്'],
    bnTitle: 'হেডোনিক ট্রেডমিল (সুখের অভিযোজন)', bnSummary: 'বড় প্রাপ্তি বা বিলাসিতার পরও মানুষের সুখের মাত্রা দ্রুত পূর্বের স্বাভাবিক অবস্থায় ফিরে আসার নিয়ম।', bnTakeaways: ['বস্তুগত সুখ ক্ষণস্থায়ী', 'মন নতুন অবস্থাকে স্বাভাবিক ধরে নেয়', 'অভ্যন্তরীণ তৃপ্তি স্থায়ী'],
    paTitle: 'ਹੈਡੋਨਿਕ ਟ੍ਰੈਡਮਿਲ (ਸੁੱਖ ਦਾ ਆਦੀ ਹੋਣਾ)', paSummary: 'ਕੋਈ ਵੱਡੀ ਸਫਲਤਾ ਜਾਂ ਖੁਸ਼ੀ ਮਿਲਣ ਦੇ ਬਾਵਜੂਦ ਇਨਸਾਨੀ ਮਨ ਦਾ ਮੁੜ ਆਮ ਪੱਧਰ ਤੇ ਆ ਜਾਣ ਦੀ ਆਦਤ।', paTakeaways: ['ਭੌਤਿਕ ਸੁੱਖ ਆਰਜ਼ੀ ਹੈ', 'ਦਿਮਾਗ ਨਵੀਂ ਹਾਲਤ ਦਾ ਆਦੀ ਹੋ ਜਾਂਦਾ ਹੈ', 'ਅਸਲ ਸੰਤੁਸ਼ਟੀ ਅੰਦਰੂਨੀ ਹੈ'],
    urTitle: 'ہیڈونک ٹریڈمل (خوشی کا معمول بن جانا)', urSummary: 'کسی بڑی کامیابی یا آسائش کے بعد بھی انسانی خوشی کی سطح کا جلد ہی معمول پر لوٹ آنا۔', urTakeaways: ['مادی خوشی عارضی ہوتی ہے', 'دماغ نئی آسائشوں کا عادی ہو جاتا ہے', 'حقیقی سکون اندرونی ہوتا ہے'],
    orTitle: 'ହେଡୋନିକ୍ ଟ୍ରେଡ୍‌ମିଲ୍ (ସୁଖର ଅନୁକୂଳନ)', orSummary: 'ବଡ଼ ସଫଳତା ପରେ ମଧ୍ୟ ମଣିଷର ଆନନ୍ଦ ପୁନର୍ବାର ସ୍ୱାଭାବିକ ସ୍ତରକୁ ଫେରିଆସିବାର ନିୟମ।', orTakeaways: ['ଭୌତିକ ସୁଖ କ୍ଷଣସ୍ଥାୟୀ', 'ମନ ନୂଆ ପରିସ୍ଥିତିକୁ ଗ୍ରହଣ କରେ', 'ଆତ୍ମସନ୍ତୋଷ ସବୁଠୁ ବଡ଼'],
    asTitle: 'হেডনিক ট্রেডমিল (সুখৰ অভিযোজন)', asSummary: 'ডাঙৰ সফলতা লাভৰ পিছতো মানুহৰ আনন্দৰ মাত্ৰা পুনৰ স্বাভাৱিক অৱস্থালৈ ঘূৰি অহাৰ মানসিকতা।', asTakeaways: ['বস্তুগত আনন্দ ক্ষণস্থায়ী', 'মগজুৱে নতুন অৱস্থাক স্বাভাৱিক বুলি গ্ৰহণ কৰে', 'আভ্যন্তৰীণ সন্তুষ্টিয়েই স্থায়ী']
  },

  {
    fileName: 'broadenAndBuildTheory.ts',
    varName: 'broaden_and_build',
    id: 'broaden_and_build',
    categoryId: 'emotions',
    slug: 'broaden-and-build-theory',
    difficulty: 'intermediate',
    readTime: 5,
    sortWeight: 8,
    titleEn: 'The Broaden-and-Build Theory: How Positive Emotions Expand Cognition',
    subtitleEn: 'Barbara Fredrickson’s empirical model demonstrating that joy and curiosity expand peripheral vision and problem-solving bandwidth.',
    shortDescEn: 'Positive emotions broaden an individual’s momentary thought-action repertoire and build enduring personal resources including resilience and social capital.',
    oneLineEn: 'Negative emotions narrow focus for survival; positive emotions broaden vision for growth.',
    summary30sEn: 'While negative emotions (fear, anger) narrow our cognitive focus to fight or flee, psychologist Barbara Fredrickson proved that positive emotions (joy, curiosity, awe) physically widen visual attention and psychological flexibility, building lasting intellectual and social reserves.',
    coreConceptEn: 'The evolutionary function of positive emotions is not just to feel good; it is to broaden our momentary cognitive horizon. Eye-tracking and fMRI studies prove that people in positive states perceive more peripheral information, generate creative divergent solutions, and build durable social alliances.',
    summary60sEn: 'Under acute threat, tunnel vision saves your life. But in everyday life, chronic stress keeps you trapped in narrow, defensive problem-solving. Experiencing micro-moments of authentic positive emotion expands attention, allowing you to connect previously unrelated ideas and discover novel paths out of dilemmas.',
    takeawaysEn: [
      'Negative emotions narrow our perspective down to immediate survival threats',
      'Positive emotions broaden visual field and creative cognitive associations',
      'Broadened mindsets accumulate into enduring psychological resilience and social alliances',
      'Cultivating micro-moments of genuine gratitude accelerates cognitive problem-solving'
    ],
    whyItHappensEn: 'Ancestors who explored, played, and bonded during safe times built alliances and tools that saved them when winter or drought struck.',
    evolutionaryEn: 'Play in young mammals builds motor coordination and social coalitions vital for adult survival.',
    howItWorksEn: 'Positive emotion felt -> Visual attention widens -> Cognitive associations expand -> Creative solutions discovered -> Enduring coping skills and social ties accumulated.',
    visualHeadlineEn: 'Tunnel Vision vs. Panoramic Cognitive Expansion',
    visualDescEn: 'How affective valence directly regulates attentional bandwidth.',
    sideALabelEn: 'Threat State (Narrow Focus)',
    sideADetailEn: 'Visual field shrinks, fixates on defects, rejects novel ideas, defaults to rigid defense.',
    sideBLabelEn: 'Positive State (Broadened Focus)',
    sideBDetailEn: 'Notices peripheral opportunities, embraces creative divergence, forms cooperative networks.',
    researchSummaryEn: 'Fredrickson (2001, American Psychologist) and Fredrickson & Branigan (2005) experimentally proved that induced positive affect significantly increases visual attention scope and global cognitive processing.',
    refAuthor: 'Fredrickson, B. L.',
    refYear: 2001,
    refTitle: 'The Role of Positive Emotions in Positive Psychology',
    refCitation: 'Fredrickson, B. L. (2001). American Psychologist, 56(3), 218–226.',
    refDoi: 'https://doi.org/10.1037/0003-066X.56.3.218',
    scenarioTitleEn: 'The Stuck Product Brainstorm in Pune',
    scenarioContextEn: 'An automotive design team in Pune was stuck for three weeks on a battery cooling problem. Tension was high, with the lead engineer threatening layoffs. Everyone suggested the same incremental tweaks. A new lead arranged a casual team lunch with humorous storytelling; within 2 hours of laughing and relaxing, the team cracked an innovative heat-sink design.',
    scenarioBiasEn: 'Fear and anxiety had narrowed the engineers\' cognitive repertoires to conservative, defensive suggestions; positive levity broadened their conceptual search space.',
    scenarioOptimalEn: 'When teams face intractable complex challenges, disengage from high-pressure grinding and deliberately introduce psychological safety and playful exploration.',
    scenarioReflectionEn: 'When was the last time a lighthearted walk or laugh with a friend sparked the solution to a problem you had been struggling with for days?',
    howToRecognizeEn: 'Feeling mentally expansive, open to other viewpoints, and eager to explore experimental solutions rather than defending your turf.',
    whereEn: 'Scientific research, product design, high-stakes crisis leadership, and personal conflict resolution.',
    misconceptionsEn: 'Myth: "Toxic positivity means pretending bad things do not exist." Fact: Broaden-and-build is about micro-moments of authentic positive emotion, not ignoring realistic risks.',
    limitationsEn: 'When immediate precision and error detection are vital (e.g., surgical procedures or flight-control audits), a narrower critical focus is functional.',
    howToRespondEn: 'Before tackling a thorny complex dilemma, prime your brain with 3 minutes of humor, gratitude, or aesthetic awe (like looking at a sunset or complex architecture).',
    defensesEn: [
      { title: 'The Positivity Priming Ritual', instruction: 'Before intense creative work, watch a 2-minute inspiring video or recall a moment of profound gratitude to broaden attentional scope.' },
      { title: 'The Playful Reframe', instruction: 'Reframe obstacles as puzzles rather than verdicts on your worth to keep prefrontal exploratory circuits open.' }
    ],
    pqPromptEn: 'A software engineering team is completely blocked on an architectural bug for 5 days. What leadership action best leverages the Broaden-and-Build theory?',
    pqScenarioEn: 'Team morale is low, exhaustion is palpable, and developers are snapping at each other in standup meetings.',
    pqExplanationEn: 'Positive affect physically broadens associative cognitive search, enabling engineers to connect disparate concepts that stress-induced tunnel vision conceals.',
    pqAntidoteEn: 'De-escalate panic, inject psychological safety and humor, and allow playfulness to reset cognitive scope.',
    pqOptionsEn: [
      { id: 'opt_a', text: 'Demand mandatory weekend overtime and threaten performance warnings for delay.', isCorrect: false, feedback: 'Incorrect. Threat narrows cognitive focus further, guaranteeing more tunnel vision.' },
      { id: 'opt_b', text: 'Host a relaxed team break with humor, psychological safety, and open-ended lateral brainstorming.', isCorrect: true, feedback: 'Correct! Broadening affective state widens problem-solving bandwidth.' },
      { id: 'opt_c', text: 'Fire the junior developer to shock the remaining engineers into working faster.', isCorrect: false, feedback: 'Incorrect. Fear paralyzes creative thinking.' }
    ],
    reflectionPromptEn: 'How can you deliberately integrate 5 minutes of genuine curiosity or awe into your daily morning routine?',
    titleHinglish: 'Broaden-and-Build Theory: Positivity Kaise Dimaag Kholti Hai',
    subtitleHinglish: 'Kyu muskurane aur halke-phulke rehne se problems ke behtar solutions milte hain.',
    shortDescHinglish: 'Barbara Fredrickson ki research: Positive emotions dimaag ka vision aur creative thinking badhate hain.',
    oneLineHinglish: 'Darr dimaag ko narrow karta hai, khushi dimaag ka daayra badhati hai.',
    summary30sHinglish: 'Jab hum darr ya gusse me hote hain, dimaag sirf ladne ya bhaagne ki sochta hai (tunnel vision). Lekin jab hum khush ya curious hote hain, to aankhon ka dekhne ka daayra aur dimaag ki creativity dono exponentially expand ho jate hain.',
    coreConceptHinglish: 'Positive emotions sirf achha feel karne ke liye nahi hain, balki wo dimaag ki problem-solving capacity badhane ka biological tool hain. Hasne aur relax karne se dimaag nayi possibilities dekh pata hai.',
    summary60sHinglish: 'Agar aap kisi mushkil problem me ghanto se fase hain, to gusse me computer screen ko ghoorne se kuch nahi hoga. 10 minute kisi dost se has kar baat karein ya chai piyein. Jaise hi mood positive hoga, dimaag naye angles dekhne lagega.',
    howItWorksHinglish: 'Khushi ya curiosity aati hai -> Dimaag relax hota hai -> Peripheral vision aur ideas widen hote hain -> Naye solutions dikhte hain -> Long-term confidence banta hai.',
    howToRespondHinglish: 'Jab bhi dimaag block ho, kaam rok kar 5 minute kuch aisa karein jisse mann khush ho—chai peena, gana sunna, ya walk karna.',
    takeawaysHinglish: [
      'Stress dimaag ko narrow tunnel me daal deta hai, jisme creative ideas nahi aate',
      'Positive emotions dimaag ki thinking aur vision dono ko physically broaden karte hain',
      'Mushkil problems solve karne se pehle 5 minute ka positive mood reset zaroori hai',
      'Rozana gratitude aur curiosity practice karne se long-term mental resilience banti hai'
    ],
    pqPromptHinglish: 'Team ek mushkil coding bug me 3 din se fasi hui hai aur sab gusse me hain. Best leadership step kya hoga?',
    pqExplanationHinglish: 'Stress aur gusse se dimaag narrow ho jata hai. Halki-phulki positivity dimaag ka scope wapas khol deti hai.',
    pqOptionsHinglish: [
      { id: 'opt_a', text: 'Sabko daantna aur raat bhar baith kar kaam karne ka order dena.', isCorrect: false, feedback: 'Galat. Isse tunnel vision aur ghaltiyan badhengi.' },
      { id: 'opt_b', text: 'Team ko 20 minute ka chai break dena, mahol halka karna aur naye nazariye se sochna.', isCorrect: true, feedback: 'Sahi! Positivity dimaag ke creative connections ko open karti hai.' },
      { id: 'opt_c', text: 'Project ko cancel kar dena.', isCorrect: false, feedback: 'Galat. Yeh defeatism hai.' }
    ],
    hiTitle: 'विस्तार और निर्माण सिद्धांत (Broaden-and-Build)',
    hiSummary: 'सकारात्मक भावनाएं कैसे संज्ञानात्मक लचीलेपन, रचनात्मकता और स्थायी मानसिक संसाधनों का निर्माण करती हैं।',
    hiTakeaways: ['सकारात्मकता दृष्टि और सोच का दायरा बढ़ाती है', 'तनाव मस्तिष्क को संकुचित कर देता है', 'आनंद स्थायी आंतरिक शक्ति का निर्माण करता है'],
    guTitle: 'બ્રોડન એન્ડ બિલ્ડ સિદ્ધાંત', guSummary: 'હકારાત્મક લાગણીઓ કેવી રીતે વિચારવાની ક્ષમતા અને સર્જનાત્મકતામાં વધારો કરે છે.', guTakeaways: ['હકારાત્મકતા દ્રષ્ટિકોણ વિસ્તારે છે', 'તણાવ વિચારશક્તિ ઘટાડે છે', 'આનંદ નવી ક્ષમતા બનાવે છે'],
    mrTitle: 'विस्तार आणि निर्मिती सिद्धांत', mrSummary: 'सकारात्मक भावनांमुळे कशा प्रकारे माणसाची विचारशक्ती आणि नवनिर्मितीची क्षमता विस्तारते.', mrTakeaways: ['सकारात्मकता विचारांची कक्षा रुंदावते', 'ताणतणाव विचार संकुचित करतो', 'आनंदातून नवी ऊर्जा मिळते'],
    teTitle: 'విస్తరణ మరియు నిర్మాణ సిద్ధాంతం', teSummary: 'సానుకూల భావోద్వేగాలు సృజనాత్మకతను మరియు ఆలోచనా పరిధిని ఎలా విస్తరిస్తాయి.', teTakeaways: ['సానుకూలత దృష్టిని పెంచుతుంది', 'ఒత్తిడి ఆలోచనలను తగ్గిస్తుంది', 'ఆనందం స్థిరమైన బలాన్ని ఇస్తుంది'],
    taTitle: 'விரிவுபடுத்து மற்றும் உருவாக்கு கோட்பாடு', taSummary: 'நேர்மறை உணர்ச்சிகள் எவ்வாறு சிந்தனைத் திறனையும் படைப்பாற்றலையும் விரிவுபடுத்துகின்றன.', taTakeaways: ['நேர்மறை எண்ணம் பார்வையை விரிக்கும்', 'மன அழுத்தம் சிந்தனையை சுருக்கும்', 'மகிழ்ச்சி புதிய வழிகளைத் திறக்கும்'],
    knTitle: 'ವಿಸ್ತರಣೆ ಮತ್ತು ನಿರ್ಮಾಣ ಸಿದ್ಧಾಂತ', knSummary: 'ಧನಾತ್ಮಕ ಭಾವನೆಗಳು ಸೃಜನಶೀಲತೆ ಮತ್ತು ಆಲೋಚನಾ ಶಕ್ತಿಯನ್ನು ಹೇಗೆ ವಿಸ್ತರಿಸುತ್ತವೆ.', knTakeaways: ['ಧನಾತ್ಮಕತೆ ಚಿಂತನೆಯನ್ನು ವಿಸ್ತರಿಸುತ್ತದೆ', 'ಒತ್ತಡ ಆಲೋಚನೆಯನ್ನು ಕುಗ್ಗಿಸುತ್ತದೆ', 'ಸಂತೋಷವು ಸಾಮರ್ಥ್ಯ ಹೆಚ್ಚಿಸುತ್ತದೆ'],
    mlTitle: 'ബ്രോഡൻ ആൻഡ് ബിൽഡ് സിദ്ധാന്തം', mlSummary: 'സകാരാത്മക വികാരങ്ങൾ സർഗ്ഗാത്മകതയും ചിന്താശേഷിയും എങ്ങനെ വികസിപ്പിക്കുന്നു.', mlTakeaways: ['പോസിറ്റീവ് ചിന്ത കാഴ്ചപ്പാട് വികസിപ്പിക്കുന്നു', 'സമ്മർദ്ദം ചിന്തയെ ഇടുങ്ങിയതാക്കുന്നു', 'സന്തോഷം പുതിയ സാധ്യതകൾ തുറക്കുന്നു'],
    bnTitle: 'ব্রডন অ্যান্ড বিল্ড তত্ত্ব', bnSummary: 'ইতিবাচক আবেগ কীভাবে মানুষের দৃষ্টিভঙ্গি প্রসারিত করে এবং সৃজনশীলতা বাড়ায়।', bnTakeaways: ['ইতিবাচকতা চিন্তা বাড়ায়', 'মানসিক চাপ দৃষ্টিভঙ্গি সংকীর্ণ করে', 'আনন্দ নতুন শক্তি জোগায়'],
    paTitle: 'ਵਿਸਤਾਰ ਅਤੇ ਨਿਰਮਾਣ ਸਿਧਾਂਤ', paSummary: 'ਸਕਾਰਾਤਮਕ ਭਾਵਨਾਵਾਂ ਕਿਵੇਂ ਸੋਚਣ ਦੇ ਦਾਇਰੇ ਅਤੇ ਰਚਨਾਤਮਕਤਾ ਵਿੱਚ ਵਾਧਾ ਕਰਦੀਆਂ ਹਨ।', paTakeaways: ['ਸਕਾਰਾਤਮਕਤਾ ਸੋਚ ਨੂੰ ਖੁੱਲ੍ਹਾ ਕਰਦੀ ਹੈ', 'ਤਣਾਅ ਸੋਚ ਨੂੰ ਤੰਗ ਕਰਦਾ ਹੈ', 'ਖੁਸ਼ੀ ਨਵੇਂ ਰਾਹ ਖੋਲ੍ਹਦੀ ਹੈ'],
    urTitle: 'وسعت اور تعمیر کا نظریہ (Broaden-and-Build)', urSummary: 'مثبت جذبات کس طرح سوچ کی وسعت اور تخلیقی صلاحیتوں کو پروان چڑھاتے ہیں۔', urTakeaways: ['مثبت سوچ دائرہ کار وسیع کرتی ہے', 'تناؤ سوچ کو محدود کرتا ہے', 'خوشی نئی صلاحیتوں کو جنم دیتی ہے'],
    orTitle: 'ବିସ୍ତାର ଓ ନିର୍ମାଣ ତତ୍ତ୍ୱ', orSummary: 'ସକାରାତ୍ମକ ଭାବନା କିପରି ଚିନ୍ତାଧାରା ଓ ସୃଜନଶୀଳତାକୁ ପ୍ରସାରିତ କରେ।', orTakeaways: ['ସକାରାତ୍ମକତା ଦୃଷ୍ଟିକୋଣ ବଢ଼ାଏ', 'ଚାପ ଚିନ୍ତାକୁ ସୀମିତ କରେ', 'ଆନନ୍ଦ ନୂଆ ସାମର୍ଥ୍ୟ ଗଢ଼େ'],
    asTitle: 'সম্প্ৰসাৰণ আৰু নিৰ্মাণ তত্ত্ব', asSummary: 'ইতিবাচক আৱেগে কেনেকৈ মানুহৰ চিন্তাৰ পৰিসৰ আৰু সৃষ্টিশীলতা বৃদ্ধি কৰে।', asTakeaways: ['ইতিবাচকতাই দৃষ্টি বহল কৰে', 'উদ্বেগে চিন্তাক সীমিত কৰে', 'আনন্দে নতুন শক্তি যোগায়']
  },

  {
    fileName: 'emotionalGranularity.ts',
    varName: 'emotional_granularity',
    id: 'emotional_granularity',
    categoryId: 'emotions',
    slug: 'emotional-granularity',
    difficulty: 'intermediate',
    readTime: 5,
    sortWeight: 9,
    titleEn: 'Emotional Granularity: Why Naming Nuanced Feelings Calms the Brain',
    subtitleEn: 'Lisa Feldman Barrett’s theory of constructed emotion and the neural calming effect of precise emotional vocabulary.',
    shortDescEn: 'The ability to construct and differentiate specific, nuanced emotional experiences rather than lumping feelings into generic categories like "bad" or "stressed".',
    oneLineEn: 'Moving from "I feel terrible" to "I feel professionally discredited and envious."',
    summary30sEn: 'Neuroscientist Lisa Feldman Barrett discovered that individuals with high emotional granularity experience less physical distress, drink less under stress, and recover from trauma faster. Pinpointing exact feelings allows the brain to select targeted behavioral remedies rather than firing generic panic alarms.',
    coreConceptEn: 'Emotions are not hardwired circuits triggered passively; they are concepts constructed in real-time by the brain using interoceptive sensations and linguistic concepts. When you label an ambiguous chest tightness as "indignant frustration" rather than generic "anger", your brain constructs a precise action plan, reducing autonomic arousal.',
    summary60sEn: 'When people say "I am stressed," the brain treats it as a massive, undefined emergency. But if you differentiate that stress into "I am feeling time-pressured because of a deadline" vs. "I am feeling socially rejected because of an email", the prefrontal cortex immediately engages targeted coping strategies. Granularity reduces the metabolic cost of emotion regulation.',
    takeawaysEn: [
      'Generic emotional labels ("bad", "stressed", "fine") amplify autonomic anxiety',
      'Precise vocabulary ("chagrined", "wistful", "overwhelmed", "resentful") calms the amygdala',
      'People with high granularity require 40% less medication and self-medicate less with alcohol',
      'Expanding your emotional vocabulary directly upgrades your emotional regulation power'
    ],
    whyItHappensEn: 'Linguistic concepts allow the brain to categorize sensory inputs efficiently, reducing neural prediction errors and metabolic strain.',
    evolutionaryEn: 'Complex social alliances required nuanced emotional signaling and targeted behavioral calibration rather than crude binary fight-or-flight reactions.',
    howItWorksEn: 'Body experiences high arousal -> Brain searches conceptual dictionary -> Low granularity defaults to "I feel bad" -> Panic escalates -> High granularity selects "I feel professional envy" -> Constructive solution chosen.',
    visualHeadlineEn: 'Generic Distress vs. Granular Emotional Precision',
    visualDescEn: 'How linguistic precision guides prefrontal regulation of physiological arousal.',
    sideALabelEn: 'Low Granularity (Blunt Categorization)',
    sideADetailEn: '"I feel completely awful and stressed out!" -> Brain has no specific fix -> Free-floating panic.',
    sideBLabelEn: 'High Granularity (Precision Labeling)',
    sideBDetailEn: '"I feel humiliated that my junior was promoted before me." -> Brain recognizes specific issue -> Constructive action plan formed.',
    researchSummaryEn: 'Barrett et al. (2001, JPSP) and Kashdan et al. (2015, Current Directions in Psychological Science) demonstrated that high emotional granularity buffers against clinical depression, impulsive aggression, and somatic illness.',
    refAuthor: 'Barrett, L. F., Gross, J., Christensen, T. C., & Benvenuto, M.',
    refYear: 2001,
    refTitle: 'Knowing What You\'re Feeling and Knowing What to Do About It',
    refCitation: 'Barrett, L. F., et al. (2001). Journal of Personality and Social Psychology, 81(4), 713–725.',
    refDoi: 'https://doi.org/10.1037/0022-3514.81.4.713',
    scenarioTitleEn: 'The Vague "Depression" in a Mumbai Agency',
    scenarioContextEn: 'Kunal, a copywriter in Mumbai, felt a heavy grey fog every Sunday evening, which he labeled "chronic depression". Working with a cognitive therapist, he dissected the fog: it wasn’t sadness, but a mix of boredom with routine ads, resentment toward his micro-managing director, and dread of a 90-minute commute.',
    scenarioBiasEn: 'Kunal had low emotional granularity, lumping complex situational dissatisfactions into a medicalized global label ("depression") which left him feeling helpless.',
    scenarioOptimalEn: 'By distinguishing between boredom, resentment, and commute exhaustion, Kunal negotiated a hybrid schedule and pitched creative experimental campaigns, resolving the issue.',
    scenarioReflectionEn: 'When you tell someone you are "stressed", what are the three distinct emotional ingredients actually brewing beneath that word?',
    howToRecognizeEn: 'Notice when you default to generic one-word summaries ("angry", "upset", "stressed", "okay") instead of articulating specific nuanced feelings.',
    whereEn: 'Therapy, couple disputes, workplace burnout, and parenting young children.',
    misconceptionsEn: 'Myth: "Emotional granularity is just academic semantics." Fact: Brain imaging shows that precise labeling shifts blood flow from the amygdala to the ventrolateral prefrontal cortex in real time.',
    limitationsEn: 'Over-intellectualizing emotions without allowing oneself to feel the bodily sensations can lead to emotional detachment.',
    howToRespondEn: 'Use an Emotion Wheel: when upset, identify at least 3 precise words from tertiary emotional vocabularies (e.g. vulnerable, exasperated, alienated, sheepish) before reacting.',
    defensesEn: [
      { title: 'The 3-Word Dissection', instruction: 'Never describe your negative state with just "stressed" or "bad"; write down 3 specific, granular emotions behind the feeling.' },
      { title: 'The Bodily Location Anchor', instruction: 'Match the specific word to the physical location: is the sensation in your throat, stomach, or shoulders?' }
    ],
    pqPromptEn: 'An employee complains: "I am feeling totally stressed and anxious about tomorrow’s meeting." According to emotional granularity science, what is the best first step?',
    pqScenarioEn: 'The employee feels overwhelmed and cannot focus on writing their presentation slides.',
    pqExplanationEn: 'Differentiating the generic "stress" into specific granular components (e.g. fear of public speaking vs. lack of data) enables the brain to choose targeted solutions.',
    pqAntidoteEn: 'Dissect the generic emotional label into specific nuanced feelings and address each individually.',
    pqOptionsEn: [
      { id: 'opt_a', text: 'Drink a double espresso and try to suppress all thoughts about the meeting.', isCorrect: false, feedback: 'Incorrect. Caffeine increases autonomic arousal and suppression backfires.' },
      { id: 'opt_b', text: 'Break down "stressed" into precise emotions: Are you unprepared, afraid of judgment, or resentful of the assignment?', isCorrect: true, feedback: 'Correct! Granular emotional labeling directly lowers amygdala arousal and guides action.' },
      { id: 'opt_c', text: 'Call in sick to avoid the feeling completely.', isCorrect: false, feedback: 'Incorrect. Avoidance reinforces emotional vulnerability.' }
    ],
    reflectionPromptEn: 'What is a specific emotion you felt this week that doesn’t have a simple English name, but you can describe vividly?',
    titleHinglish: 'Emotional Granularity: Feelings Ko Sahi Naam Dene Ki Taqat',
    subtitleHinglish: 'Kyu sirf "stress" ya "gussa" bolne ke bajaye specific feeling pehchanna dimaag ko shaant karta hai.',
    shortDescHinglish: 'Lisa Feldman Barrett ki neuroscience research: Apni feelings ko bariki se naam dena anxiety ko 40% kam kar deta hai.',
    oneLineHinglish: '"Main pareshan hu" se hatkar "Mujhe jealousy aur insecurity ho rahi hai" bolna.',
    summary30sHinglish: 'Jab hum bolte hain "Mujhe bohot stress ho raha hai", to dimaag use ek anjana disaster samajh kar alert ho jata hai. Lekin jab hum exactly bolte hain ki "Mujhe rejection ka darr lag raha hai", to dimaag ka logic center turant control me aa jata hai.',
    coreConceptHinglish: 'Dimaag emotions ko banata hai. Agar aapke paas emotions ke liye sirf 3 lafz hain (achha, bura, gussa), to dimaag dhang se react nahi kar pata. Emotional dictionary jitni rich hogi, emotional intelligence utni high hogi.',
    summary60sHinglish: 'Research dikhati hai ki jo log apni feelings ko bariki se pehchan lete hain (jaise: jalan, sharm, thakan, anjaan darr), wo sharab ya over-eating kam karte hain aur depression se jaldi nikalte hain. Apni feeling ko exact naam dena dimaag ki medicine hai.',
    howItWorksHinglish: 'Sharir me bechaini hui -> Agar bola "main pareshan hu" to panic badhega -> Agar bola "mujhe insult feel hui hai" to solution dikhega -> Amygdala shaant ho jayega.',
    howToRespondHinglish: 'Emotion Wheel ka use karein: Sirf "bura lag raha hai" mat bolo, dhoondo ki andar guilt hai, helplessness hai, ya regret hai.',
    takeawaysHinglish: [
      'Generic words ("stress", "tension") dimaag me free-floating anxiety badhate hain',
      'Feelings ko exact naam dene se dimaag ka amygdala turant shaant hota hai',
      'High emotional granularity wale log depression aur gusse par zyada control rakhte hain',
      'Apni vocabulary me naye emotional lafz jodiye taaki dimaag unhe process kar sake'
    ],
    pqPromptHinglish: 'Ek friend bolta hai: "Mujhe office se aane ke baad bohot ganda stress ho raha hai." Emotional granularity ke hisab se kya advise denge?',
    pqExplanationHinglish: 'Jab tak stress ke andar ki exact feelings (thakan, boss par gussa, boring kaam) alag nahi hongi, solution nahi milega.',
    pqOptionsHinglish: [
      { id: 'opt_a', text: 'Bolna ki chup chap so jao aur sochna band karo.', isCorrect: false, feedback: 'Galat. Yeh suppression hai.' },
      { id: 'opt_b', text: 'Usse poochna ki exact kya feel ho raha hai: Kya kaam zyada tha, beizzati hui, ya akelepan lag raha hai?', isCorrect: true, feedback: 'Sahi! Specific labeling dimaag ko problem solve karne me help karti hai.' },
      { id: 'opt_c', text: 'Usse turant naukri chhodne ki salah dena.', isCorrect: false, feedback: 'Galat. Yeh impulsive advice hai.' }
    ],
    hiTitle: 'भावनात्मक सूक्ष्मता (Emotional Granularity)',
    hiSummary: 'भावनाओं को सटीक और सूक्ष्म नाम देने की क्षमता कैसे मस्तिष्क को शांत करती है और निर्णय क्षमता सुधारती है।',
    hiTakeaways: ['भावनाओं को सटीक नाम देना तनाव कम करता है', 'सामान्य शब्द चिंता को बढ़ाते हैं', 'सूक्ष्म समझ बेहतर समाधान देती है'],
    guTitle: 'લાગણીઓની સૂક્ષ્મતા (Emotional Granularity)', guSummary: 'લાગણીઓને ચોક્કસ શબ્દોમાં ઓળખવાની ક્ષમતા માનસિક શાંતિ આપે છે.', guTakeaways: ['લાગણીઓને ચોક્કસ નામ આપો', 'સામાન્ય શબ્દો ચિંતા વધારે છે', 'સૂક્ષ્મ સમજ નિયંત્રણ આપે છે'],
    mrTitle: 'भावनिक सूक्ष्मता (Emotional Granularity)', mrSummary: 'भावनांना अचूक आणि सूक्ष्म शब्दांत ओळखल्याने मेंदू कसा शांत होतो.', mrTakeaways: ['भावना अचूक ओळखा', 'सामान्य शब्दांमुळे गोंधळ वाढतो', 'योग्य शब्दांमुळे ताण कमी होतो'],
    teTitle: 'భావోద్వేగ సూక్ష్మత (Emotional Granularity)', teSummary: 'భావోద్వేగాలను స్పష్టమైన పదాలతో గుర్తించడం ద్వారా మనస్సును ఎలా ప్రశాంతపరచవచ్చు.', teTakeaways: ['భావాలను స్పష్టంగా గుర్తించండి', 'అస్పష్టమైన పదాలు ఆందోళన పెంచుతాయి', 'సూక్ష్మ గ్రహణశక్తి శాంతినిస్తుంది'],
    taTitle: 'உணர்ச்சி துல்லியம் (Emotional Granularity)', taSummary: 'உணர்ச்சிகளை துல்லியமான பெயரிட்டு அழைப்பது மூளையை எவ்வாறு அமைதிப்படுத்துகிறது.', taTakeaways: ['உணர்ச்சிகளை துல்லியமாக பெயரிடுங்கள்', 'பொதுவான வார்த்தைகள் பதற்றத்தை கூட்டும்', 'தெளிவான உணர்வு அமைதி தரும்'],
    knTitle: 'ಭಾವನಾತ್ಮಕ ಸೂಕ್ಷ್ಮತೆ (Emotional Granularity)', knSummary: 'ಭಾವನೆಗಳನ್ನು ನಿಖರವಾಗಿ ಗುರುತಿಸುವುದು ಮೆದುಳನ್ನು ಹೇಗೆ ಶಾಂತಗೊಳಿಸುತ್ತದೆ.', knTakeaways: ['ಭಾವನೆಗಳನ್ನು ನಿಖರವಾಗಿ ಹೆಸರಿಸಿ', 'ಅಸ್ಪಷ್ಟತೆ ಆತಂಕ ಹೆಚ್ಚಿಸುತ್ತದೆ', 'ಸೂಕ್ಷ್ಮ ತಿಳುವಳಿಕೆ ನೆಮ್ಮದಿ ನೀಡುತ್ತದೆ'],
    mlTitle: 'വൈകാരിക സൂക്ഷ്മത (Emotional Granularity)', mlSummary: 'വികാരങ്ങൾക്ക് കൃത്യമായ പേര് നൽകുന്നത് മസ്തിഷ്കത്തെ എങ്ങനെ ശാന്തമാക്കുന്നു.', mlTakeaways: ['വികാരങ്ങളെ കൃത്യമായി തിരിച്ചറിയുക', 'അവ്യക്തത ഉത്കണ്ഠ കൂട്ടുന്നു', 'വ്യക്തമായ വിചാരങ്ങൾ സമാധാനം നൽകുന്നു'],
    bnTitle: 'মানসিক সূক্ষ্মতা (Emotional Granularity)', bnSummary: 'আবেগকে সুনির্দিষ্টভাবে চিহ্নিত করার ক্ষমতা কীভাবে মানসিক উদ্বেগ কমায়।', bnTakeaways: ['আবেগকে সুনির্দিষ্ট নাম দিন', 'অস্পষ্ট শব্দ দুশ্চিন্তা বাড়ায়', 'সঠিক উপলব্ধি প্রশান্তি আনে'],
    paTitle: 'ਭਾਵਨਾਤਮਕ ਸੂਖਮਤਾ (Emotional Granularity)', paSummary: 'ਭਾਵਨਾਵਾਂ ਨੂੰ ਸਹੀ ਸ਼ਬਦਾਂ ਵਿੱਚ ਪਛਾਣਨ ਨਾਲ ਦਿਮਾਗ ਕਿਵੇਂ ਸ਼ਾਂਤ ਹੁੰਦਾ ਹੈ।', paTakeaways: ['ਭਾਵਨਾਵਾਂ ਨੂੰ ਸਹੀ ਨਾਂ ਦਿਓ', 'ਅਸਪਸ਼ਟਤਾ ਚਿੰਤਾ ਵਧਾਉਂਦੀ ਹੈ', 'ਸਹੀ ਪਛਾਣ ਸਕੂਨ ਦਿੰਦੀ ਹੈ'],
    urTitle: 'جذباتی باریکی (Emotional Granularity)', urSummary: 'جذبات کو درست اور باریک بینی سے نام دینا دماغ کو کس طرح پرسکون کرتا ہے۔', urTakeaways: ['جذبات کو واضح نام دیں', 'مبہم الفاظ اضطراب بڑھاتے ہیں', 'درست فہم سکون دیتی ہے'],
    orTitle: 'ଭାବନାଗତ ସୂକ୍ଷ୍ମତା (Emotional Granularity)', orSummary: 'ଭାବନାକୁ ସଠିକ୍ ଭାବରେ ଚିହ୍ନଟ କରିବା ମସ୍ତିଷ୍କକୁ କିପରି ଶାନ୍ତ ରଖେ।', orTakeaways: ['ଭାବନାକୁ ସଠିକ୍ ନାମ ଦିଅନ୍ତୁ', 'ଅସ୍ପଷ୍ଟତା ଚିନ୍ତା ବଢ଼ାଏ', 'ସୂକ୍ଷ୍ମ ବୁଝାମଣା ଶାନ୍ତି ଦିଏ'],
    asTitle: 'আৱেগিক সূক্ষ্মতা (Emotional Granularity)', asSummary: 'আৱেগক সঠিকভাৱে নামকৰণ কৰাৰ ক্ষমতাই কেনেকৈ মগজুক শান্ত কৰে।', asTakeaways: ['আৱেগক স্পষ্ট নাম দিয়ক', 'অস্পষ্টতাই উদ্বেগ বৃদ্ধি কৰে', 'সঠিক উপলব্ধিয়ে শান্তি আনে']
  },

  {
    fileName: 'expressiveSuppressionParadox.ts',
    varName: 'expressive_suppression_paradox',
    id: 'expressive_suppression_paradox',
    categoryId: 'emotions',
    slug: 'expressive-suppression-paradox',
    difficulty: 'intermediate',
    readTime: 5,
    sortWeight: 10,
    titleEn: 'The Expressive Suppression Paradox: The Hidden Cost of Bottling Up',
    subtitleEn: 'James Gross’s emotion regulation research on why hiding outward feelings spikes internal physiological stress.',
    shortDescEn: 'The paradoxical finding that trying to conceal outward signs of emotion does not decrease emotional experience, but drastically increases cardiovascular strain and impairs memory.',
    oneLineEn: 'Hiding your feelings from others doubles your internal heart rate and blood pressure.',
    summary30sEn: 'Psychologist James Gross discovered that when individuals force a "poker face" during distressing events, their sympathetic nervous system goes into overdrive: heart rate accelerates, vasoconstriction increases, and working memory deteriorates, even while they look perfectly calm on the outside.',
    coreConceptEn: 'Emotion regulation occurs across a temporal timeline: antecedent-focused regulation (like cognitive reappraisal) changes the emotional trajectory before it peaks, while response-focused suppression attempts to stifle the physical expression after the feeling has already erupted in the nervous system.',
    summary60sEn: 'Suppressing an emotional reaction requires constant, active prefrontal inhibition. This cognitive effort consumes working memory resources, meaning that while suppressing emotion during a tough conversation, you actually remember significantly less of what was said. Furthermore, conversational partners register your suppression through unconscious mirror-neuron cues, causing their own blood pressure to spike.',
    takeawaysEn: [
      'Bottling up emotions does not reduce internal distress; it multiplies cardiovascular strain',
      'Suppressing emotions consumes working memory, causing memory gaps of difficult events',
      'Other people subconsciously detect suppression, triggering anxiety in your conversational partner',
      'Cognitive reappraisal (changing the interpretation) cools the body without any suppression costs'
    ],
    whyItHappensEn: 'Inhibition requires continuous metabolic prefrontal energy to overpower autonomic motor and facial expressions.',
    evolutionaryEn: 'Hiding fear or weakness in the presence of dominant predators or hostile rivals avoided attacks, but was only intended for brief tactical emergencies.',
    howItWorksEn: 'Emotional event occurs -> Autonomic reaction begins -> Conscious motor inhibition clamps facial muscles -> Prefrontal cortex burns metabolic glucose -> Heart rate and blood pressure soar -> Cognitive performance drops.',
    visualHeadlineEn: 'Cognitive Reappraisal vs. Expressive Suppression',
    visualDescEn: 'Gross’s Process Model of Emotion Regulation comparing antecedent vs. response modulation.',
    sideALabelEn: 'Cognitive Reappraisal (Antecedent-Focused)',
    sideADetailEn: 'Reframes meaning early: "They are stressed, not malicious." Heart rate stays calm, memory intact.',
    sideBLabelEn: 'Expressive Suppression (Response-Focused)',
    sideBDetailEn: 'Clamps poker face on the outside: Heart rate spikes 20 bpm, internal cortisol surges, memory fails.',
    researchSummaryEn: 'Gross & John (2003, JPSP) and Gross (1998, Review of General Psychology) proved that habitual suppressors experience less positive emotion, greater depressive symptoms, and lower relationship satisfaction.',
    refAuthor: 'Gross, J. J. & John, O. P.',
    refYear: 2003,
    refTitle: 'Individual Differences in Two Emotion Regulation Processes',
    refCitation: 'Gross, J. J., & John, O. P. (2003). Journal of Personality and Social Psychology, 85(2), 348–362.',
    refDoi: 'https://doi.org/10.1037/0022-3514.85.2.348',
    scenarioTitleEn: 'The Silent Poker Face in Chennai',
    scenarioContextEn: 'Anand, a software team lead in Chennai, prided himself on never showing anger. When his manager publicly assigned his promised project to someone else, Anand kept a stone-cold smile. By evening, he had a splitting migraine, elevated blood pressure of 145/95, and couldn\'t recall what his team briefed him on that afternoon.',
    scenarioBiasEn: 'Anand practiced extreme expressive suppression: he successfully masked his facial expression, but his body bore the full metabolic punishment of the inhibited rage.',
    scenarioOptimalEn: 'Practice measured verbal expression or reappraisal: "I need to share that I feel surprised and concerned about this decision. Let\'s schedule 15 minutes to discuss the transition."',
    scenarioReflectionEn: 'Have you ever maintained a fake smile through a humiliating situation, only to feel utterly exhausted, drained, and headache-ridden hours later?',
    howToRecognizeEn: 'Clamping your lips, holding your breath, freezing your facial muscles, and feeling a rising pounding sensation in your chest while trying to look unaffected.',
    whereEn: 'Corporate hierarchy politics, family gatherings with in-laws, customer service interactions, and formal ceremonies.',
    misconceptionsEn: 'Myth: "Maturity means having a poker face at all times." Fact: Constant emotional suppression leads to chronic hypertension, burnout, and social alienation.',
    limitationsEn: 'Brief suppression in front of an aggressive stranger or in a courtroom can be tactically protective, but as a permanent lifestyle it is toxic.',
    howToRespondEn: 'Shift from Suppression to Reappraisal: instead of trying not to look angry, change what the event means in your head, or express your boundary in calm, articulate words.',
    defensesEn: [
      { title: 'The De-escalation Articulation', instruction: 'Do not hide anger; verbalize it neutrally: "I am feeling frustrated by this change, so I need a moment before we continue."' },
      { title: 'Post-Event Somatic Discharge', instruction: 'If you had to suppress feelings during a formal meeting, take a brisk 10-minute walk or do deep exhales right after to discharge cardiovascular pressure.' }
    ],
    pqPromptEn: 'During a heated salary review, an executive forces a calm smile while feeling intense indignation. According to Gross’s research, what is happening physiologically?',
    pqScenarioEn: 'The executive looks composed to the board, but feels internally strained.',
    pqExplanationEn: 'Expressive suppression prevents facial movement but causes sympathetic nervous system hyperactivation, elevating blood pressure and impairing memory.',
    pqAntidoteEn: 'Use cognitive reappraisal or calm verbal assertion rather than physical expressive inhibition.',
    pqOptionsEn: [
      { id: 'opt_a', text: 'Their heart rate and blood pressure are dropping because smiling tricks the brain into calmness.', isCorrect: false, feedback: 'Incorrect. Forcing a fake smile while angry significantly increases cardiovascular strain.' },
      { id: 'opt_b', text: 'Their cardiovascular arousal is spiking and their working memory of the conversation is deteriorating.', isCorrect: true, feedback: 'Correct! Expressive suppression imposes severe physiological and cognitive costs.' },
      { id: 'opt_c', text: 'Their emotional experience has completely vanished.', isCorrect: false, feedback: 'Incorrect. The feeling remains fully active inside.' }
    ],
    reflectionPromptEn: 'Who in your life do you feel safe enough around to express authentic vulnerability without having to wear a protective mask?',
    titleHinglish: 'Expressive Suppression Paradox: Gussa Dabane Ka Bhaari Nuqsaan',
    subtitleHinglish: 'Kyu jazbaat chupana aur "poker face" banana andar se BP aur heart rate badha deta hai.',
    shortDescHinglish: 'James Gross ki research: Jazbaat ko dabane se dukh kam nahi hota, balki sharir par do guna load padta hai.',
    oneLineHinglish: 'Bahar se shaant dikhna, par andar se blood pressure ka aasmaan chhoona.',
    summary30sHinglish: 'Log samajhte hain ki gussa ya dukh chupana mature hone ki nishani hai. Lekin psychologist James Gross ne prove kiya ki jab hum chehre par jhoothi muskaan rakhte hain, to hamara heart rate 20 bpm badh jata hai aur dimaag ki memory kamzor ho jati hai.',
    coreConceptHinglish: 'Emotion regulation do tareeqe se hota hai: Ya to baat ko dekhne ka nazariya badal lo (reappraisal), ya fir chehre par emotion mat aane do (suppression). Chehre par emotion dabana sharir ko heart disease aur migraine ki taraf le jata hai.',
    summary60sHinglish: 'Jab aap boss ya rishtedaar ke samne gussa daba kar smile karte hain, to dimaag ko facial muscles rokne me itni energy lagti hai ki aapki yaad-daasht kamzor ho jati hai. Samne wale ko bhi subconscious tor par lag jata hai ki kuch fake hai.',
    howItWorksHinglish: 'Gussa aaya -> Zabardasti smile banayi -> Prefrontal cortex ne muscles ko lock kiya -> Dil ki dhadkan aur cortisol badha -> Shaam ko headache aur exhaustion hua.',
    howToRespondHinglish: 'Gussa dabao mat, balki calmly bol do: "Mujhe yeh sun kar bura laga, hum ispe baad me baat karte hain." Aur meeting ke baad tezz walk karke physical tension nikaal do.',
    takeawaysHinglish: [
      'Feelings dabane se wo khatam nahi hoti, balki blood pressure badha deti hain',
      'Poker face maintain karne me dimaag ki memory aur focus kharab hota hai',
      'Samne wale ko aapki fakeness subconscious tor par detect ho jati hai',
      'Nazariya badalna (Reappraisal) gussa dabane se 100 guna behtar hai'
    ],
    pqPromptHinglish: 'Office me boss ne bina baat ke daanta. Aapne fake smile karke "Yes sir" bola par andar se aag lag rahi hai. Research ke mutabiq aapke sharir me kya ho raha hai?',
    pqExplanationHinglish: 'Expressive suppression se heart rate aur stress hormones tezi se badhte hain, jabki bahar sab normal lagta hai.',
    pqOptionsHinglish: [
      { id: 'opt_a', text: 'Aapka dimaag bilkul shant ho gaya hai kyuki smile karne se gussa gayab ho jata hai.', isCorrect: false, feedback: 'Galat. Yeh dangerous myth hai.' },
      { id: 'opt_b', text: 'Aapka blood pressure aur heart rate spike ho raha hai aur dimaag thak raha hai.', isCorrect: true, feedback: 'Sahi! Gussa dabane ka physical cost bohot high hota hai.' },
      { id: 'opt_c', text: 'Aapki memory aur tez ho jayegi.', isCorrect: false, feedback: 'Galat. Memory kharab hoti hai.' }
    ],
    hiTitle: 'अभिव्यक्ति दमन विरोधाभास (Expressive Suppression)',
    hiSummary: 'भावनाओं को दबाने और छिपाने से आंतरिक शारीरिक तनाव, रक्तचाप और मानसिक थकान कैसे बढ़ती है।',
    hiTakeaways: ['भावनाओं को दबाना हृदय संबंधी तनाव बढ़ाता है', 'दमन से स्मरण शक्ति कमजोर होती है', 'विचार बदलना दमन से अधिक प्रभावी है'],
    guTitle: 'લાગણી દબાવવાનો વિરોધાભાસ', guSummary: 'લાગણીઓ છુપાવવાથી શરીરનું બ્લડ પ્રેશર અને તણાવ કેવી રીતે બમણો થાય છે.', guTakeaways: ['લાગણી દબાવશો નહીં', 'ખોટો ચહેરો તણાવ વધારે છે', 'વિચારો બદલવા વધુ હિતાવહ છે'],
    mrTitle: 'भावना दडपण्याचा विरोधाभास', mrSummary: 'भावना मनातल्या मनात दाबून ठेवल्याने शरीरावर आणि रक्तदाबावर कसा गंभीर परिणाम होतो.', mrTakeaways: ['भावना दडपल्याने रक्तदाब वाढतो', 'दडपशाहीमुळे स्मरणशक्ती घटते', 'योग्य शब्दात भावना व्यक्त करा'],
    teTitle: 'భావోద్వేగ అణచివేత వైరుధ్యం', teSummary: 'భావాలను బలవంతంగా దాచడం వల్ల గుండెపోటు మరియు రక్తపోటు ప్రమాదం ఎలా పెరుగుతుంది.', teTakeaways: ['భావాలను అణచివేయవద్దు', 'కృత్రిమ ప్రశాంతత ఒత్తిడిని పెంచుతుంది', 'ఆలోచనా సరళిని మార్చడం శ్రేయస్కరం'],
    taTitle: 'உணர்ச்சி அடக்குமுறை முரண்பாடு', taSummary: 'உணர்வுகளை வெளியில் காட்டாமல் அடக்கி வைப்பது ரத்த அழுத்தத்தையும் மன அழுத்தத்தையும் எவ்வாறு இரட்டிப்பாக்குகிறது.', taTakeaways: ['உணர்வுகளை அடக்காதீர்கள்', 'போலி புன்னகை உடலை பாதிக்கும்', 'உண்மையை பக்குவமாக பேசுங்கள்'],
    knTitle: 'ಭಾವನೆ ನಿಗ್ರಹದ ವಿರೋಧಾಭಾಸ', knSummary: 'ಭಾವನೆಗಳನ್ನು ಅದುಮಿಟ್ಟುಕೊಳ್ಳುವುದರಿಂದ ರಕ್ತದೊತ್ತಡ ಮತ್ತು ದೈಹಿಕ ಆಯಾಸ ಹೇಗೆ ಹೆಚ್ಚುತ್ತದೆ.', knTakeaways: ['ಭಾವನೆಗಳನ್ನು ಅದುಮಬೇಡಿ', 'ಮುಖವಾಡ ಧರಿಸುವುದು ಆಯಾಸ ತರುತ್ತದೆ', 'ಸ್ಪಷ್ಟವಾಗಿ ಸಂವಹನ ನಡೆಸಿ'],
    mlTitle: 'വികാര അടിച്ചമർത്തൽ വൈരുദ്ധ്യം', mlSummary: 'വികാരങ്ങൾ പുറത്തു കാണിക്കാതെ ഉള്ളിലൊതുക്കുന്നത് രക്തസമ്മർദ്ദവും ആരോഗ്യപ്രശ്നങ്ങളും എങ്ങനെ വർദ്ധിപ്പിക്കുന്നു.', mlTakeaways: ['വികാരങ്ങൾ ഉള്ളിലൊതുക്കരുത്', 'വ്യാജ ശാന്തത അപകടമാണ്', 'ചിന്താഗതിയിൽ മാറ്റം വരുത്തുക'],
    bnTitle: 'আবেগ দমনের বৈপরীত্য', bnSummary: 'আবেগ চেপে রাখলে কীভাবে অভ্যন্তরীণ রক্তচাপ, হৃদস্পন্দন এবং মানসিক অবসাদ দ্বিগুণ হয়।', bnTakeaways: ['আবেগ চেপে রাখবেন না', 'মুখোশ পরা মানসিক চাপ বাড়ায়', 'খোলাখুলি কথা বলাই শ্রেয়'],
    paTitle: 'ਭਾਵਨਾਵਾਂ ਦਬਾਉਣ ਦਾ ਵਿਰੋਧਾਭਾਸ', paSummary: 'ਭਾਵਨਾਵਾਂ ਨੂੰ ਲੁਕਾਉਣ ਅਤੇ ਦਬਾਉਣ ਨਾਲ ਬਲੱਡ ਪ੍ਰੈਸ਼ਰ ਅਤੇ ਸਰੀਰਕ ਤਣਾਅ ਕਿਵੇਂ ਵਧਦਾ ਹੈ।', paTakeaways: ['ਭਾਵਨਾਵਾਂ ਨੂੰ ਦਬਾਓ ਨਾ', 'ਨਕਲੀ ਹਾਸਾ ਤਣਾਅ ਵਧਾਉਂਦਾ ਹੈ', 'ਸਹੀ ਤਰੀਕੇ ਨਾਲ ਪ੍ਰਗਟ ਕਰੋ'],
    urTitle: 'جذبات دبانے کا تضاد (Expressive Suppression)', urSummary: 'جذبات کو چھپانے اور دبانے سے بلڈ پریشر اور جسمانی تناؤ میں کس طرح اضافہ ہوتا ہے۔', urTakeaways: ['جذبات کو اندر نہ گھونٹیں', 'مصنوعی مسکراہٹ نقصان دہ ہے', 'سوچ کا رخ بدلنا بہتر ہے'],
    orTitle: 'ଭାବନା ଦମନର ବିରୋଧାଭାସ', orSummary: 'ଭାବନାକୁ ଚାପି ରଖିବା ଦ୍ୱାରା ରକ୍ତଚାପ ଓ ଆଭ୍ୟନ୍ତରୀଣ ଚାପ କିପରି ବୃଦ୍ଧି ପାଏ।', orTakeaways: ['ଭାବନାକୁ ଚାପି ରଖନ୍ତୁ ନାହିଁ', 'ନକଲି ଶାନ୍ତତା କ୍ଷତିକାରକ', 'ସ୍ୱାଭାବିକ ପ୍ରକାଶ ଶ୍ରେୟସ୍କର'],
    asTitle: 'আৱেগ দমনৰ বৈপৰীত্য', asSummary: 'আৱেগ লুকুৱাই ৰখাৰ ফলত শৰীৰৰ ৰক্তচাপ আৰু মানসিক চাপ কেনেকৈ দুগুণ বৃদ্ধি পায়।', asTakeaways: ['আৱেগক হেঁচি নাৰাখিব', 'কৃত্ৰিম শান্তভাৱে ক্ষতি কৰে', 'উপযুক্তভাৱে প্ৰকাশ কৰক']
  }
];
