import { ComprehensiveTopicDef } from '../topicGeneratorHelper';

export const LEARNING_TOPICS: ComprehensiveTopicDef[] = [
  {
    fileName: 'interleavingEffect.ts',
    varName: 'interleaving_effect',
    id: 'interleaving_effect',
    categoryId: 'learning_psychology',
    slug: 'interleaving-effect',
    difficulty: 'intermediate',
    readTime: 5,
    sortWeight: 5,
    titleEn: 'The Interleaving Effect: Mixing Skills for Deep Mastery',
    subtitleEn: 'Robert Bjork and Nate Kornell’s cognitive research on why blocked practice feels easier but interleaving wins the exam.',
    shortDescEn: 'A learning strategy where related topics, problem types, or motor skills are mixed together during study sessions rather than practiced in isolated blocks.',
    oneLineEn: 'Stop practicing AAA-BBB-CCC; train ABC-CAB-BCA to teach your brain discrimination.',
    summary30sEn: 'Discovered in motor learning by John Shea and expanded to cognitive education by UCLA psychologists Robert Bjork and Nate Kornell, interleaving challenges our intuition. When students practice one type of math problem or art style repeatedly ("blocked practice"), they feel confident. But on exams, interleaved learners outperform blocked learners by up to 43%!',
    coreConceptEn: 'Blocked practice gives an illusion of mastery because working memory keeps the solution formula loaded in active cache. You don’t have to identify *which* formula to use; you just execute. Interleaving forces the brain to repeatedly retrieve different schemas, teaching the critical metacognitive skill of *discriminating* between problem categories.',
    summary60sEn: 'While interleaving feels slower, clunky, and frustrating in the moment (a classic "desirable difficulty"), it builds durable synaptic pathways in long-term memory. It prepares students for real-world scenarios and high-stakes exams (like JEE, NEET, or UPSC) where problems never arrive in neatly labeled chapters.',
    takeawaysEn: [
      'Blocked practice creates an illusion of competence; interleaving produces actual mastery',
      'Interleaving forces the brain to identify which rule to apply, not just execute it',
      'Exams and real life are naturally interleaved, not segmented into neat chapters',
      'Embrace the frustrating friction of mixing topics; that difficulty is where learning happens'
    ],
    whyItHappensEn: 'Discriminative contrast: juxtaposing different categories highlights subtle distinguishing features that isolated review obscures.',
    evolutionaryEn: 'Hunters did not encounter tracks, weather changes, and predators in isolated blocks; ancestral survival demanded rapid shifting between perceptual categories.',
    howItWorksEn: 'Study Topic A -> Switch to Topic B before comfort sets in -> Brain forced to reload Topic B schema -> Switch to Topic C -> Brain compares contrasts -> Deep generalizable neural representations form.',
    visualHeadlineEn: 'Blocked Practice (Illusion) vs. Interleaving (Real Mastery)',
    visualDescEn: 'Kornell & Bjork’s learning retention comparison.',
    sideALabelEn: 'Blocked Practice (AAA-BBB-CCC)',
    sideADetailEn: 'Feels smooth during practice; rapid performance decline during delayed testing (38% exam accuracy).',
    sideBLabelEn: 'Interleaved Practice (ABC-BCA-CAB)',
    sideBDetailEn: 'Feels difficult and error-prone during study; massive long-term retention surge (77% exam accuracy).',
    researchSummaryEn: 'Kornell & Bjork (2008, Psychological Science) and Rohrer & Taylor (2007, Instructional Science) proved interleaved problem solving dramatically outperforms blocked problem solving on delayed tests.',
    refAuthor: 'Kornell, N. & Bjork, R. A.',
    refYear: 2008,
    refTitle: 'Learning Concepts and Categories: Is Spacing the "Enemy of Induction"?',
    refCitation: 'Kornell, N., & Bjork, R. A. (2008). Psychological Science, 19(6), 585–592.',
    refDoi: 'https://doi.org/10.1111/j.1467-9280.2008.02127.x',
    scenarioTitleEn: 'The JEE Physics Chapter Trap in Kota',
    scenarioContextEn: 'Aniket spent 3 weeks in Kota solving 200 consecutive kinematics problems. He scored 95% on chapter tests. But during the full-syllabus mock exam where kinematics, thermodynamics, and electromagnetism appeared randomly, he froze, unable to identify which formulas applied.',
    scenarioBiasEn: 'Aniket fell into the blocked practice trap: he mastered formula execution but never practiced formula discrimination.',
    scenarioOptimalEn: 'Shuffle problem sets: combine 5 mechanics, 5 optics, and 5 electrodynamics problems on index cards and draw them at random.',
    scenarioReflectionEn: 'When preparing for a presentation or test, do you repeatedly polish one section to perfection before moving to the next, or do you cycle through all areas?',
    howToRecognizeEn: 'Feeling very confident when doing 30 practice problems of the exact same type, followed by total confusion on cumulative practice exams.',
    whereEn: 'Competitive entrance exam preparation (JEE/NEET/UPSC), coding interview prep (LeetCode), musical instrument practice, and sports training.',
    misconceptionsEn: 'Myth: "Interleaving confuses beginners and ruins fundamentals." Fact: Once basic conceptual definitions are grasped, immediate interleaving accelerates conceptual boundary mapping.',
    limitationsEn: 'When learning a completely novel motor skill from zero (e.g. holding a violin bow for the first time), brief blocked practice is necessary before interleaving can begin.',
    howToRespondEn: 'The 3-Card Shuffle: Divide study time into 20-minute blocks covering three related but distinct subjects, alternating continuously.',
    defensesEn: [
      { title: 'The Problem Set Blender', instruction: 'Never do 50 problems from the same textbook chapter in one sitting; mix 10 problems from Chapter 1, 10 from Chapter 3, and 10 from Chapter 6.' },
      { title: 'The Flashcard Roulette', instruction: 'Shuffle flashcards from different subjects or modules together so your brain never knows what category is coming next.' }
    ],
    pqPromptEn: 'A tennis coach wants a student to master forehands, backhands, and volleys for tournament play. Which practice schedule will produce the highest match performance?',
    pqScenarioEn: 'The student has 60 minutes of court practice available.',
    pqExplanationEn: 'Interleaved random practice simulates real match conditions, forcing motor program retrieval on every shot, which yields superior transfer compared to blocked drills.',
    pqAntidoteEn: 'Distribute practice across randomized shot sequences rather than repetitive blocks.',
    pqOptionsEn: [
      { id: 'opt_a', text: '20 minutes of forehands only, followed by 20 minutes of backhands, then 20 minutes of volleys.', isCorrect: false, feedback: 'Incorrect. This blocked practice produces poor in-game adaptation.' },
      { id: 'opt_b', text: 'Randomly alternating forehands, backhands, and volleys with unpredictable ball feeds throughout the 60 minutes.', isCorrect: true, feedback: 'Correct! Interleaved motor training builds superior game-state retrieval.' },
      { id: 'opt_c', text: '60 minutes of only forehands until the motion is completely robotic.', isCorrect: false, feedback: 'Incorrect. This creates rigid, fragile motor habits.' }
    ],
    reflectionPromptEn: 'How can you redesign your current study or work routine to intentionally mix different categories of tasks instead of doing them in long monotonous blocks?',
    titleHinglish: 'The Interleaving Effect: Mix Karke Padhne Ka Jaadu',
    subtitleHinglish: 'Robert Bjork ki research: Ek hi chapter ke 100 questions karne se exam me marks kyu nahi aate.',
    shortDescHinglish: 'Blocked vs Interleaved learning: Alag-alag topics aur problem types ko mix karke padhne se dimaag formula pehchanna seekhta hai.',
    oneLineHinglish: 'AAA-BBB-CCC padhna asaan lagta hai, par exam me ABC-BCA-CAB padhne wala hi topper banta hai.',
    summary30sHinglish: 'UCLA ke professor Robert Bjork ne dekha ki jab students ek hi type ke 50 math problems karte hain (Blocked Practice), to unhe lagta hai "sab samajh aa gaya". Par exam me mix questions aate hi wo blank ho jate hain! Interleaving ka matlab hai 3 alag chapters ke questions mix karke solve karna.',
    coreConceptHinglish: 'Jab aap ek hi chapter ke questions karte ho, to dimaag ko sochna nahi padta ki kaunsa formula lagega; wo bina soche bas calculate karta hai. Jab questions mixed hote hain, to dimaag ko pehle "category pehchanni" padti hai. Is friction se dimaag me deep learning hoti hai.',
    summary60sHinglish: 'Kota me JEE aur NEET ke bacche yahi galti karte hain: Ek hafte tak sirf Kinematics karte hain aur test me 90% laate hain. Par jab full-syllabus mock exam hota hai to dimaag confuse ho jata hai. Interleaving shuru me mushkil aur irritating lagti hai, par exam ke din yahi rank dilati hai.',
    howItWorksHinglish: 'Topic A padha -> Jaise hi easy laga, Topic B par switch kiya -> Dimaag ne zor lagaya -> Topic C par gaye -> Dimaag ne teeno ke difference samjhe -> Permanent retention hua.',
    howToRespondHinglish: 'Shuffle karo: Homework karte waqt ek hi exercise ke 30 questions mat karo. Pichle 3 chapters ke 10-10 questions mix karke solve karo.',
    takeawaysHinglish: [
      'Ek hi topic baar-baar padhne se dimaag ko nakli confidence hota hai (Illusion of competence)',
      'Interleaving dimaag ko formula chunna sikhati hai, sirf ratna nahi',
      'Real exam aur real life hamesha mixed hoti hai, chapter-wise nahi',
      'Padhte waqt aane wali thodi si pareshani hi sachhi learning ka saboot hai'
    ],
    pqPromptHinglish: 'Exam ke liye revision karna hai: Plan A hai roz ek subject poora padhna (Monday Physics, Tuesday Chemistry). Plan B hai roz teeno subjects ke 2-2 ghante mix karke padhna. Best kaunsa hai?',
    pqExplanationHinglish: 'Plan B (Interleaving) dimaag ko concepts ke beech switch karne ki aadat dalta hai, jisse exam me retention 40% badh jata hai.',
    pqOptionsHinglish: [
      { id: 'opt_a', text: 'Plan A, kyuki ek subject par focus karne se flow banta hai.', isCorrect: false, feedback: 'Galat. Flow achha lagta hai par retention poor hota hai.' },
      { id: 'opt_b', text: 'Plan B, kyuki subjects ko mix karne se dimaag ki discrimination ability aur retention dono badhte hain.', isCorrect: true, feedback: 'Sahi! Yahi Interleaving Effect ka scientific basis hai.' },
      { id: 'opt_c', text: 'Padhai chhod kar sirf YouTube par strategy videos dekhna.', isCorrect: false, feedback: 'Galat. Yeh procrastination hai.' }
    ],
    hiTitle: 'मिश्रित अभ्यास प्रभाव (The Interleaving Effect)',
    hiSummary: 'एक ही विषय का लगातार अभ्यास करने के बजाय विभिन्न विषयों या समस्याओं को मिलाकर अध्ययन करने से होने वाली दीर्घकालिक स्मृति वृद्धि।',
    hiTakeaways: ['एकल विषय अभ्यास सीखने का झूठा आत्मविश्वास पैदा करता है', 'मिश्रित अभ्यास मस्तिष्क को सही नियम और सूत्र पहचानना सिखाता है', 'परीक्षा और वास्तविक जीवन स्वाभाविक रूप से मिश्रित होते हैं'],
    guTitle: 'ઇન્ટરલીવિંગ અસર (મિશ્રિત અભ્યાસનો પ્રભાવ)', guSummary: 'એક જ વિષયને બદલે જુદા જુદા પ્રકરણો ભેગા કરીને અભ્યાસ કરવાની વૈજ્ઞાનિક પદ્ધતિ.', guTakeaways: ['મિશ્રિત પ્રશ્નો સોલ્વ કરો', 'ખોટા આત્મવિશ્વાસથી બચો', 'વાસ્તવિક પરીક્ષા માટે તૈયાર થાઓ'],
    mrTitle: 'मिश्रित सराव प्रभाव (Interleaving Effect)', mrSummary: 'एकाच प्रकारच्या अभ्यासाऐवजी विविध विषयांचे प्रश्न एकत्र सोडवून मेंदूची आकलन क्षमता वाढवणे.', mrTakeaways: ['मिश्रित अभ्यास दीर्घकालीन फायद्याचा ठरतो', 'सूत्रांमधील फरक ओळखायला शिका', 'परीक्षेसाठी सर्वोत्तम पद्धत'],
    teTitle: 'ఇంటర్‌లీవింగ్ ప్రభావం (మిశ్రమ అభ్యాసం)', teSummary: 'ఒకే అంశాన్ని కాకుండా విభిన్న పాఠ్యాంశాలను కలిపి చదవడం వల్ల కలిగే దీర్ఘకాలిక జ్ఞాపకశక్తి.', teTakeaways: ['విభిన్న అంశాలను కలిపి సాధన చేయండి', 'తప్పుడు ఆత్మవిశ్వాసంలో పడవద్దు', 'పరీక్షలలో మెరుగైన ఫలితాలు పొందండి'],
    taTitle: 'கலப்பு பயிற்சி விளைவு (Interleaving Effect)', taSummary: 'ஒரே பாடத்தை தொடர்ந்து படிக்காமல் வெவ்வேறு பாடங்களை கலந்து படிப்பதால் ஏற்படும் ஆழமான புரிதல்.', taTakeaways: ['பாடங்களை கலந்து படியுங்கள்', 'போலி நம்பிக்கையை தவிருங்கள்', 'தேர்வுகளில் அதிக மதிப்பெண் பெறுங்கள்'],
    knTitle: 'ಮಿಶ್ರಿತ ಕಲಿಕೆಯ ಪರಿಣಾಮ (Interleaving Effect)', knSummary: 'ಒಂದೇ ವಿಷಯವನ್ನು ನಿರಂತರವಾಗಿ ಕಲಿಯುವ ಬದಲು ವಿಭಿನ್ನ ಅಧ್ಯಾಯಗಳನ್ನು ಬೆರೆಸಿ ಅಭ್ಯಾಸ ಮಾಡುವ ತಂತ್ರ.', knTakeaways: ['ಮಿಶ್ರಿತ ಪ್ರಶ್ನೆಗಳನ್ನು ಅಭ್ಯಾಸ ಮಾಡಿ', 'ನಕಲಿ ಆತ್ಮವಿಶ್ವಾಸದಿಂದ ದೂರವಿರಿ', 'ದೀರ್ಘಕಾಲಿಕ ನೆನಪಿಗೆ ಸಹಕಾರಿ'],
    mlTitle: 'ഇന്റർലീവിംഗ് പ്രഭാവം (മിശ്രിത പഠന രീതി)', mlSummary: 'ഒറ്റ വിഷയത്തിന് പകരം വ്യത്യസ്ത വിഷയങ്ങൾ ഇടകലർത്തി പഠിക്കുന്നതിലൂടെ ലഭിക്കുന്ന ദീർഘകാല ഓർമ്മശക്തി.', mlTakeaways: ['വിഷയങ്ങൾ ഇടകലർത്തി പഠിക്കുക', 'തെറ്റായ ആത്മവിശ്വാസം ഒഴിവാക്കുക', 'പരീക്ഷകളിൽ മികച്ച വിജയം നേടുക'],
    bnTitle: 'মিশ্রিত অনুশীলন প্রভাব (Interleaving Effect)', bnSummary: 'একটি নির্দিষ্ট বিষয় একনাগাড়ে না পড়ে বিভিন্ন অধ্যায় বা ধারণার সংমিশ্রণে অনুশীলনের বৈজ্ঞানিক সুফল।', bnTakeaways: ['অধ্যায় মিশিয়ে অনুশীলন করুন', 'ভ্রান্ত আত্মবিশ্বাস এড়িয়ে চলুন', 'পরীক্ষার জন্য আদর্শ প্রস্তুতি নিন'],
    paTitle: 'ਰਲਵਾਂ ਅਭਿਆਸ ਪ੍ਰਭਾਵ (Interleaving Effect)', paSummary: 'ਇੱਕੋ ਵਿਸ਼ੇ ਨੂੰ ਲਗਾਤਾਰ ਪੜ੍ਹਨ ਦੀ ਬਜਾਏ ਵੱਖ-ਵੱਖ ਪਾਠਾਂ ਨੂੰ ਮਿਲਾ ਕੇ ਪੜ੍ਹਨ ਦੀ ਵਿਗਿਆਨਕ ਵਿਧੀ।', paTakeaways: ['ਵੱਖ-ਵੱਖ ਵਿਸ਼ਿਆਂ ਦਾ ਰਲਵਾਂ ਅਭਿਆਸ ਕਰੋ', 'ਝੂਠੇ ਆਤਮਵਿਸ਼ਵਾਸ ਤੋਂ ਬਚੋ', 'ਇਮਤਿਹਾਨ ਲਈ ਬਿਹਤਰੀਨ ਢੰਗ'],
    urTitle: 'مخلوط مشق کا اثر (Interleaving Effect)', urSummary: 'ایک ہی سبق کو بار بار پڑھنے کے بجائے مختلف اسباق کو ملا کر مشق کرنے سے ذہن کا گہرا فہم۔', urTakeaways: ['اسباق کو ملا کر مشق کریں', 'جھوٹے اعتماد کے فریب سے بچیں', 'امتحانات میں دیرپا کامیابی پائیں'],
    orTitle: 'ମିଶ୍ରିତ ଅଭ୍ୟାସ ପ୍ରଭାବ (Interleaving Effect)', orSummary: 'ଗୋଟିଏ ବିଷୟ ଲଗାତାର ନପଢ଼ି ବିଭିନ୍ନ ଅଧ୍ୟାୟକୁ ମିଶାଇ ଅଭ୍ୟାସ କରିବାର ବୈଜ୍ଞାନିକ ଉପକାରିତା।', orTakeaways: ['ବିଭିନ୍ନ ବିଷୟ ମିଶାଇ ଅଭ୍ୟାସ କରନ୍ତୁ', 'ମିଥ୍ୟା ଆତ୍ମବିଶ୍ୱାସରୁ ଦୂରେଇ ରୁହନ୍ତୁ', 'ଦୀର୍ଘକାଳୀନ ସ୍ମୃତି ବୃଦ୍ଧି କରନ୍ତୁ'],
    asTitle: 'মিশ্ৰিত অনুশীলনৰ প্ৰভাৱ (Interleaving Effect)', asSummary: 'এটা বিষয় একেৰাহে নপঢ়ি বিভিন্ন বিষয় বা পাঠ মিহলাই অনুশীলন কৰাৰ বৈজ্ঞানিক ফলপ্ৰসূতা।', asTakeaways: ['বিষয়বোৰ মিহলাই পঢ়ক', 'ভ্ৰান্ত আত্মবিশ্বাস পৰিহাৰ কৰক', 'পৰীক্ষাৰ বাবে উপযুক্ত প্ৰস্তুতি লওক']
  },

  {
    fileName: 'generationEffect.ts',
    varName: 'generation_effect',
    id: 'generation_effect',
    categoryId: 'learning_psychology',
    slug: 'generation-effect',
    difficulty: 'beginner',
    readTime: 5,
    sortWeight: 6,
    titleEn: 'The Generation Effect: Active Production vs. Passive Consumption',
    subtitleEn: 'Norman Slamecka’s discovery on why generating answers produces vastly superior memory to reading them.',
    shortDescEn: 'The robust cognitive phenomenon where information is significantly better remembered if it is generated from one\'s own mind rather than simply read or heard.',
    oneLineEn: 'Your brain remembers what it builds, not what it passively looks at.',
    summary30sEn: 'Discovered in 1978 by Norman Slamecka and Peter Graf, the Generation Effect proves that reading a textbook, highlighting notes, and watching lecture videos are among the least effective ways to learn. In Slamecka’s experiments, subjects who had to fill in missing letters or generate antonyms recalled 300% more information than those who simply read the pairs.',
    coreConceptEn: 'Passive reading requires minimal cognitive depth; photons hit your retinas, your semantic parser recognizes the words, and working memory discards them. When you *generate* an answer, your brain activates semantic networks, forms relational associations, and exercises motor and lexical retrieval circuits, embedding rich multi-modal memory traces.',
    summary60sEn: 'Modern students spend 80% of their study time re-reading notes and highlighting paragraphs—activities that produce an illusion of familiarity without durable encoding. Shifting to generation techniques (summarizing from memory, flashcard recall, teaching out loud, completing partial problem steps) drastically cuts study time while multiplying retention.',
    takeawaysEn: [
      'Generating an answer produces up to 3x stronger memory traces than reading it',
      'Highlighting and re-reading create familiarity, not durable comprehension',
      'When your brain struggles to pull information out of memory, neural encoding cements',
      'The antidote to passive study is closing the book and writing a blank-sheet summary'
    ],
    whyItHappensEn: 'Depth of processing: self-generation requires semantic searching, associative retrieval, and motor execution, creating multifaceted memory anchors.',
    evolutionaryEn: 'Hunters learned which plants were poisonous by trial and active problem-solving, not by listening to abstract passive lectures.',
    howItWorksEn: 'Prompt given -> Book closed -> Brain initiates search across hippocampal networks -> Partial associations linked -> Answer formulated internally -> Answer written down -> Memory trace consolidated.',
    visualHeadlineEn: 'Passive Recognition vs. Active Self-Generation',
    visualDescEn: 'Slamecka & Graf’s experimental recall comparison.',
    sideALabelEn: 'Read Condition (Passive)',
    sideADetailEn: 'Read word pair: "Hot - Cold". Takes 1 second; zero cognitive strain; 22% delayed recall.',
    sideBLabelEn: 'Generate Condition (Active)',
    sideBDetailEn: 'Generate word pair: "Hot - C___" (Opposite). Brain solves puzzle; 68% delayed recall! (3x increase).',
    researchSummaryEn: 'Slamecka & Graf (1978, Journal of Verbal Learning and Verbal Behavior) and Karpicke & Roediger (2008, Science) demonstrated that active generation and testing produce exponentially superior retention to repeated studying.',
    refAuthor: 'Slamecka, N. J. & Graf, P.',
    refYear: 1978,
    refTitle: 'The Generation Effect: Delineation of a Phenomenon',
    refCitation: 'Slamecka, N. J., & Graf, P. (1978). J. of Verbal Learning and Verbal Behavior, 17(5), 592–604.',
    refDoi: 'https://doi.org/10.1016/S0022-5371(78)90353-6',
    scenarioTitleEn: 'The UPSC Highlighter Delusion in Mukherjee Nagar',
    scenarioContextEn: 'Rohan studied Indian Polity in Mukherjee Nagar, Delhi, for 10 hours a day, covering his Laxmikanth book in yellow and green highlighters. When asked a basic constitutional question during a peer mock interview, he stuttered, remembering that the answer was on a left-hand page in green ink, but unable to generate the facts.',
    scenarioBiasEn: 'Rohan mistook visual recognition for retrieval mastery: highlighting created cognitive fluency without forcing self-generation.',
    scenarioOptimalEn: 'Close the textbook after reading a chapter. Take a blank A4 sheet of paper and generate the constitutional framework, articles, and case laws entirely from memory.',
    scenarioReflectionEn: 'When you study or read an important article, do you immediately test your recall, or do you nod along thinking "yes, that makes sense"?',
    howToRecognizeEn: 'Looking at your notes and thinking "I know this", but finding yourself completely unable to explain the concept without looking at the page.',
    whereEn: 'College exam revision, language vocabulary acquisition, software code memorization, and executive public speaking preparation.',
    misconceptionsEn: 'Myth: "I learn best by reading and absorbing quietly." Fact: While reading is the first input, generation is neurologically mandatory for memory consolidation across all human brains.',
    limitationsEn: 'Generation cannot occur if the learner has zero baseline knowledge; you must comprehend the foundational idea before you can generate answers from it.',
    howToRespondEn: 'The Blank-Page Protocol: After reading any chapter or research paper, immediately close it and write down everything you remember on a blank sheet for 5 uninterrupted minutes.',
    defensesEn: [
      { title: 'The Fill-in-the-Blank Transformation', instruction: 'Turn textbook notes into self-test questions with blanks instead of full highlighted sentences.' },
      { title: 'The Rubber Duck Teach-Out', instruction: 'Explain the concept aloud to an inanimate object without consulting your notes, forcing verbal generation of every logical step.' }
    ],
    pqPromptEn: 'Which student will retain the most historical facts 3 months after their final examination?',
    pqScenarioEn: 'Both students invest exactly 10 hours of study time.',
    pqExplanationEn: 'Generating information through flashcards and practice essays forces active memory retrieval and consolidation, outperforming passive re-reading.',
    pqAntidoteEn: 'Replace re-reading study time with active generation and self-testing.',
    pqOptionsEn: [
      { id: 'opt_a', text: 'Student A, who re-read the textbook 4 times and highlighted the key dates with neon pens.', isCorrect: false, feedback: 'Incorrect. Re-reading creates shallow familiarity that fades in days.' },
      { id: 'opt_b', text: 'Student B, who read the text once, closed the book, and spent the remaining time writing summary essays from memory.', isCorrect: true, feedback: 'Correct! The Generation Effect produces durable long-term storage.' },
      { id: 'opt_c', text: 'Both will retain the exact same amount because both studied for 10 hours.', isCorrect: false, feedback: 'Incorrect. The cognitive mechanism of study matters vastly more than raw time.' }
    ],
    reflectionPromptEn: 'If you threw away your highlighters today, what active generation technique would you replace them with?',
    titleHinglish: 'The Generation Effect: Khud Banane Se Hi Yaad Rehta Hai',
    subtitleHinglish: 'Norman Slamecka ki research: Notes ko baar-baar padhne aur highlight karne se kuch yaad kyu nahi rehta.',
    shortDescHinglish: 'Passive reading vs Active generation: Dimaag wahi yaad rakhta hai jo wo khud generate karta hai, na ki jo wo sirf dekhta hai.',
    oneLineHinglish: 'Kitab kholi to sab aata hai, kitab band ki to dimaag khali.',
    summary30sHinglish: '1978 me Norman Slamecka ne prove kiya ki jab log sirf information padhte hain, to unhe 20% yaad rehta hai. Par jab unhe fill-in-the-blanks diya jata hai aur wo khud answer sochte hain, to unka recall 300% badh jata hai! Dimaag read karne se nahi, generate karne se seekhta hai.',
    coreConceptHinglish: 'Jab aap kitab par highlighter chalate ho, to dimaag ko lagta hai "arre yeh to bohot easy hai". Par yeh samajh nahi, balki sirf pehchan (Recognition) hoti hai. Jab aap kitab band karke khud answer likhne ki koshish karte ho, to dimaag ke connections majboot hote hain.',
    summary60sHinglish: 'UPSC aur college ke students 80% time sirf notes ko baar-baar padhte rehte hain. Yeh sabse bada time-waste hai. Sabse powerful tareeqa hai: Ek chapter padho, kitab band karo, ek blank white paper lo aur jo yaad hai wo sab bina dekhe likho. Shuru me dimag thakega, par yahi asli padhai hai.',
    howItWorksHinglish: 'Chapter padha -> Kitab band ki -> Blank page par likha -> Jahan ruke wahan dimaag ne zor lagaya -> Kitab khol kar gap check kiya -> Permanent memory ban gayi.',
    howToRespondHinglish: 'Blank Paper Test: Padhte waqt highlighter phek do. Har 30 minute baad kitab band karo aur 5 minute me summary khud likho.',
    takeawaysHinglish: [
      'Highlight karna aur baar-baar padhna dimaag ka sabse bada dhokha hai',
      'Jab dimaag ko andar se answer dhoondhna padta hai, tabhi permanent memory banti hai',
      'Kitab band karke likhne se 3 guna zyada retention hota hai',
      'Padhte waqt dimaag par jitna zor padega, exam me utna sukoon milega'
    ],
    pqPromptHinglish: 'Do students hain: A ne notes ko 4 baar highlight karke padha. B ne 1 baar padh kar kitab band ki aur dosto ko bina dekhe explain kiya. Exam me kaun top karega?',
    pqExplanationHinglish: 'B ne Generation Effect use kiya: bina dekhe explain karne se dimaag ne concepts ko khud formulate kiya.',
    pqOptionsHinglish: [
      { id: 'opt_a', text: 'Student A, kyuki colorful highlighters se photographic memory banti hai.', isCorrect: false, feedback: 'Galat. Photographic memory ek myth hai.' },
      { id: 'opt_b', text: 'Student B, kyuki khud bolne aur generate karne se neural pathways 300% majboot hote hain.', isCorrect: true, feedback: 'Sahi! Generation Effect active recall ko trigger karta hai.' },
      { id: 'opt_c', text: 'Dono fail ho jayenge.', isCorrect: false, feedback: 'Galat.' }
    ],
    hiTitle: 'सृजन प्रभाव (The Generation Effect)',
    hiSummary: 'केवल निष्क्रिय रूप से पढ़ने के बजाय स्वयं उत्तर या जानकारी उत्पन्न करने से स्मृति और समझ में होने वाली 3 गुना वृद्धि का वैज्ञानिक सिद्धांत।',
    hiTakeaways: ['हाइलाइट करना और बार-बार पढ़ना निष्क्रिय और अप्रभावी है', 'किताब बंद करके स्वयं लिखने से वास्तविक समझ विकसित होती है', 'मस्तिष्क वही याद रखता है जिसे वह स्वयं बनाता है'],
    guTitle: 'જનરેશન અસર (સ્વ-સર્જનનો પ્રભાવ)', guSummary: 'માત્ર વાંચવા કરતાં પોતાના મગજમાંથી જવાબો ઉત્પન્ન કરીને શીખવાની શ્રેષ્ઠ પદ્ધતિ.', guTakeaways: ['વાંચવા કરતાં લખીને યાદ રાખો', 'હાઇલાઇટર્સનો મોહ છોડો', 'પુસ્તક બંધ કરીને રિવિઝન કરો'],
    mrTitle: 'उत्पादन प्रभाव (Generation Effect)', mrSummary: 'फक्त वाचण्यापेक्षा स्वतः माहिती तयार करून किंवा आठवून शिकल्यामुळे स्मरणशक्तीत होणारी प्रचंड वाढ.', mrTakeaways: ['फक्त वाचणे निरुपयोगी ठरते', 'पुस्तके बंद करून आठवण्याचा प्रयत्न करा', 'स्वतःच्या भाषेत नोट्स लिहा'],
    teTitle: 'సృష్టి ప్రభావం (Generation Effect)', teSummary: 'కేవలం చదవడం కంటే స్వయంగా సమాచారాన్ని గుర్తుచేసుకుని రాయడం వల్ల కలిగే అద్భుతమైన జ్ఞాపకశక్తి.', teTakeaways: ['నిష్క్రియంగా చదవవద్దు', 'పుస్తకం మూసివేసి గుర్తుచేసుకోండి', 'సొంతంగా రాసి ప్రాక్టీస్ చేయండి'],
    taTitle: 'சுய உருவாக்க விளைவு (Generation Effect)', taSummary: 'வெறுமனே படிப்பதற்கு பதிலாக சுயமாக பதில்களை சிந்தித்து உருவாக்குவதால் நினைவாற்றல் அதிகரிக்கும் அறிவியல் உண்மை.', taTakeaways: ['வெறுமனே வாசிப்பதை தவிருங்கள்', 'புத்தகத்தை மூடிவிட்டு எழுதிப் பாருங்கள்', 'சுயமாக உருவாக்குவதே நிலைத்து நிற்கும்'],
    knTitle: 'ಸ್ವಯಂ ಸೃಷ್ಟಿಯ ಪರಿಣಾಮ (Generation Effect)', knSummary: 'ಕೇವಲ ಓದುವುದಕ್ಕಿಂತ ಸ್ವಂತವಾಗಿ ಉತ್ತರಗಳನ್ನು ನೆನಪಿಸಿಕೊಂಡು ಬರೆಯುವುದರಿಂದ ನೆನಪಿನ ಶಕ್ತಿ 3 ಪಟ್ಟು ಹೆಚ್ಚಾಗುತ್ತದೆ.', knTakeaways: ['ನಿಷ್ಕ್ರಿಯ ಓದುವಿಕೆಯನ್ನು ಬಿಡಿ', 'ಪುಸ್ತಕ ಮುಚ್ಚಿ ಬರೆದು ನೋಡಿ', 'ಸ್ವಯಂ ಸೃಷ್ಟಿಯೇ ಶಾಶ್ವತ ನೆನಪು'],
    mlTitle: 'സ്വയം നിർമ്മാണ പ്രഭാവം (Generation Effect)', mlSummary: 'വെറുതെ വായിച്ചു പോകുന്നതിനേക്കാൾ സ്വന്തം മനസ്സിൽ നിന്ന് ഉത്തരങ്ങൾ രൂപപ്പെടുത്തി പഠിക്കുമ്പോഴുള്ള അറിവ്.', mlTakeaways: ['നിഷ്ക്രിയ വായന ഒഴിവാക്കുക', 'പുസ്തകം അടച്ചുവെച്ച് എഴുതി നോക്കുക', 'സ്വന്തമായി നിർമ്മിക്കുന്നത് ഓർമ്മയിൽ നിൽക്കും'],
    bnTitle: 'সৃজন প্রভাব (Generation Effect)', bnSummary: 'নিষ্ক্রিয়ভাবে পড়ার চেয়ে নিজের মেধা খাটিয়ে উত্তর বের করার মাধ্যমে স্মৃতিশক্তি বহুগুণ বৃদ্ধির মনস্তত্ত্ব।', bnTakeaways: ['প্যাসিভ রিডিং এড়িয়ে চলুন', 'বই বন্ধ করে লেখার অভ্যাস করুন', 'মস্তিষ্ক নিজে যা তৈরি করে তা-ই মনে রাখে'],
    paTitle: 'ਖ਼ੁਦ-ਸਿਰਜਣਾ ਪ੍ਰਭਾਵ (Generation Effect)', paSummary: 'ਸਿਰਫ਼ ਕਿਤਾਬ ਪੜ੍ਹਨ ਨਾਲੋਂ ਆਪਣੇ ਦਿਮਾਗ ਵਿੱਚੋਂ ਜਵਾਬ ਕੱਢ ਕੇ ਲਿਖਣ ਨਾਲ ਯਾਦਦਾਸ਼ਤ ਵਿੱਚ ਹੋਣ ਵਾਲਾ ਵਾਧਾ।', paTakeaways: ['ਸਿਰਫ਼ ਕਿਤਾਬ ਪੜ੍ਹਨ ਤੋਂ ਬਚੋ', 'ਕਿਤਾਬ ਬੰਦ ਕਰਕੇ ਲਿਖਣ ਦੀ ਆਦਤ ਪਾਓ', 'ਖ਼ੁਦ ਬਣਾਏ ਨੋਟਸ ਹੀ ਕੰਮ ਆਉਂਦੇ ਹਨ'],
    urTitle: 'تخلیقی اثر (Generation Effect)', urSummary: 'محض کتاب پڑھنے کے بجائے اپنے ذہن سے جوابات سوچ کر لکھنے سے یادداشت میں 3 گنا اضافہ۔', urTakeaways: ['محض مطالعے کے فریب سے بچیں', 'کتاب بند کر کے خود لکھنے کی مشق کریں', 'ذہن خود بنائی ہوئی چیز یاد رکھتا ہے'],
    orTitle: 'ସୃଜନ ପ୍ରଭାବ (Generation Effect)', orSummary: 'କେବଳ ପଢ଼ିବା ଅପେକ୍ଷା ନିଜେ ଉତ୍ତର ତିଆରି କରି ଲେଖିବା ଦ୍ୱାରା ସ୍ମରଣ ଶକ୍ତି ବୃଦ୍ଧି ପାଇବାର ବୈଜ୍ଞାନିକ ତଥ୍ୟ।', orTakeaways: ['କେବଳ ପଢ଼ିବା ଛାଡ଼ନ୍ତୁ', 'ବହି ବନ୍ଦ କରି ମନେପକାଇ ଲେଖନ୍ତୁ', 'ନିଜେ ତିଆରି କଲେ ମନେରହେ'],
    asTitle: 'সৃষ্টিশীল প্ৰভাৱ (Generation Effect)', asSummary: 'কেৱল কিতাপ পঢ়াৰ বিপৰীতে নিজৰ মগজু খটুৱাই উত্তৰ সৃষ্টি কৰি শিকাৰ অপৰিসীম সুফল।', asTakeaways: ['নিষ্ক্ৰিয় পঠন পৰিহাৰ কৰক', 'কিতাপ বন্ধ কৰি মনত পেলাই লিখক', 'মগজুৱে নিজে গঢ়া বস্তুটোহে মনত ৰাখে']
  },

  {
    fileName: 'dualCodingTheory.ts',
    varName: 'dual_coding_theory',
    id: 'dual_coding_theory',
    categoryId: 'learning_psychology',
    slug: 'dual-coding-theory',
    difficulty: 'beginner',
    readTime: 5,
    sortWeight: 7,
    titleEn: 'Dual Coding Theory: Double-Barreled Memory Storage',
    subtitleEn: 'Allan Paivio’s cognitive architecture on why combining words with visual imagery doubles recall capacity.',
    shortDescEn: 'A cognitive theory positing that human memory operates via two separate, interconnected systems: a linguistic/verbal system and a non-verbal visual/spatial system.',
    oneLineEn: 'Store it with a word and an image; if one cognitive pathway fails, the other retrieves it.',
    summary30sEn: 'Proposed by Canadian psychologist Allan Paivio in 1971, Dual Coding Theory asserts that memory performance is dramatically enhanced when information is encoded through both verbal and non-verbal symbolic systems. Words and visual diagrams utilize independent cognitive working memory buffers, doubling the associative pathways available for retrieval.',
    coreConceptEn: 'The verbal system processes sequential linguistic input (text, spoken words, formulas), creating "logogens". The non-verbal system processes continuous spatial information (drawings, mental models, spatial maps), creating "imagens". When a concept is encoded with both a logogen and an imagen, you create a redundant neuro-associative bridge: activating either representation reactivates the other.',
    summary60sEn: 'Dual coding debunked the myth of rigid "visual vs. verbal learners". Every human brain (barring severe sensory impairment) possesses both processing channels. Text-heavy slides and monotonous monologues overload the verbal phonological loop while leaving the visuospatial sketchpad completely idle. Integrating concise diagrams, timelines, and spatial metaphors unlocks latent cognitive bandwidth.',
    takeawaysEn: [
      'The brain processes verbal text and visual imagery through two independent parallel systems',
      'Dual encoding creates two separate retrieval cues for every concept learned',
      'Combining simple sketches with concise labels outperforms dense text paragraphs by 2x',
      'Do not decorate slides with irrelevant photos; use meaningful explanatory diagrams'
    ],
    whyItHappensEn: 'Evolutionary cortical architecture: the visual cortex and auditory language centers evolved as distinct processing modules that synergize via associative cortices.',
    evolutionaryEn: 'Hunters tracked prey by combining spoken tribal terminology with spatial visual footprints and terrain geometry.',
    howItWorksEn: 'New concept encountered -> Processed as verbal explanation (Logogen) -> Simultaneously drawn as visual flow diagram (Imagen) -> Cross-linking associative pathways established -> Dual retrieval redundancy secured.',
    visualHeadlineEn: 'Single Verbal Encoding vs. Dual-Coded Redundancy',
    visualDescEn: 'Allan Paivio’s dual cognitive architecture in working memory.',
    sideALabelEn: 'Single Verbal Encoding',
    sideADetailEn: '300-word paragraph describing photosynthesis -> Phonological loop strained; 28% delayed recall.',
    sideBLabelEn: 'Dual-Coded Architecture',
    sideBDetailEn: 'Simple flowchart diagram + 3 key bullet labels -> Verbal & visual systems active; 65% recall!',
    researchSummaryEn: 'Paivio (1971, 1986, Oxford University Press) and Mayer & Anderson (1991, Journal of Educational Psychology) established that multimedia instruction presenting coordinated text and animation significantly boosts problem-solving transfer.',
    refAuthor: 'Paivio, A.',
    refYear: 1971,
    refTitle: 'Imagery and Verbal Processes',
    refCitation: 'Paivio, A. (1971). Holt, Rinehart & Winston.',
    refDoi: 'https://doi.org/10.1037/h0032955',
    scenarioTitleEn: 'The Medical Anatomy Struggle in Chennai',
    scenarioContextEn: 'Divya, a first-year medical student in Chennai, spent 4 weeks reading a dense 40-page textbook chapter on the renal nephron countercurrent multiplier system. On her viva exam, she struggled to explain the sodium gradient. Her peer, who sketched a simple cartoon diagram with arrows while studying, explained it flawlessly in 90 seconds.',
    scenarioBiasEn: 'Divya relied strictly on single-channel verbal memorization, whereas her peer built a dual-coded spatial mental model.',
    scenarioOptimalEn: 'Whenever learning a complex process, take a sketchpad and convert every paragraph into a sequential flowchart, labeled cross-section, or spatial coordinate map.',
    scenarioReflectionEn: 'When you take notes in meetings or classes, do your pages consist entirely of words, or do you integrate arrows, boxes, and structural diagrams?',
    howToRecognizeEn: 'Memorizing long paragraphs of text by rote repetition, followed by feeling completely stuck the moment you forget a single transitional word.',
    whereEn: 'STEM education (physics, biology, engineering), corporate presentation design, workflow SOP documentation, and architecture.',
    misconceptionsEn: 'Myth: "Dual coding means putting decorative clip-art or memes on every slide." Fact: Decorative visuals cause cognitive split-attention overload. Visuals must be strictly explanatory and structurally aligned with the verbal content.',
    limitationsEn: 'For highly abstract metaphysical philosophy (e.g. existentialism, symbolic logic), spatial visual representations can sometimes oversimplify subtle nuances.',
    howToRespondEn: 'The Sketchnote Rule: For every major concept you write down, accompany it with a visual box-and-arrow schema, timeline, or conceptual icon.',
    defensesEn: [
      { title: 'The Concept Map Conversion', instruction: 'Never leave notes as pure bullet points; convert relationships between ideas into spatial concept maps.' },
      { title: 'The Pictionary Self-Test', instruction: 'Can you draw the mechanism you just learned on a whiteboard without writing any full sentences?' }
    ],
    pqPromptEn: 'A company wants employees to memorize safety protocol steps for chemical spills. Which training format will lead to the fastest, most error-free emergency execution?',
    pqScenarioEn: 'Employees must remember a 5-step sequence under high-stress conditions.',
    pqExplanationEn: 'Dual coding (pairing concise verbal steps with a sequential spatial flowchart) engages both cognitive channels, accelerating emergency retrieval.',
    pqAntidoteEn: 'Integrate clear visual schematics alongside concise verbal directives.',
    pqOptionsEn: [
      { id: 'opt_a', text: 'A 10-page text-only handbook outlining the safety regulations in dense legal paragraphs.', isCorrect: false, feedback: 'Incorrect. Single-channel verbal overload causes memory failure under stress.' },
      { id: 'opt_b', text: 'A visual sequence diagram with numbered action boxes and 5-word directive labels placed at eye level.', isCorrect: true, feedback: 'Correct! Dual coding ensures high-speed, dual-channel recognition.' },
      { id: 'opt_c', text: 'An audio podcast explaining the history of chemical safety.', isCorrect: false, feedback: 'Incorrect. Audio-only lacks spatial orientation.' }
    ],
    reflectionPromptEn: 'Look at your last page of written notes. What percentage of that page is visual versus pure text, and how can you add a diagram right now?',
    titleHinglish: 'Dual Coding Theory: Words Aur Picture Ki Double Power',
    subtitleHinglish: 'Allan Paivio ki research: Sirf text padhne ke bajaye diagram ke sath padhne se dimaag 2 guna tez kyu yaad rakhta hai.',
    shortDescHinglish: 'Logogens aur Imagens: Dimaag ke verbal aur visual channels ko ek sath activate karke memory ko double-lock karna.',
    oneLineHinglish: 'Ek word aur ek drawing: Agar dimaag ek bhool bhi jaye, to doosra rasta yaad dila deta hai.',
    summary30sHinglish: '1971 me psychologist Allan Paivio ne prove kiya ki dimaag me do alag-alag memory systems hote hain: Ek shabdo (words) ke liye aur doosra tasveeron (visuals) ke liye. Jab aap kisi concept ko padhne ke sath-sath uska ek chota sa rough diagram ya flowchart bana lete hain, to retention double ho jata hai.',
    coreConceptHinglish: 'Agar aap sirf 500 words ka paragraph ratoge, to dimaag ka sirf verbal hissa thak jayega aur visual hissa so raha hoga. Jab aap ek flowchart ya concept map banate ho, to dimaag me do alag-alag chabiya (keys) ban jati hain. Exam me agar shabd bhool gaye, to diagram ka visual memory aapko bacha leta hai.',
    summary60sHinglish: 'Yeh galatfehmi door karo ki "main to visual learner hu, main padh nahi sakta". Har insaan ka dimaag dono channels use karta hai. Boring PowerPoint presentations me log sirf bullet points bhar dete hain, jisse dimaag confuse ho jata hai. Ek simple sketch aur 3 bullet points poore paragraph se zyada asardaar hote hain.',
    howItWorksHinglish: 'Concept padha -> Verbal memory me gaya -> Hath se rough flowchart banaya -> Visual memory me gaya -> Dono connect ho gaye -> Exam me bullet-proof recall mila.',
    howToRespondHinglish: 'Rough Sketch banao: Notes banate waqt har page par kam se kam ek box-and-arrow diagram ya graph zaroor banao.',
    takeawaysHinglish: [
      'Dimaag me shabdo aur visuals ke do alag-alag processing units hote hain',
      'Dono channels ko use karne se yaad rakhne ki capacity 2x ho jati hai',
      'Text ke sath relevant diagram banao, faltu stock photos lagane se bacho',
      'Jab bhi koi mushkil process padho, use turant ek flowchart me badal do'
    ],
    pqPromptHinglish: 'Chemical spill se bachne ke 5 steps sikhane hain. Kaunsa tareeqa emergency me sabse fast yaad aayega?',
    pqExplanationHinglish: 'Numbered visual flowchart ke sath 3-3 shabdo ke steps (Dual Coding) dimaag me turant trigger hote hain.',
    pqOptionsHinglish: [
      { id: 'opt_a', text: '10 page ka lamba English essay padhana.', isCorrect: false, feedback: 'Galat. Emergency me lamba text dimaag block kar deta hai.' },
      { id: 'opt_b', text: 'Ek simple visual flowchart jisme step-by-step cartoon aur short labels ho.', isCorrect: true, feedback: 'Sahi! Dual coding emergency situations me best perform karti hai.' },
      { id: 'opt_c', text: 'Employees ko phone par audio sunana.', isCorrect: false, feedback: 'Galat. Audio spatial steps nahi dikha sakta.' }
    ],
    hiTitle: 'द्वि-कोडिंग सिद्धांत (Dual Coding Theory)',
    hiSummary: 'शाब्दिक भाषा और दृश्य छवियों के दोहरे संयोजन से स्मृति और समझ को दोगुना करने का संज्ञानात्मक सिद्धांत।',
    hiTakeaways: ['मस्तिष्क शब्दों और छवियों को दो स्वतंत्र समानांतर प्रणालियों में संसाधित करता है', 'द्वि-कोडिंग प्रत्येक अवधारणा के लिए दो स्वतंत्र पुनर्प्राप्ति मार्ग बनाती है', 'घने पैराग्राफ को हमेशा फ्लोचार्ट और रेखाचित्रों में बदलें'],
    guTitle: 'ડ્યુઅલ કોડિંગ થિયરી (દ્વિ-કોડિંગ સિદ્ધાંત)', guSummary: 'શબ્દો અને ચિત્રોના સંયોજન દ્વારા યાદશક્તિને બમણી કરવાની મનોવૈજ્ઞાનિક પદ્ધતિ.', guTakeaways: ['શબ્દો અને આકૃતિઓ સાથે શીખો', 'નોટ્સમાં ફ્લોચાર્ટ બનાવો', 'ડબલ મેમરી પાથવે બનાવો'],
    mrTitle: 'दुहेरी संकेतन सिद्धांत (Dual Coding Theory)', mrSummary: 'शब्द आणि दृश्य चित्रांच्या संयोगातून स्मरणशक्ती दुप्पट करण्याचे संज्ञानात्मक मानसशास्त्र.', mrTakeaways: ['शब्द आणि चित्रे एकत्र वापरा', 'अभ्यासात आकृत्यांचा समावेश करा', 'स्मरणशक्ती दुप्पट करा'],
    teTitle: 'డ్యూయల్ కోడింగ్ సిద్ధాంతం (ద్విముఖ సంకేతీకరణ)', teSummary: 'పదాలు మరియు దృశ్య చిత్రాల కలయికతో జ్ఞాపకశక్తిని రెట్టింపు చేసుకునే విజ్ఞానశాస్త్రం.', teTakeaways: ['పదాలు మరియు బొమ్మలను కలపండి', 'ఫ్లోచార్ట్‌లు గీయండి', 'జ్ఞాపకశక్తిని పెంచుకోండి'],
    taTitle: 'இருவழி குறியீட்டு கோட்பாடு (Dual Coding Theory)', taSummary: 'சொற்கள் மற்றும் காட்சிப் படங்களை இணைத்து நினைவாற்றலை இரட்டிப்பாக்கும் அறிவாற்றல் முறை.', taTakeaways: ['சொற்களையும் படங்களையும் இணையுங்கள்', 'வரைபடங்களை பயன்படுத்துங்கள்', 'நினைவாற்றலை இரட்டிப்பாக்குங்கள்'],
    knTitle: 'ದ್ವಿಮುಖ ಕೋಡಿಂಗ್ ಸಿದ್ಧಾಂತ (Dual Coding Theory)', knSummary: 'ಪದಗಳು ಮತ್ತು ದೃಶ್ಯ ಚಿತ್ರಗಳನ್ನು ಸಂಯೋಜಿಸಿ ನೆನಪಿನ ಶಕ್ತಿಯನ್ನು ದ್ವಿಗುಣಗೊಳಿಸುವ ಜ್ಞಾನಗ್ರಹಣ ತಂತ್ರ.', knTakeaways: ['ಪದಗಳು ಮತ್ತು ಚಿತ್ರಗಳನ್ನು ಒಟ್ಟಿಗೆ ಬಳಸಿ', 'ರೇಖಾಚಿತ್ರಗಳನ್ನು ರಚಿಸಿ', 'ನೆನಪಿನ ಶಕ್ತಿ ಹೆಚ್ಚಿಸಿಕೊಳ್ಳಿ'],
    mlTitle: 'ഡ്യുവൽ കോഡിംഗ് സിദ്ധാന്തം (ഇരട്ട കോഡിംഗ് രീതി)', mlSummary: 'വാക്കുകളും ദൃശ്യ ചിത്രങ്ങളും സംയോജിപ്പിച്ച് ഓർമ്മശക്തി ഇരട്ടിയാക്കുന്ന മനശാസ്ത്ര തത്വം.', mlTakeaways: ['വാക്കുകളും ചിത്രങ്ങളും ഒരുമിച്ച് ഉപയോഗിക്കുക', 'ഫ്ലോചാർട്ടുകൾ വരയ്ക്കുക', 'ഓർമ്മശക്തി ഇരട്ടിയാക്കുക'],
    bnTitle: 'দ্বৈত কোডিং তত্ত্ব (Dual Coding Theory)', bnSummary: 'শব্দ ও দৃশ্যমান ছবির যুগলবন্দিতে স্মৃতিশক্তি ও ধারণক্ষমতা দ্বিগুণ করার মনস্তাত্ত্বিক কাঠামো।', bnTakeaways: ['শব্দ ও ছবি একসাথে ব্যবহার করুন', 'নোটের সাথে ফ্লোচার্ট আঁকুন', 'দ্বিগুণ মেমরি পাথওয়ে তৈরি করুন'],
    paTitle: 'ਦੋਹਰੀ ਕੋਡਿੰਗ ਥਿਊਰੀ (Dual Coding Theory)', paSummary: 'ਸ਼ਬਦਾਂ ਅਤੇ ਤਸਵੀਰਾਂ ਦੇ ਸੁਮੇਲ ਨਾਲ ਯਾਦਦਾਸ਼ਤ ਨੂੰ ਦੁੱਗਣਾ ਕਰਨ ਦਾ ਵਿਗਿਆਨਕ ਸਿਧਾਂਤ।', paTakeaways: ['ਸ਼ਬਦ ਅਤੇ ਚਿੱਤਰ ਇਕੱਠੇ ਵਰਤੋ', 'ਨੋਟਸ ਵਿੱਚ ਡਾਇਗ੍ਰਾਮ ਬਣਾਓ', 'ਯਾਦਦਾਸ਼ਤ ਦੁੱਗਣੀ ਕਰੋ'],
    urTitle: 'دوہری کوڈنگ کا نظریہ (Dual Coding Theory)', urSummary: 'الفاظ اور بصری تصاویر کے اشتراک سے یادداشت کی صلاحیت کو دوگنا کرنے کا علمی طریقہ۔', urTakeaways: ['الفاظ اور خاکوں کا ملاپ کریں', 'نوٹس میں فلو چارٹ بنائیں', 'یادداشت کو دوگنا مضبوط کریں'],
    orTitle: 'ଦ୍ୱି-କୋଡିଂ ତତ୍ତ୍ୱ (Dual Coding Theory)', orSummary: 'ଶବ୍ଦ ଓ ଚିତ୍ରର ସମନ୍ୱୟରେ ସ୍ମରଣ ଶକ୍ତିକୁ ଦ୍ୱିଗୁଣିତ କରିବାର ମାନସିକ ବିଜ୍ଞାନ।', orTakeaways: ['ଶବ୍ଦ ଓ ଚିତ୍ର ଏକାଠି ବ୍ୟବହାର କରନ୍ତୁ', 'ଫ୍ଲୋଚାର୍ଟ ତିଆରି କରନ୍ତୁ', 'ସ୍ମୃତି ଶକ୍ତି ଦୃଢ଼ କରନ୍ତୁ'],
    asTitle: 'দ্বৈত কোডিং তত্ত্ব (Dual Coding Theory)', asSummary: 'শব্দ আৰু দৃশ্যমান চিত্ৰৰ সংমিশ্ৰণেৰে স্মৃতিশক্তি দুগুণ কৰাৰ জ্ঞানমূলক বৈজ্ঞানিক তত্ত্ব।', asTakeaways: ['শব্দ আৰু ছবি একেলগে ব্যৱহাৰ কৰক', 'নোটৰ লগত চিত্ৰ আঁকক', 'স্মৃতিশক্তি দুগুণ বৃদ্ধি কৰক']
  },

  {
    fileName: 'curseOfKnowledge.ts',
    varName: 'curse_of_knowledge',
    id: 'curse_of_knowledge',
    categoryId: 'learning_psychology',
    slug: 'curse-of-knowledge',
    difficulty: 'intermediate',
    readTime: 5,
    sortWeight: 8,
    titleEn: 'The Curse of Knowledge: Expert Blindness in Teaching',
    subtitleEn: 'Elizabeth Newton’s Stanford tapper-listener experiment on why knowing something makes it impossible to imagine not knowing it.',
    shortDescEn: 'A cognitive bias that occurs when an individual, communicating with other individuals, unknowingly assumes that the others have the background knowledge to understand.',
    oneLineEn: 'Once you know something, you literally cannot imagine what it felt like to be ignorant of it.',
    summary30sEn: 'First proven in 1990 by Stanford PhD student Elizabeth Newton, the Curse of Knowledge is the primary reason why brilliant professors, senior engineers, and executives are often terrible teachers. Newton had subjects tap out the rhythm of famous songs (like "Happy Birthday") with their knuckles while listeners guessed. Tappers predicted a 50% success rate; listeners guessed correctly only 2.5% of the time!',
    coreConceptEn: 'When the tapper taps, they hear the rich melody, lyrics, and orchestra playing in their own mind. The listener hears only bizarre, disconnected tapping sounds on a table. In communication, an expert has rich schemas, contextual nuances, and acronyms playing in their brain, blinding them to the reality that their novice audience is hearing only incomprehensible static.',
    summary60sEn: 'The Curse of Knowledge poisons onboarding manuals, corporate presentations, doctor-patient conversations, and software documentation. Experts use insider jargon and skip foundational logical steps not out of arrogance, but because their prefrontal cortex cannot physically reconstruct the naive mental model of a beginner.',
    takeawaysEn: [
      'Knowing a concept makes it neurologically difficult to simulate a beginner’s mind',
      'The tapper-listener gap: you hear the symphony, the listener hears random knocks',
      'Insiders chronically underestimate how confusing their jargon is to outsiders',
      'The antidote is explaining concepts using tangible, concrete metaphors without acronyms'
    ],
    whyItHappensEn: 'Egocentric anchor heuristic: the brain uses its current knowledge state as the default baseline, failing to sufficiently adjust downward for others.',
    evolutionaryEn: 'In ancestral tribes, shared knowledge was universally assumed because everyone lived in the exact same physical and cultural reality.',
    howItWorksEn: 'Expert acquires mastery -> Mental models compress into abstract chunks -> Expert communicates chunks directly -> Novice lacks foundational primitives -> Confusion and alienation ensue -> Expert blames student.',
    visualHeadlineEn: 'Tapper’s Rich Symphony vs. Listener’s Random Thuds',
    visualDescEn: 'Elizabeth Newton’s Stanford finger-tapping experiment.',
    sideALabelEn: 'Tapper’s Perception (Expert)',
    sideADetailEn: 'Hears full orchestra, emotional lyrics, and harmony inside their skull. Predicts: "50% will guess this easily!"',
    sideBLabelEn: 'Listener’s Reality (Novice)',
    sideBDetailEn: 'Hears disconnected, monotone knocks on wood: *tap... tap... tap-tap*. Actual success rate: 2.5%!',
    researchSummaryEn: 'Newton (1990, Stanford Doctoral Dissertation) and Camerer, Loewenstein & Weber (1989, Journal of Political Economy) proved that better-informed agents systematically fail to predict the choices of less-informed agents.',
    refAuthor: 'Newton, E.',
    refYear: 1990,
    refTitle: 'Overconfidence in the Communication of Intent: Heard and Unheard Melodies',
    refCitation: 'Newton, E. (1990). PhD Dissertation, Stanford University.',
    refDoi: 'https://doi.org/10.1086/261651',
    scenarioTitleEn: 'The Senior Tech Lead Onboarding in Bengaluru',
    scenarioContextEn: 'Vikram, a principal architect in Bengaluru, spent 20 minutes explaining the microservices architecture to a newly hired junior engineer, using terms like "idempotent Kafka consumers", "gRPC backpressure", and "eventual consistency". The junior engineer nodded politely, smiled, went to his desk, and stared at the terminal in paralyzed tears.',
    scenarioBiasEn: 'Vikram was trapped by the Curse of Knowledge: he forgot that it took him 12 years of production fires to understand those abstractions.',
    scenarioOptimalEn: 'Anchor to a physical real-world metaphor: "Think of Kafka like a post office counter where letters wait in line so the clerks don\'t get overwhelmed."',
    scenarioReflectionEn: 'Have you ever tried to teach a parent or grandparent how to use a smartphone feature and found yourself getting inexplicably irritated by their questions?',
    howToRecognizeEn: 'Saying phrases like "It’s obvious that...", "Simply run this command...", or feeling baffled when someone fails to understand your explanation.',
    whereEn: 'Engineering documentation, university lectures, medical consultations, user interface design, and parent-child tutoring.',
    misconceptionsEn: 'Myth: "Great experts naturally make the best teachers." Fact: True experts often make the worst introductory teachers because their cognitive gap with beginners is the largest.',
    limitationsEn: 'When communicating exclusively among peers of identical seniority and specialization, dense domain jargon is highly efficient shorthand.',
    howToRespondEn: 'The "Explain Like I\'m 12" Protocol: Strip away every single acronym and explain the core mechanism using physical objects (water pipes, buckets, post offices, traffic lights).',
    defensesEn: [
      { title: 'The Beginner Test Group', instruction: 'Never release documentation or curriculum without testing it on a complete novice who has permission to say "I don’t get it."' },
      { title: 'The Concrete Analogy Anchor', instruction: 'Force yourself to explain the abstract concept using a tangible story from everyday life before introducing formal terminology.' }
    ],
    pqPromptEn: 'A senior cardiologist explains a heart condition to a nervous patient using medical terminology like "idiopathic ventricular arrhythmia and ejection fraction deficit". What cognitive bias explains why the doctor thinks this explanation was clear?',
    pqScenarioEn: 'The patient leaves the office terrified and with zero understanding of what medications to take.',
    pqExplanationEn: 'The Curse of Knowledge prevents the physician from recognizing that words obvious to medical professionals sound like an alien language to a layperson.',
    pqAntidoteEn: 'Use simple mechanical analogies (e.g. comparing the heart to a plumbing pump and electrical spark plug).',
    pqOptionsEn: [
      { id: 'opt_a', text: 'The doctor deliberately wanted to confuse the patient to show off superior intelligence.', isCorrect: false, feedback: 'Incorrect. Most experts genuinely believe they are being helpful and clear.' },
      { id: 'opt_b', text: 'The Curse of Knowledge blinded the doctor to the huge cognitive gap between medical expertise and everyday comprehension.', isCorrect: true, feedback: 'Correct! The doctor cannot un-know their medical vocabulary.' },
      { id: 'opt_c', text: 'The patient has an unusually low IQ.', isCorrect: false, feedback: 'Incorrect. Domain jargon confuses highly intelligent non-specialists.' }
    ],
    reflectionPromptEn: 'What is a topic you know so well that you struggle to explain it to someone without getting impatient?',
    titleHinglish: 'Curse of Knowledge: Expert Ka Andha-pan',
    subtitleHinglish: 'Elizabeth Newton ki Stanford research: Jab hume koi cheez aati hai, to hum yeh imagine hi nahi kar sakte ki kisi ko yeh samajh kyu nahi aa rahi.',
    shortDescHinglish: 'Tapper-Listener Experiment: Senior engineers aur professors acche teacher kyu nahi ban pate kyuki wo basic level bhool chuke hote hain.',
    oneLineHinglish: 'Aapke dimaag me poora gaana baj raha hai, par samne wale ko sirf table par ungli patakne ki ajeeb aawaaz sunai de rahi hai.',
    summary30sHinglish: 'Stanford me ek famous experiment hua: Logo ko table par ungli maar kar "Happy Birthday" ka rhythm bajane ko bola gaya. Bajane wale ko laga 50% log gaana pehchan lenge. Par sunne walo me se sirf 2.5% log hi pehchan paye! Kyuki bajane wale ke dimaag me gaana baj raha tha, par sunne wale ko sirf bekaar thak-thak sunai de rahi thi.',
    coreConceptHinglish: 'Ise kehte hain Curse of Knowledge. Jab aap kisi cheez ke master ban jate ho, to aapka dimaag bhool jata hai ki beginner hona kaisa lagta tha. College ke topper professors aur senior IT leads isiliye kharab padhate hain kyuki wo aisi bhaari jargon bolte hain jo aam insaan ke sir ke upar se nikal jati hai.',
    summary60sHinglish: 'Jab aap kisi junior ko ya apne mummy-papa ko tech sikhate ho aur unhe samajh nahi aata, to aapko gussa aane lagta hai: "Arre itna simple to hai!" Par wo simple aapke liye hai, unke liye wo bilkul nayi duniya hai. Acche teacher wo hote hain jo technical shabdo ko aam zindagi ke real-world examples se samjhate hain.',
    howItWorksHinglish: 'Expert ne 10 saal me seekha -> Wo concepts ko easy samajhne laga -> Beginner ko jargon me samjhaya -> Beginner blank ho gaya -> Expert ne bola "Tum me dimaag nahi hai".',
    howToRespondHinglish: 'ELI5 (Explain Like I\'m 5): Kisi bhi cheez ko aam bhasha me samjhao. Microservices ko samjhane ke liye restaurant ke kitchen aur waiter ka example do.',
    takeawaysHinglish: [
      'Ek baar koi cheez seekh lo, to yeh bhoolna namumkin hota hai ki na aane par kaisa lagta tha',
      'Aapke dimaag ka symphony doosre ko bekaar knock jaisa lagta hai',
      'Jargon bolna intelligence nahi, balki communication failure ka saboot hai',
      'Asli genius wahi hai jo sabse mushkil concept ko 10 saal ke bacche ko samjha sake'
    ],
    pqPromptHinglish: 'Ek senior doctor ne patient ko bola: "Aapko idiopathic ventricular arrhythmia hai." Patient dar gaya aur kuch nahi samjha. Doctor ko kyu laga ki usne sahi samjhaya?',
    pqExplanationHinglish: 'Curse of knowledge ki wajah se doctor imagine hi nahi kar paya ki yeh medical words aam insaan ke liye kitne terrifying aur confusing hain.',
    pqOptionsHinglish: [
      { id: 'opt_a', text: 'Doctor patient se dushmani nikaal raha tha.', isCorrect: false, feedback: 'Galat. Doctor sincerely explain kar raha tha.' },
      { id: 'opt_b', text: 'Curse of Knowledge ki wajah se doctor bhool gaya ki aam insaan ko medical jargon samajh nahi aati.', isCorrect: true, feedback: 'Sahi! Expert blindness ki wajah se communication gap ban gaya.' },
      { id: 'opt_c', text: 'Patient ko sunai kam deta tha.', isCorrect: false, feedback: 'Galat. Problem vocabulary ki thi, kaan ki nahi.' }
    ],
    hiTitle: 'ज्ञान का अभिशाप (Curse of Knowledge)',
    hiSummary: 'किसी विषय का गहन ज्ञान होने पर यह कल्पना करने में असमर्थ होना कि उस विषय से अनभिज्ञ व्यक्ति कैसा महसूस करता है।',
    hiTakeaways: ['विशेषज्ञ शुरुआती शिक्षार्थी की मानसिक स्थिति का अनुमान नहीं लगा पाते', 'जटिल शब्दावली के बजाय सरल वास्तविक उदाहरणों का उपयोग करें', 'उत्कृष्ट शिक्षण के लिए ज्ञान के अभिशाप को तोड़ना आवश्यक है'],
    guTitle: 'જ્ઞાનનો અભિશાપ (Curse of Knowledge)', guSummary: 'એકવાર કંઈક શીખ્યા પછી અજાણ વ્યક્તિની સ્થિતિ સમજવામાં નિષ્ફળ જવાની માનસિક મર્યાદા.', guTakeaways: ['ટેકનિકલ ભાષા સરળ કરો', 'નવા શીખનારની દ્રષ્ટિએ વિચારો', 'સરળ ઉદાહરણોથી સમજાવો'],
    mrTitle: 'ज्ञानाचा शाप (Curse of Knowledge)', mrSummary: 'एखादी गोष्ट स्वतःला चांगल्या प्रकारे समजत असल्यामुळे इतरांना ती का समजत नाही हे न कळणे.', mrTakeaways: ['कठीण शब्द वापरणे टाळा', 'सुरुवातीच्या विद्यार्थ्याची मानसिकता ओळखा', 'सोप्या उदाहरणांनी शिकवा'],
    teTitle: 'జ్ఞాన శాపం (Curse of Knowledge)', teSummary: 'ఒక విషయంపై పట్టు సాధించిన తర్వాత, ఏమీ తెలియని వ్యక్తి దృక్పథాన్ని అర్థం చేసుకోలేకపోవడం.', teTakeaways: ['పరిభాషను సరళతరం చేయండి', 'కొత్తవారి కోణంలో ఆలోచించండి', 'ఉదాహరణలతో సులభంగా వివరించండి'],
    taTitle: 'அறிவின் சாபம் (Curse of Knowledge)', taSummary: 'ஒரு விஷயம் நமக்கு தெரிந்த பிறகு, அது தெரியாதவர்களின் நிலையை புரிந்து கொள்ள முடியாத அறிவாற்றல் குறைபாடு.', taTakeaways: ['கடினமான வார்த்தைகளை தவிருங்கள்', 'தொடக்க நிலையாளரின் கண்ணோட்டத்தில் பாருங்கள்', 'எளிய உதாரணங்களுடன் விளக்குங்கள்'],
    knTitle: 'ಜ್ಞಾನದ ಶಾಪ (Curse of Knowledge)', knSummary: 'ಒಂದು ವಿಷಯ ನಮಗೆ ಚೆನ್ನಾಗಿ ತಿಳಿದ ಮೇಲೆ, ತಿಳಿಯದವರ ಮನಸ್ಥಿತಿಯನ್ನು ಊಹಿಸಲು ಸಾಧ್ಯವಾಗದಿರುವ ಸ್ಥಿತಿ.', knTakeaways: ['ತಾಂತ್ರಿಕ ಪದಗಳನ್ನು ಸರಳಗೊಳಿಸಿ', 'ಹೊಸಬರ ದೃಷ್ಟಿಕೋನದಲ್ಲಿ ಯೋಚಿಸಿ', 'ಸರಳ ಉದಾಹરણೆಗಳಿಂದ ವಿವರಿಸಿ'],
    mlTitle: 'അറിവിന്റെ ശാപം (Curse of Knowledge)', mlSummary: 'ഒരു കാര്യം നമുക്ക് അറിയാമെന്നതിനാൽ അത് മറ്റുള്ളവർക്ക് മനസ്സിലാകാൻ ബുദ്ധിമുട്ടാണെന്ന് തിരിച്ചറിയാത്ത അവസ്ഥ.', mlTakeaways: ['സാങ്കേതിക പദങ്ങൾ ലളിതമാക്കുക', 'തുടക്കക്കാരുടെ കണ്ണിലൂടെ കാണുക', 'ലളിതമായ ഉദാഹരണങ്ങളിലൂടെ പഠിപ്പിക്കുക'],
    bnTitle: 'জ্ঞানের অভিশাপ (Curse of Knowledge)', bnSummary: 'কোনো বিষয়ে বিশেষজ্ঞ হওয়ার পর একজন শিক্ষানবিশের বোঝার অসুবিধা কল্পনা করতে না পারার মনস্তাত্ত্বিক অন্ধত্ব।', bnTakeaways: ['জটিল পারিভাষিক শব্দ এড়িয়ে চলুন', 'শিক্ষানবিশের দৃষ্টিভঙ্গি বুঝুন', 'বাস্তব জীবনের রূপক ব্যবহার করুন'],
    paTitle: 'ਗਿਆਨ ਦਾ ਸਰਾਪ (Curse of Knowledge)', paSummary: 'ਕੋਈ ਗੱਲ ਖ਼ੁਦ ਨੂੰ ਸਮਝ ਆਉਣ ਮਗਰੋਂ ਇਹ ਨਾ ਸਮਝ ਸਕਣਾ ਕਿ ਨਵੇਂ ਬੰਦੇ ਨੂੰ ਇਹ ਔਖੀ ਕਿਉਂ ਲੱਗ ਰਹੀ ਹੈ।', paTakeaways: ['ਔਖੀ ਸ਼ਬਦਾਵਲੀ ਛੱਡੋ', 'ਸਿੱਖਣ ਵਾਲੇ ਦੇ ਪੱਧਰ ਤੇ ਆਓ', 'ਸੌਖੀਆਂ ਉਦਾਹરણਾਂ ਨਾਲ ਸਮਝਾਓ'],
    urTitle: 'علم کی نحوست (Curse of Knowledge)', urSummary: 'کسی موضوع کا ماہر بننے کے بعد اس بات کو سمجھنے سے قاصر رہنا کہ مبتدی کو یہ کیوں سمجھ نہیں آ رہا۔', urTakeaways: ['تکنیکی اصطلاحات سے پرہیز کریں', 'اناڑی کے نقطہ نظر سے سوچیں', 'آسان مثالوں سے سمجھائیں'],
    orTitle: 'ଜ୍ଞାନର ଅଭିଶାପ (Curse of Knowledge)', orSummary: 'ନିଜେ କୌଣସି ବିଷୟ ଜାଣିବା ପରେ, ଅଜ୍ଞ ବ୍ୟକ୍ତିର ମାନସିକ ସ୍ଥିତିକୁ ବୁଝିବାରେ ଅସମର୍ଥ ହେବାର ମନୋବୃତ୍ତି।', orTakeaways: ['କଠିନ ଶବ୍ଦ ବ୍ୟବହାର କରନ୍ତୁ ନାହିଁ', 'ନୂଆ ଶିଖୁଥିବା ଲୋକର ସ୍ତର ବୁଝନ୍ତୁ', 'ସରଳ ଉଦାହରଣ ଦିଅନ୍ତୁ'],
    asTitle: 'জ্ঞানৰ অভিশাপ (Curse of Knowledge)', asSummary: 'কোনো কথা নিজে বুজি পোৱাৰ পিছত আনৰ বাবে সেইটো বুজি পোৱা কিয় টান সেয়া অনুভৱ কৰিব নোৱৰা মানসিকতা।', asTakeaways: ['কঠিন পৰিভাষা পৰিহাৰ কৰক', 'নতুন শিকাৰুৰ দৃষ্টিৰে চাওক', 'সহজ উদাহৰণেৰে বুজাওক']
  },

  {
    fileName: 'desirableDifficulties.ts',
    varName: 'desirable_difficulties',
    id: 'desirable_difficulties',
    categoryId: 'learning_psychology',
    slug: 'desirable-difficulties',
    difficulty: 'advanced',
    readTime: 6,
    sortWeight: 9,
    titleEn: 'Desirable Difficulties: Why Effortful Friction Creates Mastery',
    subtitleEn: 'Robert and Elizabeth Bjork’s framework on why short-term struggle creates long-term durability.',
    shortDescEn: 'Learning conditions that introduce cognitive friction, effort, and temporary setbacks, which slow down initial acquisition but dramatically optimize long-term retention and transfer.',
    oneLineEn: 'If it feels easy and flowing, you aren’t learning; ease is the enemy of durability.',
    summary30sEn: 'Introduced in 1994 by UCLA cognitive psychologist Robert Bjork, the concept of "Desirable Difficulties" revolutionized pedagogical science. Bjork distinguished between *performance* (what is measurable right now during study) and *learning* (permanent neurological modification). Techniques that maximize rapid immediate performance (cramming, re-reading) lead to catastrophic rapid forgetting.',
    coreConceptEn: 'Memory storage operates under the "New Theory of Disuse": memories have both Retrieval Strength (accessibility in working memory) and Storage Strength (entrenched synaptic weight). When retrieval strength is high, studying does almost nothing to increase storage strength. Only when retrieval is difficult—forcing the brain to sweat and reconstruct traces—does storage strength multiply exponentially.',
    summary60sEn: 'Desirable difficulties include: spaced retrieval across days (spacing effect), mixing problem categories (interleaving), testing instead of studying (retrieval practice), varying the physical study environment, and self-generating answers. The key word is *desirable*: difficulties must be challenges the learner can successfully overcome, not bewildering confusion.',
    takeawaysEn: [
      'High immediate study performance is often an illusion that conceals zero long-term learning',
      'The harder it is to retrieve a memory, the more its permanent storage strength increases',
      'Spacing, interleaving, and self-testing are the core trio of desirable difficulties',
      'Welcome cognitive friction; smooth, effortless studying is a neurological dead end'
    ],
    whyItHappensEn: 'Synaptic consolidation requires biological stress: when retrieval is challenging, the hippocampus signals the cortex to allocate resources to reconstruct and reinforce pathways.',
    evolutionaryEn: 'Survival skills were acquired through life-and-death struggle and physical resistance; painless absorption was biologically impossible.',
    howItWorksEn: 'Memory allowed to partially decay -> Learner struggles to recall -> High cognitive effort expended -> Neural reconstructive circuits fire -> Storage strength surges -> Forgetting curve flattens.',
    visualHeadlineEn: 'Smooth Cramming vs. Desirable Difficulty Trajectory',
    visualDescEn: 'Robert Bjork’s performance vs. learning dichotomy.',
    sideALabelEn: 'Easy Cramming (Massed Review)',
    sideADetailEn: 'Day 1: 95% performance (feels amazing!). Day 7: 15% retention (catastrophic forgetting).',
    sideBLabelEn: 'Desirable Difficulty (Spaced Recall)',
    sideBDetailEn: 'Day 1: 50% performance (feels like a failure!). Day 7: 82% retention! (true durability).',
    researchSummaryEn: 'Bjork, R. A. (1994, Metacognition: Knowing about Knowing) and Bjork & Bjork (2011, Psychology of Learning and Motivation) synthesized decades of experimental evidence separating immediate performance from durable learning.',
    refAuthor: 'Bjork, R. A. & Bjork, E. L.',
    refYear: 2011,
    refTitle: 'Making Things Hard on Yourself, But in a Good Way: Creating Desirable Difficulties to Enhance Learning',
    refCitation: 'Bjork, E. L., & Bjork, R. A. (2011). Psych. of Learning and Motivation, 55, 59–68.',
    refDoi: 'https://doi.org/10.1016/B978-0-12-387693-5.00002-5',
    scenarioTitleEn: 'The NEET Repeater Breakthrough in Hyderabad',
    scenarioContextEn: 'Sai failed his first attempt at the NEET medical entrance exam in Hyderabad after spending 14 hours a day watching recorded online lectures and nodding along smoothly. In his second year, he completely stopped re-watching lectures; he forced himself to do closed-book question banks, getting 40% wrong daily, sweating with frustration. On the actual exam, he ranked in the top 0.5%.',
    scenarioBiasEn: 'In Year 1, Sai mistook effortless lecture-watching for learning. In Year 2, he leveraged desirable difficulties: the painful struggle of testing forged permanent synaptic connections.',
    scenarioOptimalEn: 'Embrace the feeling of struggle: if a study session feels relaxing and comfortable, stop immediately and test yourself with closed books.',
    scenarioReflectionEn: 'When studying, do you prefer activities that make you feel smart (like re-reading highlighted notes) or activities that expose what you don’t know (like flashcards)?',
    howToRecognizeEn: 'Feeling mentally fatigued, slightly frustrated, and humbled during study, but realizing days later that the material is etched permanently in your mind.',
    whereEn: 'High-stakes academic examinations, surgical residency training, flight simulator pilot certification, and foreign language fluency.',
    misconceptionsEn: 'Myth: "Effective studying should feel smooth, effortless, and fun." Fact: Effortless studying is largely an illusion of competence; real synaptic remodeling requires metabolic struggle.',
    limitationsEn: 'Difficulties are only "desirable" if the learner possesses the background knowledge and motivation to ultimately succeed; excessive difficulty without foundational scaffolding causes helplessness.',
    howToRespondEn: 'The Friction Protocol: For every hour of study, ensure at least 35 minutes are spent in difficult, active retrieval (doing practice problems, explaining aloud, closed-book testing).',
    defensesEn: [
      { title: 'The Delayed Retrieval Rule', instruction: 'Never test yourself on material immediately after reading it; wait at least 4 hours or sleep overnight so retrieval requires real cognitive work.' },
      { title: 'The Deliberate Error Welcome', instruction: 'Treat getting a practice question wrong not as a failure, but as the exact moment your brain triggers dopamine-driven memory updating.' }
    ],
    pqPromptEn: 'A student has a choice between two study methods for an anatomy exam next month. Method A: Re-reading the textbook until it feels completely fluent (takes 3 hours). Method B: Taking timed practice quizzes where they get 30% wrong and must look up the corrections (takes 3 hours). Which method produces higher retention?',
    pqScenarioEn: 'The student feels much more confident and relaxed using Method A during the session.',
    pqExplanationEn: 'Method B introduces desirable difficulties: struggling to retrieve answers and correcting errors cements neural storage strength far beyond passive fluent re-reading.',
    pqAntidoteEn: 'Choose effortful self-testing over passive familiarity, regardless of how stressful it feels in the moment.',
    pqOptionsEn: [
      { id: 'opt_a', text: 'Method A, because positive emotional confidence is the number one predictor of test performance.', isCorrect: false, feedback: 'Incorrect. Confidence is often a false signal of fluency.' },
      { id: 'opt_b', text: 'Method B, because effortful retrieval and error correction trigger deep neuroplastic consolidation (Desirable Difficulties).', isCorrect: true, feedback: 'Correct! The cognitive friction of Method B maximizes delayed test recall.' },
      { id: 'opt_c', text: 'Both methods are equal because the total time spent (3 hours) was identical.', isCorrect: false, feedback: 'Incorrect. Cognitive engagement mechanisms matter far more than raw study hours.' }
    ],
    reflectionPromptEn: 'What is one "easy" study habit you regularly rely on that you know in your heart is not creating durable memory?',
    titleHinglish: 'Desirable Difficulties: Mushkil Raaste Hi Manzil Tak Le Jate Hain',
    subtitleHinglish: 'Robert Bjork ki groundbreaking research: Padhai me jitni takleef aur friction hoga, exam me utna hi solid result aayega.',
    shortDescHinglish: 'Performance vs Learning: Easy lagne wali padhai turant bhool jati hai, jabki dimaag ko nichodne wali struggle hi permanent memory banati hai.',
    oneLineHinglish: 'Agar padhte waqt maza aa raha hai aur sab easy lag raha hai, to samajh lo dimaag kuch nahi seekh raha.',
    summary30sHinglish: 'UCLA ke professor Robert Bjork ne dekha ki students do cheezon me confuse ho jate hain: Immediate Performance (padhte waqt kaisa lag raha hai) aur Long-term Learning (1 mahine baad kitna yaad hai). Videos dekhna aur notes padhna easy lagta hai, par exam ke din dimaag blank ho jata hai.',
    coreConceptHinglish: 'Dimaag muscle ki tarah hai: Bina weight uthaye gym me body nahi banti. Jab aap kisi cheez ko dimaag se zabardasti bahar nikaalne ki koshish karte ho (Closed-book test, questions solve karna, galti karna), to dimaag par stress padta hai. Is friction ko Bjork ne "Desirable Difficulty" kaha hai.',
    summary60sHinglish: 'Neet aur JEE ke toppers rote nahi hain jab unke mock test me questions galat hote hain; wo khush hote hain kyuki galti hone se dimaag us connection ko permanent lock kar deta hai. Easy tareeqo se padhna band karo. Spacing, Testing aur Interleaving ko apnao.',
    howItWorksHinglish: 'Padhai shuru ki -> Closed-book questions lagaye -> Galtiyan hui -> Dimaag ne struggle kiya -> Correction check kiya -> Permanent neural pathways ban gaye.',
    howToRespondHinglish: 'Friction dhoondo: Agar revision easy lag raha hai, to kitab band karo aur bina dekhe khud ko test karo. Jo question galat ho, wahi aapki असली learning hai.',
    takeawaysHinglish: [
      'Padhte waqt aane wala confidence aksar jhootha hota hai (Illusion of fluency)',
      'Dimaag jitna zor lagayega, memory utni hi pathar ki lakeer banegi',
      'Galtiyan hona bura nahi hai, wahi dimaag ko update karne ka signal hai',
      'Comfortable study band karo, testing aur active recall se dimaag ko challenge karo'
    ],
    pqPromptHinglish: 'Method A: Notes ko 3 baar aaram se padhna (sukoon milta hai). Method B: Practice quiz lagana jisme 30% questions galat ho jayein aur dimaag thak jaye. Exam ke liye kaunsa better hai?',
    pqExplanationHinglish: 'Method B (Desirable Difficulties) dimaag ko zor lagane par majboor karta hai jisse exam me retention 80% rehta hai.',
    pqOptionsHinglish: [
      { id: 'opt_a', text: 'Method A, kyuki padhte waqt tension nahi honi chahiye.', isCorrect: false, feedback: 'Galat. Zero tension matlab zero retention.' },
      { id: 'opt_b', text: 'Method B, kyuki dimaag ka struggle aur galtiyon ka correction hi permanent memory banata hai.', isCorrect: true, feedback: 'Sahi! Yahi Desirable Difficulties ka core principle hai.' },
      { id: 'opt_c', text: 'Dono bekaar hain.', isCorrect: false, feedback: 'Galat.' }
    ],
    hiTitle: 'वांछनीय कठिनाइयां (Desirable Difficulties)',
    hiSummary: 'अध्ययन के दौरान मानसिक संघर्ष, त्रुटियों और प्रयास को शामिल करने से होने वाली दीर्घकालिक स्मृति सुदृढ़ीकरण का सिद्धांत।',
    hiTakeaways: ['सरल और सहज अध्ययन अक्सर सीखने का झूठा भ्रम होता है', 'जितना अधिक मानसिक प्रयास होगा, स्मृति उतनी ही स्थायी बनेगी', 'गलतियों को सीखने और सुधार के सबसे बड़े अवसर के रूप में अपनाएं'],
    guTitle: 'વાંછનીય મુશ્કેલીઓ (Desirable Difficulties)', guSummary: 'અભ્યાસમાં મુશ્કેલી અને સંઘર્ષ દ્વારા લાંબા ગાળાની યાદશક્તિ પાકી કરવાની વૈજ્ઞાનિક રીત.', guTakeaways: ['સરળ રસ્તો છોડો', 'મગજને કસરત કરાવો', 'ભૂલોમાંથી સાચું શીખો'],
    mrTitle: 'इच्छित अडचणी (Desirable Difficulties)', mrSummary: 'अभ्यासात येणारा बौद्धिक ताण आणि संघर्ष दीर्घकालीन स्मरणशक्तीसाठी कसा आवश्यक असतो याचे मानसशास्त्र.', mrTakeaways: ['सोप्या पद्धतींचा मोह सोडा', 'मेंदूला आव्हाने द्या', 'चुका दुरुस्त करून शिका'],
    teTitle: 'వాంఛనీయ కష్టాలు (Desirable Difficulties)', teSummary: 'చదివేటప్పుడు పడే మానసిక శ్రమ మరియు ఇబ్బందులే దీర్ఘకాలిక జ్ఞాపకశక్తికి బలమైన పునాది.', teTakeaways: ['సులువైన పద్ధతులను వీడండి', 'మెదడుకు శ్రమ కలిగించండి', 'తప్పుల నుండి నేర్చుకోండి'],
    taTitle: 'விரும்பத்தக்க கடினங்கள் (Desirable Difficulties)', taSummary: 'படிக்கும் போது ஏற்படும் மன சவால்களும் சிரமங்களுமே நீண்டகால நினைவாற்றலை உருவாக்கும் அறிவியல் உண்மை.', taTakeaways: ['எளிதான வழிகளை தவிருங்கள்', 'மூளைக்கு சவால் விடுங்கள்', 'தவறுகளிலிருந்து கற்றுக் கொள்ளுங்கள்'],
    knTitle: 'ಅಪೇಕ್ಷಣೀಯ ಕಷ್ಟಗಳು (Desirable Difficulties)', knSummary: 'ಕಲಿಯುವಾಗ ಎದುರಾಗುವ ಮಾನಸಿಕ ಸವಾಲುಗಳು ಮತ್ತು ಶ್ರಮವೇ ಶಾಶ್ವತ ನೆನಪಿಗೆ ಕಾರಣವಾಗುವ ಮನೋವಿಜ್ಞಾನ.', knTakeaways: ['ಸುಲಭದ ಹಾದಿ ಬಿಡಿ', 'ಮೆದುಳಿಗೆ ಕಷ್ಟ ಕೊಡಿ', 'ತಪ್ಪುಗಳಿಂದ ಕಲಿಯಿರಿ'],
    mlTitle: 'ആവശ്യമായ ബുദ്ധിമുട്ടുകൾ (Desirable Difficulties)', mlSummary: 'പഠനത്തിൽ ഉണ്ടാകുന്ന മാനസിക വെല്ലുവിളികളും പ്രയാസങ്ങളും ദീർഘകാല ഓർമ്മശക്തി വർദ്ധിപ്പിക്കുന്നു.', mlTakeaways: ['എളുപ്പവഴികൾ ഉപേക്ഷിക്കുക', 'മനസ്സിനെ പരിശീലിപ്പിക്കുക', 'തെറ്റുകൾ തിരുത്തി പഠിക്കുക'],
    bnTitle: 'বাঞ্ছনীয় প্রতিবন্ধকতা (Desirable Difficulties)', bnSummary: 'পড়ার সময় মানসিক শ্রম ও বাধার সম্মুখীন হওয়াই দীর্ঘমেয়াদী স্মৃতির ভিত্তি গড়ে তোলার বৈজ্ঞানিক সত্য।', bnTakeaways: ['সহজ উপায়ের মোহ ত্যাগ করুন', 'মস্তিষ্ককে চ্যালেঞ্জ জানান', 'ভুল থেকে স্থায়ী শিক্ষা নিন'],
    paTitle: 'ਲੋੜੀਂਦੀਆਂ ਮੁਸ਼ਕਿਲਾਂ (Desirable Difficulties)', paSummary: 'ਪੜ੍ਹਾਈ ਵਿੱਚ ਮਾਨਸਿਕ ਸੰਘਰਸ਼ ਅਤੇ ਔਖ ਹੀ ਲੰਬੇ ਸਮੇਂ ਦੀ ਪੱਕੀ ਯਾਦਦਾਸ਼ਤ ਬਣਾਉਣ ਦਾ ਅਸਲ ਤਰੀਕਾ ਹੈ।', paTakeaways: ['ਸੌਖੇ ਰਾਹਾਂ ਤੋਂ ਬਚੋ', 'ਦਿਮਾਗ ਤੇ ਜ਼ੋਰ ਪਾਓ', 'ਗ਼ਲਤੀਆਂ ਸੁਧਾਰ ਕੇ ਸਿੱਖੋ'],
    urTitle: 'پسندیدہ مشکلات (Desirable Difficulties)', urSummary: 'پڑھائی کے دوران ذہنی مشقت اور دشواری ہی دیرپا یادداشت اور مہارت پیدا کرنے کا ذریعہ ہے۔', urTakeaways: ['آسان راستوں سے پرہیز کریں', 'ذہن کو چیلنج دیں', 'غلطیوں سے سبق سیکھیں'],
    orTitle: 'ବାଞ୍ଛନୀୟ କଠିନତା (Desirable Difficulties)', orSummary: 'ପଢ଼ିବା ସମୟରେ ମାନସିକ ସଂଘର୍ଷ ଓ ପରିଶ୍ରମ ହିଁ ଦୀର୍ଘକାଳୀନ ସ୍ମୃତିର ପ୍ରକୃତ ଆଧାର।', orTakeaways: ['ସହଜ ଉପାୟ ଛାଡ଼ନ୍ତୁ', 'ମସ୍ତିଷ୍କକୁ ଚ୍ୟାଲେଞ୍ଜ କରନ୍ତୁ', 'ଭୁଲ୍ ସଂଶୋଧନ କରି ଶିଖନ୍ତୁ'],
    asTitle: 'বাঞ্ছনীয় জটিলতা (Desirable Difficulties)', asSummary: 'পঢ়াৰ সময়ত মানসিক সংগ্ৰাম আৰু প্ৰত্যাহ্বানেই স্থায়ী স্মৃতি গঢ়ি তোলাৰ প্ৰকৃত বৈজ্ঞানিক ভিত্তি।', asTakeaways: ['সহজ পথ পৰিহাৰ কৰক', 'মগজুক কষ্ট কৰিবলৈ দিয়ক', 'ভুলৰ পৰা স্থায়ী শিক্ষা লওক']
  },

  {
    fileName: 'feynmanTechnique.ts',
    varName: 'feynman_technique',
    id: 'feynman_technique',
    categoryId: 'learning_psychology',
    slug: 'the-feynman-technique',
    difficulty: 'beginner',
    readTime: 5,
    sortWeight: 10,
    titleEn: 'The Feynman Technique: Ultimate Mental Model Simplification',
    subtitleEn: 'Nobel laureate Richard Feynman’s 4-step framework for uncovering hidden ignorance and mastering any subject.',
    shortDescEn: 'A mental model for deep conceptual mastery where a learner identifies gaps in their understanding by attempting to explain a complex topic in simple language as if teaching a sixth-grader.',
    oneLineEn: 'If you cannot explain it to an 11-year-old in simple words, you don’t understand it yourself.',
    summary30sEn: 'Developed by Nobel Prize-winning theoretical physicist Richard Feynman (dubbed the "Great Explainer"), this 4-step learning protocol exposes the difference between knowing the *name* of something and knowing the *thing*. By forcing yourself to explain ideas without complex terminology, you strip away deceptive vocabulary masks.',
    coreConceptEn: 'Human beings regularly hide their conceptual deficits behind domain jargon (e.g. reciting that "gravity is the curvature of spacetime caused by mass-energy tensor fields" without having any intuitive grasp of what that means). The Feynman Technique consists of 4 distinct steps: 1) Choose a concept, 2) Teach it to a child without jargon, 3) Identify gaps and return to source material, 4) Simplify and create concrete analogies.',
    summary60sEn: 'This technique harnesses metacognition, the generation effect, and elaboration. When forced to explain quantum electrodynamics, calculus, or economics in everyday language, your brain must compress the underlying causal mechanisms into foundational first principles. Gaps in your explanation reveal exactly where your cognitive model is broken.',
    takeawaysEn: [
      'Knowing the name of a concept is completely different from understanding how it works',
      'Explaining ideas to a child exposes hidden knowledge gaps and false confidence',
      'The 4 steps: Choose concept -> Teach to a novice -> Pinpoint gaps -> Simplify & analogize',
      'Replace all domain jargon with concrete physical metaphors from everyday life'
    ],
    whyItHappensEn: 'Jargon operates as a semantic black box; decomposing the black box into simple mechanical primitives forces deep relational understanding.',
    evolutionaryEn: 'Early human culture transmitted fire-making and tool-crafting entirely through concrete demonstration and simple oral storytelling.',
    howItWorksEn: 'Select topic -> Take blank paper -> Write simple explanation for a 6th grader -> Hit stumbling block (jargon required) -> Re-open textbook -> Master the underlying primitive -> Complete the analogy.',
    visualHeadlineEn: 'The 4 Steps of the Feynman Protocol',
    visualDescEn: 'Richard Feynman’s conceptual distillation loop.',
    sideALabelEn: 'Jargon Mask (Shallow Knowledge)',
    sideADetailEn: '"Mitochondria is the powerhouse of the cell via ATP oxidative phosphorylation." (Recited from memory; zero real comprehension).',
    sideBLabelEn: 'Feynman Distillation (Deep Understanding)',
    sideBDetailEn: '"It’s like a tiny furnace in every brick of your body that burns food with oxygen to charge microscopic batteries." (Intuitive mastery!).',
    researchSummaryEn: 'Feynman (1985, Surely You\'re Joking, Mr. Feynman!) and Chi et al. (1994, Cognitive Science) demonstrated that self-explanation and teaching aloud produce massive gains in problem-solving transfer.',
    refAuthor: 'Feynman, R. P.',
    refYear: 1985,
    refTitle: 'Surely You\'re Joking, Mr. Feynman!: Adventures of a Curious Character',
    refCitation: 'Feynman, R. P. (1985). W. W. Norton & Company.',
    refDoi: 'https://doi.org/10.1063/1.2814641',
    scenarioTitleEn: 'The Machine Learning Interview in Gurugram',
    scenarioContextEn: 'Dev applied for a Data Scientist role in Gurugram. When asked how an artificial neural network learns, he regurgitated: "It computes the gradient of the loss function via the chain rule of backpropagation." When the interviewer asked: "Explain that as if I were a farmer," Dev froze, unable to formulate a single sentence.',
    scenarioBiasEn: 'Dev possessed name knowledge and mathematical jargon, but lacked first-principles mental models.',
    scenarioOptimalEn: 'Use the Feynman technique: "It’s like adjusting dials on a radio in the dark; you turn a knob slightly, see if the music gets clearer, and keep nudging it in that direction until the static vanishes."',
    scenarioReflectionEn: 'What is a concept in your profession that you regularly talk about using acronyms that you would struggle to explain to your mother?',
    howToRecognizeEn: 'Realizing that every time someone asks "how does that actually work?", you default to repeating complex definitions verbatim from a textbook.',
    whereEn: 'Technical interview preparation, teaching, scientific communication, executive presentations, and university exam revision.',
    misconceptionsEn: 'Myth: "Simplifying a topic makes it dumbed down and unscientific." Fact: Albert Einstein and Richard Feynman proved that simplifying a topic to its essence is the ultimate hallmark of genius.',
    limitationsEn: 'For highly technical mathematical derivations, simplification serves to build intuition; the formal mathematical rigor must still be practiced alongside it.',
    howToRespondEn: 'The Whiteboard Child Challenge: Grab an empty notebook and write down an explanation of your most difficult work problem as if explaining it to an 11-year-old child.',
    defensesEn: [
      { title: 'The Jargon Ban Protocol', instruction: 'Whenever you write notes, highlight every technical buzzword or acronym in red and rewrite the sentence using only words found in a children\'s dictionary.' },
      { title: 'The Analogy Generator', instruction: 'Find an everyday mechanical analogy (plumbing, cooking, sports) for every abstract algorithmic or theoretical process.' }
    ],
    pqPromptEn: 'A student claims they thoroughly understand blockchain technology because they can recite: "It is a decentralized, cryptographically secured, immutable distributed ledger." How can an educator verify if they actually understand it?',
    pqScenarioEn: 'The student memorized this exact definition from an online article.',
    pqExplanationEn: 'Reciting definitions is name knowledge. Asking the student to explain the mechanism using an everyday analogy (like an open ledger on a town square table) tests first-principles understanding.',
    pqAntidoteEn: 'Apply the Feynman test: ask them to explain how it works without using the words "cryptographic", "immutable", or "distributed".',
    pqOptionsEn: [
      { id: 'opt_a', text: 'Give them an A+ because their definition matches the textbook verbatim.', isCorrect: false, feedback: 'Incorrect. This measures rote recall, not conceptual mastery.' },
      { id: 'opt_b', text: 'Ask them to explain how a blockchain prevents double-spending using an analogy of a shared notebook among 5 friends without using any tech jargon.', isCorrect: true, feedback: 'Correct! The Feynman Technique strips away vocabulary and tests true causal comprehension.' },
      { id: 'opt_c', text: 'Ask them to spell the word "cryptographic" backwards.', isCorrect: false, feedback: 'Incorrect. Meaningless trivia test.' }
    ],
    reflectionPromptEn: 'Pick one concept you studied this week. Can you explain it right now in 3 simple sentences without using a single technical term?',
    titleHinglish: 'The Feynman Technique: Asli Samajh Ka 4-Step Formula',
    subtitleHinglish: 'Nobel prize winner Richard Feynman ka tareeqa: Kisi bhi mushkil cheez ko 10 saal ke bacche ko samjhane layak banana.',
    shortDescHinglish: 'Feynman Method: Definition ratne aur asli samajh ke beech ka farq jaan kar kisi bhi topic ke master banna.',
    oneLineHinglish: 'Agar aap kisi cheez ko simple shabdo me nahi samjha sakte, to sach yeh hai ki aapko khud samajh nahi aayi.',
    summary30sHinglish: 'Nobel prize winner physicist Richard Feynman ko "The Great Explainer" kaha jata tha. Unhone kaha ki kisi cheez ka "naam janna" aur us cheez ko "samajhna" do bilkul alag baatein hain. Jab aap bina technical words use kiye kisi cheez ko aasan bhasha me samjha lete ho, tabhi aap uske asli master bante ho.',
    coreConceptHinglish: 'Log aksar technical terms ke peeche apni ignorance chupate hain (Jaise bolna: "Mitochondria is the powerhouse of the cell"). Feynman ke 4 steps hain: 1) Topic chuno, 2) Ek 10 saal ke bacche ko aasan bhasha me samjhao, 3) Jahan ruko ya jargon bolna pade, wahan wapas book kholo aur gap door karo, 4) Real-life analogy banao.',
    summary60sHinglish: 'Coding interviews aur competitive exams me wahi log reject hote hain jo ratta maar kar aate hain. Agar aapse poocha jaye ki "Machine Learning kya hai?" aur aap bolo "Algorithm optimizing weights via loss function", to yeh ratta hai. Par agar aap bolo: "Yeh ek radio ke knob ghumane jaisa hai jahan gaana saaf aane tak hum switch hilate hain", to yeh Feynman mastery hai.',
    howItWorksHinglish: 'Topic padha -> Blank page par 10 saal ke bacche ke liye likha -> Jahan technical word aaya wahan ruk gaye -> Wapas padha aur basic primitive samjha -> Simple analogy banayi -> Master ban gaye.',
    howToRespondHinglish: 'Feynman Test lagao: Padhne ke baad khud se poocho: "Agar mujhe yeh apni nani ya 10 saal ke bhai ko samjhana ho, to main bina English words ke kaise samjhaunga?"',
    takeawaysHinglish: [
      'Bhaari-bharkam technical words aksar kamzori ko chupane ke liye use kiye jate hain',
      'Simple bhasha me bolna intelligence ka sabse bada saboot hai',
      'Feynman ke 4 steps: Chuno -> Bacche ko sikhao -> Gap identify karo -> Simplify karo',
      'Har abstract concept ke liye aam zindagi ka ek concrete example dhoondo'
    ],
    pqPromptHinglish: 'Ek student bolta hai: "Blockchain ek decentralized immutable cryptographic ledger hai." Kya wo sach me blockchain samajhta hai?',
    pqExplanationHinglish: 'Feynman technique ke mutabiq yeh sirf definition ratna hai. Asli samajh tab prove hogi jab wo bina technical terms ke 5 dosto ke khate ki analogy se samjha sake.',
    pqOptionsHinglish: [
      { id: 'opt_a', text: 'Haan, usne 100% sahi definition boli hai to wo master hai.', isCorrect: false, feedback: 'Galat. Yeh sirf bookish rote memorization hai.' },
      { id: 'opt_b', text: 'Nahi, jab tak wo bina jargon ke aam zindagi ke example se na samjhaye, tab tak yeh sirf name knowledge hai.', isCorrect: true, feedback: 'Sahi! Yahi Feynman Technique ka sabse bada lesson hai.' },
      { id: 'opt_c', text: 'Blockchain samajhna impossible hai.', isCorrect: false, feedback: 'Galat.' }
    ],
    hiTitle: 'फाइनमैन तकनीक (The Feynman Technique)',
    hiSummary: 'नोबेल पुरस्कार विजेता रिचर्ड फाइनमैन द्वारा प्रतिपादित 4-चरणीय शिक्षण मॉडल, जो किसी भी जटिल विषय को अत्यंत सरल भाषा में समझाने पर आधारित है।',
    hiTakeaways: ['किसी अवधारणा का नाम जानना और उसे समझना दो अलग बातें हैं', '10 वर्ष के बच्चे को समझाने से समझ की वास्तविक कमियां उजागर होती हैं', 'जटिल पारिभाषिक शब्दों के स्थान पर दैनिक जीवन के रूपकों का उपयोग करें'],
    guTitle: 'ફેનમેન ટેકનિક (સરળતાથી શીખવાની કળા)', guSummary: 'નોબેલ વિજેતા રિચાર્ડ ફેનમેનની કોઈપણ અઘરા વિષયને સરળ ભાષામાં સમજવાની ૪-પગલાંની પદ્ધતિ.', guTakeaways: ['સરળ ભાષામાં સમજાવો', 'ગોખણપટ્ટીથી દૂર રહો', 'વાસ્તવિક ઉદાહરણો વાપરો'],
    mrTitle: 'फेनमन तंत्र (Feynman Technique)', mrSummary: 'कोणताही कठीण विषय लहान मुलाला समजेल इतक्या सोप्या भाषेत मांडून त्यावर प्रभुत्व मिळवण्याची ४-टप्प्यांची पद्धत.', mrTakeaways: ['पारिभाषिक शब्दांमागे लपू नका', 'लहान मुलाला समजावून सांगा', 'ज्ञानातील त्रुटी ओळखून दूर करा'],
    teTitle: 'ఫెయిన్‌మాన్ పద్ధతి (Feynman Technique)', teSummary: 'ఏదైనా సంక్లిష్టమైన అంశాన్ని చిన్న పిల్లాడికి అర్థమయ్యేలా సులభమైన భాషలో వివరించి నైపుణ్యం సాధించే పద్ధతి.', teTakeaways: ['సాధారణ భాషలో వివరించండి', 'కంఠస్థం చేయవద్దు', 'అవగాహన లోపాలను సరిదిద్దుకోండి'],
    taTitle: 'ஃபெய்ன்மேன் நுட்பம் (Feynman Technique)', taSummary: 'எந்தவொரு கடினமான பாடத்தையும் ஒரு சிறுவனுக்கு புரியும் வகையில் எளிய மொழியில் கற்பித்து முழுமையாக புரிந்து கொள்ளும் முறை.', taTakeaways: ['எளிய மொழியில் விளக்குங்கள்', 'மனப்பாடம் செய்வதை தவிருங்கள்', 'புரிதலில் உள்ள இடைவெளிகளை நிரப்புங்கள்'],
    knTitle: 'ಫೆನ್‌ಮನ್ ತಂತ್ರಜ್ಞಾನ (Feynman Technique)', knSummary: 'ಯಾವುದೇ ಕಠಿಣ ವಿಷಯವನ್ನು ಪುಟ್ಟ ಮಗುವಿಗೆ ಅರ್ಥವಾಗುವಂತೆ ಸರಳ ಭಾಷೆಯಲ್ಲಿ ವಿವರಿಸಿ ಕಲಿಯುವ ೪ ಹಂತಗಳ ಮಾದರಿ.', knTakeaways: ['ಸರಳ ಭಾಷೆಯಲ್ಲಿ ವಿವರಿಸಿ', 'ಬಾಯಿಪಾಠ ಮಾಡುವುದನ್ನು ಬಿಡಿ', 'ಅರಿವಿನ ಕೊರತೆಗಳನ್ನು ಸರಿಪಡಿಸಿ'],
    mlTitle: 'ഫെയ്ൻമാൻ ടെക്നിക് (Feynman Technique)', mlSummary: 'ഏതൊരു സങ്കീർണ്ണമായ വിഷയവും ഒരു കൊച്ചുകുട്ടിക്ക് മനസ്സിലാകുന്ന ലളിതമായ ഭാഷയിൽ വിശദീകരിച്ച് പഠിക്കുന്ന രീതി.', mlTakeaways: ['ലളിതമായ ഭാഷയിൽ വിശദീകരിക്കുക', 'ഹൃദിസ്ഥമാക്കൽ ഉപേക്ഷിക്കുക', 'അറിവിലെ വിടവുകൾ നികത്തുക'],
    bnTitle: 'ফাইনম্যান পদ্ধতি (Feynman Technique)', bnSummary: 'যেকোনো জটিল বিষয়কে একজন শিশুর কাছে সহজ ভাষায় ব্যাখ্যা করার মাধ্যমে প্রকৃত জ্ঞান অর্জনের ৪-ধাপের বৈজ্ঞানিক মডেল।', bnTakeaways: ['সহজ ভাষায় প্রকাশ করুন', 'মুখস্থ বিদ্যার ফাঁদ এড়িয়ে চলুন', 'বাস্তব জীবনের উদাহরণের সাহায্য নিন'],
    paTitle: 'ਫਾਈਨਮੈਨ ਤਕਨੀਕ (Feynman Technique)', paSummary: 'ਕਿਸੇ ਵੀ ਔਖੇ ਵਿਸ਼ੇ ਨੂੰ ਇੱਕ ਨਿੱਕੇ ਬੱਚੇ ਨੂੰ ਸਮਝਾਉਣ ਵਾਂਗ ਸੌਖੀ ਬੋਲੀ ਵਿੱਚ ਬਿਆਨ ਕਰਕੇ ਮੁਹਾਰਤ ਹਾਸਲ ਕਰਨ ਦਾ ਢੰਗ।', paTakeaways: ['ਸੌਖੀ ਬੋਲੀ ਵਿੱਚ ਸਮਝਾਓ', 'ਰੱਟਾ ਲਾਉਣ ਤੋਂ ਬਚੋ', 'ਸਮਝ ਦੀਆਂ ਕਮੀਆਂ ਦੂਰ ਕਰੋ'],
    urTitle: 'فائن مین تکنیک (Feynman Technique)', urSummary: 'کسی بھی پیچیدہ تصور کو ایک بچے کو سمجھانے کی طرح آسان زبان میں پیش کر کے مکمل مہارت حاصل کرنے کا طریقہ۔', urTakeaways: ['آسان زبان میں بیان کریں', 'رٹا لگانے سے گریز کریں', 'علم کی خامیوں کو دور کریں'],
    orTitle: 'ଫାଇନମ୍ୟାନ୍ କୌଶଳ (Feynman Technique)', orSummary: 'ଯେକୌଣସି ଜଟିଳ ବିଷୟକୁ ଜଣେ ଛୋଟ ପିଲାକୁ ବୁଝାଇବା ଭଳି ସରଳ ଭାଷାରେ ବ୍ୟାଖ୍ୟା କରି ପାରଙ୍ଗମ ହେବାର ୪-ସ୍ତରୀୟ ପଦ୍ଧତି।', orTakeaways: ['ସରଳ ଭାଷାରେ ବୁଝାନ୍ତୁ', 'ମୁଖସ୍ଥ କରିବା ଛାଡ଼ନ୍ତୁ', 'ଅବବୋଧର ତ୍ରୁଟି ସୁଧାରନ୍ତୁ'],
    asTitle: 'ফাইনমেন কৌশল (Feynman Technique)', asSummary: 'যিকোনো জটিল বিষয় এটা শিশুৱে বুজি পোৱাকৈ সহজ ভাষাত ব্যাখ্যা কৰি প্ৰকৃত জ্ঞান আহৰণ কৰাৰ ৪-স্তৰীয় আৰ্হি।', asTakeaways: ['সহজ ভাষাত বুজাওক', 'মুখস্থ কৰা ত্যাগ কৰক', 'বুজি পোৱাৰ ঘাটি পূৰণ কৰক']
  }
];

