import { ComprehensiveTopicDef } from '../topicGeneratorHelper';

export const RELATIONSHIPS_TOPICS: ComprehensiveTopicDef[] = [
  {
    fileName: 'attachmentStylesAdults.ts',
    varName: 'attachment_styles_adults',
    id: 'attachment_styles_adults',
    categoryId: 'relationships_comm',
    slug: 'attachment-styles-adults',
    difficulty: 'intermediate',
    readTime: 6,
    sortWeight: 5,
    titleEn: 'Adult Attachment Theory: Anxious, Avoidant, and Secure Bonds',
    subtitleEn: 'How early childhood caregiver dynamics shape romantic intimacy, conflict styles, and emotional security.',
    shortDescEn: 'The psychological framework developed by Bowlby, Ainsworth, and Hazan-Shaver describing how internal working models of trust govern adult relationship intimacy.',
    oneLineEn: 'Your relationship conflict style is often an echo of your earliest childhood attachment blueprint.',
    summary30sEn: 'Originating from John Bowlby’s attachment theory and adapted for adults by Hazan and Shaver in 1987, adult attachment styles (Secure, Anxious-Preoccupied, Dismissive-Avoidant, and Fearful-Avoidant) explain why some people crave constant closeness while others flee at the first sign of emotional intimacy.',
    coreConceptEn: 'Attachment styles reflect neural "internal working models" about whether others are trustworthy and whether oneself is worthy of love. In romantic relationships, stress activates the attachment system: anxious individuals hyperactivate (protest behavior, clinging), avoidants deactivate (stonewalling, emotional distancing), while secures communicate vulnerably.',
    summary60sEn: 'The classic "Anxious-Avoidant Trap" occurs when an anxious partner senses distance and demands closeness, which triggers the avoidant partner’s fear of engulfment, causing them to pull away further. Recognizing that these are automated survival adaptations rather than malicious intent is the first step toward "Earned Security."',
    takeawaysEn: [
      'Attachment styles are learned coping blueprints, not immutable biological destiny',
      'The Anxious-Avoidant trap is the most common and exhausting relational dynamic',
      'Protest behaviors (calling 30 times, silent treatment) are maladaptive cries for safety',
      'Earned Security can be developed through self-awareness and secure relationship modeling'
    ],
    whyItHappensEn: 'Infant survival depended 100% on caregiver proximity; inconsistent or cold caregiving forced infants to develop hyperactivating or deactivating strategies.',
    evolutionaryEn: 'In dangerous ancestral environments, having individuals with hyper-vigilance (anxious) and self-reliance (avoidant) provided distinct tribal survival advantages.',
    howItWorksEn: 'Relationship friction occurs -> Attachment system triggers -> Anxious feels abandoned (demands attention) -> Avoidant feels trapped (shuts down) -> Escalation spiral -> Eventual emotional exhaustion.',
    visualHeadlineEn: 'The Anxious-Avoidant Feedback Loop',
    visualDescEn: 'How complementary attachment insecurities feed and amplify each other.',
    sideALabelEn: 'Anxious Partner (Hyperactivation)',
    sideADetailEn: '"You are emotionally distant; I must call and text until I confirm you still love me."',
    sideBLabelEn: 'Avoidant Partner (Deactivation)',
    sideBDetailEn: '"You are suffocating me with demands; I must withdraw into my cave to feel safe."',
    researchSummaryEn: 'Hazan & Shaver (1987, JPSP) and Mikulincer & Shaver (2007) proved that roughly 50% of adults are Secure, 20% Anxious, 25% Avoidant, and 5% Fearful, strongly predicting relationship longevity.',
    refAuthor: 'Hazan, C. & Shaver, P.',
    refYear: 1987,
    refTitle: 'Romantic Love Conceptualized as an Attachment Process',
    refCitation: 'Hazan, C., & Shaver, P. (1987). Journal of Personality and Social Psychology, 52(3), 511–524.',
    refDoi: 'https://doi.org/10.1037/0022-3514.52.3.511',
    scenarioTitleEn: 'The WhatsApp Blue Tick Panic in Delhi',
    scenarioContextEn: 'Kavita and Siddharth had been dating in South Delhi for 8 months. When Siddharth didn\'t reply to a message for three hours despite being online, Kavita sent 14 texts accusing him of losing interest. Siddharth felt overwhelmed, switched his phone off, and didn\'t call for two days.',
    scenarioBiasEn: 'Kavita\'s anxious attachment triggered catastrophic abandonment fears; Siddharth\'s avoidant attachment triggered defensive deactivation.',
    scenarioOptimalEn: 'Kavita self-soothes her physiological panic without texting; Siddharth communicates clearly: "I am in a tight deadline meeting until 7 PM; I love you and will call you as soon as I finish."',
    scenarioReflectionEn: 'When you feel insecure in a relationship, is your natural instinct to pursue and demand connection, or to retreat and become self-reliant?',
    howToRecognizeEn: 'Notice if relationship disagreements quickly trigger either a panic of abandonment (anxious) or a feeling of suffocation and urge to run away (avoidant).',
    whereEn: 'Dating apps, marriage negotiations, long-distance relationships, and parent-child conflicts.',
    misconceptionsEn: 'Myth: "Avoidant people have no feelings and don\'t want love." Fact: Avoidant individuals desire intimacy equally, but experience severe physiological panic when intimacy requires vulnerability.',
    limitationsEn: 'Attachment styles are spectrum tendencies, not rigid diagnostic disorders; people can be secure with friends but anxious with romantic partners.',
    howToRespondEn: 'Practice Secure Communication: State your emotional need directly without protest behavior: "I am feeling disconnected right now and would love 15 minutes of uninterrupted conversation tonight."',
    defensesEn: [
      { title: 'The Anti-Protest Pause', instruction: 'If you feel the urge to send angry paragraphs or give the silent treatment, wait 2 hours until your nervous system calms down.' },
      { title: 'The Reassurance Bridge', instruction: 'If you need space, always provide a clear return time: "I need 30 minutes to calm down, and I will be back at 8:00 PM to talk."' }
    ],
    pqPromptEn: 'During an argument, your partner shuts down and says "I can\'t deal with this right now" and looks away. As an emotionally intelligent communicator, what is the best interpretation?',
    pqScenarioEn: 'Your partner’s heart rate is elevated and they appear emotionally frozen.',
    pqExplanationEn: 'Avoidant withdrawal during conflict is usually a physiological deactivation response to flooding, not callous indifference. Demanding immediate engagement worsens the shutdown.',
    pqAntidoteEn: 'Respect the need for biological de-escalation while agreeing on a specific time to resume the discussion.',
    pqOptionsEn: [
      { id: 'opt_a', text: 'Follow them from room to room demanding they answer your questions immediately.', isCorrect: false, feedback: 'Incorrect. This intensifies physiological flooding.' },
      { id: 'opt_b', text: 'Say: "I see you are overwhelmed. Let’s take a 20-minute break, and let’s sit down together at 8:30 PM to resolve this."', isCorrect: true, feedback: 'Correct! This provides psychological safety and structured reconnection.' },
      { id: 'opt_c', text: 'Pack your bags and threaten divorce to force them to speak.', isCorrect: false, feedback: 'Incorrect. This is destructive protest behavior.' }
    ],
    reflectionPromptEn: 'How can you offer clear, predictable reassurance to the people you care about when you are feeling busy or stressed?',
    titleHinglish: 'Adult Attachment Theory: Pyaar Me Hum Kyu Darrte Hain',
    subtitleHinglish: 'Bachpan ke anubhav kaise tay karte hain ki hum relationship me chipakne lagte hain ya bhaagne lagte hain.',
    shortDescHinglish: 'John Bowlby aur Hazan-Shaver ki psychological theory: Anxious aur Avoidant attachment styles kaise rishto ko affect karti hain.',
    oneLineHinglish: 'Rishto ke jhagde aksar bachpan ke purane darr ka reflection hote hain.',
    summary30sHinglish: 'Attachment theory batati hai ki log pyaar me do tarah se react karte hain: Anxious log jinko lagta hai samne wala chhod kar chala jayega, aur Avoidant log jinko lagta hai pyaar unki azaadi cheen lega. In dono ka rishta sabse exhausting hota hai.',
    coreConceptHinglish: 'Stress me hamara dimaag bachpan ka survival mode chalu kar deta hai. Anxious insaan baar-baar call karke reassurance chahta hai (protest behavior), jabki avoidant insaan phone switch off karke akelepan me bhaagta hai.',
    summary60sHinglish: 'Agar aapka partner message ka reply na aane par gussa ho jata hai, to wo bura insaan nahi balki anxious attachment se lad raha hai. Aur agar koi ladai ke waqt chup ho jata hai, to wo pathar dil nahi balki overwhelmed ho chuka hai. Dono ko samjhna hi mature rishta banata hai.',
    howItWorksHinglish: 'Jhagda hua -> Anxious ko laga "yeh mujhe chhod dega" (over-messaging shuru) -> Avoidant ko laga "meri azaadi khatam" (phone band kiya) -> Jhagda badh gaya.',
    howToRespondHinglish: 'Direct baat karein: "Mujhe abhi insecure feel ho raha hai, kya hum 10 minute baat kar sakte hain?" Aur agar space chahiye to bolen: "Main 30 minute baad aakar baat karta hu."',
    takeawaysHinglish: [
      'Attachment styles bachpan ke blueprints hain, par unhe mature communication se badla ja sakta hai',
      'Anxious-Avoidant loop rishton ka sabse common aur thaka dene wala pattern hai',
      'Gusse me 50 messages bhejna ya bilkul baat band karna (Silent treatment) dono bachkaana tareeqe hain',
      'Space maangte waqt hamesha waqt batao: "Main 1 ghante me aakar baat karunga"'
    ],
    pqPromptHinglish: 'Ladaai ke waqt aapka partner bolta hai "Mujhe abhi baat nahi karni" aur chup ho jata hai. Sahi reaction kya hoga?',
    pqExplanationHinglish: 'Jab koi overwhelmed ho jata hai to usse 20-30 minute ka break chahiye hota hai taaki wo shant ho sake.',
    pqOptionsHinglish: [
      { id: 'opt_a', text: 'Uske peeche-peeche jao aur bolo jab tak jawab nahi doge main jane nahi dunga.', isCorrect: false, feedback: 'Galat. Isse samne wala aur zyada shut down hoga.' },
      { id: 'opt_b', text: 'Bolo: "Theek hai, 20 minute ka break lete hain, 9 baje chai ke sath baat karenge."', isCorrect: true, feedback: 'Sahi! Yeh space aur reassurance dono provide karta hai.' },
      { id: 'opt_c', text: 'Turant status laga do ki single hona hi behtar hai.', isCorrect: false, feedback: 'Galat. Yeh childish protest behavior hai.' }
    ],
    hiTitle: 'वयस्क लगाव सिद्धांत (Adult Attachment Theory)',
    hiSummary: 'बचपन के अनुभव कैसे वयस्क प्रेम संबंधों में निकटता, सुरक्षा और विवादों को प्रभावित करते हैं।',
    hiTakeaways: ['लगाव शैलियाँ सीखी हुई प्रवृत्तियाँ हैं', 'चिंतित और पलायनवादी चक्र सबसे आम है', 'स्पष्ट और सुरक्षित संवाद से बदलाव संभव है'],
    guTitle: 'પુખ્ત જોડાણ સિદ્ધાંત (Attachment Theory)', guSummary: 'બાળપણના અનુભવો પુખ્ત વયના સંબંધોમાં વિશ્વાસ અને ભયને કેવી રીતે આકાર આપે છે.', guTakeaways: ['સંબંધોની શૈલી સમજો', 'અસલામતી દૂર કરો', 'ખુલ્લી વાતચીત કરો'],
    mrTitle: 'प्रौढ भावनिक अनुबंध सिद्धांत', mrSummary: 'लहानपणीचे अनुभव प्रौढ वयातील नातेसंबंधांमधील जवळीक आणि संवादावर कसा प्रभाव टाकतात.', mrTakeaways: ['भावनिक शैली ओळखा', 'संवादात स्पष्टता ठेवा', 'सुरक्षित नातेसंबंध जोपासा'],
    teTitle: 'వయోజన అనుబంధ సిద్ధాంతం (Attachment Theory)', teSummary: 'బాల్య అనుభవాలు పెద్దయ్యాక ప్రేమ సంబంధాలలో భద్రత మరియు నమ్మకాన్ని ఎలా నిర్దేశిస్తాయి.', teTakeaways: ['అనుబంధ శైలిని గుర్తించండి', 'అభద్రతా భావాన్ని అధిగమించండి', 'స్పష్టమైన సంభాషణ అవసరం'],
    taTitle: 'வயதுவந்தோர் பிணைப்புக் கோட்பாடு', taSummary: 'குழந்தைப் பருவ அனுபவங்கள் எவ்வாறு பெரியவர்களின் காதல் மற்றும் திருமண உறவுகளை பாதிக்கின்றன.', taTakeaways: ['பிணைப்பு முறையை புரிந்து கொள்ளுங்கள்', 'பயத்தை தவிருங்கள்', 'வெளிப்படையான உரையாடல் நன்று'],
    knTitle: 'ವಯಸ್ಕ ಬಾಂಧವ್ಯ ಸಿದ್ಧಾಂತ (Attachment Theory)', knSummary: 'ಬಾಲ್ಯದ ಅನುಭವಗಳು ವಯಸ್ಕರ ಪ್ರೇಮ ಮತ್ತು ವೈವಾಹಿಕ ಸಂಬಂಧಗಳ ಮೇಲೆ ಹೇಗೆ ಪ್ರಭಾವ ಬೀರುತ್ತವೆ.', knTakeaways: ['ಬಾಂಧವ್ಯದ ಶೈಲಿಯನ್ನು ಅರಿಯಿರಿ', 'ಅಭದ್ರತೆಯನ್ನು ದೂರವಿಡಿ', 'ನೇರ ಸಂವಹನ ನಡೆಸಿ'],
    mlTitle: 'മുതിർന്നവരിലെ അറ്റാച്ച്മെന്റ് സിദ്ധാന്തം', mlSummary: 'കുട്ടിക്കാലത്തെ അനുഭവങ്ങൾ മുതിർന്നവരുടെ പ്രണയബന്ധങ്ങളെയും വിവാഹജീവിതത്തെയും എങ്ങനെ സ്വാധീനിക്കുന്നു.', mlTakeaways: ['വൈകാരിക ശൈലി തിരിച്ചറിയുക', 'അരക്ഷിതാവസ്ഥ മാറ്റുക', 'തുറന്ന സംസാരം ശീലിക്കുക'],
    bnTitle: 'প্রাপ্তবয়স্কদের সংযুক্তি তত্ত্ব', bnSummary: 'শৈশবের অভিজ্ঞতা কীভাবে পরিণত বয়সের প্রেমের সম্পর্কে বিশ্বাস এবং টানাপোড়েন তৈরি করে।', bnTakeaways: ['মানসিক প্যাটার্ন বুঝুন', 'ভয় এড়িয়ে চলুন', 'খোলামেলা কথা বলুন'],
    paTitle: 'ਬਾਲਗ ਲਗਾਓ ਸਿਧਾਂਤ (Attachment Theory)', paSummary: 'ਬਚਪਨ ਦੇ ਤਜਰਬੇ ਕਿਵੇਂ ਵੱਡੇ ਹੋ ਕੇ ਰਿਸ਼ਤਿਆਂ ਵਿੱਚ ਨੇੜਤਾ ਅਤੇ ਵਿਵਾਦਾਂ ਨੂੰ ਪ੍ਰਭਾਵਿਤ ਕਰਦੇ ਹਨ।', paTakeaways: ['ਲਗਾਓ ਦੀ ਸ਼ੈਲੀ ਨੂੰ ਪਛਾਣੋ', 'ਡਰ ਅਤੇ ਸ਼ੱਕ ਛੱਡੋ', 'ਸਾਫ਼ ਗੱਲਬਾਤ ਕਰੋ'],
    urTitle: 'بالغوں کا وابستگی کا نظریہ (Attachment Theory)', urSummary: 'بچپن کے تجربات کس طرح بالغ رشتوں میں قربت، جھجک اور بے چینی کو جنم دیتے ہیں۔', urTakeaways: ['جذباتی انداز کو سمجھیں', 'عدم تحفظ پر قابو پائیں', 'واضح بات چیت اپنائیں'],
    orTitle: 'ପ୍ରାପ୍ତବୟସ୍କ ଆସକ୍ତି ତତ୍ତ୍ୱ', orSummary: 'ବାଲ୍ୟକାଳର ଅନୁଭୂତି କିପରି ବୟସ୍କ ସମ୍ପର୍କରେ ନିରାପତ୍ତା ଓ ବିଶ୍ୱାସକୁ ପ୍ରଭାବିତ କରେ।', orTakeaways: ['ସମ୍ପର୍କ ଶୈଳୀ ବୁଝନ୍ତୁ', 'ଅସୁରକ୍ଷିତ ଭାବନା ଦୂର କରନ୍ତୁ', 'ସ୍ପଷ୍ଟ ଆଲୋଚନା କରନ୍ତୁ'],
    asTitle: 'প্ৰাপ্তবয়স্কৰ আসক্তি তত্ত্ব', asSummary: 'শৈশৱৰ অভিজ্ঞতাই কেনেকৈ প্ৰাপ্তবয়স্কৰ বৈবাহিক আৰু প্ৰেমৰ সম্পৰ্কসমূহ গঢ় দিয়ে।', asTakeaways: ['সম্পৰ্কৰ ধৰণ বুজি লওক', 'ভয় আৰু দ্বিধা এৰক', 'স্পষ্ট যোগাযোগ বজাই ৰাখক']
  },

  {
    fileName: 'michelangeloPhenomenon.ts',
    varName: 'michelangelo_phenomenon',
    id: 'michelangelo_phenomenon',
    categoryId: 'relationships_comm',
    slug: 'michelangelo-phenomenon',
    difficulty: 'intermediate',
    readTime: 5,
    sortWeight: 6,
    titleEn: 'The Michelangelo Phenomenon: How Partners Sculpt Each Other',
    subtitleEn: 'Caryl Rusbult’s interpersonal model showing that close partners sculpt one another toward their ideal selves.',
    shortDescEn: 'The interpersonal process in which close romantic partners affirm and elicit each other’s ideal self-conceptions, much like Michelangelo carving the hidden angel out of marble.',
    oneLineEn: 'A great partner does not try to change you; they help you become who you wish to be.',
    summary30sEn: 'Named after Michelangelo’s famous assertion that the sculpture already exists inside the raw marble and the sculptor merely chips away the excess, Caryl Rusbult showed that loving partners who affirm your core aspirations physically help you unlock your ideal potential.',
    coreConceptEn: 'Partner affirmation occurs when a partner views and treats you in ways that align with your ideal self (your core aspirational goals and virtues). Over years, behavioral confirmation leads individuals to actualize their latent aspirations, enhancing relationship vitality and personal self-esteem.',
    summary60sEn: 'The opposite of the Michelangelo phenomenon is "Pygmalion Sculpting", where a partner attempts to mold you into who *they* want you to be according to their selfish preferences. Michelangelo sculpting is selfless: it mirrors back your own highest dreams and gently supports your growth toward them.',
    takeawaysEn: [
      'Michelangelo sculpting supports YOUR ideal self, not your partner\'s selfish demands',
      'Partner affirmation acts as a daily biological incubator for personal growth and courage',
      'Pygmalion manipulation breeds resentment; genuine affirmation breeds profound intimacy',
      'Couples with high mutual sculpting experience significantly higher long-term marital satisfaction'
    ],
    whyItHappensEn: 'Humans are social organisms whose self-concepts are continually shaped by the reflected appraisals of their primary attachment figures.',
    evolutionaryEn: 'Alliances where partners augmented each other’s competencies enhanced the overall resource acquisition and survivability of the family unit.',
    howItWorksEn: 'Individual holds ideal self aspirational goals -> Partner observes and affirms these ideals -> Partner creates low-risk environments to practice new skills -> Individual internalizes competence -> Ideal self is realized.',
    visualHeadlineEn: 'Michelangelo Sculpting vs. Pygmalion Imposition',
    visualDescEn: 'The crucial difference between unlocking a partner\'s potential vs. forcing your own desires on them.',
    sideALabelEn: 'Michelangelo Sculpting (Healthy Intimacy)',
    sideADetailEn: '"I see your deep passion for writing; let me handle the errands on Saturday so you can work on your novel."',
    sideBLabelEn: 'Pygmalion Imposition (Toxic Control)',
    sideBDetailEn: '"You need to dress differently and change careers because your choices embarrass me socially."',
    researchSummaryEn: 'Drigotas, Rusbult, Wieselquist & Whitton (1999, JPSP) proved that partner perceptual affirmation and partner behavioral affirmation directly predict personal growth and relationship durability.',
    refAuthor: 'Rusbult, C. E., Finkel, E. J., & Kumashiro, M.',
    refYear: 2009,
    refTitle: 'The Michelangelo Phenomenon',
    refCitation: 'Rusbult, C. E., et al. (2009). Current Directions in Psychological Science, 18(6), 305–309.',
    refDoi: 'https://doi.org/10.1111/j.1467-8721.2009.01657.x',
    scenarioTitleEn: 'The Reluctant Entrepreneur in Hyderabad',
    scenarioContextEn: 'Aditya had worked in IT support for 10 years in Hyderabad, secretly dreaming of opening an organic artisanal bakery. His family called it risky madness. His wife, Meera, remembered his passionate experiments with sourdough, bought him a professional oven for his birthday, and encouraged him to run weekend pop-ups.',
    scenarioBiasEn: 'Meera practiced authentic Michelangelo sculpting: she affirmed Aditya\'s latent ideal self when he lacked the courage to claim it alone.',
    scenarioOptimalEn: 'Celebrate and invest in your partner\'s authentic creative aspirations rather than imposing your own anxiety-driven safety demands.',
    scenarioReflectionEn: 'Does your partner\'s presence make you feel closer to the person you genuinely want to become?',
    howToRecognizeEn: 'Feeling energized, supported, and courageous in pursuing your authentic passions when around your partner, rather than judged or diminished.',
    whereEn: 'Marriage, creative partnerships, master-apprentice dynamics, and long-term friendships.',
    misconceptionsEn: 'Myth: "A good partner accepts you exactly as you are without wanting any change." Fact: Healthy partners accept you unconditionally, while actively helping you grow into your own chosen dreams.',
    limitationsEn: 'If a partner\'s "ideal self" is destructive (e.g., criminal aspirations or reckless gambles), unconditional affirmation is dangerous and boundary-setting is required.',
    howToRespondEn: 'Conduct the Ideal Self Interview: ask your partner: "What are two skills or virtues you want to cultivate this year, and how can I best support you in reaching them?"',
    defensesEn: [
      { title: 'The Aspirational Mirror', instruction: 'Verbally highlight moments when your partner demonstrates the virtues they aspire to: "I love how patiently you handled that difficult client today."' },
      { title: 'The Pygmalion Check', instruction: 'Audit your criticisms: are you trying to help them achieve their goals, or trying to make your own life more convenient?' }
    ],
    pqPromptEn: 'A spouse notices their partner wants to become healthier but struggles with gym consistency. What represents the Michelangelo Phenomenon?',
    pqScenarioEn: 'The partner often feels guilty and discouraged about their physical stamina.',
    pqExplanationEn: 'The Michelangelo Phenomenon involves creating affirmative, supportive structures that empower the partner’s chosen goal without shaming them.',
    pqAntidoteEn: 'Affirm their identity as a healthy person and offer practical collaborative support.',
    pqOptionsEn: [
      { id: 'opt_a', text: 'Shame them by pointing out their weight gain every time they reach for food.', isCorrect: false, feedback: 'Incorrect. Shaming triggers defensiveness and resentment.' },
      { id: 'opt_b', text: 'Offer to cook nutritious meals together and invite them for enjoyable weekend hiking trips.', isCorrect: true, feedback: 'Correct! This behaviorally affirms and supports their own ideal aspiration.' },
      { id: 'opt_c', text: 'Tell them they look fine and should give up on exercise completely.', isCorrect: false, feedback: 'Incorrect. This discourages their genuine personal goal.' }
    ],
    reflectionPromptEn: 'How can you actively support the hidden potential of someone you love this week without being overbearing?',
    titleHinglish: 'The Michelangelo Phenomenon: Partner Ka Best Version Nikaalna',
    subtitleHinglish: 'Ek sachha partner aapko badalna nahi chahta, balki aapko wo banne me madad karta hai jo aap banna chahte hain.',
    shortDescHinglish: 'Caryl Rusbult ki research: Kaise achhe partners ek doosre ke hidden potential ko nikaal kar life badal dete hain.',
    oneLineHinglish: 'Jaise shilpkaar patthar me se moorti nikaalta hai, waise partner aapka best version nikaalta hai.',
    summary30sHinglish: 'Michelangelo ne kaha tha: "Moorti patthar ke andar pehle se hoti hai, shilpkaar bas bekaar patthar ko hatata hai." Caryl Rusbult ne prove kiya ki loving partners wahi karte hain: wo aapke andar ke best potential ko pehchan kar use bahar nikaalte hain.',
    coreConceptHinglish: 'Do tarah ke partners hote hain: Pygmalion partner jo aapko apni marzi ke hisab se zabardasti badalna chahta hai, aur Michelangelo partner jo aapke khud ke sapno ko support karta hai aur aapko himmat deta hai.',
    summary60sHinglish: 'Agar aapka partner aapki drawing, coding ya business ke sapne ko seriously leta hai aur time nikaalne me madad karta hai, to wo Michelangelo sculpting kar raha hai. Aise rishte 10 guna zyada khushaal aur lambe chalte hain.',
    howItWorksHinglish: 'Aapka ek sapna hai -> Partner use respect karta hai -> Wo aapko practical help aur hosla deta hai -> Aapka confidence badhta hai -> Aap apna goal achieve kar lete hain.',
    howToRespondHinglish: 'Apne partner se pucho: "Tumhara is saal ka sabse bada sapna kya hai aur main usme tumhari kya madad kar sakta hu?"',
    takeawaysHinglish: [
      'Sahi partner aapko control nahi karta, balki aapke sapno ka sabse bada supporter banta hai',
      'Pygmalion partner apni ego ke liye aapko badalta hai, jabki Michelangelo partner aapke liye support karta hai',
      'Partner ki choti-choti achievements ko celebrate karna unka confidence 10 guna badha deta hai',
      'Pyaar ka matlab sirf sath rehna nahi, ek doosre ki growth ka reason banna hai'
    ],
    pqPromptHinglish: 'Aapka partner apna naya YouTube channel shuru karna chahta hai par darr raha hai. Michelangelo Phenomenon ke hisab se aapko kya karna chahiye?',
    pqExplanationHinglish: 'Partner ke authentic goal ko support karna aur himmat dena hi Michelangelo sculpting hai.',
    pqOptionsHinglish: [
      { id: 'opt_a', text: 'Bolna ki yeh sab bekaar hai aur chup chap job par focus karo.', isCorrect: false, feedback: 'Galat. Yeh unke sapne ko crush karna hai.' },
      { id: 'opt_b', text: 'Unka pehla video record karne me madad karna aur unki presentation skills ki tareef karna.', isCorrect: true, feedback: 'Sahi! Yeh unke ideal self ko realize karne me help karta hai.' },
      { id: 'opt_c', text: 'Kaho ki jab 10 lakh subscribers ho jayenge tabhi main video dekhunga.', isCorrect: false, feedback: 'Galat. Yeh unsupportive conditional attitude hai.' }
    ],
    hiTitle: 'माइकलएंजेलो परिघटना (Michelangelo Phenomenon)',
    hiSummary: 'कैसे एक आदर्श जीवनसाथी व्यक्ति के भीतर छिपे सर्वश्रेष्ठ रूप और महत्वाकांक्षाओं को निखारने में मदद करता है।',
    hiTakeaways: ['सच्चा साथी आपके सपनों का समर्थन करता है', 'पारस्परिक प्रोत्साहन व्यक्तिगत विकास को गति देता है', 'नियंत्रण के बजाय सहयोग से संबंध मजबूत होते हैं'],
    guTitle: 'માઇકલએન્જેલો ઘટના (સાથીદારનો વિકાસ)', guSummary: 'એક સારો સાથીદાર તમારી અંદર રહેલી શ્રેષ્ઠ પ્રતિભાને કેવી રીતે નિખારે છે.', guTakeaways: ['સાથીદારના સપનાને ટેકો આપો', 'પ્રેરણા આપો, નિયંત્રણ નહીં', 'સાથે મળીને વિકાસ કરો'],
    mrTitle: 'मायकेलएंजेलो सिद्धांत (नात्यातील विकास)', mrSummary: 'एक उत्तम जोडीदार आपल्यातील सुप्त गुणांना आणि ध्येयांना कशा प्रकारे आकार देतो.', mrTakeaways: ['जोडीदाराच्या स्वप्नांना पाठिंबा द्या', 'नियंत्रणाऐवजी सहकार्य करा', 'नात्यात परस्परांचा विकास साधा'],
    teTitle: 'మైఖేలాంజెలో దృగ్విషయం', teSummary: 'ఒక ఆదర్శ భాగస్వామి మీలోని దాగివున్న ఉత్తమ ప్రతిభను మరియు ఆశయాలను ఎలా వెలికితీస్తారో వివరించే సిద్ధాంతం.', teTakeaways: ['భాగస్వామి ఆశయాలను గౌరవించండి', 'నియంత్రణ వద్దు ప్రోత్సాహం ముద్దు', 'కలిసి ఎదగండి'],
    taTitle: 'மைக்கேலேஞ்சலோ நிகழ்வு (துணையின் சிற்பம்)', taSummary: 'ஒரு நல்ல வாழ்க்கைத்துணை உங்கள் உள் திறமைகளை செதுக்கி சிறந்த மனிதராக எவ்வாறு மாற்றுகிறார்.', taTakeaways: ['துணையின் கனவை ஆதரியுங்கள்', 'கட்டுப்படுத்தாமல் ஊக்கப்படுத்துங்கள்', 'இருவரும் இணைந்து முன்னேறுங்கள்'],
    knTitle: 'ಮೈಕೆಲ್ಯಾಂಜೆಲೋ ವಿದ್ಯಮಾನ', knSummary: 'ಉತ್ತಮ ಸಂಗಾತಿಯು ನಿಮ್ಮೊಳಗಿನ ಸುಪ್ತ ಪ್ರತಿಭೆ ಮತ್ತು ಕನಸುಗಳನ್ನು ಹೇಗೆ ಹೊರತರುತ್ತಾರೆ ಎಂಬ ತತ್ವ.', knTakeaways: ['ಸಂಗಾತಿಯ ಕನಸಿಗೆ ಬೆಂಬಲ ನೀಡಿ', 'ನಿಯಂತ್ರಿಸದೆ ಪ್ರೋತ್સાಹಿಸಿ', 'ಒಟ್ಟಾಗಿ ಬೆಳೆಯಿರಿ'],
    mlTitle: 'മൈക്കലാഞ്ചലോ പ്രതിഭാസം', mlSummary: 'ഒരു നല്ല പങ്കാളി നിങ്ങളുടെ ഉള്ളിലെ മികച്ച വ്യക്തിത്വത്തെയും ലക്ഷ്യങ്ങളെയും എങ്ങനെ വളർത്തിയെടുക്കുന്നു.', mlTakeaways: ['പങ്കാളിയുടെ ലക്ഷ്യങ്ങളെ പിന്തുണയ്ക്കുക', 'നിയന്ത്രിക്കാതെ പ്രോത്സാഹിപ്പിക്കുക', 'ഒരുമിച്ച് വളരുക'],
    bnTitle: 'মাইকেলেঞ্জেলো ঘটনা (সঙ্গীর রূপান্তর)', bnSummary: 'একজন আদর্শ জীবনসঙ্গী কীভাবে আপনার সুপ্ত প্রতিভা ও স্বপ্নকে বাস্তবে রূপ দিতে সাহায্য করে।', bnTakeaways: ['সঙ্গীর স্বপ্নকে সম্মান দিন', 'নিয়ন্ত্রণ নয় উৎসাহ দিন', 'একসাথে এগিয়ে চলুন'],
    paTitle: 'ਮਾਈਕਲਐਂਜਲੋ ਵਰਤਾਰਾ (ਸਾਥੀ ਦਾ ਵਿਕਾਸ)', paSummary: 'ਇੱਕ ਚੰਗਾ ਜੀਵਨ ਸਾਥੀ ਤੁਹਾਡੇ ਅੰਦਰ ਛੁਪੇ ਹੁਨਰ ਅਤੇ ਸੁਪਨਿਆਂ ਨੂੰ ਕਿਵੇਂ ਨਿਖਾਰਦਾ ਹੈ।', paTakeaways: ['ਸਾਥੀ ਦੇ ਸੁਪਨਿਆਂ ਦਾ ਸਾਥ ਦਿਓ', 'ਦਬਾਅ ਦੀ ਥਾਂ ਹੌਸਲਾ ਦਿਓ', 'ਮਿਲ ਕੇ ਤਰੱਕੀ ਕਰੋ'],
    urTitle: 'مائیکل اینجلو کا نظریہ (ساتھی کا نکھار)', urSummary: 'ایک مخلص ساتھی کس طرح آپ کی چھپی ہوئی صلاحیتوں اور خوابوں کو نکھارنے میں مددگار بنتا ہے۔', urTakeaways: ['ساتھی کے خوابوں کو سراہیں', 'کنٹرول کرنے کے بجائے حوصلہ دیں', 'باہمی ترقی کو فروغ دیں'],
    orTitle: 'ମାଇକେଲ୍‌ଆଞ୍ଜେଲୋ ଘଟଣା (ସାଥୀର ବିକାଶ)', orSummary: 'ଜଣେ ଉତ୍ତମ ଜୀବନସାଥୀ କିପରି ଆପଣଙ୍କ ଭିତରେ ଥିବା ସୁପ୍ତ ପ୍ରତିଭାକୁ ଜାଗ୍ରତ କରନ୍ତି।', orTakeaways: ['ସାଥୀଙ୍କ ସ୍ୱପ୍ନକୁ ସମର୍ଥନ କରନ୍ତୁ', 'ନିୟନ୍ତ୍ରଣ ବଦଳରେ ଉତ୍ସାହିତ କରନ୍ତୁ', 'ଏକାଠି ଆଗକୁ ବଢ଼ନ୍ତୁ'],
    asTitle: 'মাইকেলেঞ্জেলো পৰিঘটনা (সঙ্গীৰ বিকাশ)', asSummary: 'এগৰাকী ভাল সংগীয়ে কেনেকৈ আপোনাৰ অন্তৰ্নিহিত প্ৰতিভা আৰু সপোনক বাস্তৱ ৰূপ দিয়ে।', asTakeaways: ['সংগীৰ সপোনক উৎসাহিত কৰক', 'নিয়ন্ত্ৰণ নকৰি সহায় কৰক', 'একেসাথে আগবাঢ়ক']
  },

  {
    fileName: 'passiveAggressivePatterns.ts',
    varName: 'passive_aggressive_patterns',
    id: 'passive_aggressive_patterns',
    categoryId: 'relationships_comm',
    slug: 'passive-aggressive-patterns',
    difficulty: 'intermediate',
    readTime: 5,
    sortWeight: 7,
    titleEn: 'Passive-Aggression: Indirect Hostility and Covert Resistance',
    subtitleEn: 'The psychology of disguised anger, weaponized compliance, and chronic procrastination in relationships.',
    shortDescEn: 'A pattern of indirectly expressing negative feelings instead of openly addressing them, creating emotional erosion while maintaining plausible deniability.',
    oneLineEn: 'Saying "yes" with words while screaming "no" through delays, eye-rolls, and sulking.',
    summary30sEn: 'First identified clinically by the US War Department in 1945, passive-aggression is covert hostility. When people fear direct conflict or lack assertive communication skills, they express resentment through subtle sabotage: chronic lateness, weaponized incompetence, and sarcastic backhanded compliments.',
    coreConceptEn: 'Passive-aggression preserves "plausible deniability": the perpetrator can inflict emotional frustration on their target while claiming: "What are you talking about? I was just joking!" or "I forgot, why are you always so paranoid?" It shifts the burden of emotional dysregulation onto the victim.',
    summary60sEn: 'Underneath passive-aggressive behavior is a profound fear of vulnerability and powerlessness. The individual feels entitled to anger but terrified of direct confrontation. In families and workplaces, chronic passive-aggression is far more toxic than open conflict because open conflict can be resolved with facts, while covert hostility denies its own existence.',
    takeawaysEn: [
      'Passive-aggression stems from the dual desire to retaliate while evading accountability',
      'Plausible deniability ("I was only joking") is the primary psychological shield',
      'Calling out the underlying hostility directly forces covert dynamics into the light',
      'Never respond with counter passive-aggression; enforce calm, clear boundaries'
    ],
    whyItHappensEn: 'Childhood environments where direct anger was severely punished or forbidden taught individuals that indirect resistance was the only safe form of self-defense.',
    evolutionaryEn: 'Subordinate primates use covert sabotage and food-withholding to weaken despotic alpha leaders without risking direct lethal combat.',
    howItWorksEn: 'Resentment experienced -> Direct assertion avoided out of fear -> Covert sabotage planned (deliberate mistake or delay) -> Target reacts with anger -> Passive-aggressive acts innocent -> Target appears unstable.',
    visualHeadlineEn: 'Direct Assertive Communication vs. Covert Passive Sabotage',
    visualDescEn: 'Comparing the emotional clarity of honest conflict against the toxic ambiguity of indirect hostility.',
    sideALabelEn: 'Direct Assertion (Healthy)',
    sideADetailEn: '"I disagree with this project deadline; let’s negotiate realistic deliverables openly."',
    sideBLabelEn: 'Passive-Aggression (Toxic Ambiguity)',
    sideBDetailEn: 'Nods enthusiastically in the meeting, then deliberately submits incomplete work 3 days late with excuses.',
    researchSummaryEn: 'Kantor (2002, Passive-Aggression) and Millon (1993, Disorders of Personality) analyzed covert negativism and its clinical manifestation in interpersonal erosion and organizational paralysis.',
    refAuthor: 'Kantor, M.',
    refYear: 2002,
    refTitle: 'Passive-Aggression: A Guide for the Clinician, the Patient, and the Sufferer',
    refCitation: 'Kantor, M. (2002). Passive-Aggression. Praeger Publishers.',
    refDoi: 'https://doi.org/10.5860/choice.40-1854',
    scenarioTitleEn: 'The Sarcastic "Fine" in a Bangalore Flat',
    scenarioContextEn: 'Pooja asked her flatmate Rhea to clean her dishes before leaving for work. Rhea said "Fine, if you are that obsessed," washed three plates while slamming cabinets violently, and left one greasy pan directly on Pooja\'s laptop bag.',
    scenarioBiasEn: 'Rhea used weaponized compliance and covert sabotage: she complied outwardly while inflicting acoustic and physical retaliation.',
    scenarioOptimalEn: 'Address the covert pattern neutrally: "Rhea, when you slam cupboards and leave grease on my bag, it feels like you are angry about my request. Can we talk about household chores honestly?"',
    scenarioReflectionEn: 'Have you ever agreed to a request with a sweet smile while deliberately dragging your feet or making subtle mistakes to punish the requester?',
    howToRecognizeEn: 'Chronic sighing, sarcastic jokes followed by "relax, don\'t take everything so seriously," and deliberate "forgetting" of key commitments.',
    whereEn: 'Shared apartments, corporate email threads, extended family WhatsApp groups, and marital disputes.',
    misconceptionsEn: 'Myth: "Passive-aggressive people are evil masterminds." Fact: Most are deeply conflict-averse and terrified of rejection, resorting to covert tactics out of perceived helplessness.',
    limitationsEn: 'When living under tyrannical authoritarian regimes or physically abusive domestic situations, passive resistance can be a necessary survival tactic.',
    howToRespondEn: 'Name the Game: Point out the discrepancy between words and actions without anger: "You say everything is fine, but your body language and delayed emails suggest you are upset. What is really on your mind?"',
    defensesEn: [
      { title: 'The Reality Discrepancy Callout', instruction: 'Gently highlight the mismatch: "Your words said yes, but your tone felt angry. I want to hear your real opinion."' },
      { title: 'Refuse Plausible Deniability', instruction: 'Never accept sarcastic digs; respond with calm neutrality: "I don\'t understand the joke, could you explain what you meant?"' }
    ],
    pqPromptEn: 'A project teammate agrees to review your slides, but "forgets" three days in a row, then says: "Oops, sorry, I guess some of us have actual work to do! Just kidding!" What is the most effective response?',
    pqScenarioEn: 'The teammate smiles sweetly while delivering the passive-aggressive dig.',
    pqExplanationEn: 'Calling out the covert aggression calmly removes plausible deniability without escalating into a screaming match.',
    pqAntidoteEn: 'Address the pattern directly: ask for an explanation of the joke and re-establish the professional boundary.',
    pqOptionsEn: [
      { id: 'opt_a', text: 'Laugh nervously and apologize for asking for help.', isCorrect: false, feedback: 'Incorrect. This rewards the passive-aggressive tactic and invites further disrespect.' },
      { id: 'opt_b', text: 'Calmly look at them and ask: "What did you mean by actual work? If you are too busy, just tell me directly so I can find another reviewer."', isCorrect: true, feedback: 'Correct! This disarms the sarcasm and demands honest communication.' },
      { id: 'opt_c', text: 'Secretly delete their files from the shared drive to get even.', isCorrect: false, feedback: 'Incorrect. Counter-passive aggression creates a toxic workplace spiral.' }
    ],
    reflectionPromptEn: 'When you are angry at someone, what stops you from expressing it clearly and assertively in that moment?',
    titleHinglish: 'Passive-Aggressive Behavior: Taano Aur Khamoshi Ka Khel',
    subtitleHinglish: 'Kyu log seedha bolne ke bajaye sarcasm, late aana aur muh banana choose karte hain.',
    shortDescHinglish: 'Indirect hostility: Jab insaan gussa seedha nahi nikal pata to wo taane maarta hai aur kaam me delay karta hai.',
    oneLineHinglish: 'Muh se "Haan" bolna par harkaton se badla lena.',
    summary30sHinglish: 'Passive-aggression me log ladai se darrte hain, isliye seedha bolne ke bajaye indirect gussa dikhate hain: Bartan patakna, jaan-boojh kar der se aana, aur taana maar kar bolna: "Mazaak kar raha tha, tum to bura maan gaye!"',
    coreConceptHinglish: 'Iska sabse bada hathiyar hota hai "Plausible Deniability"—yani aise acting karna jaise kuch hua hi nahi. Samne wale ko pareshan bhi kar diya aur masoom bhi ban gaye.',
    summary60sHinglish: 'Bachpan me jin logo ko gussa express karne par daant padti thi, wo bade hokar passive-aggressive ban jate hain. Wo khul kar lad nahi sakte, isliye wo silent treatment dete hain ya kaam kharab karte hain. Iska ilaj hai unke taane ko shanti se call out karna.',
    howItWorksHinglish: 'Gussa aaya -> Direct bolne me darr laga -> Chupchap badla liya (kaam delay kiya) -> Target gussa hua -> Innocent bankar bola "Aap to hamesha gussa rehte ho".',
    howToRespondHinglish: 'Taane par gussa mat karo, seedha pucho: "Tum keh rahe ho sab theek hai, par tumhara chehra bol raha hai ki tum naraz ho. Asal baat kya hai?"',
    takeawaysHinglish: [
      'Passive-aggression darr aur kamzori se aati hai, taaki zimmedari na leni pade',
      '"Mazaak kar raha tha" passive-aggressive logo ka sabse bada shield hota hai',
      'Unke jaisa bankar badla mat lo, balki shanti se unki harkat ko samne lao',
      'Direct aur respectful baat karna hi is bimaari ka ek-matra ilaaj hai'
    ],
    pqPromptHinglish: 'Office me colleague ne aapke kaam par taana maara: "Wah! Kuch log kitni aish karte hain!" Aur fir bola "Mazaak tha yaar!" Kya response best hoga?',
    pqExplanationHinglish: 'Mazaak ke peeche chhipe taane ko seedhe sawal se neutralise kiya jata hai.',
    pqOptionsHinglish: [
      { id: 'opt_a', text: 'Jhoothi smile karke chup ho jana.', isCorrect: false, feedback: 'Galat. Isse samne wale ki himmat badhti hai.' },
      { id: 'opt_b', text: 'Shanti se dekh kar poochna: "Mujhe mazaak samajh nahi aaya, kya aap explain karenge ki aish se aapka kya matlab tha?"', isCorrect: true, feedback: 'Sahi! Yeh taane ko expose kar deta hai bina ladai kiye.' },
      { id: 'opt_c', text: 'Uska lunch box chupa dena.', isCorrect: false, feedback: 'Galat. Yeh childish hai.' }
    ],
    hiTitle: 'परोक्ष आक्रामकता (Passive-Aggression)',
    hiSummary: 'प्रत्यक्ष संवाद से बचते हुए अप्रत्यक्ष कटाक्ष, विलंब और व्यंग्य के माध्यम से क्रोध व्यक्त करने की मनोवैज्ञानिक प्रवृत्ति।',
    hiTakeaways: ['परोक्ष आक्रामकता भय और कमजोरी से उत्पन्न होती है', 'कटाक्ष और बहानेबाजी इसका मुख्य लक्षण है', 'स्पष्ट और शांत संवाद से इसे समाप्त करें'],
    guTitle: 'પરોક્ષ આક્રમકતા (Passive-Aggression)', guSummary: 'સીધી વાત કરવાને બદલે કટાક્ષ, વિલંબ અને નારાજગી દ્વારા ગુસ્સો દર્શાવવાની વૃત્તિ.', guTakeaways: ['પરોક્ષ ગુસ્સો ઓળખો', 'કટાક્ષનો શાંતિથી સામનો કરો', 'સ્પષ્ટ વાતચીત કરો'],
    mrTitle: 'अप्रत्यक्ष आक्रमकता (Passive-Aggression)', mrSummary: 'थेट न बोलता टोमणे, टाळाटाळ आणि सुप्त नाराजीच्या माध्यमातून राग व्यक्त करण्याची सवय.', mrTakeaways: ['अप्रत्यक्ष राग ओळखा', 'टोमण्यांना शांतपणे आव्हान द्या', 'थेट संवादाला प्रोत्साहन द्या'],
    teTitle: 'పరోక్ష దూకుడు (Passive-Aggression)', teSummary: 'ప్రత్యక్షంగా చెప్పకుండా వ్యంగ్యం, ఆలస్యం మరియు అలక ద్వారా కోపాన్ని వ్యక్తపరిచే మానసిక వైఖరి.', teTakeaways: ['పరోక్ష కోపాన్ని గుర్తించండి', 'వ్యంగ్యాన్ని ధైర్యంగా ఎదుర్కోండి', 'స్పష్టమైన సంభాషణ ముఖ్యం'],
    taTitle: 'மறைமுக ஆக்கிரமிப்பு (Passive-Aggression)', taSummary: 'நேரடியாக பேசாமல் நக்கல், தாமதம் மற்றும் மௌனத்தின் மூலம் கோபத்தை வெளிப்படுத்தும் தந்திரம்.', taTakeaways: ['மறைமுக கோபத்தை தவிருங்கள்', 'நக்கலான பேச்சை எதிர்கொள்ளுங்கள்', 'நேர்மையான உரையாடல் நன்று'],
    knTitle: 'ಪರೋಕ್ಷ ಆಕ್ರಮಣಶೀಲತೆ (Passive-Aggression)', knSummary: 'ನೇರವಾಗಿ ಹೇಳದೆ ವ್ಯಂಗ್ಯ, ವಿಳಂಬ ಮತ್ತು ಮೌನದ ಮೂಲಕ ಅಸಮಾಧಾನ ತೋರ್ಪಡಿಸುವ ವರ್ತನೆ.', knTakeaways: ['ಪರೋಕ್ಷ ಸಿಟ್ಟನ್ನು ಗುರುತಿಸಿ', 'ವ್ಯಂಗ್ಯಕ್ಕೆ ಬಲಿಯಾಗಬೇಡಿ', 'ನೇರ ಸಂವಾದ ನಡೆಸಿ'],
    mlTitle: 'പരോക്ഷ ആക്രമണോത്സുകത (Passive-Aggression)', mlSummary: 'നേരിട്ട് പറയാതെ പരിഹാസം, കാലതാമസം എന്നിവയിലൂടെ ദേഷ്യം പ്രകടിപ്പിക്കുന്ന രീതി.', mlTakeaways: ['പരോക്ഷ ദേഷ്യം തിരിച്ചറിയുക', 'പരിഹാസങ്ങളെ നേരിടുക', 'തുറന്ന ചർച്ച നടത്തുക'],
    bnTitle: 'পরোক্ষ আক্রমণাত্মক আচরণ (Passive-Aggression)', bnSummary: 'সরাসরি বিরোধ না করে ব্যঙ্গ, অবহেলা এবং ইচ্ছাকৃত বিলম্বের মাধ্যমে রাগ প্রকাশের প্রবণতা।', bnTakeaways: ['পরোক্ষ রাগ শনাক্ত করুন', 'ব্যঙ্গের মুখোমুখি হোন', 'খোলামেলা কথা বলুন'],
    paTitle: 'ਅਸਿੱਧੀ ਹਮਲਾਵਰਤਾ (Passive-Aggression)', paSummary: 'ਸਿੱਧੀ ਗੱਲ ਕਰਨ ਦੀ ਥਾਂ ਵਿਅੰਗ, ਦੇਰੀ ਅਤੇ ਗੁੱਸੇ ਨਾਲ ਆਪਣੀ ਨਾਰਾਜ਼ਗੀ ਦਿਖਾਉਣ ਦੀ ਆਦਤ।', paTakeaways: ['ਅਸਿੱਧੇ ਗੁੱਸੇ ਨੂੰ ਪਛਾਣੋ', 'ਵਿਅੰਗ ਦਾ ਸ਼ਾਂਤੀ ਨਾਲ ਜਵਾਬ ਦਿਓ', 'ਸਾਫ਼ ਗੱਲ ਕਰੋ'],
    urTitle: 'بالواسطہ جارحیت (Passive-Aggression)', urSummary: 'براہ راست بات کرنے کے بجائے طنز، سستی اور خاموشی کے ذریعے غصہ نکالنے کی عادت۔', urTakeaways: ['بالواسطہ غصے کو پہچانیں', 'طنز کا پرسکون جواب دیں', 'کھل کر بات کریں'],
    orTitle: 'ପରୋକ୍ଷ ଆକ୍ରମଣଶୀଳତା', orSummary: 'ସିଧାସଳଖ ନକହି ବ୍ୟଙ୍ଗ, ବିଳମ୍ବ ଓ ଅସହଯୋଗ ମାଧ୍ୟମରେ କ୍ରୋଧ ପ୍ରକାଶ କରିବା।', orTakeaways: ['ପରୋକ୍ଷ କ୍ରୋଧ ବୁଝନ୍ତୁ', 'ବ୍ୟଙ୍ଗକୁ ସାମ୍ନା କରନ୍ତୁ', 'ସ୍ପଷ୍ଟ ଆଲୋଚନା କରନ୍ତୁ'],
    asTitle: 'পৰোক্ষ আক্ৰমণাত্মকতা (Passive-Aggression)', asSummary: 'মুখ খুলি নকৈ ব্যংগ, অযথা পলম আৰু মৌনতাৰে খং প্ৰকাশ কৰাৰ মানসিকতা।', asTakeaways: ['পৰোক্ষ খং চিনাক্ত কৰক', 'ব্যংগৰ সঠিক প্ৰত্যুত্তৰ দিয়ক', 'খোলাখুলিকৈ আলোচনা কৰক']
  },

  {
    fileName: 'karpmanDramaTriangle.ts',
    varName: 'drama_triangle',
    id: 'drama_triangle',
    categoryId: 'relationships_comm',
    slug: 'karpman-drama-triangle',
    difficulty: 'intermediate',
    readTime: 6,
    sortWeight: 8,
    titleEn: 'The Karpman Drama Triangle: Victim, Rescuer, and Persecutor',
    subtitleEn: 'Stephen Karpman’s social model of recurring relational dysfunctions and the shift to the Empowerment Dynamic.',
    shortDescEn: 'A recurring transactional psychological game where individuals cycle between three dysfunctional roles: the helpless Victim, the righteous Persecutor, and the enabling Rescuer.',
    oneLineEn: 'A toxic interpersonal game where everyone switches roles but nobody solves the problem.',
    summary30sEn: 'Conceived by Dr. Stephen Karpman in 1968 within Transactional Analysis, the Drama Triangle shows how chronic relational conflicts trap participants in three scripted roles. The Rescuer helps to feel needed, which keeps the Victim helpless, until the Rescuer grows resentful and turns into the Persecutor.',
    coreConceptEn: 'The triangle operates through unconscious psychological payoffs: The Victim avoids responsibility ("Poor me!"); the Rescuer gains self-worth by fixing others ("Let me save you!"); the Persecutor vents hostility under the guise of justice ("It is all your fault!"). Roles are fluid: participants frequently rotate across all three points during a single argument.',
    summary60sEn: 'In joint families and teams, the Drama Triangle generates endless gossip, alliances, and dramatic confrontations without ever solving underlying issues. To exit the triangle, David Emerald proposed The Empowerment Dynamic (TED): The Victim becomes a Creator (focusing on solutions); the Persecutor becomes a Challenger (holding accountable with love); the Rescuer becomes a Coach (asking questions rather than doing the work).',
    takeawaysEn: [
      'The Rescuer role is not altruism; it is codependent control that disempowers the Victim',
      'The Victim role abdicates personal agency in exchange for sympathy and guilt-tripping',
      'Participants constantly rotate roles: today’s Rescuer becomes tomorrow’s Persecutor',
      'The exit route (The Empowerment Dynamic) transforms Victims into Creators and Rescuers into Coaches'
    ],
    whyItHappensEn: 'Childhood families where drama was the primary vehicle for intimacy and connection conditioned individuals to equate conflict loops with feeling alive and valued.',
    evolutionaryEn: 'Coalition politics in ancestral groups involved playing the wounded party or noble defender to win tribal sympathy and resource redistribution.',
    howItWorksEn: 'Person A plays Victim -> Person B jumps in as Rescuer -> Rescuer overextends and exhausts self -> Rescuer attacks Victim as Persecutor -> Person A attacks back -> Chaos repeats indefinitely.',
    visualHeadlineEn: 'The Drama Triangle vs. The Empowerment Dynamic',
    visualDescEn: 'Karpman\'s dysfunctional game mapped against Emerald\'s constructive transformation.',
    sideALabelEn: 'Dysfunctional Drama Triangle',
    sideADetailEn: 'Victim (helpless) <-> Rescuer (enabling) <-> Persecutor (blaming). Endless drama, zero growth.',
    sideBLabelEn: 'Constructive Empowerment Dynamic',
    sideBDetailEn: 'Creator (owns power) <-> Coach (asks empowering questions) <-> Challenger (inspires accountability).',
    researchSummaryEn: 'Karpman (1968, Transactional Analysis Bulletin) and Emerald (2009, The Power of TED) detailed the unconscious scripts that perpetuate codependent relationship cycles across couples and organizations.',
    refAuthor: 'Karpman, S. & Emerald, D.',
    refYear: 1968,
    refTitle: 'Fairy Tales and Script Drama Analysis',
    refCitation: 'Karpman, S. (1968). Transactional Analysis Bulletin, 7(26), 39–43.',
    refDoi: 'https://doi.org/10.1177/036215376800702603',
    scenarioTitleEn: 'The Family Loan Drama in Jaipur',
    scenarioContextEn: 'In Jaipur, Rahul constantly lost money in day-trading and came to his elder brother Aman crying that he couldn\'t pay his rent (Victim). Aman repeatedly paid his debts (Rescuer). When Aman finally asked Rahul for a budget plan, Rahul shouted: "You think you are God just because you have a corporate job!" and Aman snapped: "You are a parasite!" (Aman became Persecutor, Rahul became Victim again).',
    scenarioBiasEn: 'Both brothers were trapped in the Karpman Drama Triangle: Aman enabled Rahul\'s irresponsibility to feel like a noble elder brother, while Rahul used helplessness to extract funds.',
    scenarioOptimalEn: 'Aman shifts to Coach: "Rahul, I love you, but I will not pay your rent. I am happy to sit with you for 2 hours to help you write a debt repayment plan with a financial advisor."',
    scenarioReflectionEn: 'In your close relationships, do you tend to jump in as the exhausted Rescuer, or do you sometimes adopt the helpless Victim stance?',
    howToRecognizeEn: 'Feeling exhausted and unappreciated after "saving" someone, or feeling like life is always unfairly targeting you and nobody understands your suffering.',
    whereEn: 'In-law relationships, codependent marriages, startup founder disputes, and HR complaints.',
    misconceptionsEn: 'Myth: "Helping someone in need is always good." Fact: If your help prevents them from learning necessary skills or suffering natural consequences, you are an enabling Rescuer, not a helper.',
    limitationsEn: 'In genuine emergencies (medical crises, natural disasters), rescuing is vital and appropriate; the triangle applies to psychological and repetitive chronic patterns.',
    howToRespondEn: 'Refuse the script: If someone approaches as a Victim, ask: "What do you think is the best next step you can take?" If you feel the urge to rescue, sit on your hands and offer coaching instead of cash or labor.',
    defensesEn: [
      { title: 'The Coaching Pivot', instruction: 'Never do for an adult what they can do for themselves; ask empowering open questions: "What options have you considered?"' },
      { title: 'Decline the Persecutor Hook', instruction: 'When accused of being cruel for setting boundaries, respond: "I understand you are upset, but my boundary stands."' }
    ],
    pqPromptEn: 'A coworker repeatedly complains that the manager hates them and that they are doomed to fail their review (Victim). They ask you to write their summary report for them. How do you respond to stay out of the Drama Triangle?',
    pqScenarioEn: 'They look tearful and say: "You are the only person in this company who cares about me!"',
    pqExplanationEn: 'Taking over their report is entering the Rescuer trap, which keeps them helpless and burns you out. Offering guidance while leaving responsibility with them is the Coach stance.',
    pqAntidoteEn: 'Decline to do their work while offering 15 minutes of coaching on how they can structure it themselves.',
    pqOptionsEn: [
      { id: 'opt_a', text: 'Write the report for them late at night to save them from getting fired.', isCorrect: false, feedback: 'Incorrect. This is classic enabling Rescuer behavior that perpetuates helplessness.' },
      { id: 'opt_b', text: 'Say: "I believe you are capable of writing this. I can spare 15 minutes to review an outline you write, but the drafting is yours."', isCorrect: true, feedback: 'Correct! This adopts the Coach stance in the Empowerment Dynamic.' },
      { id: 'opt_c', text: 'Go scream at the manager on the coworker’s behalf.', isCorrect: false, feedback: 'Incorrect. This escalates you into the aggressive Persecutor role.' }
    ],
    reflectionPromptEn: 'Where in your life are you currently "rescuing" someone who needs to experience the consequences of their own choices?',
    titleHinglish: 'Karpman Drama Triangle: Victim, Rescuer Aur Villain Ka Khel',
    subtitleHinglish: 'Kyu parivaro aur dosti me hamesha wahi purani ladai repeat hoti rehti hai bina kisi solution ke.',
    shortDescHinglish: 'Stephen Karpman ka psychological model: Hum kaise Victim, Rescuer aur Persecutor ke toxic chakravyuh me phas jate hain.',
    oneLineHinglish: 'Ek aisa khel jisme har koi role badalta hai par problem kabhi solve nahi hoti.',
    summary30sHinglish: 'Drama Triangle me teen roles hote hain: Bechaara (Victim) jo zimmedari nahi leta, Masiha (Rescuer) jo sabko bachane nikalta hai taaki mahan ban sake, aur Villain (Persecutor) jo gussa nikaalta hai. Yeh teeno log aapas me ladte rehte hain par situation kabhi theek nahi hoti.',
    coreConceptHinglish: 'Rescuer banna koi bhalai nahi hai, balki doosre ko kamzor rakhne ka tareeqa hai. Jab Rescuer thak jata hai to wo gusse me Villain ban jata hai aur Victim par chilla padta hai. Ise todne ke liye Victim ko Creator aur Rescuer ko Coach banna padta hai.',
    summary60sHinglish: 'Indian joint families me yeh bohot common hai: Ek bhai hamesha karze me dooba rehta hai (Victim), doosra bhai use baar-baar paise dekar bachata hai (Rescuer). Phir jab Rescuer hisaab maangta hai to sab use zalim bolne lagte hain (Persecutor). Is toxic cycle se bahar nikalna zaroori hai.',
    howItWorksHinglish: 'Victim rota hai -> Rescuer use bachane daudta hai -> Victim sudharta nahi -> Rescuer gusse me use daantta hai -> Victim kehta hai "tum kitne zaalim ho" -> Chakravyuh chalta rehta hai.',
    howToRespondHinglish: 'Rescuer banna band karein: Kisi ka kaam khud mat karo, balki pucho: "Tum is problem ko solve karne ke liye kya steps lene wale ho?"',
    takeawaysHinglish: [
      'Doosro ki zimmedari apne sar lena bhalai nahi, balki unhe apahij banana hai',
      'Aaj ka Rescuer kal ka Persecutor ban jata hai jab wo thak jata hai',
      'Victim banne se sympathy to milti hai par insaan apni life ka control kho deta hai',
      'Coach bano: Advice aur sawal pucho, par unka bojh khud mat uthao'
    ],
    pqPromptHinglish: 'Aapka dost roz aakar rota hai ki boss bohot ganda hai aur bolta hai "Meri jagah tum hi email likh do." Aapko kya karna chahiye?',
    pqExplanationHinglish: 'Uska email khud likhna Rescuer trap hai. Usse khud likhne ke liye encourage karna Coach banna hai.',
    pqOptionsHinglish: [
      { id: 'opt_a', text: 'Uska email khud likh dena taaki wo bechaara daant na khaye.', isCorrect: false, feedback: 'Galat. Isse wo hamesha aap par dependent ho jayega.' },
      { id: 'opt_b', text: 'Bolo: "Main email nahi likhunga, lekin tum likhkar dikhao main 5 minute me review kar dunga."', isCorrect: true, feedback: 'Sahi! Yeh usse empowered banata hai aur drama todta hai.' },
      { id: 'opt_c', text: 'Dost par gussa ho kar dosti tod lena.', isCorrect: false, feedback: 'Galat. Yeh Persecutor banna hai.' }
    ],
    hiTitle: 'कार्पमैन ड्रामा त्रिकोण (Karpman Drama Triangle)',
    hiSummary: 'संबंधों में पीड़ित, रक्षक और उत्पीड़क के बीच चलने वाले अस्वस्थ और अंतहीन मनोवैज्ञानिक चक्र का विश्लेषण।',
    hiTakeaways: ['रक्षक बनना अक्सर निर्भरता को बढ़ावा देता है', 'पीड़ित की भूमिका में व्यक्ति अपनी शक्ति खो देता है', 'सहानुभूतिपूर्ण सशक्तिकरण से ही समाधान संभव है'],
    guTitle: 'કાર્પમેન ડ્રામા ત્રિકોણ', guSummary: 'સંબંધોમાં પીડિત, રક્ષક અને વિરોધી વચ્ચે ચાલતા ઝેરી માનસિક ચક્રને કેવી રીતે તોડવું.', guTakeaways: ['નિરર્થક રક્ષક ન બનો', 'પોતાની જવાબદારી સ્વીકારો', 'સહયોગથી આગળ વધો'],
    mrTitle: 'कार्पमन ड्रामा त्रिकोण (नात्यातील चक्रव्यूह)', mrSummary: 'नात्यांमध्ये पीडित, तारणहार आणि छळवादी यांच्यात फिरणाऱ्या अस्वस्थ मानसिक चक्राचे विश्लेषण.', mrTakeaways: ['अति-मदत करणे टाळा', 'प्रत्येकाला स्वावलंबी बनवा', 'नात्यातील नाटक संपवा'],
    teTitle: 'కార్ప్‌మన్ డ్రామా త్రిభుజం', teSummary: 'సంబంధాలలో బాధితుడు, రక్షకుడు మరియు నిందించే వ్యక్తి మధ్య సాగే విషపూరిత మానసిక చక్రం.', teTakeaways: ['అనవసర రక్షకుడిగా మారకండి', 'బాధ్యతను గుర్తించండి', 'సాధికారత వైపు నడవండి'],
    taTitle: 'கார்ப்மேன் நாடக முக்கோணம் (Drama Triangle)', taSummary: 'உறவுகளில் பாதிக்கப்பட்டவர், காப்பாற்றுபவர் மற்றும் கொடுமைப்படுத்துபவர் இடையே சுழலும் நச்சு வட்டம்.', taTakeaways: ['அளவுக்கு மீறி உதவாதீர்கள்', 'சுயசார்பை ஊக்குவியுங்கள்', 'நாடக வட்டத்திலிருந்து வெளியேறுங்கள்'],
    knTitle: 'ಕಾರ್ಪ್‌ಮನ್ ಡ್ರಾಮಾ ತ್ರಿಕೋನ', knSummary: 'ಸಂಬಂಧಗಳಲ್ಲಿ ಸಂತ್ರಸ್ತ, ರಕ್ಷಕ ಮತ್ತು ನಿಂದಕನ ನಡುವೆ ಸುತ್ತುವ ವಿಷಕಾರಿ ಮಾನಸಿಕ ಚಕ್ರದ ವಿಶ್ಲೇಷಣೆ.', knTakeaways: ['ಅನಗತ್ಯ ರಕ್ಷಕರಾಗಬೇಡಿ', 'ಸ್ವಾವಲಂಬನೆಗೆ ಪ್ರೋತ್ಸಾಹಿಸಿ', 'ಸಮಸ್ಯೆಗೆ ನಿಜವಾದ ಪರಿಹಾರ ಕಂಡುಕೊಳ್ಳಿ'],
    mlTitle: 'കാർപ്മാൻ ഡ്രാമ ട്രയാംഗിൾ', mlSummary: 'ബന്ധങ്ങളിൽ ഇര, രക്ഷകൻ, വേട്ടക്കാരൻ എന്നിവർക്കിടയിൽ ആവർത്തിക്കുന്ന വിഷലിപ്തമായ മാനസിക ചക്രം.', mlTakeaways: ['അമിതമായി സംരക്ഷിക്കരുത്', 'സ്വയംപര്യാപ്തത വളർത്തുക', 'യഥാർത്ഥ പ്രശ്നപരിഹാരം കണ്ടെത്തുക'],
    bnTitle: 'কার্পম্যান ড্রামা ট্রায়াঙ্গেল (সম্পর্কের বিষাক্ত চক্র)', bnSummary: 'সম্পর্কের মধ্যে ভুক্তভোগী, উদ্ধারকর্তা এবং নিপীড়কের মধ্যে আবর্তিত অস্বাস্থ্যকর মানসিক চক্র।', bnTakeaways: ['অহেতুক ত্রাণকর্তা হবেন না', 'স্বাবলম্বী হতে সাহায্য করুন', 'নাটকীয়তা পরিহার করুন'],
    paTitle: 'ਕਾਰਪਮੈਨ ਡਰਾਮਾ ਤਿਕੋਣ (ਰਿਸ਼ਤਿਆਂ ਦਾ ਚੱਕਰਵਿਊ)', paSummary: 'ਰਿਸ਼ਤਿਆਂ ਵਿੱਚ ਪੀੜਤ, ਬਚਾਉਣ ਵਾਲੇ ਅਤੇ ਦੋਸ਼ੀ ਵਿਚਕਾਰ ਚੱਲਣ ਵਾਲੇ ਜ਼ਹਿਰੀਲੇ ਮਨੋਵਿਗਿਆਨਕ ਚੱਕਰ ਦੀ ਪਛਾਣ।', paTakeaways: ['ਲੋੜ ਤੋਂ ਵੱਧ ਮਦਦ ਨਾ ਕਰੋ', 'ਸਭ ਨੂੰ ਆਤਮਨਿਰਭਰ ਬਣਾਓ', 'ਡਰਾਮੇ ਤੋਂ ਬਾਹਰ ਨਿਕਲੋ'],
    urTitle: 'کارپ مین ڈراما تکون (Drama Triangle)', urSummary: 'رشتوں میں مظلوم، نجات دہندہ اور ظالم کے درمیان گھومنے والے زہریلے نفسیاتی چکر کا حل۔', urTakeaways: ['ہر بار نجات دہندہ نہ بنیں', 'خود انحصاری کو فروغ دیں', 'صحیح رہنمائی فراہم کریں'],
    orTitle: 'କାର୍ପମ୍ୟାନ୍ ଡ୍ରାମା ତ୍ରିକୋଣ', orSummary: 'ସମ୍ପର୍କରେ ପୀଡ଼ିତ, ରକ୍ଷକ ଓ ଅତ୍ୟାଚାରୀ ମଧ୍ୟରେ ଘୁରୁଥିବା ବିଷାକ୍ତ ମାନସିକ ଚକ୍ର।', orTakeaways: ['ଅଯଥା ରକ୍ଷକ ସାଜନ୍ତୁ ନାହିଁ', 'ସ୍ୱାବଲମ୍ବୀ ହେବାକୁ ପ୍ରେରଣା ଦିଅନ୍ତୁ', 'ସମସ୍ୟାର ସଠିକ୍ ସମାଧାନ କରନ୍ତୁ'],
    asTitle: 'কাৰ্পমেন ড্ৰামা ত্ৰিকোণ', asSummary: 'সম্পৰ্কত ভুক্তভোগী, ৰক্ষক আৰু অত্যাচাৰীৰ মাজত ঘূৰি থকা বিষাক্ত মানসিক চক্ৰৰ বিশ্লেষণ।', asTakeaways: ['অযথা ত্ৰাণকৰ্তা নহ’ব', 'স্বাৱলম্বনক প্ৰাধান্য দিয়ক', 'নাটকীয়তাৰ পৰা আঁতৰি থাকক']
  },

  {
    fileName: 'emotionalBidsRepairAttempts.ts',
    varName: 'emotional_bids_repair',
    id: 'emotional_bids_repair',
    categoryId: 'relationships_comm',
    slug: 'emotional-bids-and-repair-attempts',
    difficulty: 'beginner',
    readTime: 5,
    sortWeight: 9,
    titleEn: 'Emotional Bids & Repair Attempts: The Micro-Currency of Intimacy',
    subtitleEn: 'John Gottman’s landmark research on turning toward connection and saving conversations mid-conflict.',
    shortDescEn: 'The fundamental micro-interactions that determine relationship success: responding to bids for connection and deploying timely de-escalation repair attempts during fights.',
    oneLineEn: 'A relationship is built or destroyed in ordinary 5-second moments of attention.',
    summary30sEn: 'Over 40 years at the University of Washington\'s "Love Lab", Dr. John Gottman discovered that couples who stay together turn toward each other’s bids for emotional connection 86% of the time, while couples who divorce do so only 33% of the time. Intimacy is not sustained by grand vacations, but by small moments of acknowledged attention.',
    coreConceptEn: 'A "bid" is any verbal or nonverbal attempt to get attention, affection, humor, or support (e.g. "Look at that pretty bird outside!"). The partner can respond in three ways: Turning Toward (acknowledging enthusiastically), Turning Away (ignoring/glancing at phone), or Turning Against (snapping irritably). Additionally, "Repair Attempts" are verbal seatbelts deployed mid-fight to prevent physiological flooding.',
    summary60sEn: 'Gottman discovered that master couples fight just as passionately as disasters, but they succeed because they deploy and accept repair attempts: humorous smiles, self-deprecating apologies, or physical touch. When an apology is offered ("Hey, I was rude, let me try again"), accepting it stops the heart-rate escalation and preserves relational safety.',
    takeawaysEn: [
      'Masters of relationships turn toward bids 86% of the time; disasters only 33%',
      'Ignoring a bid (turning away) hurts connection far more than active arguing',
      'Repair attempts are verbal circuit breakers that prevent marital flooding',
      'The effectiveness of a repair attempt depends on the emotional bank account built beforehand'
    ],
    whyItHappensEn: 'Mammalian attachment systems continuously test for safety and reciprocity through low-stakes social pings.',
    evolutionaryEn: 'In close-knit ancestral tribes, knowing which partner had your back in micro-moments was vital for reliable mutual defense.',
    howItWorksEn: 'Partner makes bid ("Look at this article") -> Choice point -> Partner turns toward ("That is fascinating, tell me more") -> Emotional bank account grows -> Conflict resilience skyrockets.',
    visualHeadlineEn: 'Turning Toward vs. Turning Away from Micro-Bids',
    visualDescEn: 'How everyday 3-second responses determine long-term marital longevity.',
    sideALabelEn: 'Turning Toward (86% of Masters)',
    sideADetailEn: 'Looks up from laptop, makes eye contact, smiles: "Wow, that looks interesting! What happened?"',
    sideBLabelEn: 'Turning Away (33% of Disasters)',
    sideBDetailEn: 'Stares silently at phone screen, mumbles "uh-huh", ignores the partner\'s bid for connection.',
    researchSummaryEn: 'Gottman & Silver (1999, The Seven Principles for Making Marriage Work) and Driver & Gottman (2004, Journal of Family Psychology) documented how bid response rates predict divorce with 90%+ statistical accuracy.',
    refAuthor: 'Gottman, J. M. & Silver, N.',
    refYear: 1999,
    refTitle: 'The Seven Principles for Making Marriage Work',
    refCitation: 'Gottman, J. M., & Silver, N. (1999). Crown Publishers.',
    refDoi: 'https://doi.org/10.1037/0022-006X.68.5.759',
    scenarioTitleEn: 'The Evening Chai Moment in Kolkata',
    scenarioContextEn: 'Anirban was scrolling LinkedIn while his wife Tanu served evening tea and said: "Look at the rain on the balcony, doesn\'t it smell amazing?" Anirban didn\'t look up and muttered: "Hmm." Over five years, hundreds of these tiny missed bids turned their Kolkata apartment into a silent emotional desert.',
    scenarioBiasEn: 'Anirban practiced chronic "Turning Away": he didn\'t attack Tanu, but his persistent lack of engagement eroded her emotional security.',
    scenarioOptimalEn: 'Put the phone face down for 5 seconds, look her in the eye, and say: "It really does; let’s sit out on the balcony for 10 minutes." This deposits currency in the emotional bank account.',
    scenarioReflectionEn: 'When your partner or child shares a trivial observation, do you routinely look up and engage, or do you stay glued to your screen?',
    howToRecognizeEn: 'Noticing small comments like "Did you see that?", sighs, gentle shoulder taps, or shared funny memes—these are all bids for connection.',
    whereEn: 'Evening dinners, car rides, bedside conversations, and remote work spaces.',
    misconceptionsEn: 'Myth: "Great relationships are made by grand anniversary surprises." Fact: Daily micro-bids of attention are 100 times more predictive of marital stability than expensive vacations.',
    limitationsEn: 'When under intense work deadlines, it is impossible to catch every bid; turning away occasionally is normal as long as you circle back and repair.',
    howToRespondEn: 'The 3-Second Turn: Whenever a loved one speaks to you, force yourself to make direct eye contact for at least 3 seconds before responding.',
    defensesEn: [
      { title: 'The Mid-Fight Repair Statement', instruction: 'When an argument gets loud, insert a pre-agreed repair phrase: "I love you, but we are both screaming. Can we pause and hold hands for 60 seconds?"' },
      { title: 'The Postponed Bid Reconnection', instruction: 'If you are genuinely busy, don\'t ignore: "I am in the middle of this email, but I want to hear this. Give me 10 minutes and let\'s talk."' }
    ],
    pqPromptEn: 'During a heated fight about finances, your partner suddenly stops, smiles weakly, and says: "Hey, we are both starving and exhausted. I am sorry I raised my voice." What is the scientifically optimal response?',
    pqScenarioEn: 'You are still feeling angry and have 3 more counter-arguments prepared.',
    pqExplanationEn: 'This is a Gottman Repair Attempt. Accepting a repair attempt de-escalates physiological flooding and preserves the relationship; rejecting it leads to contempt.',
    pqAntidoteEn: 'Accept the repair attempt immediately, acknowledge the shared exhaustion, and pause the fight.',
    pqOptionsEn: [
      { id: 'opt_a', text: 'Say: "Don\'t try to change the subject with food! You always do this when you are losing an argument!"', isCorrect: false, feedback: 'Incorrect. Rejecting a repair attempt pushes the conflict toward contempt and stonewalling.' },
      { id: 'opt_b', text: 'Breathe, take their hand, and say: "You are right. I am sorry too. Let’s eat first and finish this calmly later."', isCorrect: true, feedback: 'Correct! Accepting repair attempts is the single biggest predictor of relationship longevity.' },
      { id: 'opt_c', text: 'Roll your eyes and walk out of the house silently.', isCorrect: false, feedback: 'Incorrect. This triggers emotional abandonment panic.' }
    ],
    reflectionPromptEn: 'What is your favorite "repair phrase" that helps you and your partner de-escalate tension during a disagreement?',
    titleHinglish: 'Emotional Bids & Repair: Rishto Ka Chota Chota Currency',
    subtitleHinglish: 'John Gottman ki 40 saal ki research: Kaise 5 second ke micro-moments tay karte hain ki rishta chalega ya tootega.',
    shortDescHinglish: 'Ek doosre ke attention maangne ke chote signals (Bids) ko acknowledge karna aur ladaai me repair attempts accept karna.',
    oneLineHinglish: 'Rishta mehenge gifts se nahi, balki mobile chhod kar 5 second dekhne se banta hai.',
    summary30sHinglish: 'Dr. John Gottman ne dekha ki jo couples 40 saal sath rehte hain, wo din me choti-choti baaton par ek doosre ko 86% time attention dete hain ("Turning toward"). Jo log mobile me ghuse rehte hain aur partner ko ignore karte hain ("Turning away"), unka divorce hona 90% tay hota hai.',
    coreConceptHinglish: 'Bid har wo choti baat hai jisme partner attention chahta hai (jaise: "Dekho kitni pyaari baarish ho rahi hai!"). Agar aap phone se nazar utha kar smile karte hain, to emotional bank account me paise jama hote hain. Ladai ke waqt maafi maangna "Repair attempt" kehlata hai.',
    summary60sHinglish: 'Master couples bhi ladte hain, lekin ladai ke beech me koi ek bol deta hai: "Chalo ladai rokte hain, dono ko bhookh lagi hai." Agar doosra partner is repair attempt ko accept kar leta hai, to rishta bach jata hai. Repair attempt ko ignore karna rishte ka murder karna hai.',
    howItWorksHinglish: 'Partner ne kuch bola -> Phone chhod kar uski taraf dekha -> Trust badha -> Ladaai ke waqt ek ne bola "Sorry main zyada bol gaya" -> Doosre ne gale lagaya -> Rishta strong hua.',
    howToRespondHinglish: '3-Second Rule apnayein: Jab bhi partner ya bachha kuch bole, screen se nazar hata kar 3 second unki aankhon me dekh kar jawab dein.',
    takeawaysHinglish: [
      'Rishte bade vacations se nahi, balki roz ke 5 second ke dhyan se bante hain',
      'Partner ki baat ko ignore karna ladne se bhi zyada toxic hota hai',
      'Ladai ke beech me sorry ya mazaaq karna "Repair Attempt" hai, use accept karein',
      'Emotional bank account bhara ho to badi se badi ladaai asani se sulajh jati hai'
    ],
    pqPromptHinglish: 'Garma-garam behes ke beech partner ne bola: "Sorry main gusse me chilla gaya, hum dono thak gaye hain, thoda paani peete hain." Kya karein?',
    pqExplanationHinglish: 'Yeh Gottman ka Repair Attempt hai. Isko accept karne se ladai turant de-escalate ho jati hai.',
    pqOptionsHinglish: [
      { id: 'opt_a', text: 'Bolo: "Muddha mat bhatkao! Tum haar rahe ho isliye paani ka bahana bana rahe ho!"', isCorrect: false, feedback: 'Galat. Repair attempt ko reject karna rishte ko barbaad karta hai.' },
      { id: 'opt_b', text: 'Paani lein, shant ho jayein aur bolein: "Haan yaar, main bhi zyada bol gaya tha."', isCorrect: true, feedback: 'Sahi! Repair accept karna hi mature rishto ki pehchan hai.' },
      { id: 'opt_c', text: 'Chilla kar kamre ka darwaza band kar lena.', isCorrect: false, feedback: 'Galat. Yeh toxic stonewalling hai.' }
    ],
    hiTitle: 'भावनात्मक संकेत और समाधान (Bids & Repair Attempts)',
    hiSummary: 'संबंधों में छोटे-छोटे भावनात्मक संकेतों पर ध्यान देने और विवाद के बीच समाधान के प्रयासों को स्वीकार करने का विज्ञान।',
    hiTakeaways: ['दैनिक छोटे क्षण बड़े उपहारों से अधिक महत्वपूर्ण हैं', 'संकेतों की अनदेखी करना संबंधों को खोखला करता है', 'विवाद के बीच माफी और शांति के प्रयासों को स्वीकार करें'],
    guTitle: 'લાગણીઓના સંકેતો અને સમાધાન (Bids & Repair)', guSummary: 'રોજિંદા જીવનમાં સાથીદારના નાના સંકેતોને મહત્વ આપવું અને ઝઘડા વખતે સમાધાન સ્વીકારવું.', guTakeaways: ['નાની પળોમાં પ્રેમ દર્શાવો', 'સાથીદારની અવગણના ન કરો', 'સમાધાનના પ્રયાસો સ્વીકારો'],
    mrTitle: 'भावनिक संकेत आणि संवाद दुरुस्ती (Bids & Repair)', mrSummary: 'नात्यांमध्ये रोजच्या छोट्या क्षणांमध्ये लक्ष देणे आणि भांडणाच्या वेळी समेट घडवून आणण्याचे महत्त्व.', mrTakeaways: ['छोट्या क्षणांना महत्त्व द्या', 'दुर्लक्ष करणे टाळा', 'माफी आणि समेटाचे प्रयत्न स्वीकारा'],
    teTitle: 'భావోద్వేగ ఆహ్వానాలు మరియు పరిష్కారాలు', teSummary: 'సంబంధాలలో రోజువారీ చిన్నపాటి శ్రద్ధ మరియు గొడవల సమయంలో సర్దుబాటు ప్రయత్నాల ప్రాముఖ్యత.', teTakeaways: ['చిన్న క్షణాలను గుర్తించండి', 'నిర్లక్ష్యం చేయవద్దు', 'సర్దుబాటు ప్రయత్నాలను అంగీకరించండి'],
    taTitle: 'உணர்ச்சி சமிக்ஞைகளும் சமரசங்களும்', taSummary: 'உறவுகளில் அன்றாட சிறு கவனங்களும் சண்டைகளின் போது செய்யப்படும் சமரச முயற்சிகளும்.', taTakeaways: ['சிறு தருணங்களை கவனியுங்கள்', 'புறக்கணிக்காதீர்கள்', 'சமரச முயற்சிகளை ஏற்றுக்கொள்ளுங்கள்'],
    knTitle: 'ಭಾವನಾತ್ಮಕ ಸಂಕೇತಗಳು ಮತ್ತು ಸರಿಪಡಿಸುವಿಕೆ', knSummary: 'ದೈನಂದಿನ ಸಣ್ಣಪುಟ್ಟ ಗಮನ ಮತ್ತು ಜಗಳಗಳ ಸಮಯದಲ್ಲಿ ರಾಜಿ ಪ್ರಯತ್ನಗಳ ಪ್ರಾಮುಖ್ಯತೆ.', knTakeaways: ['ಸಣ್ಣ ಕ್ಷಣಗಳನ್ನು ಗೌರವಿಸಿ', 'ಅಲಕ್ಷ್ಯ ಮಾಡಬೇಡಿ', 'ರಾಜಿ ಪ್ರಯತ್ನಗಳನ್ನು ಒಪ್ಪಿಕೊಳ್ಳಿ'],
    mlTitle: 'വൈകാരിക സൂചനകളും അനുരഞ്ജന ശ്രമങ്ങളും', mlSummary: 'ബന്ധങ്ങളിൽ ദൈനംദിന ചെറിയ ശ്രദ്ധയും വഴക്കുകൾക്കിടയിലെ അനുരഞ്ജന ശ്രമങ്ങളും ചെലുത്തുന്ന സ്വാധീനം.', mlTakeaways: ['ചെറിയ നിമിഷങ്ങൾ ശ്രദ്ധിക്കുക', 'അവഗണിക്കരുത്', 'അനുരഞ്ജന ശ്രമങ്ങൾ സ്വീകരിക്കുക'],
    bnTitle: 'মানসিক সংকেত এবং পুনর্মিলন প্রচেষ্টা', bnSummary: 'সম্পর্কের দৈনন্দিন ছোট ছোট মুহূর্তের মনোযোগ এবং ঝগড়ার মাঝে পুনর্মিলন প্রচেষ্টার বিজ্ঞান।', bnTakeaways: ['ছোট মুহূর্তগুলোকে গুরুত্ব দিন', 'উপেক্ষা করবেন না', 'পুনর্মিলনের প্রস্তাব গ্রহণ করুন'],
    paTitle: 'ਭਾਵਨਾਤਮਕ ਸੰਕੇਤ ਅਤੇ ਸੁਲ੍ਹਾ ਦੇ ਯਤਨ', paSummary: 'ਰਿਸ਼ਤਿਆਂ ਵਿੱਚ ਰੋਜ਼ਾਨਾ ਦੇ ਛੋਟੇ ਪਲਾਂ ਵਿੱਚ ਧਿਆਨ ਦੇਣਾ ਅਤੇ ਲੜਾਈ ਵੇਲੇ ਸੁਲ੍ਹਾ ਦੀ ਕੋਸ਼ਿਸ਼ ਨੂੰ ਸਵੀਕਾਰ ਕਰਨਾ।', paTakeaways: ['ਛੋਟੇ ਪਲਾਂ ਦੀ ਕਦਰ ਕਰੋ', 'ਅਣਦੇਖਾ ਨਾ ਕਰੋ', 'ਸੁਲ੍ਹਾ ਦੇ ਯਤਨਾਂ ਨੂੰ ਅਪਣਾਓ'],
    urTitle: 'جذباتی اشارے اور صلح کی کوششیں (Bids & Repair)', urSummary: 'روزمرہ کے رشتوں میں چھوٹی چھوٹی باتوں پر توجہ دینا اور لڑائی کے دوران صلح کو قبول کرنا۔', urTakeaways: ['چھوٹے لمحات کو اہمیت دیں', 'نظر انداز نہ کریں', 'صلح کی پیشکش قبول کریں'],
    orTitle: 'ଭାବନାଗତ ସଙ୍କେତ ଓ ସମାଧାନର ପ୍ରୟାସ', orSummary: 'ସମ୍ପର୍କରେ ଦୈନନ୍ଦିନ ଛୋଟ ଛୋଟ ମୁହୂର୍ତ୍ତ ପ୍ରତି ଧ୍ୟାନ ଏବଂ କଳହ ମଧ୍ୟରେ ସମାଧାନର ପ୍ରୟାସ।', orTakeaways: ['ଛୋଟ ମୁହୂର୍ତ୍ତକୁ ଗୁରୁତ୍ୱ ଦିଅନ୍ତୁ', 'ଅଣଦେଖା କରନ୍ତୁ ନାହିଁ', 'ସମାଧାନ ପ୍ରସ୍ତାବ ଗ୍ରହଣ କରନ୍ତୁ'],
    asTitle: 'আৱেগিক সংকেত আৰু মিলামিছাৰ প্ৰয়াস', asSummary: 'দৈনন্দিন জীৱনত সংগীৰ সৰু সৰু কথাত গুৰুত্ব দিয়া আৰু কাজিয়াৰ মাজত মিলামিছাৰ প্ৰচেষ্টা গ্ৰহণ কৰা।', asTakeaways: ['ক্ষুদ্ৰ মুহূৰ্তক মূল্য দিয়ক', 'অৱহেলা নকৰিব', 'শান্তিৰ প্ৰচেষ্টা স্বীকাৰ কৰক']
  },

  {
    fileName: 'actorObserverInRelationships.ts',
    varName: 'actor_observer_in_relationships',
    id: 'actor_observer_in_relationships',
    categoryId: 'relationships_comm',
    slug: 'actor-observer-in-relationships',
    difficulty: 'intermediate',
    readTime: 5,
    sortWeight: 10,
    titleEn: 'Attribution Asymmetry: The Flaw in Couple Explanations',
    subtitleEn: 'Frank Fincham’s relationship attribution research on why we excuse our own mistakes while blaming our partner’s character.',
    shortDescEn: 'The tendency in intimate relationships to attribute one’s own negative behaviors to temporary situational stress while attributing a partner’s mistakes to deep-seated character flaws.',
    oneLineEn: '"When I snap, it is because I had a hard day; when you snap, it is because you are mean."',
    summary30sEn: 'Relationship psychologist Frank Fincham demonstrated that in unhappy relationships, partners suffer from severe attributional asymmetry. If I am late, it is traffic (situational); if you are late, you are selfish and disrespectful (dispositional). This double standard turns minor frictions into chronic character assassinations.',
    coreConceptEn: 'Attribution theory distinguishes between locus of causality (internal vs. external), stability (permanent vs. temporary), and globality (pervasive vs. specific). In distressed couples, negative partner behaviors are attributed to internal, stable, and global character flaws ("You always ruin everything"), making forgiveness cognitively impossible.',
    summary60sEn: 'Conversely, in flourishing relationships, partners maintain a "Generous Attribution Style": when their partner makes a mistake, they attribute it to external stress ("They must be overwhelmed with work today"). When the partner does something wonderful, they credit their core character ("She is so thoughtful"). Flipping this attributional filter is the primary therapeutic intervention in marital therapy.',
    takeawaysEn: [
      'We judge ourselves by our internal good intentions, but judge partners by their external impact',
      'Unhappy couples attribute partner mistakes to permanent character defects ("You are lazy")',
      'Happy couples grant situational grace to their partner ("He had an exhausting shift")',
      'The antidote is practicing the Benefit of the Doubt before assigning malice'
    ],
    whyItHappensEn: 'We have direct access to our own internal stress, fatigue, and intentions, but only perceive our partner’s external actions.',
    evolutionaryEn: 'Early detection of defection or disloyalty in pair-bonds was critical for parental investment security.',
    howItWorksEn: 'Partner forgets task -> I evaluate action -> My brain skips situational factors -> Labels partner "selfish" -> Resentful attack launched -> Partner defends themselves -> Intimacy deteriorates.',
    visualHeadlineEn: 'Distressed Attributions vs. Generous Relationship Attributions',
    visualDescEn: 'How cognitive interpretation filters transform identical relationship events.',
    sideALabelEn: 'Distressed Attribution Filter',
    sideADetailEn: 'Partner is late -> "They don’t respect my time because they only care about themselves."',
    sideBLabelEn: 'Generous Attribution Filter',
    sideBDetailEn: 'Partner is late -> "Traffic must be terrible today; let me check if they are okay."',
    researchSummaryEn: 'Fincham & Bradbury (1992, JPSP) and Bradbury & Fincham (1990) proved that marital distress is strongly mediated by negative attributional patterns, predicting marital dissolution across 10-year longitudinal studies.',
    refAuthor: 'Fincham, F. D. & Bradbury, T. N.',
    refYear: 1992,
    refTitle: 'Assessing Attributions in Marriage: The Relationship Attribution Measure',
    refCitation: 'Fincham, F. D., & Bradbury, T. N. (1992). Journal of Personality and Social Psychology, 62(3), 457–468.',
    refDoi: 'https://doi.org/10.1037/0022-3514.62.3.457',
    scenarioTitleEn: 'The Forgotten Anniversary in Ahmedabad',
    scenarioContextEn: 'Dev and Radhika were celebrating their 4th anniversary in Ahmedabad. Dev forgot to book the restaurant. Radhika immediately erupted: "You never care about me! You are completely selfish and self-absorbed!" Meanwhile, when Radhika forgot Dev\'s sister\'s birthday the previous month, she excused herself: "I had an insane tax audit deadline."',
    scenarioBiasEn: 'Radhika applied double attribution: she excused her own forgetfulness as situational stress, while labeling Dev’s forgetfulness as a permanent flaw in his character.',
    scenarioOptimalEn: 'Practice generous attribution: "Dev, I am hurt that the reservation wasn\'t made, but I know how exhausted you’ve been with the factory audit. Let’s order in and celebrate tonight."',
    scenarioReflectionEn: 'When your partner makes an annoying mistake, is your immediate thought about their situation or about their personality?',
    howToRecognizeEn: 'Using absolute words like "You always" or "You never" to turn a single situational oversight into an indictment of your partner\'s entire character.',
    whereEn: 'Chore divisions, punctuality disputes, financial disagreements, and in-law relations.',
    misconceptionsEn: 'Myth: "Generous attribution means tolerating chronic abuse." Fact: Generous attribution applies to normal human errors in healthy partners; chronic patterns of deliberate harm require firm boundaries.',
    limitationsEn: 'If a partner is actively deceitful or abusive, attributing their behavior to external stress enables toxicity; situational grace requires mutual goodwill.',
    howToRespondEn: 'The Reverse Mirror Technique: Ask yourself: "If I had made this exact same mistake today, what excuse would I have given myself? Can I offer that same grace to my partner?"',
    defensesEn: [
      { title: 'The Ban on "Always" and "Never"', instruction: 'Purge the words "You always" and "You never" from your conflict vocabulary; address only the specific incident today.' },
      { title: 'The Generous Hypothesis Rule', instruction: 'Before speaking, formulate at least one plausible benevolent explanation for why your partner made the mistake.' }
    ],
    pqPromptEn: 'Your partner forgot to buy milk on their way home from a 10-hour workday. What represents a generous, healthy attribution?',
    pqScenarioEn: 'You are standing in the kitchen frustrated because you wanted evening coffee.',
    pqExplanationEn: 'Attributing the mistake to situational fatigue ("They had an exhausting shift") rather than personal disrespect preserves emotional connection.',
    pqAntidoteEn: 'Give situational grace for honest errors and discuss practical reminders neutrally.',
    pqOptionsEn: [
      { id: 'opt_a', text: 'Say: "You are so lazy and selfish, you never think of anyone but yourself!"', isCorrect: false, feedback: 'Incorrect. This attacks their character with a toxic global attribution.' },
      { id: 'opt_b', text: 'Think: "They had a grueling 10-hour day and their brain was overloaded. I will order via quick commerce and remind them tomorrow."', isCorrect: true, feedback: 'Correct! This generous attribution protects relationship warmth.' },
      { id: 'opt_c', text: 'Throw the coffee mug in the sink and refuse to speak to them for the rest of the evening.', isCorrect: false, feedback: 'Incorrect. Passive-aggressive punishment destroys intimacy.' }
    ],
    reflectionPromptEn: 'How would your relationship change if you gave your partner the exact same benefit of the doubt that you give yourself?',
    titleHinglish: 'Attribution Asymmetry: Apni Galti Majboori, Partner Ki Fitrat',
    subtitleHinglish: 'Kyu hum apni galti par kehte hain "main thaka tha", par partner ki galti par bolte hain "tum ho hi aise".',
    shortDescHinglish: 'Frank Fincham ki research: Rishto me double standard rakhna jisme hum partner ke character par attack karte hain.',
    oneLineHinglish: 'Main late hua to traffic tha, tum late huye to tum laparwah ho.',
    summary30sHinglish: 'Fincham ne prove kiya ki tootte huye rishton me log double standard use karte hain. Jab khud se galti ho to kehte hain "aaj bohot stress tha", lekin jab partner wahi galti kare to kehte hain "tumhara character hi kharab hai, tum kabhi kisi ki parwah nahi karte".',
    coreConceptHinglish: 'Hum apne dimaag ki majboori jante hain, lekin partner ka sirf bahar ka action dekhte hain. Isliye hum unki galti ko unki "fitrat" (disposition) maan lete hain aur apni galti ko "halat" (situation). Ise kehte hain Attribution Asymmetry.',
    summary60sHinglish: 'Khushaal rishton me log apne partner ko "Benefit of the Doubt" dete hain: "Shayad wo thaka hua tha isliye bhool gaya." Jabki dukhi rishton me log har choti bhool par partner ke character par attack karte hain ("Tum hamesha laparwah rehte ho"). Words like "Always" aur "Never" rishto me zeher gholte hain.',
    howItWorksHinglish: 'Partner se galti hui -> Humne uski situation nahi sochi -> Uske character ko dosh diya ("Tum matlabi ho") -> Usne defend kiya -> Badi ladai ban gayi.',
    howToRespondHinglish: 'Reverse Mirror rule: Sochein agar yahi galti maine ki hoti to main kya bahana banata? Wahi maafi partner ko bhi dein.',
    takeawaysHinglish: [
      'Hum khud ko intentions se judge karte hain aur partner ko unke actions se',
      'Ladai me "Tum hamesha aise hi karte ho" bolna character assassination hai',
      'Partner ko thoda grace aur benefit of the doubt dena mature pyaar ki nishani hai',
      'Single incident par baat karein, unke poore wajood par ilzam mat lagayein'
    ],
    pqPromptHinglish: 'Partner office se aate waqt dahi lana bhool gaya. Healthy attribution ke hisab se aapko kya sochna chahiye?',
    pqExplanationHinglish: 'Usse thakan aur busy schedule ki bhool samajhna rishte me shanti banaye rakhta hai.',
    pqOptionsHinglish: [
      { id: 'opt_a', text: 'Sochna: "Isse meri koi parwah nahi hai, yeh hamesha mujhe ignore karta hai."', isCorrect: false, feedback: 'Galat. Yeh toxic character blaming hai.' },
      { id: 'opt_b', text: 'Sochna: "Bechaara thak gaya hoga, main Blinkit se manga leta hu, koi badi baat nahi."', isCorrect: true, feedback: 'Sahi! Yeh generous attribution rishte ko majboot banata hai.' },
      { id: 'opt_c', text: 'Khana banana band kar dena taaki use galti ka ehsaas ho.', isCorrect: false, feedback: 'Galat. Yeh passive-aggressive childishness hai.' }
    ],
    hiTitle: 'संबंधों में आरोपण विषमता (Attribution Asymmetry)',
    hiSummary: 'रिश्तों में अपनी गलतियों को परिस्थितियों का दोष देना परंतु साथी की गलतियों को उसके चरित्र की कमी ठहराने का मनोवैज्ञानिक दोहरा मापदंड।',
    hiTakeaways: ['हम स्वयं को इरादों से और दूसरों को कर्मों से आंकते हैं', 'चरित्र पर हमला करने के बजाय परिस्थिति को समझें', 'सहानुभूतिपूर्ण दृष्टिकोण संबंधों को बचाता है'],
    guTitle: 'સંબંધોમાં બેવડા ધોરણો (Attribution Asymmetry)', guSummary: 'સંબંધોમાં પોતાની ભૂલને સંજોગોનો દોષ આપવો પરંતુ સાથીદારની ભૂલને તેના ખરાબ સ્વભાવનું પરિણામ માનવું.', guTakeaways: ['બેવડા ધોરણો છોડો', 'સાથીદારની મજબૂરી સમજો', 'સ્વભાવ પર આક્ષેપ ન કરો'],
    mrTitle: 'नात्यातील दुटप्पी दृष्टिकोन (Attribution Asymmetry)', mrSummary: 'स्वतःच्या चुकीला परिस्थिती जबाबदार धरणे पण जोडीदाराच्या चुकीला त्याचा स्वभाव कारणीभूत मानणे.', mrTakeaways: ['दुटप्पी विचार थांबवा', 'जोडीदाराला समजून घ्या', 'स्वभावावर दोषारोप करू नका'],
    teTitle: 'సంబంధాలలో ఆపాదనా అసమానత', teSummary: 'మన తప్పులకు పరిస్థితులను సమర్థించుకుంటూ భాగస్వామి తప్పులకు వారి గుణాన్ని నిందించే ద్వంద్వ వైఖరి.', teTakeaways: ['ద్వంద్వ వైఖరిని విడనాడండి', 'పరిస్థితిని అర్థం చేసుకోండి', 'వ్యక్తిత్వాన్ని నిందించవద్దు'],
    taTitle: 'உறவுகளில் இரட்டை நிலைப்பாடு (Attribution Asymmetry)', taSummary: 'நம் தவறுகளுக்கு சூழ்நிலையை காரணமாகக் கூறிவிட்டு துணையின் தவறுகளுக்கு அவரது குணத்தைக் குறை கூறும் போக்கு.', taTakeaways: ['இரட்டை நிலைப்பாட்டை தவிருங்கள்', 'சூழ்நிலையை புரிந்து கொள்ளுங்கள்', 'குணத்தை குறை கூறாதீர்கள்'],
    knTitle: 'ಸಂಬಂಧಗಳಲ್ಲಿ ದ್ವಂದ್ವ ದೃಷ್ಟಿಕೋನ (Attribution Asymmetry)', knSummary: 'ತನ್ನ ತಪ್ಪಿಗೆ ಸಂದರ್ಭವನ್ನು ದೂಷಿಸಿ ಸಂಗಾತಿಯ ತಪ್ಪಿಗೆ ಅವರ ಗುಣವನ್ನೇ ಹಳಿಯುವ ಮಾನಸಿಕ ಪಕ್ಷಪಾತ.', knTakeaways: ['ದ್ವಂದ್ವ ಧೋರಣೆ ಬಿಡಿ', 'ಸಂದರ್ಭವನ್ನು ಅರ್ಥಮಾಡಿಕೊಳ್ಳಿ', 'ವ್ಯಕ್ತಿತ್ವದ ಮೇಲೆ ದಾಳಿ ಮಾಡಬೇಡಿ'],
    mlTitle: 'ബന്ധങ്ങളിലെ ഇരട്ടത്താപ്പ് മനോഭാവം', mlSummary: 'സ്വന്തം തെറ്റുകൾക്ക് സാഹചര്യങ്ങളെ പഴിചാരുകയും പങ്കാളിയുടെ തെറ്റുകൾക്ക് അവരുടെ സ്വഭാവത്തെ കുറ്റപ്പെടുത്തുകയും ചെയ്യുന്ന രീതി.', mlTakeaways: ['ഇരട്ടത്താപ്പ് ഉപേക്ഷിക്കുക', 'സാഹചര്യങ്ങൾ മനസ്സിലാക്കുക', 'സ്വഭാവത്തെ കുറ്റപ്പെടുത്തരുത്'],
    bnTitle: 'সম্পর্কের পক্ষপাতমূলক মূল্যায়ন', bnSummary: 'নিজের ভুলের জন্য পরিস্থিতিকে দায়ী করা কিন্তু সঙ্গীর ভুলের জন্য তার চরিত্রকে দোষারোপ করার দ্বিমুখী নীতি।', bnTakeaways: ['দ্বিমুখী নীতি ত্যাগ করুন', 'পরিস্থিতি বোঝার চেষ্টা করুন', 'ব্যক্তিত্বকে আক্রমণ করবেন না'],
    paTitle: 'ਰਿਸ਼ਤਿਆਂ ਵਿੱਚ ਦੋਹਰਾ ਮਾਪਦੰਡ (Attribution Asymmetry)', paSummary: 'ਆਪਣੀ ਗਲਤੀ ਨੂੰ ਹਾਲਾਤਾਂ ਦਾ ਕਸੂਰ ਦੱਸਣਾ ਪਰ ਸਾਥੀ ਦੀ ਗਲਤੀ ਨੂੰ ਉਸਦੇ ਸੁਭਾਅ ਦਾ ਨੁਕਸ ਮੰਨਣਾ।', paTakeaways: ['ਦੋਹਰਾ ਮਾਪਦੰਡ ਛੱਡੋ', 'ਸਾਥੀ ਦੇ ਹਾਲਾਤ ਸਮਝੋ', 'ਸੁਭਾਅ ਤੇ ਚਿੱਕੜ ਨਾ ਉਛਾਲੋ'],
    urTitle: 'رشتوں میں دہرا معیار (Attribution Asymmetry)', urSummary: 'اپنی غلطی کو مجبوری اور حالات کا نتیجہ قرار دینا مگر ساتھی کی غلطی کو اس کی بری فطرت کہنا۔', urTakeaways: ['دوہرے معیار سے بچیں', 'ساتھی کی مجبوری سمجھیں', 'کردار پر حملہ نہ کریں'],
    orTitle: 'ସମ୍ପର୍କରେ ଦ୍ୱିମୁଖୀ ମୂଲ୍ୟାଙ୍କନ', orSummary: 'ନିଜ ଭୁଲ୍ ପାଇଁ ପରିସ୍ଥିତିକୁ ଦୋଷ ଦେବା କିନ୍ତୁ ସାଥୀଙ୍କ ଭୁଲ୍ ପାଇଁ ତାଙ୍କ ଚରିତ୍ରକୁ ଦାୟୀ କରିବା।', orTakeaways: ['ଦ୍ୱିମୁଖୀ ନୀତି ତ୍ୟାଗ କରନ୍ତୁ', 'ପରିସ୍ଥିତିକୁ ବୁଝିବାକୁ ଚେଷ୍ଟା କରନ୍ତୁ', 'ସ୍ୱଭାବକୁ ନିନ୍ଦା କରନ୍ତୁ ନାହିଁ'],
    asTitle: 'সম্পৰ্কত দ্বৈত দৃষ্টিভংগী (Attribution Asymmetry)', asSummary: 'নিজৰ ভুলক পৰিস্থিতিৰ দোষ বুলি কোৱা কিন্তু সংগীৰ ভুলক তেওঁৰ চৰিত্ৰৰ দোষ বুলি ভবাৰ মানসিকতা।', asTakeaways: ['দ্বৈত নীতি পৰিহাৰ কৰক', 'পৰিস্থিতিক বুজিবলৈ যত্ন কৰক', 'চৰিত্ৰক আক্ৰমণ নকৰিব']
  }
];

