import { ComprehensiveTopicDef } from '../topicGeneratorHelper';

export const SOCIAL_MEDIA_TOPICS: ComprehensiveTopicDef[] = [
  {
    fileName: 'doomscrollingCycle.ts',
    varName: 'doomscrolling_cycle',
    id: 'doomscrolling_cycle',
    categoryId: 'social_media_tech',
    slug: 'doomscrolling-cycle',
    difficulty: 'beginner',
    readTime: 5,
    sortWeight: 5,
    titleEn: 'The Doomscrolling Loop: Negativity Bias in the Algorithmic Era',
    subtitleEn: 'Why the brain obsesses over catastrophic news feeds and how infinite scrolling traps attention.',
    shortDescEn: 'The compulsive habit of continuously scrolling through distressing, negative, and threatening news on social media despite feeling anxious and exhausted.',
    oneLineEn: 'Searching for certainty in bad news, but only feeding your nervous system panic.',
    summary30sEn: 'Coined during the 2020 pandemic and studied extensively by clinical psychologists, doomscrolling is driven by an ancient survival instinct: the brain seeks information to gain a sense of control during threats. However, algorithmic feeds curate an endless stream of crises, creating a toxic loop of hyperarousal and despair.',
    coreConceptEn: 'Doomscrolling hijacks the evolutionary negativity bias. Ancestral brains treated negative information as a matter of immediate survival. On modern platforms, algorithmic recommendation models exploit this bias by prioritizing outrage and disaster content, tricking your amygdala into believing you are constantly surrounded by lethal threats.',
    summary60sEn: 'Research shows doomscrolling triggers chronic sympathetic nervous system activation, flooding the body with cortisol. While users believe scrolling makes them "informed", cognitive testing shows it severely impairs working memory, sleep architecture, and rational risk assessment. The antidote is setting physical cessation boundaries.',
    takeawaysEn: [
      'Doomscrolling is an evolutionary survival reflex hijacked by engagement algorithms',
      'Consuming negative news does not prepare you for danger; it paralyzes your agency',
      'The brain treats digital headlines as local, immediate physical threats',
      'Replacing infinite feeds with deliberate, bounded news consumption restores mental calm'
    ],
    whyItHappensEn: 'Negativity bias and the illusion of control: the brain subconsciously believes that gathering more disaster data will protect it from unforeseen calamity.',
    evolutionaryEn: 'Early humans who hyper-focused on predator tracks or famine warnings survived; those who ignored negative cues perished.',
    howItWorksEn: 'Stress or boredom -> Open app -> Negative headline encountered -> Amygdala feels threat -> Brain demands more data to feel safe -> Infinite scroll provides endless threats -> Cortisol spikes -> Insomnia and dread.',
    visualHeadlineEn: 'The Illusion of Preparation vs. Algorithmic Paralysis',
    visualDescEn: 'How compulsive news consumption masquerades as awareness while eroding well-being.',
    sideALabelEn: 'Informed Awareness (Healthy)',
    sideADetailEn: 'Reads a 15-minute curated morning briefing, understands key geopolitical facts, takes constructive action.',
    sideBLabelEn: 'Doomscrolling Loop (Toxic)',
    sideBDetailEn: 'Scrolls disaster threads for 90 minutes in bed at midnight; heart rate elevated, sleep destroyed.',
    researchSummaryEn: 'Sharma et al. (2022, Technology, Mind, and Behavior) and Buchanan et al. (2021, PLOS ONE) proved doomscrolling directly predicts elevated secondary traumatic stress, depressive symptoms, and cognitive fatigue.',
    refAuthor: 'Sharma, B., Lee, S. S., & Johnson, B. K.',
    refYear: 2022,
    refTitle: 'The Dark at the End of the Tunnel: Doomscrolling and Mental Health',
    refCitation: 'Sharma, B., et al. (2022). Technology, Mind, and Behavior, 3(1).',
    refDoi: 'https://doi.org/10.1037/tmb0000059',
    scenarioTitleEn: 'The 1 AM Twitter Spiral in Noida',
    scenarioContextEn: 'Vikrant, a product manager in Noida, woke up at 1 AM to check a breaking geopolitical alert. Two hours later, he was 400 tweets deep into nuclear war commentary, climate collapse predictions, and layoffs, feeling trembling anxiety and a racing pulse.',
    scenarioBiasEn: 'Vikrant fell into the doomscrolling trap: his brain sought cognitive reassurance, but the algorithm fed continuous threat stimuli.',
    scenarioOptimalEn: 'Place the phone in another room overnight. When news curiosity strikes, check a trusted factual portal once at noon, not in the dark before sleep.',
    scenarioReflectionEn: 'How often do you close a news app feeling genuinely empowered and calm versus feeling anxious, heavy, and drained?',
    howToRecognizeEn: 'Losing track of time in bed while reading catastrophic headlines, feeling a tight chest, and an inability to put the phone down despite feeling exhausted.',
    whereEn: 'Late-night phone use, election cycles, pandemic outbreaks, and geopolitical crises.',
    misconceptionsEn: 'Myth: "Doomscrolling keeps me informed and prepared for the real world." Fact: It skews your worldview toward extreme statistical outliers and induces learned helplessness.',
    limitationsEn: 'Staying aware of local emergencies (earthquakes, curfews) is necessary; the pathology is the compulsive, passive consumption of global unresolvable dread.',
    howToRespondEn: 'The Digital Sunset: Charge your phone outside the bedroom and establish a hard rule of no news consumption after 9 PM.',
    defensesEn: [
      { title: 'The 15-Minute News Bounding', instruction: 'Consume news only once a day from text-based editorial sources for 15 minutes, never from algorithmic endless-scroll feeds.' },
      { title: 'Physical Phone Quarantine', instruction: 'Buy an analog alarm clock and make the bedroom an absolute screen-free zone to eliminate midnight threat spirals.' }
    ],
    pqPromptEn: 'You find yourself lying in bed at midnight feeling anxious while reading about a distant natural catastrophe for the 45th minute. What is the most psychologically sound intervention?',
    pqScenarioEn: 'Your chest feels tight and you tell yourself: "Just one more tweet to make sure things are under control."',
    pqExplanationEn: 'The belief that reading more will provide reassurance is the cognitive trap of doomscrolling. Physical disconnection is required to break the loop.',
    pqAntidoteEn: 'Physically place the phone across the room, engage in slow diaphragmatic breathing, and ground your attention in your immediate physical environment.',
    pqOptionsEn: [
      { id: 'opt_a', text: 'Keep reading until you find an optimistic tweet that allows you to relax.', isCorrect: false, feedback: 'Incorrect. The algorithm is engineered to keep showing outrage and disaster.' },
      { id: 'opt_b', text: 'Put the phone face down in another room, take 5 slow belly breaths, and remind yourself: "I am safe in this room right now."', isCorrect: true, feedback: 'Correct! This interrupts the neurochemical threat loop and re-engages the parasympathetic system.' },
      { id: 'opt_c', text: 'Comment on 10 political posts to vent your nervous energy.', isCorrect: false, feedback: 'Incorrect. Active commenting escalates dopamine and adrenaline arousal.' }
    ],
    reflectionPromptEn: 'What is one specific positive action or hobby that could replace your late-night scrolling habit?',
    titleHinglish: 'The Doomscrolling Loop: Buri Khabron Ka Nasha',
    subtitleHinglish: 'Kyu hamara dimaag aadhi raat ko buri khabrein scroll karta rehta hai jabki andar se ghabrahat hoti hai.',
    shortDescHinglish: 'Compulsive negative news scrolling: Kaise social media algorithms hamari darr ki natural instinct ko trap karte hain.',
    oneLineHinglish: 'Khatre ki khabrein padh kar sukoon dhoondna, par andar anxiety ka toofan khada karna.',
    summary30sHinglish: 'Jab hum pareshan hote hain, to dimaag darr se bachne ke liye information dhoondta hai. Lekin Twitter aur Instagram ke algorithms sirf aag lagane wali aur disaster wali khabrein dikhate hain. Result: 2 ghante scroll karne ke baad insaan helpless aur depressed feel karta hai.',
    coreConceptHinglish: 'Hamare purvaj jungle me sher ki aahat par focus karte the taaki bach sakein (Negativity Bias). Social media apps isi biological darr ka fayda uthati hain. Unhe pata hai ki bad news par log scroll karna band nahi karte.',
    summary60sHinglish: 'Research dikhati hai ki aadhi raat ko buri khabrein padhne se cortisol spike hota hai aur neend ki quality khatam ho jati hai. Aapko lagta hai ki aap "aware" ho rahe hain, par actually aapka dimaag panic mode me freeze ho raha hai. Iska ek hi ilaaj hai: Phone ko bedroom se bahar nikalna.',
    howItWorksHinglish: 'Boredom hua -> App kholi -> Darr wali headline aayi -> Amygdala bola "aur jaano" -> Infinite scroll chalta raha -> Raat ke 2 baj gaye -> Anxiety aur insomnia hua.',
    howToRespondHinglish: 'Digital Sunset apnayein: Raat 9 baje ke baad news band. Phone ko drawing room me charge karein aur ek ₹200 ki analog ghadi khareed lein.',
    takeawaysHinglish: [
      'Doomscrolling aapko smart nahi banata, balki aapko helpless aur anxious feel karata hai',
      'Algorithms darr aur gusse par engagement kamate hain, unhe aapki mental peace se matlab nahi',
      'Aadhi raat ko global problems solve karne ki koshish dimaag ka sabse bada trap hai',
      'News din me sirf 15 minute padhein, text format me, endless scroll par nahi'
    ],
    pqPromptHinglish: 'Aap bistar par lete huye 1 ghante se economic recession aur war ki tweets padh rahe hain aur dil tezi se dhadak raha hai. Sahi step kya hoga?',
    pqExplanationHinglish: 'Phone band karke physical environment me wapas aana nervous system ko reset karne ka ek-matra tareeqa hai.',
    pqOptionsHinglish: [
      { id: 'opt_a', text: 'Tab tak padhte rehna jab tak koi khushi wali tweet na mil jaye.', isCorrect: false, feedback: 'Galat. Algorithm aisi feed me negative content hi dikhayega.' },
      { id: 'opt_b', text: 'Phone ko doosre kamre me rakh aana, 5 gehri saans lena aur so jana.', isCorrect: true, feedback: 'Sahi! Yeh doomscrolling cycle ko break karta hai.' },
      { id: 'opt_c', text: 'Comments me logon se ladna shuru kar dena.', isCorrect: false, feedback: 'Galat. Isse adrenaline aur badhega.' }
    ],
    hiTitle: 'डूमस्क्रॉलिंग चक्र (Doomscrolling Loop)',
    hiSummary: 'सोशल मीडिया पर नकारात्मक और विनाशकारी समाचारों को लगातार स्क्रॉल करने की बाध्यकारी लत और उसका मानसिक स्वास्थ्य पर प्रभाव।',
    hiTakeaways: ['डूमस्क्रॉलिंग मस्तिष्क के नकारात्मक पूर्वाग्रह का शोषण करती है', 'बुरी खबरें पढ़ने से चिंता और अनिद्रा बढ़ती है', 'डिजिटल सीमाएं और स्क्रीन-मुक्त शयनकक्ष आवश्यक हैं'],
    guTitle: 'ડૂમસ્ક્રોલિંગ લૂપ (નકારાત્મક સમાચારોની લત)', guSummary: 'સોશિયલ મીડિયા પર સતત નકારાત્મક સમાચારો જોવાની ટેવ અને માનસિક શાંતિ પર તેની અસર.', guTakeaways: ['નકારાત્મકતાથી દૂર રહો', 'રાત્રે ફોનનો ઉપયોગ ટાળો', 'મર્યાદિત સમાચાર વાંચો'],
    mrTitle: 'डूमस्क्रोलिंग लूप (नकारात्मक बातम्यांचे व्यसन)', mrSummary: 'सोशल मीडियावर सतत संकट आणि भीतिदायक बातम्या वाचत राहण्याची घातक मानसिक सवय.', mrTakeaways: ['भीतीदायक बातम्यांचे व्यसन टाळा', 'रात्री मोबाईलचा वापर थांबवा', 'सकारात्मक गोष्टींवर लक्ष द्या'],
    teTitle: 'డూమ్‌స్క్రోలింగ్ లూప్ (ప్రతికూల వార్తల వ్యసనం)', teSummary: 'సోషల్ మీడియాలో నిరంతరం ఆందోళనకరమైన వార్తలను చూస్తూ గడిపే మానసిక అలవాటు.', teTakeaways: ['ప్రతికూల వార్తలను పరిమితం చేయండి', 'రాత్రి వేళ ఫోన్ పక్కన పెట్టండి', 'మానసిక ప్రశాంతతకు ప్రాధాన్యత ఇవ్వండి'],
    taTitle: 'டூம்ஸ்க்ரோலிங் சுழற்சி (எதிர்மறை செய்தி அடிமைத்தனம்)', taSummary: 'சமூக வலைத்தளங்களில் தொடர்ந்து பதற்றமூட்டும் செய்திகளை பார்த்துக்கொண்டே இருக்கும் உளவியல் பழக்கம்.', taTakeaways: ['எதிர்மறை செய்திகளை தவிருங்கள்', 'இரவில் போன் பார்க்காதீர்கள்', 'மன அமைதியை பாதுகாக்கவும்'],
    knTitle: 'ಡೂಮ್‌ಸ್ಕ್ರೋಲಿಂಗ್ ಲೂಪ್ (ನಕಾರಾತ್ಮಕ ಸುದ್ದಿಗಳ ಚಟ)', knSummary: 'ಸಾಮಾಜಿಕ ಮಾಧ್ಯಮಗಳಲ್ಲಿ ನಿರಂತರವಾಗಿ ಭಯಾನಕ ಮತ್ತು ಆತಂಕಕಾರಿ ಸುದ್ದಿಗಳನ್ನು ಓದುವ ಮಾನಸಿಕ ದಾಸ್ಯ.', knTakeaways: ['ನಕಾರಾತ್ಮಕತೆಯನ್ನು ನಿಯಂತ್ರಿಸಿ', 'ರಾತ್ರಿ ಫೋನ್ ಮುಟ್ಟಬೇಡಿ', 'ಮನಸ್ಸಿನ ಶಾಂತಿಗೆ ಆದ್ಯತೆ ನೀಡಿ'],
    mlTitle: 'ഡൂംസ്ക്രോളിംഗ് ലൂപ്പ് (നെഗറ്റീവ് വാർത്താ ആസക്തി)', mlSummary: 'സോഷ്യൽ മീഡിയയിൽ നിരന്തരം ഭയപ്പെടുത്തുന്ന വാർത്തകൾ വായിച്ചു കൂട്ടുന്ന അപകടകരമായ മാനസികാവസ്ഥ.', mlTakeaways: ['നെഗറ്റീവ് വാർത്തകൾ കുറയ്ക്കുക', 'രാത്രി ഫോൺ മാറ്റിവെക്കുക', 'മാനസികാരോഗ്യം സംരക്ഷിക്കുക'],
    bnTitle: 'ডুমস্ক্রোলিং লুপ (নেতিবাচক সংবাদের আসক্তি)', bnSummary: 'সোশ্যাল মিডিয়ায় অনবরত বিপর্যয় ও আতঙ্কের খবর দেখার ক্ষতিকর মানসিক অভ্যাস।', bnTakeaways: ['নেতিবাচক খবর এড়িয়ে চলুন', 'রাতে ফোন দূরে রাখুন', 'সীমিত তথ্য গ্রহণ করুন'],
    paTitle: 'ਡੂਮਸਕ੍ਰੋਲਿੰਗ ਲੂਪ (ਮਾੜੀਆਂ ਖ਼ਬਰਾਂ ਦੀ ਲਤ)', paSummary: 'ਸੋਸ਼ਲ ਮੀਡੀਆ ਤੇ ਲਗਾਤਾਰ ਡਰਾਉਣੀਆਂ ਅਤੇ ਮਾੜੀਆਂ ਖ਼ਬਰਾਂ ਪੜ੍ਹਦੇ ਰਹਿਣ ਦੀ ਮਾਨਸਿਕ ਆਦਤ।', paTakeaways: ['ਮਾੜੀਆਂ ਖ਼ਬਰਾਂ ਤੋਂ ਬਚੋ', 'ਰਾਤ ਨੂੰ ਫ਼ੋਨ ਦੂਰ ਰੱਖੋ', 'ਮਨ ਦੀ ਸ਼ਾਂਤੀ ਬਣਾਈ ਰੱਖੋ'],
    urTitle: 'ڈوم اسکرولنگ کا چکر (منفی خبروں کی لت)', urSummary: 'سوشل میڈیا پر مسلسل خوفناک اور مایوس کن خبریں دیکھتے رہنے کی نفسیاتی عادت۔', urTakeaways: ['منفی خبروں سے پرہیز کریں', 'رات کو موبائل دور رکھیں', 'ذہنی سکون کو ترجیح دیں'],
    orTitle: 'ଡୁମ୍‌ସ୍କ୍ରୋଲିଂ ଲୁପ୍ (ନକାରାତ୍ମକ ଖବରର ନିଶା)', orSummary: 'ସୋସିଆଲ ମିଡ଼ିଆରେ ନିରନ୍ତର ଭୟାନକ ଓ ଆତଙ୍କଜନକ ଖବର ଦେଖିବାର ବାଧ୍ୟତାମୂଳକ ଅଭ୍ୟାସ।', orTakeaways: ['ନକାରାତ୍ମକ ଖବର ସୀମିତ କରନ୍ତୁ', 'ରାତିରେ ଫୋନ୍ ବନ୍ଦ ରଖନ୍ତୁ', 'ମାନସିକ ଶାନ୍ତି ରକ୍ଷା କରନ୍ତୁ'],
    asTitle: 'ডুমস্ক্ৰ’লিং লুপ (নেতিবাচক বাতৰিৰ নিচা)', asSummary: 'ছচিয়েল মিডিয়াত অহৰহ ভয়ংকৰ আৰু হতাশাজনক বাতৰি পঢ়ি থকাৰ ক্ষতিকাৰক অভ্যাস।', asTakeaways: ['নেতিবাচক বাতৰিৰ পৰা আঁতৰি থাকক', 'ৰাতি ফোন ব্যৱহাৰ নকৰিব', 'মানসিক স্বাস্থ্যৰ যত্ন লওক']
  },

  {
    fileName: 'phantomVibrationSyndrome.ts',
    varName: 'phantom_vibration_syndrome',
    id: 'phantom_vibration_syndrome',
    categoryId: 'social_media_tech',
    slug: 'phantom-vibration-syndrome',
    difficulty: 'beginner',
    readTime: 5,
    sortWeight: 6,
    titleEn: 'Phantom Vibration Syndrome: Tactile Hypervigilance',
    subtitleEn: 'Why you constantly feel your phone vibrating in your pocket even when nobody called.',
    shortDescEn: 'A sensory hallucination where an individual perceives that their cell phone is vibrating or ringing when it is not, caused by anticipatory sensory gating in the cerebral cortex.',
    oneLineEn: 'Your brain treating every slight muscle twitch as an urgent incoming digital notification.',
    summary30sEn: 'Studied extensively by Dr. Michelle Drouin and neuroscientists, Phantom Vibration Syndrome affects up to 89% of smartphone users. The brain anticipates notifications so intensely that it misinterprets clothes rubbing against the leg or muscle spasms as phone vibration signals.',
    coreConceptEn: 'Signal Detection Theory explains phantom vibrations. The brain constantly monitors ambiguous sensory signals. Because missing an important text or notification carries perceived social cost, the brain sets its sensitivity threshold extremely low: it prefers a "false alarm" (checking an unvibrated phone) over a "miss" (ignoring a real call).',
    summary60sEn: 'This phenomenon proves that modern smartphones have literally become integrated into the human brain\'s biological body schema (the neurological map of one\'s physical body). When the phone is in your pocket, your somatosensory cortex treats it like an extended limb, remaining in a state of chronic low-grade sensory hypervigilance.',
    takeawaysEn: [
      'Phantom vibrations are sensory false alarms generated by an anxious brain',
      'Up to 90% of college students and knowledge workers experience this regularly',
      'The brain treats the smartphone as a literal neurological extension of the body',
      'Carrying the phone in a bag or taking weekly screen detoxes resets the sensory threshold'
    ],
    whyItHappensEn: 'Signal detection calibration: our social reward circuitry values incoming connection so highly that the brain biases sensory interpretation toward false positives.',
    evolutionaryEn: 'Hunters in the wild needed to mistake rustling grass for a predator (false alarm) rather than ignore a tiger (fatal miss).',
    howItWorksEn: 'Anticipation of messages -> Somatosensory cortex increases tactile gain -> Thigh muscle twitches or trousers rustle -> Brain categorizes sensation as vibration -> Reach for pocket -> Screen is blank.',
    visualHeadlineEn: 'Signal Detection Theory: The Low Threshold Trap',
    visualDescEn: 'How the brain trades sensory accuracy for avoiding social misses.',
    sideALabelEn: 'Sensory Reality',
    sideADetailEn: 'Pocket fabric rubs against thigh hair follicle (0.05 Newtons of friction, zero phone activity).',
    sideBLabelEn: 'Brain\'s Perceptual Output',
    sideBDetailEn: '"ALERT! Important notification incoming! Check your phone right now!" (False Positive).',
    researchSummaryEn: 'Drouin et al. (2012, Computers in Human Behavior) and Rothberg et al. (2010) found that 89% of respondents experienced phantom vibrations, with frequency directly correlating to emotional dependency on text messaging.',
    refAuthor: 'Drouin, M., Kaiser, D. H., & Miller, D. A.',
    refYear: 2012,
    refTitle: 'Phantom Vibrations Among Undergraduates: Prevalence and Characteristics',
    refCitation: 'Drouin, M., et al. (2012). Computers in Human Behavior, 28(4), 1490–1496.',
    refDoi: 'https://doi.org/10.1016/j.chb.2012.03.013',
    scenarioTitleEn: 'The Mumbai Local Train False Alarm',
    scenarioContextEn: 'Sameer was commuting on a crowded Mumbai local train to Churchgate. Every 4 minutes, he reached down to tap his front pocket, convinced his phone was buzzing with urgent client emails. When he finally took it out, it was at 0% battery and had been dead for an hour.',
    scenarioBiasEn: 'Sameer experienced acute tactile hypervigilance: train vibrations and muscle tension were misclassified by his cortex as digital notifications.',
    scenarioOptimalEn: 'Break the tactile attachment: carry the phone in a backpack compartment and turn off vibration mode for non-essential notifications.',
    scenarioReflectionEn: 'How many times today did you reach for your pocket only to find no new messages or alerts waiting for you?',
    howToRecognizeEn: 'Reaching for your thigh or pocket feeling an unmistakable buzzing sensation, only to pull out a screen that has had no alerts for hours.',
    whereEn: 'Commutes, exam halls, high-pressure office environments, and waiting rooms.',
    misconceptionsEn: 'Myth: "Phantom vibrations mean you have brain damage or schizophrenia." Fact: It is a benign neurological false alarm caused by learned cognitive conditioning.',
    limitationsEn: 'Rarely, true nerve damage (meralgia paresthetica) can cause tingling in the thigh; the distinction is that phantom vibrations match the exact haptic rhythm of your phone.',
    howToRespondEn: 'Relocate the device: stop carrying your phone in the exact same front pocket. Moving it to a jacket pocket or bag breaks the sensory association.',
    defensesEn: [
      { title: 'The Pocket Relocation Drill', instruction: 'Keep your phone in your desk drawer or backpack rather than your trouser pocket to desensitize your leg nerves.' },
      { title: 'Haptic Notification Audit', instruction: 'Turn off vibration for WhatsApp groups, social media, and email; keep haptic buzzes exclusively for direct phone calls.' }
    ],
    pqPromptEn: 'You feel a distinct vibration in your right pocket, reach in, and realize your phone is actually on the kitchen table. What neural mechanism explains this?',
    pqScenarioEn: 'You swear on your life you felt the exact 2-buzz pattern of a WhatsApp notification.',
    pqExplanationEn: 'Phantom vibration is a sensory false positive where clothing friction or muscle fasciculations are mapped onto learned digital notification patterns.',
    pqAntidoteEn: 'Recognize the hypervigilance and recalibrate by leaving the phone away from your body for several hours.',
    pqOptionsEn: [
      { id: 'opt_a', text: 'You are experiencing early-onset neurological motor neuron degeneration.', isCorrect: false, feedback: 'Incorrect. It is a completely normal cognitive false positive.' },
      { id: 'opt_b', text: 'Your brain’s signal detection threshold is set so low that it misinterprets ordinary clothes friction as a notification.', isCorrect: true, feedback: 'Correct! This is classical Signal Detection Theory in digital psychology.' },
      { id: 'opt_c', text: 'Someone hacked your phone and is sending ghost signals.', isCorrect: false, feedback: 'Incorrect. This is a paranoid misconception.' }
    ],
    reflectionPromptEn: 'Can you spend an entire Sunday carrying your phone exclusively in a backpack rather than your pocket?',
    titleHinglish: 'Phantom Vibration Syndrome: Jeb Me Naqli Vibration Ka Ehsaas',
    subtitleHinglish: 'Kyu lagta hai ki phone vibrate hua, par jeb se nikaalo to koi notification nahi hota.',
    shortDescHinglish: 'Sensory hallucination: Jab kapdo ki ragad ya muscle twitch ko dimaag phone ka vibration samajh leta hai.',
    oneLineHinglish: 'Dimaag ka phone ke notifications ke liye itna bechain hona ki hawa se bhi phone bajta lagta hai.',
    summary30sHinglish: 'Research ke mutabiq 89% smartphone users ko lagta hai ki unka phone vibrate hua, jabki phone par koi call nahi aayi hoti. Hamara dimaag notifications ke dopamine ke liye itna alert rehta hai ki pant ki ragad ko bhi call samajh leta hai.',
    coreConceptHinglish: 'Ise kehte hain Signal Detection Theory. Dimaag kehta hai: "Agar call aayi aur maine miss kar di to nuksan hoga, isliye shak hone par bhi phone check kar lo." Dimaag phone ko apne sharir ka ek hissa maan leta hai.',
    summary60sHinglish: 'Agar aap roz phone ko right pocket me rakhte hain, to wahan ki nerves hyper-sensitive ho jati hain. Train ki vibration ya pair ki muscle twitch ko dimaag message samajhta hai. Is aadat ko todne ke liye phone ko jeb se nikaal kar bag me rakhna shuru karein.',
    howItWorksHinglish: 'Notification ka intezar -> Dimaag nerves ko extra alert karta hai -> Pant thodi si hili -> Dimaag ne signal diya "Vibration hua!" -> Jeb me haath daala -> Screen blank thi.',
    howToRespondHinglish: 'Phone ki jagah badlein: Phone ko jeans ki pocket me rakhna band karein, bag ya table par rakhein. Aur faltu apps ke vibration notifications band kar dein.',
    takeawaysHinglish: [
      'Phantom vibration koi bimari nahi, balki mobile addiction ka brain signal hai',
      'Dimaag notification miss karne ke darr se jhoothe alerts generate karta hai',
      'Phone ko pant ki pocket ke bajaye bag ya table par rakhne se yeh 3 din me theek ho jata hai',
      'Faltu WhatsApp groups aur apps ka vibration hamesha OFF rakhein'
    ],
    pqPromptHinglish: 'Aapko laga jeb me phone 2 baar vibrate hua, nikaal kar dekha to phone switch off tha. Dimaag me kya hua?',
    pqExplanationHinglish: 'Dimaag ne kapdo ki aam movement ko notification samajh liya kyuki wo extra alert mode me tha.',
    pqOptionsHinglish: [
      { id: 'opt_a', text: 'Aapka dimaag kharab ho raha hai aur doctor ke paas jana padega.', isCorrect: false, feedback: 'Galat. Yeh 90% smartphone users ke sath hota hai.' },
      { id: 'opt_b', text: 'Dimaag ki sensory nerves ne kapde ki ragad ko galti se vibration interpret kar liya.', isCorrect: true, feedback: 'Sahi! Ise Phantom Vibration kehte hain.' },
      { id: 'opt_c', text: 'Phone switch off hone ke baad bhi tarangein chhod raha tha.', isCorrect: false, feedback: 'Galat. Yeh physical sensation brain ki hai, phone ki nahi.' }
    ],
    hiTitle: 'आभासी कंपन सिंड्रोम (Phantom Vibration)',
    hiSummary: 'फोन में कोई कॉल या मैसेज न होने पर भी जेब में कंपन महसूस होने का संवेदी मनोवैज्ञानिक भ्रम।',
    hiTakeaways: ['मस्तिष्क कपड़ों के घर्षण को नोटिफिकेशन समझ लेता है', 'यह अत्यधिक डिजिटल निर्भरता का संकेत है', 'फोन को जेब के बजाय बैग में रखना इसका समाधान है'],
    guTitle: 'ફેન્ટમ વાઇબ્રેશન સિન્ડ્રોમ (આભાસી કંપન)', guSummary: 'ફોન વાગ્યો ન હોવા છતાં ખિસ્સામાં વાઇબ્રેશનનો ખોટો આભાસ થવાની મનોવૈજ્ઞાનિક સ્થિતિ.', guTakeaways: ['ખોટા આભાસથી સાવધાન રહો', 'ફોનને ખિસ્સામાં ન રાખો', 'ડિજિટલ નિર્ભરતા ઘટાડો'],
    mrTitle: 'फॅन्टम व्हायब्रेशन सिंड्रोम (भासमान कंपन)', mrSummary: 'फोनवर कोणताही मेसेज नसतानाही खिशात व्हायब्रेशन झाल्याचा भास होण्याची मेंदूची सवय.', mrTakeaways: ['हा मेंदूचा एक भास आहे', 'अति-डिजिटल वापराचे लक्षण', 'फोन खिशात ठेवणे टाळा'],
    teTitle: 'ఫాంటమ్ వైబ్రేషన్ సిండ్రోమ్ (భ్రమతో కూడిన ప్రకంపనలు)', teSummary: 'ఫోన్ మోగకపోయినా జేబులో వైబ్రేషన్ వచ్చినట్లు అనిపించే సహజ మానసిక భ్రమ.', teTakeaways: ['ఇది ఒక నాడీ సంబంధిత భ్రమ', 'డిజిటల్ వ్యసనాన్ని తగ్గించండి', 'ఫోన్‌ను బ్యాగ్‌లో ఉంచండి'],
    taTitle: 'போலி அதிர்வு நோய்க்குறி (Phantom Vibration)', taSummary: 'தொலைபேசி அதிராத போதும் பாக்கெட்டில் அதிர்வு ஏற்படுவது போல் தோன்றும் உளவியல் மாயை.', taTakeaways: ['இது ஒரு தவறான உணர்வு', 'செல்போன் பயன்பாட்டை குறையுங்கள்', 'போனை பையில் வையுங்கள்'],
    knTitle: 'ಫ್ಯಾಂಟಮ್ ವೈಬ್ರೇಶನ್ ಸಿಂಡ್ರೋಮ್', knSummary: 'ಫೋನ್ ರಿಂಗ್ ಆಗದಿದ್ದರೂ ಜೇಬಿನಲ್ಲಿ ಕಂಪನವಾದಂತೆ ಭಾಸವಾಗುವ ಸಾಮಾನ್ಯ ಮಾನಸಿಕ ಭ್ರಮೆ.', knTakeaways: ['ಇದು ನರಗಳ ಅತಿಯಾದ ಜಾಗರೂಕತೆ', 'ಮೊಬೈಲ್ ಗೀಳನ್ನು ಕಡಿಮೆ ಮಾಡಿ', 'ಫೋನನ್ನು ಬ್ಯಾಗ್‌ನಲ್ಲಿಡಿ'],
    mlTitle: 'ഫാന്റം വൈബ്രേഷൻ സിൻഡ്രോം', mlSummary: 'ഫോൺ വൈബ്രേറ്റ് ചെയ്യാതിരുന്നിട്ടും പോക്കറ്റിൽ അങ്ങനെ തോന്നുന്ന മാനസിക വിഭ്രാന്തി.', mlTakeaways: ['ഇതൊരു സാധാരണ ഇന്ദ്രിയ ഭ്രമമാണ്', 'ഫോൺ ഉപയോഗം പരിമിതപ്പെടുത്തുക', 'ഫോൺ ബാഗിൽ സൂക്ഷിക്കുക'],
    bnTitle: 'ফ্যান্টম ভাইব্রেশন সিন্ড্রোম (অলীক কম্পন)', bnSummary: 'ফোনে কোনো নোটিফিকেশন না আসা সত্ত্বেও পকেটে ভাইব্রেশন অনুভব করার মনস্তাত্ত্বিক ভ্রান্তি।', bnTakeaways: ['এটি একটি সংবেদনশীল বিভ্রম', 'ডিজিটাল নির্ভরতা কমান', 'ফোন পকেটে না রেখে ব্যাগে রাখুন'],
    paTitle: 'ਫੈਂਟਮ ਵਾਈਬ੍ਰੇਸ਼ਨ ਸਿੰਡਰੋਮ (ਕੰਬਣੀ ਦਾ ਭੁਲੇਖਾ)', paSummary: 'ਫ਼ੋਨ ਨਾ ਵੱਜਣ ਦੇ ਬਾਵਜੂਦ ਜੇਬ ਵਿੱਚ ਵਾਈਬ੍ਰੇਸ਼ਨ ਮਹਿਸੂਸ ਹੋਣ ਦਾ ਮਨੋਵਿਗਿਆਨਕ ਭੁਲੇਖਾ।', paTakeaways: ['ਇਹ ਦਿਮਾਗ ਦਾ ਇੱਕ ਭਰਮ ਹੈ', 'ਮੋਬਾਈਲ ਦੀ ਵਰਤੋਂ ਘਟਾਓ', 'ਫ਼ੋਨ ਬੈਗ ਵਿੱਚ ਰੱਖੋ'],
    urTitle: 'فینٹم وائبریشن سنڈروم (خام خیالی لرزش)', urSummary: 'موبائل پر کوئی کال یا میسج نہ ہونے کے باوجود جیب میں وائبریشن محسوس ہونے کا نفسیاتی وہم۔', urTakeaways: ['یہ حسیات کا ایک مغالطہ ہے', 'موبائل پر انحصار کم کریں', 'فون کو بیگ میں رکھیں'],
    orTitle: 'ଫାଣ୍ଟମ୍ ଭାଇବ୍ରେସନ୍ ସିଣ୍ଡ୍ରୋମ୍ (କାଳ୍ପନିକ କମ୍ପନ)', orSummary: 'ଫୋନ୍ ନବାଜିଲେ ମଧ୍ୟ ପକେଟ୍‌ରେ ଭାଇବ୍ରେସନ୍ ହେଉଥିବାର ମାନସିକ ଭ୍ରମ।', orTakeaways: ['ଏହା ମସ୍ତିଷ୍କର ଏକ ଭ୍ରମ', 'ମୋବାଇଲ୍ ବ୍ୟବହାର ସୀମିତ କରନ୍ତୁ', 'ଫୋନ୍‌କୁ ବ୍ୟାଗ୍‌ରେ ରଖନ୍ତୁ'],
    asTitle: 'ফেণ্টম ভাইব্ৰেচন চিনড্ৰম (কাল্পনিক কম্পন)', asSummary: 'ফোনটো নবজাকৈয়ে পকেটত ভাইব্ৰেচন হোৱা যেন অনুভৱ হোৱাৰ মানসিক বিভ্ৰান্তি।', asTakeaways: ['ই এটা ইন্দ্ৰিয়গত ভ্ৰম', 'ডিজিটেল আসক্তি হ্ৰাস কৰক', 'ফোনটো জেপত নাৰাখি বেগত থওক']
  },

  {
    fileName: 'parasocialInteraction.ts',
    varName: 'parasocial_interaction',
    id: 'parasocial_interaction',
    categoryId: 'social_media_tech',
    slug: 'parasocial-interaction',
    difficulty: 'beginner',
    readTime: 5,
    sortWeight: 7,
    titleEn: 'Parasocial Relationships: One-Sided Intimacy with Digital Creators',
    subtitleEn: 'How daily vloggers, streamers, and influencers trigger real attachment neurochemistry without real reciprocation.',
    shortDescEn: 'A psychological relationship where a media consumer develops an illusion of friendship, intimacy, and mutual trust with a public media figure who does not know they exist.',
    oneLineEn: 'Feeling like a YouTuber is your best friend while they don’t even know your name.',
    summary30sEn: 'First identified in 1956 by Donald Horton and R. Richard Wohl during the rise of television, parasocial interaction has exploded with social media and podcasting. High-definition front-facing cameras and daily casual vlogging simulate close-proximity eye contact, tricking the social brain into feeling genuine familial warmth.',
    coreConceptEn: 'The human brain evolved in small bands of 50 to 150 people where anyone you saw and listened to daily was an actual tribal member. Because our evolutionary social circuitry cannot distinguish between photons on a screen and a human sitting 2 feet away, hearing someone speak intimate details about their life triggers oxytocin and attachment security.',
    summary60sEn: 'While parasocial bonds can provide comfort and combat loneliness, they become pathological when individuals prioritize defending their favorite creator over real-world relationships, buy unnecessary branded merchandise to feel "seen", or experience deep grief when an influencer changes their life direction.',
    takeawaysEn: [
      'Parasocial bonds exploit the brain’s inability to differentiate video from physical presence',
      'Intimate camera angles and conversational podcasts simulate authentic tribal closeness',
      'Creators use parasocial intimacy as commercial leverage to sell products and sponsorships',
      'Healthy digital consumption treats creators as entertainers, not substitute real friends'
    ],
    whyItHappensEn: 'Ancestral brains never encountered one-way broadcasting; daily visual familiarity was 100% correlated with biological kinship or tribal alliance.',
    evolutionaryEn: 'Recognizing faces and voices over repeated encounters cemented vital cooperative alliances in early hunter-gatherer bands.',
    howItWorksEn: 'Creator posts daily intimate vlogs -> Direct eye contact into camera lens -> User listens on headphones (intimate acoustic space) -> Brain releases attachment neurochemicals -> User feels deep personal friendship -> Creator monetizes user trust.',
    visualHeadlineEn: 'Authentic Reciprocal Friendship vs. One-Sided Parasocial Bond',
    visualDescEn: 'The structural cognitive difference between genuine mutual intimacy and broadcast affection.',
    sideALabelEn: 'Real Reciprocal Friendship',
    sideADetailEn: 'Two-way vulnerability: they listen to your sorrows, hold you accountable, and show up when you are sick.',
    sideBLabelEn: 'Parasocial Dynamic (One-Way)',
    sideBDetailEn: 'You know everything about their dog, wedding, and diet; they see you only as an anonymous view count metric.',
    researchSummaryEn: 'Horton & Wohl (1956, Psychiatry) and Giles (2002, Media Psychology) analyzed how direct address and conversational media simulate interpersonal interaction, demonstrating deep emotional distress upon relationship termination.',
    refAuthor: 'Horton, D. & Wohl, R. R.',
    refYear: 1956,
    refTitle: 'Mass Communication and Para-Social Interaction',
    refCitation: 'Horton, D., & Wohl, R. R. (1956). Psychiatry, 19(3), 215–229.',
    refDoi: 'https://doi.org/10.1080/00332747.1956.11023049',
    scenarioTitleEn: 'The YouTuber Defense Force in Bengaluru',
    scenarioContextEn: 'Karthik spent 4 hours every night watching an Indian tech vlogger. When another creator published a mild critique of the vlogger’s sponsored review, Karthik felt an intense rage, spending 6 hours posting abusive comments to defend his "friend\'s" honor, missing his sister\'s birthday dinner.',
    scenarioBiasEn: 'Karthik formed an intense parasocial attachment: his brain perceived the critique of a wealthy celebrity as an existential attack on his personal inner circle.',
    scenarioOptimalEn: 'Remember that creators are commercial media enterprises, not personal friends. Reallocate emotional loyalty toward real human connections.',
    scenarioReflectionEn: 'Is there a podcaster, streamer, or celebrity whose opinions you care about more than the people you physically live with?',
    howToRecognizeEn: 'Defending an influencer online with intense emotional anger, buying products purely to support them, or dreaming about casual conversations with them.',
    whereEn: 'Twitch streaming, YouTube vlogs, lifestyle podcasts, K-pop fandoms, and political punditry.',
    misconceptionsEn: 'Myth: "Parasocial relationships only happen to lonely losers." Fact: Highly social, intelligent individuals form parasocial bonds because our human brains are naturally wired for empathy and connection.',
    limitationsEn: 'Mild parasocial bonds can be positive: learning valuable habits from an inspiring educator or finding solace in tough times is healthy as long as it does not replace real friends.',
    howToRespondEn: 'Conduct the Reality Anchor: Whenever you feel intense loyalty to a creator, remind yourself: "If I passed them on the street right now, they would not know who I am, and that is okay."',
    defensesEn: [
      { title: 'The Commercial Separation Filter', instruction: 'Remember that when creators say "I love you guys!", it is a broadcast marketing phrase designed to drive engagement, not personal affection.' },
      { title: 'The Real-World Friendship Ratio', instruction: 'Spend at least two hours in face-to-face or voice conversation with real friends for every hour spent listening to solo lifestyle podcasts.' }
    ],
    pqPromptEn: 'A young adult feels deeply devastated and weeps for days when an internet gaming streamer announces a temporary 1-month hiatus. What psychological concept best explains this intense grief?',
    pqScenarioEn: 'They have watched this streamer for 3 hours every day for three years straight from their bedroom.',
    pqExplanationEn: 'Daily exposure and perceived conversational intimacy build genuine neural attachment pathways (parasocial relationship), triggering grief upon separation.',
    pqAntidoteEn: 'Acknowledge the neural attachment, re-frame the creator as a broadcaster, and invest in reciprocal relationships.',
    pqOptionsEn: [
      { id: 'opt_a', text: 'They are suffering from a rare dissociative identity disorder.', isCorrect: false, feedback: 'Incorrect. It is a very common parasocial attachment response.' },
      { id: 'opt_b', text: 'Their brain formed an authentic parasocial attachment due to thousands of hours of simulated intimacy.', isCorrect: true, feedback: 'Correct! The brain treated the creator as an intimate tribal companion.' },
      { id: 'opt_c', text: 'The streamer cast a psychic spell over the viewer.', isCorrect: false, feedback: 'Incorrect. This is an irrational unscientific belief.' }
    ],
    reflectionPromptEn: 'How much of your discretionary emotional energy is directed at people who will never know your name?',
    titleHinglish: 'Parasocial Relationships: Influencer Ko Dost Samajhne Ka Dhokha',
    subtitleHinglish: 'Kyu hamara dimaag YouTubers aur vloggers ko apna jigri dost maan leta hai.',
    shortDescHinglish: 'One-sided digital intimacy: Jab screen par roz dekhne se dimaag samne wale ko parivaar jaisa feel karne lagta hai.',
    oneLineHinglish: 'Aap unki zindagi ki har baat jante hain, par wo aapka naam tak nahi jante.',
    summary30sHinglish: 'Donald Horton ne 1956 me Parasocial Interaction term diya tha. Hamara dimaag 1 lakh saal pehle jungle me bana tha, jahan jo chehra roz dikhta tha wo tribal dost hota tha. Dimaag screen aur real human me farq nahi kar pata, isliye roz vlogger ko dekh kar dosti jaisi feelings generate hoti hain.',
    coreConceptHinglish: 'YouTuber camera ki lens me dekhta hai jaise aapse baat kar raha ho. Earphones lagane se unki awaaz aapke dimaag ke sabse intimate space me aati hai. Result: Oxytocin release hota hai aur aap unhe apna sachha dost maan kar unki ladai me online ladne lagte hain.',
    summary60sHinglish: 'Problem tab hoti hai jab log apne real dosto ko chhod kar in vloggers ke liye time aur paisa lutate hain. Influencers ke liye "I love you guys" ek commercial dialogue hai taaki sponsorships sell ho sakein. Creators entertainer hain, aapke dost nahi.',
    howItWorksHinglish: 'Roz vlogs dekhe -> Earphones me awaaz aayi -> Dimaag ne close friend ka tag lagaya -> Unki burai sun kar gussa aaya -> Unke kehne par faltu products khareede.',
    howToRespondHinglish: 'Reality check karein: Jab bhi kisi creator par gussa ya pyaar aaye, khud ko yaad dilayein: "Agar main raste me mila to wo mujhe pehchanega bhi nahi."',
    takeawaysHinglish: [
      'Dimaag roz screen par aane wale chehre ko sachha dost samajhne ki galti karta hai',
      'Headphones aur camera angle jan-bujhkar aisi intimacy simulate karne ke liye design kiye jate hain',
      'Creators broadcast karte hain, wo personally aapse pyaar nahi karte',
      'Apna time aur jazbaat real insaano par lagao jo musibat me aapke kaam aayenge'
    ],
    pqPromptHinglish: 'Ek streamer ke 1 mahine ke break lene par ek ladka 3 din tak depressed ho kar rota raha. Research ke mutabiq yeh kya hai?',
    pqExplanationHinglish: 'Yeh parasocial attachment hai, jisme roz dekhne ki wajah se dimaag use apna close companion maan chuka tha.',
    pqOptionsHinglish: [
      { id: 'opt_a', text: 'Usse koi ajeeb bimari ho gayi hai jiska koi ilaaj nahi.', isCorrect: false, feedback: 'Galat. Yeh parasocial dynamic ka common side effect hai.' },
      { id: 'opt_b', text: 'Uski attachment ek-tarfa parasocial bond par ban chuki thi jo achanak toot gayi.', isCorrect: true, feedback: 'Sahi! Dimaag ne creator ko real-life attachment bana liya tha.' },
      { id: 'opt_c', text: 'Wo ladka streamer ka business partner tha.', isCorrect: false, feedback: 'Galat. Yeh ek-tarfa relationship tha.' }
    ],
    hiTitle: 'एकतरफा आभासी संबंध (Parasocial Interaction)',
    hiSummary: 'सोशल मीडिया इन्फ्लुएंसर्स और रचनाकारों के साथ एकतरफा घनिष्ठता और मित्रता की मनोवैज्ञानिक अनुभूति।',
    hiTakeaways: ['मस्तिष्क वीडियो और वास्तविक उपस्थिति में अंतर नहीं कर पाता', 'यह संबंध पूर्णतः एकतरफा और व्यावसायिक होता है', 'वास्तविक सामाजिक रिश्तों को प्राथमिकता दें'],
    guTitle: 'પેરાસોશિયલ સંબંધો (એકતરફી ડિજિટલ મિત્રતા)', guSummary: 'સોશિયલ મીડિયા કન્ટેન્ટ ક્રિએટર્સ સાથે એકતરફી નિકટતા અને મિત્રતાનો મનોવૈજ્ઞાનિક આભાસ.', guTakeaways: ['એકતરફી મિત્રતાથી સાવધાન', 'વાસ્તવિક મિત્રોને સમય આપો', 'ક્રિએટર્સના વ્યવસાયને સમજો'],
    mrTitle: 'पॅरासोशल नातेसंबंध (एकतर्फी डिजिटल मैत्री)', mrSummary: 'सोशल मीडियावरील व्यक्तींशी स्वतःहून घनिष्ठ आणि जवळचे नाते निर्माण झाल्याचा भास होणे.', mrTakeaways: ['एकतर्फी भावनिक गुंतवणूक टाळा', 'वास्तविक नातेसंबंधांना वेळ द्या', 'व्यावसायिक उद्देश ओळखा'],
    teTitle: 'పారాసోషల్ ఇంటరాక్షన్ (ఏకపక్ష డిజిటల్ స్నేహం)', teSummary: 'సోషల్ మీడియా సృష్టికర్తలు మరియు సెలబ్రిటీలతో నిజమైన స్నేహం ఉందనే ఏకపక్ష మానసిక భ్రమ.', teTakeaways: ['ఏకపక్ష అనుబంధాన్ని నియంత్రించండి', 'నిజమైన స్నేహాలకు ప్రాధాన్యత ఇవ్వండి', 'వాణిజ్య ఉద్దేశాలను గ్రహించండి'],
    taTitle: 'பாரಾಸோஷியல் உறவுகள் (ஒருதலைப்பட்ச டிஜிட்டல் நட்பு)', taSummary: 'சமூக வலைத்தள பிரபலங்களை தங்களின் நெருங்கிய நண்பராக நினைக்கும் ஒருதலைப்பட்ச உளவியல் மாயை.', taTakeaways: ['ஒருதலைப்பட்ச நட்பை தவிருங்கள்', 'நிஜ மனிதர்களுடன் பழகுங்கள்', 'வியாபார நோக்கத்தை புரிந்து கொள்ளுங்கள்'],
    knTitle: 'ಪ್ಯಾರಾಸೋಶಿಯಲ್ ಸಂಬಂಧಗಳು (ಏಕಮುಖ ಡಿಜಿಟಲ್ ಸ್ನೇಹ)', knSummary: 'ಸಾಮಾಜಿಕ ಮಾಧ್ಯಮದ ಸೃಷ್ಟಿಕರ್ತರೊಂದಿಗೆ ನಿಜವಾದ ಆಪ್ತತೆ ಇದೆ ಎಂದು ಭಾವಿಸುವ ಏಕಮುಖ ಮಾನಸಿಕ ಭ್ರಮೆ.', knTakeaways: ['ಏಕಮುಖ ಸಂಬಂಧದಿಂದ ಹೊರಬನ್ನಿ', 'ನಿಜವಾದ ಸ್ನೇಹಿತರಿಗೆ ಸಮಯ ನೀಡಿ', 'ವಾಣಿಜ್ಯಿಕ ತಂತ್ರಗಳನ್ನು ಅರಿಯಿರಿ'],
    mlTitle: 'പാരാസോഷ്യൽ ബന്ധങ്ങൾ (ഏകപക്ഷീയ ഡിജിറ്റൽ സൗഹൃദം)', mlSummary: 'സോഷ്യൽ മീഡിയ സെലിബ്രിറ്റികളുമായി യഥാർത്ഥ സൗഹൃദമുണ്ടെന്ന രീതിയിൽ മനസ്സ് ഉണ്ടാക്കുന്ന മിഥ്യാധാരണ.', mlTakeaways: ['ഏകപക്ഷീയ ആസക്തി കുറയ്ക്കുക', 'യഥാർത്ഥ സൗഹൃദങ്ങൾ വളർത്തുക', 'വ്യാവസായിക തന്ത്രങ്ങൾ തിരിച്ചറിയുക'],
    bnTitle: 'প্যারাসোশ্যাল মিথস্ক্রিয়া (একতরফা ডিজিটাল বন্ধুত্ব)', bnSummary: 'সোশ্যাল মিডিয়া সেলিব্রিটি ও কনটেন্ট নির্মাতাদের সাথে কাল্পনিক ও একতরফা বন্ধুত্বের মনস্তাত্ত্বিক ভ্রান্তি।', bnTakeaways: ['একতরফা মোহ থেকে দূরে থাকুন', 'বাস্তব বন্ধুত্ব গড়ে তুলুন', 'বাণিজ্যিক স্বার্থ বুঝতে শিখুন'],
    paTitle: 'ਪੈਰਾਸੋਸ਼ਲ ਰਿਸ਼ਤੇ (ਇਕਪਾਸੜ ਡਿਜੀਟਲ ਦੋਸਤੀ)', paSummary: 'ਸੋਸ਼ਲ ਮੀਡੀਆ ਇਨਫਲੂਐਂਸਰਾਂ ਨਾਲ ਅਸਲ ਦੋਸਤੀ ਹੋਣ ਦਾ ਇਕਪਾਸੜ ਅਤੇ ਝੂਠਾ ਮਨੋਵਿਗਿਆਨਕ ਅਹਿਸਾਸ।', paTakeaways: ['ਇਕਪਾਸੜ ਲਗਾਓ ਤੋਂ ਬਚੋ', 'ਅਸਲ ਜ਼ਿੰਦਗੀ ਦੇ ਰਿਸ਼ਤੇ ਸੰਭਾਲੋ', 'ਵਪਾਰਕ ਚਾਲਾਂ ਨੂੰ ਸਮਝੋ'],
    urTitle: 'پیراسوشل تعامل (یکطرفہ ڈیجیٹل دوستی)', urSummary: 'سوشل میڈیا اسٹارز اور یوٹیوبرز کے ساتھ ذاتی دوستی اور قربت کا یکطرفہ نفسیاتی احساس۔', urTakeaways: ['یکطرفہ تعلق سے ہوشیار رہیں', 'حقیقی رشتوں کو ترجیح دیں', 'تجارتی پہلو کو سمجھیں'],
    orTitle: 'ପାରାସୋସିଆଲ୍ ସମ୍ପର୍କ (ଏକତରଫା ଡିଜିଟାଲ୍ ବନ୍ଧୁତା)', orSummary: 'ସୋସିଆଲ୍ ମିଡ଼ିଆ କ୍ରିଏଟର୍ସଙ୍କ ସହ ବାସ୍ତବ ବନ୍ଧୁତା ଥିବାର ଏକତରଫା ମାନସିକ ଭ୍ରାନ୍ତି।', orTakeaways: ['ଏକତରଫା ମୋହରୁ ଦୂରେଇ ରୁହନ୍ତୁ', 'ପ୍ରକୃତ ସମ୍ପର୍କକୁ ସମୟ ଦିଅନ୍ତୁ', 'ବାଣିଜ୍ୟିକ ଉଦ୍ଦେଶ୍ୟ ବୁଝନ୍ତୁ'],
    asTitle: 'পেৰাছ’চিয়েল সম্পৰ্ক (একতৰফা ডিজিটেল বন্ধুত্ব)', asSummary: 'ছচিয়েল মিডিয়াৰ তাৰকা আৰু ক্ৰিয়েটৰসকলৰ লগত বাস্তৱ বন্ধুত্ব থকা বুলি ভবাৰ একপক্ষীয় মানসিকতা।', asTakeaways: ['একতৰফা আসক্তি পৰিহাৰ কৰক', 'বাস্তৱ সম্পৰ্কক গুৰুত্ব দিয়ক', 'ব্যৱসায়িক স্বাৰ্থ বুজি লওক']
  },

  {
    fileName: 'contextCollapse.ts',
    varName: 'context_collapse',
    id: 'context_collapse',
    categoryId: 'social_media_tech',
    slug: 'context-collapse',
    difficulty: 'intermediate',
    readTime: 5,
    sortWeight: 8,
    titleEn: 'Context Collapse: When Audiences Collide on Social Media',
    subtitleEn: 'danah boyd’s sociological insight into why posting to everyone makes communicating with anyone exhausting.',
    shortDescEn: 'The phenomenon that occurs on social media when historically distinct social contexts and audiences (family, boss, college friends, strangers) merge into a single flattened audience.',
    oneLineEn: 'Trying to speak to your grandmother, your employer, and your party friends in the exact same sentence.',
    summary30sEn: 'First articulated by media scholar danah boyd and Alice Marwick in 2011, context collapse occurs because social platforms flatten diverse social groups into a single audience. In physical reality, you speak differently to your boss than to your childhood friends. On social media, all these audiences overlap, generating anxiety and self-censorship.',
    coreConceptEn: 'Erving Goffman’s sociological theory of "impression management" established that human sanity relies on presenting nuanced, context-dependent versions of the self to different groups. Context collapse destroys boundaries: a harmless inside joke meant for college peers can be screenshotted and viewed by an HR recruiter or conservative in-law, destroying careers and marriages.',
    summary60sEn: 'To cope with context collapse, social media users either default to bland, sterilized corporate platitudes (lowest common denominator communication) or engage in "steganography" (encoded subtext that only certain friends understand). The cognitive strain of managing infinite imaginary audiences is a primary cause of creator burnout.',
    takeawaysEn: [
      'Social media flattens separate life contexts (family, career, friends) into one audience',
      'Communicating without social context creates constant fear of misunderstanding and cancellation',
      'The lowest common denominator trap forces individuals to speak in bland corporate clichés',
      'Segregating digital communication into private group chats restores authentic nuance'
    ],
    whyItHappensEn: 'Digital architecture lacks physical walls, spatial boundaries, and organic social segregation.',
    evolutionaryEn: 'Ancestral humans interacted in face-to-face circles where the physical setting (hunting field, campfire, sacred cave) automatically dictated behavioral norms.',
    howItWorksEn: 'Post created -> Distributed to 800 followers -> Mix of parents, boss, college friends, strangers -> Different audiences apply contradictory social norms -> Outrage or misunderstanding erupts.',
    visualHeadlineEn: 'Organic Physical Segregation vs. Digital Context Collapse',
    visualDescEn: 'Goffman’s social spheres collapsed onto a single flattened broadcast timeline.',
    sideALabelEn: 'Physical Social Segregation',
    sideADetailEn: 'Office: Professional dialogue; Friday night pub: Uncensored humor; Sunday dinner: Respectful family bonding.',
    sideBLabelEn: 'Social Media Context Collapse',
    sideBDetailEn: 'One public tweet read simultaneously by boss, parents, ex-partner, and 50,000 strangers looking for offense.',
    researchSummaryEn: 'Marwick & boyd (2011, New Media & Society) and boyd (2014, It’s Complicated) demonstrated how teenagers and professionals navigate the collapsing boundaries between public and private spheres online.',
    refAuthor: 'Marwick, A. E. & boyd, d.',
    refYear: 2011,
    refTitle: 'I Tweet Honestly, I Tweet Passionately: Twitter Users, Context Collapse, and the Imagined Audience',
    refCitation: 'Marwick, A. E., & boyd, d. (2011). New Media & Society, 13(1), 114–133.',
    refDoi: 'https://doi.org/10.1177/1461444810365313',
    scenarioTitleEn: 'The Sarcastic Meme Controversy in Pune',
    scenarioContextEn: 'Tanmay posted a darkly humorous meme about corporate burnout on his public Instagram story, intended for 4 close college roommates. His uncle saw it and told his father he was failing at life, while his HR director screenshotted it as evidence of poor team motivation.',
    scenarioBiasEn: 'Tanmay suffered from context collapse: he created content with a specific intimate micro-audience in mind, but published it to a collapsed public stage.',
    scenarioOptimalEn: 'Use Close Friends lists or private WhatsApp group chats for edgy humor, reserving public feeds exclusively for professional public-domain updates.',
    scenarioReflectionEn: 'Have you ever felt an instinctive dread before posting something because you remembered a specific family member or boss might see it?',
    howToRecognizeEn: 'Hesitating before posting and feeling anxious about which audience group will misinterpret your message or take offense.',
    whereEn: 'Public Twitter, LinkedIn, Instagram Stories, and family WhatsApp groups that include distant relatives.',
    misconceptionsEn: 'Myth: "If you have nothing to hide, context collapse shouldn’t bother you." Fact: Contextual nuance is the essence of human communication; taking words out of social context is inherently distortive.',
    limitationsEn: 'For public politicians and celebrities, context collapse is unavoidable and managed through dedicated public relations teams.',
    howToRespondEn: 'Balkanize your social footprint: move intimate, uncensored social interactions to end-to-end encrypted micro-channels (Signal, private groups) and treat public social media as a professional broadcast billboard.',
    defensesEn: [
      { title: 'The Close Friends Wall', instruction: 'Never post personal opinions or humor to public stories; strictly restrict sensitive posts to an audited list of under 20 trusted friends.' },
      { title: 'The Front-Page Newspaper Test', instruction: 'Before hitting post on public platforms, ask: "Would I be comfortable with this on the front page of tomorrow’s newspaper with my boss watching?"' }
    ],
    pqPromptEn: 'A professional wants to share an inside joke about medical school with three doctor friends on social media. What is the scientifically safest digital architecture?',
    pqScenarioEn: 'Their followers include patients, hospital directors, and conservative relatives.',
    pqExplanationEn: 'Public broadcasts suffer from context collapse. Direct messaging channels preserve the organic social context necessary for accurate interpretation.',
    pqAntidoteEn: 'Route the message exclusively through an encrypted private group rather than a public timeline.',
    pqOptionsEn: [
      { id: 'opt_a', text: 'Post it publicly on Twitter with a disclaimer saying "Only doctors will understand this."', isCorrect: false, feedback: 'Incorrect. Disclaimers do not prevent out-of-context screenshots and moral outrage.' },
      { id: 'opt_b', text: 'Share it in a private 4-person group chat where all members share the exact same contextual framing.', isCorrect: true, feedback: 'Correct! This avoids context collapse by preserving social boundaries.' },
      { id: 'opt_c', text: 'Post it on LinkedIn to demonstrate healthcare industry experience.', isCorrect: false, feedback: 'Incorrect. LinkedIn has severe professional reputational risks.' }
    ],
    reflectionPromptEn: 'How has the awareness of multiple watching audiences changed the way you express yourself online over the last 5 years?',
    titleHinglish: 'Context Collapse: Sabke Samne Bolne Ki Majboori',
    subtitleHinglish: 'Kyu social media par post karte waqt darr lagta hai ki rishtedaar ya boss bura na maan jayein.',
    shortDescHinglish: 'danah boyd ka sociological concept: Jab office, dosti, aur parivaar ek hi feed me aakar merge ho jate hain.',
    oneLineHinglish: 'Ek hi sentence me dadi, boss aur pub ke dosto se ek sath baat karne ki koshish.',
    summary30sHinglish: 'Real life me hum boss se alag baat karte hain, dosto se alag mazaak karte hain, aur parivaar ke samne alag sanskari bante hain. Lekin social media par yeh teeno ek hi jagah aakar khade ho jate hain. Ise kehte hain Context Collapse.',
    coreConceptHinglish: 'Jab hum Instagram ya Twitter par post karte hain, to context gayab ho jata hai. Dosto ke liye banaya gaya ek halka mazaak boss dekh le to naukri chali jati hai aur rishtedaar dekh lein to ghar me panchayat baith jati hai. Is dar se log fake ya boring corporate baatein karne lagte hain.',
    summary60sHinglish: 'Is mental pressure se bachne ka ek hi tareeqa hai: Sabke samne sab kuch bolna band karo. Close Friends list banao ya WhatsApp/Telegram ke private groups me baat karo. Public profile ko sirf ek professional billboard ki tarah treat karo.',
    howItWorksHinglish: 'Dosto ke liye mazaak post kiya -> Chacha ji aur HR ne dekh liya -> Galat matlab nikala -> Ghar aur office me behes hui -> Insaan ne post karna hi band kar diya.',
    howToRespondHinglish: 'Public vs Private boundary banao: Har baat public me mat daalo. Sensitive baatein sirf 5 logo ke private group me share karo.',
    takeawaysHinglish: [
      'Social media par sabhi rishte ek sath khade hain, jisse natural communication mushkil ho jati hai',
      'Bina context ke chota sa mazaak bhi badi misunderstanding ban sakta hai',
      'Public profile par wahi likho jo aap newspaper ke front page par chhapne par comfortable ho',
      'Asli dil ki baatein private group chats me karo, public timeline par nahi'
    ],
    pqPromptHinglish: 'Aapne college ke dosto ke liye ek sarcastic meme banaya. Usko share karne ka sabse safe tareeqa kya hoga?',
    pqExplanationHinglish: 'Context collapse se bachne ke liye meme ko sirf un dosto ke private group me share karna chahiye jo context jante hain.',
    pqOptionsHinglish: [
      { id: 'opt_a', text: 'LinkedIn par post kar dena taaki HR ko aapka sense of humor pata chale.', isCorrect: false, feedback: 'Galat. Yeh career ke liye khatarnak ho sakta hai.' },
      { id: 'opt_b', text: 'College ke dosto ke private WhatsApp group me bhejna jahan sab context samajhte hain.', isCorrect: true, feedback: 'Sahi! Yeh context collapse se bachata hai.' },
      { id: 'opt_c', text: 'Public Twitter par post karna taaki viral ho sake.', isCorrect: false, feedback: 'Galat. Isse misunderstanding aur outrage ka khatra hai.' }
    ],
    hiTitle: 'संदर्भ पतन (Context Collapse)',
    hiSummary: 'सोशल मीडिया पर विभिन्न सामाजिक संदर्भों (परिवार, सहकर्मी, मित्र) के एक साथ मिल जाने से उत्पन्न होने वाला संवाद संकट।',
    hiTakeaways: ['सोशल मीडिया विभिन्न सामाजिक संदर्भों को मिटा देता है', 'बिना संदर्भ के कही गई बात विवाद उत्पन्न करती है', 'निजी और सार्वजनिक संवाद को स्पष्ट रूप से अलग रखें'],
    guTitle: 'કન્ટેક્સ્ટ કોલેપ્સ (સંદર્ભનું વિભાજન)', guSummary: 'સોશિયલ મીડિયા પર વિવિધ સામાજિક જૂથો ભેગા થઈ જવાથી વાતચીતમાં ઊભી થતી ગેરસમજ.', guTakeaways: ['વાતચીતનો સંદર્ભ જાળવો', 'જાહેર પ્લેટફોર્મ પર સાવચેત રહો', 'ખાનગી ગ્રૂપમાં જ અંગત વાતો કરો'],
    mrTitle: 'संदर्भ संकोच (Context Collapse)', mrSummary: 'सोशल मीडियावर कुटुंब, कार्यालय आणि मित्र एकत्र आल्यामुळे संवाद साधताना होणारा गोंधळ.', mrTakeaways: ['संवादाचा योग्य संदर्भ ओळखा', 'सार्वजनिक पोस्ट करताना काळजी घ्या', 'खाजगी गटांचा वापर करा'],
    teTitle: 'సందర్భ పతనం (Context Collapse)', teSummary: 'సోషల్ మీడియాలో కుటుంబం, ఉద్యోగం మరియు స్నేహితులు ఒకే చోట చేరడం వల్ల వచ్చే సంభాషణ సంక్షోభం.', teTakeaways: ['సందర్భాన్ని కాపాడుకోండి', 'బహిరంగ వేదికలపై జాగ్రత్త వహించండి', 'వ్యక్తిగత విషయాలను పరిమితం చేయండి'],
    taTitle: 'சூழல் முறிவு (Context Collapse)', taSummary: 'சமூக வலைத்தளங்களில் குடும்பம், வேலை மற்றும் நண்பர்கள் ஒன்றிணைவதால் ஏற்படும் கருத்து மோதல்கள்.', taTakeaways: ['சூழலுக்கு ஏற்ப பேசுங்கள்', 'பொதுவெளியில் கவனமாக இருங்கள்', 'தனிப்பட்ட குழுக்களை பயன்படுத்துங்கள்'],
    knTitle: 'ಸಂದರ್ಭದ ಕುಸಿತ (Context Collapse)', knSummary: 'ಸಾಮಾಜಿಕ ಮಾಧ್ಯಮಗಳಲ್ಲಿ ಕುಟುಂಬ, ವೃತ್ತಿ ಮತ್ತು ಸ್ನೇಹಿತರು ಒಂದೇ ವೇದಿಕೆಗೆ ಬರುವುದರಿಂದಾಗುವ ಸಂವಹನ ಗೊಂದಲ.', knTakeaways: ['ಸಂದರ್ಭಕ್ಕೆ ತಕ್ಕಂತೆ ವರ್ತಿಸಿ', 'ಸಾರ್ವಜನಿಕ ಪೋಸ್ಟ್‌ಗಳಲ್ಲಿ ಜಾಗರೂಕರಾಗಿರಿ', 'ಖಾಸಗಿ ಸಂವಹನಕ್ಕೆ ಆದ್ಯತೆ ನೀಡಿ'],
    mlTitle: 'സാഹചര്യ തകർച്ച (Context Collapse)', mlSummary: 'സോഷ്യൽ മീഡിയയിൽ കുടുംബം, ജോലി, സുഹൃത്തുക്കൾ എന്നിവർ ഒന്നിച്ചു വരുമ്പോഴുണ്ടാകുന്ന ആശയവിനിമയ പ്രതിസന്ധി.', mlTakeaways: ['സാഹചര്യം തിരിച്ചറിഞ്ഞ് സംസാരിക്കുക', 'പൊതു പ്ലാറ്റ്‌ഫോമുകളിൽ ജാഗ്രത പാലിക്കുക', 'സ്വകാര്യ ഗ്രൂപ്പുകൾ ഉപയോഗിക്കുക'],
    bnTitle: 'প্রসঙ্গের অবক্ষয় (Context Collapse)', bnSummary: 'সোশ্যাল মিডিয়ায় পরিবার, সহকর্মী ও বন্ধুদের সীমানা বিলীন হয়ে যাওয়ার ফলে সৃষ্ট মানসিক অস্বস্তি।', bnTakeaways: ['কথার প্রেক্ষাপট বজায় রাখুন', 'পাবলিক পোস্টে সতর্ক থাকুন', 'ব্যক্তিগত আলাপের জন্য আলাদা গ্রুপ রাখুন'],
    paTitle: 'ਪ੍ਰਸੰਗ ਦਾ ਢਹਿਣਾ (Context Collapse)', paSummary: 'ਸੋਸ਼ਲ ਮੀਡੀਆ ਤੇ ਪਰਿਵਾਰ, ਨੌਕਰੀ ਅਤੇ ਦੋਸਤਾਂ ਦੇ ਇਕੱਠੇ ਹੋਣ ਕਾਰਨ ਗੱਲਬਾਤ ਵਿੱਚ ਪੈਦਾ ਹੋਣ ਵਾਲੀ ਉਲਝਣ।', paTakeaways: ['ਗੱਲ ਦਾ ਪ੍ਰਸੰਗ ਸਮਝੋ', 'ਖੁੱਲ੍ਹੇ ਮੰਚ ਤੇ ਸੋਚ ਕੇ ਬੋਲੋ', 'ਨਿੱਜੀ ਗੱਲਾਂ ਲਈ ਵੱਖਰੇ ਗਰੁੱਪ ਵਰਤੋ'],
    urTitle: 'سیاق و سباق کا خاتمہ (Context Collapse)', urSummary: 'سوشل میڈیا پر خاندان، دوستوں اور دفتر کے لوگوں کے ایک جگہ جمع ہونے سے پیدا ہونے والی الجھن۔', urTakeaways: ['گفتگو کے ماحول کا خیال رکھیں', 'پبلک پلیٹ فارم پر محتاط رہیں', 'نجی گروپس میں بات کریں'],
    orTitle: 'ପ୍ରସଙ୍ଗ ପତନ (Context Collapse)', orSummary: 'ସୋସିଆଲ ମିଡ଼ିଆରେ ପରିବାର, କାର୍ଯ୍ୟାଳୟ ଓ ସାଙ୍ଗମାନେ ଏକାଠି ହେବା ଦ୍ୱାରା ସୃଷ୍ଟି ହେଉଥିବା ଭ୍ରାନ୍ତି।', orTakeaways: ['ପ୍ରସଙ୍ଗର ସଠିକ୍ ବ୍ୟବହାର କରନ୍ତୁ', 'ସର୍ବସାଧାରଣରେ ସତର୍କ ରୁହନ୍ତୁ', 'ବ୍ୟକ୍ତିଗତ କଥା ବ୍ୟକ୍ତିଗତ ରଖନ୍ତୁ'],
    asTitle: 'প্ৰসংগৰ পতন (Context Collapse)', asSummary: 'ছচিয়েল মিডিয়াত পৰিয়াল, কৰ্মক্ষেত্ৰ আৰু বন্ধু-বান্ধৱী একত্ৰিত হোৱাৰ ফলত সৃষ্টি হোৱা যোগাযোগৰ জটিলতা।', asTakeaways: ['প্ৰসংগ বুজি কথা কওক', 'ৰাজহুৱা পোষ্টত সাৱধান হওক', 'ব্যক্তিগত কথাৰ বাবে সুকীয়া গ্ৰুপ ব্যৱহাৰ কৰক']
  },

  {
    fileName: 'onlineDisinhibitionEffect.ts',
    varName: 'online_disinhibition_effect',
    id: 'online_disinhibition_effect',
    categoryId: 'social_media_tech',
    slug: 'online-disinhibition-effect',
    difficulty: 'intermediate',
    readTime: 5,
    sortWeight: 9,
    titleEn: 'The Online Disinhibition Effect: Toxic and Benign Cyber-Behavior',
    subtitleEn: 'John Suler’s landmark cyberpsychology framework on why people say things online they would never say to someone\'s face.',
    shortDescEn: 'The psychological loosening of social inhibitions, behavioural constraints, and empathy when communicating through digital screens and internet channels.',
    oneLineEn: 'Why polite, civilized humans become ruthless monsters or deeply vulnerable in online comment sections.',
    summary30sEn: 'Coined by psychologist John Suler in 2004, the Online Disinhibition Effect explains how cyberspace dismantles normal psychological boundaries. Suler distinguished between toxic disinhibition (rude rants, cyberbullying, hate speech) and benign disinhibition (sharing deep personal trauma, unusual generosity, emotional honesty).',
    coreConceptEn: 'Suler identified six specific psychological drivers of online disinhibition: Dissociative Anonymity ("You don’t know who I am"), Invisibility ("You can’t see my face"), Asynchronicity ("I don’t have to deal with your immediate reaction"), Solipsistic Introjection ("It’s all in my head"), Dissociative Imagination ("It’s just a game"), and Minimizing Authority ("There are no real bosses here").',
    summary60sEn: 'In face-to-face dialogue, non-verbal feedback (facial micro-expressions, tears, posture) triggers our mirror-neuron empathy circuits, physically curbing our cruelty. Behind a glowing screen, the absence of real-time somatic feedback depersonalizes the other human into a cartoon villain, unleashing aggressive impulses that the prefrontal cortex would normally restrain.',
    takeawaysEn: [
      'Online anonymity and invisibility short-circuit the brain\'s empathy and inhibition circuits',
      'Asynchronous delays disconnect people from the visceral emotional pain their words inflict',
      'Benign disinhibition can facilitate deep therapeutic vulnerability and peer support',
      'Toxic disinhibition is fueled by viewing internet platforms as a fictional game with no consequences'
    ],
    whyItHappensEn: 'Empathy requires real-time perceptual feedback; text-based digital screens strip away facial, vocal, and postural humanizing signals.',
    evolutionaryEn: 'Humans evolved to regulate aggression through visible submissive displays, crying, and vocal tone; digital text completely deletes these pacification signals.',
    howItWorksEn: 'Individual reads opposing view -> Anonymity/Invisibility active -> Mirror neurons receive zero facial distress cues -> Moral brakes disengage -> Vitriolic comment launched -> Real-world emotional devastation caused.',
    visualHeadlineEn: 'In-Person Empathic Regulation vs. Digital Disinhibition',
    visualDescEn: 'How physical presence anchors prosocial behavior compared to digital detachment.',
    sideALabelEn: 'Face-to-Face Interaction',
    sideADetailEn: 'Sees the other person\'s flinch and tearful eyes; mirror neurons fire instantly; tone softens naturally.',
    sideBLabelEn: 'Anonymous Comment Box',
    sideBDetailEn: 'Sees only pixels on a screen; perceives target as an abstract avatar; unleashes cruel vitriol without remorse.',
    researchSummaryEn: 'Suler (2004, CyberPsychology & Behavior) and Lapidot-Lefler & Barak (2012, Computers in Human Behavior) proved that lack of eye contact is the single most powerful contributor to online flaming and hostility.',
    refAuthor: 'Suler, J.',
    refYear: 2004,
    refTitle: 'The Online Disinhibition Effect',
    refCitation: 'Suler, J. (2004). CyberPsychology & Behavior, 7(3), 321–326.',
    refDoi: 'https://doi.org/10.1089/1094931041291295',
    scenarioTitleEn: 'The LinkedIn Trolling Scandal in Gurugram',
    scenarioContextEn: 'Manish, a quiet, mild-mannered accountant in Gurugram who never raised his voice at home, created an anonymous Twitter handle. Over 6 months, he posted hundreds of vicious, threatening comments attacking female journalists, feeling an exhilarating rush of power and zero guilt until his identity was revealed.',
    scenarioBiasEn: 'Manish suffered from extreme toxic online disinhibition: dissociative anonymity and invisibility detached his moral identity from his digital avatar.',
    scenarioOptimalEn: 'Remember that an avatar is a living human being with a nervous system. Never type anything online that you wouldn\'t look someone in the eye and say in a crowded room.',
    scenarioReflectionEn: 'Have you ever written a comment or message in an argument online that made you feel slightly ashamed when you re-read it the next morning?',
    howToRecognizeEn: 'Feeling a sudden reckless urge to type aggressive, cruel, or uncharacteristically vulnerable things while looking at a screen that you would hesitate to say in person.',
    whereEn: 'Reddit threads, YouTube comments, anonymous work feedback portals (Blind), and multiplayer gaming chats.',
    misconceptionsEn: 'Myth: "Only bad, sadistic people become toxic online." Fact: The digital architecture itself structurally disinhibits ordinary, empathetic people by removing humanizing feedback loops.',
    limitationsEn: 'Benign disinhibition is heavily leveraged in tele-mental health and anonymous recovery groups (AA, trauma forums), enabling people to speak truth without social stigma.',
    howToRespondEn: 'The Eye Contact Visualization Drill: Before pressing "send" or "post" on an angry critique, visualize yourself standing 1 foot away from the person, looking them in the eye, and saying the words aloud.',
    defensesEn: [
      { title: 'The Humanizing Avatar Overlay', instruction: 'Force yourself to remember: behind every handle is an actual person who experiences heartbreak, stress, and family obligations.' },
      { title: 'The 24-Hour Draft Rule', instruction: 'Never post an angry rebuttal immediately; save it in your notes app for 24 hours. 95% of the time, you will delete it upon re-reading.' }
    ],
    pqPromptEn: 'A user writes a vicious, insulting personal attack on an anonymous forum, but is known by all their neighbors as a gentle, polite community volunteer. What explains this discrepancy?',
    pqScenarioEn: 'The user experiences no guilt when typing online, but feels immediate empathy when meeting people in physical distress.',
    pqExplanationEn: 'The Online Disinhibition Effect removes visual eye contact and real-time social feedback, preventing mirror neurons from activating moral constraints.',
    pqAntidoteEn: 'Reinstate psychological accountability by deliberately humanizing the recipient before typing.',
    pqOptionsEn: [
      { id: 'opt_a', text: 'The user has multiple personality disorder (Dissociative Identity Disorder).', isCorrect: false, feedback: 'Incorrect. This is a common sociological disinhibition phenomenon, not a dissociative psychiatric pathology.' },
      { id: 'opt_b', text: 'Anonymity, invisibility, and lack of eye contact structurally disengage the brain’s social inhibition and empathy circuits.', isCorrect: true, feedback: 'Correct! This is Suler\'s foundational Online Disinhibition framework.' },
      { id: 'opt_c', text: 'The user was possessed by an external computer virus.', isCorrect: false, feedback: 'Incorrect. Unscientific nonsense.' }
    ],
    reflectionPromptEn: 'How would your online posting style change if your real name, photograph, and workplace were displayed next to every comment you made?',
    titleHinglish: 'Online Disinhibition Effect: Screen Ke Peeche Ka Asli Chehra',
    subtitleHinglish: 'Kyu shareef se shareef insaan bhi Twitter ya YouTube comments me ghatiya baatein likhne lagta hai.',
    shortDescHinglish: 'John Suler ki cyberpsychology research: Screen ke peeche aate hi insaan ka moral control aur sharam kaise gayab ho jati hai.',
    oneLineHinglish: 'Jo baat samne bolne ki aukaat nahi hoti, wo log anonymous account se likh dete hain.',
    summary30sHinglish: '2004 me psychologist John Suler ne dekha ki internet par log do tarah se behave karte hain: Ya to wo achanak bohot zaalim aur gaali-galoch wale ban jate hain (Toxic Disinhibition), ya fir wo achanak bohot zyada emotional aur sach bolne lagte hain (Benign Disinhibition).',
    coreConceptHinglish: 'Iske 6 reasons hain: Anonymity ("Mujhe koi nahi janta"), Invisibility ("Koi mujhe dekh nahi sakta"), aur Asynchronicity ("Samne wale ka instant chehra nahi dikhta"). Real life me samne wale ka dukhi chehra dekh kar hum shant ho jate hain, screen par wo chehra nahi hota to empathy mar jati hai.',
    summary60sHinglish: 'Agar aap road par kisi se milte hain to aap tameez se baat karte hain kyuki mirror neurons active rehte hain. Par internet par dusra insaan sirf ek "DP" aur "Text" hota hai. Dimaag use insaan nahi balki game ka villain samajhta hai. Isliye troll karna asaan lagta hai.',
    howItWorksHinglish: 'Post dekha -> Gussa aaya -> Anonymous account khola -> Samne wale ka dard nahi dikha -> Ganda comment likha -> Real insaan ko mental trauma hua.',
    howToRespondHinglish: 'Eye Contact Test: Koi bhi comment post karne se pehle socho: "Kya main yahi line iske muh par sabke samne bol sakta hu?" Agar nahi, to delete kar do.',
    takeawaysHinglish: [
      'Screen ke peeche se bolna asaan hota hai kyuki dimaag ko samne wale ka dard nahi dikhta',
      'Anonymity insaan ke andar ke sabse kharab janwar ko bahar nikaal sakti hai',
      'Gusse me likha comment 24 ghante draft me rakho, subah khud hi delete karne ka mann karega',
      'Yaad rakho: Har handle ke peeche ek real insaan hai jisko chot lagti hai'
    ],
    pqPromptHinglish: 'Ek seedha-saadha ladka anonymous handle se logo ko gaaliyan deta hai, par real life me kisi par chilla bhi nahi sakta. Kyu?',
    pqExplanationHinglish: 'Online anonymity aur face-to-face eye contact ka na hona dimaag ki empathy circuits ko switch off kar deta hai.',
    pqOptionsHinglish: [
      { id: 'opt_a', text: 'Uske andar bhoot aa gaya hai.', isCorrect: false, feedback: 'Galat. Yeh cyberpsychology ka well-known dynamic hai.' },
      { id: 'opt_b', text: 'Online disinhibition ki wajah se screen ke peeche sharam aur empathy khatam ho jati hai.', isCorrect: true, feedback: 'Sahi! Yeh Suler ka Online Disinhibition Effect hai.' },
      { id: 'opt_c', text: 'Uska keyboard automatically gaaliyan type karta hai.', isCorrect: false, feedback: 'Galat. Yeh childish excuse hai.' }
    ],
    hiTitle: 'ऑनलाइन अनियंत्रण प्रभाव (Online Disinhibition)',
    hiSummary: 'डिजिटल स्क्रीन और गुमनामी के पीछे सामाजिक संकोच, सहानुभूति और नैतिक सीमाओं के समाप्त होने का मनोवैज्ञानिक अध्ययन।',
    hiTakeaways: ['गुमनामी और अदृश्यता मस्तिष्क की सहानुभूति को सुन्न कर देती है', 'स्क्रीन के पीछे इंसान वास्तविक दर्द नहीं देख पाता', 'प्रत्यक्ष संवाद की मर्यादा को डिजिटल दुनिया में भी बनाए रखें'],
    guTitle: 'ઓનલાઇન અનિયંત્રણ અસર (Online Disinhibition)', guSummary: 'ડિજિટલ સ્ક્રીન પાછળ અનામી બનીને સામાજિક મર્યાદાઓ અને સંવેદનશીલતા ભૂલી જવાની પ્રવૃત્તિ.', guTakeaways: ['અનામી હોવાનો દુરુપયોગ ન કરો', 'સ્ક્રીન પાછળ પણ માનવતા રાખો', 'સંયમપૂર્વક કમેન્ટ કરો'],
    mrTitle: 'ऑनलाइन अनिर्बंधता प्रभाव (Online Disinhibition)', mrSummary: 'डिजिटल पडद्याआड आणि अनामिकतेमुळे माणसाची सामाजिक बंधने आणि सहानुभूती नष्ट होण्याची मानसिक प्रवृत्ती.', mrTakeaways: ['अनामिकतेचा गैरवापर टाळा', 'डिजिटल जगातही संवेदनशीलता बाळगा', 'संयमाने व्यक्त व्हा'],
    teTitle: 'ఆన్‌లైన్ నిరోధరాహిత్య ప్రభావం (Online Disinhibition)', teSummary: 'స్క్రీన్ వెనుక అజ్ఞాతంగా ఉన్నప్పుడు సామాజిక సంకోచాలు మరియు సానుభూతి నశించే మనస్తత్వం.', teTakeaways: ['అజ్ఞాతత్వాన్ని దుర్వినియోగం చేయవద్దు', 'సానుభూతిని కోల్పోకండి', 'గౌరవప్రదంగా మాట్లాడండి'],
    taTitle: 'இணையதள கட்டுப்பாடின்மை விளைவு (Online Disinhibition)', taSummary: 'டிஜிட்டல் திரைகளுக்குப் பின்னால் இருக்கும் போது மனிதநேயமும் சமூகக் கட்டுப்பாடுகளும் மறையும் உளவியல்.', taTakeaways: ['முகமூடிக்கு பின்னால் ஒளியாதீர்கள்', 'மனிதநேயத்தை மறக்காதீர்கள்', 'கண்ணியமாக கருத்து தெரிவியுங்கள்'],
    knTitle: 'ಆನ್‌ಲೈನ್ ಅಸಂಯಮ ಪರಿಣಾಮ (Online Disinhibition)', knSummary: 'ಡಿಜಿಟಲ್ ಪರದೆಯ ಹಿಂದೆ ಅನಾಮಧೇಯರಾಗಿದ್ದಾಗ ಸಾಮಾಜಿಕ ಕಟ್ಟುಪಾಡುಗಳು ಮತ್ತು ಸಹಾನುಭೂತಿ ಕಳೆದುಕೊಳ್ಳುವ ವರ್ತನೆ.', knTakeaways: ['ಅನಾಮಧೇಯತೆಯನ್ನು ದುರುಪಯೋಗಪಡಿಸಿಕೊಳ್ಳಬೇಡಿ', 'ಮಾನವೀಯತೆಯನ್ನು ಮರೆಯಬೇಡಿ', 'ಸಂಯಮದಿಂದ ಪ್ರತಿಕ್ರಿಯಿಸಿ'],
    mlTitle: 'ഓൺലൈൻ നിയന്ത്രണമില്ലായ്മ (Online Disinhibition)', mlSummary: 'ഡിജിറ്റൽ സ്ക്രീനുകൾക്ക് പിന്നിൽ മറഞ്ഞിരിക്കുമ്പോൾ സഹാനുഭൂതിയും സാമൂഹിക മര്യാദകളും നഷ്ടപ്പെടുന്ന അവസ്ഥ.', mlTakeaways: ['അജ്ഞാതത്വം ദുരുപയോഗം ചെയ്യരുത്', 'മനുഷ്യത്വത്തോടെ പെരുമാറുക', 'മാന്യമായി അഭിപ്രായം പറയുക'],
    bnTitle: 'অনলাইন অসংযম প্রভাব (Online Disinhibition)', bnSummary: 'ডিজিটাল স্ক্রিনের আড়ালে ও বেনামী পরিচয়ে সহানুভূতি এবং সামাজিক দায়বদ্ধতা হারিয়ে ফেলার প্রবণতা।', bnTakeaways: ['বেনামী পরিচয়ের অপব্যবহার করবেন না', 'স্ক্রিনের পেছনেও বিবেক জাগ্রত রাখুন', 'শালীন আচরণ বজায় রাখুন'],
    paTitle: 'ਔਨਲਾਈਨ ਬੇਲਗਾਮੀ ਪ੍ਰਭਾਵ (Online Disinhibition)', paSummary: 'ਡਿਜੀਟਲ ਪਰਦੇ ਪਿੱਛੇ ਗੁਮਨਾਮ ਹੋ ਕੇ ਸਮਾਜਿਕ ਮਰਿਆਦਾਵਾਂ ਅਤੇ ਹਮਦਰਦੀ ਗੁਆ ਬੈਠਣ ਦੀ ਮਾਨਸਿਕ ਆਦਤ।', paTakeaways: ['ਗੁਮਨਾਮੀ ਦਾ ਨਾਜਾਇਜ਼ ਫਾਇਦਾ ਨਾ ਚੁੱਕੋ', 'ਸੰਵੇਦਨਸ਼ੀਲਤਾ ਬਣਾਈ ਰੱਖੋ', 'ਸਲੀਕੇ ਨਾਲ ਗੱਲ ਕਰੋ'],
    urTitle: 'آن لائن بے لگامی کا اثر (Online Disinhibition)', urSummary: 'ڈیجیٹل اسکرین اور گمنامی کی آڑ میں سماجی اخلاقیات اور ہمدردی کے ختم ہونے کا نفسیاتی رجحان۔', urTakeaways: ['گمنامی کا غلط فائدہ نہ اٹھائیں', 'انسانیت کو فراموش نہ کریں', 'شائستہ زبان استعمال کریں'],
    orTitle: 'ଅନଲାଇନ୍ ଅସଂଯମ ପ୍ରଭାବ (Online Disinhibition)', orSummary: 'ଡିଜିଟାଲ୍ ସ୍କ୍ରିନ୍ ପଛରେ ଅଜ୍ଞାତ ରହି ସାମାଜିକ ଶିଷ୍ଟାଚାର ଓ ସହାନୁଭୂତି ହରାଇବାର ମାନସିକତା।', orTakeaways: ['ଅଜ୍ଞାତତାର ଅପବ୍ୟବହାର କରନ୍ତୁ ନାହିଁ', 'ମାନବିକତା ବଜାୟ ରଖନ୍ତୁ', 'ସଂଯମତାର ସହ ମତାମତ ଦିଅନ୍ତୁ'],
    asTitle: 'অনলাইন নিয়ন্ত্ৰণহীনতাৰ প্ৰভাৱ (Online Disinhibition)', asSummary: 'ডিজিটেল পৰ্দাৰ আঁৰত বেনামী হৈ মানৱীয় সহানুভূতি আৰু সামাজিক শিষ্টাচাৰ পাহৰি যোৱাৰ প্ৰৱণতা।', asTakeaways: ['বেনামী পৰিচয়ৰ অপব্যৱহাৰ নকৰিব', 'মানৱীয়তা বজাই ৰাখক', 'সংযমেৰে মন্তব্য কৰক']
  },

  {
    fileName: 'infiniteScrollCessation.ts',
    varName: 'infinite_scroll_cessation',
    id: 'infinite_scroll_cessation',
    categoryId: 'social_media_tech',
    slug: 'infinite-scroll-and-cessation-deficit',
    difficulty: 'beginner',
    readTime: 5,
    sortWeight: 10,
    titleEn: 'Infinite Scroll & The Cessation Deficit: The Bottomless Bowl',
    subtitleEn: 'Aza Raskin’s engineering regret and Brian Wansink’s bottomless soup bowl experiment applied to digital feeds.',
    shortDescEn: 'The UI/UX architecture that eliminates natural stopping cues, causing the brain to consume media indefinitely without registering cognitive satiety.',
    oneLineEn: 'When the page never ends, your brain never gets the biological signal to stop.',
    summary30sEn: 'Invented in 2006 by engineer Aza Raskin (who later publicly apologized for its societal impact), Infinite Scroll replaced pagination with an auto-loading feed. By deleting natural "stopping cues" (like the end of a page or chapter), platforms bypass the brain\'s executive pause mechanism, trapping users in multi-hour trance states.',
    coreConceptEn: 'The psychology mirrors Brian Wansink’s famous Cornell University "Bottomless Soup Bowl" experiment: participants fed from bowls that imperceptibly refilled from beneath the table ate 73% more soup without feeling any fuller. In the digital realm, infinite scroll, auto-play videos, and pull-to-refresh create an artificial sensory loop where the brain never encounters a boundary to trigger self-reflection.',
    summary60sEn: 'Executive self-control is metabolically expensive. In the real world, physical stopping cues (the last page of a newspaper, the closing credits of a movie) externalize the decision to stop. Infinite scroll systematically strips away every external stopping cue, forcing your exhausted prefrontal cortex to generate an internal interruption while submerged in dopamine-rich stimuli.',
    takeawaysEn: [
      'Infinite scroll deletes the natural stopping cues that trigger human self-reflection',
      'The brain relies on external boundaries; without them, consumption increases 70%+',
      'The feature was engineered to maximize screen time, not user satisfaction',
      'Artificial stopping cues (app timers, greyscale mode, friction apps) restore cognitive control'
    ],
    whyItHappensEn: 'Evolutionary foraging mechanisms assume physical limits; our biology has no innate stopping reflex for an infinite, zero-friction resource.',
    evolutionaryEn: 'Ancestral foragers stopped eating or searching when the berry bush was bare or the sun set; an endless bush never existed in evolutionary history.',
    howItWorksEn: 'User reaches bottom of screen -> Script pre-loads 10 more items -> No pause or click required -> Working memory stays engrossed -> Dopamine loop continues -> 3 hours vanish unconsciously.',
    visualHeadlineEn: 'Book Pagination vs. Bottomless Algorithmic Feed',
    visualDescEn: 'How natural stopping boundaries protect executive cognitive resources.',
    sideALabelEn: 'Paginated Media (Stopping Cues)',
    sideADetailEn: 'End of Chapter 4 -> White space -> Visual pause -> Prefrontal cortex asks: "Should I keep reading or go to bed?"',
    sideBLabelEn: 'Infinite Scroll (Bottomless Feed)',
    sideBDetailEn: 'Post 49 blends into Post 50 -> Zero interruption -> Brain remains in passive hypnotic consumption loop.',
    researchSummaryEn: 'Wansink, Painter & North (2005, Obesity Research) proved bottomless eating leads to massive unconscious overconsumption; Alter (2017, Irresistible) applied this directly to digital infinite-scroll mechanics.',
    refAuthor: 'Wansink, B., Painter, J. E., & North, J.',
    refYear: 2005,
    refTitle: 'Bottomless Bowls: Why Visual Cues of Quality May Influence Intake',
    refCitation: 'Wansink, B., et al. (2005). Obesity Research, 13(1), 93–100.',
    refDoi: 'https://doi.org/10.1038/oby.2005.12',
    scenarioTitleEn: 'The Midnight Instagram Trance in Hyderabad',
    scenarioContextEn: 'Zoya opened Instagram in Hyderabad at 11:00 PM to check a message from her cousin. At 1:45 AM, she was still flicking her thumb downward, watching random wedding dance reels and street food clips, with bloodshot eyes and dry contact lenses, feeling completely numb.',
    scenarioBiasEn: 'Zoya was trapped by the cessation deficit: because Instagram never presented a stopping boundary or "End of Content" signpost, her tired brain never woke up from the auto-play trance.',
    scenarioOptimalEn: 'Install a physical stopping cue: set a daily 20-minute app timer that locks the application, or turn the smartphone display to greyscale to strip visual dopamine rewards.',
    scenarioReflectionEn: 'When was the last time you reached the "end" of an app and consciously decided you had consumed enough?',
    howToRecognizeEn: 'The zombie flick: rapidly sliding your thumb upward on a glass screen with an open mouth and unfocused eyes, unable to recall the last 5 posts you just saw.',
    whereEn: 'TikTok, Instagram Reels, YouTube Shorts, Twitter timelines, and online shopping endless grids.',
    misconceptionsEn: 'Myth: "I just lack personal willpower and self-discipline." Fact: Infinite scroll was specifically designed by behavioral scientists to defeat human willpower by removing cognitive choice-points.',
    limitationsEn: 'For brief reference searches or large photo libraries, continuous scroll is functionally convenient; the pathology is using it for entertainment discovery feeds.',
    howToRespondEn: 'Construct Artificial Friction: Delete social apps from your phone and access them only through mobile web browsers (which reload slowly and lack auto-play), or enable Greyscale Mode.',
    defensesEn: [
      { title: 'The Greyscale Disenchantment', instruction: 'Turn your phone screen to black-and-white (Greyscale). Without bright neon colors, infinite scrolling loses 60% of its hypnotic dopamine appeal.' },
      { title: 'The 1-Scroll Rule', instruction: 'Decide in advance: "I will open this app, check notifications, scroll 5 posts, and close it immediately regardless of what appears next."' }
    ],
    pqPromptEn: 'Why do people routinely watch 40 short video clips in a row on social media when they would never watch a single 40-minute movie?',
    pqScenarioEn: 'The individual planned to check their phone for 2 minutes before bed.',
    pqExplanationEn: 'The cessation deficit eliminates natural stopping points, whereas a 40-minute movie requires a deliberate conscious choice to begin and continues without micro-reward variability.',
    pqAntidoteEn: 'Create external stopping points using hard hardware timers or grayscale screen filters.',
    pqOptionsEn: [
      { id: 'opt_a', text: 'Short clips have superior cinematic and artistic value compared to movies.', isCorrect: false, feedback: 'Incorrect. The dynamic is driven by friction-free auto-play and variable reward mechanics, not art.' },
      { id: 'opt_b', text: 'The elimination of stopping cues and continuous variable micro-dopamine rewards bypass executive decision-making.', isCorrect: true, feedback: 'Correct! This is the precise psychological engine of the Cessation Deficit.' },
      { id: 'opt_c', text: 'Human brains can no longer comprehend stories longer than 60 seconds.', isCorrect: false, feedback: 'Incorrect. Attention span is context-dependent, not fundamentally destroyed.' }
    ],
    reflectionPromptEn: 'If every social media platform reintroduced a mandatory "Click here for Page 2" button, how would your daily screen time change?',
    titleHinglish: 'Infinite Scroll: Kabhi Na Khatam Hone Wali Thali',
    subtitleHinglish: 'Kyu Reels aur Shorts dekhte waqt pata hi nahi chalta ki kab 2 ghante beet gaye.',
    shortDescHinglish: 'Aza Raskin ka UI design: Stopping cues ko khatam karke dimaag ko bina ruke content consume karne par majboor karna.',
    oneLineHinglish: 'Jab page ka koi ant hi nahi hota, to dimaag ko rukne ka signal kabhi nahi milta.',
    summary30sHinglish: '2006 me Aza Raskin ne Infinite Scroll banaya tha, jiske liye unhone baad me maafi maangi. Pehle websites par page 1, page 2 hota tha, jisse dimaag ko rukne ka mauka milta tha (Stopping cue). Infinite scroll ne is rukne ke signal ko hamesha ke liye mita diya.',
    coreConceptHinglish: 'Cornell University ka ek famous experiment tha: "Bottomless Soup Bowl". Unhone ek aisi soup ki thali banayi jo table ke neeche se chupke se refill hoti rehti thi. Logo ne 73% zyada soup pi liya aur unhe pata bhi nahi chala! Reels aur Shorts wahi bottomless soup bowl hain.',
    summary60sHinglish: 'Insaan ka dimaag thakne ke baad faisla nahi le sakta. Agar movie khatam hoti hai to credits aate hain, jisse dimaag kehta hai "chalo ab so jao". Lekin Reels me ek video ke baad doosra automatically chalu ho jata hai. Dimaag ko rukne ka koi bahana nahi milta.',
    howItWorksHinglish: 'Video khatam hone se pehle doosra load hua -> Koi button nahi dabana pada -> Dimaag hypnosis me chala gaya -> Pata chala raat ke 2 baj gaye.',
    howToRespondHinglish: 'Phone ko Black & White (Greyscale) mode par daal do. Jab colorful reels feeki dikhengi, to dimaag ka dopamine spike 70% gir jayega aur phone rakhne ka mann karega.',
    takeawaysHinglish: [
      'Infinite scroll aapki kamzori nahi, balki engineers ka banaya gaya deliberate trap hai',
      'Stopping cues ke bina dimaag unconscious robot ki tarah scroll karta rehta hai',
      'Phone ko Greyscale (Black & White) karne se reels ka nasha turant toot jata hai',
      'App timers aur web browser use karna hi is endless feed ka tod hai'
    ],
    pqPromptHinglish: 'Aap 5 minute ke liye Insta kholte hain aur 1 ghante tak Reels scroll karte reh jate hain. Psychology ke mutabiq asal wajah kya hai?',
    pqExplanationHinglish: 'Stopping cue na hone ki wajah se dimaag ko rukne ka biological signal nahi milta.',
    pqOptionsHinglish: [
      { id: 'opt_a', text: 'Aapke andar will-power bilkul zero ho chuki hai.', isCorrect: false, feedback: 'Galat. Yeh design specifically will-power ko bypass karne ke liye banaya gaya hai.' },
      { id: 'opt_b', text: 'Infinite scroll ne rukne ke natural signals (Stopping cues) ko mita diya hai.', isCorrect: true, feedback: 'Sahi! Bottomless design dimaag ko trance me daal deta hai.' },
      { id: 'opt_c', text: 'Phone aapko hypnotise karne wali radiation chhod raha tha.', isCorrect: false, feedback: 'Galat. Yeh psychological engineering hai, radiation nahi.' }
    ],
    hiTitle: 'अनंत स्क्रॉल और विराम शून्यता (Infinite Scroll)',
    hiSummary: 'स्वाभाविक ठहराव और पृष्ठ सीमाओं को समाप्त करके मस्तिष्क को अंतहीन सामग्री उपभोग में फंसाने वाली डिजिटल संरचना।',
    hiTakeaways: ['अनंत स्क्रॉल स्वाभाविक विराम संकेतों को मिटा देता है', 'यह अनपेक्षित अत्यधिक उपभोग को 70% तक बढ़ा देता है', 'ग्रेस्केल मोड और स्क्रीन टाइमर प्रभावी समाधान हैं'],
    guTitle: 'અનંત સ્ક્રોલ અને વિરામનો અભાવ (Infinite Scroll)', guSummary: 'અંતહીન ફીડ દ્વારા વપરાશકર્તાઓને સતત સ્ક્રોલિંગમાં ફસાવી રાખતી ડિજિટલ યુક્તિ.', guTakeaways: ['વિરામના સંકેતો ગાયબ છે', 'સમયની બરબાદી અટકાવો', 'સ્ક્રીન ટાઇમ મર્યાદિત કરો'],
    mrTitle: 'अनंत स्क्रोल आणि थांबण्याचा अभाव (Infinite Scroll)', mrSummary: 'थांबण्याचे नैसर्गिक संकेत नष्ट करून मेंदूला सतत मोबाईल वापरण्यात अडकवून ठेवणारी रचना.', mrTakeaways: ['थांबण्याचे संकेत नष्ट झाले आहेत', 'वेळेचा अपव्यय टाळा', 'मोबाईलचा वापर मर्यादित ठेवा'],
    teTitle: 'అనంతమైన స్క్రోల్ మరియు విరామ రాహిత్యం', teSummary: 'సహజమైన విరామాలను తొలగించి వినియోగదారులను నిరంతరం స్క్రోలింగ్‌లో బంధించే డిజిటల్ వ్యూహం.', teTakeaways: ['సహజ విరామాలు లేకపోవడం ప్రమాదం', 'సమయాన్ని వృథా చేయవద్దు', 'గ్రేస్కేల్ మోడ్ ఉపయోగించండి'],
    taTitle: 'முடிவில்லா உருளல் மற்றும் நிறுத்தக் குறைபாடு (Infinite Scroll)', taSummary: 'இயற்கையான நிறுத்தங்களை அழித்து மனித மனதை தொடர்ச்சியான பயன்பாட்டில் அடிமையாக்கும் டிஜிட்டல் வடிவமைப்பு.', taTakeaways: ['இயற்கை நிறுத்தங்கள் அழிக்கப்படுகின்றன', 'நேரத்தை வீணாக்காதீர்கள்', 'திரை நேரத்தை கட்டுப்படுத்துங்கள்'],
    knTitle: 'ಅನಂತ ಸ್ಕ್ರೋಲ್ ಮತ್ತು ನಿಲುಗಡೆಯ ಕೊರತೆ', knSummary: 'ನೈಸರ್ಗಿಕ ನಿಲುಗಡೆಗಳನ್ನು ಅಳಿಸಿಹಾಕಿ ಮೆದುಳನ್ನು ನಿರಂತರ ಬಳಕೆಯಲ್ಲಿ ಸಿಲುಕಿಸುವ ಡಿಜಿಟಲ್ ತಂತ್ರಜ್ಞಾನ.', knTakeaways: ['ನೈಸರ್ಗಿಕ ನಿಲುಗಡೆಗಳಿಲ್ಲ', 'ಸಮಯ ವ್ಯರ್ಥ ಮಾಡಬೇಡಿ', 'ಗ್ರೇಸ್ಕೇಲ್ ಮೋಡ್ ಬಳಸಿ'],
    mlTitle: 'അനന്തമായ സ്ക്രോളിംഗും വിരാമമില്ലായ്മയും', mlSummary: 'സ്വാഭാവിക വിരാമങ്ങളെ ഇല്ലാതാക്കി ഉപയോക്താക്കളെ നിരന്തരം സ്ക്രീനിൽ തളച്ചിടുന്ന ഡിജിറ്റൽ രൂപകൽപ്പന.', mlTakeaways: ['വിരാമ സൂചനകൾ അപ്രത്യക്ഷമാകുന്നു', 'സമയം പാഴാക്കരുത്', 'ആപ്പ് ടൈമറുകൾ ഉപയോഗിക്കുക'],
    bnTitle: 'অনন্ত স্ক্রোল এবং বিরতিহীনতা (Infinite Scroll)', bnSummary: 'স্বাভাবিক বিরতি ও সীমানা মুছে ফেলে মানুষকে অন্তহীন স্ক্রোলিংয়ে আটকে রাখার প্রযুক্তিগত নকশা।', bnTakeaways: ['বিরতির সংকেত মুছে ফেলা হয়েছে', 'সময়ের অপচয় রোধ করুন', 'স্ক্রিন টাইম নিয়ন্ত্রণ করুন'],
    paTitle: 'ਬੇਅੰਤ ਸਕ੍ਰੋਲ ਅਤੇ ਠਹਿਰਾਅ ਦੀ ਘਾਟ (Infinite Scroll)', paSummary: 'ਕੁਦਰਤੀ ਠਹਿਰਾਅ ਨੂੰ ਖ਼ਤਮ ਕਰਕੇ ਦਿਮਾਗ ਨੂੰ ਲਗਾਤਾਰ ਮੋਬਾਈਲ ਵਰਤੋਂ ਵਿੱਚ ਉਲਝਾ ਕੇ ਰੱਖਣ ਵਾਲੀ ਚਾਲ।', paTakeaways: ['ਰੁਕਣ ਦੇ ਸੰਕੇਤ ਗਾਇਬ ਹਨ', 'ਸਮਾਂ ਬਰਬਾਦ ਨਾ ਕਰੋ', 'ਸਕ੍ਰੀਨ ਸਮਾਂ ਸੀਮਤ ਕਰੋ'],
    urTitle: 'لامحدود اسکرول اور وقفے کا فقدان (Infinite Scroll)', urSummary: 'قدرتی رکاوٹوں کو ختم کر کے صارفین کو مسلسل اسکرولنگ میں جکڑے رکھنے کا ڈیجیٹل ڈیزائن۔', urTakeaways: ['رکنے کے اشارے مٹا دیے گئے ہیں', 'وقت کا ضیاع روکیں', 'اسکرین کا وقت محدود کریں'],
    orTitle: 'ଅସୀମିତ ସ୍କ୍ରୋଲ୍ ଓ ବିରାମହୀନତା (Infinite Scroll)', orSummary: 'ସ୍ୱାଭାବିକ ବିରାମକୁ ନଷ୍ଟ କରି ବ୍ୟବହାରକାରୀଙ୍କୁ ଅନବରତ ମୋବାଇଲ୍ ବ୍ୟବହାରରେ ବାନ୍ଧି ରଖିବାର କୌଶଳ।', orTakeaways: ['ବିରାମ ସଙ୍କେତ ନାହିଁ', 'ସମୟ ନଷ୍ଟ କରନ୍ତୁ ନାହିଁ', 'ସ୍କ୍ରିନ୍ ସମୟ ସୀମିତ କରନ୍ତୁ'],
    asTitle: 'অনন্ত স্ক্ৰ’ল আৰু বিৰতিহীনতা (Infinite Scroll)', asSummary: 'স্বাভাৱিক বিৰতি নোহোৱা কৰি মানুহক অহৰহ স্ক্ৰ’লিঙত আৱদ্ধ কৰি ৰখাৰ ডিজিটেল কৌশল।', asTakeaways: ['বিৰতিৰ সংকেত নাইকিয়া কৰা হৈছে', 'সময়ৰ অপচয় ৰোধ কৰক', 'স্ক্ৰীণ টাইম নিয়ন্ত্ৰণ কৰক']
  }
];

