import * as fs from 'fs';
import * as path from 'path';
import { renderTopicFile } from './generateAllExpandedTopics';

const topicsDir = path.join(__dirname, '../src/core/mind/topics');

const ALL_TOPICS = [
  // =========================================================================
  // SOCIAL PSYCHOLOGY (Topics 6 to 20 -> 15 topics)
  // =========================================================================
  {
    fileName: 'socialLoafing.ts',
    varName: 'social_loafing',
    id: 'social_loafing',
    categoryId: 'social_psychology' as const,
    slug: 'social-loafing',
    difficulty: 'beginner' as const,
    readTime: 5,
    sortWeight: 6,
    titleEn: 'Social Loafing: The Ringelmann Effect and Free-Riding in Groups',
    subtitle: 'Why individuals exert substantially less physical and mental effort when working in a team than when working alone.',
    shortDescEn: 'The psychological tendency for individuals to expend less effort on a task when working collectively as part of a group compared to when working alone.',
    oneLineEn: 'Assuming others in the team will pull the weight, so individual output quietly drops.',
    summary30sEn: 'First discovered in rope-pulling experiments by Max Ringelmann in 1913, Social Loafing shows that as group size increases, individual effort drops dramatically. When people feel their individual contributions cannot be identified, their motivation and energy decrease because accountability is diffused across the collective.',
    coreConceptEn: 'Social loafing is driven by evaluation diffusion and perceived dispensability. In individual work, performance is 100% visible and tied to self-esteem and accountability. In a team without granular individual metrics, members experience the free-rider effect or the sucker effect (withholding effort to avoid being taken advantage of by slackers).',
    summary60sEn: 'In a 1979 landmark study by Bibb Latané and colleagues, participants were asked to shout and clap as loud as possible. When individuals believed they were shouting in a group of six, they produced only one-third of the sound output compared to shouting alone, even when blindfolded and wearing noise-canceling headphones. The drop was completely unconscious and purely psychological.',
    takeawaysEn: [
      'The Ringelmann Curve: Group performance increases at a diminishing rate as individual output siphons off',
      'The Free-Rider Instinct: When rewards are shared equally regardless of input, effort drops',
      'The Sucker Effect: High performers deliberately slow down when they notice peers slacking',
      'Granular Accountability Antidote: Make every individual\'s output measurable and publicly visible',
    ] as [string, string, string, string],
    whyItHappensEn: 'Reduced evaluation apprehension and moral dispersion. When individual contributions cannot be separated from the total pool, social pressure drops and cognitive energy is conserved.',
    evolutionaryEn: 'In ancestral foraging bands, conserving metabolic calories during shared communal tasks was advantageous as long as the group achieved the minimum baseline threshold.',
    howItWorksEn: 'Group is formed -> Individual roles are left vague -> Output is evaluated only as a collective total -> High performers carry the workload -> Low performers fade into the background -> Overall group efficiency deteriorates.',
    whereEn: 'College group projects, corporate brainstorming meetings, open-source pull requests, joint household chores, and committee governance.',
    headlineEn: 'Individual Effort vs. Group Dilution',
    sideALabelEn: 'Solo Accountability (100% Visible)',
    sideADetailEn: '"Every line of code and every deliverable is tied directly to my name; I must perform."',
    sideBLabelEn: 'Collective Group (Diffused Output)',
    sideBDetailEn: '"There are 8 of us on this project; if I don\'t finish this slide tonight, someone else will handle it."',
    researchSummaryEn: 'Latané, Williams & Harkins (1979) published "Many hands make light the work," proving that social loafing occurs across cognitive, creative, and physical tasks whenever individual contribution is unidentifiable.',
    scenarioTitleEn: 'The College Capstone Project in Pune',
    scenarioVignetteEn: 'A team of five final-year computer science students in Pune is assigned a semester-long project. Rahul and Sneha write 95% of the backend and frontend code. The other three teammates skip meetings, submit plagiarized documentation slides, and promise to "handle the final presentation." At graduation evaluation, the whole team receives an "A" grade equally, leaving Rahul and Sneha feeling exploited and burnt out.',
    scenarioBreakdownEn: 'Classic social loafing compounded by the sucker effect. The absence of individual peer-evaluated scorecards allowed three members to free-ride on the high conscientiousness of two students.',
    scenarioActionEn: 'Implement Git commit tracking and peer contribution matrices where 40% of the final score is determined by anonymous intra-team rubric ratings.',
    pqContextEn: 'An IT consultancy in Hyderabad notices that moving developers from individual solo feature branches into a shared 10-person "general backlog swarm" resulted in a 35% decrease in overall tickets completed per engineer.',
    pqPromptEn: 'Which intervention directly counteracts the core psychological driver of Social Loafing in this team?',
    pqOptA: 'Offering a collective pizza party if the entire 10-person team hits the milestone',
    pqOptB: 'Assigning explicit single-owner tickets and reviewing individual commit velocity in weekly 1-on-1s',
    pqOptC: 'Increasing the size of the team to 15 engineers to handle the ticket volume',
    pqOptD: 'Sending daily motivational emails emphasizing the importance of team spirit',
    pqCorrect: 'opt_b' as const,
    pqExplanation: 'Social loafing is dissolved when individual contributions are clearly delineated, measurable, and tied to personal accountability rather than hidden behind collective obscurity.',
    pqTakeaway: 'Visibility dissolves loafing: whenever individual input is identifiable, social loafing drops to zero.',
    authorYear: 'Latané, Williams & Harkins (1979)',
    refTitle: 'Many hands make light the work: The causes and consequences of social loafing',
    refCitation: 'Latané, B., Williams, K., & Harkins, S. (1979). Journal of Personality and Social Psychology, 37(6), 822–832.',
    doi: '10.1037/0022-3514.37.6.822',
    relatedA: { topicId: 'bystander_effect', slug: 'bystander-effect', title: 'Bystander Effect' },
    relatedB: { topicId: 'social_proof', slug: 'social-proof', title: 'Social Proof' },

    titleHinglish: 'Social Loafing: Team Me Kaam Chori Aur Free-Riding Ka Psychology',
    subtitleHinglish: 'Jab log akele kaam karte hain toh poori jaan lagate hain, par group me aate hi effort kyu kam ho jata hai?',
    shortDescHinglish: 'Group me kaam karte waqt individual mehnat ka achanak kam ho jana kyunki lagta hai ki koi aur sambhal lega.',
    oneLineHinglish: 'Bheed me chupkar aaram karna: "Baaki log toh kar hi rahe hain, mere akele se kya farak padega."',
    summary30sHinglish: '1913 me Max Ringelmann ne dekha ki rassi kheenchne ke game me akele aadmi ne jitni taqat lagayi, 8 logo ke group me har ek ki taqat aadhe se bhi kam reh gayi. Ise Social Loafing kehte hain: jab hamari akele ki mehnat track nahi hoti, toh dimaag bina bataye energy bachana shuru kar deta hai.',
    coreConceptHinglish: 'Social loafing ke do mukhya kaaran hote hain: Free-rider effect (doosro ki mehnat par credit lena) aur Sucker effect (jab hard workers dekhte hain ki baaki aaram kar rahe hain, toh wo bhi apna effort gira dete hain).',
    takeawaysHinglish: [
      'Team ka size jitna bada hoga, har insaan ka individual effort utna hi kam hoga',
      'Free-Rider Problem: Jab credit sabko barabar milta hai, toh log shortcut dhundte hain',
      'Sucker Effect: Mehanti log bhi dheere-dheere kaam karna kam kar dete hain',
      'Solution: Har bande ka kaam alag aur clearly visible hona chahiye',
    ] as [string, string, string, string],

    hiTitle: 'सामाजिक अकर्मण्यता (Social Loafing): समूह में व्यक्तिगत प्रयास की कमी',
    hiSummary: 'जब व्यक्ति किसी समूह में मिलकर काम करता है, तो वह अकेले काम करने की तुलना में काफी कम मेहनत और ऊर्जा खर्च करता है। इसे रिंगेलमैन प्रभाव कहा जाता है।',
    hiTakeaways: ['समूह में उत्तरदायित्व का बिखराव', 'व्यक्तिगत योगदान की माप आवश्यक', 'मुफ्तखोरी की प्रवृत्ति से बचाव'] as [string, string, string],
    guTitle: 'સોશિયલ લોફિંગ: જૂથમાં વ્યક્તિગત પ્રયાસોમાં ઘટાડો',
    guSummary: 'જ્યારે લોકો જૂથમાં કામ કરે છે ત્યારે વ્યક્તિગત પ્રયાસો આપમેળે ઘટી જાય છે કારણ કે જવાબદારી વહેંચાઈ જાય છે.',
    mrTitle: 'सोशल लोफिंग: समूहात काम करताना वैयक्तिक प्रयत्नांची चोरी',
    mrSummary: 'एकट्याने काम करताना जितकी मेहनत घेतली जाते, तितकी समूहात घेतली जात नाही. वैयक्तिक मोजमाप नसल्याने ही प्रवृत्ती वाढते.',
    teTitle: 'సోషల్ లోఫింగ్: సమూహంలో వ్యక్తిగత ప్రయత్నం తగ్గడం',
    teSummary: 'వ్యక్తిగతంగా కాకుండా బృందంలో పనిచేస్తున్నప్పుడు శ్రమను తగ్గించే మానసిక ప్రవృత్తి.',
    taTitle: 'சமூக சோம்பல்: குழுவில் உழைப்பைக் குறைக்கும் உளவியல்',
    taSummary: 'தனியாக உழைக்கும் போது காட்டும் தீவிரத்தை குழுவில் இருக்கும் போது மக்கள் காட்டுவதில்லை.',
    knTitle: 'ಸಾಮಾಜಿಕ ಸೋಮಾರಿತನ: ಗುಂಪಿನಲ್ಲಿ ವೈಯಕ್ತಿಕ ಶ್ರಮ ಕುಸಿಯುವ ಪ್ರವೃತ್ತಿ',
    knSummary: 'ಗುಂಪಿನಲ್ಲಿ ಕೆಲಸ ಮಾಡುವಾಗ ಪ್ರತಿಯೊಬ್ಬರ ವೈಯಕ್ತಿಕ ಪರಿಶ್ರಮ ಕಡಿಮೆಯಾಗುವ ಮಾನಸಿಕ ವಿದ್ಯಮಾನ.',
    mlTitle: 'സോഷ്യൽ ലോഫിംഗ്: കൂട്ടായ്മയിൽ അധ്വാനം കുറയ്ക്കുന്ന സ്വഭാവം',
    mlSummary: 'ഗ്രൂപ്പിൽ പ്രവർത്തിക്കുമ്പോൾ വ്യക്തിഗതമായ പരിശ്രമം കുറയുന്ന പ്രവണതയാണിത്.',
    bnTitle: 'সোশ্যাল লোফিং: দলবদ্ধ কাজে ব্যক্তিগত প্রচেষ্টার ঘাটতি',
    bnSummary: 'দলে কাজ করার সময় প্রত্যেকে নিজের সম্পূর্ণ পরিশ্রম না দিয়ে অন্যদের ওপর নির্ভর করার প্রবণতা।',
    paTitle: 'ਸੋਸ਼ਲ ਲੋਫਿੰਗ: ਸਮੂਹ ਵਿੱਚ ਨਿੱਜੀ ਮਿਹਨਤ ਘਟਾਉਣ ਦੀ ਪ੍ਰਵਿਰਤੀ',
    paSummary: 'ਇਕੱਲੇ ਕੰਮ ਕਰਨ ਦੇ ਮੁਕਾਬਲੇ ਗਰੁੱਪ ਵਿੱਚ ਵਿਅਕਤੀ ਦਾ ਯੋਗਦਾਨ ਘੱਟ ਜਾਣ ਦੀ ਮਨੋਵਿਗਿਆਨਕ ਆਦਤ।',
    urTitle: 'سوشل لوفنگ: گروہ میں انفرادی محنت کی کمی',
    urSummary: 'جب لوگ گروہ میں کام کرتے ہیں تو وہ انفرادی سطح کے مقابلے میں کم محنت اور توجہ صرف کرتے ہیں۔',
    orTitle: 'ସୋସିଆଲ୍ ଲୋଫିଂ: ଗୋଷ୍ଠୀଗତ କାର୍ଯ୍ୟରେ ବ୍ୟକ୍ତିଗତ ପରିଶ୍ରମ ହ୍ରାସ',
    orSummary: 'ଏକାକୀ କାମ କରିବା ତୁଳନାରେ ଗୋଷ୍ଠୀରେ କାମ କଲାବେଳେ ଲୋକେ କମ୍ ଶ୍ରମ ପ୍ରୟୋଗ କରିବାର ମାନସିକତା।',
    asTitle: 'ছচিয়েল লোফিং: দলীয় কামত ব্যক্তিগত পৰিশ্ৰম হ্ৰাস পোৱাৰ মানসিকতা',
    asSummary: 'দলত কাম কৰাৰ সময়ত ব্যক্তিগত দায়িত্ব এৰাই চলি কম পৰিশ্ৰম কৰাৰ মানসিক প্ৰৱণতা।',
  },

  // 7. Groupthink
  {
    fileName: 'groupthink.ts',
    varName: 'groupthink',
    id: 'groupthink',
    categoryId: 'social_psychology' as const,
    slug: 'groupthink',
    difficulty: 'intermediate' as const,
    readTime: 6,
    sortWeight: 7,
    titleEn: 'Groupthink: Why Highly Cohesive Teams Make Disastrous Decisions',
    subtitle: 'The psychological drive for harmony and consensus that suppresses dissent, ignores risks, and leads to organizational catastrophe.',
    shortDescEn: 'A mode of thinking where the desire for harmony or conformity in a group results in irrational or dysfunctional decision-making outcomes.',
    oneLineEn: 'Valuing peace in the room above the objective truth of the decision.',
    summary30sEn: 'Coined by psychologist Irving Janis in 1972, Groupthink occurs when a team prioritizes politeness, unanimity, and mutual agreement over rigorous critical evaluation. Dissenting voices self-censor out of fear of social friction, creating an artificial illusion of invulnerability that leads to catastrophic failures like corporate bankruptcies and strategic disasters.',
    coreConceptEn: 'Groupthink thrives in high-pressure, insular teams with charismatic leaders. Eight primary symptoms define it: (1) Illusion of invulnerability; (2) Collective rationalization; (3) Unquestioned belief in inherent morality; (4) Stereotyped outgroup views; (5) Direct pressure on dissenters; (6) Self-censorship; (7) Illusion of unanimity; (8) Self-appointed mindguards who shield the leader from contradictory information.',
    summary60sEn: 'Janis analyzed historical catastrophes such as the Bay of Pigs invasion and the Challenger space shuttle launch. Engineers warned that the shuttle\'s O-rings would fail in freezing temperatures, but under intense NASA launch deadline pressure, managers demanded: "Take off your engineering hat and put on your management hat." The pressure for collective consensus killed all seven astronauts.',
    takeawaysEn: [
      'Illusion of Unanimity: Silence in the room is falsely interpreted as 100% agreement',
      'Mindguards: Eager deputies who actively suppress negative data before it reaches the boss',
      'The Self-Censorship Spiral: Individuals swallow valid doubts to avoid being labeled "unsupportive"',
      'Designated Devil\'s Advocate: Formally assigning team members to attack every consensus proposal',
    ] as [string, string, string, string],
    whyItHappensEn: 'Social cohesion protection and stress reduction. Challenging a dominant group consensus triggers amygdala activation and acute fear of social ostracization.',
    evolutionaryEn: 'In ancestral tribes, maintaining united group solidarity against rival predators was often more critical for immediate survival than endless analytical deliberation.',
    howItWorksEn: 'Charismatic leader announces preferred direction -> Team members nod agreeably -> Doubter A feels uneasy but stays silent -> Doubter B sees Doubter A\'s silence and suppresses their own concern -> The plan is approved unanimously -> Catastrophe strikes.',
    whereEn: 'Corporate boardroom acquisitions, startup strategy pivots, political cabinets, medical surgical teams, and family council disputes.',
    headlineEn: 'Groupthink vs. Independent Red Teaming',
    sideALabelEn: 'Groupthink Trap',
    sideADetailEn: '"Everyone seems to agree with the CEO\'s expansion plan; raising risks now will just brand me as negative."',
    sideBLabelEn: 'Cognitively Calibrated Team',
    sideBDetailEn: '"Let\'s appoint a Red Team specifically incentivized to break this thesis before we invest capital."',
    researchSummaryEn: 'Irving Janis (1972, 1982) demonstrated that high group cohesiveness coupled with structural insulation and directive leadership consistently produces defective decision outcomes.',
    scenarioTitleEn: 'The Mumbai NBFC Lending Disaster',
    scenarioVignetteEn: 'The executive committee of a prominent non-banking financial company in Mumbai meets to approve an aggressive ₹2,000-crore commercial real estate loan. The Managing Director is visibly enthusiastic. A junior risk analyst notices that the builder has multiple shell companies and debt covenants are paper-thin. When he timidly clears his throat, a senior director snaps: "Are you questioning our biggest promoter relationship?" The analyst falls silent. The loan is approved unanimously. Eighteen months later, the builder defaults, wiping out 40% of the NBFC\'s equity.',
    scenarioBreakdownEn: 'Textbook Groupthink. Directive leadership and fear of challenging authority created an environment where silence was treated as unanimous consensus, silencing crucial empirical risk data.',
    scenarioActionEn: 'Implement anonymous written risk submissions and mandate a formal Pre-Mortem where the committee assumes default has already happened and analyzes causes.',
    pqContextEn: 'A fintech executive team in Bangalore is voting on acquiring a competitor. The CEO is passionately in favor. Every department head nods and agrees during the round-robin discussion, despite multiple private misgivings.',
    pqPromptEn: 'Which practice is most effective at preventing Groupthink from corrupting this acquisition vote?',
    pqOptA: 'Having the CEO speak first and passionately outline the vision so everyone understands the goal',
    pqOptB: 'Mandating that the CEO speaks LAST, and requiring an independent Devil\'s Advocate team to present the failure case',
    pqOptC: 'Taking a public show of hands at the very beginning of the meeting',
    pqOptD: 'Encouraging everyone to maintain a positive, cooperative, and optimistic team spirit',
    pqCorrect: 'opt_b' as const,
    pqExplanation: 'Having leadership state preferences last and formally institutionalizing dissent (Devil\'s Advocate) removes the social penalty for voicing critical concerns.',
    pqTakeaway: 'When everyone thinks alike, nobody is thinking: formal dissent protocols save teams from disaster.',
    authorYear: 'Irving L. Janis (1972)',
    refTitle: 'Victims of Groupthink: A psychological study of foreign-policy decisions and fiascoes',
    refCitation: 'Janis, I. L. (1972). Victims of Groupthink. Boston: Houghton Mifflin.',
    doi: '10.1177/002216788302300412',
    relatedA: { topicId: 'conformity_asch_effect', slug: 'conformity-asch-effect', title: 'Conformity (Asch Effect)' },
    relatedB: { topicId: 'confirmation_bias', slug: 'confirmation-bias', title: 'Confirmation Bias' },

    titleHinglish: 'Groupthink: Intelligent Log Milkar Bewakoofi Bhare Faisle Kyu Lete Hain?',
    subtitleHinglish: 'Meeting me sab ek doosre ki haan me haan milate hain, aur koi sach bolkar dushmani nahi lena chahta.',
    shortDescHinglish: 'Group me sabke sath agree karne aur ladai se bachne ki aisi aadat jo poori team ko galat faisla lene par majboor kar deti hai.',
    oneLineHinglish: 'Meeting me shanti banaye rakhne ke chakkar me sachai ko dafan kar dena.',
    summary30sHinglish: 'Irving Janis ne 1972 me Groupthink concept diya. Jab kisi team me boss bohot assertive hota hai aur log disagreement se darte hain, toh koi bhi khatra point out nahi karta. Har koi sochta hai: "Baaki sab chup hain toh shayad main hi galat hoon." Is fake unity ke chakkar me lakho karodo ke loss ho jate hain.',
    coreConceptHinglish: 'Groupthink tab hota hai jab unity aur politeness ko facts aur analysis ke upar rakh diya jata hai. Isme Mindguards hote hain jo boss tak buri khabar nahi pahunchne dete, aur log khud hi apne valid sawaalo ko pee jaate hain (Self-censorship).',
    takeawaysHinglish: [
      'Chuppi ka matlab agreement nahi hota: Log aksar dar ke maare chup rehte hain',
      'Boss ki pehle opinion aana dangerous hai: Leader ko hamesha aakhiri me bolna chahiye',
      'Devil\'s Advocate: Meeting me ek bande ka kaam officially flaws dhundna hona chahiye',
      'Anonymous Feedback: Sensitive matters par secret voting karwani chahiye',
    ] as [string, string, string, string],

    hiTitle: 'ग्रुपथिंक (Groupthink): अत्यधिक सामूहिकता से उपजे विनाशकारी निर्णय',
    hiSummary: 'जब किसी समूह में मतभेदों से बचने और सहमति बनाए रखने की तीव्र इच्छा निष्पक्ष विश्लेषण और तार्किक सोच पर हावी हो जाती है, तो बड़े पैमाने पर गलत फैसले होते हैं।',
    hiTakeaways: ['सहमति का कृत्रिम भ्रम', 'असहमति का दमन न करें', 'डेविल्स एडवोकेट की भूमिका अनिवार्य'] as [string, string, string],
    guTitle: 'ગ્રુપથિંક: જૂથની એકરૂપતામાં ખોટા નિર્ણયો લેવાની ભૂલ',
    guSummary: 'સંવાદિતા અને સહમતિ જાળવવાના દબાણમાં જ્યારે ટીમ સાચા જોખમોની અવગણના કરે છે ત્યારે વિનાશક નિર્ણયો લેવાય છે.',
    mrTitle: 'ग्रुपथिंक: समूहाच्या दबावातून होणारे चुकीचे निर्णय',
    mrSummary: 'एकमत दाखवण्याच्या नादात जेव्हा लोक खरी वस्तुस्थिती सांगणे टाळतात, तेव्हा संस्थांचे प्रचंड नुकसान होते.',
    teTitle: 'గ్రూప్‌థింక్: సమూహ సామరస్యం కోసం తప్పుడు నిర్ణయాలు తీసుకోవడం',
    teSummary: 'విబేధాలను అణచివేసి అందరితో ఏకీభవించాలనే కోరిక వినాశకరమైన ఫలితాలకు దారితీస్తుంది.',
    taTitle: 'குழுச்சிந்தனை: சமரசத்தால் ஏற்படும் தவறான முடிவுகள்',
    taSummary: 'குழுவில் உள்ள அனைவருடனும் ஒத்துப்போக வேண்டும் என்ற கட்டாயத்தில் உண்மையான இடர்களை புறக்கணிக்கும் நிலை.',
    knTitle: 'ಗ್ರೂಪ್‌ಥಿಂಕ್: ಗುಂಪಿನ ಸಾಮರಸ್ಯಕ್ಕಾಗಿ ತಪ್ಪು ನಿರ್ಧಾರಗಳನ್ನು ಕೈಗೊಳ್ಳುವುದು',
    knSummary: 'ಭಿನ್ನಾಭಿಪ್ರಾಯಗಳನ್ನು ಮರೆಮಾಚಿ ಎಲ್ಲರೂ ಒಪ್ಪಿಕೊಂಡಂತೆ ನಟಿಸುವುದರಿಂದ ದುರಂತಮಯ ಫಲಿತಾಂಶಗಳು ಉಂಟಾಗುತ್ತವೆ.',
    mlTitle: 'ഗ്രൂപ്പ്തിങ്ക്: വിയോജിപ്പുകൾ ഒതുക്കിവെച്ച് കൂട്ടത്തോടെ തെറ്റായ തീരുമാനങ്ങൾ എടുക്കൽ',
    mlSummary: 'ഗ്രൂപ്പിലെ സമാധാനം നിലനിർത്താൻ ശരിയായ സംശയങ്ങൾ പ്രകടിപ്പിക്കാതെ ഇരിക്കുന്നത് വൻ പരാജയങ്ങൾക്ക് വഴിവെക്കുന്നു.',
    bnTitle: 'গ্রুপথিংক: দলের ঐকমত্য বজায় রাখতে গিয়ে ভুল সিদ্ধান্ত নেওয়ার ফাঁদ',
    bnSummary: 'দলে বিরোধ এড়াতে গিয়ে যৌক্তিক সমালোচনা বন্ধ করে দিলে মারাত্মক বিপর্যয় ঘটে।',
    paTitle: 'ਗਰੁੱਪਥਿੰਕ: ਸਹਿਮਤੀ ਦੇ ਚੱਕਰ ਵਿੱਚ ਲਏ ਜਾਣ ਵਾਲੇ ਵਿਨਾਸ਼ਕਾਰੀ ਫੈਸਲੇ',
    paSummary: 'ਜਦੋਂ ਟੀਮ ਵਿੱਚ ਬਹਿਸ ਤੋਂ ਬਚਣ ਲਈ ਸਾਰੇ ਇੱਕੋ ਗੱਲ ਨਾਲ ਸਹਿਮਤ ਹੋ ਜਾਂਦੇ ਹਨ ਅਤੇ ਜੋਖਮਾਂ ਨੂੰ ਅਣਦੇਖਾ ਕਰ ਦਿੰਦੇ ਹਨ।',
    urTitle: 'گروپ تھنک: اتحاد کے دباؤ میں اجتماعی غلط فیصلے',
    urSummary: 'جب کسی گروہ میں ہم آہنگی برقرار رکھنے کی خواہش آزادانہ اور تنقیدی سوچ پر غالب آ جاتی ہے تو تباہ کن نتائج برآمد ہوتے ہیں۔',
    orTitle: 'ଗ୍ରୁପ୍‌ଥିଙ୍କ୍: ଗୋଷ୍ଠୀ ସହମତି ପାଇଁ ଭୁଲ୍ ନିଷ୍ପତ୍ତି ନେବାର ମନସ୍ତତ୍ତ୍ୱ',
    orSummary: 'ଦଳରେ ବିବାଦ ଏଡ଼ାଇବା ପାଇଁ ସତ୍ୟ ତଥ୍ୟକୁ ଲୁଚାଇ ରଖି ସମସ୍ତେ ସହମତ ହେବାର ଭୟଙ୍କର ପରିଣାମ।',
    asTitle: 'গ্ৰুপথিঙ্ক: দলীয় ঐক্য ৰক্ষাৰ স্বাৰ্থত ভুল সিদ্ধান্ত গ্ৰহণৰ প্ৰৱণতা',
    asSummary: 'দলত বিৰোধিতাৰ ভয়ত নিজৰ সঠিক সন্দেহ ব্যক্ত নকৰাৰ ফলত সৃষ্টি হোৱা ভুল সিদ্ধান্ত।',
  },

  // 8. Group Polarization
  {
    fileName: 'groupPolarization.ts',
    varName: 'group_polarization',
    id: 'group_polarization',
    categoryId: 'social_psychology' as const,
    slug: 'group-polarization',
    difficulty: 'intermediate' as const,
    readTime: 5,
    sortWeight: 8,
    titleEn: 'Group Polarization: The Risky Shift and Echo Chamber Extremism',
    subtitle: 'Why like-minded groups inevitably migrate toward more extreme, radicalized versions of their initial opinions after discussion.',
    shortDescEn: 'The tendency for a group to make decisions that are more extreme than the initial inclination of its members, shifting either toward greater caution or greater risk.',
    oneLineEn: 'Echo chambers do not just reinforce beliefs; they push them to radical extremes.',
    summary30sEn: 'First identified as the "risky shift" by James Stoner in 1961 and generalized by Moscovici and Zavalloni in 1969, Group Polarization proves that discussing a topic with people who agree with you doesn\'t bring moderation—it shifts everyone toward a more extreme stance. Social media feeds and political factions are natural incubators for this phenomenon.',
    coreConceptEn: 'Two complementary mechanisms drive polarization: (1) Persuasive Arguments Theory (Informational Influence): In a room of like-minded peers, you hear novel arguments supporting your preexisting view, giving you fresh justification to become more confident and extreme; (2) Social Comparison Theory (Normative Influence): Group members compete to be perceived as "true believers" or exemplary leaders of the group\'s core value, pulling the consensus outward.',
    summary60sEn: 'In a 1970 study by David Myers and George Bishop, high school students were pre-screened on racial attitudes. Moderately prejudiced students were grouped together, as were moderately unprejudiced students. After 30 minutes of discussion, the unprejudiced group became significantly more progressive, while the prejudiced group became dramatically more hostile. Unmoderated homophily naturally generates radicalism.',
    takeawaysEn: [
      'The Radicalizing Shift: Group discussion pulls members toward the extreme end of their initial shared bias',
      'The Novel Argument Surge: Hearing fresh arguments supporting your view increases overconfidence',
      'One-Upmanship Signaling: Members compete to prove they are the most loyal, virtuous member of the tribe',
      'Deliberate Depolarization: Force groups to read and summarize the strongest arguments of the opposition',
    ] as [string, string, string, string],
    whyItHappensEn: 'Information asymmetry and normative status signaling. People want to stand out positively within their peer group while hearing only one-sided evidence.',
    evolutionaryEn: 'In inter-tribal conflict, cohesive ideological zeal and decisive collective aggression increased war-band solidarity against competing tribes.',
    howItWorksEn: 'Mild initial leaning -> Deliberation with like-minded peers -> Novel supportive arguments shared -> Social signaling causes members to out-radicalize each other -> Group adopts an extreme, uncompromising stance.',
    whereEn: 'WhatsApp family groups, RWA resident societies, political rallies, cryptocurrency forum threads, and investment subreddits.',
    headlineEn: 'Individual Moderation vs. Echo Chamber Extremism',
    sideALabelEn: 'Individual Baseline (Moderate)',
    sideADetailEn: '"I think we should look into increasing apartment security fees slightly to fix the back gate."',
    sideBLabelEn: 'Post-Discussion Polarization (Extreme)',
    sideBDetailEn: '"We must ban all outside delivery workers, install biometric fences, and fine anyone who questions the policy!"',
    researchSummaryEn: 'Moscovici & Zavalloni (1969) established that French students discussing Charles de Gaulle or American policy moved to significantly more extreme consensus positions than their individual pre-test averages.',
    scenarioTitleEn: 'The Gurgaon RWA WhatsApp Escalation',
    scenarioVignetteEn: 'A high-rise apartment society in Gurgaon creates a WhatsApp group to discuss food delivery bikes parking on society lawns. Initial opinions are moderate: "Let\'s designate two parking slots near the gate." But over three days of feverish messaging, members share angry photos, complain about traffic noise, and compete to sound the most vigilant. By Sunday\'s general meeting, the group passes an aggressive resolution banning all delivery partners from entering the premises and imposing ₹5,000 fines on residents ordering groceries.',
    scenarioBreakdownEn: 'Group Polarization in full effect. Echo-chamber interaction provided a cascade of one-sided grievances, and members competed to signal uncompromising loyalty to "society safety," resulting in a hyper-extreme policy.',
    scenarioActionEn: 'Require asynchronous structured polls with neutral question framing, and mandate that both sides of an issue are represented equally before any general body vote.',
    pqContextEn: 'A retail investor Telegram channel in Mumbai dedicated to a specific small-cap green-energy stock starts out discussing whether the company\'s quarterly revenue is decent. Three weeks later, members are actively liquidating emergency savings to double down, labeling anyone who takes profits as "a traitor."',
    pqPromptEn: 'What psychological dynamic explains this rapid descent into radical financial risk-taking?',
    pqOptA: 'Social Facilitation enhancing individual mathematical accuracy',
    pqOptB: 'Group Polarization amplifying initial optimism into collective zealotry through one-sided argument exposure',
    pqOptC: 'The Ringelmann Effect reducing the total number of stock shares purchased',
    pqOptD: 'Diffusion of responsibility making individual investors indifferent to their money',
    pqCorrect: 'opt_b' as const,
    pqExplanation: 'Group polarization occurs when like-minded individuals discuss a shared belief, exposing each other to exclusively positive arguments and competitive in-group status signaling.',
    pqTakeaway: 'Homogeneous discussion radicalizes: always inject opposing empirical viewpoints to maintain calibration.',
    authorYear: 'Moscovici & Zavalloni (1969)',
    refTitle: 'The group as a polarizer of attitudes',
    refCitation: 'Moscovici, S., & Zavalloni, M. (1969). Journal of Personality and Social Psychology, 12(2), 125–135.',
    doi: '10.1037/h0027568',
    relatedA: { topicId: 'confirmation_bias', slug: 'confirmation-bias', title: 'Confirmation Bias' },
    relatedB: { topicId: 'ingroup_outgroup_bias', slug: 'ingroup-outgroup-bias', title: 'Ingroup-Outgroup Bias' },

    titleHinglish: 'Group Polarization: Echo Chamber Me Baatcheet Se Log Radical Kyu Ho Jate Hain?',
    subtitleHinglish: 'Jab ek jaisi soch wale log aapas me baat karte hain, toh unke vichaar moderate hone ke bajaye aur extreme ho jate hain.',
    shortDescHinglish: 'Group discussion ke baad sabka faisla pehle se zyada aggressive ya risky ban jana.',
    oneLineHinglish: 'Echo chamber me baatein karne se aam log bhi kattar aur extreme ban jate hain.',
    summary30sHinglish: '1961 me James Stoner ne discover kiya ki log akele me safe sochte hain, par jab ek hi vichar wale 10 log baithkar baat karte hain, toh wo bohot risky aur aggressive faisla le lete hain. Ise Group Polarization kehte hain. Social media groups aur political WhatsApp chats iska sabse bada example hain.',
    coreConceptHinglish: 'Yeh do vajah se hota hai: (1) Naye arguments milte hain jo purani baat ko aur pakka karte hain; (2) Group me sabse zyada loyal aur radical dikhne ki hod lagti hai (Social Comparison).',
    takeawaysHinglish: [
      'Echo Chamber Trap: Sirf apne jaisi soch walo se milne par vichar extreme ho jate hain',
      'One-Upmanship: Group me log ek-doosre se zyada aggressive banne ki koshish karte hain',
      'Nuance Khatam: Grey area gayab ho jata hai aur sab kuch black-and-white lagta hai',
      'Remedy: Hamesha opposite perspective wale logo ke arguments padhein aur samjhein',
    ] as [string, string, string, string],

    hiTitle: 'समूह ध्रुवीकरण (Group Polarization): चर्चा से विचारों का कट्टर होना',
    hiSummary: 'समान विचारधारा वाले लोगों के समूह में चर्चा के बाद सदस्यों के विचार अधिक चरम और आक्रामक हो जाते हैं। इसे समूह ध्रुवीकरण कहते हैं।',
    hiTakeaways: ['विचारों का अतिवाद', 'इको चैंबर का प्रभाव', 'विपरीत दृष्टिकोण सुनना अनिवार्य'] as [string, string, string],
    guTitle: 'જૂથ ધ્રુવીકરણ: ચર્ચા પછી વિચારોનું વધુ કટ્ટર બનવું',
    guSummary: 'જ્યારે સમાન વિચારધારા ધરાવતા લોકો ચર્ચા કરે છે, ત્યારે તેમના નિર્ણયો વધુ જોખમી અને આત્યંતિક બને છે.',
    mrTitle: 'गट ध्रुवीकरण: चर्चेतून विचारांचे टोकाचे स्वरूप',
    mrSummary: 'समान विचारसरणीच्या लोकांमध्ये चर्चा झाल्यावर त्यांचे मत मवाळ होण्याऐवजी अधिक तीव्र आणि आक्रमक बनते.',
    teTitle: 'సమూహ ధ్రువీకరణ: చర్చల ద్వారా ఆలోచనలు తీవ్రతరం కావడం',
    teSummary: 'ఒకే రకమైన ఆలోచనలు కలిగిన వ్యక్తులు చర్చించినప్పుడు మరింత తీవ్రమైన నిర్ణయాలు తీసుకుంటారు.',
    taTitle: 'குழு துருவமுனைப்பு: உரையாடலால் தீவிரமடையும் கருத்துகள்',
    taSummary: 'ஒத்த கருத்துடையவர்கள் குழுவாகப் பேசும்போது அவர்களின் நிலைப்பாடு மேலும் தீவிரமடைகிறது.',
    knTitle: 'ಗುಂಪು ಧ್ರುವೀಕರಣ: ಚರ್ಚೆಯ ನಂತರ ತೀವ್ರಗಾಮಿ ನಿರ್ಧಾರಗಳನ್ನು ಕೈಗೊಳ್ಳುವುದು',
    knSummary: 'ಒಂದೇ ರೀತಿಯ ಅಭಿಪ್ರಾಯವಿರುವ ಜನರು ಚರ್ಚಿಸಿದಾಗ ಅವರ ಅಭಿಪ್ರಾಯಗಳು ಮತ್ತಷ್ಟು ತೀವ್ರಗೊಳ್ಳುತ್ತವೆ.',
    mlTitle: 'ഗ്രൂപ്പ് ധ്രുവീകരണം: ചർച്ചകൾക്കൊടുവിൽ നിലപാടുകൾ തീവ്രമാകൽ',
    mlSummary: 'ഒരേ ചിന്താഗതിയുള്ള ആളുകൾ ഒരുമിച്ചു സംസാരിക്കുമ്പോൾ അഭിപ്രായങ്ങൾ കൂടുതൽ തീവ്രമായ അവസ്ഥയിലേക്ക് മാറുന്നു.',
    bnTitle: 'গ্রুপ মেরুকরণ: আলোচনার মাধ্যমে মতামতের চরমপন্থায় রূপান্তর',
    bnSummary: 'একই মতাদর্শের মানুষের মধ্যে আলোচনার পর তাদের মনোভাব আরও কট্টর ও চরম আকার ধারণ করে।',
    paTitle: 'ਗਰੁੱਪ ਪੋਲਰਾਈਜ਼ੇਸ਼ਨ: ਗੱਲਬਾਤ ਰਾਹੀਂ ਵਿਚਾਰਾਂ ਦਾ ਕੱਟੜ ਹੋਣਾ',
    paSummary: 'ਇੱਕੋ ਸੋਚ ਵਾਲੇ ਲੋਕਾਂ ਦੀ ਚਰਚਾ ਤੋਂ ਬਾਅਦ ਫੈਸਲੇ ਹੋਰ ਵੀ ਤਿੱਖੇ ਅਤੇ ਕੱਟੜਪੰਥੀ ਹੋ ਜਾਂਦੇ ਹਨ।',
    urTitle: 'گروپ پولرائزیشن: بحث و تکرار سے خیالات کا انتہا پسندی کی طرف جانا',
    urSummary: 'ہم خیال افراد جب آپس میں بحث کرتے ہیں تو ان کے فیصلے اور خیالات مزید انتہا پسندانہ ہو جاتے ہیں۔',
    orTitle: 'ଗୋଷ୍ଠୀ ଧ୍ରୁବୀକରଣ: ଆଲୋଚନା ପରେ ମତାମତ ଉଗ୍ର ହେବା',
    orSummary: 'ସମାନ ବିଚାରଧାରାର ଲୋକେ ଏକାଠି ହୋଇ ଚର୍ଚ୍ଚା କଲେ ସେମାନଙ୍କ ନିଷ୍ପତ୍ତି ଅଧିକ ଚରମ ସୀମାରେ ପହଞ୍ଚିଥାଏ।',
    asTitle: 'দলীয় মেৰুকৰণ: আলোচনাৰ জৰিয়তে মতাদৰ্শ অধিক উগ্ৰ হোৱা',
    asSummary: 'একে মতৰ মানুহ একেলগ হৈ আলোচনা কৰিলে সিদ্ধান্তসমূহ মধ্যপন্থী হোৱাৰ পৰিৱৰ্তে অধিক চৰমপন্থী হৈ পৰে।',
  },

  // 9. Cognitive Dissonance
  {
    fileName: 'cognitiveDissonance.ts',
    varName: 'cognitive_dissonance',
    id: 'cognitive_dissonance',
    categoryId: 'social_psychology' as const,
    slug: 'cognitive-dissonance',
    difficulty: 'beginner' as const,
    readTime: 6,
    sortWeight: 9,
    titleEn: 'Cognitive Dissonance: The Mental Discomfort of Contradictory Beliefs',
    subtitle: 'The psychological distress experienced when actions clash with values, driving people to rationalize mistakes rather than admit them.',
    shortDescEn: 'A state of mental tension that occurs when a person holds two contradictory beliefs, values, or ideas, or when their behavior conflicts with their core beliefs.',
    oneLineEn: 'Changing your beliefs to match your actions when you cannot change the past.',
    summary30sEn: 'Formulated by Leon Festinger in 1957, Cognitive Dissonance is the sharp emotional irritation that occurs when you do something that violates your view of yourself as smart, ethical, or rational. Because humans cannot rewrite history, the brain frantically rewrites its beliefs, memories, and attitudes to justify what just happened.',
    coreConceptEn: 'When behavior clashes with belief (e.g., "I value honesty" vs. "I just lied to my client"), a high-arousal negative affective state is triggered in the anterior insula and anterior cingulate cortex. To escape this stress, people have three choices: (1) Change behavior (difficult); (2) Acquire new information (rare); (3) Rationalize and trivialize the contradiction (effortless and common).',
    summary60sEn: 'In Festinger & Carlsmith\'s famous 1959 experiment, students performed a mind-numbing task turning wooden pegs for an hour. Afterwards, they were paid either $1 or $20 to tell the next participant the task was thrilling. Students paid $20 felt no dissonance ("I did it for the money"). But students paid only $1 experienced severe dissonance ("I wouldn\'t lie for a mere dollar, so the task must have actually been quite fascinating!"). They unconsciously altered their genuine attitude.',
    takeawaysEn: [
      'The Rationalization Engine: Humans are not rational animals; we are rationalizing animals',
      'Effort Justification: The more pain, time, or hazing an initiation requires, the more we value the club',
      'Post-Decision Spreading: Immediately after buying a car or house, we fiercely praise our choice and mock alternatives',
      'Humility Antidote: Treat dissonance as a dashboard warning light; say: "My ego is hurt because I made a mistake"',
    ] as [string, string, string, string],
    whyItHappensEn: 'Self-integrity preservation. Humans have a fundamental psychological need to view themselves as coherent, competent, and morally upright.',
    evolutionaryEn: 'A fractured sense of internal agency leads to behavioral hesitation. Resolving dissonance quickly allowed ancestral humans to act decisively without being paralyzed by self-doubt.',
    howItWorksEn: 'Action violates core value -> Acute emotional dissonance felt -> Ego seeks psychological comfort -> Brain invents a post-hoc rationalization -> Belief shifts -> Action feels justified.',
    whereEn: 'Smoking while knowing the health risks, staying in toxic relationships, defending bad financial investments, religious cults after failed prophecies, and political party loyalty.',
    headlineEn: 'Admitting a Flaw vs. Cognitive Rationalization',
    sideALabelEn: 'Calibrated Self-Correction',
    sideADetailEn: '"I spent ₹50,000 on an impulse gadget that I do not need. I made an emotional mistake; I will return it."',
    sideBLabelEn: 'Dissonance Rationalization',
    sideBDetailEn: '"Actually, this luxury watch is an investment for my personal brand that will boost my networking income."',
    researchSummaryEn: 'Festinger & Carlsmith (1959) demonstrated that insufficient external justification forces individuals to internally shift their genuine beliefs to resolve psychological inconsistency.',
    scenarioTitleEn: 'The Delhi Green Activist\'s Diesel SUV',
    scenarioVignetteEn: 'Arjun is a prominent corporate sustainability manager in Delhi who gives keynote talks on air pollution and decarbonization. For his 40th birthday, he purchases a massive 3.0-liter diesel SUV to impress his extended family. When his colleagues express surprise, Arjun\'s face flushes. Instead of admitting he wanted the luxury status symbol, he vigorously argues: "Actually, modern clean-diesel engines produce less lifetime carbon than lithium battery manufacturing, so my purchase is technically more ecological." He spends the next month sharing fringe articles debunking EV batteries.',
    scenarioBreakdownEn: 'Classic cognitive dissonance. The conflict between his identity ("Green Climate Champion") and his action (driving a diesel monster) created severe anxiety. Rather than admitting vanity, his brain rationalized the contradiction by attacking EVs.',
    scenarioActionEn: 'Recognize the uncomfortable emotional flush as cognitive dissonance. Separate ego from behavior by acknowledging: "I wanted luxury status; it contradicts my environmental ideals. I will not pretend it is green."',
    pqContextEn: 'A high-performing software architect invests ₹10 lakhs into a high-risk crypto altcoin token. Two weeks later, the token crashes 80% following a smart-contract hack.',
    pqPromptEn: 'Which behavior indicates that the architect is trapped in severe Cognitive Dissonance rather than rational Bayesian updating?',
    pqOptA: 'Auditing the hack post-mortem report and selling the remaining balance at a loss',
    pqOptB: 'Publicly posting that "the crash is a blessing in disguise because it flushes out paper hands, proving the technology is revolutionary"',
    pqOptC: 'Updating his portfolio risk-management allocation rules to prevent concentrated altcoin exposure in the future',
    pqOptD: 'Reflecting on his lack of technical due diligence and consulting an independent financial advisor',
    pqCorrect: 'opt_b' as const,
    pqExplanation: 'Severe cognitive dissonance triggers defensive rationalization where an objectively disastrous failure is reframed as a secret victory or brilliant long-term test.',
    pqTakeaway: 'When belief and behavior collide, our minds usually bend the belief: learn to sit with the discomfort of admitting an error.',
    authorYear: 'Festinger & Carlsmith (1959)',
    refTitle: 'Cognitive consequences of forced compliance',
    refCitation: 'Festinger, L., & Carlsmith, J. M. (1959). Journal of Abnormal and Social Psychology, 58(2), 203–210.',
    doi: '10.1037/h0041593',
    relatedA: { topicId: 'confirmation_bias', slug: 'confirmation-bias', title: 'Confirmation Bias' },
    relatedB: { topicId: 'self_serving_bias', slug: 'self-serving-bias', title: 'Self-Serving Bias' },

    titleHinglish: 'Cognitive Dissonance: Jab Dimaag Galti Maanne Ke Bajaye Bahane Banata Hai',
    subtitleHinglish: 'Apne hi vichaaro ke ult kaam karke dimaag me jo bechaini hoti hai, use chupane ke liye hum jhooth bolte hain.',
    shortDescHinglish: 'Jab hamara action hamare values se match nahi karta, toh hum sharminda hone ke bajaye illogical bahane banate hain.',
    oneLineHinglish: 'Galti qubool karne ke bajaye apne dimaag ko convince karna ki "jo hua achhe ke liye hua."',
    summary30sHinglish: '1957 me Leon Festinger ne Cognitive Dissonance discover kiya. Jab aap koi aisa kaam karte hain jo aapke principles ke khilaf hai (jaise cigarette peena jabki aapko pata hai cancer hota hai), toh andar ek ajeeb bechaini hoti hai. Us bechaini ko mitane ke liye dimaag sachai badal leta hai: "Mere dada ji bhi 90 saal tak peete the, kuch nahi hota."',
    coreConceptHinglish: 'Insaan rational nahi hota, balki "rationalizing" animal hota hai. Jab humse koi blunder hota hai, toh hum use admit karne ke bajaye aisi kahani bana lete hain jisse hume khud ki nazro me bura na lage.',
    takeawaysHinglish: [
      'Galti accept karna ego ke liye dardnaak hota hai, isliye dimaag bahane dhundta hai',
      'Effort Justification: Jis cheez me jitna dard aur paisa lagta hai, hum use utna hi mahan maante hain',
      'Post-Purchase Rationalization: Mehengi bekaar cheez khareedne ke baad log uski tareef karte hain',
      'Antidote: Jab andar ghabrahat ho, toh maano: "Mujhse galti hui hai, main perfect nahi hoon."',
    ] as [string, string, string, string],

    hiTitle: 'संज्ञानात्मक विसंवाद (Cognitive Dissonance): परस्पर विरोधी विचारों का मानसिक तनाव',
    hiSummary: 'जब किसी व्यक्ति के कार्य उसके सिद्धांतों या मूल्यों के विपरीत होते हैं, तो वह तीव्र मानसिक असहजता महसूस करता है। इस तनाव से बचने के लिए लोग तर्कहीन बहाने बनाते हैं।',
    hiTakeaways: ['व्यवहार और विचार का टकराव', 'गलती न मानने की प्रवृत्ति', 'आत्म-निरीक्षण और विनम्रता आवश्यक'] as [string, string, string],
    guTitle: 'કોગ્નિટિવ ડિસોનન્સ: વિરોધાભાસી વિચારો વચ્ચેનો માનસિક તણાવ',
    guSummary: 'જ્યારે આપણું વર્તન આપણા મૂલ્યો સાથે મેળ ખાતું નથી, ત્યારે મગજ પોતાની ભૂલ સ્વીકારવાને બદલે બહાના શોધે છે.',
    mrTitle: 'कॉग्निटिव्ह डिसोनन्स: परस्परविरोधी विचारांमधील मानसिक अस्वस्थता',
    mrSummary: 'जेव्हा आपली कृती आपल्या तत्वांच्या विरुद्ध असते, तेव्हा होणारा मानसिक ताण कमी करण्यासाठी लोक स्वतःचीच दिशाभूल करतात.',
    teTitle: 'కాగ్నిటివ్ డిస్సొనెన్స్: పరస్పర విరుద్ధ ఆలోచనల వల్ల కలిగే మానసిక అసౌకర్యం',
    teSummary: 'వ్యక్తి ప్రవర్తన వారి నమ్మకాలకు విరుద్ధంగా ఉన్నప్పుడు కలిగే అంతర్గత ఒత్తిడిని సమర్థించుకునే ప్రవృత్తి.',
    taTitle: 'அறிவாற்றல் முரண்பாடு: முரண்பட்ட கருத்துகளால் ஏற்படும் மன அழுத்தம்',
    taSummary: 'நமது செயல்கள் நமது நம்பிக்கைகளுக்கு முரணாக இருக்கும் போது ஏற்படும் அசௌகரியத்தை மறைக்க காரணங்களை அடுக்கும் உளவியல்.',
    knTitle: 'ಕಾಗ್ನಿಟಿವ್ ಡಿಸೋನೆನ್ಸ್: ಪರಸ್ಪರ ವಿರುದ್ಧ ಆಲೋಚನೆಗಳಿಂದ ಉಂಟಾಗುವ ಮಾನಸಿಕ ಅಸ್ವಸ್ಥತೆ',
    knSummary: 'ತಮ್ಮ ನಡವಳಿಕೆ ತಮ್ಮ ಸಿದ್ಧಾಂತಕ್ಕೆ ವಿರುದ್ಧವಾದಾಗ ತಪ್ಪನ್ನು ಒಪ್ಪಿಕೊಳ್ಳದೆ ಸಮರ್ಥಿಸಿಕೊಳ್ಳುವ ಮಾನಸಿಕ ತುಮುಲ.',
    mlTitle: 'കോഗ്നിറ്റീവ് ഡിസ്സൊണൻസ്: വിരുദ്ധ ചിന്തകൾ ഉണ്ടാക്കുന്ന മാനസിക സംഘർഷം',
    mlSummary: 'നമ്മുടെ പ്രവൃത്തികൾ നമ്മുടെ മൂല്യങ്ങൾക്ക് വിരുദ്ധമാകുമ്പോൾ ഉണ്ടാകുന്ന മാനസിക ബുദ്ധിമുട്ട് ഒഴിവാക്കാൻ സ്വയം ന്യായീകരിക്കുന്ന അവസ്ഥ.',
    bnTitle: 'কগনিটিভ ডিসোনেন্স: পরস্পরবিরোধী চিন্তাভাবনার মানসিক অস্বস্তি',
    bnSummary: 'নিজের কাজের সাথে বিশ্বাসের অমিল হলে ভুল স্বীকার না করে অযৌক্তিক সাফাই দেওয়ার মানসিক প্রবণতা।',
    paTitle: 'ਕਾਗਨੀਟਿਵ ਡਿਸੋਨੈਂਸ: ਵਿਰੋਧੀ ਵਿਚਾਰਾਂ ਦਾ ਮਾਨਸਿਕ ਤਣਾਅ',
    paSummary: 'ਜਦੋਂ ਤੁਹਾਡੀ ਕਰਨੀ ਤੁਹਾਡੇ ਸਿਧਾਂਤਾਂ ਦੇ ਉਲਟ ਹੁੰਦੀ ਹੈ, ਤਾਂ ਗਲਤੀ ਮੰਨਣ ਦੀ ਬਜਾਏ ਝੂਠੇ ਬਹਾਨੇ ਬਣਾਉਣ ਦੀ ਮਨੋਵਿਗਿਆਨਕ ਸਥਿਤੀ।',
    urTitle: 'علمی عدم مطابقت: متضاد خیالات کی وجہ سے پیدا ہونے والی ذہنی الجھن',
    urSummary: 'جب انسان کا عمل اس کے نظریات کے خلاف ہوتا ہے تو وہ اپنی غلطی تسلیم کرنے کے بجائے بے بنیاد تاویلیں تراشتا ہے۔',
    orTitle: 'କଗ୍ନିଟିଭ୍ ଡିସୋନାନ୍ସ: ପରସ୍ପର ବିରୋଧୀ ଚିନ୍ତାଧାରାର ମାନସିକ ଅସ୍ଥିରତା',
    orSummary: 'ଯେତେବେଳେ ନିଜର କାର୍ଯ୍ୟ ନିଜର ଆଦର୍ଶ ସହିତ ମେଳ ଖାଏ ନାହିଁ, ସେତେବେଳେ ଭୁଲ୍ ସ୍ୱୀକାର ନ କରି ଯୁକ୍ତି ବାଢ଼ିବାର ମାନସିକତା।',
    asTitle: 'কগনিটিভ ডিচনেঞ্চ: পৰস্পৰ বিৰোধী চিন্তাৰ ফলত হোৱা মানসিক অস্বস্তি',
    asSummary: 'যেতিয়া কাৰ্য আৰু বিশ্বাসৰ মাজত সংঘাত হয়, ভুল স্বীকাৰ নকৰি অদ্ভুত যুক্তিৰে নিজকে সান্ত্বনা দিয়াৰ প্ৰক্ৰিয়া।',
  },

  // 10. Social Facilitation
  {
    fileName: 'socialFacilitation.ts',
    varName: 'social_facilitation',
    id: 'social_facilitation',
    categoryId: 'social_psychology' as const,
    slug: 'social-facilitation',
    difficulty: 'intermediate' as const,
    readTime: 5,
    sortWeight: 10,
    titleEn: 'Social Facilitation & Inhibition: Performance Under the Gaze of Others',
    subtitle: 'Why having an audience supercharges simple, well-rehearsed tasks but cripples novel, complex problem-solving.',
    shortDescEn: 'The tendency for the presence of others to improve a person\'s performance on an easy or well-learned task, but impair performance on a difficult or unmastered task.',
    oneLineEn: 'Audiences energize your habits, but paralyze your thinking.',
    summary30sEn: 'First observed in cyclists by Norman Triplett in 1898 and unlocked theoretically by Robert Zajonc in 1965, Social Facilitation demonstrates that the mere presence of other people triggers physiological arousal. This arousal sharpens "dominant responses": if a skill is pure muscle memory (running, typing), you excel; if a skill requires creative calculation (coding, chess), you freeze.',
    coreConceptEn: 'Zajonc\'s Drive Theory integrates social presence with Yerkes-Dodson arousal laws: (1) Mere presence triggers autonomic nervous system alertness; (2) Heightened drive enhances the likelihood of the dominant response; (3) For simple, overlearned tasks, the dominant response is correct (Facilitation); (4) For complex, unfamiliar tasks, the dominant response is error-prone trial-and-error (Social Inhibition).',
    summary60sEn: 'Zajonc famously tested this even in cockroaches. When running through a simple straight-line tube to escape light, roaches ran faster when other roaches were watching from transparent plastic "bleachers." But when running through a complex multi-turn maze, the audience of roaches caused the runner to make significantly more mistakes and slow down. The effect is hardwired into animal physiology.',
    takeawaysEn: [
      'The Audience Multiplier: Spectators boost motor habits and stamina, but crush complex working memory',
      'Evaluation Apprehension: Performance anxiety spikes when observers are seen as judgmental evaluators',
      'The Open-Office Trap: Open-plan offices facilitate routine busywork while severely degrading deep architecture work',
      'Solitude for Synthesis: Master complex algorithms and difficult writing alone; perform public speeches with an audience',
    ] as [string, string, string, string],
    whyItHappensEn: 'Involuntary autonomic arousal. The presence of conspecifics activates evolutionary threat/opportunity appraisal systems, narrowing attentional focus.',
    evolutionaryEn: 'In ancestral environments, having other eyes upon you meant you were either being evaluated by dominant group members or stalked by competitors, demanding high physical alertness.',
    howItWorksEn: 'Observers present -> Heart rate and cortisol increase -> Attentional spotlight narrows -> Habitual dominant responses fire automatically -> Simple tasks speed up -> Complex creative tasks suffer cognitive bottlenecks.',
    whereEn: 'Public speaking, athletic sprints, coding interviews under live screen-sharing, open-plan office desk environments, and musical recitals.',
    headlineEn: 'Simple Motor Tasks vs. Complex Creative Tasks',
    sideALabelEn: 'Well-Learned Habit (Facilitated)',
    sideADetailEn: '"A marathon runner running 10% faster because thousands of cheering fans line the Mumbai streets."',
    sideBLabelEn: 'Novel Complex Synthesis (Inhibited)',
    sideBDetailEn: '"A software engineer choking on a novel dynamic-programming problem while three interviewers stare at his cursor."',
    researchSummaryEn: 'Robert Zajonc (1965) resolved decades of conflicting experimental literature by formulating Drive Theory: presence enhances dominant responses and impairs subordinate responses.',
    scenarioTitleEn: 'The Live Screen-Share Coding Interview in Bengaluru',
    scenarioVignetteEn: 'Kavita is a senior software engineer in Bengaluru who writes flawless distributed systems code in private. During an interview for a top tech firm, two senior staff engineers watch her screen live over Zoom, saying "Talk through your thoughts in real time." Faced with a graph-traversal problem she has never seen, Kavita\'s heart pounds, her hands shake, and she cannot even remember basic Python dictionary syntax. Later that evening alone in her room, she solves the exact same problem in 12 minutes.',
    scenarioBreakdownEn: 'Severe Social Inhibition. The complex novel task required extensive working memory, which was throttled by the intense physiological arousal of having two evaluators staring at her screen.',
    scenarioActionEn: 'De-escalate arousal during complex synthesis: take 2 minutes of silent scratchpad thinking without talking, or request take-home asynchronous assessments.',
    pqContextEn: 'A tech startup in Gurgaon transitions its software developers and data scientists from private quiet booths into a bustling open-plan bench layout to "improve creative energy."',
    pqPromptEn: 'Based on Zajonc\'s Social Facilitation Theory, what will be the empirical outcome of this office reorganization?',
    pqOptA: 'Engineers will solve novel machine-learning mathematical architectures significantly faster',
    pqOptB: 'Routine administrative tasks (replying to emails, ticketing) will speed up, while deep novel architectural problem-solving will decline',
    pqOptC: 'Both routine and complex creative tasks will improve equally across all employees',
    pqOptD: 'Social loafing will completely disappear because everyone can see each other\'s monitors',
    pqCorrect: 'opt_b' as const,
    pqExplanation: 'Social presence facilitates overlearned, routine tasks (emails, tickets) but creates cognitive interference that inhibits novel, high-load cognitive synthesis.',
    pqTakeaway: 'Work alone to think; work together to execute: match the task complexity to the social setting.',
    authorYear: 'Robert B. Zajonc (1965)',
    refTitle: 'Social facilitation: A solution is suggested for an old unsolved social psychological problem',
    refCitation: 'Zajonc, R. B. (1965). Science, 149(3681), 269–274.',
    doi: '10.1126/science.149.3681.269',
    relatedA: { topicId: 'social_loafing', slug: 'social-loafing', title: 'Social Loafing' },
    relatedB: { topicId: 'spotlight_effect', slug: 'spotlight-effect', title: 'The Spotlight Effect' },

    titleHinglish: 'Social Facilitation: Doosro Ke Saamne Performance Achhi Ya Kharab Kyu Hoti Hai?',
    subtitleHinglish: 'Aasaan kaam logo ke saamne tez ho jata hai, par mushkil kaam me dimaag kyu freeze ho jata hai?',
    shortDescHinglish: 'Bheed ki presence me aasaan kaam behtar hona par naye aur mushkil kaam me dimaag ka blank ho jana.',
    oneLineHinglish: 'Bheed aadat ko taqat deti hai, par nayi soch ko paralyze kar deti hai.',
    summary30sHinglish: '1965 me Robert Zajonc ne prove kiya ki jab log hume dekh rahe hote hain, toh hamare sharir me adrenaline aur heartbeat badh jati hai. Agar kaam aasan hai ya aapki aadat ban chuka hai (jaise cycling, gyming), toh aap bheed ke saamne kamaal karte hain. Par agar kaam mushkil hai (jaise live coding interview), toh dimaag freeze ho jata hai.',
    coreConceptHinglish: 'Ise Zajonc Drive Theory kehte hain. Arousal hamare "dominant response" (purani aadato) ko trigger karta hai. Simple tasks me aadat sahi hoti hai, isliye performance badhti hai. Complex tasks me fresh thinking chahiye hoti hai, jo bheed ke dar se ruk jati hai.',
    takeawaysHinglish: [
      'Audience Effect: Routine kaam bheed me fast hota hai, creative kaam slow',
      'Screen-Share Anxiety: Live coding me dimaag ka blank hona ek natural physiological response hai',
      'Open Office Reality: Open office me log busy dikhte hain, par gehra kaam nahi kar paate',
      'Strategy: Mushkil coding aur study akele me karein; speech aur performance bheed me',
    ] as [string, string, string, string],

    hiTitle: 'सामाजिक सुगमीकरण एवं अवरोध (Social Facilitation): दर्शकों की उपस्थिति का प्रदर्शन पर प्रभाव',
    hiSummary: 'दूसरों की उपस्थिति सरल या अभ्यस्त कार्यों में प्रदर्शन को सुधारती है, लेकिन जटिल या नए बौद्धिक कार्यों में बाधा उत्पन्न करती है। इसे जायॉन्क का ड्राइव सिद्धांत कहते हैं।',
    hiTakeaways: ['सरल कार्यों में सुगमीकरण', 'जटिल चिंतन में अवरोध', 'गहन कार्य के लिए एकांत अनिवार्य'] as [string, string, string],
    guTitle: 'સોશિયલ ફેસિલિટેશન: લોકોની હાજરીમાં કામગીરી પર પડતો પ્રભાવ',
    guSummary: 'સરળ કામ લોકોની સામે ઝડપી બને છે, પરંતુ નવા અને જટિલ કાર્યોમાં લોકોનું ધ્યાન ભટકે છે અને કાર્યક્ષમતા ઘટે છે.',
    mrTitle: 'सोशल फॅसिलिटेशन: इतरांच्या उपस्थितीचा कामावर होणारा परिणाम',
    mrSummary: 'सोपी कामे लोकांसमोर उत्तम होतात, पण गुंतागुंतीच्या बौद्धिक कामांमध्ये लोकांची उपस्थिती अडथळा ठरते.',
    teTitle: 'సోషల్ ఫెసిలిటేషన్: ఇతరుల సమక్షంలో పనితీరు మారే విధానం',
    teSummary: 'సులభమైన పనులు నలుగురిలో వేగంగా జరుగుతాయి, కానీ సంక్లిష్టమైన విశ్లేషణ పనులకు ఏకాంతం అవసరం.',
    taTitle: 'சமூக வசதிப்பாடு (Social Facilitation): பிறர் முன்னிலையில் வெளிப்படும் செயல்திறன்',
    taSummary: 'பழகிய எளிய பணிகளை பிறர் பார்க்கும்போது விரைவாகச் செய்வோம், ஆனால் சிக்கலான பணிகளில் தயக்கம் ஏற்படும்.',
    knTitle: 'ಸಾಮಾಜಿಕ ಸುಗಮೀಕರಣ: ಇತರರ ಸಮ್ಮುಖದಲ್ಲಿ ಕಾರ್ಯಕ್ಷಮತೆ ಬದಲಾಗುವ ವಿಧಾನ',
    knSummary: 'ಸುಲಭವಾದ ಅಭ್ಯಾಸದ ಕೆಲಸಗಳು ಜನರ ಮುಂದೆ ಉತ್ತಮಗೊಳ್ಳುತ್ತವೆ, ಆದರೆ ಹೊಸ ಸಂಕೀರ್ಣ ಕೆಲಸಗಳು ಕುಂಠಿತಗೊಳ್ಳುತ್ತವೆ.',
    mlTitle: 'സോഷ്യൽ ഫെസിലിറ്റേഷൻ: മറ്റുള്ളവരുടെ സാന്നിധ്യം പ്രകടനത്തെ ബാധിക്കുന്ന വിധം',
    mlSummary: 'പരിചിതമായ കാര്യങ്ങൾ ജനക്കൂട്ടത്തിന് മുന്നിൽ മികച്ച രീതിയിൽ ചെയ്യാനും പുതിയ സങ്കീർണ്ണ കാര്യങ്ങളിൽ പതറാനും ഇടയാക്കുന്നു.',
    bnTitle: 'সোশ্যাল ফ্যাসিলিটেশন: অন্যের উপস্থিতিতে কাজের দক্ষতার পরিবর্তন',
    bnSummary: 'সহজ বা অভ্যস্ত কাজ মানুষের সামনে দ্রুত হয়, কিন্তু জটিল বুদ্ধিবৃত্তিক কাজের ক্ষেত্রে দর্শকের উপস্থিতি বাধার সৃষ্টি করে।',
    paTitle: 'ਸੋਸ਼ਲ ਫੈਸੀਲੀਟੇਸ਼ਨ: ਦੂਜਿਆਂ ਦੀ ਮੌਜੂਦਗੀ ਵਿੱਚ ਕਾਰਗੁਜ਼ਾਰੀ ਦਾ ਬਦਲਣਾ',
    paSummary: 'ਸੌਖੇ ਕੰਮ ਭੀੜ ਦੇ ਸਾਹਮਣੇ ਬਿਹਤਰ ਹੁੰਦੇ ਹਨ, ਪਰ ਗੁੰਝਲਦਾਰ ਕੰਮਾਂ ਵਿੱਚ ਲੋਕਾਂ ਦੀ ਨਿਗਰਾਨੀ ਕਾਰਨ ਦਿਮਾਗ ਫ੍ਰੀਜ਼ ਹੋ ਜਾਂਦਾ ਹੈ।',
    urTitle: 'سوشل فیسیلیٹیشن: دوسروں کی موجودگی میں کارکردگی کا ردعمل',
    urSummary: 'آسان اور روزمرہ کے کام ہجوم کے سامنے تیز تر ہو جاتے ہیں لیکن پیچیدہ اور فکری کاموں میں رکاوٹ پیدا ہوتی ہے۔',
    orTitle: 'ସୋସିଆଲ୍ ଫାସିଲିଟେସନ୍: ଅନ୍ୟମାନଙ୍କ ଉପସ୍ଥିତିରେ କାର୍ଯ୍ୟଦକ୍ଷତା ବଦଳିବା',
    orSummary: 'ସହଜ କାମ ଲୋକଙ୍କ ଆଗରେ ଶୀଘ୍ର ହୋଇଥାଏ, ମାତ୍ର ଜଟିଳ ନିଷ୍ପତ୍ତି ନେବା ସମୟରେ ଲୋକଙ୍କ ଉପସ୍ଥିତି ବାଧା ସୃଷ୍ଟି କରେ।',
    asTitle: 'ছচিয়েল ফেচিলিটেচন: লোকৰ উপস্থিতিত প্ৰদৰ্শনৰ তাৰতম্য',
    asSummary: 'সহজ আৰু অভ্যস্ত কাম আনৰ উপস্থিতিত দ্ৰুত হয়, কিন্তু জটিল বিশ্লেষণাত্মক কামত মনোযোগ বিঘ্নিত হয়।',
  },
];

console.log('Writing topics...');
let count = 0;
for (const topic of ALL_TOPICS) {
  const content = renderTopicFile(topic);
  const targetPath = path.join(topicsDir, topic.fileName);
  fs.writeFileSync(targetPath, content, 'utf8');
  console.log(`Generated: ${topic.fileName}`);
  count++;
}
console.log(`Done! Wrote ${count} topics.`);
