import * as fs from 'fs';
import * as path from 'path';
import { renderTopicFile } from './generateAllExpandedTopics';

const topicsDir = path.join(__dirname, '../src/core/mind/topics');

const BATCH_2 = [
  // 14. Spotlight Effect
  {
    fileName: 'spotlightEffect.ts',
    varName: 'spotlight_effect',
    id: 'spotlight_effect',
    categoryId: 'social_psychology' as const,
    slug: 'spotlight-effect',
    difficulty: 'beginner' as const,
    readTime: 5,
    sortWeight: 14,
    titleEn: 'The Spotlight Effect: Overestimating How Much Others Notice You',
    subtitle: 'The egocentric cognitive bias where we assume a harsh public spotlight is tracking our every flaw, stain, and stumble.',
    shortDescEn: 'A psychological phenomenon where people tend to overestimate the degree to which they are noticed, observed, and evaluated by others.',
    oneLineEn: 'You are the center of your own universe, but a background extra in everyone else\'s.',
    summary30sEn: 'Discovered in 2000 by Thomas Gilovich and colleagues at Cornell University, the Spotlight Effect proves that humans systematically exaggerate how much the world is watching them. Whether you have a stained shirt, an awkward stutter in a meeting, or bad hair, you assume the entire room is judging you—when in truth, barely anyone noticed.',
    coreConceptEn: 'The Spotlight Effect is rooted in egocentric anchoring and insufficient adjustment. Because we are continuously trapped inside our own sensory experience, our internal state (embarrassment, anxiety, self-consciousness) is intensely salient to us. When estimating what others perceive, we anchor on our own heightened awareness and fail to adjust for the fact that other people are busy thinking about themselves.',
    summary60sEn: 'In Gilovich\'s famous experiment, students were forced to put on an embarrassing Barry Manilow t-shirt before entering a crowded seminar room. The students predicted that at least 50% of the room would notice the ridiculous shirt. In reality, post-room surveys showed that only 23% had even registered what shirt the student was wearing. The students had doubled the perceived audience.',
    takeawaysEn: [
      'The Egocentric Anchor: We assume our internal embarrassment is visible to external observers',
      'The 50% Rule of Thumb: In social situations, assume people notice less than half of what you obsess over',
      'Freedom from Scrutiny: Recognizing the spotlight effect liberates you from crippling social anxiety',
      'Audience Narcissism: Everyone around you is too busy worrying about their own spotlight to watch yours',
    ] as [string, string, string, string],
    whyItHappensEn: 'Egocentric cognitive anchoring. We cannot turn off our first-person perspective, so our own mistakes feel massively magnified.',
    evolutionaryEn: 'In small ancestral bands of 50 people, public blunders could affect tribal reputation and mating opportunities, evolving an over-sensitive paranoia.',
    howItWorksEn: 'You make a small mistake -> Intense internal emotional flash -> Assume your internal state is radiated externally -> Overestimate observer scrutiny -> Experience intense social anxiety.',
    whereEn: 'Public speaking slip-ups, spilling food at parties, bad haircuts, wearing casual clothes to formal events, and making a typo in a company email.',
    headlineEn: 'Perceived Scrutiny vs. Actual Indifference',
    sideALabelEn: 'Your Internal Perception',
    sideADetailEn: '"I stumbled on that slide transition; everyone in this 50-person board meeting thinks I am unqualified."',
    sideBLabelEn: 'Actual Audience Reality',
    sideBDetailEn: '"The attendees were checking their Slack messages, wondering what to eat for lunch, and noticed nothing."',
    researchSummaryEn: 'Gilovich, Medvec & Savitsky (2000) proved across multiple experiments that targets overestimate the salience of their appearance and actions by more than 100%.',
    scenarioTitleEn: 'The Spilled Chai at a Jaipur Sangeet',
    scenarioVignetteEn: 'Rohan attends a grand wedding sangeet in Jaipur. While greeting relatives, he accidentally spills a drop of hot chai on his beige silk kurta, leaving a quarter-sized brown spot near his collar. Rohan is paralyzed with mortification: "The bride\'s family, my cousins, everyone is staring at my messy stain!" He spends the next four hours hiding behind pillars, refusing to dance, and leaving before dinner. The next morning, when he mentions the stain to his sister, she laughs: "What stain? Nobody was looking at your kurta, Rohan."',
    scenarioBreakdownEn: 'The Spotlight Effect in full swing. Rohan anchored on his own acute embarrassment, ruining an entire evening over an imaginary audience.',
    scenarioActionEn: 'Apply the "Nobody Cares Rule": Remind yourself that every other person in that room is completely occupied thinking about their own clothes, hair, and status.',
    pqContextEn: 'A product manager in Bangalore stutters for 3 seconds during a 45-minute sprint demo to 30 colleagues. Afterward, he is so humiliated that he avoids speaking in meetings for the rest of the week.',
    pqPromptEn: 'Which empirical insight from the Spotlight Effect would most effectively recalibrate his anxiety?',
    pqOptA: 'Research shows that over 80% of meeting attendees were intensely analyzing his vocal rhythm',
    pqOptB: 'Most attendees were focused on their own upcoming speaking slots and barely registered the 3-second hesitation',
    pqOptC: 'Taking public speaking classes will eliminate the spotlight effect completely',
    pqOptD: 'Social loafing prevented anyone from paying attention to the entire demo',
    pqCorrect: 'opt_b' as const,
    pqExplanation: 'The spotlight effect proves that people massively overestimate external scrutiny; colleagues are preoccupied with their own tasks and self-presentation.',
    pqTakeaway: 'You are rarely the main character in other people\'s minds: forgive your minor social slips.',
    authorYear: 'Gilovich, Medvec & Savitsky (2000)',
    refTitle: 'The spotlight effect in social judgment: An egocentric bias in estimates of the salience of one\'s own actions and appearance',
    refCitation: 'Gilovich, T., Medvec, V. H., & Savitsky, K. (2000). Journal of Personality and Social Psychology, 78(2), 211–222.',
    doi: '10.1037/0022-3514.78.2.211',
    relatedA: { topicId: 'illusion_of_transparency', slug: 'illusion-of-transparency', title: 'The Illusion of Transparency' },
    relatedB: { topicId: 'social_facilitation', slug: 'social-facilitation', title: 'Social Facilitation' },

    titleHinglish: 'The Spotlight Effect: Hum Sabko Lagta Hai Ki Puri Duniya Hume Dekh Rahi Hai',
    subtitleHinglish: 'Kapde par chota sa daag lagne par hume lagta hai sab hume judge kar rahe hain, jabki kisi ko parwah nahi hoti.',
    shortDescHinglish: 'Ek aisi egocentric soch jisme hume lagta hai ki log hamari har choti galti aur appearance ko continuously observe kar rahe hain.',
    oneLineHinglish: 'Aap apni movie ke hero hain, par baaki logo ki movie me aap bas ek background extra hain.',
    summary30sHinglish: '2000 me Thomas Gilovich ne Spotlight Effect discover kiya. Jab hamare kapde kharab hote hain ya presentation me koi slip of tongue hota hai, toh hume lagta hai ki room ke sab log hamara mazaak uda rahe hain. Sachai yeh hai ki 80% logo ne us baat par dhyaan bhi nahi diya hota, kyunki wo sab apne baare me sochne me busy hote hain.',
    coreConceptHinglish: 'Hum apne dimaag me band hain, isliye hamari choti si sharmindagi hume bohot badi lagti hai. Ise Egocentric Anchoring kehte hain. Sachai yeh hai ki duniya aapko utna closely track nahi kar rahi jitna aap sochte hain.',
    takeawaysHinglish: [
      '50% Rule: Log aapki galti ko aapki expectation se aadhi se bhi kam notice karte hain',
      'Nobody Cares: Har insaan apne baal, kapde aur phone me busy hai',
      'Freedom: Is bias ko samajhne se public anxiety aur self-doubt khatam ho jata hai',
      'Mistakes Are Normal: Minor slip-ups par over-apologize karne ki zaroorat nahi hai',
    ] as [string, string, string, string],

    hiTitle: 'स्पॉटलाइट प्रभाव (Spotlight Effect): अत्यधिक सार्वजनिक ध्यान का भ्रम',
    hiSummary: 'एक ऐसा आत्म-केंद्रित पूर्वाग्रह जिसमें व्यक्ति यह मान बैठता है कि उसकी हर छोटी गलती, रूप-रंग और व्यवहार पर सभी लोग लगातार ध्यान दे रहे हैं और उसका मूल्यांकन कर रहे हैं।',
    hiTakeaways: ['अहं-केंद्रित दृष्टिकोण का प्रभाव', 'सार्वजनिक जांच का अत्यधिक अनुमान', 'सामाजिक चिंता से मुक्ति का उपाय'] as [string, string, string],
    guTitle: 'સ્પોટલાઇટ ઇફેક્ટ: લોકો તમને જ જોઈ રહ્યા છે તેવો ભ્રમ',
    guSummary: 'જ્યારે આપણને લાગે છે કે આપણી દરેક નાની ભૂલ અને વર્તનને આખી દુનિયા નોંધી રહી છે, જ્યારે હકીકતમાં કોઈનું ધ્યાન હોતું નથી.',
    mrTitle: 'स्पॉटलाइट इफेक्ट: संपूर्ण जग आपल्यावरच लक्ष ठेवून असल्याचा भ्रम',
    mrSummary: 'आपल्या छोट्या चुका, कपडे किंवा वागण्यावर सर्वांचेच बारीक लक्ष आहे हा गैरसमज असतो. प्रत्यक्षात लोक स्वतःतच मग्न असतात.',
    teTitle: 'స్పాట్‌లైట్ ఎఫెక్ట్: అందరూ మనల్నే గమనిస్తున్నారనే భ్రమ',
    teSummary: 'మన చిన్న తప్పులు మరియు రూపాన్ని ఇతరులు తీవ్రంగా గమనిస్తున్నారని అతిగా అంచనా వేసే మానసిక పరిస్థితి.',
    taTitle: 'ஸ்பாட்லைட் விளைவு: அனைவரும் நம்மையே கவனிக்கிறார்கள் என்ற மாயை',
    taSummary: 'நமது சிறிய தவறுகளையும் தோற்றத்தையும் மற்றவர்கள் கூர்ந்து கவனிக்கிறார்கள் என்று நாம் தேவையின்றி பயப்படும் நிலை.',
    knTitle: 'ಸ್ಪಾಟ್‌ಲೈಟ್ ಎಫೆಕ್ಟ್: ಎಲ್ಲರೂ ನಮ್ಮನ್ನೇ ಗಮನಿಸುತ್ತಿದ್ದಾರೆಂಬ ಭ್ರಮೆ',
    knSummary: 'ನಮ್ಮ ಸಣ್ಣ ತಪ್ಪುಗಳು ಮತ್ತು ನಡವಳಿಕೆಯನ್ನು ಪ್ರತಿಯೊಬ್ಬರೂ ಸೂಕ್ಷ್ಮವಾಗಿ ಗಮನಿಸುತ್ತಿದ್ದಾರೆ ಎಂದು ಅತಿಯಾಗಿ ಯೋಚಿಸುವ ಮಾನಸಿಕ ದೋಷ.',
    mlTitle: 'സ്പോട്ട്‌ലൈറ്റ് ഇഫക്റ്റ്: എല്ലാവരും നമ്മെത്തന്നെ ശ്രദ്ധിക്കുന്നു എന്ന തെറ്റിദ്ധാരണ',
    mlSummary: 'നമ്മുടെ ചെറിയ വീഴ്ചകളെയും രൂപഭാവങ്ങളെയും മറ്റുള്ളവർ സൂക്ഷ്മമായി വീക്ഷിക്കുന്നുണ്ടെന്ന് അനാവശ്യമായി ചിന്തിക്കുന്ന അവസ്ഥ.',
    bnTitle: 'স্পটলাইট প্রভাব: সবাই আমাকেই দেখছে—এই অহেতুক বিভ্রম',
    bnSummary: 'নিজের ছোটখাটো ভুল বা পোশাকের খুঁত নিয়ে সবাই সমালোচনা করছে ভেবে অহেতুক হীনম্মন্যতায় ভোগার মানসিকতা।',
    paTitle: 'ਸਪੌਟਲਾਈਟ ਪ੍ਰਭਾਵ: ਸਭ ਮੇਰੇ ਵੱਲ ਹੀ ਦੇਖ ਰਹੇ ਹਨ ਦਾ ਭੁਲੇਖਾ',
    paSummary: 'ਇੱਕ ਮਨੋਵਿਗਿਆਨਕ ਭਰਮ ਜਿਸ ਵਿੱਚ ਵਿਅਕਤੀ ਸੋਚਦਾ ਹੈ ਕਿ ਉਸਦੀ ਹਰ ਨਿੱਕੀ ਗਲਤੀ ਉੱਤੇ ਸਾਰੇ ਲੋਕ ਨਜ਼ਰ ਰੱਖ ਰਹੇ ਹਨ।',
    urTitle: 'اسپاٹ لائٹ اثر: ہر وقت توجہ کا مرکز سمجھے جانے کا وہم',
    urSummary: 'یہ سوچنا کہ آپ کی چھوٹی سی غلطی یا لباس کی خامی کو تمام لوگ غور سے دیکھ کر فیصلہ صادر کر رہے ہیں۔',
    orTitle: 'ସ୍ପଟ୍‌ଲାଇଟ୍ ପ୍ରଭାବ: ସମସ୍ତେ ମୋତେ ହିଁ ଦେଖୁଛନ୍ତି ବୋଲି ଭ୍ରମ',
    orSummary: 'ନିଜର ସାମାନ୍ୟ ଭୁଲ୍ ବା ବେଶଭୂଷାକୁ ନେଇ ସାରା ଦୁନିଆ ଆଲୋଚନା କରୁଛି ବୋଲି ଭାବି ଆତଙ୍କିତ ହେବାର ମନସ୍ତତ୍ତ୍ୱ।',
    asTitle: 'স্পটলাইট প্ৰভাৱ: সকলোৱে মোক লক্ষ্য কৰিছে বুলি ভবাৰ ভুল',
    asSummary: 'নিজা ভুল বা সাজ-পোছাকৰ ত্রুটি সকলোৱে লক্ষ্য কৰি আছে বুলি ভাবি অহেতুক সামাজিক লাজ পোৱাৰ মানসিকতা।',
  },

  // 15. Psychological Reactance
  {
    fileName: 'psychologicalReactance.ts',
    varName: 'psychological_reactance',
    id: 'psychological_reactance',
    categoryId: 'social_psychology' as const,
    slug: 'psychological-reactance',
    difficulty: 'intermediate' as const,
    readTime: 5,
    sortWeight: 15,
    titleEn: 'Psychological Reactance: The Instinctive Urge to Defy Restriction',
    subtitle: 'The intense motivational pushback triggered when an individual perceives their autonomy and behavioral freedom being constrained.',
    shortDescEn: 'An unpleasant motivational arousal that emerges when people experience a threat to or loss of their free behaviors, driving them to do the forbidden.',
    oneLineEn: 'Tell someone they cannot have it or do it, and it instantly becomes their obsession.',
    summary30sEn: 'Formulated by Jack Brehm in 1966, Psychological Reactance is the brain\'s immune system against coercion. When someone forcefully orders you to do something, limits your options, or bans a behavior, you feel a visceral surge of anger and an overwhelming desire to do the exact opposite to restore your sense of freedom.',
    coreConceptEn: 'Reactance is an evolutionary defense of personal sovereignty. When perceived freedom is threatened, three things occur: (1) The forbidden option skyrockets in perceived attractiveness; (2) The person experiences negative emotional affect (anger, resentment); (3) The person actively engages in counter-behaviors to restore autonomy (the "Romeo and Juliet effect").',
    summary60sEn: 'In a classic 1972 study by James Pennebaker, signs in university restrooms were compared. Sign A read: "Do not write on these walls under any circumstances." Sign B read: "Please do not write on these walls." Restrooms with the authoritative, freedom-restricting Sign A suffered dramatically more graffiti vandalism. Harsh demands provoke rebellion.',
    takeawaysEn: [
      'The Forbidden Fruit Effect: Banning or censoring an idea immediately increases public interest in it',
      'The Coercion Backlash: Aggressive mandates in marketing, parenting, and management trigger active resistance',
      'The Autonomy Paradox: People willingly follow advice if they feel the choice was completely theirs',
      'Autonomy-Supportive Language: Replace "You must do this" with "It is completely up to you, but here are the facts"',
    ] as [string, string, string, string],
    whyItHappensEn: 'Self-determination and personal control. Humans prioritize autonomy over obedience; perceived threats to freedom trigger defensive rebellion.',
    evolutionaryEn: 'In ancestral dominance hierarchies, blindly submitting to unilateral restrictions could reduce resource access and status, requiring calibrated pushback.',
    howItWorksEn: 'Freedom threatened by an authority or rule -> Emotional reactance surge (irritation) -> Forbidden alternative becomes highly attractive -> Defiant action taken to reassert control.',
    whereEn: 'Parent-teen disputes, public health mandates, sales pressure tactics, heavy-handed software policies, and government censorship.',
    headlineEn: 'Aggressive Mandate vs. Autonomy-Supportive Choice',
    sideALabelEn: 'Coercive Restriction (Triggers Reactance)',
    sideADetailEn: '"You are strictly forbidden from choosing arts; you must study engineering or you are disowned."',
    sideBLabelEn: 'Autonomy Choice (Invites Rationality)',
    sideBDetailEn: '"The career decision is yours. Let us analyze the job market data and risks together."',
    researchSummaryEn: 'Jack W. Brehm (1966) published the seminal book "A Theory of Psychological Reactance," proving individuals will choose objectively worse outcomes simply to reclaim freedom.',
    scenarioTitleEn: 'The Strict Engineering Mandate in Kota',
    scenarioVignetteEn: 'Rishi is an 18-year-old student preparing for competitive exams in Kota. His father constantly monitors his phone, installs CCTV in his study room, and announces: "You are not allowed to touch a musical guitar or play cricket until you crack the entrance exam." Feeling suffocated and micro-managed, Rishi develops intense psychological reactance. He secretly skips physics lectures to smoke on the hostel terrace and completely stops studying, purely to regain a feeling of being in control of his own life.',
    scenarioBreakdownEn: 'Textbook psychological reactance. The father\'s complete destruction of Rishi\'s autonomy transformed self-destructive defiance into an emotional victory of reclaiming control.',
    scenarioActionEn: 'Restore autonomy through collaborative choice architecture: establish joint goals and grant unconditional ownership over daily scheduling and small hobbies.',
    pqContextEn: 'An HR department in Gurgaon sends a stern company-wide email: "All employees MUST mandatorily attend tomorrow\'s 8 AM wellness seminar. Attendance will be audited and violators reported." Attendance ends up being the lowest in company history.',
    pqPromptEn: 'Which communication shift would leverage Brehm\'s Reactance Theory to maximize actual attendance?',
    pqOptA: 'Threatening salary deductions for anyone who arrives even two minutes late',
    pqOptB: 'Framing attendance as an open choice: "Attendance is entirely voluntary, but here is how previous attendees boosted their energy and focus"',
    pqOptC: 'Hiring security guards to check badges at the auditorium entrance',
    pqOptD: 'Making the seminar 3 hours longer to prove its institutional value',
    pqCorrect: 'opt_b' as const,
    pqExplanation: 'Autonomy-supportive framing removes the perceived threat to freedom, allowing individuals to choose participation without feeling coerced.',
    pqTakeaway: 'Respect autonomy to invite cooperation: whenever you force someone, their brain immediately wants to push back.',
    authorYear: 'Jack W. Brehm (1966)',
    refTitle: 'A Theory of Psychological Reactance',
    refCitation: 'Brehm, J. W. (1966). A Theory of Psychological Reactance. New York: Academic Press.',
    doi: '10.1111/j.1460-2466.2005.tb02664.x',
    relatedA: { topicId: 'conformity_asch_effect', slug: 'conformity-asch-effect', title: 'Conformity (Asch Effect)' },
    relatedB: { topicId: 'social_proof', slug: 'social-proof', title: 'Social Proof' },

    titleHinglish: 'Psychological Reactance: Jab Mana Karne Par Wo Kaam Karne Ka Dil Karta Hai',
    subtitleHinglish: 'Jab koi hume hukum deta hai ya humari aazadi cheenta hai, toh dimaag jaanbujhkar ulta kaam karta hai.',
    shortDescHinglish: 'Aazadi chhinne par paida hone wali aisi gusse bhari zid jisme insaan sirf control wapas paane ke liye rule tod deta hai.',
    oneLineHinglish: 'Kisi ko bolo "yeh mat karna", aur wo sabse pehle wahi karega.',
    summary30sHinglish: '1966 me Jack Brehm ne Psychological Reactance explain kiya. Jab kisi insaan par strict restriction lagayi jaati hai ya use jabardasti kuch karne ko kaha jata hai, toh uska dimaag use attack manta hai. Freedom wapas lene ke liye insaan jaan-bujhkar wahi kaam karta hai jisse use mana kiya gaya tha.',
    coreConceptHinglish: 'Insaan ko apni aazadi bohot pyari hoti hai. "Forbidden fruit" iska proof hai: jo cheez ban hoti hai, log usi ko dekhne ke liye VPN lagate hain. Leadership aur parenting me jab aap "You must" kehte hain, toh samne wala dushman ban jata hai.',
    takeawaysHinglish: [
      'Forbidden Fruit Effect: Jis cheez par ban lagta hai, uski demand double ho jati hai',
      'Jabardasti Ka Nuksan: Micro-management se employees kaam chori shuru kar dete hain',
      'Choice Ka Jadoo: "Faisla aapka hai" kehne se log aapki advice zyada maante hain',
      'Reverse Psychology: Reactance ko samajhkar log manipulate bhi karte hain, isliye satark rahein',
    ] as [string, string, string, string],

    hiTitle: 'मनोवैज्ञानिक प्रतिक्रिया (Psychological Reactance): पाबंदी के विरुद्ध विद्रोह की स्वाभाविक प्रवृत्ति',
    hiSummary: 'जब किसी व्यक्ति को लगता है कि उसकी स्वतंत्रता या स्वायत्तता छीनी जा रही है, तो वह तीव्र प्रतिरोध महसूस करता है और जानबूझकर वही काम करता है जो वर्जित किया गया है।',
    hiTakeaways: ['स्वायत्तता की रक्षा की प्रवृत्ति', 'निषेध का आकर्षण (वर्जित फल)', 'आदेश के स्थान पर विकल्प देना प्रभावी'] as [string, string, string],
    guTitle: 'સાયકોલોજિકલ રિએક્ટન્સ: બંધનો સામે વિદ્રોહ કરવાની વૃત્તિ',
    guSummary: 'જ્યારે કોઈ આપણી સ્વતંત્રતા પર પ્રતિબંધ મૂકે છે, ત્યારે મગજ પોતાની સ્વાયત્તતા સાબિત કરવા માટે જાણીજોઈને વિપરીત પગલાં ભરે છે.',
    mrTitle: 'सायकोलॉजिकल रिॲक्टन्स: बंधनांविरुद्ध बंडखोरीची मानसिक वृत्ती',
    mrSummary: 'जेव्हा लोकांच्या स्वातंत्र्यावर गदा येते, तेव्हा ते स्वतःचे नियंत्रण परत मिळवण्यासाठी नेमके निषिद्ध काम करतात.',
    teTitle: 'సైకలాజికల్ రియాక్టెన్స్: ఆంక్షలపై తిరుగుబాటు చేసే సహజ ప్రవృత్తి',
    teSummary: 'వ్యక్తిగత స్వేచ్ఛకు భంగం కలిగినప్పుడు తిరస్కరించబడిన విషయాన్ని కావాలనే చేసే మానసిక స్వభావం.',
    taTitle: 'உளவியல் எதிர்ப்பு: கட்டுப்பாடுகளை மீறும் இயல்பான உந்துதல்',
    taSummary: 'நமது சுதந்திரம் பறிக்கப்படும் போது, அதை மீட்டெடுக்க வேண்டும் என்ற ஆவேசத்தில் தடைசெய்யப்பட்ட காரியத்தை துணிந்து செய்யும் நிலை.',
    knTitle: 'ಸೈಕಲಾಜಿಕಲ್ ರಿಯಾಕ್ಟೆನ್ಸ್: ನಿರ್ಬಂಧಗಳ ವಿರುದ್ಧ ಬಂಡಾಯವೆದ್ದು ಕೆಲಸ ಮಾಡುವ ಪ್ರವೃತ್ತಿ',
    knSummary: 'ತಮ್ಮ ಸ್ವಾತಂತ್ರ್ಯವನ್ನು ಕಸಿದುಕೊಳ್ಳಲಾಗುತ್ತಿದೆ ಎಂದು ಭಾವಿಸಿದಾಗ ನಿಷೇಧಿತ ಕೆಲಸವನ್ನೇ ಹಠದಿಂದ ಮಾಡುವ ಪ್ರವೃತ್ತಿ.',
    mlTitle: 'സൈക്കോളജിക്കൽ റിയാക്ടൻസ്: നിയന്ത്രണങ്ങൾക്കെതിരെയുള്ള സ്വാഭാവിക കലാപം',
    mlSummary: 'നമ്മുടെ വ്യക്തിസ്വാതന്ത്ര്യം പരിമിതപ്പെടുത്തപ്പെടുമ്പോൾ നിരോധിക്കപ്പെട്ട കാര്യങ്ങളിലേക്ക് മനസ്സ് കൂടുതൽ ആകർഷിക്കപ്പെടുന്ന അവസ്ഥ.',
    bnTitle: 'সাইকোলজিক্যাল রিঅ্যাক্ট্যান্স: নিষেধাজ্ঞার বিরুদ্ধে স্বতঃস্ফূর্ত বিদ্রোহের মানসিকতা',
    bnSummary: 'স্বাধীনতা খর্ব হলে নিজের নিয়ন্ত্রণ জাহির করতে মানুষ ঠিক নিষিদ্ধ কাজটিই করার তীব্র তাগিদ অনুভব করে।',
    paTitle: 'ਮਨੋਵਿਗਿਆਨਕ ਪ੍ਰਤੀਕਿਰਿਆ: ਪਾਬੰਦੀਆਂ ਦੇ ਵਿਰੁੱਧ ਬਗਾਵਤ ਦੀ ਆਦਤ',
    paSummary: 'ਜਦੋਂ ਕਿਸੇ ਉੱਤੇ ਹੁਕਮ ਚਲਾਇਆ ਜਾਂਦਾ ਹੈ ਜਾਂ ਕੋਈ ਕੰਮ ਕਰਨ ਤੋਂ ਰੋਕਿਆ ਜਾਂਦਾ ਹੈ, ਤਾਂ ਉਹ ਆਪਣੀ ਆਜ਼ਾਦੀ ਸਾਬਤ ਕਰਨ ਲਈ ਉਹੀ ਕੰਮ ਕਰਦਾ ਹੈ।',
    urTitle: 'نفسیاتی مزاحمت: پابندی کے خلاف بغاوت کا فطری جذبہ',
    urSummary: 'جب انسان کی خود مختاری چھینی جاتی ہے تو وہ اپنا کنٹرول ثابت کرنے کے لیے جان بوجھ کر ممنوعہ کام کرتا ہے۔',
    orTitle: 'ମାନସିକ ପ୍ରତିକ୍ରିୟା: କଟକଣା ବିରୁଦ୍ଧରେ ବିଦ୍ରୋହ କରିବାର ସହଜାତ ପ୍ରବୃତ୍ତି',
    orSummary: 'ଯେତେବେଳେ କାହା ଉପରେ କଟକଣା ଲଗାଯାଏ, ସେ ନିଜର ସ୍ୱାଧୀନତା ପ୍ରମାଣିତ କରିବା ପାଇଁ ଉଦ୍ଦେଶ୍ୟମୂଳକ ଭାବେ ସେହି ନିଷିଦ୍ଧ କାର୍ଯ୍ୟ କରେ।',
    asTitle: 'মনস্তাত্ত্বিক প্ৰতিক্ৰিয়া: নিষেধাজ্ঞা আৰু বন্ধনৰ বিৰুদ্ধে বিদ্ৰোহ',
    asSummary: 'স্বাধীনতা খৰ্ব হ’লে নিজৰ নিয়ন্ত্ৰণ সাব্যস্ত কৰিবলৈ মানুহে নিষিদ্ধ কামটোকে আগবাঢ়ি কৰাৰ মানসিক প্ৰৱণতা।',
  },
];

console.log('Writing Social Psychology batch 2...');
for (const topic of BATCH_2) {
  const content = renderTopicFile(topic);
  const targetPath = path.join(topicsDir, topic.fileName);
  fs.writeFileSync(targetPath, content, 'utf8');
  console.log(`Generated: ${topic.fileName}`);
}
console.log('Done Social Psychology batch 2.');
