import * as fs from 'fs';
import * as path from 'path';
import { renderTopicFile } from './generateAllExpandedTopics';

const topicsDir = path.join(__dirname, '../src/core/mind/topics');

const REMAINING_5_SOCIAL_PSYCHOLOGY = [
  // 16. Just-World Hypothesis
  {
    fileName: 'justWorldHypothesis.ts',
    varName: 'just_world_hypothesis',
    id: 'just_world_hypothesis',
    categoryId: 'social_psychology' as const,
    slug: 'just-world-hypothesis',
    difficulty: 'intermediate' as const,
    readTime: 6,
    sortWeight: 16,
    titleEn: 'The Just-World Hypothesis: The Urge to Believe Life is Fair',
    subtitleEn: 'The cognitive necessity to believe that noble actions are rewarded and evil is punished, frequently leading to victim-blaming.',
    shortDescEn: 'A cognitive bias wherein people assume that a person\'s actions inherently bring morally fair and fitting consequences to that person.',
    oneLineEn: 'Assuming people get what they deserve, and deserve what they get.',
    summary30sEn: 'First formulated by Melvin Lerner in 1965, the Just-World Hypothesis is our psychological defense against the terror of random misfortune. To feel safe in an unpredictable world, humans convince themselves that the universe operates on cosmic justice: good things happen to good people, and tragedy only befalls those who made foolish or immoral choices.',
    coreConceptEn: 'The belief in a just world creates a powerful psychological delusion: if bad things can happen completely at random to innocent people, then disaster could strike us at any second. To ward off this existential dread, observers subconsciously blame the victim (e.g., "They shouldn\'t have walked alone," "They must have been careless"), reassuring themselves that careful people remain immune to catastrophe.',
    summary60sEn: 'Lerner\'s foundational experiments showed students observing an innocent victim receiving painful electrical shocks during a learning task. When observers were completely powerless to stop the suffering or compensate the victim, they began derogating the victim\'s character, viewing her as unintelligent, careless, or morally flawed. Their minds invented moral culpability to maintain the illusion of cosmic fairness.',
    takeawaysEn: [
      'The Illusion of Universal Fairness: The universe is indifferent; randomness affects good and bad alike',
      'The Roots of Victim-Blaming: Blaming victims is a defensive mechanism to soothe our own vulnerability',
      'The Karma Misapplication: Conflating personal moral responsibility with arbitrary systemic accidents',
      'Empathetic Recalibration: Separate someone\'s tragic outcome from assumptions about their moral worth',
    ] as [string, string, string, string],
    whyItHappensEn: 'Existential anxiety reduction. Acknowledging that cruel tragedies can strike completely innocent people creates intense psychological vulnerability.',
    evolutionaryEn: 'Promoted cooperation and rule-following in ancestral tribes by fostering faith that prosocial deeds would ultimately be rewarded.',
    howItWorksEn: 'Tragedy strikes an innocent person -> Observer feels existential dread -> "If it happened to them, it could happen to me" -> Search for victim flaws -> Conclude victim deserved it -> Sense of safety restored.',
    whereEn: 'Accident reporting, medical disease judgments, financial bankruptcy commentary, poverty discussions, and judicial courtrooms.',
    headlineEn: 'Cosmic Fairness Illusion vs. Statistical Reality',
    sideALabelEn: 'Just-World Fallacy',
    sideADetailEn: '"He got laid off after 15 years; he must have been secretly lazy or incompetent in his duties."',
    sideBLabelEn: 'Objective Reality',
    sideBDetailEn: '"The entire industry faced macro-economic headwinds; layoffs impacted top and bottom performers indiscriminately."',
    researchSummaryEn: 'Lerner (1965, 1980) documented across decades of empirical testing that when people cannot rectify suffering, they cognitively re-evaluate victims as deserving their fate.',
    scenarioTitleEn: 'The Highway Accident on the Delhi-Jaipur Expressway',
    scenarioVignetteEn: 'During heavy monsoon rains, an auto-rickshaw carrying a daily-wage worker, Ramesh, is struck by a speeding truck whose brakes failed. Ramesh suffers severe fractures. At the local tea stall, onlookers discuss the news: "Why was he traveling in an auto in the rain? He should have taken a bus. Poor people take unnecessary risks." None of them check if the truck driver was speeding or the road was poorly lit.',
    scenarioBreakdownEn: 'Classic Just-World Hypothesis. The tea-stall onlookers rationalize Ramesh\'s catastrophe by inventing personal flaws in his travel choice, soothing their own fear that an errant truck could crush any of them on that same road.',
    scenarioActionEn: 'Counter victim-blaming with systemic causality: examine engineering, road safety policies, and vehicle mechanics rather than attacking the victim\'s character.',
    pqContextEn: 'Following a sudden data breach at an ed-tech startup caused by a zero-day vulnerability, several board members remark: "The IT head must have been incompetent or corrupt to let this happen, even though all security audits were green."',
    pqPromptEn: 'Which psychological mechanism explains the board\'s urge to blame the IT head rather than accept that zero-day exploits carry unavoidable systemic risk?',
    pqOptA: 'Group polarization toward cyber-security funding',
    pqOptB: 'The Just-World Hypothesis comforting the board by attributing bad outcomes to individual moral/competence flaws',
    pqOptC: 'Social loafing among the development engineers',
    pqOptD: 'The Pygmalion effect elevating the attackers\' performance',
    pqCorrect: 'opt_b' as const,
    pqExplanation: 'The Just-World Hypothesis drives people to attribute catastrophic events to individual fault rather than accept that unpredictability and random threats exist.',
    pqTakeaway: 'Resist the urge to blame victims: randomness does not consult anyone\'s moral ledger.',
    authorYear: 'Melvin J. Lerner (1980)',
    refTitle: 'The Belief in a Just World: A Fundamental Delusion',
    refCitation: 'Lerner, M. J. (1980). The Belief in a Just World: A Fundamental Delusion. Plenum Press, New York.',
    doi: '10.1007/978-1-4899-0448-5',
    relatedA: { topicId: 'fundamental_attribution_error', slug: 'fundamental-attribution-error', title: 'Fundamental Attribution Error' },
    relatedB: { topicId: 'hindsight_bias', slug: 'hindsight-bias', title: 'Hindsight Bias' },

    titleHinglish: 'The Just-World Hypothesis: Duniya Hamesha Fair Hoti Hai Ka Bhram',
    subtitleHinglish: 'Hume lagta hai ache logo ke sath acha aur bure ke sath bura hota hai, isliye hum accident ke victim ko hi dosh dene lagte hain.',
    shortDescHinglish: 'Ek aisi soch jisme hum maan lete hain ki jo jaisa karega waisa bharega, aur haadse ka shikaar insaan khud hi apni musibat ka zimmedar hai.',
    oneLineHinglish: 'Yeh sochna ki kismat hamesha insaaf karti hai, aur victim me hi koi kami thi.',
    summary30sHinglish: '1965 me Melvin Lerner ne Just-World Hypothesis discover kiya. Jab kisi masoom ke sath koi bura haadsa hota hai, toh hume darr lagta hai ki yeh hamare sath bhi ho sakta hai. Is darr se bachne ke liye hamara dimaag victim me hi galtiyan dhoondhne lagta hai—jaise "use wahan jaana hi nahi chahiye tha"—taaki hume lage ki hum safe hain.',
    coreConceptHinglish: 'Duniya me bohot si cheezein random hoti hain. Lekin insaan ka dimaag randomness accept nahi kar pata. Hum karma ko galat tareeqe se apply karte hain aur bimaari, poverty ya accident ke victims ko judge karne lagte hain.',
    takeawaysHinglish: [
      'Victim-Blaming Ka Sach: Hum victim ko isliye blame karte hain taaki khud ko surakshit mehsoos kara sakein',
      'Randomness Ki Haqeeqat: Bura haadsa kisi ke sath bhi bina kisi galti ke ho sakta hai',
      'False Sense of Security: "Main aisi galti nahi karunga" sochna bas ek jhoothi tasalli hai',
      'Compassion First: Haadse ke waqt moral lecture dene ke bajaye madad par dhyaan dein',
    ] as [string, string, string, string],

    hiTitle: 'न्यायपूर्ण विश्व परिकल्पना (Just-World Hypothesis): न्यायसंगत दुनिया का भ्रम',
    hiSummary: 'यह विश्वास कि दुनिया मूलतः निष्पक्ष है जहाँ लोगों को उनके कर्मों के अनुसार ही फल मिलता है; इसके कारण लोग अक्सर निर्दोष पीड़ितों को ही उनके दुर्भाग्य का दोषी ठहराने लगते हैं।',
    hiTakeaways: ['पीड़ित को दोष देने की मनोवैज्ञानिक प्रवृत्ति', 'अनिश्चितता और भय से बचने की रक्षा-प्रणाली', 'संयोग और दुर्भाग्य की वास्तविकता को स्वीकारना'] as [string, string, string],
    guTitle: 'જસ્ટ-વર્લ્ડ હાયપોથિસિસ: દુનિયા હંમેશા ન્યાયી છે તેવો ભ્રમ',
    guSummary: 'જ્યારે લોકો માને છે કે દરેક વ્યક્તિ સાથે તેના કર્મો મુજબ જ થાય છે, જેના પરિણામે અકસ્માત કે આફતના ભોગ બનેલા નિર્દોષને જ દોષી ગણવામાં આવે છે.',
    mrTitle: 'जस्ट-वर्ल्ड हायपोथिसिस: जग पूर्णतः न्याय्य असल्याचा गैरसमज',
    mrSummary: 'चांगल्या लोकांसोबत चांगलेच घडते आणि वाईटांसोबत वाईट हा हट्ट धरल्यामुळे पीडित व्यक्तीलाच तिच्या दुर्दैवासाठी जबाबदार धरण्याची विकृती निर्माण होते.',
    teTitle: 'జస్ట్-వరల్డ్ హైపోథీసిస్: ప్రపంచం ఎల్లప్పుడూ న్యాయబద్ధంగా ఉంటుందనే భ్రమ',
    teSummary: 'మంచివారికి మంచే జరుగుతుందని భావించి, అనుకోని ప్రమాదాల్లో చిక్కుకున్న బాధితులనే నిందించే అహేతుక ఆలోచనా విధానం.',
    taTitle: 'நியாயமான உலகக் கோட்பாடு: உலகம் எப்போதும் நியாயமானது என்ற மாயை',
    taSummary: 'நல்லவர்களுக்கு நன்மையே நடக்கும் என குருட்டுத்தனமாக நம்பி, எதிர்பாராத விபத்தில் பாதிக்கப்பட்டவர்களையே குற்றம் சாட்டும் மனித உளவியல்.',
    knTitle: 'ಜಸ್ಟ್-ವರ್ಲ್ಡ್ ಹೈಪೋಥಿಸಿಸ್: ಜಗತ್ತು ಸದಾ ನ್ಯಾಯಯುತವಾಗಿದೆ ಎಂಬ ಭ್ರಮೆ',
    knSummary: 'ಒಳ್ಳೆಯವರಿಗೆ ಒಳ್ಳೆಯದೇ ಆಗುತ್ತದೆ ಎಂದು ಭಾವಿಸಿ, ಅನಿರೀಕ್ಷಿತ ದುರಂತಕ್ಕೀಡಾದ ಸಂತ್ರಸ್ತರನ್ನೇ ದೂಷಿಸುವ ಮಾನಸಿಕ ದೋಷ.',
    mlTitle: 'ജസ്റ്റ്-വേൾഡ് ഹൈപ്പോതെസിസ്: ലോകം തികച്ചും നീതിയുക്തമാണെന്ന മിഥ്യാധാരണ',
    mlSummary: 'നല്ലവർക്ക് നല്ലതേ വരൂ എന്ന് വിശ്വസിച്ച്, അപ്രതീക്ഷിത ദുരന്തങ്ങളിൽ പെടുന്ന നിരപരാധികളെത്തന്നെ കുറ്റപ്പെടുത്തുന്ന മനോഭാവം.',
    bnTitle: 'জাস্ট-ওয়ার্ল্ড হাইপোথিসিস: পৃথিবী সর্বদা ন্যায়সঙ্গত—এই অন্ধ বিশ্বাস',
    bnSummary: 'মানুষ তার কর্মফলেই কষ্ট পায়—এই বিশ্বাস আঁকড়ে ধরে কোনো দুর্ঘটনার শিকার নিরপরাধ ব্যক্তিকেই দোষারোপ করার অদ্ভুত প্রবণতা।',
    paTitle: 'ਜਸਟ-ਵਰਲਡ ਹਾਈਪੋਥਿਸਿਸ: ਦੁਨੀਆ ਹਮੇਸ਼ਾ ਇਨਸਾਫ਼-ਪਸੰਦ ਹੈ ਦਾ ਭੁਲੇਖਾ',
    paSummary: 'ਇਹ ਮੰਨਣਾ ਕਿ ਮਾੜਾ ਸਿਰਫ਼ ਮਾੜੇ ਲੋਕਾਂ ਨਾਲ ਹੀ ਹੁੰਦਾ ਹੈ, ਜਿਸ ਕਰਕੇ ਪੀੜਤ ਵਿਅਕତି ਨੂੰ ਹੀ ਉਸਦੇ ਦੁੱਖਾਂ ਦਾ ਕਸੂਰਵਾਰ ਠਹਿਰਾਇਆ ਜਾਂਦਾ ਹੈ।',
    urTitle: 'منصفانہ دنیا کا مغالطہ: ہر انجام کو ذاتی عمل کا نتیجہ سمجھنا',
    urSummary: 'یہ یقین رکھنا کہ دنیا ہمیشہ انصاف پر چلتی ہے، جس کی وجہ سے حادثات کے شکار معصوم افراد کو ہی ان کی بدقسمتی کا ذمہ دار ٹھہرایا جاتا ہے۔',
    orTitle: 'ଜଷ୍ଟ-ୱାର୍ଲ୍ଡ ହାଇପୋଥିସିସ୍: ଦୁନିଆ ସର୍ବଦା ନ୍ୟାୟପୂର୍ଣ୍ଣ ବୋଲି ଭ୍ରମ',
    orSummary: 'ଭଲ ଲୋକଙ୍କ ସହ କେବଳ ଭଲ ହିଁ ଘଟେ ବୋଲି ବିଶ୍ୱାସ କରି ବିପଦରେ ପଡ଼ିଥିବା ନିରୀହ ପୀଡ଼ିତଙ୍କୁ ହିଁ ଦୋଷ ଦେବାର ମନସ୍ତାତ୍ତ୍ୱିକ ଦୁର୍ବଳତା।',
    asTitle: 'জাস্ট-ৱাৰ্ল্ড হাইপ’থিছিছ: পৃথিৱীখন সদায় ন্যায়সঙ্গত বুলি ভবাৰ ভুল',
    asSummary: 'ভাল মানুহৰ লগত বেয়া নহয় বুলি ভাবি কোনো দুৰ্ঘটনাত পতিত নিৰীহ ব্যক্তিক নিজেই দোষী সাব্যস্ত কৰাৰ মানসিক বিকৃতি।',
  },

  // 17. Realistic Conflict Theory
  {
    fileName: 'realisticConflictTheory.ts',
    varName: 'realistic_conflict_theory',
    id: 'realistic_conflict_theory',
    categoryId: 'social_psychology' as const,
    slug: 'realistic-conflict-theory',
    difficulty: 'intermediate' as const,
    readTime: 6,
    sortWeight: 17,
    titleEn: 'Realistic Conflict Theory: Resource Scarcity and Intergroup Hostility',
    subtitleEn: 'How competition over scarce, zero-sum resources transforms cordial groups into bitter rivals—and how superordinate goals unite them.',
    shortDescEn: 'A model of intergroup conflict explaining how real or perceived competition for limited resources inevitably sparks prejudice, hostility, and discrimination.',
    oneLineEn: 'When two groups fight over one pie, prejudice is manufactured; when they bake a bigger pie together, peace returns.',
    summary30sEn: 'Demonstrated in 1954 by Muzafer Sherif in the legendary Robbers Cave Experiment, Realistic Conflict Theory explains that prejudice does not require ancient cultural hatreds. Merely putting two distinct groups into direct zero-sum competition over scarce rewards (trophies, promotions, water, territory) rapidly triggers dehumanization, tribal slurs, and overt hostility.',
    coreConceptEn: 'Sherif\'s breakthrough proved two profound truths: (1) Intergroup conflict is easily ignited through negative interdependence (one group\'s victory means the other\'s defeat); (2) Mere contact or lecturing does not fix hostility. The only reliable cure is introducing superordinate goals—urgent challenges that neither group can solve alone without mutual cooperation.',
    summary60sEn: 'At Robbers Cave camp, 22 well-adjusted boys were split into the "Eagles" and "Rattlers". Within days of competitive tournaments for pocketknives and trophies, the boys burned each other\'s banners, raided cabins, and carried socks filled with rocks. Sherif then created superordinate emergencies: the camp\'s sole water pipeline ruptured, and a supply truck broke down. To survive, both tribes had to pull the same rope together, dissolving all hostility into genuine camaraderie.',
    takeawaysEn: [
      'The Zero-Sum Trigger: Scarcity transforms neutral peers into bitter tribal enemies',
      'The Superordinate Goal Antidote: Intergroup peace requires shared survival objectives, not polite team-building dinners',
      'Manufactured Prejudice: Bias is often the symptom of economic competition, not its primary cause',
      'Cross-Functional Alignment: Break silo wars by tying departmental bonuses to unified company-wide metrics',
    ] as [string, string, string, string],
    whyItHappensEn: 'Resource competition and zero-sum threat perception. When resources are limited, our evolutionary tribal circuitry mobilizes aggression against rivals.',
    evolutionaryEn: 'In Paleolithic eras, bands competed for hunting grounds, fertile riverbanks, and cave shelter; outgroup aggression protected tribal lineage.',
    howItWorksEn: 'Scarce resource identified -> Groups realize only one can win -> Ingroup solidarity tightens -> Outgroup is demonized and stereotyped -> Conflict erupts -> Superordinate goal unites both groups.',
    whereEn: 'Departmental budget battles, startup co-founder disputes, water-sharing river disputes between states, and corporate mergers.',
    headlineEn: 'Zero-Sum Resource Battle vs. Superordinate Unification',
    sideALabelEn: 'Zero-Sum Scarcity (Conflict Escalation)',
    sideADetailEn: '"Product and Sales are competing for a single fixed bonus pool; each department sabotages the other\'s timelines."',
    sideBLabelEn: 'Superordinate Goal (Cooperative Synergy)',
    sideBDetailEn: '"The primary client threatened to cancel the enterprise contract unless both teams deliver a joint integration within 48 hours."',
    researchSummaryEn: 'Sherif et al. (1961) published "Intergroup Conflict and Cooperation: The Robbers Cave Experiment," providing the foundation for modern conflict resolution.',
    scenarioTitleEn: 'The IT Silo Warfare in a Mumbai Fintech',
    scenarioVignetteEn: 'At a growing Mumbai payment gateway company, the Backend Engineering team and the Risk Management team despise each other. Backend calls Risk "paranoid bureaucrats who slow down deployment," while Risk calls Backend "reckless cowboys who ignore fraud." Hostility explodes during quarterly appraisals when only one team can win the "Excellence Award." However, during Diwali shopping week, a massive Distributed Denial of Service (DDoS) attack knocks the payment servers offline. For 36 continuous hours, both teams sit in the war room ordering pizza, fixing firewall vulnerabilities and optimizing database locks together. By the time the servers are restored, the bitter rivalry has evaporated into mutual respect.',
    scenarioBreakdownEn: 'A textbook real-world demonstration of Realistic Conflict Theory. The zero-sum award created tribal rivalry; the existential server threat acted as a superordinate goal requiring joint survival.',
    scenarioActionEn: 'Abolish silo-based zero-sum competitions; replace them with collaborative cross-functional objectives and collective performance metrics.',
    pqContextEn: 'Two branch offices of an Indian bank in Pune are pitted against each other to win the single "Best Region" trophy. Within two months, loan officers hide high-value leads and refuse to share verification files.',
    pqPromptEn: 'Based on Sherif\'s Realistic Conflict Theory, which leadership intervention would most effectively resolve this inter-branch warfare?',
    pqOptA: 'Organizing a mandatory weekend motivational dinner for both teams',
    pqOptB: 'Increasing the cash value of the single winning trophy',
    pqOptC: 'Establishing a superordinate regional target where both branches must collaborate to beat a rival competitor bank',
    pqOptD: 'Firing the lowest-performing employee from each branch',
    pqCorrect: 'opt_c' as const,
    pqExplanation: 'Sherif proved that only superordinate goals requiring joint interdependence eliminate intergroup prejudice created by zero-sum competition.',
    pqTakeaway: 'When teams fight over scraps, redirect their collective focus toward a shared, larger mission.',
    authorYear: 'Muzafer Sherif et al. (1961)',
    refTitle: 'Intergroup Conflict and Cooperation: The Robbers Cave Experiment',
    refCitation: 'Sherif, M., Harvey, O. J., White, B. J., Hood, W. R., & Sherif, C. W. (1961). Intergroup Conflict and Cooperation: The Robbers Cave Experiment. University of Oklahoma Book Exchange.',
    doi: '10.1037/h0045199',
    relatedA: { topicId: 'ingroup_outgroup_bias', slug: 'ingroup-outgroup-bias', title: 'Ingroup-Outgroup Bias' },
    relatedB: { topicId: 'social_identity_theory', slug: 'social-identity-theory', title: 'Social Identity Theory' },

    titleHinglish: 'Realistic Conflict Theory: Jab Limited Resources Se Dushmani Paida Hoti Hai',
    subtitleHinglish: 'Jab do groups ek hi cheez ke liye ladte hain toh nafrat badhti hai; par jab milkar koi musibat solve karte hain toh dosti ho jati hai.',
    shortDescHinglish: 'Ek aisi psychological theory jo batati hai ki resources ki kami se aapas me dushmani kaise shuru hoti hai aur shared goals se kaise khatam hoti hai.',
    oneLineHinglish: 'Resource ek aur ladne wale do, toh nafrat banegi; samasya badi aur dono mil jayein, toh dosti hogi.',
    summary30sHinglish: '1954 ke prasiddh Robbers Cave experiment me Muzafer Sherif ne dikhaya ki dushmani paida karne ke liye koi purani dushmani ki zaroorat nahi hoti. Bas do groups ke beech ek single prize ya resource rakh do, dono ek doosre ke dushman ban jayenge. Aur is nafrat ko sirf ek Superordinate Goal—yaani aisi musibat jise dono milkar hi hal kar sakein—se hi mitaya ja sakta hai.',
    coreConceptHinglish: 'Office me departments ke beech jo ladaai hoti hai (jaise Tech vs Sales), wo unke nature ki wajah se nahi, balki zero-sum appraisal system ki wajah se hoti hai. Jab dono ko lagta hai ki doosre ki jeet meri haar hai, toh toxicity badhti hai.',
    takeawaysHinglish: [
      'Zero-Sum Ka Zehar: Jab reward ek hi team ko milna ho toh sahyog khatam ho jata hai',
      'Superordinate Goals: Shared problem hi purani dushmani ko mita sakti hai',
      'Silos Ko Todo: Sales aur Engineering ko common metric par evaluate karo',
      'Contact Hypothesis Incomplete: Sirf saath baithakar pizza khilane se dushmani khatam nahi hoti',
    ] as [string, string, string, string],

    hiTitle: 'यथार्थवादी समूह संघर्ष सिद्धांत (Realistic Conflict Theory): संसाधनों की कमी और अंतर-समूह शत्रुता',
    hiSummary: 'यह सिद्धांत स्पष्ट करता है कि जब दो समूह सीमित और शून्य-योग (zero-sum) संसाधनों के लिए प्रतिस्पर्धा करते हैं, तो पूर्वाग्रह और शत्रुता स्वतः भड़क उठती है; इसे केवल साझा लक्ष्यों (superordinate goals) से ही शांत किया जा सकता है।',
    hiTakeaways: ['संसाधन प्रतिस्पर्धा से शत्रुता का जन्म', 'साझा लक्ष्यों (Superordinate Goals) का उपचारात्मक प्रभाव', 'शून्य-योग मूल्यांकन प्रणालियों के खतरे'] as [string, string, string],
    guTitle: 'રિયાલિસ્ટિક કોન્ફ્લિક્ટ થિયરી: સંસાધનોની તંગી અને જૂથ વચ્ચેનો વિવાદ',
    guSummary: 'જ્યારે બે જૂથો મર્યાદિત સંસાધનો માટે લડે છે ત્યારે અંદરોઅંદર પૂર્વગ્રહ વધે છે, જેને માત્ર એક સહિયારા મોટા લક્ષ્ય દ્વારા જ ઉકેલી શકાય છે.',
    mrTitle: 'रिअॅलिस्टिक कॉन्फ्लिक्ट थिअरी: संसाधनांची टंचाई आणि गटांमधील संघर्ष',
    mrSummary: 'जेव्हा मर्यादित फायद्यांसाठी दोन गटांमध्ये स्पर्धा लावली जाते, तेव्हा द्वेष वाढतो; मात्र जेव्हा एखादी सामायिक समस्या येते, तेव्हाच ते एकत्र येतात.',
    teTitle: 'రియలిస్టిక్ కాన్ఫ్లిక్ట్ థియరీ: వనరుల కొరత మరియు వర్గాల మధ్య వైరం',
    teSummary: 'పరిమిత వనరుల కోసం పోటీ పడినప్పుడు గ్రూపుల మధ్య ద్వేషం రగులుకుంటుంది; దీనిని పరిష్కరించడానికి ఉమ్మడి సమస్యను అధిగమించే లక్ష్యం అవసరం.',
    taTitle: 'எதார்த்த மோதல் கோட்பாடு: வளப் பற்றாக்குறையும் குழுக்களுக்கிடையேயான பகையும்',
    taSummary: 'வரையறுக்கப்பட்ட வளங்களுக்காக இரு குழுக்கள் போட்டியிடும் போது பகையுணர்வு வெடிக்கிறது; ஒரு பொதுவான பெரும் இலக்கினால் மட்டுமே ஒற்றுமை ஏற்படும்.',
    knTitle: 'ರಿಯಲಿಸ್ಟಿಕ್ ಕಾನ್ಫ್ಲಿಕ್ಟ್ ಥಿಯರಿ: ಸಂಪನ್ಮೂಲಗಳ ಕೊರತೆ ಮತ್ತು ಗುಂಪುಗಳ ನಡುವಿನ ವೈಷಮ್ಯ',
    knSummary: 'ಸೀಮಿತ ಸಂಪನ್ಮೂಲಗಳಿಗಾಗಿ ಪೈಪೋಟಿ ನಡೆದಾಗ ಗುಂಪುಗಳಲ್ಲಿ ಪರಸ್ಪರ ದ್ವೇಷ ಉಂಟಾಗುತ್ತದೆ; ಇದನ್ನು ಸಾಮಾನ್ಯ ಸವಾಲುಗಳನ್ನು ಒಟ್ಟಾಗಿ ಎದುರಿಸುವ ಮೂಲಕವೇ ಸರಿಪಡಿಸಬಹುದು.',
    mlTitle: 'റിയലിസ്റ്റിക് കോൺഫ്ലിക്റ്റ് തിയറി: വിഭവ ദൗർലഭ്യവും ഗ്രൂപ്പുകൾ തമ്മിലുള്ള ശത്രുതയും',
    mlSummary: 'പരിമിതമായ വിഭവങ്ങൾക്കായി ഗ്രൂപ്പുകൾ മത്സരിക്കുമ്പോൾ ശത്രുത ഉടലെടുക്കുന്നു; ഒരു വലിയ പൊതു ലക്ഷ്യത്തിലൂടെ മാത്രമേ ഈ അകൽച്ച ഇല്ലാതാക്കാൻ കഴിയൂ.',
    bnTitle: 'রিয়্যালিস্টিক কনফ্লিক্ট থিওরি: সম্পদের অভাব এবং দলগত সংঘাত',
    bnSummary: 'সীমিত সুযোগের জন্য প্রতিযোগিতা শুরু হলে দলের মধ্যে হিংসা বাড়ে; কোনো যৌথ বড় সংকট মোকাবিলা করলেই কেবল এই শত্রুতা মেটে।',
    paTitle: 'ਰਿਅਲਿਸਟਿਕ ਕਨਫਲਿਕਟ ਥਿਊਰੀ: ਸੀਮਤ ਵਸੀਲਿਆਂ ਕਾਰਨ ਗਰੁੱਪਾਂ ਵਿੱਚ ਵੈਰ',
    paSummary: 'ਜਦੋਂ ਦੋ ਗਰੁੱਪ ਇੱਕੋ ਸੀਮਤ ਇਨਾਮ ਲਈ ਮੁਕਾਬਲਾ ਕਰਦੇ ਹਨ ਤਾਂ ਨਫ਼ਰਤ ਪੈਦਾ ਹੁੰਦੀ ਹੈ, ਜਿਸਨੂੰ ਸਿਰਫ਼ ਸਾਂਝੇ ਟੀਚੇ ਨਾਲ ਹੀ ਖਤਮ ਕੀਤਾ ਜਾ ਸਕਦਾ ਹੈ।',
    urTitle: 'حقیقی گروہی تنازع کا نظریہ: وسائل کی کمی اور باہمی عداوت',
    urSummary: 'جب دو گروہ محدود وسائل کے حصول کے لیے آمنے سامنے آتے ہیں تو نفرت بڑھتی ہے، جسے صرف مشترکہ مقصد کے تحت ختم کیا جا سکتا ہے۔',
    orTitle: 'ରିଅଲିଷ୍ଟିକ୍ କନଫ୍ଲିକ୍ଟ ଥିଓରୀ: ସୀମିତ ସମ୍ବଳ ଏବଂ ଗୋଷ୍ଠୀଗତ ଶତ୍ରୁତା',
    orSummary: 'ଯେତେବେଳେ ଦୁଇଟି ଦଳ ସୀମିତ ସମ୍ବଳ ପାଇଁ ପ୍ରତିଦ୍ୱନ୍ଦ୍ୱିତା କରନ୍ତି, ସେତେବେଳେ ବିବାଦ ଉପୁଜେ; ଏକ ମିଳିତ ବଡ଼ ଲକ୍ଷ୍ୟ ହିଁ ସେମାନଙ୍କୁ ଏକାଠି କରିପାରେ।',
    asTitle: 'ৰিয়েলিষ্টিক কনফ্লিক্ট থিয়ৰী: সম্পদৰ অভাৱ আৰু দলীয় সংঘাত',
    asSummary: 'সীমিত সুযোগৰ বাবে প্ৰতিযোগিতা হ’লে দলবোৰৰ মাজত শত্রুতা বাঢ়ে, যাক কেৱল যৌথ লক্ষ্যৰ দ্বাৰাহে দূৰ কৰিব পৰা যায়।',
  },

  // 18. Social Identity Theory
  {
    fileName: 'socialIdentityTheory.ts',
    varName: 'social_identity_theory',
    id: 'social_identity_theory',
    categoryId: 'social_psychology' as const,
    slug: 'social-identity-theory',
    difficulty: 'intermediate' as const,
    readTime: 6,
    sortWeight: 18,
    titleEn: 'Social Identity Theory: Self-Worth Through Group Belonging',
    subtitleEn: 'How identifying with social categories shapes self-esteem, driving in-group favoritism and out-group derogation even on arbitrary grounds.',
    shortDescEn: 'A theory proposing that a person\'s sense of who they are is based on their group memberships, creating a cognitive imperative to elevate the in-group.',
    oneLineEn: 'We don\'t just belong to a group; our self-esteem becomes hostage to our team\'s status.',
    summary30sEn: 'Formulated in 1979 by Henri Tajfel and John Turner, Social Identity Theory explains why human beings passionately defend their sports teams, alma maters, and political tribes. Part of our self-worth is derived from the social categories we belong to. Consequently, making our "in-group" look superior makes us feel personally accomplished, while belittling the "out-group" protects our ego.',
    coreConceptEn: 'Tajfel demonstrated the Minimal Group Paradigm: even when test subjects are divided into groups based on completely trivial criteria (like guessing the number of dots on a screen or flipping a coin), they immediately discriminate against out-group members, distributing more money to anonymous in-group peers while sacrificing total collective profit just to maximize the gap between the two groups.',
    summary60sEn: 'Social identity operates through three cognitive stages: (1) Social Categorization (labeling people into us vs. them); (2) Social Identification (absorbing the norms, badges, and pride of the chosen tribe); (3) Social Comparison (comparing our group against rivals to ensure perceived dominance). This explains why fans feel personal euphoria when their team wins a championship without having played a single minute.',
    takeawaysEn: [
      'The Basking in Reflected Glory (BIRGing) Effect: We wear our team\'s jersey when they win to absorb social status',
      'The Minimal Group Trap: Arbitrary labels (e.g., Mac vs. PC, frontend vs. backend) trigger instinctive bias in minutes',
      'Ego-Driven Tribalism: Belittling another group is often an unconscious attempt to bolster fragile self-esteem',
      'Decoupling Self-Worth: Build an internal locus of identity rather than outsourcing pride to corporate or political badges',
    ] as [string, string, string, string],
    whyItHappensEn: 'Self-esteem maintenance and cognitive efficiency. Affiliating with high-status groups provides ready-made dignity, belonging, and social safety.',
    evolutionaryEn: 'Survival in ancestral hunter-gatherer bands depended 100% on intense in-group cohesion and hyper-vigilance against unfamiliar nomadic outsiders.',
    howItWorksEn: 'Category assigned -> Identity internalized -> Group victory becomes personal victory -> In-group favoritism emerges -> Out-group is devalued to maintain relative status superiority.',
    whereEn: 'Cricket fan wars (CSK vs. MI), smartphone fanboys (Apple vs. Android), college rivalries (IIT vs. BITS), and corporate brand loyalty.',
    headlineEn: 'Individual Merits vs. Reflected Tribal Glory',
    sideALabelEn: 'Tribal Identity Fusion',
    sideADetailEn: '"We crushed their team 4-0! Our city is fundamentally superior to their pathetic town."',
    sideBLabelEn: 'Objective Individuality',
    sideBDetailEn: '"Eleven professional athletes won a sporting match; my personal competence and life remain entirely unchanged."',
    researchSummaryEn: 'Tajfel & Turner (1979) established Social Identity Theory in "An Integrative Theory of Intergroup Conflict," proving that group categorization alone suffices to trigger bias.',
    scenarioTitleEn: 'The College Tech-Fest Tribalism in Delhi',
    scenarioVignetteEn: 'Kabir is a second-year engineering student in Delhi. At an inter-college robotics competition, students from his college wear matching navy hoodies and chant insults whenever the rival college\'s robot steps onto the arena. When Kabir\'s robot wins, Kabir feels a rush of supreme intellectual pride, shouting: "We proved our college has the greatest engineers in northern India!" In reality, Kabir only watched from the bleachers and didn\'t write a single line of the robot\'s code.',
    scenarioBreakdownEn: 'Tajfel\'s Social Identity Theory in action. Kabir underwent Social Categorization and Social Identification, experiencing "Basking in Reflected Glory" (BIRGing) to elevate his personal self-esteem.',
    scenarioActionEn: 'Recognize when your emotional highs and lows are being outsourced to external group symbols; anchor your self-worth on tangible personal contributions.',
    pqContextEn: 'A company randomly divides 100 new management trainees into "Alpha Pod" and "Beta Pod" using a colored lanyard lottery on day one. By week three, Alpha trainees openly mock Beta trainees in the cafeteria and refuse to share lunch tables.',
    pqPromptEn: 'Which empirical finding from Tajfel\'s Minimal Group Paradigm explains this rapid onset of tribal animosity?',
    pqOptA: 'Group hostility only develops after decades of economic resource inequality',
    pqOptB: 'Merely categorizing humans into arbitrary distinct groups is sufficient to trigger in-group favoritism and out-group derogation',
    pqOptC: 'The trainees were experiencing severe cognitive dissonance regarding their salaries',
    pqOptD: 'Social loafing caused the Beta Pod to lose motivation',
    pqCorrect: 'opt_b' as const,
    pqExplanation: 'Tajfel proved that arbitrary categorization alone—with no prior history, competition, or interaction—sparks immediate in-group favoritism and tribal discrimination.',
    pqTakeaway: 'Be vigilant when identifying with labels: the human brain can turn a colored lanyard into an ideological crusade in days.',
    authorYear: 'Henri Tajfel & John Turner (1979)',
    refTitle: 'An Integrative Theory of Intergroup Conflict',
    refCitation: 'Tajfel, H., & Turner, J. C. (1979). An integrative theory of intergroup conflict. The Social Psychology of Intergroup Relations, 33(47), 74.',
    doi: '10.1002/ejsp.2420010202',
    relatedA: { topicId: 'ingroup_outgroup_bias', slug: 'ingroup-outgroup-bias', title: 'Ingroup-Outgroup Bias' },
    relatedB: { topicId: 'realistic_conflict_theory', slug: 'realistic-conflict-theory', title: 'Realistic Conflict Theory' },

    titleHinglish: 'Social Identity Theory: Group Se Judkar Apni Value Badhana',
    subtitleHinglish: 'Hum kisi college, cricket team ya company se judkar uski jeet ko apni personal jeet samajhne lagte hain.',
    shortDescHinglish: 'Ek aisi psychological theory jisme insaan ka aatmavishwas uske group ki status par depend karta hai, jisse out-group ke prati nafrat paida hoti hai.',
    oneLineHinglish: 'Jab team jeet-ti hai toh hum kehte hain "Hum jeet gaye", aur jab haarti hai toh "Wo haar gaye".',
    summary30sHinglish: '1979 me Henri Tajfel ne Social Identity Theory di. Insaan ko apna samman badhana hota hai, isliye wo kisi group ka hissa banta hai—jaise IITian, Royal Challengers Bengaluru fan, ya Apple user. Jab hamara group accha perform karta hai, toh hume lagta hai ki hum personally superior hain, aur hum doosre groups ko neecha dikhane lagte hain.',
    coreConceptHinglish: 'Tajfel ke experiment me logo ko bas coin flip karke do groups me baant diya gaya. Sirf itne se arbitrary division se logo ne apne group walo ko zyada paise diye aur doosre group ko discriminate kiya. Isse pata chalta hai ki tribal thinking hamare dimaag me kitni gehri hai.',
    takeawaysHinglish: [
      'BIRGing Effect: Team ki jeet par garv mehsoos karna bina kisi mehnat ke',
      'Minimal Group Bias: Sirf ek alag badge lagane se log doosro ko dushman maan lete hain',
      'True Self-Worth: Apni pehchaan apne kaam se banayein, kisi brand ya group ke naam par nahi',
      'Tribal Trap: "Us vs Them" ki baatein sunte hi satark ho jayein',
    ] as [string, string, string, string],

    hiTitle: 'सामाजिक पहचान सिद्धांत (Social Identity Theory): समूह से आत्मसम्मान का निर्माण',
    hiSummary: 'यह सिद्धांत बताता है कि व्यक्ति का आत्म-सम्मान उसके समूह (जाति, कॉलेज, खेल टीम, धर्म) की स्थिति से गहराई से जुड़ा होता है, जिससे अपने समूह के प्रति पक्षपात और बाहरी समूह के प्रति उपेक्षा जन्म लेती है।',
    hiTakeaways: ['समूह के माध्यम से आत्मसम्मान की खोज (BIRGing)', 'न्यूनतम समूह प्रतिमान (Minimal Group Paradigm)', 'पहचान के आधार पर पक्षपात की पहचान'] as [string, string, string],
    guTitle: 'સોશિયલ આઇડેન્ટિટી થિયરી: જૂથના આધારે આત્મસન્માન ઊભું કરવું',
    guSummary: 'જ્યારે વ્યક્તિ પોતાની કિંમત પોતાની ટીમ કે સંસ્થાની સ્થિતિ સાથે જોડી દે છે, જેનાથી પોતાના જૂથ પ્રત્યે પક્ષપાત અને અન્ય જૂથ પ્રત્યે પૂર્વગ્રહ વધે છે.',
    mrTitle: 'सोशल आयडेंटिटी थिअरी: गटाच्या माध्यमातून आत्मसन्मान मिळवणे',
    mrSummary: 'आपला स्वाभिमान आपण ज्या गटात (कॉलेज, संघ, जात) आहोत त्याच्या यशावर अवलंबून ठेवणे आणि इतर गटांना तुच्छ लेखण्याची प्रवृत्ती.',
    teTitle: 'సోషల్ ఐడెంటిటీ థియరీ: సమూహం ద్వారా ఆత్మగౌరవాన్ని పొందడం',
    teSummary: 'వ్యక్తి తన గుర్తింపును మరియు ఆత్మగౌరవాన్ని తను ఉన్న గ్రూపుతో ముడిపెట్టి, ఇతర గ్రూపులను చిన్నచూపు చూసే మానసిక ప్రవర్తన.',
    taTitle: 'சமூக அடையாளக் கோட்பாடு: குழுவின் மூலம் சுயமரியாதையை தேடுதல்',
    taSummary: 'ஒருவர் தனது சுயமரியாதையை தான் சார்ந்த குழுவின் வெற்றியோடு இணைத்துக்கொண்டு, பிற குழுக்களை இழிவாகக் கருதும் உளவியல் போக்கு.',
    knTitle: 'ಸೋಷಿಯಲ್ ಐಡೆಂಟಿಟಿ ಥಿಯರಿ: ಗುಂಪಿನ ಮೂಲಕ ಸ್ವಾಭಿಮಾನವನ್ನು ಕಂಡುಕೊಳ್ಳುವುದು',
    knSummary: 'ವ್ಯಕ್ತಿಯು ತನ್ನ ಸ್ವಾಭಿಮಾನವನ್ನು ತನ್ನ ತಂಡ ಅಥವಾ ಜಾತಿ/ಧರ್ಮದ ಯಶಸ್ಸಿನೊಂದಿಗೆ ಜೋಡಿಸಿಕೊಂಡು, ಇತರ ಗುಂపుಗಳನ್ನು ಕೀಳಾಗಿ ಕಾಣುವ ಪ್ರವೃತ್ತಿ.',
    mlTitle: 'സോഷ്യൽ ഐഡന്റിറ്റി തിയറി: ഗ്രൂപ്പിലൂടെ ആത്മാഭിമാനം കണ്ടെത്തൽ',
    mlSummary: 'നമ്മുടെ സ്വന്തം മൂല്യം നാം ഉൾപ്പെടുന്ന കൂട്ടായ്മയുടെ വിജയവുമായി ബന്ധിപ്പിക്കുകയും മറ്റ് ഗ്രൂപ്പുകളെ താഴ്ത്തിക്കെട്ടുകയും ചെയ്യുന്ന സ്വഭാവം.',
    bnTitle: 'সোশ্যাল আইডেন্টিটি থিওরি: দলের মাধ্যমে আত্মমর্যাদা বৃদ্ধির মোহ',
    bnSummary: 'নিজের পরিচয় ও সম্মান কোনো বিশেষ গোষ্ঠীর সাথে জুড়ে দিয়ে অন্য দলকে হেয় প্রতিপন্ন করার প্রাচীন সামাজিক মানসিকতা।',
    paTitle: 'ਸੋਸ਼ਲ ਆਈਡੈਂਟਿਟੀ ਥਿਊਰੀ: ਗਰੁੱਪ ਰਾਹੀਂ ਸਵੈ-ਮਾਣ ਬਣਾਉਣਾ',
    paSummary: 'ਆਪਣੀ ਇੱਜ਼ਤ ਨੂੰ ਆਪਣੀ ਟੀਮ ਜਾਂ ਸੰਸਥਾ ਦੀ ਸਫਲਤਾ ਨਾਲ ਜੋੜ ਕੇ ਦੂਜੇ ਗਰੁੱਪਾਂ ਨੂੰ ਨੀਵਾਂ ਦਿਖਾਉਣ ਦੀ ਮਨੋਵਿਗਿਆਨਕ ਆਦਤ।',
    urTitle: 'سماجی شناخت کا نظریہ: گروہ کی کامیابی سے عزت نفس کشید کرنا',
    urSummary: 'اپنی عزت نفس کو کسی خاص گروہ کی کامیابی سے وابستہ کر لینا اور دوسرے گروہوں کو حقارت کی نگاہ سے دیکھنا۔',
    orTitle: 'ସୋସିଆଲ୍ ଆଇଡେଣ୍ଟିଟି ଥିଓରୀ: ଗୋଷ୍ଠୀ ମାଧ୍ୟମରେ ଆତ୍ମସମ୍ମାନ ହାସଲ',
    orSummary: 'ବ୍ୟକ୍ତି ନିଜର ମୂଲ୍ୟ ନିଜ ଦଳ ବା ସଙ୍ଗଠନର ସଫଳତା ସହ ଯୋଡ଼ି ଅନ୍ୟ ଗୋଷ୍ଠୀକୁ ହେୟଜ୍ଞାନ କରିବାର ସାମାଜିକ ପ୍ରବୃତ୍ତି।',
    asTitle: 'ছচিয়েল আইডেণ্টিটি থিয়ৰী: দলৰ জৰিয়তে আত্মসন্মান প্ৰতিষ্ঠাৰ প্ৰয়াস',
    asSummary: 'নিজৰ সন্মান কোনো দল বা সংঘৰ সফলতাৰ লগত সাঙুৰি আন দলক উপলুঙা কৰাৰ মনস্তাত্ত্বিক প্ৰৱণতা।',
  },

  // 19. Normative vs. Informational Social Influence
  {
    fileName: 'normativeInformationalInfluence.ts',
    varName: 'normative_informational_influence',
    id: 'normative_informational_influence',
    categoryId: 'social_psychology' as const,
    slug: 'normative-informational-influence',
    difficulty: 'intermediate' as const,
    readTime: 6,
    sortWeight: 19,
    titleEn: 'Normative vs. Informational Social Influence: Fitting In vs. Being Right',
    subtitleEn: 'Distinguishing between conforming to gain social approval (normative) versus conforming because you trust others\' knowledge (informational).',
    shortDescEn: 'The two foundational social forces governing conformity: the desire to be liked and accepted versus the desire to be accurate and correct.',
    oneLineEn: 'Normative influence is going along to get along; informational influence is following the crowd because you don\'t know the way.',
    summary30sEn: 'Disentangled in 1955 by Morton Deutsch and Harold Gerard, conformity is split into two completely distinct cognitive pathways. Normative Social Influence occurs when you know the crowd is wrong, but you conform anyway to avoid social rejection or awkwardness. Informational Social Influence occurs when reality is ambiguous, and you genuinely assume the crowd has superior knowledge.',
    coreConceptEn: 'Understanding the split is critical for intellectual sovereignty. Normative conformity changes overt public compliance without changing private belief (e.g., clapping for a boring speech). Informational conformity causes true private acceptance and cognitive internalization (e.g., following locals during an earthquake evacuation because you assume they know the safest exit route).',
    summary60sEn: 'Deutsch and Gerard modified Solomon Asch\'s line experiment. When participants gave their line judgments in private without social exposure, conformity dropped by more than 50%—proving that the majority of Asch\'s original conformity was normative (fear of standing out), rather than informational (genuine perceptual confusion). When stakes are high and accuracy is incentivized, normative conformity collapses, but informational conformity rises if uncertainty remains.',
    takeawaysEn: [
      'The Two Conformity Engines: Ask yourself: "Am I doing this to be liked, or because I believe they know better?"',
      'Public Compliance vs. Private Acceptance: Normative influence shapes polite words; informational influence rewires your world model',
      'The Ambiguity Vulnerability: In unfamiliar environments (new jobs, new cities), informational influence makes you mimic anyone with confidence',
      'The Fear of Rejection Shield: Train yourself to endure 10 seconds of awkwardness rather than endorse a disastrous consensus',
    ] as [string, string, string, string],
    whyItHappensEn: 'Dual human evolutionary imperatives: (1) The need to belong to avoid tribal exile; (2) The need to acquire accurate navigational data about the environment.',
    evolutionaryEn: 'Ostracism from ancestral hunter bands meant certain starvation; simultaneously, copying tribal elders\' foraging routes saved calories and prevented poisoning.',
    howItWorksEn: 'Social situation encountered -> Check ambiguity level -> If high ambiguity, use Informational route (trust crowd data) -> If low ambiguity but high social scrutiny, use Normative route (comply to avoid rejection).',
    whereEn: 'Office dress codes, clapping at conferences, investing in trending meme stocks, fine dining etiquette, and voting behavior.',
    headlineEn: 'Fear of Disapproval vs. Quest for Accuracy',
    sideALabelEn: 'Normative Influence (Compliance)',
    sideADetailEn: '"I know this slide deck has false metrics, but challenging the VP right now will get me branded as non-collaborative."',
    sideBLabelEn: 'Informational Influence (Acceptance)',
    sideBDetailEn: '"I have never visited this Mumbai metro interchange before; everyone is running toward Platform 3, so that must be the correct train."',
    researchSummaryEn: 'Deutsch & Gerard (1955) published "A study of normative and informational social influences upon individual judgment," establishing modern conformity taxonomy.',
    scenarioTitleEn: 'The Startup Pitch Meeting in Indiranagar',
    scenarioVignetteEn: 'Aarav joins a hot Bangalore artificial intelligence startup as a junior product designer. During a design sprint, the charismatic CEO proposes a user onboarding flow that requires users to upload their Aadhaar card before seeing the homepage. Aarav immediately recognizes this will cause an 80% drop-off rate and violates basic UX principles. However, all three senior directors nod and say: "Brilliant, this demonstrates trust." Aarav remains silent and votes in favor. At night, he texts his friend: "The idea is terrible, but I didn\'t want to look like a troublemaker on day 4."',
    scenarioBreakdownEn: 'Pure Normative Social Influence. Aarav had zero informational doubt (he knew the UX science), but succumbed to normative pressure to preserve social capital and avoid being ostracized.',
    scenarioActionEn: 'Implement anonymous voting mechanisms or designated "Devil\'s Advocate" roles in product reviews to neutralize normative social pressure.',
    pqContextEn: 'An American tourist and a local resident are dining at a traditional thali restaurant in Varanasi. The tourist watches the surrounding 20 diners eat with their right hand and immediately adopts the practice, believing it is the hygienically and culturally proper method.',
    pqPromptEn: 'Which type of social influence did the tourist experience, and what was the internal cognitive outcome?',
    pqOptA: 'Normative influence resulting in superficial public compliance without belief',
    pqOptB: 'Informational social influence resulting in genuine private acceptance of correct behavior',
    pqOptC: 'Diffusion of responsibility leading to ethical lapse',
    pqOptD: 'Psychological reactance driving rebellion against cultural norms',
    pqCorrect: 'opt_b' as const,
    pqExplanation: 'The tourist faced an ambiguous situation, looked to others as a credible source of accurate information, and internalized the behavior (informational influence with private acceptance).',
    pqTakeaway: 'Distinguish between learning from others (informational) and cowardly surrendering your judgment (normative).',
    authorYear: 'Morton Deutsch & Harold B. Gerard (1955)',
    refTitle: 'A study of normative and informational social influences upon individual judgment',
    refCitation: 'Deutsch, M., & Gerard, H. B. (1955). Journal of Abnormal and Social Psychology, 51(3), 629–636.',
    doi: '10.1037/h0046408',
    relatedA: { topicId: 'conformity_asch_effect', slug: 'conformity-asch-effect', title: 'Conformity (Asch Effect)' },
    relatedB: { topicId: 'pluralistic_ignorance', slug: 'pluralistic-ignorance', title: 'Pluralistic Ignorance' },

    titleHinglish: 'Normative vs Informational Influence: Logo Ki Pasand Banna Ya Sahi Hona',
    subtitleHinglish: 'Kuch baatein hum isliye maante hain kyunki hume logo se validation chahiye (Normative), aur kuch isliye kyunki hume lagta hai unhe sach pata hai (Informational).',
    shortDescHinglish: 'Samajik prabhav ke do mukhya roop: ek jisme hum dosti banaye rakhne ke liye haan me haan milate hain, aur doosra jisme hum bheed ki samajh par bharosa karte hain.',
    oneLineHinglish: 'Normative matlab rejection se bachna; Informational matlab anjaan raste par bheed ke peeche chalna.',
    summary30sHinglish: '1955 me Deutsch aur Gerard ne bataya ki log do alag-alag wajah se bheed ki baat maante hain. Pehla hai Normative Influence—jab aapko pata hota hai ki bheed galat hai, par aap akele alag nahi dikhna chahte isliye haan keh dete hain. Doosra hai Informational Influence—jab aapko khud koi jaankari nahi hoti aur aap sochte hain ki bheed ko sab pata hoga.',
    coreConceptHinglish: 'Office meetings me jab sab boss ki bekaar baat par taali bajate hain, wo Normative influence hai. Par jab nayi city me jaakar aap sabse bheed wali chaat ki dukaan par khade hote hain, wo Informational influence hai.',
    takeawaysHinglish: [
      'Khud Se Puchhein: "Kya main darr ke maare haan bol raha hoon ya sach me yeh sahi hai?"',
      'Validation vs Reality: Rejection ke darr se apni sahi baat ko chupana band karein',
      'Unfamiliar Territory: Nayi jagah par informational influence ka asar sabse zyada hota hai',
      'Psychological Safety: Teams me anonymous feedback rakhne se normative pressure khatam hota hai',
    ] as [string, string, string, string],

    hiTitle: 'मानक बनाम सूचनात्मक सामाजिक प्रभाव (Normative vs. Informational Social Influence)',
    hiSummary: 'अनुरूपता के दो मूलभूत स्रोत: अस्वीकृति के डर से केवल समूह में फिट होने के लिए सहमत होना (मानक प्रभाव) बनाम दूसरों के ज्ञान को अधिक सटीक मानकर उसका अनुसरण करना (सूचनात्मक प्रभाव)।',
    hiTakeaways: ['स्वीकृति की इच्छा बनाम सत्य की खोज', 'सार्वजनिक सहमति और आंतरिक विश्वास का अंतर', 'सामाजिक दबाव में स्वतंत्र सोच का संरक्षण'] as [string, string, string],
    guTitle: 'નોર્મેટિવ વિ. ઇન્ફોર્મેશનલ સોશિયલ ઇન્ફ્લુઅન્સ: સ્વીકૃતિ કે સત્યની શોધ',
    guSummary: 'જૂથમાં ભળવા માટે સંમત થવું (નોર્મેટિવ) અને લોકો પાસે સાચી માહિતી છે એમ માનીને તેમનું અનુકરણ કરવું (ઇન્ફોર્મેશનલ) વચ્ચેનો મનોવૈજ્ઞાનિક તફાવત.',
    mrTitle: 'नॉर्मेटिव्ह विरुद्ध इन्फॉर्मेशनल प्रभाव: गटात सामावून घेणे की सत्य शोधणे',
    mrSummary: 'लोकांच्या पसंतीस उतरायचे म्हणून होकार देणे (नॉर्मेटिव्ह) आणि लोकांना जास्त माहिती आहे असे समजून त्यांचे अनुकरण करणे (इन्फॉर्मेशनल) यातील फरक.',
    teTitle: 'నార్మేటివ్ వర్సెస్ ఇన్ఫర్మేషనల్ సోషల్ ఇన్‌ఫ్లుయెన్స్: మెప్పు కోసమా లేక సత్యం కోసమా',
    teSummary: 'ఇతరుల ఆమోదం పొందడం కోసం అంగీకరించడం (నార్మేటివ్) మరియు ఇతరుల వద్ద సరైన సమాచారం ఉందని నమ్మి అనుసరించడం (ఇన్ఫర్మేషనల్) మధ్య తేడా.',
    taTitle: 'நெறிமுறை மற்றும் தகவல் சமூக செல்வாக்கு: ஏற்புக்காகவா அல்லது உண்மைக்காகவா',
    taSummary: 'மற்றவர்களின் ஏற்பைப் பெறுவதற்காக இணங்கிப்போதல் (நெறிமுறை) மற்றும் மற்றவர்களுக்கு அதிகம் தெரியும் என நம்பிப் பின்பற்றுதல் (தகவல்) இடையேயான வேறுபாடு.',
    knTitle: 'ನಾರ್ಮೇಟಿವ್ ವರ್ಸಸ್ ಇನ್ಫಾರ್ಮೇಷನಲ್ ಪ್ರಭಾವ: ಒಪ್ಪಿಗೆಗಾಗಿ ಅಥವಾ ಸತ್ಯಕ್ಕಾಗಿ',
    knSummary: 'ಇತರರ ಮೆಚ್ಚುಗೆಗಾಗಿ ಒಪ್ಪಿಕೊಳ್ಳುವುದು (ನಾರ್ಮೇಟಿವ್) ಮತ್ತು ಇತರರಿಗೆ ಹೆಚ್ಚು ತಿಳಿದಿದೆ ಎಂದು ಭಾವಿಸಿ ಅನುಸರಿಸುವುದು (ಇನ್ಫಾರ್ಮೇಷನಲ್) ನಡುವಿನ ವ್ಯತ್ಯಾಸ.',
    mlTitle: 'നോർമേറ്റീവ് വേഴ്സസ് ഇൻഫർമേഷണൽ സോഷ്യൽ ഇൻഫ്ലുവൻസ്: സ്വീകാര്യതയോ സത്യമോ',
    mlSummary: 'മറ്റുള്ളവരുടെ അംഗീകാരം നേടാനായി വഴങ്ങുന്നതും (നോർമേറ്റീവ്) മറ്റുള്ളവർക്ക് കൂടുതൽ അറിയാമെന്ന് കരുതി അനുസരിക്കുന്നതും (ഇൻഫർമേഷണൽ) തമ്മിലുള്ള അന്തരം.',
    bnTitle: 'নর্মেটিভ বনাম ইনফরমেশনাল সামাজিক প্রভাব: গ্রহণযোগ্যতা নাকি সত্যের অনুসন্ধান',
    bnSummary: 'দলের অংশ হতে ভুল জেনেও সম্মতি দেওয়া (নর্মেটিভ) এবং সঠিক পথ জানার জন্য ভিড়ের ভরসায় চলা (ইনফরমেশনাল)—এই দুই প্রভাবের পার্থক্য।',
    paTitle: 'ਨੋਰਮੇਟਿਵ ਬਨਾਮ ਇਨਫਾਰਮੇਸ਼ਨਲ ਪ੍ਰਭਾਵ: ਸਵੀਕ੍ਰਿਤੀ ਜਾਂ ਸੱਚ ਦੀ ਭਾਲ',
    paSummary: 'ਲੋਕਾਂ ਵਿੱਚ ਫਿੱਟ ਹੋਣ ਲਈ ਹਾਮੀ ਭਰਨਾ (ਨੋਰਮੇਟਿਵ) ਅਤੇ ਦੂਜਿਆਂ ਨੂੰ ਵੱਧ ਗਿਆਨਵਾਨ ਸਮਝ ਕੇ ਉਹਨਾਂ ਦਾ ਪਿੱਛਾ ਕਰਨਾ (ਇਨਫਾਰਮੇਸ਼ਨਲ) ਦੇ ਵਿਚਕਾਰ ਅੰਤਰ।',
    urTitle: 'معیاری بمقابلہ معلوماتی سماجی اثر: منظوری کی خواہش یا حق کی تلاش',
    urSummary: 'لوگوں میں شامل ہونے کے لیے سر ہلا دینا (معیاری) اور دوسروں کو زیادہ باخبر سمجھ کر ان کی تقلید کرنا (معلوماتی) کے درمیان فرق۔',
    orTitle: 'ନର୍ମେଟିଭ୍ ବନାମ ଇନଫରମେସନାଲ୍ ସାମାଜିକ ପ୍ରଭାବ: ଗ୍ରହଣୀୟତା ନା ସତ୍ୟର ସନ୍ଧାନ',
    orSummary: 'ଅନ୍ୟମାନଙ୍କ ପସନ୍ଦ ହେବା ପାଇଁ ସହମତ ହେବା (ନର୍ମେଟିଭ୍) ଏବଂ ଲୋକଙ୍କ ପାଖରେ ସଠିକ୍ ତଥ୍ୟ ଅଛି ଭାବି ଅନୁକରଣ କରିବା (ଇନଫରମେସନାଲ୍) ମଧ୍ୟରେ ପାର୍ଥକ୍ୟ।',
    asTitle: 'নৰ্মেটিভ বনাম ইনফৰ্মেচনেল সামাজিক প্ৰভাৱ: সন্মতি নে সত্যৰ সন্ধান',
    asSummary: 'দলত স্থান পাবলৈ সন্মতি প্ৰকাশ কৰা (নৰ্মেটিভ) আৰু আনৰ জ্ঞানক শ্ৰেষ্ঠ বুলি ভাবি অনুসৰণ কৰা (ইনফৰ্মেচনেল)ৰ মাজৰ মনোবৈজ্ঞানিক পাৰ্থক্য।',
  },

  // 20. Illusion of Transparency
  {
    fileName: 'illusionOfTransparency.ts',
    varName: 'illusion_of_transparency',
    id: 'illusion_of_transparency',
    categoryId: 'social_psychology' as const,
    slug: 'illusion-of-transparency',
    difficulty: 'beginner' as const,
    readTime: 5,
    sortWeight: 20,
    titleEn: 'The Illusion of Transparency: Overestimating How Well Others Read You',
    subtitleEn: 'The tendency to overestimate the degree to which our internal mental, emotional, and nervous states leak out and are detected by observers.',
    shortDescEn: 'A cognitive bias where people overestimate others\' ability to know their internal mental state, believing their nervousness, lies, or feelings are obvious.',
    oneLineEn: 'You feel your heart pounding in your throat, but to the audience, you look as calm as still water.',
    summary30sEn: 'Discovered in 1998 by Thomas Gilovich, Kenneth Savitsky, and Victoria Medvec, the Illusion of Transparency explains why public speakers and negotiators suffer immense performance anxiety. Because we experience our own internal physiological sensations (sweaty palms, racing pulse, dry throat) so vividly, we mistakenly assume that external observers can see straight through our poker face.',
    coreConceptEn: 'The illusion operates through egocentric anchoring. We are acutely aware of our internal physiological arousal, so we anchor heavily on that visceral experience. When attempting to infer what observers see from the outside, we make an insufficient adjustment, drastically overestimating how much of our nervousness, deception, or disgust is broadcasting onto our face.',
    summary60sEn: 'In Cornell experiments, speakers were asked to rate how nervous they appeared to an audience, while audience members rated the speakers\' actual perceived nervousness. Speakers consistently predicted their terror was completely obvious, rating their visible anxiety at nearly double what the audience actually detected. In truth, audiences perceived the speakers as poised, confident, and professional.',
    takeawaysEn: [
      'The Opaque Shield: Your internal bodily sensations are virtually invisible to the external world',
      'The Public Speaking Antidote: Remembering that you look far calmer than you feel immediately lowers stage fright',
      'Lie-Detector Paranoia: Liars overestimate how guilty they look; honesty doesn\'t need to prove itself',
      'Communication Clarity: Don\'t assume your partner or manager knows you are frustrated—express it verbally',
    ] as [string, string, string, string],
    whyItHappensEn: 'Egocentric sensory anchoring. Internal visceral sensations (adrenalin, gut feelings) are so overwhelming that we assume they project outwardly like a billboard.',
    evolutionaryEn: 'Evolutionary benefit of rapid social signaling: in small groups, subtle facial cues signaled threats or emotions, leading humans to err on the side of assuming visibility.',
    howItWorksEn: 'Nervousness or secret felt internally -> Heart rate spikes -> Person anchors on physical sensations -> Assumes face is beaming the anxiety -> Over-apologizes or freezes -> Real audience saw nothing.',
    whereEn: 'Salary negotiations, first dates, public speeches, job interviews, and when telling white lies.',
    headlineEn: 'Felt Internal Chaos vs. Observed External Composure',
    sideALabelEn: 'Your Internal Sensation',
    sideADetailEn: '"My voice is trembling, my hands are shaking, and the board definitely knows I am having a panic attack."',
    sideBLabelEn: 'Audience Observation',
    sideBDetailEn: '"The presenter spoke clearly, maintained great posture, and delivered an exceptionally composed deck."',
    researchSummaryEn: 'Gilovich, Savitsky & Medvec (1998) published "The illusion of transparency: Biased assessments of others\' ability to read one\'s emotional states" in JPSP.',
    scenarioTitleEn: 'The High-Stakes Investor Pitch in Koramangala',
    scenarioVignetteEn: 'Priya is pitching her climate-tech startup to marquee venture capitalists in Bangalore. As she stands at the podium, her throat goes bone dry, her knees shake inside her trousers, and her heart hammers at 140 BPM. Priya is convinced the lead partner can see through her: "He knows I am terrified; they are going to reject our round because of my nervous breakdown!" Distracted by this fear, she rushes through her slides. Afterward, when she apologizes to the lead investor for being visibly shaking, the partner blinks in surprise: "Shaking? Priya, you were the most commanding, poised founder we\'ve seen all quarter. We\'re putting together a term sheet."',
    scenarioBreakdownEn: 'A textbook manifestation of the Illusion of Transparency. Priya anchored on her internal adrenaline storm and assumed it was broadcasting on her face, when in reality her external presentation was completely solid.',
    scenarioActionEn: 'Leverage the Savitsky Intervention: Before any speech, remind yourself: "Audience members cannot see my heartbeat. Even if I feel anxious, I appear calm and authoritative to them."',
    pqContextEn: 'A software engineer in Hyderabad attends his annual appraisal with his director to ask for a 30% raise. During the conversation, his stomach churns and he feels intensely awkward.',
    pqPromptEn: 'Applying the empirical research on the Illusion of Transparency, what should the engineer remind himself to stay grounded?',
    pqOptA: 'The director can accurately detect every micro-expression and pulse change',
    pqOptB: 'Internal physical discomfort does not project visibly; to the director, he appears composed and professional',
    pqOptC: 'He should confess his acute nausea immediately to gain sympathy',
    pqOptD: 'Social loafing will make the director ignore the raise request anyway',
    pqCorrect: 'opt_b' as const,
    pqExplanation: 'Research proves that internal nervous sensations are largely invisible to external observers; we drastically overestimate how transparent we are.',
    pqTakeaway: 'You look infinitely calmer than you feel: trust your external composure.',
    authorYear: 'Thomas Gilovich et al. (1998)',
    refTitle: 'The illusion of transparency: Biased assessments of others\' ability to read one\'s emotional states',
    refCitation: 'Gilovich, T., Savitsky, K., & Medvec, V. H. (1998). Journal of Personality and Social Psychology, 75(2), 332–346.',
    doi: '10.1037/0022-3514.75.2.332',
    relatedA: { topicId: 'spotlight_effect', slug: 'spotlight-effect', title: 'The Spotlight Effect' },
    relatedB: { topicId: 'social_facilitation', slug: 'social-facilitation', title: 'Social Facilitation' },

    titleHinglish: 'The Illusion of Transparency: Hum Kitne Transparent Hain Ka Bhram',
    subtitleHinglish: 'Presentation me andar se dil dhak-dhak kar raha hota hai, par samne walo ko lagta hai hum bilkul calm hain.',
    shortDescHinglish: 'Ek aisi soch jisme hume lagta hai ki hamari ghabrahat, jhooth ya darr samne wale ke saamne saaf-saaf dikh raha hai, jabki aisa bilkul nahi hota.',
    oneLineHinglish: 'Aapko lagta hai sab aapka darr padh sakte hain, jabki bahar se aap bilkul normal dikhte hain.',
    summary30sHinglish: '1998 me Gilovich ne Illusion of Transparency discover kiya. Jab hum stage par bolte hain ya salary negotiate karte hain, toh hamare gale me sookha pad jata hai aur haath kaanpne lagte hain. Hume lagta hai sabko hamari ghabrahat saaf dikh rahi hai. Sachai yeh hai ki log hamara dimaag ya heartbeat nahi padh sakte; bahar se hum bilkul confident nazar aate hain.',
    coreConceptHinglish: 'Hamari body ke andar jo adrenaline daudta hai, wo hume bohot tezi se mehsoos hota hai. Lekin chehre par uska 10% bhi nahi dikhta. Is baat ko yaad rakhne se public speaking ka darr aadha ho jata hai.',
    takeawaysHinglish: [
      'Poker Face Sach: Aap jitna nervous feel karte hain, uska 10% bhi samne nahi dikhta',
      'Stage Fright Ka Ilaj: Apne aap ko yaad dilayein: "Duniya meri heartbeat nahi dekh sakti"',
      'Clear Communication: Apne partner se expect mat karein ki wo bina bole aapka mood samajh jaye',
      'Fake It Till You Make It: Bahar se calm dikhna shuru karein, andar ka darr apne aap shaant ho jayega',
    ] as [string, string, string, string],

    hiTitle: 'पारदर्शिता का भ्रम (Illusion of Transparency): आंतरिक भावों के उजागर होने का भ्रम',
    hiSummary: 'यह अत्यधिक अनुमान लगाने की प्रवृत्ति कि हमारी आंतरिक घबराहट, भय, मनोदशा या झूठ दूसरों को स्पष्ट रूप से दिखाई दे रहे हैं, जबकि वास्तव में लोग हमारे चेहरे से इसे आसानी से नहीं पढ़ सकते।',
    hiTakeaways: ['आंतरिक घबराहट का अदृश्य होना', 'सार्वजनिक भाषण में आत्मविश्वास की रक्षा', 'स्पष्ट मौखिक संवाद का महत्व'] as [string, string, string],
    guTitle: 'ઇલ્યુઝન ઓફ ટ્રાન્સપરન્સી: આપણી નર્વસનેસ દેખાઈ આવે છે તેવો ભ્રમ',
    guSummary: 'સ્ટેજ પર બોલતી વખતે કે ઇન્ટરવ્યુમાં આપણી અંદરની ગભરામણ બહારના લોકોને સ્પષ્ટ દેખાઈ રહી છે તેવો ખોટો ડર.',
    mrTitle: 'इल्युजन ऑफ ट्रान्सपरन्सी: अंतर्गत भावना इतरांना स्पष्ट दिसतात हा गैरसमज',
    mrSummary: 'आपली भीती, अस्वस्थता किंवा खोटे बोलणे समोरच्याला सहज समजते हा निव्वळ भ्रम असतो; प्रत्यक्षात आपण शांतच दिसत असतो.',
    teTitle: 'ఇల్యూజన్ ఆఫ్ ట్రాన్స్‌పరెన్సీ: మన ఆందోళన అందరికీ తెలిసిపోతుందనే భ్రమ',
    teSummary: 'వేదికపై మాట్లాడేటప్పుడు మన గుండె చప్పుడు మరియు భయం ఇతరులకు స్పష్టంగా తెలిసిపోతోందని అతిగా భయపడే మానసిక స్థితి.',
    taTitle: 'வெளிப்படைத்தன்மையின் மாயை: நமது பதற்றம் வெளியில் தெரிகிறது என்ற அச்சம்',
    taSummary: 'நமது உள்மனப் பயமும் படபடப்பும் மற்றவர்களுக்கு அப்பட்டமாகத் தெரிகிறது என்று நாம் தவறாகக் கருதி அஞ்சுவது.',
    knTitle: 'ಇಲ್ಯೂಷನ್ ಆಫ್ ಟ್ರಾನ್ಸ್‌ಪರೆನ್ಸಿ: ನಮ್ಮ ಆತಂಕ ಎಲ್ಲರಿಗೂ ಕಾಣಿಸುತ್ತಿದೆ ಎಂಬ ಭ್ರಮೆ',
    knSummary: 'ನಮ್ಮ ಆಂತರಿಕ ನಡುಕ ಮತ್ತು ಭಯ ಇತರರಿಗೆ ಸ್ಪಷ್ಟವಾಗಿ ಗೋಚರಿಸುತ್ತದೆ ಎಂದು ಅತಿಯಾಗಿ ಯೋಚಿಸಿ ಗಾಬರಿಯಾಗುವ ಪ್ರವೃತ್ತಿ.',
    mlTitle: 'ഇല്യൂഷൻ ഓഫ് ട്രാൻസ്പരൻസി: നമ്മുടെ ഭയം മറ്റുള്ളവർ തിരിച്ചറിയുന്നു എന്ന മിഥ്യാധാരണ',
    mlSummary: 'നമ്മുടെ ഉള്ളിലെ പരിഭ്രാന്തിയും ടെൻഷനും മറ്റുള്ളവർക്ക് വ്യക്തമായി കാണാൻ കഴിയുമെന്ന് അനാവശ്യമായി ഭയപ്പെടുന്ന അവസ്ഥ.',
    bnTitle: 'ইল্যুশন অব ট্রান্সপারেন্সি: নিজের মানসিক অবস্থা প্রকাশ্যে ধরা পড়ার অমূলক ভয়',
    bnSummary: 'নিজের অভ্যন্তরীণ নার্ভাসনেস বা ভয় বাইরে থেকে সবাই সহজে বুঝতে পারছে ভেবে অহেতুক আতঙ্কিত হওয়ার মানসিক বিভ্রম।',
    paTitle: 'ਇਲਿਊਜ਼ਨ ਆਫ਼ ਟਰਾਂਸਪੇਰੈਂਸੀ: ਮੇਰੀ ਘਬਰਾਹਟ ਸਭ ਨੂੰ ਦਿਖ ਰਹੀ ਹੈ ਦਾ ਡਰ',
    paSummary: 'ਇਹ ਸੋਚ ਕੇ ਡਰਨਾ ਕਿ ਮੇਰੇ ਅੰਦਰਲਾ ਡਰ ਅਤੇ ਕੰਬਣੀ ਬਾਹਰ ਬੈਠੇ ਲੋਕਾਂ ਨੂੰ ਸਾਫ਼ ਦਿਖ ਰਹੀ ਹੈ, ਜਦਕਿ ਬਾਹਰੋਂ ਵਿਅਕਤੀ ਬਿਲਕੁਲ ਸ਼ਾਂਤ ਦਿਖਦਾ ਹੈ।',
    urTitle: 'شفافیت کا مغالطہ: اپنے اندرونی خوف کے عیاں ہونے کا وہم',
    urSummary: 'یہ سمجھنا کہ ہماری گھبراہٹ اور بے چینی سب پر واضح ہے، حالانکہ بیرونی مشاہدہ کار کے لیے ہم بالکل پُرسکون نظر آتے ہیں۔',
    orTitle: 'ଇଲ୍ୟୁଜନ୍ ଅଫ୍ ଟ୍ରାନ୍ସପରେନ୍ସି: ମନର ଡର ସମସ୍ତେ ଜାଣିପାରୁଛନ୍ତି ବୋଲି ଭ୍ରମ',
    orSummary: 'ଷ୍ଟେଜ୍ ଉପରେ ଥିବାବେଳେ ନିଜର ଆଭ୍ୟନ୍ତରୀଣ ଉତ୍ତେଜନା ଓ ଭୟ ବାହାର ଲୋକଙ୍କୁ ସ୍ପଷ୍ଟ ଦିଶୁଛି ବୋଲି ଭାବି ଅଧିକ ବିଚଳିତ ହେବା।',
    asTitle: 'ইলিউজন অৱ ট্ৰান্সপাৰেঞ্চি: নিজৰ ভয়-উদ্বেগ আনৰ চকুত ধৰা পৰাৰ বিভ্ৰম',
    asSummary: 'মঞ্চত বক্তব্য ৰখাৰ সময়ত নিজৰ কম্পন আৰু ভয় আন সকলোৱে বুজি পাইছে বুলি ভাবি অহেতুক হতাশ হোৱাৰ মানসিকতা।',
  },
];

console.log('Writing remaining 5 Social Psychology topics...');
for (const topic of REMAINING_5_SOCIAL_PSYCHOLOGY) {
  const content = renderTopicFile(topic);
  const targetPath = path.join(topicsDir, topic.fileName);
  fs.writeFileSync(targetPath, content, 'utf8');
  console.log(`Generated: ${topic.fileName}`);
}
console.log('Done generating all 20 Social Psychology topics!');
