import * as fs from 'fs';
import * as path from 'path';
import { renderTopicFile } from './generateAllExpandedTopics';

const topicsDir = path.join(__dirname, '../src/core/mind/topics');

const SOCIAL_PSYCHOLOGY_TOPICS = [
  // 11. Pluralistic Ignorance
  {
    fileName: 'pluralisticIgnorance.ts',
    varName: 'pluralistic_ignorance',
    id: 'pluralistic_ignorance',
    categoryId: 'social_psychology' as const,
    slug: 'pluralistic-ignorance',
    difficulty: 'intermediate' as const,
    readTime: 6,
    sortWeight: 11,
    titleEn: 'Pluralistic Ignorance: Private Doubts and Public Silence',
    subtitle: 'The social paradox where a majority of individuals privately reject an uncomfortable norm, but falsely assume everyone else supports it.',
    shortDescEn: 'A psychological situation in which a majority of group members privately reject a norm, but incorrectly assume that most others accept it.',
    oneLineEn: 'Nobody believes it, but everybody thinks everybody else believes it.',
    summary30sEn: 'First identified by Daniel Katz and Floyd Allport in 1931, Pluralistic Ignorance occurs when individuals misjudge the private attitudes of their peers based on their outward public compliance. Because everyone masks their hesitation to avoid embarrassment, everyone falsely concludes that the group consensus is genuine, entrenching irrational customs.',
    coreConceptEn: 'Pluralistic ignorance is created by asymmetric information: we have direct access to our own private doubts, but we only have access to others\' external public behaviors. When others appear calm or conformist, we attribute their behavior to internal conviction rather than social pressure, locking the entire room in collective silence.',
    summary60sEn: 'Prentice and Miller (1993) famously demonstrated pluralistic ignorance on university campuses regarding heavy binge drinking. Male students privately reported feeling uncomfortable with extreme alcohol consumption, but believed their peers were passionately enthusiastic about it. Because everyone hid their discomfort, the dangerous drinking culture persisted unopposed.',
    takeawaysEn: [
      'The Emperor\'s New Clothes Dynamic: Collective delusion maintained because no one wants to look foolish alone',
      'Misattributed Conformity: Assuming others\' compliance stems from genuine belief rather than social fear',
      'The Power of One Voice: A single brave individual vocalizing private doubt shatters the illusion instantly',
      'Anonymous Polls Antidote: Real-time digital polling exposes the hidden gap between public faces and private beliefs',
    ] as [string, string, string, string],
    whyItHappensEn: 'Fear of social non-conformity and the illusion of transparency. People fear that admitting doubt will expose them as incompetent or out-of-step.',
    evolutionaryEn: 'Public disagreement in ancestral groups could provoke ostracization; masking reservations was a protective social strategy.',
    howItWorksEn: 'Individual A has doubts -> Looks at Individual B -> Individual B is hiding doubts -> Individual A thinks: "B is fine with this" -> Individual A stays silent -> The group adopts a plan nobody privately wants.',
    whereEn: 'College lecture halls, corporate all-hands meetings, lavish dowry demands in family weddings, hazing rituals, and toxic work hours.',
    headlineEn: 'Private Reality vs. Public Facade',
    sideALabelEn: 'Private Internal Thought (Majority)',
    sideADetailEn: '"I have no idea what the professor just derived on the whiteboard and I feel totally lost."',
    sideBLabelEn: 'Public Conformist Mask',
    sideBDetailEn: '"Everyone else is calmly taking notes without asking questions, so I must be the only slow person here."',
    researchSummaryEn: 'Prentice & Miller (1993) proved that students significantly overestimated peer approval of campus drinking norms, leading to pluralistic compliance.',
    scenarioTitleEn: 'The Silent IIT Lecture in Kanpur',
    scenarioVignetteEn: 'In an advanced thermodynamics lecture at an engineering institute in Kanpur, the professor writes a 40-step tensor equation on the board and asks: "Is this derivation completely obvious to everyone, or does anyone need clarification?" The entire lecture hall of 120 students remains dead silent. Many nod slightly. Vikram is completely baffled, but looking at his calm peers, he assumes he is the only student struggling. After class in the canteen, he discovers that every single one of his classmates was equally confused and prayed someone else would speak up.',
    scenarioBreakdownEn: 'Classic pluralistic ignorance. The visible silence of the room was misinterpreted as intellectual comprehension, creating a false norm that silenced 120 students.',
    scenarioActionEn: 'Use digital anonymous polling tools (like Slido or Kahoot) to ask conceptual check questions where real-time accuracy percentages are shown immediately.',
    pqContextEn: 'At a management consulting firm in Mumbai, associates work 85 hours a week. In private anonymous HR exit surveys, 92% of associates state they hate the hours and want work-life boundaries, yet in team dinners, everyone brags about pulling all-nighters.',
    pqPromptEn: 'Which phenomenon explains why this grueling work culture persists despite overwhelming majority dissatisfaction?',
    pqOptA: 'Pluralistic Ignorance: Each associate assumes all other colleagues genuinely love the grinding hours',
    pqOptB: 'Social Loafing: Associates are reducing their cognitive effort during late nights',
    pqOptC: 'The Ringelmann Effect: The consulting firm is hiring too many associates',
    pqOptD: 'Drive Theory: Having clients watch them speeds up their slide formatting',
    pqCorrect: 'opt_a' as const,
    pqExplanation: 'Pluralistic ignorance occurs when a silent majority privately rejects a cultural norm but falsely believes they are in the minority, perpetuating the norm.',
    pqTakeaway: 'When everyone hides their doubt, bad norms survive: vocalizing questions liberates the silent majority.',
    authorYear: 'Prentice & Miller (1993)',
    refTitle: 'Pluralistic ignorance and alcohol use on campus: Some consequences of misperceiving the social norm',
    refCitation: 'Prentice, D. A., & Miller, D. T. (1993). Journal of Personality and Social Psychology, 64(2), 243–256.',
    doi: '10.1037/0022-3514.64.2.243',
    relatedA: { topicId: 'bystander_effect', slug: 'bystander-effect', title: 'The Bystander Effect' },
    relatedB: { topicId: 'conformity_asch_effect', slug: 'conformity-asch-effect', title: 'Conformity (Asch Effect)' },

    titleHinglish: 'Pluralistic Ignorance: Dil Me Shak Par Sabke Saamne Chuppi',
    subtitleHinglish: 'Koyi bhi us baat ko dil se nahi maanta, par har koi sochta hai ki baaki sab usse agree karte hain.',
    shortDescHinglish: 'Ek aisi ajeeb situation jisme majority log kisi bekaar riwaaz ya rule ke khilaf hote hain, par sab dar ke maare chup rehte hain.',
    oneLineHinglish: 'Dil me sab mana kar rahe hain, par bheed me sab sar hila rahe hain.',
    summary30sHinglish: '1931 me Katz aur Allport ne dekha ki class me jab teacher puchta hai "Kisi ko doubt hai?", toh koi haath nahi uthata. Har student sochta hai: "Agar main puchunga toh log mujhe bewakoof samjhenge, baaki sabko samajh aa gaya hai." Jabki sachai yeh hoti hai ki 100 me se 90 logo ko kuch samajh nahi aaya hota.',
    coreConceptHinglish: 'Pluralistic Ignorance tab banti hai jab hum doosro ki bahar ki shanti dekhkar yeh maan lete hain ki wo andar se satisfied hain. Shadiyo me fizool-kharch, corporate me 14 ghante kaam, aur society ke faltu rules isi vajah se chalte rehte hain.',
    takeawaysHinglish: [
      'Emperor\'s New Clothes: Raja nanga hai par sharm ke maare koi bol nahi raha',
      'Silent Majority: Zyadatar log change chahte hain par pehla kadam uthane se darte hain',
      'Ek Awaaz Ki Taqat: Ek insaan ka bolna baaki 99 logo ko himmat deta hai',
      'Anonymous Polls: Real opinion janne ke liye secret ballot sabse best tareeqa hai',
    ] as [string, string, string, string],

    hiTitle: 'बहुलवादी अज्ञान (Pluralistic Ignorance): निजी असहमति और सार्वजनिक मौन',
    hiSummary: 'एक ऐसी मनोवैज्ञानिक स्थिति जहां समूह का अधिकांश भाग किसी नियम या प्रथा से असहमत होता है, लेकिन गलत अनुमान लगाता है कि बाकी सभी इसका समर्थन करते हैं।',
    hiTakeaways: ['निजी असहमति का दमन', 'सामाजिक शर्म का भय', 'गुमनाम मतदान समाधान'] as [string, string, string],
    guTitle: 'પ્લુરલિસ્ટિક ઇગ્નોરન્સ: ખાનગી શંકા અને જાહેર મૌન',
    guSummary: 'જ્યારે મોટાભાગના લોકો કોઈ બાબત સાથે સંમત ન હોવા છતાં એવું માને છે કે બાકીના બધા લોકો તેની સાથે સંમત છે.',
    mrTitle: 'प्ल्युरॅलिस्टिक इग्नोरन्स: मनात असहमती आणि ओठांवर मौन',
    mrSummary: 'बहुसंख्य लोकांना एखादी प्रथा चुकीची वाटत असूनही, इतर सर्वांना ती मान्य आहे या गैरसमजातून कोणीही विरोध करत नाही.',
    teTitle: 'ప్లూరలిస్టిక్ ఇగ్నోరెన్స్: అంతర్గత సందేహం మరియు బహిరంగ మౌనం',
    teSummary: 'మెజారిటీ ప్రజలు ఒక విషయాన్ని వ్యతిరేకిస్తున్నప్పటికీ, ఇతరులందరూ అంగీకరిస్తున్నారని భావించి మౌనంగా ఉండే పరిస్థితి.',
    taTitle: 'பன்முக அறியாமை: தனிப்பட்ட மறுப்பும் பொதுவான மௌனமும்',
    taSummary: 'பெரும்பான்மையான மக்கள் ஒரு நடைமுறையை தனிப்பட்ட முறையில் எதிர்த்தாலும், மற்றவர்கள் அதை ஏற்றுக்கொள்கிறார்கள் என்று தவறாக நினைத்து மௌனமாக இருத்தல்.',
    knTitle: 'ಪ್ಲೂರಲಿಸ್ಟಿಕ್ ಇಗ್ನೊರೆನ್ಸ್: ಖಾಸಗಿ ಸಂದೇಹ ಮತ್ತು ಸಾರ್ವಜನಿಕ ಮೌನ',
    knSummary: 'ಬಹುತೇಕ ಜನರಿಗೆ ಒಂದು ನಿಯಮ ತಪ್ಪೆಂದು ತಿಳಿದಿದ್ದರೂ, ಇತರರೆಲ್ಲರೂ ಒಪ್ಪಿಕೊಂಡಿದ್ದಾರೆ ಎಂಬ ಭ್ರಮೆಯಿಂದ ಯಾರೂ ಧ್ವನಿ ಎತ್ತದಿರುವುದು.',
    mlTitle: 'പ്ലൂറലിസ്റ്റിക് ഇഗ്നോറൻസ്: ഉള്ളിലെ എതിർപ്പും പുറമെയുള്ള മൗനവും',
    mlSummary: 'ഭൂരിഭാഗം ആളുകൾക്കും ഒരു കാര്യത്തിൽ വിയോജിപ്പുണ്ടെങ്കിലും മറ്റുള്ളവർ അത് അംഗീകരിക്കുന്നു എന്ന് തെറ്റിദ്ധരിച്ച് മിണ്ടാതിരിക്കുന്ന അവസ്ഥ.',
    bnTitle: 'প্লুরালিস্টিক ইগনোরেন্স: ব্যক্তিগত দ্বিধা এবং প্রকাশ্য নীরবতা',
    bnSummary: 'অধিকাংশ মানুষ ব্যক্তিগতভাবে একটি নিয়মের বিরোধী হলেও সবাই তা মেনে নিয়েছে ভেবে চুপ থাকার বিভ্রান্তি।',
    paTitle: 'ਪਲੂਰਲਿਸਟਿਕ ਇਗਨੋਰੈਂਸ: ਮਨ ਵਿੱਚ ਅਸਹਿਮਤੀ ਅਤੇ ਬਾਹਰ ਚੁੱਪ',
    paSummary: 'ਜਦੋਂ ਬਹੁਤੇ ਲੋਕ ਕਿਸੇ ਗੱਲ ਨੂੰ ਗਲਤ ਮੰਨਦੇ ਹੋਏ ਵੀ ਇਹ ਸੋਚ ਕੇ ਚੁੱਪ ਰਹਿੰਦੇ ਹਨ ਕਿ ਬਾਕੀ ਸਾਰੇ ਇਸ ਨਾਲ ਸਹਿਮਤ ਹਨ।',
    urTitle: 'کثرتی جہالت: نجی اختلاف اور عوامی خاموشی',
    urSummary: 'جب اکثریت نجی طور پر کسی رسم کے خلاف ہو لیکن یہ سمجھ کر خاموش رہے کہ باقی سب خوشی سے متفق ہیں۔',
    orTitle: 'ପ୍ଲୁରାଲିଷ୍ଟିକ୍ ଇଗ୍ନୋରାନ୍ସ: ମନରେ ସନ୍ଦେହ ଏବଂ ମୁହଁରେ ଚୁପ୍',
    orSummary: 'ଅଧିକାଂଶ ଲୋକ କୌଣସି ପ୍ରଥାକୁ ବିରୋଧ କରୁଥିଲେ ମଧ୍ୟ ଅନ୍ୟମାନେ ସହମତ ବୋଲି ଭାବି ନିରବ ରହିବାର ମନସ୍ତତ୍ତ୍ୱ।',
    asTitle: 'প্লুৰেলিষ্টিক ইগনৰেন্স: ব্যক্তিগত দ্বিধা আৰু মুকলি মৌনতা',
    asSummary: 'অধিকাংশ মানুহে ব্যক্তিগতভাৱে নিয়ম এটা বেয়া পালেও আনে ভাল পাইছে বুলি ভাবি মৌন হৈ থকাৰ ভুল।',
  },

  // 12. Diffusion of Responsibility
  {
    fileName: 'diffusionOfResponsibility.ts',
    varName: 'diffusion_of_responsibility',
    id: 'diffusion_of_responsibility',
    categoryId: 'social_psychology' as const,
    slug: 'diffusion-of-responsibility',
    difficulty: 'beginner' as const,
    readTime: 5,
    sortWeight: 12,
    titleEn: 'Diffusion of Responsibility: The Dilution of Moral Duty in Groups',
    subtitle: 'Why the psychological weight of duty shrinks as group size expands, leading to collective neglect and moral disengagement.',
    shortDescEn: 'A sociopsychological phenomenon whereby a person is less likely to take responsibility for action or inaction when others are present.',
    oneLineEn: 'When everyone is responsible, nobody feels responsible.',
    summary30sEn: 'First formulated by Darley and Latané in 1968, Diffusion of Responsibility explains why individuals feel their personal moral obligation decrease in proportion to the number of people around them. If an urgent task belongs to a 10-person team, each member feels only 10% of the burden to act, often resulting in complete collective paralysis.',
    coreConceptEn: 'Moral accountability requires focused cognitive ownership. When an individual is alone, 100% of the blame for failure rests squarely on their shoulders. When in a group, the expected psychological penalty of inaction is divided by the number of witnesses (1/N). This fosters "moral disengagement," where individuals tell themselves: "Someone more qualified or senior will handle this."',
    summary60sEn: 'Bandura (1999) expanded this to corporate and military contexts. When decisions are fragmented into small administrative sub-tasks across bureaucratic committees, no single individual feels moral culpability for destructive outcomes. The executioner blames the judge; the judge blames the law; the lawmaker blames the electorate.',
    takeawaysEn: [
      'The 1/N Psychological Rule: Felt moral obligation shrinks inversely with group size',
      'Bureaucratic Camouflage: Complex committees disperse blame, allowing unethical actions to pass without individual guilt',
      'The Open-Channel Paralysis: Asking a group "Can someone fix this?" guarantees delays; naming one owner guarantees action',
      'Single-Threaded Ownership: Assign exactly one name to every decision and action item',
    ] as [string, string, string, string],
    whyItHappensEn: 'Shared consequence expectation. The perceived social and moral consequences of failing to act are psychologically distributed across all witnesses.',
    evolutionaryEn: 'Diffusing blame within an ancestral hunting pack protected individual rank and avoided concentrated tribal retribution.',
    howItWorksEn: 'Urgent situation appears -> Witness notes presence of peers -> Calculates: "Blame will be shared by all 20 of us" -> Personal guilt drops below action threshold -> Complete inaction ensues.',
    whereEn: 'Broadcast emails with 50 people in CC, group chat requests, medical ward handovers, compliance auditing committees, and public road accidents.',
    headlineEn: 'Felt Responsibility vs. Group Headcount',
    sideALabelEn: 'Single Assigned Owner (100% Duty)',
    sideADetailEn: '"Rohan is accountable for running the database backup at 2 AM tonight."',
    sideBLabelEn: 'Diffused Collective (0% Felt Duty)',
    sideBDetailEn: '"The infrastructure team should ensure backups run smoothly whenever possible."',
    researchSummaryEn: 'Darley & Latané (1968) demonstrated that bystander intervention time increased linearly with perceived group size, confirming moral dilution.',
    scenarioTitleEn: 'The Broken Payment Gateway at a Bengaluru Startup',
    scenarioVignetteEn: 'On a busy Saturday evening, an e-commerce startup in Bengaluru experiences a critical payment gateway outage. The automated alert fires into a public Slack channel with 450 engineers: "URGENT: Payments failing at 90% rate!" For four straight hours, engineers see the alert, assume the dedicated payments team or an on-call DevOps engineer is already debugging, and continue scrolling. Over ₹1.2 crores in transactions are lost before the CEO directly calls one engineer by name on mobile.',
    scenarioBreakdownEn: 'Classic diffusion of responsibility. The public alert to 450 people meant nobody felt individually responsible. Each engineer felt only 1/450th of the guilt.',
    scenarioActionEn: 'Never broadcast emergencies to groups without automated single-threaded on-call escalations (PagerDuty alerts routed directly to ONE person with a 15-minute phone buzzer).',
    pqContextEn: 'A project manager in Hyderabad sends an email to 25 stakeholders: "Can someone please update the client slide deck before tomorrow morning\'s meeting?" The next morning, the deck is completely untouched.',
    pqPromptEn: 'Which procedural adjustment best counteracts the Diffusion of Responsibility that caused this failure?',
    pqOptA: 'Sending the exact same email marked with HIGH IMPORTANCE and red exclamation points',
    pqOptB: 'Assigning the task to one specific individual: "Ananya, please own updating slides 4–8 by 8 PM tonight"',
    pqOptC: 'Adding 10 more stakeholders to the CC line so more people see the request',
    pqOptD: 'Offering a collective team praise shoutout on LinkedIn if the deck gets completed',
    pqCorrect: 'opt_b' as const,
    pqExplanation: 'Directly naming one specific individual assigns 100% of the moral and professional responsibility, completely bypassing diffusion.',
    pqTakeaway: 'Shared responsibility is no responsibility: assign singular ownership to every critical action.',
    authorYear: 'Darley & Latané (1968)',
    refTitle: 'Bystander intervention in emergencies: Diffusion of responsibility',
    refCitation: 'Darley, J. M., & Latané, B. (1968). Journal of Personality and Social Psychology, 8(4), 377–383.',
    doi: '10.1037/0022-3514.8.4.377',
    relatedA: { topicId: 'bystander_effect', slug: 'bystander-effect', title: 'The Bystander Effect' },
    relatedB: { topicId: 'social_loafing', slug: 'social-loafing', title: 'Social Loafing' },

    titleHinglish: 'Diffusion of Responsibility: Jab Zimmedari Bheed Me Gayab Ho Jati Hai',
    subtitleHinglish: 'Jab sabki zimmedari hoti hai, toh koi bhi aage nahi aata kyunki har koi sochta hai koi aur kar dega.',
    shortDescHinglish: 'Bheed me har insaan ka apna moral duty kam mehsoos karna kyunki wo sochta hai ki bojh sab par bat gaya hai.',
    oneLineHinglish: 'Jab sab zimmedar hote hain, toh aslyat me koi bhi zimmedar nahi hota.',
    summary30sHinglish: '1968 me Darley aur Latané ne dekha ki agar 100 logo ke WhatsApp group me poocho "Koyi client ki file send karega?", toh koi reply nahi karta. Har koi sochta hai: "Bohot log hain, koi aur bhej dega." Par agar aap kisi ek bande ka naam lekar pucho: "Rahul, file bhejo", toh wo 2 minute me bhej deta hai. Ise kehte hain Diffusion of Responsibility.',
    coreConceptHinglish: 'Jab koi kaam akele bande ko diya jata hai, toh 100% credit ya blame uska hota hai. Par bheed me blame 1/N hisso me bat jata hai, jisse guilt khatam ho jata hai.',
    takeawaysHinglish: [
      'The 1/N Rule: Bheed jitni badi hogi, zimmedari ka ehsaas utna hi kam hoga',
      'Slack/Group Trap: Open group me emergency daalna bekaar hai; naam le kar mention karo',
      'Bureaucracy Ka Khel: Bade offices me har koi doosre department par ungli uthata hai',
      'Rule: Hamesha ek task ka sirf ek hi single owner hona chahiye',
    ] as [string, string, string, string],

    hiTitle: 'उत्तरदायित्व का बिखराव (Diffusion of Responsibility): सामूहिकता में कर्तव्य का विलोपन',
    hiSummary: 'जब किसी आपातकालीन स्थिति या कार्य में अनेक लोग उपस्थित होते हैं, तो प्रत्येक व्यक्ति अपने व्यक्तिगत उत्तरदायित्व को कम महसूस करता है, जिससे कोई भी कार्रवाई नहीं करता।',
    hiTakeaways: ['सामूहिकता में उत्तरदायित्व शून्य', 'एकल स्वामित्व का सिद्धांत', 'सीधा और व्यक्तिगत आवंटन अनिवार्य'] as [string, string, string],
    guTitle: 'જવાબદારીનું વિભાજન: જૂથમાં કર્તવ્યબોધનો ઘટાડો',
    guSummary: 'જ્યારે કોઈ કામ ઘણા લોકોને સોંપવામાં આવે છે, ત્યારે દરેક વ્યક્તિ માને છે કે અન્ય કોઈ તે કરશે, જેના કારણે કોઈ પગલાં લેવાતા નથી.',
    mrTitle: 'जबाबदारीचे विकेंद్రీकरण: समूहात वैयक्तिक कर्तव्याचा विसर',
    mrSummary: 'जेव्हा सर्वांची जबाबदारी असते, तेव्हा प्रत्यक्षात कोणाचीच जबाबदारी नसते. कामाचे वाटप एकाच व्यक्तीकडे असणे गरजेचे आहे.',
    teTitle: 'బాధ్యత విస్తరణ: సమూహంలో కర్తవ్య భావన తగ్గడం',
    teSummary: 'ఎక్కువ మంది ఉన్నప్పుడు ప్రతి ఒక్కరూ తమ వ్యక్తిగత బాధ్యతను మరచిపోయి ఇతరులపై ఆధారపడే పరిస్థితి.',
    taTitle: 'பொறுப்புப் பரவல்: குழுவில் குறையும் தார்மீகக் கடமை',
    taSummary: 'பலர் இருக்கும் இடத்தில் ஒவ்வொருவரும் தங்கள் பொறுப்பைக் குறைவாக உணர்வதால், இறுதியில் எவரும் செயல்படாமல் போகும் நிலை.',
    knTitle: 'ಜವಾಬ್ದಾರಿಯ ಪ್ರಸರಣ: ಗುಂಪಿನಲ್ಲಿ ಕರ್ತವ್ಯದ ಕ್ಷೀಣತೆ',
    knSummary: 'ಎಲ್ಲರಿಗೂ ಜವಾಬ್ದಾರಿ ಇದ್ದಾಗ ಯಾರೊಬ್ಬರೂ ಅದನ್ನು ಸ್ವೀಕರಿಸುವುದಿಲ್ಲ. ಪ್ರತಿಯೊಂದು ಕಾರ್ಯಕ್ಕೂ ಒಬ್ಬನೇ ಮಾಲೀಕನಿರಬೇಕು.',
    mlTitle: 'ഉത്തരവാദിത്ത വിഭജനം: കൂട്ടായ്മയിൽ ഉത്തരവാദിത്തബോധം കുറയുന്ന അവസ്ഥ',
    mlSummary: 'ധാരാളം ആളുകൾ ഉള്ളപ്പോൾ ആരും സ്വയം മുന്നോട്ട് വരാതിരിക്കുകയും മറ്റുള്ളവർ ചെയ്യുമെന്ന് കരുതുകയും ചെയ്യുന്ന പ്രവണത.',
    bnTitle: 'দায়িত্বের বিস্তারণ: দলগত উপস্থিতিতে ব্যক্তিগত কর্তব্যের অবক্ষয়',
    bnSummary: 'সবার দায়িত্ব মানে কারও দায়িত্ব নয়—দলে অনেকে থাকলে প্রত্যেকেই অন্যের ওপর ভরসা করে নিষ্ক্রিয় থাকে।',
    paTitle: 'ਜ਼ਿੰਮੇਵਾਰੀ ਦਾ ਖਿਲਾਰਾ: ਭੀੜ ਵਿੱਚ ਨਿੱਜੀ ਫਰਜ਼ ਦਾ ਗਾਇਬ ਹੋਣਾ',
    paSummary: 'ਜਦੋਂ ਕੰਮ ਸਾਰਿਆਂ ਦਾ ਹੁੰਦਾ ਹੈ, ਤਾਂ ਕੋਈ ਵੀ ਅੱਗੇ ਨਹੀਂ ਆਉਂਦਾ ਕਿਉਂਕਿ ਹਰ ਕੋਈ ਦੂਜੇ ਉੱਤੇ ਆਸ ਲਗਾਈ ਬੈਠਾ ਹੁੰਦਾ ਹੈ।',
    urTitle: 'ذمہ داری کا پھیلاؤ: ہجوم میں انفرادی فرض کا کم ہو جانا',
    urSummary: 'جب سب کی مشترکہ ذمہ داری ہو تو درحقیقت کوئی بھی ذمہ داری قبول نہیں کرتا اور کام رک جاتا ہے۔',
    orTitle: 'ଦାୟିତ୍ୱର ବିଭାଜନ: ଗୋଷ୍ଠୀରେ ବ୍ୟକ୍ତିଗତ କର୍ତ୍ତବ୍ୟବୋଧ ହ୍ରାସ',
    orSummary: 'ଯେତେବେଳେ ସମସ୍ତଙ୍କର ଦାୟିତ୍ୱ ଥାଏ, ସେତେବେଳେ କେହି ଜଣେ ହେଲେ ନିଜ ତରଫରୁ କାର୍ଯ୍ୟ କରିବାକୁ ଆଗେଇ ଆସନ୍ତି ନାହିଁ।',
    asTitle: 'দায়িত্বৰ বিস্তাৰণ: দলীয় পৰিৱেশত কৰ্তব্যবোধ হ্ৰাস',
    asSummary: 'সকলোৰে দায়িত্ব মানে কাৰো দায়িত্ব নহয়—মানুহ বেছি হ’লে প্রত্যেকেই আনৰ ওপৰত আশা কৰি নিষ্ক্ৰিয় হৈ ৰয়।',
  },

  // 13. Pygmalion Effect
  {
    fileName: 'pygmalionEffect.ts',
    varName: 'pygmalion_effect',
    id: 'pygmalion_effect',
    categoryId: 'social_psychology' as const,
    slug: 'pygmalion-effect',
    difficulty: 'beginner' as const,
    readTime: 5,
    sortWeight: 13,
    titleEn: 'The Pygmalion Effect: How Expectations Shape Human Reality',
    subtitle: 'The self-fulfilling prophecy where high expectations unconsciously drive higher performance, while low expectations crush potential.',
    shortDescEn: 'A psychological phenomenon in which high expectations lead to improved performance in a given area, and vice versa (the Golem Effect).',
    oneLineEn: 'Treat people as who they could be, and their performance will rise to meet your belief.',
    summary30sEn: 'Documented in classrooms by Robert Rosenthal and Lenore Jacobson in 1968, the Pygmalion Effect proves that human performance is intensely malleable to the expectations of authority figures. When teachers or managers believe someone is exceptionally gifted, they unconsciously provide more warmth, feedback, and challenging opportunities, causing the person\'s actual competence to skyrocket.',
    coreConceptEn: 'The Pygmalion mechanism operates across a continuous circular feedback loop: (1) Our beliefs about others -> (2) Influence our subtle actions toward them (micro-expressions, patience, opportunity allocation) -> (3) Impact their self-beliefs and confidence -> (4) Cause their actions and performance to improve -> (5) Reinforces our original belief. The inverse is the Golem Effect, where negative expectations systematically destroy talent.',
    summary60sEn: 'In Rosenthal & Jacobson\'s classic experiment, elementary school teachers were told that a standardized test had identified specific students as "intellectual bloomers" destined for dramatic academic growth. In reality, the students were chosen completely at random. One year later, those randomly selected "bloomers" demonstrated significantly higher real IQ score gains than their peers. The teachers\' belief literally altered the students\' cognitive development.',
    takeawaysEn: [
      'The Expectancy Loop: High expectations create supportive micro-behaviors that genuinely boost competence',
      'The Golem Hazard: Low expectations communicate mistrust, causing employees and students to mentally check out',
      'Micro-Behaviors Matter: Teachers and bosses signal confidence through tone of voice, eye contact, and patience during mistakes',
      'Calibrated Optimism: Set rigorous, ambitious goals while providing unconditional emotional support',
    ] as [string, string, string, string],
    whyItHappensEn: 'Interpersonal expectancy bias. Subordinates read nonverbal cues from leaders and unconsciously adjust their internal self-efficacy and effort.',
    evolutionaryEn: 'In ancestral social groups, young hunters invested effort into skills that tribal elders recognized and rewarded with high status.',
    howItWorksEn: 'Leader forms high expectation -> Leader allocates high-leverage challenges and detailed coaching -> Subordinate feels trusted -> Self-efficacy increases -> Subordinate works harder -> Performance surges -> Leader\'s expectation confirmed.',
    whereEn: 'School classrooms, engineering mentorship, executive coaching, parenting, sports coaching, and medical patient rehabilitation.',
    headlineEn: 'Pygmalion Lift vs. Golem Destruction',
    sideALabelEn: 'Pygmalion Expectations (High Trust)',
    sideADetailEn: '"I know this architecture is complex, but I have seen your analytical depth; you will crack it."',
    sideBLabelEn: 'Golem Trap (Low Expectations)',
    sideBDetailEn: '"Don\'t give him the critical payment module; he is slow and will probably introduce bugs."',
    researchSummaryEn: 'Rosenthal & Jacobson (1968) demonstrated that false teacher expectations generated statistically significant, real-world IQ increases in elementary students.',
    scenarioTitleEn: 'The Junior Data Analyst in Hyderabad',
    scenarioVignetteEn: 'Pooja joins a top analytics firm in Hyderabad as a junior hire with average college grades. Her manager, Vikram, reviews her initial work and says: "Pooja has rare conceptual clarity; she is going to be our lead machine-learning architect in two years." Vikram invites her to client presentations, gives her complex feature-engineering assignments, and spends time patiently reviewing her math. Pooja feels immensely valued, studies ML papers late into the night, and within 18 months files two patents for the company.',
    scenarioBreakdownEn: 'The Pygmalion Effect in full bloom. Vikram\'s genuine high expectations led to elevated opportunities, feedback, and warmth, which transformed Pooja\'s internal confidence and real performance.',
    scenarioActionEn: 'Identify one struggling or average performer in your organization and deliberately assign them a high-autonomy project with enthusiastic, public executive backing.',
    pqContextEn: 'A high school mathematics teacher in Delhi is assigned two identical sections of 10th-grade algebra. He is falsely informed that Section A is "gifted mathematically" and Section B is "remedial." At the end of the semester, Section A scores 25% higher on the standardized state board exam.',
    pqPromptEn: 'According to Rosenthal\'s research on the Pygmalion Effect, what caused this dramatic score divergence?',
    pqOptA: 'Section A students possessed superior natural genetic mathematical aptitude',
    pqOptB: 'The teacher unconsciously provided more wait-time for answers, richer conceptual feedback, and warmer encouragement to Section A',
    pqOptC: 'Section B students experienced social loafing due to large classroom headcount',
    pqOptD: 'Section A students engaged in pluralistic ignorance during exams',
    pqCorrect: 'opt_b' as const,
    pqExplanation: 'The Pygmalion effect is transmitted through subtle teacher micro-behaviors: tone of voice, patience, question difficulty, and high-frequency constructive feedback.',
    pqTakeaway: 'Expectations become self-fulfilling: human beings almost always rise or fall to the expectations set by their leaders.',
    authorYear: 'Rosenthal & Jacobson (1968)',
    refTitle: 'Pygmalion in the classroom: Teacher expectation and pupils\' intellectual development',
    refCitation: 'Rosenthal, R., & Jacobson, L. (1968). The Urban Review, 3(1), 16–20.',
    doi: '10.1177/004208596800300403',
    relatedA: { topicId: 'halo_effect', slug: 'halo-effect', title: 'The Halo Effect' },
    relatedB: { topicId: 'confirmation_bias', slug: 'confirmation-bias', title: 'Confirmation Bias' },

    titleHinglish: 'The Pygmalion Effect: Aapki Ummeedein Doosro Ki Reality Kaise Badal Deti Hain',
    subtitleHinglish: 'Jab boss ya teacher kisi ko genius maante hain, toh wo sach me genius ki tarah perform karne lagta hai.',
    shortDescHinglish: 'Ek aisi self-fulfilling prophecy jahan high expectations insaan ke confidence aur real performance ko aasmaan par pahuncha deti hain.',
    oneLineHinglish: 'Kisi ko vishwas do ki wo kamaal kar sakta hai, aur uska dimaag use sach kar dikhayega.',
    summary30sHinglish: '1968 me Robert Rosenthal ne ek school me experiment kiya. Unhone teachers se jhooth bola ki kuch random bacche "super gifted" hain. Ek saal baad, unhi randomly selected baccho ka real IQ sach me 25% badh gaya! Kyunki teachers unhe pyaar, patience aur challenging kaam dete the. Ise Pygmalion Effect kehte hain.',
    coreConceptHinglish: 'Insaan waisa hi perform karta hai jaisi ummeed usse ki jaati hai. Agar aap kisi employee ko nalaayak samjhoge (Golem Effect), toh wo galti hi karega. Agar aap uspe genuine bharosa dikhaoge aur bada task doge, toh uska dimaag us standard par uth jayega.',
    takeawaysHinglish: [
      'Expectation Loop: Aapki soch aapke gestures aur tone me jhalakti hai',
      'Golem Effect Ka Khatra: Kisi ko useless kehna uski skills ko sach me destroy kar deta hai',
      'Patience Ka Khel: Mistakes par daantne ke bajaye sikhane se performance double hoti hai',
      'Leadership Rule: Team ko unke past records se nahi, unki future potential se judge karo',
    ] as [string, string, string, string],

    hiTitle: 'पिग्मेलियन प्रभाव (Pygmalion Effect): अपेक्षाएं बनाती हैं वास्तविकता',
    hiSummary: 'जब किसी शिक्षक, माता-पिता या प्रबंधक की किसी व्यक्ति से उच्च अपेक्षाएं होती हैं, तो वह व्यक्ति अनजाने में अधिक प्रयास करता है और उसका प्रदर्शन वास्तव में बेहतर हो जाता है।',
    hiTakeaways: ['अपेक्षाओं का प्रत्यक्ष प्रभाव', 'आत्म-संतुष्टि की भविष्यवाणी', 'सहानुभूतिपूर्ण और उच्च मानक आवश्यक'] as [string, string, string],
    guTitle: 'પિગ્મેલિયન ઇફેક્ટ: અપેક્ષાઓ વાસ્તવિકતામાં પરિવર્તિત થાય છે',
    guSummary: 'જ્યારે નેતા કે શિક્ષક કોઈ વ્યક્તિમાં વિશ્વાસ દર્શાવે છે, ત્યારે તે વ્યક્તિનું વાસ્તવિક પ્રદર્શન નોંધપાત્ર રીતે સુધરે છે.',
    mrTitle: 'पिग्मॅलियन इफेक्ट: उच्च अपेक्षांमधून घडणारे उत्तम प्रदर्शन',
    mrSummary: 'जेव्हा अधिकारपद व्यक्ती एखाद्यावर विश्वास ठेवते आणि उच्च अपेक्षा बाळगते, तेव्हा ती व्यक्ती स्वतःला सिद्ध करून दाखवते.',
    teTitle: 'పిగ్మాలియన్ ఎఫెక్ట్: అంచనాలు వాస్తవ రూపాన్ని సంతరించుకోవడం',
    teSummary: 'నాయకులు తమ సహచరులపై ఉంచే ఉన్నతమైన నమ్మకం వారి పనితీరును స్వయంచాలకంగా మెరుగుపరుస్తుంది.',
    taTitle: 'பிக்மேலியன் விளைவு: எதிர்பார்ப்புகள் உருவாக்கும் உண்மை',
    taSummary: 'ஒருவர் மீது நாம் வைக்கும் உயர்ந்த எதிர்பார்ப்புகள் அவர்களை அறியாமலேயே அவர்களின் செயல்திறனை உயர்த்துகின்றன.',
    knTitle: 'ಪಿಗ್ಮ್ಯಾಲಿಯನ್ ಎಫೆಕ್ಟ್: ಉನ್ನತ ನಿರೀಕ್ಷೆಗಳು ವಾಸ್ತವವನ್ನು ರೂಪಿಸುವ ವಿಧಾನ',
    knSummary: 'ನಾಯಕರು ಅಥವಾ ಶಿಕ್ಷಕರು ವ್ಯಕ್ತಿಯ ಮೇಲೆ ಇಡುವ ವಿಶ್ವಾಸವು ಅವರ ನೈಜ ಸಾಮರ್ಥ್ಯವನ್ನು ಗಮನಾರ್ಹವಾಗಿ ಹೆಚ್ಚಿಸುತ್ತದೆ.',
    mlTitle: 'പിഗ്മാലിയൻ ഇഫക്റ്റ്: പ്രതീക്ഷകൾ യാഥാർത്ഥ്യത്തെ രൂപപ്പെടുത്തുന്ന വിധം',
    mlSummary: 'മറ്റുള്ളവരിൽ അർപ്പിക്കുന്ന ഉയർന്ന പ്രതീക്ഷകൾ അവരുടെ യഥാർത്ഥ പ്രകടനത്തെ മെച്ചപ്പെടുത്തുന്ന മനശാസ്ത്രപരമായ പ്രതിഭാസം.',
    bnTitle: 'পিগম্যালিয়ন প্রভাব: উচ্চ প্রত্যাশার জাদুকরী বাস্তব রূপায়ন',
    bnSummary: 'শিক্ষক বা নেতার গভীর বিশ্বাস এবং উচ্চ প্রত্যাশা যেকোনো সাধারণ মানুষের ভেতরের প্রতিভাকে জাগিয়ে তোলে।',
    paTitle: 'ਪਿਗਮੈਲੀਅਨ ਪ੍ਰਭਾਵ: ਉਮੀਦਾਂ ਕਿਵੇਂ ਅਸਲੀਅਤ ਬਣ ਜਾਂਦੀਆਂ ਹਨ',
    paSummary: 'ਜਦੋਂ ਕਿਸੇ ਵਿਅਕਤੀ ਉੱਤੇ ਭਰੋਸਾ ਕੀਤਾ ਜਾਂਦਾ ਹੈ ਅਤੇ ਵੱਡੀਆਂ ਉਮੀਦਾਂ ਰੱਖੀਆਂ ਜਾਂਦੀਆਂ ਹਨ, ਤਾਂ ਉਸਦੀ ਕਾਰਗੁਜ਼ਾਰੀ ਆਪਣੇ ਆਪ ਵਧ ਜਾਂਦੀ ਹੈ।',
    urTitle: 'پگمیلین اثر: توقعات کیسے حقیقت کا روپ دھار لیتی ہیں',
    urSummary: 'جب سربراہ اپنے ماتحتوں سے بلند توقعات وابستہ کرتا ہے تو ان کی حقیقی کارکردگی میں غیر معمولی اضافہ ہوتا ہے۔',
    orTitle: 'ପିଗ୍‌ମାଲିଅନ୍ ପ୍ରଭାବ: ଆଶା ଓ ବିଶ୍ୱାସର ଶକ୍ତି',
    orSummary: 'ଯେତେବେଳେ ଜଣେ ଶିକ୍ଷକ ବା ଅଧିକାରୀ କୌଣସି ବ୍ୟକ୍ତି ଉପରେ ଦୃଢ଼ ବିଶ୍ୱାସ ପ୍ରକଟ କରନ୍ତି, ସେହି ବ୍ୟକ୍ତି ନିଜ କାର୍ଯ୍ୟଦକ୍ଷତା ବୃଦ୍ଧି କରେ।',
    asTitle: 'পিগমেলিয়ন প্ৰভাৱ: উচ্চ প্রত্যাশাই কেনেকৈ সফলতা কঢ়িয়াই আনে',
    asSummary: 'নেতা বা শিক্ষকে যেতিয়া এজন ব্যক্তিৰ পৰা ভাল প্ৰদৰ্শন আশা কৰে, তেতিয়া ব্যক্তিজনৰ আত্মবিশ্বাস আৰু দক্ষতা বৃদ্ধি পায়।',
  },
];

console.log('Writing Social Psychology batch...');
for (const topic of SOCIAL_PSYCHOLOGY_TOPICS) {
  const content = renderTopicFile(topic);
  const targetPath = path.join(topicsDir, topic.fileName);
  fs.writeFileSync(targetPath, content, 'utf8');
  console.log(`Generated: ${topic.fileName}`);
}
console.log('Done Social Psychology batch.');
