import * as fs from 'fs';
import * as path from 'path';
import { renderTopicFile, TopicDef } from './generateAllExpandedTopics';

const topicsDir = path.join(__dirname, '../src/core/mind/topics');

export const EXPANDED_TOPICS_REMAINING: TopicDef[] = [
  // ==========================================
  // TRACK 6: EMOTIONS & REGULATION (emotions)
  // ==========================================
  {
    fileName: 'amygdalaHijack.ts',
    varName: 'amygdala_hijack',
    id: 'amygdala_hijack',
    categoryId: 'emotions',
    slug: 'amygdala-hijack',
    difficulty: 'intermediate',
    readTime: 6,
    sortWeight: 5,
    titleEn: 'Amygdala Hijack: The Neural Surge That Overrides Reason',
    subtitleEn: 'When the brain’s primitive threat detector triggers an immediate fight-or-flight response before the rational prefrontal cortex can process facts.',
    summaryEn: 'Coined by psychologist Daniel Goleman in 1995 based on neuroscientist Joseph LeDoux’s work, an amygdala hijack happens when sensory input bypasses the slow neocortex via a direct subcortical pathway to the amygdala, triggering a sudden, overwhelming emotional explosion before rational evaluation occurs.',
    takeawaysEn: [
      'The amygdala reacts in milliseconds, sending adrenaline surges before rational analysis starts',
      'Blood flow leaves the prefrontal cortex, reducing logical processing and nuanced judgment',
      'The physiological reaction takes approximately 6 seconds to biologically clear with conscious breathwork'
    ],
    titleHinglish: 'Amygdala Hijack: Jab Gussa Dimaag Ke Logic Ko Band Kar Deta Hai',
    subtitleHinglish: 'Kyu achanak choti si baat par insaan bina soche samjhe chilla padta hai aur baad me regret karta hai.',
    summaryHinglish: 'Daniel Goleman ne samjhaya ki hamare dimaag ka threat center (amygdala) prefrontal cortex se pehle react karta hai. Jab koi verbal attack ya criticism aati hai, amygdala use physical attack samajh kar survival adrenaline chhod deta hai. 6 second ka pause lene se prefrontal cortex wapas control me aa jata hai.',
    takeawaysHinglish: [
      'Gusse me logic isliye band ho jata hai kyuki dimaag survival mode me chala jata hai',
      'React karne se pehle 6 second ka deep breath lena biological circuit breaker ka kaam karta hai',
      'Baad ka pachtava is baat ka proof hai ki aapka prefrontal cortex gusse ke waqt offline tha'
    ],
    hiTitle: 'Amygdala Hijack (अमिग्डाला अपहरण)',
    hiSummary: 'जब मस्तिष्क का भावुक केंद्र तार्किक प्रीफ्रंटल कॉर्टेक्स को बाईपास करके तात्कालिक क्रोध या भय की प्रतिक्रिया शुरू कर देता है।',
    hiTakeaways: [
      'भावनाएं तर्क की तुलना में मस्तिष्क में अधिक तेजी से प्रवाहित होती हैं',
      'सहानुभूतिपूर्ण तंत्रिका तंत्र तात्कालिक रक्षात्मक प्रतिक्रिया उत्पन्न करता है',
      'सचेत श्वास द्वारा ६ सेकंड का विराम तर्क को पुनः सक्रिय करता है'
    ],
    guTitle: 'એમિગ્ડાલા હાઇજેક (આવેગિક પ્રતિક્રિયા)',
    guSummary: 'જ્યારે તીવ્ર ક્રોધ કે ભય વિચારશક્તિ પર હાવી થઈને અવિચારી નિર્ણય લેવડાવે છે.',
    mrTitle: 'अमिग्डाला हायजॅक (आवेगाचा स्फोट)',
    mrSummary: 'तार्किक विचारांआधी मेंदूच्या भावनिक केंद्राकडून तात्काळ आक्रमक प्रतिक्रिया उमटणे.',
    teTitle: 'అమిగ్డాలా హైజాక్ (ఆవేశపు స్పందన)',
    teSummary: 'మెదడులోని భావోద్వేగ కేంద్రం విచక్షణా జ్ఞానాన్ని నిలిపివేసి ఆవేశంతో స్పందించే స్థితి.',
    taTitle: 'அமிக்டாலா கடத்தல் (உணர்ச்சி வெடிப்பு)',
    taSummary: 'மூளையின் தர்க்கரீதியான சிந்தனையை முடக்கி உடனடி கோபத்தை உருவாக்கும் நரம்பியல் செயல்முறை.',
    knTitle: 'ಅಮಿಗ್ಡಾಲಾ ಹೈಜಾಕ್ (ಭಾವೋದ್ರೇಕದ ಸೆಳೆತ)',
    knSummary: 'ತರ್ಕಬದ್ಧ ಚಿಂತನೆಗೆ ಮುನ್ನವೇ ಮೆದುಳಿನ ಭಾವನಾತ್ಮಕ ಕೇಂದ್ರವು ತಕ್ಷಣದ ಪ್ರತಿಕ್ರಿಯೆಯನ್ನು ಪ್ರಚೋದಿಸುವ ಸ್ಥಿತಿ.',
    mlTitle: 'അമിഗ്ഡല ഹൈജാക്ക് (വൈകാരിക തരംഗം)',
    mlSummary: 'യുക്തിസഹമായ ചിന്തയെ മറികടന്ന് മസ്തിഷ്കം പെട്ടെന്നുള്ള വൈകാരിക പ്രതികരണം നൽകുന്ന അവസ്ഥ.',
    bnTitle: 'অ্যামিগডালা হাইজ্যাক (আবেগীয় বিস্ফোরণ)',
    bnSummary: 'মস্তিষ্কের যৌক্তিক অংশ কাজ করার আগেই তাত্ক্ষণিক রাগ বা ভয়ের অপ্রতিরোধ্য বহিঃপ্রকাশ।',
    paTitle: 'ਐਮਿਗਡਾਲਾ ਹਾਈਜੈਕ (ਗੁੱਸੇ ਦਾ ਉਛਾਲ)',
    paSummary: 'ਜਦੋਂ ਤਰਕ ਤੋਂ ਪਹਿਲਾਂ ਦਿਮਾਗ ਦਾ ਭਾਵਨਾਤਮਕ ਕੇਂਦਰ ਬੇਕਾਬੂ ਪ੍ਰਤੀਕਿਰਿਆ ਸ਼ੁਰੂ ਕਰ ਦਿੰਦਾ ਹੈ।',
    urTitle: 'امیگڈالا ہائی جیک (جذباتی طوفان)',
    urSummary: 'جب دماغ کا جذباتی مرکز عقل و شعور کو معطل کر کے فوری اور بے قابو ردعمل پیدا کرتا ہے۔',
    orTitle: 'ଆମିଗ୍ଡାଲା ହାଇଜ୍ୟାକ୍ (ଆବେଗପୂର୍ଣ୍ଣ ପ୍ରତିକ୍ରିୟା)',
    orSummary: 'ତର୍କପୂର୍ଣ୍ଣ ଚିନ୍ତା ପୂର୍ବରୁ ମସ୍ତିଷ୍କର ଭାବପ୍ରବଣ କେନ୍ଦ୍ର ଅପ୍ରତ୍ୟାଶିତ କ୍ରୋଧ ସୃଷ୍ଟି କରିବା।',
    asTitle: 'এমিগডালা হাইজেক (আৱেগিক আক্ৰমণ)',
    asSummary: 'যুক্তিগত চিন্তাৰ পূৰ্বেই মগজুৰ আৱেগিক কেন্দ্ৰই নিয়ন্ত্ৰণহীন খং বা ভয় সৃষ্টি কৰে।',
    citationAuthors: 'Goleman, D., & LeDoux, J. E.',
    citationYear: 1995,
    citationJournal: 'Emotional Intelligence: Why It Can Matter More Than IQ / The Emotional Brain',
    citationDoi: 'https://doi.org/10.1037/0003-066X.51.10.1069',
    caseTitle: 'The Startup Pitch Outburst in Gurgaon',
    caseDomain: 'workplace',
    caseSituation: 'During an angel funding round in Cyber City Gurgaon, an investor casually questioned a co-founder’s unit economics as "naive".',
    caseOutcome: 'Triggered by sleep deprivation and identity threat, the founder exploded with personal insults, destroying the term sheet instantly.',
    caseFix: 'The founder learned to recognize somatic warning signs (racing pulse, shallow breathing) and implement a non-negotiable 6-second water sip delay.'
  },
  {
    fileName: 'somaticMarkerHypothesis.ts',
    varName: 'somatic_marker_hypothesis',
    id: 'somatic_marker_hypothesis',
    categoryId: 'emotions',
    slug: 'somatic-marker-hypothesis',
    difficulty: 'advanced',
    readTime: 7,
    sortWeight: 6,
    titleEn: 'The Somatic Marker Hypothesis: How Bodily Signals Guide Reasoning',
    subtitleEn: 'Antonio Damasio’s groundbreaking discovery that rational decision making fundamentally depends on subconscious bodily sensations ("gut feelings").',
    summaryEn: 'Formulated by neuroscientist Antonio Damasio in 1994, the Somatic Marker Hypothesis shows that when facing complex decisions, the brain creates unconscious physiological signals (gut sensations, heart rate shifts) associated with past emotional outcomes, pruning the option tree before conscious logic begins.',
    takeawaysEn: [
      'Pure abstract rationality without emotional body feedback leads to decision paralysis',
      'Gut feelings are condensed neural memories of past rewards and punishments',
      'Healthy decision making harmonizes somatic sensations with analytical verification'
    ],
    titleHinglish: 'Somatic Marker Hypothesis: Gut Feeling Aur Dimaag Ka Rishta',
    subtitleHinglish: 'Kyu hamara pet aur dil kisi faisle se pehle hi signal de dete hain ki kuch gadbad hai.',
    summaryHinglish: 'Antonio Damasio ne prove kiya ki jin patients ka emotional brain damage ho jata hai, wo chote chote decisions lene me ghanto atak jate hain. Hamara sharir purane anubhavo ki emotional summary ("gut feeling") ke zariye hazaro options ko filter karta hai.',
    takeawaysHinglish: [
      'Gut feeling koi magic nahi, balki past experience ka unconscious data summary hai',
      'Bina emotion ke insaan ultra-logical nahi banta, balki decision lene me paralyzed ho jata hai',
      'Body signals ko suno, par final confirmation factual analysis se karo'
    ],
    hiTitle: 'Somatic Marker Hypothesis (शारीरिक संकेत परिकल्पना)',
    hiSummary: 'शारीरिक अनुभूतियां और अंतर्ज्ञान कैसे जटिल निर्णयों को सरल और सटीक बनाने में मस्तिष्क का मार्गदर्शन करते हैं।',
    hiTakeaways: [
      'शारीरिक संवेदनाएं अतीत के अनुभवों की स्मृति का संक्षिप्त रूप होती हैं',
      'भावनाओं के अभाव में तार्किक विश्लेषण अंतहीन भ्रम में फंस जाता है',
      'आंतरिक अनुभूतियों और तार्किक गणना का समन्वय ही श्रेष्ठ निर्णय देता है'
    ],
    guTitle: 'સોમેટિક માર્કર પૂર્વધારણા',
    guSummary: 'શરીરના સંકેતો અને આંતરિક લાગણીઓ નિર્ણય લેવાની ક્ષમતાને કેવી રીતે માર્ગદર્શન આપે છે.',
    mrTitle: 'सोमॅटिक मार्कर सिद्धांत',
    mrSummary: 'शारीरिक संवेदना आणि अंतःप्रेरणा कशा प्रकारे जटिल निर्णयांमध्ये मेंदूला मदत करतात.',
    teTitle: 'సోమాటిక్ మార్కర్ సిద్ధాంతం',
    teSummary: 'శరీర సంకేతాలు మరియు సహజ అంతర్దృష్టి సరైన నిర్ణయాలు తీసుకోవడంలో ఎలా సహాయపడతాయి.',
    taTitle: 'உடல் உணர்வு கோட்பாடு (Somatic Marker)',
    taSummary: 'உடலின் உள்ளுணர்வு சமிக்ஞைகள் எவ்வாறு பகுத்தறிவு முடிவுகளை வழிநடத்துகின்றன.',
    knTitle: 'ಸೊಮ್ಯಾಟಿಕ್ ಮಾರ್ಕರ್ ಸಿದ್ಧಾಂತ',
    knSummary: 'ದೇಹದ ಆಂತರಿಕ ಸಂವೇದನೆಗಳು ನಿರ್ಧಾರ ಕೈಗೊಳ್ಳುವಲ್ಲಿ ಮೆದುಳಿಗೆ ಹೇಗೆ ಮಾರ್ಗದರ್ಶನ ನೀಡುತ್ತವೆ.',
    mlTitle: 'സൊമാറ്റിക് മാർക്കർ സിദ്ധാന്തം',
    mlSummary: 'ശരീരത്തിൻ്റെ ആന്തരിക പ്രതികരണങ്ങൾ ശരിയായ തീരുമാനങ്ങളിലേക്ക് എങ്ങനെ നയിക്കുന്നു.',
    bnTitle: 'সোমাটিক মার্কার হাইপোথিসিস',
    bnSummary: 'শারীরিক অনুভূতি এবং অবচেতন সংকেত কীভাবে সঠিক সিদ্ধান্ত নিতে সাহায্য করে।',
    paTitle: 'ਸੋਮੈਟਿਕ ਮਾਰਕਰ ਸਿਧਾਂਤ',
    paSummary: 'ਸਰੀਰਕ ਸੰਕੇਤ ਅਤੇ ਅੰਦਰੂਨੀ ਆਵਾਜ਼ ਫੈਸਲਾ ਲੈਣ ਵਿੱਚ ਦਿਮਾਗ ਨੂੰ ਕਿਵੇਂ ਰਾਹ ਦਿਖਾਉਂਦੇ ਹਨ।',
    urTitle: 'سوماتی نشاناتی مفروضہ (Somatic Marker)',
    urSummary: 'جسمانی کیفیات اور دل کی دھڑکن کس طرح عقلی فیصلوں کی رہنمائی کرتی ہے۔',
    orTitle: 'ସୋମାଟିକ୍ ମାର୍କର୍ ଅନୁମାନ',
    orSummary: 'ଶରୀରର ଆଭ୍ୟନ୍ତରୀଣ ସଙ୍କେତ କିପରି ନିଷ୍ପତ୍ତି ନେବାରେ ସାହାଯ୍ୟ କରେ।',
    asTitle: 'সোমেটিক মাৰ্কাৰ অনুমান',
    asSummary: 'শাৰীৰিক সংবেদনাই জটিল সিদ্ধান্ত গ্ৰহণত কেনেকৈ মগজুক বাট দেখুৱায়।',
    citationAuthors: 'Damasio, A. R.',
    citationYear: 1994,
    citationJournal: 'Descartes’ Error: Emotion, Reason, and the Human Brain',
    citationDoi: 'https://doi.org/10.1037/0003-066X.50.4.382',
    caseTitle: 'The Suspicious Warehouse Lease in Bhiwandi',
    caseDomain: 'workplace',
    caseSituation: 'A logistics manager felt an inexplicable nausea and chest tightness while negotiating an unusually cheap warehouse lease in Bhiwandi, Maharashtra.',
    caseOutcome: 'Despite glowing paperwork, the bodily unease prompted a deep municipal registry search that uncovered impending zoning demolition.',
    caseFix: 'The manager codified a dual protocol: treat somatic discomfort not as infallible proof, but as an alarm bell to audit underlying contract clauses.'
  },

  // ==========================================
  // TRACK 7: RELATIONSHIPS & COMMUNICATION
  // ==========================================
  {
    fileName: 'attachmentTheoryAdults.ts',
    varName: 'attachment_theory_adults',
    id: 'attachment_theory_adults',
    categoryId: 'relationships_comm',
    slug: 'attachment-theory-adults',
    difficulty: 'intermediate',
    readTime: 6,
    sortWeight: 5,
    titleEn: 'Adult Attachment Styles: The Invisible Blueprints of Intimacy',
    subtitleEn: 'How childhood bonding patterns shape adult romantic behaviors into Secure, Anxious-Preoccupied, Dismissive-Avoidant, or Fearful-Avoidant styles.',
    summaryEn: 'Originating from John Bowlby’s infant research (1969) and expanded to adults by Hazan & Shaver (1987), attachment theory demonstrates that individuals operate on deep internal working models of self-worth and trust, dictating whether they chase closeness, flee vulnerability, or communicate with grounded security.',
    takeawaysEn: [
      'Anxious individuals equate distance with abandonment; avoidant individuals equate intimacy with loss of autonomy',
      'The "anxious-avoidant trap" is a reciprocal cycle where one partner’s pursuit triggers the other’s withdrawal',
      'Attachment styles are malleable through self-awareness and earned security'
    ],
    titleHinglish: 'Adult Attachment Styles: Rishton Me Darr Aur Dooriyan Kyu Aati Hain',
    subtitleHinglish: 'Samjhein Anxious aur Avoidant styles ka chakra jo couples ke beech jhagdo ki asli wajah hota hai.',
    summaryHinglish: 'Hazan aur Shaver ke research ke mutabiq bachpan ke bonding patterns hamare romantic rishto ko drive karte hain. Anxious partner ko lagta hai ki samne wala chhod kar chala jayega, jabki Avoidant partner ko lagta hai ki zyada closeness se uski azadi chhin jayegi. Dono ek dusre ko trigger karte hain.',
    takeawaysHinglish: [
      'Partner ka late reply anxious person ke liye threat aur avoidant ke liye breathing space hota hai',
      'Jhagdo me personal attacks ke bajaye apni emotional need ko clearly communicate karna seekhein',
      'Earned security ke through kisi bhi attachment style ko heal kiya ja sakta hai'
    ],
    hiTitle: 'Adult Attachment Styles (वयस्क लगाव शैलियाँ)',
    hiSummary: 'बचपन के सुरक्षात्मक अनुभव किस प्रकार वयस्क संबंधों में निकटता, भय और स्वतंत्रता के प्रतिमान तय करते हैं।',
    hiTakeaways: [
      'सुरक्षित लगाव विश्वास और भावनात्मक परिपक्वता को बढ़ावा देता है',
      'चिंतित साथी दूरी से डरता है जबकि बचाववादी साथी निकटता से घबराता है',
      'सचेत संवाद द्वारा संबंधों में अर्जित सुरक्षा (Earned Security) प्राप्त की जा सकती है'
    ],
    guTitle: 'પુખ્ત જોડાણ શૈલીઓ (Attachment Styles)',
    guSummary: 'બાળપણના સંબંધો પુખ્ત વયના પ્રેમ અને વિશ્વાસને કેવી રીતે આકાર આપે છે.',
    mrTitle: 'प्रौढ भावनिक जोडणी प्रकार (Attachment Styles)',
    mrSummary: 'नात्यांमधील जवळीक, भीती आणि विश्वास यावर बालपणातील अनुभवांचा प्रभाव.',
    teTitle: 'అడల్ట్ అటాచ్‌మెంట్ శైలులు',
    teSummary: 'బాంధవ్యాలలో అనుబంధం, భయం మరియు స్వేచ్ఛను నిర్ణయించే అంతర్గత నమూనాలు.',
    taTitle: 'வயதுவந்தோர் பற்றுதல் பாணிகள் (Attachment Styles)',
    taSummary: 'உறவுகளில் நெருக்கம் மற்றும் சுதந்திரத்தை வழிநடத்தும் குழந்தைப்பருவ தாக்கங்கள்.',
    knTitle: 'ವಯಸ್ಕರ ಭಾವನಾತ್ಮಕ ಬಾಂಧವ್ಯ ಶೈಲಿಗಳು',
    knSummary: 'ಸಂಬಂಧಗಳಲ್ಲಿ ನಿಕಟತೆ ಮತ್ತು ಸ್ವಾತಂತ್ರ್ಯವನ್ನು ರೂಪಿಸುವ ಬಾಲ್ಯದ ಅನುಭವಗಳು.',
    mlTitle: 'മുതിർന്നവരിലെ അറ്റാച്ച്മെൻ്റ് ശൈലികൾ',
    mlSummary: 'ബന്ധങ്ങളിലെ അടുപ്പവും സ്വാതന്ത്ര്യവും നിയന്ത്രിക്കുന്ന വൈകാരിക മാതൃകകൾ.',
    bnTitle: 'অ্যাডাল্ট অ্যাটাচমেন্ট স্টাইলস',
    bnSummary: 'শৈশবের বন্ধন কীভাবে প্রাপ্তবয়স্ক সম্পর্কের ঘনিষ্ঠতা ও নিরাপত্তাহীনতাকে নিয়ন্ত্রণ করে।',
    paTitle: 'ਬਾਲਗ ਲਗਾਓ ਸ਼ੈਲੀਆਂ (Attachment Styles)',
    paSummary: 'ਰਿਸ਼ਤਿਆਂ ਵਿੱਚ ਨਜ਼ਦੀਕੀ ਅਤੇ ਆਜ਼ਾਦੀ ਨੂੰ ਪ੍ਰਭਾਵਿਤ ਕਰਨ ਵਾਲੇ ਮਨੋਵਿਗਿਆਨਕ ਪੈਟਰਨ।',
    urTitle: 'بالغ وابستگی کے انداز (Attachment Styles)',
    urSummary: 'بچپن کے تجربات کس طرح محبت اور رشتوں میں خوف اور اعتماد کا تعین کرتے ہیں۔',
    orTitle: 'ପ୍ରୌଢ଼ ଆବେଗିକ ସଂଲଗ୍ନତା ଶୈଳୀ',
    orSummary: 'ସମ୍ପର୍କରେ ନିକଟତା ଓ ଆତ୍ମବିଶ୍ୱାସ ଗଠନରେ ପିଲାଦିନର ପ୍ରଭାବ।',
    asTitle: 'প্ৰাপ্তবয়স্ক সংযোগ শৈলী (Attachment Styles)',
    asSummary: 'সম্পৰ্কত ঘনিষ্ঠতা আৰু বিশ্বাস গঢ়ি তোলাত শৈশৱৰ অনুভৱৰ প্ৰভাৱ।',
    citationAuthors: 'Hazan, C., & Shaver, P.',
    citationYear: 1987,
    citationJournal: 'Journal of Personality and Social Psychology',
    citationDoi: 'https://doi.org/10.1037/0022-3514.52.3.511',
    caseTitle: 'The Silent Dinner in South Mumbai',
    caseDomain: 'relationships',
    caseSituation: 'An anxious partner felt intense abandonment panic when their avoidant spouse came home exhausted and retreated into silent smartphone scrolling.',
    caseOutcome: 'Lashing out with accusations caused the spouse to leave the room entirely, confirming the anxious partner’s worst fears in an escalation spiral.',
    caseFix: 'Both agreed to explicit verbal reassurance: "I love you and I am committed to us, but I need 30 minutes of silence to decompress before we connect."'
  },
  {
    fileName: 'karpmanDramaTriangle.ts',
    varName: 'karpman_drama_triangle',
    id: 'karpman_drama_triangle',
    categoryId: 'relationships_comm',
    slug: 'karpman-drama-triangle',
    difficulty: 'intermediate',
    readTime: 6,
    sortWeight: 6,
    titleEn: 'The Karpman Drama Triangle: Escaping Victim, Persecutor, and Rescuer Roles',
    subtitleEn: 'Stephen Karpman’s model of dysfunctional social games where people rotate between Victim, Persecutor, and Rescuer positions to evade genuine responsibility.',
    summaryEn: 'Developed in 1968 by psychiatrist Stephen Karpman, this transactional analysis model explains recurring interpersonal conflict where participants adopt unconscious roles: the Victim feels helpless, the Rescuer fosters dependency, and the Persecutor blames. As tension peaks, players inevitably switch roles.',
    takeawaysEn: [
      'Rescuing without explicit consent enables helplessness and breeds eventual resentment',
      'The Victim role disempowers the individual from taking constructive agency',
      'Exit the triangle by shifting to the "Winner’s Triangle": Creator, Challenger, and Coach'
    ],
    titleHinglish: 'Karpman Drama Triangle: Rishto Ke Toxic Natak Se Bahar Nikalna',
    subtitleHinglish: 'Kyu parivaar aur office me log Victim, Rescuer aur Blamer ban kar ghanto bekar ki ladai karte hain.',
    summaryHinglish: 'Stephen Karpman ne dikhaya ki log aksar 3 toxic roles me fas jate hain: Bechaara (Victim), Bachane Wala (Rescuer), aur Dosh Dene Wala (Persecutor). Rescuer samne wale ko helpless banata hai, aur jab help ki kadar nahi hoti toh wo khud Persecutor ban jata hai. Is natak se nikal kar Coach aur Creator banna seekhein.',
    takeawaysHinglish: [
      'Har kisi ki problem solve karne ki aadat (Hero complex) rishto ko barbad kar deti hai',
      'Bechaara banne se sympathy milti hai par asli problem solve nahi hoti',
      'Unsolicited advice dena band karein; samne wale ko khud solution dhundne ka mauka dein'
    ],
    hiTitle: 'Karpman Drama Triangle (कार्पमैन ड्रामा त्रिकोण)',
    hiSummary: 'आपसी संबंधों में पीड़ित, उद्धारक और अभियोजक की अचेतन भूमिकाओं का चक्रव्यूह और उससे मुक्ति।',
    hiTakeaways: [
      'बिना मांगे मदद करना सामने वाले को निर्भर और असहाय बनाता है',
      'पीड़ित की भूमिका व्यक्ति की वास्तविक निर्णय क्षमता को छीन लेती है',
      'उद्धारक से मार्गदर्शक (Coach) और पीड़ित से निर्माता (Creator) बनकर त्रिकोण से बाहर निकलें'
    ],
    guTitle: 'કાર્પમેન ડ્રામા ત્રિકોણ',
    guSummary: 'સંબંધોમાં ભોગ બનેલા, તારણહાર અને આરોપ મૂકનારના નકારાત્મક ચક્રમાંથી મુક્તિ.',
    mrTitle: 'कार्पमन ड्रामा ट्रँगल',
    mrSummary: 'नात्यांमधील बळी, तारणहार आणि दोष देणारा या भूमिकांचे विषारी चक्र तोडणे.',
    teTitle: 'కార్ప్‌మన్ డ్రామా ట్రయాంగిల్',
    teSummary: 'సంబంధాలలో బాధితుడు, రక్షకుడు మరియు నిందించే వ్యక్తిగా మారే విషపూరిత చక్రం.',
    taTitle: 'கார்ப்மேன் நாடக முக்கோணம் (Drama Triangle)',
    taSummary: 'உறவுகளில் பாதிக்கப்பட்டவர், மீட்பவர் மற்றும் தண்டிப்பவர் பாத்திரங்களை தவிர்ப்பது எப்படி.',
    knTitle: 'ಕಾರ್ಪ್‌ಮನ್ ಡ್ರಾಮಾ ತ್ರಿಕೋನ',
    knSummary: 'ಸಂಬಂಧಗಳಲ್ಲಿ ಬಲಿಪಶು, ರಕ್ಷಕ ಮತ್ತು ಆರೋಪಿಯ ಪಾತ್ರಗಳ ವಿಷವರ್ತುಲದಿಂದ ಹೊರಬರುವ ವಿಧಾನ.',
    mlTitle: 'കാർപ്മാൻ ഡ്രാമ ട്രയാംഗിൾ',
    mlSummary: 'വ്യക്തിബന്ധങ്ങളിലെ ഇര, രക്ഷകൻ, പീഡകൻ എന്നീ റോളുകളുടെ വിഷമവൃത്തം.',
    bnTitle: 'কার্পম্যান ড্রামা ট্রায়াঙ্গেল',
    bnSummary: 'সম্পর্কের মধ্যে শিকার, উদ্ধারকর্তা ও দোষারোপকারীর বিষাক্ত ভূমিকার অবসান।',
    paTitle: 'ਕਾਰਪਮੈਨ ਡਰਾਮਾ ਤ੍ਰਿਕੋਣ',
    paSummary: 'ਰਿਸ਼ਤਿਆਂ ਵਿੱਚ ਪੀੜਤ, ਰੱਖਿਅਕ ਅਤੇ ਦੋਸ਼ੀ ਦੀਆਂ ਗੈਰ-ਸਿਹਤਮੰਦ ਭੂਮਿਕਾਵਾਂ ਤੋਂ ਬਚਣਾ।',
    urTitle: 'کارپ مین ڈراما تکون (Drama Triangle)',
    urSummary: 'تعلقات میں مظلوم، نجات دہندہ اور الزام تراش کے غیر صحت مند کرداروں سے چھٹکارا۔',
    orTitle: 'କାର୍ପମ୍ୟାନ୍ ଡ୍ରାମା ତ୍ରିକୋଣ',
    orSummary: 'ସମ୍ପର୍କରେ ପୀଡ଼ିତ, ରକ୍ଷକ ଓ ଅଭିଯୁକ୍ତ ଭୂମିକାର ନକାରାତ୍ମକ ଚକ୍ରରୁ ମୁକ୍ତି।',
    asTitle: 'কাৰ্পমেন ড্ৰামা ত্ৰিকোণ',
    asSummary: 'সম্পৰ্কত ভুক্তভোগী, ৰক্ষাকৰ্তা আৰু দোষাৰোপকাৰীৰ বিষাক্ত চক্ৰৰ পৰা মুক্তি।',
    citationAuthors: 'Karpman, S. B.',
    citationYear: 1968,
    citationJournal: 'Transactional Analysis Bulletin',
    citationDoi: 'https://doi.org/10.1177/036215376800702603',
    caseTitle: 'The Extended Family Financial Drama in Jaipur',
    caseDomain: 'relationships',
    caseSituation: 'An elder brother repeatedly paid off his younger brother’s reckless speculative stock trading debts without holding him accountable.',
    caseOutcome: 'When the elder brother finally refused, the younger brother labeled him cruel (Persecutor), casting himself as the abandoned Victim.',
    caseFix: 'The elder brother stepped into the Coach role: offering financial literacy mentoring and emotional support, but zero unconditional monetary bailouts.'
  },

  // ==========================================
  // TRACK 8: SOCIAL MEDIA PSYCHOLOGY
  // ==========================================
  {
    fileName: 'onlineDisinhibitionEffect.ts',
    varName: 'online_disinhibition_effect',
    id: 'online_disinhibition_effect',
    categoryId: 'social_media_tech',
    slug: 'online-disinhibition-effect',
    difficulty: 'intermediate',
    readTime: 6,
    sortWeight: 5,
    titleEn: 'The Online Disinhibition Effect: Why Normal People Turn Toxic Behind Screens',
    subtitleEn: 'John Suler’s framework demonstrating how anonymity, invisibility, and asynchronous communication dismantle normal social restraints.',
    summaryEn: 'Identified by psychologist John Suler in 2004, the online disinhibition effect explains why people say and do things in cyberspace that they would never do in face-to-face reality, driven by dissociative anonymity ("You don’t know me"), invisibility ("You can’t see me"), and asynchronous communication.',
    takeawaysEn: [
      'Lack of real-time eye contact and somatic feedback eliminates natural empathy brakes',
      'Text communication leads to solipsistic introjection—reading messages in an internalized hostile voice',
      'Minimizing perceived authority makes users view digital forums as lawless arenas'
    ],
    titleHinglish: 'Online Disinhibition Effect: Screen Ke Peeche Log Toxic Kyu Ho Jaate Hain',
    subtitleHinglish: 'Kyu aam shareef log Twitter aur Instagram comments me gaaliyan aur nafrat failane lagte hain.',
    summaryHinglish: 'John Suler ne 2004 me prove kiya ki jab insaan kisi ka chehra samne nahi dekhta, toh uske dimaag ka empathy circuit band ho jata hai. Anonymity aur physical distance ki wajah se lagta hai ki koi consequences nahi honge. Screen par likhte waqt lagta hai hum kisi video game me hain, kisi real human ke sath nahi.',
    takeawaysHinglish: [
      'Samne wale ke aakho ke expressions na dikhne se dimaag ko lagta hai use dard nahi ho raha',
      'Comment likhne se pehle socho: "Kya main ye baat iske muh par aamne-saamne bol sakta hu?"',
      'Internet troll aksar real life me kamzor aur frustrated hote hain'
    ],
    hiTitle: 'Online Disinhibition Effect (ऑनलाइन असंयम प्रभाव)',
    hiSummary: 'स्क्रीन की गोपनीयता और अदृश्यता के कारण सामान्य व्यक्तियों द्वारा ऑनलाइन अपमानजनक या आक्रामक व्यवहार करना।',
    hiTakeaways: [
      'आमने-सामने के संपर्क के अभाव में स्वाभाविक सहानुभूति समाप्त हो जाती है',
      'अनामिकता व्यक्ति को नैतिक जवाबदेही से मुक्त होने का भ्रम देती है',
      'डिजिटल टिप्पणियों को एक वास्तविक मानवीय संवाद की तरह देखने से संयम लौटता है'
    ],
    guTitle: 'ઓનલાઇન અસંયમ પ્રભાવ',
    guSummary: 'સ્ક્રીન પાછળ અદ્રશ્ય હોવાને કારણે લોકોનું આક્રમક અને ઝેરી વર્તન.',
    mrTitle: 'ऑनलाइन असंयम प्रभाव',
    mrSummary: 'स्क्रीनच्या आड चेहऱ्याचा अभाव आणि अनामिकतेमुळे इंटरनेटवर वाढणारी आक्रमकता.',
    teTitle: 'ఆన్‌లైన్ నిరోధకతా లోపం (Disinhibition Effect)',
    teSummary: 'స్క్రీన్ వెనుక అనామకత్వం వల్ల సాధారణ వ్యక్తులు కూడా అసభ్యంగా ప్రవర్తించే మనస్తత్వం.',
    taTitle: 'ஆன்லைன் கட்டுப்பாடின்மை விளைவு (Online Disinhibition)',
    taSummary: 'திரையின் பின்னால் முகம் தெரியாததால் மனிதர்கள் காட்டும் கடுமையான ஆக்ரோஷ நடத்தை.',
    knTitle: 'ಆನ್‌ಲೈನ್ ಅಸಂಯಮ ಪರಿಣಾಮ',
    knSummary: 'ಪರದೆಯ ಹಿಂದೆ ಮುಖ ಕಾಣಿಸದ ಕಾರಣ ಸಾಮಾನ್ಯ ಜನರು ತೋರುವ ಅಸಭ್ಯ ವರ್ತನೆ.',
    mlTitle: 'ഓൺലൈൻ ഡിസിൻഹിബിഷൻ ഇഫക്റ്റ്',
    mlSummary: 'സ്ക്രീനിന് പിന്നിലെ അജ്ഞാതാവസ്ഥ മനുഷ്യരിൽ ഉണ്ടാക്കുന്ന അതിരുകടന്ന പെരുമാറ്റം.',
    bnTitle: 'অনলাইন ডিসইনহিবিশন ইফেক্ট',
    bnSummary: 'পর্দার আড়ালে বেনামী থাকার কারণে অনলাইনে মানুষের আক্রমণাত্মক আচরণের কারণ।',
    paTitle: 'ਔਨਲਾਈਨ ਅਸੰਜਮ ਪ੍ਰਭਾਵ',
    paSummary: 'ਸਕ੍ਰੀਨ ਪਿੱਛੇ ਅਗਿਆਤ ਹੋਣ ਕਾਰਨ ਇੰਟਰਨੈੱਟ ਉੱਤੇ ਵੱਧਦੀ ਹਮਲਾਵਰਤਾ।',
    urTitle: 'آن لائن بے باکی کا اثر (Online Disinhibition)',
    urSummary: 'اسکرین کے پیچھے چہرہ چھپنے کی وجہ سے انٹرنیٹ پر لوگوں کا زہریلا اور جارحانہ رویہ۔',
    orTitle: 'ଅନଲାଇନ୍ ଅସଂଯମ ପ୍ରଭାବ',
    orSummary: 'ପରଦା ପଛରେ ଅଜ୍ଞାତ ରହି ଅନ୍ୟକୁ ଅପମାନିତ କରିବାର ମାନସିକତା।',
    asTitle: 'অনলাইন অসংযম প্ৰভাৱ',
    asSummary: 'পৰ্দাৰ আঁৰত পৰিচয় গোপন থকাৰ বাবে ইণ্টাৰনেটত বৃদ্ধি পোৱা আক্ৰমণাত্মক আচৰণ।',
    citationAuthors: 'Suler, J.',
    citationYear: 2004,
    citationJournal: 'CyberPsychology & Behavior',
    citationDoi: 'https://doi.org/10.1089/1094931041291295',
    caseTitle: 'The LinkedIn Roast of an Entry-Level Engineer in Bengaluru',
    caseDomain: 'social_media',
    caseSituation: 'A junior developer shared an innocent career milestone post on LinkedIn that was shared to Twitter/X without context.',
    caseOutcome: 'Over 500 anonymous accounts launched venomous mockery and personal insults they would never utter in a conference hallway.',
    caseFix: 'The company established digital wellness norms: never post feedback online that you would hesitate to deliver face-to-face over tea.'
  },
  {
    fileName: 'doomscrollingCycle.ts',
    varName: 'doomscrolling_cycle',
    id: 'doomscrolling_cycle',
    categoryId: 'social_media_tech',
    slug: 'doomscrolling-cycle',
    difficulty: 'beginner',
    readTime: 5,
    sortWeight: 6,
    titleEn: 'The Doomscrolling Cycle: The Evolutionary Trap of Endless Catastrophe',
    subtitleEn: 'The compulsive consumption of distressing negative news driven by evolutionary threat vigilance and algorithmic dopamine loops.',
    summaryEn: 'Documented extensively during recent crises (Sharma et al. 2022), doomscrolling exploits our ancestral survival instinct to scan for impending predators. In modern algorithmic ecosystems, social platforms constantly serve sensational crises, trapping the brain in an endless state of cortisol-fueled anxiety without action.',
    takeawaysEn: [
      'Evolution designed our brains to prioritize threat signals over positive news',
      'Passive digital consumption provides zero defensive utility while triggering chronic stress',
      'Breaking the cycle requires physical friction: app timers, grayscale mode, and scheduled news intervals'
    ],
    titleHinglish: 'Doomscrolling: Raat Ke 2 Baje Tak Buri Khabrein Dekhne Ka Rog',
    subtitleHinglish: 'Kyu hamara dimaag negative aur shocking videos scroll karne me fas jata hai.',
    summaryHinglish: 'Purane zamaane me shikar aur dushmano ke khatre ko janne se jaan bachti thi. Hamare phone ke algorithms is survival instinct ka misuse karte hain. Jitna zyada aap war, crimes aur tragedy ki khabre padhte hain, utna dimaag alert ho jata hai aur phone rakhne nahi deta.',
    takeawaysHinglish: [
      'Buri khabrein scroll karne se koi solution nahi nikalta, bas mental peace barbad hoti hai',
      'Bed me phone le jana band karein aur phone screen ko grayscale (black & white) mode me daalein',
      'Information diet ko control karein: din me sirf 15 minute news check karein'
    ],
    hiTitle: 'Doomscrolling (नकारात्मक समाचारों का अंतहीन चक्र)',
    hiSummary: 'आदिम संकट-चेतावनी प्रवृत्ति और एल्गोरिथम के जाल में फंसकर लगातार नकारात्मक समाचारों को पढ़ने की आदत।',
    hiTakeaways: [
      'मानव मस्तिष्क नकारात्मकता को जीवित रहने की रक्षात्मक युक्ति समझता है',
      'अंतहीन स्क्रॉलिंग तनाव हार्मोन (कोर्टिसोल) को अनियंत्रित रूप से बढ़ाती है',
      'स्क्रीन समय सीमा और रात्रि में फोन से दूरी मानसिक शांति की पुनर्स्थापना करती है'
    ],
    guTitle: 'ડૂમસ્ક્રોલિંગ (નકારાત્મક સમાચારોનું વળગણ)',
    guSummary: 'મોડી રાત સુધી નકારાત્મક અને ચિંતાજનક સમાચારો સતત વાંચવાની અવિચારી ટેવ.',
    mrTitle: 'डूमस्क्रोलिंग (नकारात्मक बातम्यांचे व्यसन)',
    mrSummary: 'तणावपूर्ण आणि धक्कादायक बातम्या अविरतपणे वाचण्याची सवय आणि त्याचे दुष्परिणाम.',
    teTitle: 'డూమ్‌స్క్రోలింగ్ (నిరంతర ప్రతికూల వార్తల వ్యసనం)',
    teSummary: 'భయానక వార్తలను మరియు సంఘటనలను నిరంతరం స్క్రోల్ చేస్తూ చూసే మానసిక ఉచ్చు.',
    taTitle: 'டூம்ஸ்க்ரோலிங் (எதிர்மறை செய்திகளின் சுழல்)',
    taSummary: 'தொடர்ந்து ஆபத்தான மற்றும் மன அழுத்தத்தை உண்டாக்கும் செய்திகளைப் பார்க்கும் பழக்கம்.',
    knTitle: 'ಡೂಮ್‌ಸ್ಕ್ರೋಲಿಂಗ್ (ನಕಾರಾತ್ಮಕ ಸುದ್ದಿಗಳ ಚಟ)',
    knSummary: 'ಆತಂಕಕಾರಿ ಮತ್ತು ಕೆಟ್ಟ ಸುದ್ದಿಗಳನ್ನು ಸತತವಾಗಿ ಸ್ಕ್ರಾಲ್ ಮಾಡುವ ಮಾನಸಿಕ ಚಕ್ರವ್ಯೂಹ.',
    mlTitle: 'ഡൂംസ്ക്രോളിംഗ് (നെഗറ്റീവ് വാർത്തകളുടെ കുരുക്ക്)',
    mlSummary: 'മാനസിക സമ്മർദ്ദം ഉണ്ടാക്കുന്ന ദാരുണ വാർത്തകൾ നിർത്താതെ നോക്കിക്കൊണ്ടിരിക്കുന്ന അവസ്ഥ.',
    bnTitle: 'ডুমস্ক্রোলিং (নেতিবাচক সংবাদের অন্তহীন চক্র)',
    bnSummary: 'ভয়াবহ এবং মানসিক চাপ সৃষ্টিকারী খবর একটানা স্ক্রোল করার ক্ষতিকর অভ্যাস।',
    paTitle: 'ਡੂਮਸਕ੍ਰੋਲਿੰਗ (ਨਕਾਰਾਤਮਕ ਖਬਰਾਂ ਦੀ ਲਤ)',
    paSummary: 'ਤਣਾਅ ਭਰੀਆਂ ਅਤੇ ਦੁਖਦਾਈ ਖ਼ਬਰਾਂ ਨੂੰ ਲਗਾਤਾਰ ਸਕ੍ਰੋਲ ਕਰਨ ਦਾ ਮਾਨਸਿਕ ਜਾਲ।',
    urTitle: 'ڈوم اسکرولنگ (منفی خبروں کا نہ ختم ہونے والا چکر)',
    urSummary: 'مسلسل پریشان کن اور خوفناک خبریں پڑھتے رہنے کی نفسیاتی عادت۔',
    orTitle: 'ଡୁମ୍‌ସ୍କ୍ରୋଲିଂ (ନକାରାତ୍ମକ ଖବରର ନିଶା)',
    orSummary: 'ଭୟ ଓ ଚିନ୍ତା ବଢ଼ାଉଥିବା ଖବରକୁ ଲଗାତାର ସ୍କ୍ରୋଲ୍ କରି ଦେଖିବାର ଅଭ୍ୟାସ।',
    asTitle: 'ডুমস্ক্ৰলিং (নেতিবাচক বাতৰিৰ চক্ৰ)',
    asSummary: 'উদ্বেগজনক আৰু বেয়া বাতৰি অবিৰতভাৱে স্ক্ৰল কৰি থকাৰ ক্ষতিকাৰক মানসিকতা।',
    citationAuthors: 'Sharma, B., Lee, S. S., & Johnson, B. K.',
    citationYear: 2022,
    citationJournal: 'Technology, Mind, and Behavior',
    citationDoi: 'https://doi.org/10.1037/tmb0000059',
    caseTitle: 'The Midnight Stock Market Crash Panic in Pune',
    caseDomain: 'health',
    caseSituation: 'A software engineer in Pune spent 3 consecutive nights doomscrolling sensational YouTube financial collapse predictions until 3:30 AM.',
    caseOutcome: 'Severe chronic insomnia triggered a daytime panic attack during an architecture review, causing him to liquidate sound long-term mutual funds at a loss.',
    caseFix: 'The engineer instituted a strict "digital sunset" rule: phone docked in the living room at 10 PM, swapped for a physical book.'
  },

  // ==========================================
  // TRACK 9: CONSUMER & ADVERTISING PSYCHOLOGY
  // ==========================================
  {
    fileName: 'leftDigitBias.ts',
    varName: 'left_digit_bias',
    id: 'left_digit_bias',
    categoryId: 'consumer_advertising',
    slug: 'left-digit-bias',
    difficulty: 'beginner',
    readTime: 5,
    sortWeight: 5,
    titleEn: 'The Left-Digit Bias: Why ₹999 Feels So Much Cheaper Than ₹1,000',
    subtitleEn: 'Thomas & Morwitz’s empirical proof that human cognition anchors on the leftmost numeral before processing the full numerical magnitude.',
    summaryEn: 'Discovered in consumer behavior research by Thomas & Morwitz (2005), left-digit bias occurs because human reading orientation processes numbers left-to-right. When looking at ₹999 vs ₹1,000, the mind anchors on the "9" versus the "1", creating the subconscious illusion of an enormous category drop rather than a single rupee difference.',
    takeawaysEn: [
      'The human brain reads prices left-to-right, anchoring instantaneously on the primary integer',
      'The drop from ₹2,000 to ₹1,999 feels like a hundred-rupee discount rather than a ₹1 difference',
      'Defend yourself by rounding every price ending in 99 up to the next round hundred immediately'
    ],
    titleHinglish: 'Left-Digit Bias: Kyu ₹999 Lagta Hai ₹1,000 Se Bohot Sasta',
    subtitleHinglish: 'Retailers aur e-commerce sites kyu har cheez ka price 99 ya 999 par khatam karte hain.',
    summaryHinglish: 'Thomas aur Morwitz ke research ne prove kiya ki hamara dimaag numbers ko left se right padhta hai. Jaise hi aankh pehle number "9" ko dekhti hai, dimaag use 900 ki range me daal deta hai, jabki ₹1000 ko dekhte hi dimaag use 1,000 ki category me dalta hai. Asal me farq sirf ₹1 ka hota hai!',
    takeawaysHinglish: [
      'Shopping karte waqt ₹999 ko turant dimaag me ₹1000 count karein',
      'Left-digit trick ka maqsad aapko product sasta dikha kar impulsive shopping karwana hota hai',
      'Kharidne se pehle total bill me delivery aur GST jodkar actual calculation karein'
    ],
    hiTitle: 'Left-Digit Bias (बायां अंक पूर्वाग्रह)',
    hiSummary: 'मनुष्य द्वारा संख्याओं को बाएं से दाएं पढ़ने के कारण ₹999 का ₹1,000 से काफी सस्ता प्रतीत होना।',
    hiTakeaways: [
      'मस्तिष्क पहले अंक पर लंगर (anchor) डाल देता है',
      'मात्र एक रुपये का अंतर भी श्रेणीबद्ध अंतर (Category shift) का भ्रम पैदा करता है',
      'खरीदारी करते समय प्रत्येक .99 वाले मूल्य को सीधे अगले पूर्णांक में राउंड करें'
    ],
    guTitle: 'લેફ્ટ-ડિજિટ બાયસ (ડાબા અંકનો પ્રભાવ)',
    guSummary: 'ગ્રાહક મનોવિજ્ઞાનમાં ₹999 શા માટે ₹1,000 કરતાં ઘણું સસ્તું લાગે છે તેનું કારણ.',
    mrTitle: 'डाव्या अंकाचा प्रभाव (Left-Digit Bias)',
    mrSummary: 'किंमत वाचताना डाव्या अंकावर लक्ष केंद्रित झाल्यामुळे ₹९९९ हे ₹१,००० पेक्षा खूपच स्वस्त वाटणे.',
    teTitle: 'లెఫ్ట్-డిజిట్ బయాస్',
    teSummary: 'ధరలు చూసినప్పుడు మొదటి అంకెను బట్టి ₹999 అనేది ₹1,000 కంటే చాలా తక్కువగా కనిపించే భ్రమ.',
    taTitle: 'இடது இலக்க சார்பு (Left-Digit Bias)',
    taSummary: 'விலை நிர்ணயத்தில் ₹999 என்பது ₹1,000 ஐ விட மிகக் குறைவானதாக தோன்றும் உளவியல் தந்திரம்.',
    knTitle: 'ಎಡ ಅಂಕಿಯ ಪಕ್ಷಪಾತ (Left-Digit Bias)',
    knSummary: 'ಬೆಲೆಗಳನ್ನು ನೋಡಿದಾಗ ₹999 ಎಂಬುದು ₹1,000 ಕ್ಕಿಂತ ತುಂಬಾ ಅಗ್ಗವೆಂದು ಭಾಸವಾಗುವ ಭ್ರಮೆ.',
    mlTitle: 'ലെഫ്റ്റ് ഡിജിറ്റ് ബയസ്',
    mlSummary: 'വിലയിലെ ആദ്യ സംഖ്യ നോക്കി ₹999 എന്നത് ₹1,000-നേക്കാൾ വളരെ കുറവാണെന്ന് തെറ്റിദ്ധരിക്കുന്ന അവസ്ഥ.',
    bnTitle: 'লেফট-ডিজিট বায়াস',
    bnSummary: 'মূল্য নির্ধারণে ₹৯৯৯ কেন ₹১,০০০-এর চেয়ে অনেক বেশি সস্তা মনে হয় তার মনস্তাত্ত্বিক কারণ।',
    paTitle: 'ਖੱਬੇ ਅੰਕ ਦਾ ਪੱਖਪਾਤ (Left-Digit Bias)',
    paSummary: 'ਕੀਮਤ ਪੜ੍ਹਦੇ ਸਮੇਂ ₹999 ਕਿਉਂ ₹1,000 ਨਾਲੋਂ ਬਹੁਤ ਸਸਤਾ ਪ੍ਰਤੀਤ ਹੁੰਦਾ ਹੈ।',
    urTitle: 'بائیں ہندسے کی جانبداری (Left-Digit Bias)',
    urSummary: 'قیمتوں میں ₹999 کس طرح ₹1000 کے مقابلے میں بہت سستا معلوم ہوتا ہے۔',
    orTitle: 'ବାମ ଅଙ୍କ ପ୍ରଭାବ (Left-Digit Bias)',
    orSummary: 'ଗ୍ରାହକ ମନସ୍ତତ୍ତ୍ୱରେ ₹୯୯୯ କିପରି ₹୧,୦୦୦ ଠାରୁ ବହୁତ କମ୍ ମନେହୁଏ।',
    asTitle: 'বাওঁ অংকৰ পক্ষপাতিত্ব (Left-Digit Bias)',
    asSummary: 'মূল্য নিৰ্ধাৰণত ₹৯৯৯ টকা কিয় ₹১,০০০ টকাতকৈ বহু কম যেন লাগে।',
    citationAuthors: 'Thomas, M., & Morwitz, V.',
    citationYear: 2005,
    citationJournal: 'Journal of Consumer Research',
    citationDoi: 'https://doi.org/10.1086/429600',
    caseTitle: 'The Festive Electronics Sale in Delhi',
    caseDomain: 'consumer_advertising',
    caseSituation: 'A consumer in Lajpat Nagar felt an urge to buy a smart vacuum cleaner priced at ₹19,999, believing it was "within the teens".',
    caseOutcome: 'After paying shipping and taxes, the total was ₹21,400, instantly dissolving the mental accounting boundary.',
    caseFix: 'The buyer adopted an infallible mental rule: always round prices ending in 999 to the nearest ceiling thousand plus 10% taxes.'
  },

  // ==========================================
  // TRACK 10: LEARNING PSYCHOLOGY
  // ==========================================
  {
    fileName: 'testingEffect.ts',
    varName: 'testing_effect',
    id: 'testing_effect',
    categoryId: 'learning_psychology',
    slug: 'testing-effect',
    difficulty: 'beginner',
    readTime: 5,
    sortWeight: 5,
    titleEn: 'The Testing Effect: Why Retrieval Beats Re-Reading Every Time',
    subtitleEn: 'Roediger & Karpicke’s definitive research showing that taking a quiz consolidates long-term memory far more effectively than passive re-reading.',
    summaryEn: 'Validated by cognitive psychologists Henry Roediger and Jeffrey Karpicke in 2006, the testing effect (retrieval practice) demonstrates that the act of actively retrieving information from memory fundamentally alters the memory trace, producing stronger neural pathways and dramatically reducing forgetting curves compared to repeated study.',
    takeawaysEn: [
      'Passive re-reading creates an illusion of competence without building durable memory pathways',
      'The mental effort required to pull an answer from memory strengthens synaptic connectivity',
      'Frequent low-stakes self-testing is the single most potent study intervention in cognitive science'
    ],
    titleHinglish: 'Testing Effect: Baar Baar Padhne Se Achha Hai Khud Ka Test Lena',
    subtitleHinglish: 'Kyu book ko 5 baar re-read karne ke bajaye flashcards aur quiz se 10x zyada yaad rehta hai.',
    summaryHinglish: 'Roediger aur Karpicke ke world-famous experiment me dekha gaya ki jo students book ko baar baar padhte hain, unhe lagta hai ki sab yaad ho gaya (illusion of competence). Lekin exam me wahi jeet te hain jinhone book band karke recall karne ki koshish ki thi. Dimaag me information daalne se zyada, dimaag se information bahar nikalne se memory banti hai.',
    takeawaysHinglish: [
      'Re-reading se dimag me comfort milta hai par exam me sab bhool jata hai',
      'Har page padhne ke baad book band karein aur khud se poochein: "Maine abhi kya seekha?"',
      'Active recall aur flashcards se revision time aadha aur retention double ho jata hai'
    ],
    hiTitle: 'The Testing Effect (परीक्षण प्रभाव)',
    hiSummary: 'बार-बार पढ़ने के स्थान पर सक्रिय रूप से स्मृति से ज्ञान को याद करने (Retrieval) से दीर्घकालिक स्मृति का निर्माण।',
    hiTakeaways: [
      'निष्क्रिय रूप से पुनः पढ़ना केवल ज्ञान की समझ का भ्रम (Illusion of competence) पैदा करता है',
      'स्मृति से उत्तर खोजने का मानसिक प्रयास न्यूरल पाथवे को स्थायी रूप से मजबूत बनाता है',
      'स्व-मूल्यांकन और क्विज़ अध्ययन की सबसे वैज्ञानिक और प्रभावशाली विधि है'
    ],
    guTitle: 'ટેસ્ટિંગ ઇફેક્ટ (પરીક્ષણ પ્રભાવ)',
    guSummary: 'વારંવાર વાંચવા કરતાં જાતે ટેસ્ટ આપીને યાદ કરવાની પદ્ધતિ વધુ અસરકારક કેમ છે.',
    mrTitle: 'चाचणी प्रभाव (Testing Effect)',
    mrSummary: 'पुन्हा पुन्हा वाचण्यापेक्षा स्वतःची चाचणी घेतल्याने माहिती दीर्घकाळ कशी स्मरणात राहते.',
    teTitle: 'టెస్టింగ్ ఎఫెక్ట్ (పరీక్షా ప్రభావం)',
    teSummary: 'పదే పదే చదవడం కంటే స్వీయ పరీక్షల ద్వారా జ్ఞాపకశక్తిని బలోపేతం చేసుకునే విధానం.',
    taTitle: 'சோதனை விளைவு (Testing Effect)',
    taSummary: 'மீண்டும் மீண்டும் வாசிப்பதை விட சுயமாக தேர்வு எழுதுவது நீண்டகால நினைவாற்றலை உருவாக்கும்.',
    knTitle: 'ಪರೀಕ್ಷಾ ಪರಿಣಾಮ (Testing Effect)',
    knSummary: 'ಮತ್ತೆ ಮತ್ತೆ ಓದುವುದಕ್ಕಿಂತ ಸ್ವಯಂ ಪರೀಕ್ಷೆ ತೆಗೆದುಕೊಳ್ಳುವುದು ದೀರ್ಘಕಾಲದ ನೆನಪಿಗೆ ಸಹಕಾರಿ.',
    mlTitle: 'ടെസ്റ്റിംഗ് ഇഫക്റ്റ്',
    mlSummary: 'വീണ്ടും വീണ്ടും വായിക്കുന്നതിനേക്കാൾ സ്വയം പരീക്ഷിക്കുന്നത് ഓർമ്മശക്തി വർദ്ധിപ്പിക്കുന്നു.',
    bnTitle: 'টেস্টিং ইফেক্ট',
    bnSummary: 'বারবার পড়ার চেয়ে কুইজ বা পরীক্ষার মাধ্যমে স্মৃতি থেকে তথ্য উদ্ধার করার কার্যকারিতা।',
    paTitle: 'ਪਰੀਖਣ ਪ੍ਰਭਾਵ (Testing Effect)',
    paSummary: 'ਵਾਰ-ਵਾਰ ਪੜ੍ਹਨ ਨਾਲੋਂ ਆਪਣੇ ਆਪ ਦਾ ਟੈਸਟ ਲੈ ਕੇ ਯਾਦ ਰੱਖਣ ਦੀ ਵਿਗਿਆਨਕ ਵਿਧੀ।',
    urTitle: 'امتحانی اثر (Testing Effect)',
    urSummary: 'بار بار پڑھنے کے بجائے خود سے ٹیسٹ لے کر معلومات کو مستقل یاد رکھنے کا طریقہ۔',
    orTitle: 'ପରୀକ୍ଷଣ ପ୍ରଭାବ (Testing Effect)',
    orSummary: 'ବାରମ୍ବାର ପଢ଼ିବା ଅପେକ୍ଷା ନିଜର ପରୀକ୍ଷା ନେବା ଦ୍ୱାରା ସ୍ମୃତିଶକ୍ତି କିପରି ଦୃଢ଼ ହୁଏ।',
    asTitle: 'পৰীক্ষণ প্ৰভাৱ (Testing Effect)',
    asSummary: 'বাৰে বাৰে পঢ়াতকৈ নিজৰ পৰীক্ষা লৈ মনত ৰখাৰ বৈজ্ঞানিক পদ্ধতি।',
    citationAuthors: 'Roediger, H. L., & Karpicke, J. D.',
    citationYear: 2006,
    citationJournal: 'Psychological Science',
    citationDoi: 'https://doi.org/10.1111/j.1467-9280.2006.01709.x',
    caseTitle: 'The UPSC Aspirant in Mukherjee Nagar Delhi',
    caseDomain: 'education',
    caseSituation: 'A civil services aspirant highlighted NCERT textbooks in 4 different colored pens, re-reading modern history 6 times over 4 months.',
    caseOutcome: 'During the full-length mock test, the aspirant suffered blank-out on simple chronologies despite feeling completely familiar with the pages.',
    caseFix: 'He pivoted to active blurting and timed quizzes: reading 15 minutes, closing the book, and drafting recall outlines on a blank notepad.'
  },

  // ==========================================
  // TRACK 11: CRITICAL THINKING
  // ==========================================
  {
    fileName: 'secondOrderThinking.ts',
    varName: 'second_order_thinking',
    id: 'second_order_thinking',
    categoryId: 'critical_thinking',
    slug: 'second-order-thinking',
    difficulty: 'advanced',
    readTime: 6,
    sortWeight: 6,
    titleEn: 'Second-Order Thinking: Asking "And Then What?"',
    subtitleEn: 'Howard Marks’ framework distinguishing first-order simplicity from second-order strategic foresight in complex systemic decisions.',
    summaryEn: 'Popularized by legendary investor Howard Marks and systems theorists, second-order thinking is the disciplined practice of evaluating not just the immediate, obvious consequences of an action (first-order), but the subsequent downstream reactions, unintended incentives, and feedback loops (second and third-order effects).',
    takeawaysEn: [
      'First-order thinking solves for immediate gratification and creates long-term crises',
      'Second-order thinkers ask: "And then what happens?" and "How will people’s incentives adjust?"',
      'Virtually all political and organizational blunders stem from blind first-order interventions'
    ],
    titleHinglish: 'Second-Order Thinking: Pehla Asar Nahi, Uske Baad Ka Asar Socho',
    subtitleHinglish: 'Kyu har simple solution baad me ek bohot badi nayi problem paida kar deta hai.',
    summaryHinglish: 'Howard Marks ne samjhaya ki First-Order thinker sirf pehla step dekhta hai: "Bhookh lagi hai toh chocolate khao." Second-Order thinker agla step dekhta hai: "Sugar spike aayega, lethargic hunga aur weight badhega." Har faisle ke baad khud se poochein: "Aur uske baad kya hoga?"',
    takeawaysHinglish: [
      'Short-term fayde aksar long-term barbadi ka rasta bante hain',
      'Kisi bhi nayi policy ya rule ko lagane se pehle socho: "Log iska galat faayda kaise uthayenge?"',
      'Exceptional thinkers wahi hote hain jo 2-3 steps aage ki consequences calculate karte hain'
    ],
    hiTitle: 'Second-Order Thinking (द्वितीय-क्रम चिंतन)',
    hiSummary: 'निर्णय के तात्कालिक प्रभाव के परे दीर्घकालिक परिणामों और अप्रत्याशित प्रतिक्रियाओं का पूर्वानुमान।',
    hiTakeaways: [
      'प्रथम-क्रम चिंतन त्वरित संतुष्टि देखता है और भविष्य की समस्याओं को जन्म देता है',
      'द्वितीय-क्रम विचारक निरंतर पूछता है: "और फिर इसके बाद क्या होगा?"',
      'जटिल प्रणालियों में प्रत्येक हस्तक्षेप नए प्रोत्साहन (Incentives) और प्रति-प्रतिक्रियाएं उत्पन्न करता है'
    ],
    guTitle: 'સેકન્ડ-ઓર્ડર થિંકિંગ (દૂરગામી વિચારસરણી)',
    guSummary: 'નિર્ણયના ત્વરિત પરિણામ ઉપરાંત લાંબા ગાળાની અસરો અને પરિણામોનું વિશ્લેષણ.',
    mrTitle: 'दुसऱ्या फळीचा विचार (Second-Order Thinking)',
    mrSummary: 'तात्काळ फायद्याऐवजी निर्णयाचे दूरगामी परिणाम आणि त्याचे साखळी परिणाम ओळखणे.',
    teTitle: 'సెకండ్ ఆర్డర్ థింకింగ్ (దూరదృష్టి ఆలోచన)',
    teSummary: 'తక్షణ ఫలితాలకే పరిమితం కాకుండా భవిష్యత్ పరిణామాలను ముందుగానే ఊహించే నైపుణ్యం.',
    taTitle: 'இரண்டாம் நிலை சிந்தனை (Second-Order Thinking)',
    taSummary: 'ஒரு முடிவின் உடனடி விளைவைத் தாண்டி அதன் நீண்டகால பின்விளைவுகளை கணிக்கும் கலை.',
    knTitle: 'ಸೆಕೆಂಡ್ ಆರ್ಡರ್ ಥಿಂಕಿಂಗ್ (ದೂರದೃಷ್ಟಿಯ ಚಿಂತನೆ)',
    knSummary: 'ತ್ವರಿತ ಪರಿಣಾಮಗಳಿಗಿಂತ ಹೆಚ್ಚಾಗಿ ದೀರ್ಘಾವಧಿಯ ಪರಿಣಾಮಗಳು ಮತ್ತು ಪ್ರತಿಕ್ರಿಯೆಗಳನ್ನು ಅಳೆಯುವುದು.',
    mlTitle: 'സെക്കൻഡ് ഓർഡർ തിങ്കിംഗ്',
    mlSummary: 'ഒരു തീരുമാനത്തിൻ്റെ പെട്ടെന്നുള്ള ഫലം മാത്രമല്ല, തുടർന്നുണ്ടാകുന്ന അനന്തരഫലങ്ങളും മുൻകൂട്ടി കാണൽ.',
    bnTitle: 'সেকেন্ড-অর্ডার থিঙ্কিং',
    bnSummary: 'তাৎক্ষণিক ফলাফলের বাইরে গিয়ে সিদ্ধান্তের দীর্ঘমেয়াদী ও পরোক্ষ প্রভাবের গভীর বিশ্লেষণ।',
    paTitle: 'ਦੂਜੇ ਦਰਜੇ ਦੀ ਸੋਚ (Second-Order Thinking)',
    paSummary: 'ਤੁਰੰਤ ਨਤੀਜਿਆਂ ਤੋਂ ਪਰੇ ਫੈਸਲੇ ਦੇ ਦੂਰਗਾਮੀ ਪ੍ਰਭਾਵਾਂ ਅਤੇ ਨਤੀਜਿਆਂ ਦੀ ਪੜਚੋਲ ਕਰਨਾ।',
    urTitle: 'دوسرے درجے کی سوچ (Second-Order Thinking)',
    urSummary: 'کسی فیصلے کے فوری اثر سے آگے بڑھ کر طویل مدتی نتائج اور ردعمل کو سمجھنا۔',
    orTitle: 'ସେକେଣ୍ଡ୍-ଅର୍ଡର ଚିନ୍ତାଧାରା',
    orSummary: 'ତତ୍କାଳ ଫଳାଫଳ ବଦଳରେ ଦୀର୍ଘକାଳୀନ ପ୍ରଭାବ ଓ ପରିଣାମର ଆକଳନ।',
    asTitle: 'দ্বিতীয় ক্ৰমৰ চিন্তা (Second-Order Thinking)',
    asSummary: 'সিদ্ধান্তৰ তাৎক্ষণিক ফলৰ বাহিৰেও সুদূৰপ্ৰসাৰী ফলাফলসমূহ অনুধাৱন কৰা।',
    citationAuthors: 'Marks, H.',
    citationYear: 2011,
    citationJournal: 'The Most Important Thing: Uncommon Sense for the Thoughtful Investor',
    citationDoi: 'https://doi.org/10.7312/mark15348',
    caseTitle: 'The Unintended Cobra Bounty in Colonial Delhi',
    caseDomain: 'general',
    caseSituation: 'The British administration in colonial Delhi offered a cash bounty for every dead cobra to eliminate venomous snakes.',
    caseOutcome: 'First-order thinkers assumed snakes would vanish; second-order enterprising citizens began breeding cobras in basements for profit.',
    caseFix: 'When designing policies or team incentives, map out how rational actors will game the metric before deployment.'
  }
];

export function runExpansion() {
  console.log(`Starting generation of ${EXPANDED_TOPICS_REMAINING.length} expanded topics across remaining tracks...`);
  for (const t of EXPANDED_TOPICS_REMAINING) {
    const filePath = path.join(topicsDir, t.fileName);
    const code = renderTopicFile(t);
    fs.writeFileSync(filePath, code, 'utf-8');
    console.log(`✓ Wrote ${t.fileName} (${t.id})`);
  }
  console.log('All remaining track expansion files written successfully.');
}

if (require.main === module) {
  runExpansion();
}
