import { TopicBlueprint } from './generateExpandedCurriculum';

export const SOCIAL_PSYCHOLOGY_BLUEPRINTS: TopicBlueprint[] = [
  // 6. Social Loafing
  {
    fileName: 'socialLoafing.ts',
    varName: 'social_loafing',
    id: 'social_loafing',
    categoryId: 'social_psychology',
    slug: 'social-loafing',
    difficulty: 'beginner',
    readTime: 5,
    sortWeight: 6,
    titleEn: 'Social Loafing: The Ringelmann Effect and Free-Riding in Groups',
    subtitle: 'Why individuals exert substantially less physical and mental effort when working in a team than when working alone.',
    shortDescEn: 'The psychological tendency for individuals to expend less effort on a task when working collectively as part of a group compared to when working alone.',
    oneLineEn: 'Assuming others in the team will pull the weight, so individual output quietly drops.',
    summary30sEn: 'First discovered in rope-pulling experiments by Max Ringelmann in 1913, Social Loafing shows that as group size increases, individual effort drops dramatically. When people feel their individual contributions cannot be identified, their motivation and energy decrease because accountability is diffused across the collective.',
    coreConceptEn: 'Social loafing is driven by evaluation diffusion and perceived dispensability. In individual work, performance is 100% visible and tied to self-esteem and accountability. In a team without granular individual metrics, members experience the "free-rider effect" (relying on conscientious teammates) or the "sucker effect" (withholding effort to avoid being taken advantage of by slackers).',
    summary60sEn: 'In a 1979 landmark study by Bibb Latané and colleagues, participants were asked to shout and clap as loud as possible. When individuals believed they were shouting in a group of six, they produced only one-third of the sound output compared to shouting alone, even when blindfolded and wearing noise-canceling headphones. The drop was completely unconscious and purely psychological.',
    takeawaysEn: [
      'The Ringelmann Curve: Group performance increases at a diminishing rate as individual output siphons off',
      'The Free-Rider Instinct: When rewards are shared equally regardless of input, effort drops',
      'The Sucker Effect: High performers deliberately slow down when they notice peers slacking',
      'Granular Accountability Antidote: Make every individual\'s output measurable and publicly visible',
    ],
    whyItHappensEn: 'Reduced evaluation apprehension and moral dispersion. When individual contributions cannot be separated from the total pool, social pressure drops and cognitive energy is conserved.',
    evolutionaryEn: 'In ancestral foraging bands, conserving metabolic calories during shared communal tasks was advantageous as long as the group achieved the minimum baseline threshold.',
    howItWorksEn: 'Group is formed -> Individual roles are left vague -> Output is evaluated only as a collective total -> High performers carry the workload -> Low performers fade into the background -> Overall group efficiency deteriorates.',
    whereEn: 'College group projects, corporate brainstorming meetings, open-source pull requests, joint household chores, and committee governance.',
    headlineEn: 'Individual Effort vs. Group Dilution',
    analogySideALabelEn: 'Solo Accountability (100% Visible)',
    analogySideADetailEn: '"Every line of code and every deliverable is tied directly to my name; I must perform."',
    analogySideBLabelEn: 'Collective Group (Diffused Output)',
    analogySideBDetailEn: '"There are 8 of us on this project; if I don\'t finish this slide tonight, someone else will handle it."',
    researchSummaryEn: 'Latané, Williams & Harkins (1979) published "Many hands make light the work," proving that social loafing occurs across cognitive, creative, and physical tasks whenever individual contribution is unidentifiable.',
    scenarioTitleEn: 'The College Capstone Project in Pune',
    scenarioVignetteEn: 'A team of five final-year computer science students in Pune is assigned a semester-long project. Rahul and Sneha write 95% of the backend and frontend code. The other three teammates skip meetings, submit plagiarized documentation slides, and promise to "handle the final presentation." At graduation evaluation, the whole team receives an "A" grade equally, leaving Rahul and Sneha feeling exploited and burnt out.',
    scenarioBreakdownEn: 'Classic social loafing compounded by the sucker effect. The absence of individual peer-evaluated scorecards allowed three members to free-ride on the high conscientiousness of two students.',
    scenarioActionEn: 'Implement Git commit tracking and peer contribution matrices where 40% of the final score is determined by anonymous intra-team rubric ratings.',
    pqContextEn: 'An IT consultancy in Hyderabad notices that moving developers from individual solo feature branches into a shared 10-person "general backlog swarm" resulted in a 35% decrease in overall tickets completed per engineer.',
    pqPromptEn: 'Which intervention directly counteracts the core psychological driver of Social Loafing in this team?',
    pqOptA: 'Offering a collective pizza party if the entire 10-person team hits the milestone',
    pqOptB: 'Assigning explicit single-owner tickets and reviewing individual commit velocity in weekly 1-on-1s',
    pqOptC: 'Increasing the size of the team to 15 engineers to handle the ticket volume',
    pqOptD: 'Sending daily motivational emails emphasizing the importance of team spirit',
    pqCorrect: 'opt_b',
    pqExplanation: 'Social loafing is dissolved when individual contributions are clearly delineated, measurable, and tied to personal accountability rather than hidden behind collective obscurity.',
    pqTakeaway: 'Visibility dissolves loafing: whenever individual input is identifiable, social loafing drops to zero.',
    authorYear: 'Latané, Williams & Harkins (1979)',
    refTitle: 'Many hands make light the work: The causes and consequences of social loafing',
    refCitation: 'Latané, B., Williams, K., & Harkins, S. (1979). Journal of Personality and Social Psychology, 37(6), 822–832.',
    doi: '10.1037/0022-3514.37.6.822',
    relatedA: { topicId: 'bystander_effect', slug: 'bystander-effect', title: 'Bystander Effect' },
    relatedB: { topicId: 'social_proof', slug: 'social-proof', title: 'Social Proof' },

    titleHinglish: 'Social Loafing: Team Me Kaam Chori Aur Free-Riding Ka Psychology',
    subtitleHinglish: 'Jab log akele kaam karte hain toh poori jaan lagate hain, par group me aate hi effort kyu kam ho jata hai?',
    shortDescHinglish: 'Group me kaam karte waqt individual mehnat ka achanak kam ho jana kyunki lagta hai ki koi aur sambhal lega.',
    oneLineHinglish: 'Bheed me chupkar aaram karna: "Baaki log toh kar hi rahe hain, mere akele se kya farak padega."',
    summary30sHinglish: '1913 me Max Ringelmann ne dekha ki rassi kheenchne ke game me akele aadmi ne jitni taqat lagayi, 8 logo ke group me har ek ki taqat aadhe se bhi kam reh gayi. Ise Social Loafing kehte hain: jab hamari akele ki mehnat track nahi hoti, toh dimaag bina bataye energy bachana shuru kar deta hai.',
    coreConceptHinglish: 'Social loafing ke do mukhya kaaran hote hain: Free-rider effect (doosro ki mehnat par credit lena) aur Sucker effect (jab hard workers dekhte hain ki baaki aaram kar rahe hain, toh wo bhi apna effort gira dete hain).',
    takeawaysHinglish: [
      'Team ka size jitna bada hoga, har insaan ka individual effort utna hi kam hoga',
      'Free-Rider Problem: Jab credit sabko barabar milta hai, toh log shortcut dhundte hain',
      'Sucker Effect: Mehanti log bhi dheere-dheere kaam karna kam kar dete hain',
      'Solution: Har bande ka kaam alag aur clearly visible hona chahiye',
    ],

    hiTitle: 'सामाजिक अकर्मण्यता (Social Loafing): समूह में व्यक्तिगत प्रयास की कमी',
    hiSummary: 'जब व्यक्ति किसी समूह में मिलकर काम करता है, तो वह अकेले काम करने की तुलना में काफी कम मेहनत और ऊर्जा खर्च करता है। इसे रिंगेलमैन प्रभाव कहा जाता है।',
    hiTakeaways: ['समूह में उत्तरदायित्व का बिखराव', 'व्यक्तिगत योगदान की माप आवश्यक', 'मुफ्तखोरी की प्रवृत्ति से बचाव'],

    guTitle: 'સોશિયલ લોફિંગ: જૂથમાં વ્યક્તિગત પ્રયાસોમાં ઘટાડો',
    guSummary: 'જ્યારે લોકો જૂથમાં કામ કરે છે ત્યારે વ્યક્તિગત પ્રયાસો આપમેળે ઘટી જાય છે કારણ કે જવાબદારી વહેંચાઈ જાય છે.',

    mrTitle: 'सोशल लोफिंग: समूहात काम करताना वैयक्तिक प्रयत्नांची चोरी',
    mrSummary: 'एकट्याने काम करताना जितकी मेहनत घेतली जाते, तितकी समूहात घेतली जात नाही. वैयक्तिक मोजमाप नसल्याने ही प्रवृत्ती वाढते.',

    teTitle: 'సోషల్ లోఫింగ్: సమూహంలో వ్యక్తిగత ప్రయత్నం తగ్గడం',
    teSummary: 'వ్యక్తిగతంగా కాకుండా బృందంలో పనిచేస్తున్నప్పుడు శ్రమను తగ్గించే మానసిక ప్రవృత్తి.',

    taTitle: 'சமூக சோம்பல் (Social Loafing): குழுவில் உழைப்பைக் குறைக்கும் உளவியல்',
    taSummary: 'தனியாக உழைக்கும் போது காட்டும் தீவிரத்தை குழுவில் இருக்கும் போது மக்கள் காட்டுவதில்லை.',

    knTitle: 'ಸಾಮಾಜಿಕ ಸೋಮಾರಿತನ: ಗುಂಪಿನಲ್ಲಿ ವೈಯಕ್ತಿಕ ಶ್ರಮ ಕುಸಿಯುವ ಪ್ರವೃತ್ತಿ',
    knSummary: 'ಗುಂಪಿನಲ್ಲಿ ಕೆಲಸ ಮಾಡುವಾಗ ಪ್ರತಿಯೊಬ್ಬರ ವೈಯಕ್ತಿಕ ಪರಿಶ್ರಮ ಕಡಿಮೆಯಾಗುವ ಮಾನಸಿಕ ವಿದ್ಯಮಾನ.',

    mlTitle: 'സോഷ്യൽ ലോഫിംഗ്: കൂട്ടായ്മയിൽ അധ്വാനം കുറയ്ക്കുന്ന സ്വഭാവം',
    mlSummary: 'ഗ്രൂപ്പിൽ പ്രവർത്തിക്കുമ്പോൾ വ്യക്തിഗതമായ പരിശ്രമം കുറയുന്ന പ്രവണതയാണിത്.',

    bnTitle: 'সোশ্যাল লোফিং: দলবদ্ধ কাজে ব্যক্তিগত প্রচেষ্টার ঘাটতি',
    bnSummary: 'দলে কাজ করার সময় প্রত্যেকে নিজের সম্পূর্ণ পরিশ্রম না দিয়ে অন্যদের ওপর নির্ভর করার প্রবণতা।',

    paTitle: 'ਸੋਸ਼ਲ ਲੋਫਿੰਗ: ਸਮੂਹ ਵਿੱਚ ਨਿੱਜੀ ਮਿਹਨਤ ਘਟਾਉਣ ਦੀ ਪ੍ਰਵਿਰਤੀ',
    paSummary: 'ਇਕੱਲੇ ਕੰਮ ਕਰਨ ਦੇ ਮੁਕਾਬਲੇ ਗਰੁੱਪ ਵਿੱਚ ਵਿਅਕਤੀ ਦਾ ਯੋਗਦਾਨ ਘੱਟ ਜਾਣ ਦੀ ਮਨੋਵਿਗਿਆਨਕ ਆਦਤ।',

    urTitle: 'سوشل لوفنگ: گروہ میں انفرادی محنت کی کمی',
    urSummary: 'جب لوگ گروہ میں کام کرتے ہیں تو وہ انفرادی سطح کے مقابلے میں کم محنت اور توجہ صرف کرتے ہیں۔',

    orTitle: 'ସୋସିଆଲ୍ ଲୋଫିଂ: ଗୋଷ୍ଠୀଗତ କାର୍ଯ୍ୟରେ ବ୍ୟକ୍ତିଗତ ପରିଶ୍ରମ ହ୍ରାସ',
    orSummary: 'ଏକାକୀ କାମ କରିବା ତୁଳନାରେ ଗୋଷ୍ଠୀରେ କାମ କଲାବେଳେ ଲୋକେ କମ୍ ଶ୍ରମ ପ୍ରୟୋଗ କରିବାର ମାନସିକତା।',

    asTitle: 'ছচিয়েল লোফিং: দলীয় কামত ব্যক্তিগত পৰিশ্ৰম হ্ৰাস পোৱাৰ মানসিকতা',
    asSummary: 'দলত কাম কৰাৰ সময়ত ব্যক্তিগত দায়িত্ব এৰাই চলি কম পৰিশ্ৰম কৰাৰ মানসিক প্ৰৱণতা।',
  },

  // 7. Groupthink
  {
    fileName: 'groupthink.ts',
    varName: 'groupthink',
    id: 'groupthink',
    categoryId: 'social_psychology',
    slug: 'groupthink',
    difficulty: 'intermediate',
    readTime: 6,
    sortWeight: 7,
    titleEn: 'Groupthink: Why Highly Cohesive Teams Make Disastrous Decisions',
    subtitle: 'The psychological drive for harmony and consensus that suppresses dissent, ignores risks, and leads to organizational catastrophe.',
    shortDescEn: 'A mode of thinking where the desire for harmony or conformity in a group results in irrational or dysfunctional decision-making outcomes.',
    oneLineEn: 'Valuing peace in the room above the objective truth of the decision.',
    summary30sEn: 'Coined by psychologist Irving Janis in 1972, Groupthink occurs when a team prioritizes politeness, unanimity, and mutual agreement over rigorous critical evaluation. Dissenting voices self-censor out of fear of social friction, creating an artificial "illusion of invulnerability" that leads to catastrophic failures like corporate bankruptcies and strategic disasters.',
    coreConceptEn: 'Groupthink thrives in high-pressure, insular teams with charismatic leaders. Eight primary symptoms define it: (1) Illusion of invulnerability; (2) Collective rationalization; (3) Unquestioned belief in inherent morality; (4) Stereotyped outgroup views; (5) Direct pressure on dissenters; (6) Self-censorship; (7) Illusion of unanimity; (8) Self-appointed "mindguards" who shield the leader from contradictory information.',
    summary60sEn: 'Janis analyzed historical catastrophes such as the Bay of Pigs invasion and the Challenger space shuttle launch. Engineers warned that the shuttle\'s O-rings would fail in freezing temperatures, but under intense NASA launch deadline pressure, managers demanded: "Take off your engineering hat and put on your management hat." The pressure for collective consensus killed all seven astronauts.',
    takeawaysEn: [
      'Illusion of Unanimity: Silence in the room is falsely interpreted as 100% agreement',
      'Mindguards: Eager deputies who actively suppress negative data before it reaches the boss',
      'The Self-Censorship Spiral: Individuals swallow valid doubts to avoid being labeled "unsupportive"',
      'Designated Devil\'s Advocate: Formally assigning team members to attack every consensus proposal',
    ],
    whyItHappensEn: 'Social cohesion protection and stress reduction. Challenging a dominant group consensus triggers amygdala activation and acute fear of social ostracization.',
    evolutionaryEn: 'In ancestral tribes, maintaining united group solidarity against rival predators was often more critical for immediate survival than endless analytical deliberation.',
    howItWorksEn: 'Charismatic leader announces preferred direction -> Team members nod agreeably -> Doubter A feels uneasy but stays silent -> Doubter B sees Doubter A\'s silence and suppresses their own concern -> The plan is approved unanimously -> Catastrophe strikes.',
    whereEn: 'Corporate boardroom acquisitions, startup strategy pivots, political cabinets, medical surgical teams, and family council disputes.',
    headlineEn: 'Groupthink vs. Independent Red Teaming',
    analogySideALabelEn: 'Groupthink Trap',
    analogySideADetailEn: '"Everyone seems to agree with the CEO\'s expansion plan; raising risks now will just brand me as negative."',
    analogySideBLabelEn: 'Cognitively Calibrated Team',
    analogySideBDetailEn: '"Let\'s appoint a Red Team specifically incentivized to break this thesis before we invest capital."',
    researchSummaryEn: 'Irving Janis (1972, 1982) demonstrated that high group cohesiveness coupled with structural insulation and directive leadership consistently produces defective decision outcomes.',
    scenarioTitleEn: 'The Mumbai NBFC Lending Disaster',
    scenarioVignetteEn: 'The executive committee of a prominent non-banking financial company in Mumbai meets to approve an aggressive ₹2,000-crore commercial real estate loan. The Managing Director is visibly enthusiastic. A junior risk analyst notices that the builder has multiple shell companies and debt covenants are paper-thin. When he timidly clears his throat, a senior director snaps: "Are you questioning our biggest promoter relationship?" The analyst falls silent. The loan is approved unanimously. Eighteen months later, the builder defaults, wiping out 40% of the NBFC\'s equity.',
    scenarioBreakdownEn: 'Textbook Groupthink. Directive leadership and fear of challenging authority created an environment where silence was treated as unanimous consensus, silencing crucial empirical risk data.',
    scenarioActionEn: 'Implement anonymous written risk submissions and mandate a formal "Pre-Mortem" where the committee assumes default has already happened and analyzes causes.',
    pqContextEn: 'A fintech executive team in Bangalore is voting on acquiring a competitor. The CEO is passionately in favor. Every department head nods and agrees during the round-robin discussion, despite multiple private misgivings.',
    pqPromptEn: 'Which practice is most effective at preventing Groupthink from corrupting this acquisition vote?',
    pqOptA: 'Having the CEO speak first and passionately outline the vision so everyone understands the goal',
    pqOptB: 'Mandating that the CEO speaks LAST, and requiring an independent "Devil\'s Advocate" team to present the failure case',
    pqOptC: 'Taking a public show of hands at the very beginning of the meeting',
    pqOptD: 'Encouraging everyone to maintain a positive, cooperative, and optimistic team spirit',
    pqCorrect: 'opt_b',
    pqExplanation: 'Having leadership state preferences last and formally institutionalizing dissent (Devil\'s Advocate) removes the social penalty for voicing critical concerns.',
    pqTakeaway: 'When everyone thinks alike, nobody is thinking: formal dissent protocols save teams from disaster.',
    authorYear: 'Irving L. Janis (1972)',
    refTitle: 'Victims of Groupthink: A psychological study of foreign-policy decisions and fiascoes',
    refCitation: 'Janis, I. L. (1972). Victims of Groupthink. Boston: Houghton Mifflin.',
    doi: '10.1177/002216788302300412',
    relatedA: { topicId: 'conformity_asch_effect', slug: 'conformity-asch-effect', title: 'Conformity (Asch Effect)' },
    relatedB: { topicId: 'confirmation_bias', slug: 'confirmation-bias', title: 'Confirmation Bias' },

    titleHinglish: 'Groupthink: Intelligent Log Milkar Bewakoofi Bhare Faisle Kyu Lete Hain?',
    subtitleHinglish: 'Meeting me sab ek doosre ki haan me haan milate hain, aur koi sach bolkar dushmani nahi lena chahta.',
    shortDescHinglish: 'Group me sabke sath agree karne aur ladai se bachne ki aisi aadat jo poori team ko galat faisla lene par majboor kar deti hai.',
    oneLineHinglish: 'Meeting me shanti banaye rakhne ke chakkar me sachai ko dafan kar dena.',
    summary30sHinglish: 'Irving Janis ne 1972 me Groupthink concept diya. Jab kisi team me boss bohot assertive hota hai aur log disagreement se darte hain, toh koi bhi khatra point out nahi karta. Har koi sochta hai: "Baaki sab chup hain toh shayad main hi galat hoon." Is fake unity ke chakkar me lakho karodo ke loss ho jate hain.',
    coreConceptHinglish: 'Groupthink tab hota hai jab unity aur politeness ko facts aur analysis ke upar rakh diya jata hai. Isme "Mindguards" hote hain jo boss tak buri khabar nahi pahunchne dete, aur log khud hi apne valid sawaalo ko pee jaate hain (Self-censorship).',
    takeawaysHinglish: [
      'Chuppi ka matlab agreement nahi hota: Log aksar dar ke maare chup rehte hain',
      'Boss ki pehle opinion aana dangerous hai: Leader ko hamesha aakhiri me bolna chahiye',
      'Devil\'s Advocate: Meeting me ek bande ka kaam officially flaws dhundna hona chahiye',
      'Anonymous Feedback: Sensitive matters par secret voting karwani chahiye',
    ],

    hiTitle: 'ग्रुपथिंक (Groupthink): अत्यधिक सामूहिकता से उपजे विनाशकारी निर्णय',
    hiSummary: 'जब किसी समूह में मतभेदों से बचने और सहमति बनाए रखने की तीव्र इच्छा निष्पक्ष विश्लेषण और तार्किक सोच पर हावी हो जाती है, तो बड़े पैमाने पर गलत फैसले होते हैं।',
    hiTakeaways: ['सहमति का कृत्रिम भ्रम', 'असहमति का दमन न करें', 'डेविल्स एडवोकेट की भूमिका अनिवार्य'],

    guTitle: 'ગ્રુપથિંક: જૂથની એકરૂપતામાં ખોટા નિર્ણયો લેવાની ભૂલ',
    guSummary: 'સંવાદિતા અને સહમતિ જાળવવાના દબાણમાં જ્યારે ટીમ સાચા જોખમોની અવગણના કરે છે ત્યારે વિનાશક નિર્ણયો લેવાય છે.',

    mrTitle: 'ग्रुपथिंक: समूहाच्या दबावातून होणारे चुकीचे निर्णय',
    mrSummary: 'एकमत दाखवण्याच्या नादात जेव्हा लोक खरी वस्तुस्थिती सांगणे टाळतात, तेव्हा संस्थांचे प्रचंड नुकसान होते.',

    teTitle: 'గ్రూప్‌థింక్: సమూహ సామరస్యం కోసం తప్పుడు నిర్ణయాలు తీసుకోవడం',
    teSummary: 'విబేధాలను అణచివేసి అందరితో ఏకీభవించాలనే కోరిక వినాశకరమైన ఫలితాలకు దారితీస్తుంది.',

    taTitle: 'குழுச்சிந்தனை (Groupthink): சமரசத்தால் ஏற்படும் தவறான முடிவுகள்',
    taSummary: 'குழுவில் உள்ள அனைவருடனும் ஒத்துப்போக வேண்டும் என்ற கட்டாயத்தில் உண்மையான இடர்களை புறக்கணிக்கும் நிலை.',

    knTitle: 'ಗ್ರೂಪ್‌ಥಿಂಕ್: ಗುಂಪಿನ ಸಾಮರಸ್ಯಕ್ಕಾಗಿ ತಪ್ಪು ನಿರ್ಧಾರಗಳನ್ನು ಕೈಗೊಳ್ಳುವುದು',
    knSummary: 'ಭಿನ್ನಾಭಿಪ್ರಾಯಗಳನ್ನು ಮರೆಮಾಚಿ ಎಲ್ಲರೂ ಒಪ್ಪಿಕೊಂಡಂತೆ ನಟಿಸುವುದರಿಂದ ದುರಂತಮಯ ಫಲಿತಾಂಶಗಳು ಉಂಟಾಗುತ್ತವೆ.',

    mlTitle: 'ഗ്രൂപ്പ്തിങ്ക്: വിയോജിപ്പുകൾ ഒതുക്കിവെച്ച് കൂട്ടത്തോടെ തെറ്റായ തീരുമാനങ്ങൾ എടുക്കൽ',
    mlSummary: 'ഗ്രൂപ്പിലെ സമാധാനം നിലനിർത്താൻ ശരിയായ സംശയങ്ങൾ പ്രകടിപ്പിക്കാതെ ഇരിക്കുന്നത് വൻ പരാജയങ്ങൾക്ക് വഴിവെക്കുന്നു.',

    bnTitle: 'গ্রুপথিংক: দলের ঐকমত্য বজায় রাখতে গিয়ে ভুল সিদ্ধান্ত নেওয়ার ফাঁদ',
    bnSummary: 'দলে বিরোধ এড়াতে গিয়ে যৌক্তিক সমালোচনা বন্ধ করে দিলে মারাত্মক বিপর্যয় ঘটে।',

    paTitle: 'ਗਰੁੱਪਥਿੰਕ: ਸਹਿਮਤੀ ਦੇ ਚੱਕਰ ਵਿੱਚ ਲਏ ਜਾਣ ਵਾਲੇ ਵਿਨਾਸ਼ਕਾਰੀ ਫੈਸਲੇ',
    paSummary: 'ਜਦੋਂ ਟੀਮ ਵਿੱਚ ਬਹਿਸ ਤੋਂ ਬਚਣ ਲਈ ਸਾਰੇ ਇੱਕੋ ਗੱਲ ਨਾਲ ਸਹਿਮਤ ਹੋ ਜਾਂਦੇ ਹਨ ਅਤੇ ਜੋਖਮਾਂ ਨੂੰ ਅਣਦੇਖਾ ਕਰ ਦਿੰਦੇ ਹਨ।',

    urTitle: 'گروپ تھنک: اتحاد کے دباؤ میں اجتماعی غلط فیصلے',
    urSummary: 'جب کسی گروہ میں ہم آہنگی برقرار رکھنے کی خواہش آزادانہ اور تنقیدی سوچ پر غالب آ جاتی ہے تو تباہ کن نتائج برآمد ہوتے ہیں۔',

    orTitle: 'ଗ୍ରୁପ୍‌ଥିଙ୍କ୍: ଗୋଷ୍ଠୀ ସହମତି ପାଇଁ ଭୁଲ୍ ନିଷ୍ପତ୍ତି ନେବାର ମନସ୍ତତ୍ତ୍ୱ',
    orSummary: 'ଦଳରେ ବିବାଦ ଏଡ଼ାଇବା ପାଇଁ ସତ୍ୟ ତଥ୍ୟକୁ ଲୁଚାଇ ରଖି ସମସ୍ତେ ସହମତ ହେବାର ଭୟଙ୍କର ପରିଣାମ।',

    asTitle: 'গ্ৰুপথিঙ্ক: দলীয় ঐক্য ৰক্ষাৰ স্বাৰ্থত ভুল সিদ্ধান্ত গ্ৰহণৰ প্ৰৱণতা',
    asSummary: 'দলত বিৰোধিতাৰ ভয়ত নিজৰ সঠিক সন্দেহ ব্যক্ত নকৰাৰ ফলত সৃষ্টি হোৱা ভুল সিদ্ধান্ত।',
  },
];
